### ISSUE TITLE
cmd-ref: document update with revision specified

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1001]
https://github.com/iterative/dvc/pull/3337 was merged.  We need to update Command Reference and perhaps mention this feature on User Guide as well.

**Comment by jorgeorpinel** [comment]
@skshetry thanks. In case you're not fully aware of the current process, please just send a PR (it can be draft or §normal but please use a branch directly on this repo) with some basic changes in all the appropriate docs you can find that are relevant to this but don't worry too much about the language if you're not interested in writing docs, we'll take over based on your suggestions. There's also this resourece about it: https://github.com/iterative/dvc.org/wiki/2.-dvc.org-pull-requests-for-core-repo-changes Thanks!
