### ISSUE TITLE
cmd ref: update get/import to explain how to use ganularity in target paths

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1011]
To match iterative/dvc/pull/3309

**Comment by jorgeorpinel** [comment]
This is relatively old. We should probably prioritize for soon after the 1.0 release. (Someone asked on Discord.)

**Comment by johan-sightic** [comment]
Does this mean it its possible to dvc import a subset from a dvc tracked directory?

**Comment by dberenbaum** [comment]
Sorry for the delayed reply @johan-sightic. In case you were still wondering, yes it's possible.

**Comment by dberenbaum** [comment]
I think it's already mentioned:

> The path argument specifies a file or directory to download (paths inside tracked directories are supported

Not sure if there's any more explanation needed here. Closing for now but open to suggestions.
