### ISSUE TITLE
cmd-ref: document gc changes

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1013]
PR https://github.com/iterative/dvc/pull/3363 is under review. After this is merged, the docs for `gc` will need adjustments.

**Comment by jorgeorpinel** [comment]
A corresponding draft PR in this repo would be best @skshetry, to hep avoid docs going out of sync. Please see https://github.com/iterative/dvc.org/wiki/2.-dvc.org-pull-requests-for-core-repo-changes. Thanks!
