### ISSUE TITLE
doc urls

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#102]
`https://dvc.org/doc`
`https://dvc.org/docs`
`https://dvc.org/doc111111`

All pages started from `doc` show the docs which is great. It might look even better if we just redirect to a single url like `https://dvc.org/doc`.

**Comment by shcheklein** [comment]
fixed!

**Comment by dmpetrov** [comment]
Thank you!

**Comment by shcheklein** [comment]
👍
