### ISSUE TITLE
api: UI improvements

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1028]
> Emanates from #908

- [ ] Support ```py Markdown highlighter (code blocks)

- [ ] Automatic link to function names in back quotes (similar to command names) to their api ref. Eg. `` `dvc.api.read()` ``  -> /doc/api-reference/read

- ~~(maybe) special CSS for first `<h3>` (`###`) in api ref pages, currently used as title~~ No longer needed, see https://github.com/iterative/dvc.org/pull/908#issuecomment-593167171.

- [ ] Better way to show what literals in example code blocks evaluate to. Currently `print()` is used in the block, then a `---` (`<hr>`) and a following block quote (```dvc) shows what the output of running the script would do:
  ![image](https://user-images.githubusercontent.com/1477535/75638572-1b82ed80-5bf2-11ea-9248-ad41eb71a564.png)

**Comment by shcheklein** [comment]
Closing in favor of https://github.com/iterative/dvc.org/issues/910 ... everything else is solved more or less I believe
