### ISSUE TITLE
guide: using NFS as a remote storage

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#103]
I.e. mount it to some dir and specify it as a local dir repository for dvc.

Related to https://github.com/iterative/dvc.org/issues/4303

**Comment by dashohoxha** [comment]
I have generalized this as "Mounted DVC Storage", which includes not only NFS, but also SSHFS, Samba, or any other data storage that can be network-mounted on a local directory.

I have also built an interactive example that explains how to do it for SSHFS (since this is easier to set up for an interactive example): https://katacoda.com/dvc/courses/examples/mounted-storage

**Comment by jorgeorpinel** [comment]
@efiop did you mean in https://dvc.org/doc/command-reference/remote/add though? Or somewhere else.

**Comment by efiop** [comment]
@jorgeorpinel I guess a note there would also be pretty nice as a way of using any storage that you can mount to your local fs.

**Comment by jorgeorpinel** [comment]
OK. So while #784 greatly simplifies this issue, it won't completely solve it. I'm updating the PR's description to remove the link. Or if you prefer to also add the note Ruslan suggests Dashamir, please reestablish the link to close this issue automatically from your PR. 🙂

**Comment by iesahin** [comment]
I read the comments in #784. Is there anything that should be done here?

**Comment by shcheklein** [comment]
It feels that we don't have a perfect place at the moment to put this note. I think there should be something about remotes in the User Guide in the first place. Starting from basic concepts, expanding into a proper section, where we can put a note in the introductory part about "Unsupported directly remotes" with a solutions like sshfs, mounted NFS, etc. For now, we can probably create a section and a note in the existing `remote add`, `remote modify`, `remote index` with the same meaning.

**Comment by jorgeorpinel** [comment]
QQ @dberenbaum: This has a low priority now but https://github.com/iterative/dvc.org/issues/4303 (part of this one) a high priority. 🤔 Does that mean you want to focus on the latter without addressing the former (this one) ?

**Comment by dberenbaum** [comment]
@jorgeorpinel In https://dvc.org/doc/user-guide/data-management/remote-storage#file-systems-local-remotes, you added:

> You can also use system directories, mounted drives, network resources e.g. network-attached storage (NAS), and other external devices as storage. 

Is that enough to close this one? Do we need anything else for this issue specifically?

**Comment by jorgeorpinel** [comment]
Maybe just add "mounted drives (e.g. NFS)" (link to https://nfs.sourceforge.net/ ?) unless the intention here was specifically about NFS for some reason, and not in general any mounted drives. Note that there are NFS-specific notes in the config options `state.dir` and `index.dir`.
