### ISSUE TITLE
guide: add more links to the .dvcignore guide from other docs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1033]
To help increase awareness about this feature!

> Per https://github.com/iterative/dvc/pull/3257#discussion_r385531995

UPDATE: Here's a non-inclusive list of some ideas of the most obvious places where mentions of .dvcignore should exist. Each one could be addressed in different PRs:

- [x] Definitely in the description of https://dvc.org/doc/command-reference/add, and maybe add an example (not sure) which could be copied from [these](https://dvc.org/doc/user-guide/dvcignore#examples). Check how dvcignore interacts with `dvc move` - #1346
- [ ] Note that the `.hg/` dir is ignored by default along with .git/ (in git-enabled DVC repos), per same discussion. This can go in https://dvc.org/doc/command-reference/init
- [ ] See how .dvcignore interacts with `dvc checkout` and `dvc pull`
- [ ] ^ Same for `dvc list`, `dvc get`, and `dvc import`
- [ ] ^ Same for `metrics` and `plots`
- [ ] ^ `push` and `pull`...
- [ ] ^ etc. just go down the command reference 🙂 
- [ ] Maybe in a get-started page or tutorial? Just as a note with link (no need for actual example).

BTW if while attempting any of the above bugs or strange behavior arise, please ask in Discord or open an issue in the core repo (iterative/dvc)

**Comment by sarthakforwet** [comment]
Hey @jorgeorpinel  . As far as I got this all you mean to say is that we have to refer the https://dvc.org/doc/user-guide/dvcignore from other sections of DVC docs?

**Comment by jorgeorpinel** [comment]
Yes @sarthakforwet! You would first need to play with and fully understand the .dvcignore feature, then explore all the existing docs and try to find all the places where it would be appropriate to link to the .dvcignore guide.

But I see you're also interested in https://github.com/iterative/dvc.org/issues/1172#issuecomment-629842491, let's focus on a single one for now 🙂 please pick one and feel free to submit a PR to close it, thanks.

**Comment by utkarshsingh99** [comment]
If no one is on this issue, I would like to take it up. @jorgeorpinel

**Comment by jorgeorpinel** [comment]
@sarthakforwet are you still interested in this issue or #1172? Thanks

**Comment by jorgeorpinel** [comment]
> p.s. Both involve .dvcignore which I'm guessing you've studied already so at this point focusing on these is probably the best bet.

**Comment by jorgeorpinel** [comment]
Per https://github.com/iterative/dvc.org/pull/1328#issuecomment-632356316 this issue is too vague.

> write things we want to mention, use case we have in mind for people to be aware, write simple scripts to show those use case. So that we are on the same page

**Comment by jorgeorpinel** [comment]
OK updated the description to improve this issue. It's still vague but better. Following some of the checkboxes should get someone started with the bigger task.

**Comment by sarthakforwet** [comment]
@jorgeorpinel,  Yes, I am interested in both but unable to get #1172 correctly about what we have to do . Do we need to play with all external dependencies i.e SSH , Amazon S3 , Google Cloud Storage etc.. and check for them with respect to .dvcignore ?

**Comment by jorgeorpinel** [comment]
> Do we need to play with all external dependencies

No, you could just play with the most basic one i.e. an external directory path in the same file system.

But you're already doing PR #1346 so let's focus on that for now 🙂
