### ISSUE TITLE
replace global docserach with npm module

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#1046]
Right now we importing docsearch in `html.js`:

https://github.com/iterative/dvc.org/blob/0d886a14c60b697fe7648ebad5f3bc8b3a10b0b5/src/html.js#L16-L23

And it's not a very good place for it. We should either import is node package in Documenation component (but find out why it breaks ssr if we do it this way), or move to `gatsby-browser.js`

**Comment by pavelgrinchenko** [comment]
@iAdramelk I hadn't time to replace it via npm module, but it was refactored to asynchronous loading https://github.com/iterative/dvc.org/blob/c5b5d43f36b721c4036cdfa6852ff90ac2a8a575/src/components/Documentation/Layout/SearchForm/index.tsx#L17-L26

**Comment by jorgeorpinel** [comment]
Not sure this can be considered `migration` at this point, removed the flag for now.

**Comment by jorgeorpinel** [comment]
Closing since there's been no follow up from @iterative/websites to date but please re-open/update/plan if it's still relevant. Thanks
