### ISSUE TITLE
we need to purge CF cache on deployment

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1048]
Changes introduced to the caching layer for DVC blog affected DVC.org - we need to purge cache in the same as we do in blog.

**Comment by fabiosantoscode** [comment]
The script was added correctly, all that was missing was the environment variables with required cloudflare information for the script to consume.

Due to preview environments, it doesn't fail when these are missing.

I've added them now.

**Comment by shcheklein** [comment]
@fabiosantoscode 

> Due to preview environments, it doesn't fail when these are missing.

what about production? not sure I got the point ...

**Comment by fabiosantoscode** [comment]
> what about production? not sure I got the point ...

They both share `npm start`.

I can fix this by only running the script if `process.env.CONTEXT === 'production'` and crashing otherwise.

**Comment by shcheklein** [comment]
@fabiosantoscode still not sure I understand. It failed to clean the cache on prod, so not sure what  preview envs have to do with this?

**Comment by fabiosantoscode** [comment]
If there were no preview environments, I would've made it crash loudly when CF tokens are missing.

**Comment by shcheklein** [comment]
kk, got it ... I saw your PR and it makes sense - fail in prod if tokens are not set
