### ISSUE TITLE
Broken link to Files and Directories

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#105]
Link from our doc: https://dvc.org/doc/dvc-files-and-directories
But the page was moved to https://dvc.org/doc/user-guide/dvc-files-and-directories

Unfortunately, we don't know the exact source of the broken link.

**Comment by shcheklein** [comment]
@dmpetrov What do you mean by `Unfortunately, we don't know the exact source of the broken link.`?

I've fixed the link. Btw, it's pretty easy to fix it using the `Edit on Github` button on the top of each page.
