### ISSUE TITLE
nav: allow folding sidebar lists

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1052]
Some nav elements e.g. https://dvc.org/doc/command-reference have so many subelements that you have to scroll the left sidebar to see what other super sections are available, which new users may not even thing about doing. At the same time, the little arrow icon changes from pointing right to pointing down when you open any nav section that is expandable, which feels like if you click on it again it should fold back up. It would be nice if they did fold up so you can explore the overall structure of the docs without having to navigate to different sections.

**Comment by jorgeorpinel** [comment]
> when you open any nav section that is expandable

p.s. maybe also sections that do NOT have ay elements underneath should have a different bullet type, like just a round one, so you can tell from that which ones have children hierarchies to explore.

**Comment by shcheklein** [comment]
I thinks this has been done by @ashiishme .
