### ISSUE TITLE
image processing with Gatsby

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#1063]
When we used Next.js we just placed all assets to the `/static/img/` folder and inserted in html by url. 

This approach works, but have some drawbacks:

1. We can't automatically optimize images on build.
2. We don't have cache busting.
3. We can't crate different sizes of images for different resolutions on the fly.

Now, after migration we have better ways to do it:

1. Use webpack loaders for images to import images directly is js. It will give us cachebusting and otimizations on build.
2. Use gatsby image API to automatically resize images.
3. Use gatsby's plugin for remark that will automatically resize and optimize images in doc pages.

Also, as we don't need to make image folder public with this approach, we should move images closer to the components or markdown files that use them.

**Comment by shcheklein** [comment]
> Also, as we don't need to make image folder public with this approach, we should move images closer to the components or markdown files that use them.

this can be done independently and should resolve the problem with `gatsby-remark-relative-images` which is now pinned at 0.2.3 and which we can not update.

**Comment by jorgeorpinel** [comment]
I guess this is related to the Gatsby `migration` so will keep the label (last old issue with that label) but is it still relevant and/or can it maybe be implemented easily with the current version of Gatsby or some other module? Cc @rogermparent for ideas if any 🙂

**Comment by rogermparent** [comment]
> I guess this is related to the Gatsby `migration` so will keep the label (last old issue with that label) but is it still relevant and/or can it maybe be implemented easily with the current version of Gatsby or some other module? Cc @rogermparent for ideas if any slightly_smiling_face

We currently use an older version of the Gatsby image plugins due to issues with the new Caching API they introduced a while ago. There's been a lot of iterations on those plugins since then, so it may be worth trying an update in a PR to see if the cache behavior improvements also fixed our issue. If we are able to use the latest versions of those plugins, we'll get access to a slew of new features like that greatly improve DX like lazy queries/images and true parallel processing.

I can check into it when I get some time.

**Comment by shcheklein** [comment]
@rogermparent can it be considered done?

**Comment by rogermparent** [comment]
Yeah, this ticket specifically seems like it can be considered long since done after the Next -> Gatsby migration.
