### ISSUE TITLE
ci: restyled seems broken

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1064]
~~per https://github.com/iterative/dvc.org/pull/1058#pullrequestreview-376234425~~

Let's double check it's still working and that it can fix as much as possible from our format checks...

**Comment by jorgeorpinel** [comment]
Now Restyled seems completely removed from the repo. Maybe a recent merge guys? @iAdramelk @pavelgrinchenko @fabiosantoscode 

Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel it's not, we just need to update and make sure it works - https://github.com/iterative/dvc.org/blob/master/.restyled.yaml

**Comment by jorgeorpinel** [comment]
Yeah turns out someone added `stylelint` but it's not supported. I just removed it in 20c17baf5ce5c5e83096878a86c9da5260264299.

Should we add any others? Availeble ones: https://github.com/restyled-io/restyled.io/wiki/Available-Restylers

**Comment by shcheklein** [comment]
sounds good, I would not worry about even JS files to be honest ... mostly we should provide simple workflow for md files.

can we test it?

**Comment by shcheklein** [comment]
Fixed, see #1159
