### ISSUE TITLE
docs: add `dvc gc --projects`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#107]
https://github.com/iterative/dvc/issues/1300

**Comment by shcheklein** [comment]
Done https://dvc.org/doc/commands-reference/gc#options .

**Comment by johnyaku** [comment]
It's still a bit unclear how to actually use `--projects`.
None of the combinations of absolute or relative paths that I've tried have worked.
I get "not inside a DVC repository, checked up to mountpoint ..."

https://discordapp.com/channels/485586884165107732/1051668788925448224/1052471908358172692

**Comment by shcheklein** [comment]
It might be a regression then. Could you create a ticket on the DVC repo and share exact steps that you are doing please?
