### ISSUE TITLE
links check: getting 429 too many requests on CI

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1070]
https://circleci.com/gh/iterative/dvc.org/2626?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

@casperdcl should we ignore this and consider as 200?

**Comment by casperdcl** [comment]
Hmm looks like it. There's no easy way to avoid this.

Right now we process each file individually (makes it easy to associate errors with the correct file).

If instead we first grep links in all files, then process together we can avoid checking the same link multiple times - but it would be harder to associate errors with the originating file. Possible but a little bit of scripting involved.

At that stage I'd be tempted to create a separate repo for link checking and install it as a hook :)

For now maybe best to ignore 429?

**Comment by shcheklein** [comment]
yes, agreed - let's just ignore them
