### ISSUE TITLE
cmd ref: explain remote://myremote notation in `import` & `run`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#108]
- [x] import/get-url
- [ ] run
- [ ] add

**Comment by jorgeorpinel** [comment]
I don't see this in either cmd ref yet so I unchecked "import" above.

**Comment by efiop** [comment]
Also `dvc add remote://`

**Comment by jorgeorpinel** [comment]
> I unchecked "import" above.

Actually this only applies to import/get-url right? And it's explained in those already. So only `add` and `run` are pending (only mentioned for those in the external data guides ATM).

**Comment by jorgeorpinel** [comment]
> only mentioned for those in the external data guides

After reviewing the add and run refs I see they link to those guides in the appropriate places so I'm not seeing a need to explain `remote://` directly in them. We don't go over all the other URLs either. But lmk if you have a specific idea on how else to address this!
