### ISSUE TITLE
annoying delays on route change/navigate

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1092]
It's more or less random, usually just after you open the site.

You click to any internal link and nothing happens (for >500ms), after that page opens immediately - it's quite annoying since there is no response from the UI and it's not clear if I missed the link for example.

**Comment by pavelgrinchenko** [comment]
As I mentioned before we have strange TTFB for responses 
![image](https://user-images.githubusercontent.com/53296341/77620414-5bb46200-6f4b-11ea-9f87-6baf9890e479.png)
I don't know what server.js do and why it's so long, but what I really know that nobody serves static files through Node.js. Usually all use Nginx as reverse proxy before Node.js app for serving static files.
/cc @fabiosantoscode wdyt?

**Comment by pavelgrinchenko** [comment]
Here is simple example https://github.com/ahawkin/heroku-nginx-proxy-node

**Comment by fabiosantoscode** [comment]
Express is not going to be an issue. Cloudflare should be responding to those requests directly. Only first request goes to express (which is really fast and definitely not taking almost 1 second to respond).

Something else is going on, but I don't believe we need to look into it.

**Comment by pavelgrinchenko** [comment]
@shcheklein Is it still relevant after migrating deployment method from the blog? Seems it's now much better

**Comment by shcheklein** [comment]
I still hit it from time to time, but it's definitely better! Let's close it for now. Would be great to know if there are tools to detect this happening across clients - like some analytics to detect delays, long loading times, etc
