### ISSUE TITLE
user-guide: update gdrive setup guide

### ISSUE THREAD

**Issue by maxhora** [iterative/dvc.org#1095]
- New optional param to turn on Trash_Only option for gdrive remote;
- DVC starts to provide default client id and secret to access GDrive API;
- Service account support.

**Comment by jorgeorpinel** [comment]
Please link to corresponding core repo PR.

**Comment by shcheklein** [comment]
@jorgeorpinel I doubt the will be very informative, ask me any questions or let's do a call so that I can share the context

**Comment by jorgeorpinel** [comment]
Is it iterative/dvc/pull/3269?

**Comment by jorgeorpinel** [comment]
I'm just trying to find a place to comment on the name of the remote modify parameters being used e.g. `projectname` should probably be `project_name`.

**Comment by shcheklein** [comment]
Yes, and one or two to `gdrive.py` after that.

**Comment by jorgeorpinel** [comment]
I'm just trying to find a place to comment on the name of the remote modify parameters being used e.g. `projectname` should probably be `project_name`.

**Comment by shcheklein** [comment]
@jorgeorpinel projectname was way before GDrive - it's common for Google tools I believe

**Comment by jorgeorpinel** [comment]
K. also `credentailpath`. We have underscores in most other param names from what I can see. Not a huge deal I guess.

**Comment by jorgeorpinel** [comment]
Oh yeah sorry I was looking at the Google Cloud Storage section! Never mind...

**Comment by maxhora** [comment]
> 
> 
> Please link to corresponding core repo PR.

It is related to last 3 commits https://github.com/iterative/dvc/commits?author=maxhora

**Comment by jorgeorpinel** [comment]
Thanks Max
