### ISSUE TITLE
user-guide: why would we ever want gdrive://appDataFolder as a remote?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1099]
See https://dvc.org/doc/user-guide/setup-google-drive-remote#url-format-for-google-drive-remotes

Maybe we should just remove that from docs. And if possible prevent it in the core repo (if it's a specially coded feature)

**Comment by shcheklein** [comment]
Don't see a strong reason to remove it tbh (it comes for free). Though I don't see a strong use case for this also. Probably, users won't be able to specify a path within this folder - it's a limitation, they would be able to use only root of it.

**Comment by jorgeorpinel** [comment]
Ah I see. So this folder is created as a kind of isolated container for each connected app it seems? I was afraid it would contain other apps or even internal GDrive config files so it would be unwise to use it as a remote. It's a boomer you can't easily create subfolders in there though.

But anywa, it's meanf for app-data meaning probably metadata, config files, etc. Not really big files but then again it's up to the user so OK no reason to remove this. Probably no one will ever use it thought haha

**Comment by jorgeorpinel** [comment]
*bummer

**Comment by jorgeorpinel** [comment]
Just one last Q though. This only works when you have a custom GC project/app right? Not for the default shared DVC GC project... Cc @maxhora

**Comment by maxhora** [comment]
@jorgeorpinel it should work also for default shared DVC GC project.

**Comment by shcheklein** [comment]
thanks, @maxhora !

@jorgeorpinel yes, I think this folder is unique per combination (app, user) - so every user can create this `appDataFolder` for the DVC GDrive app.

**Comment by jorgeorpinel** [comment]
OK great thanks, that makes sense... But one last Q actually, what about this note:

> The application data folder is deleted when a user uninstalls your app from their MyDrive. Users can also delete your app's data folder manually.

? Could this cause issues? Thanks

**Comment by shcheklein** [comment]
No, I don't think so tbh. It's up to users to manage this folder. We just can put data into it if they want.
