### ISSUE TITLE
install: make conda, choco, or pip the default method for Win. Installer has this problem:

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1101]
Similar to iterative/dvc#2677, Windows prevented me from running the latest installer (dvc-0.91.1.exe) with a screen but I didn't take a screenshot and now it's not happening again with any version after I told it to run it anyway. It looked like this but green:

![image](https://user-images.githubusercontent.com/1477535/77971321-98fe5400-72ab-11ea-84f7-a4377035464e.png)

and the [Run anyway] button is hidden until you click a "More info" link.

**Comment by shcheklein** [comment]
I think we already have one in docs to rearrange the order of options we recomend

**Comment by shcheklein** [comment]
@jorgeorpinel https://github.com/iterative/dvc/issues/936

**Comment by jorgeorpinel** [comment]
> I think we already have one in docs to rearrange the order of options we recomend

True, closing in favor of #904
