### ISSUE TITLE
pretty-quick --bail is gone for .md files

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1108]
After the merge with Gatsby and blog, some changes in package.json may need reviewing:

Script `format-staged` is still there but uses a removed dependency, `pretty-quick`. The full script is `pretty-quick --staged --no-restage --bail` and used to be run by the pre-commit hook (via `husky`) — applying to all staged changes but most useful for MD files.
   Now the formatting is still being done with a simple `yarn prettier --write` (via `lint-staged`) which isn't as good, because there's no `--bail` option, so any automatic formatting is just applied and you are not even aware of it. Before, the commit would fails and the auto-formatted changes were applied but not staged, allowing you to see them with `git diff`. Solutions:
  a. Find a way to configure `pretty` to behave the same way.
  b. Setup `pretty-quick` again.
  c. Settle for this new behavior and remove the `format-staged` script.

  I vote to try a. and if not, do b.

~~2. The README has more info now which is good but should probably be reviewed so it matches the docs contrib guide (https://dvc.org/doc/user-guide/contributing/docs) and vice versa. The latter is currently outdated, still mentioning the `format-staged` script, for example.~~ Extracted to #1125

**Comment by jorgeorpinel** [comment]
@shcheklein I see you added some labels. Was that for 1. or for 2. in the description? I've extracted 2. o #1125 so you may want to edit the labels in both. Thanks

**Comment by pavelgrinchenko** [comment]
@jorgeorpinel I created PR with reverting back old behaviour. You could merge it after reviewing
