### ISSUE TITLE
lint/pre-commit: forbid and fix long comments and string constants

### ISSUE THREAD

**Issue by fabiosantoscode** [iterative/dvc.org#1112]
All of our lints accept very long comments and strings, which go way past 80 characters per line.

The purpose of this issue is to make one of the lints (eslint or prettier) complain and fail the build.

Edit: Fail the build if any requires cannot be resolved.

UPDATE: See https://github.com/iterative/dvc.org/issues/1112#issuecomment-611822294 below.

**Comment by shcheklein** [comment]
@fabiosantoscode @pavelgrinchenko am I right that we use `eslint` now? Is this one fixed?

**Comment by shcheklein** [comment]
So, it's not fixed for long string constants, repurposed it to revisit and fix linters.

**Comment by jorgeorpinel** [comment]
HI. Is this still relevant and if so can we remove the `migration` flag? Cc @rogermparent WDYT 🙂

**Comment by jorgeorpinel** [comment]
In fact I took the liberty to remove the flag for now, please reinstate it or LMK if I'm wrong.

**Comment by rogermparent** [comment]
> In fact I took the liberty to remove the flag for now, please reinstate it or LMK if I'm wrong.

I think it's safe to say this doesn't need to be marked as a migration issue.

**Comment by jorgeorpinel** [comment]
> it's not fixed for long string constants

Do you know whether this is still an issue @rogermparent ?

To be honest I haven't bumped into this problem much if at all: in code blocks we manually keep them short to prevent horizontal scrolling anyway (and the col limit varies depending on browser, from 68 to 72). I guess if that can be linted it would be nice, but from what I remember `eslint` doesn't have that ability so I would understand if you prefer to close this.

**Comment by rogermparent** [comment]
Do we have an example of one of these failing long string constants? My assumption is we're talking about something like `const LONG_CONSTANT = 'aaaaaaaaaaaaaaa'` where the amount of `a`s breaks 80 lines. I'd consider that fine for cases where it's needed, but if we want to break lines for something like:

```ts
const LONG_CONSTANT = 'aaaaaaaaaaaaaaaaaaaaaaaa'
  + 'aaaaaaaaaaaaaaaaaaaaa'
```

I have very little passion toward linting for this or not, but I'll take a look into using the `max-len` rule, see if it works, then close this whether or not we add it since that's mostly all it warrants IMO. Open to other opinions.

**Comment by rogermparent** [comment]
`max-len` also has [a lot of configuration options](https://eslint.org/docs/rules/max-len#options), but I think the defaults fit what we want nicely:

- "code" (default 80) enforces a maximum line length
- "tabWidth" (default 4) specifies the character width for tab characters
- "comments" enforces a maximum line length for comments; defaults to value of code
- "ignorePattern" ignores lines matching a regular expression; can only match a single line and need to be double escaped when written in YAML or JSON
- "ignoreComments": true ignores all trailing comments and comments on their own line
- "ignoreTrailingComments": true ignores only trailing comments
- "ignoreUrls": true ignores lines that contain a URL
- "ignoreStrings": true ignores lines that contain a double-quoted or single-quoted string
- "ignoreTemplateLiterals": true ignores lines that contain a template literal
- "ignoreRegExpLiterals": true ignores lines that contain a RegExp literal

`code` is 80 like mentioned here, and there's seemingly no exceptions by default.

**Comment by jorgeorpinel** [comment]
> If we want, one of us can go through and fix all these so we can carry the rule in the future.

Up to you since it's mostly an engine code thing at this point.
