### ISSUE TITLE
blog: show forum widget on a button click

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1116]
On a comment button show a widget on the page itself.

Show a simple text field behind button and open the widget when you click/activate it as well.

**Comment by santos22** [comment]
👋 

Clicking on the **Discuss this post** button at the bottom of a blog post takes you to the discussion on Discourse.

Example: https://dvc.org/blog/dvc-3-years-and-1-0-release

Is this issue about embedding the comments found on Discourse on each blog post?

References:
- https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963
- https://blog.codinghorror.com/welcome-to-the-internet-of-compromised-things/#discourse-comments

**Comment by jorgeorpinel** [comment]
Hi @santos22 thanks for your interest on this in the context of GSoD 20202. I'm not sure, maybe @shcheklein can clarify, but I think so. There seems to be some other design requirements from the description but seeing the embed working when you click [Discuss this post] would probably be a good first step for a PR to address this.

**Comment by shcheklein** [comment]
@santos22 I would say it is out of the GSoD program a bit, it's not about docs engine or docs content after all. I still think it can be accepted as a contribution that demonstrates an interest in the project. 

> but seeing the embed working when you click [Discuss this post] would probably be a good first step for a PR to address this.

this is a good first step 👍
