### ISSUE TITLE
review meta tags, keywords, favicons, etc

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1119]
https://docs.google.com/document/d/1lOhYiIxE02X27mRNXezJCNZEAS2nObjShZ1wnPBpxpY/edit

also check this PR https://github.com/iterative/blog/pull/144 for some fixes

**Comment by MerlynMShelley** [comment]
Hi Team,
I have found these issues in improving the SEO of the site,
![IMG_20200607_164351](https://user-images.githubusercontent.com/46276713/83967387-6f326080-a8de-11ea-946b-0d696124bd29.jpg)
![IMG_20200607_164334](https://user-images.githubusercontent.com/46276713/83967392-735e7e00-a8de-11ea-99de-2621cd6e35d8.jpg)
![IMG_20200607_164311](https://user-images.githubusercontent.com/46276713/83967395-778a9b80-a8de-11ea-88c9-bc8f4c13b956.jpg)

You can find the complete report here,
https://www.seoptimer.com/www.dvc.org

Thank you @shcheklein @ jorgeorpinel

**Comment by jorgeorpinel** [comment]
@MerlynMShelley I collapsed those long vertical images. Hard to read and unnecessary. We can click the link. Please just copy/paste test or small horizontal screenshots of key elements you'd like to bring to our attention.

Meaning: what specific suggestions about meta tags, etc. (this issue's topic) would you make based on that report? Thanks

**Comment by shcheklein** [comment]
@julieg18 One of the existing problems:

https://dvc.org/favicon.ico - is the old low res icon.

According to this https://realfavicongenerator.net/favicon_checker - a lot of formats are not set/available.
