### ISSUE TITLE
scripts: link check compatibility and docs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1123]
Compatibility: it doesn't run out-of-the-box because `pcregrep` is not usually on the OS.
- Not sure about MacOS (but I remember `sed` was a problem there)
- On Ubuntu I had to `sudo apt install pcregrep`
- For Windows, I got it from https://sourceforge.net/projects/gnuwin32/files/pcre/, installed and put in PATH.
  `sed` will likely be a problem in some Windows terminals too, but it can also be obtained from GNUWin (http://sourceforge.net/projects/gnuwin32/files/sed).

By "and docs" I mean we should probably at least write the above info and how to use these commands in the README.

**Comment by jorgeorpinel** [comment]
Cc @casperdcl

**Comment by shcheklein** [comment]
It sounds too complicated if we run it locally on pre-commit. We should not require installing stuff with apt (or even worse on Windows) for the link checker.

**Comment by jorgeorpinel** [comment]
Sure, I guess I'm just suggesting we add this info to the README, at least 🙂

**Comment by jorgeorpinel** [comment]
...so maybe this is a duplicate or can be merged into #1125

**Comment by shcheklein** [comment]
no, I think it's a bug to require this in the first place. We should not require more than `yarn` on most reasonable platforms.

**Comment by shcheklein** [comment]
> ...so maybe this is a duplicate or can be merged into #1125

no, this is a different one and is not related with the recent migration to Gatsby.

**Comment by jorgeorpinel** [comment]
Got it. Also note it seems to have another bug as noted in https://github.com/iterative/dvc.org/issues/1000#issuecomment-610762657:

> It's outputting
> 
> `find: ‘/.../dvc.org/pages/’: No such file or directory`
> 
> every time now. I think it has to be updated given the new project structure.

**Comment by shcheklein** [comment]
> find: ‘/.../dvc.org/pages/’: No such file or directory

can we do a quick fix for this?

**Comment by jorgeorpinel** [comment]
You're right, that's pretty simple ha. OK fixed in 9665edc3 (#1124)

**Comment by casperdcl** [comment]
> Compatibility: it doesn't run out-of-the-box because `pcregrep` is not usually on the OS [...] Not sure about MacOS (but I remember `sed` was a problem there) [...] likely be a problem in some Windows terminals too

and

> [...] sounds too complicated if we run it locally on pre-commit. We should not require installing stuff with apt (or even worse on Windows) for the link checker [...] it's a bug to require this in the first place. We should not require more than `yarn` on most reasonable platforms.

`link-check` was never intended to be run locally. We had discussions about this originally and there were several reasons:

- `pcregrep` really is required. Most regex implementations (including python's own as well as any I could find via `yarn`) lack the features required to make nested bracket detection (as with markdown links) work flawlessly
- it can take a few minutes to check *all* links (which is why it's best done in the cloud via a cron job)
- ergo the scripts were written in bash, which itself could be an issue on e.g. Windows

Compared to the hassle of finding work-arounds, I don't think it's too much of an issue to wait for small diffs to be checked by CI rather than installing & running locally.

> By "and docs" I mean we should probably at least write the above info and how to use these commands in the README.

... maybe. I think just documenting in code is enough purely for the purpose of maintenance of CI scripts.

**Comment by shcheklein** [comment]
@jorgeorpinel let's remove it from docs for now. Since there is not intention to support it locally for now, let's not bother documenting a lot of stuff.

@casperdcl may be we can write a comment in the script itself about its dependencies and this script is purely for CI to run?

**Comment by jorgeorpinel** [comment]
> let's remove it from docs for now

Removed in 4bf9eea7 (for #1160)

**Comment by casperdcl** [comment]
Also note from https://github.com/iterative/dvc.org/pull/958#issuecomment-583359254

> [`prcregrep` is] one of the reasons why this is a CI-only check by default rather than a pre-commit hook... no guarantee that it'll run on dev machines

**Comment by shcheklein** [comment]
Closing this. I think it's resolved more or less. Decided to keep it CI focused mostly.
