### ISSUE TITLE
docs: contrib guide outdated, compare vs README

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1125]
The README has more info now which is good but should probably be reviewed so it matches the docs contrib guide (https://dvc.org/doc/user-guide/contributing/docs) and vice versa. The latter is currently outdated, still mentioning the `format-staged` script, for example.

> Extacted from 2. in #1108

What should the README be for? If it's mainly to document some optional scripts, lets make sure all scripts are explained (purpose, depencencies, etc) either there or in the contrib guide, currently some are missing.

**Comment by jorgeorpinel** [comment]
> Extacted from 2. in #1108

**Comment by shcheklein** [comment]
I would say README can be an extended version of the contrib guide. We def don't to repeat info everywhere.

**Comment by jorgeorpinel** [comment]
So an extension to the docs contrib guid, you mean? With extra info. (more optional/internal details) but not repeating the whole guide again.

**Comment by shcheklein** [comment]
@jorgeorpinel I'll just do something about it this weekend and prepare a PR - easiest way in this case to explain probably :)
