### ISSUE TITLE
term: ambiguous use of "external" and "workspace"

### ISSUE THREAD

**Issue by woodshop** [iterative/dvc.org#1127]
The term "workspace" is defined in the glossary as "Directory containing all your project files..." However advanced dvc usage allows for remote storage of external data and external dependencies. It is not clear from the docs whether the "workspace" includes external data & dependencies. Furthermore, the docs for various commands assume different definitions of workspace. For instance, `dvc push` does not interact with external data, but `dvc checkout` does. This should be clarified in the docs.

UPDATE: Go to https://github.com/iterative/dvc.org/issues/1127#issuecomment-783060111

**Comment by woodshop** [comment]
In general, I find that several definitions could be tightened in the docs along with workspace.

E.g. "external dependencies" and "external data" seem to refer, respectively, to stage inputs and outputs that don't reside in the "workspace" but that are nevertheless tracked by dvc. I think it would be really helpful to clarify this in the docs. At the same time, it would be useful to refer to non-external dependencies/data as "internal" to make it easier to discriminate from external. I suppose "internal" data is located in a directory that shares the same root as ".dvc" but I might be wrong about that.

**Comment by shcheklein** [comment]
More context - https://discordapp.com/channels/485586884165107732/563406153334128681/697459286455877732

**Comment by jorgeorpinel** [comment]
Hi, sorry for the delay. Some feedback:

> advanced dvc usage allows for remote storage of external data and external dependencies. It is not clear from the docs whether the "workspace" includes external data & dependencies

External dependencies, outputs, and cache are the exception to the rule. Here are some of the explanation from docs:
![image](https://user-images.githubusercontent.com/1477535/79404772-3d44f380-7f58-11ea-8840-4db1a3ad5922.png)
![image](https://user-images.githubusercontent.com/1477535/79404801-53eb4a80-7f58-11ea-9134-981bdd310f67.png)
![image](https://user-images.githubusercontent.com/1477535/79404857-78472700-7f58-11ea-9af6-fb4a030459a5.png)

In any case, I don't think we really consider them part of the workspace. They are an extension of it, like Andy correctly interpreted. They are part of the project as a whole. Any suggestion on how/where best we should clarify this?

> refer to non-external dependencies/data as "internal"

Thanks for the idea but I think it would be a little cumbersome to have to call deps and outs "internal" in let's say 95% of the cases just to be bring attention to the exceptions.

> docs for various commands assume different definitions of workspace. For instance, dvc push does not interact with external data, but dvc checkout does

`dvc push` does interact with external dependencies and outputs, same as `dvc checkout`. It uploads/copy them to remote storage.

It is true we don't really explore the external data cases inside individual command references though. Should we try to do so?

**Comment by iesahin** [comment]
Another point regarding _workspace_ concept is its difference from _DVC project._ Currently these two have different pages in BC but these two seem to overlap a lot. 

Can we say a DVC project = workspace + external dependencies? (I think we cannot.) How can we make a distinction between these two?

**Comment by jorgeorpinel** [comment]
There's also the concept of DVC repository 🤯 

Sometimes you just need to juggle with all the terms. They're more appropriate under different contexts. Current implicit definitions:

- workspace: directory where you `dvc init`
- project: (can be in general "whatever you're doing", or specifically -> ) all the code, config (e.g. including remotes), and data related to the stuff you're tracking/versioning/codifying with DVC
- repository: a Git-enabled DVC project. The term is used under that context e.g. when talking about branches, revisions, etc (many commands require Git, like `dvc diff`)

**Comment by iesahin** [comment]
We have a new PR regarding workspace concept #2197. 

> workspace: directory where you dvc init — but "extended workspace" includes external data

There is no result for `extended.*workspace` in the docs :) I think we don't need to mention it. We already have too many overlapping / context dependent concepts. 

From what I understand
```
DVC project = workspace + local cache + remote data. 
DVC repository = DVC project + .git
```

Therefore 

```
workspace = DVC repository - .git - local cache - remote data
```

I defined it as *user visible part of the project* in the BC doc because of this. 

I think we can define subset/superset relationships between these and revise the docs & DVC itself by checking the usage.

**Comment by jorgeorpinel** [comment]
> There is no result for extended.*workspace in the docs :)

I guess I was thinking of "extended project" which you can find in https://dvc.org/doc/user-guide/external-dependencies and https://dvc.org/doc/user-guide/managing-external-data — should probably be "extended workspace" 😋 

> DVC project = workspace + local cache + remote data. 

Interesting, I don't see remote storage as part of the remote as it's kind of a backup. Also multiple projects can share a remote (that can also be true of the cache dir but it's less common). Also the cache is usually in the workspace (in .dvc/cache).

I think they're 🍐 and 🍎, not easy to put into an equation. Workspace is literally a file system directory. Project is more conceptual, comprised by all the possible workspaces (project versions) — in that sense yes, it must include all the cached data (whether local or remote).

> workspace = DVC repository - .git

Why not consider .git/ as part of the ws? .dvc/ is I think. Anyway, no need to be so mathematical with these definitions probably 🙂 

> defined it as _user visible part of the project_

Great.

**Comment by iesahin** [comment]
There are about 160 references to _workspace_ in cmd ref, but I couldn't find a one mentioning a _remote workspace._ There are references to _local workspace_ like [this](https://github.com/iterative/dvc.org/blob/03a736ab3971ce1ca195008954ef6863c3686b54/content/docs/command-reference/status.md#L53) or [this](https://github.com/iterative/dvc.org/blob/d58af5bfdf4a992156eaa84f85acdb1cf955c4fc/content/docs/command-reference/import-url.md#L63) but these can be considered as emphasis, I think. 

Maybe it's better to remove this emphasis and call these _workspace_ plainly. When I read about _local workspace_, I may think about the possibility of a _remote workspace_ too.

**Comment by jorgeorpinel** [comment]
> remote workspace

Not sure why we're looking into that term TBH.

> local workspace... remove this emphasis

Yeah, that would be OK. But again, how does that relate to the OP? To recap, this issue is about:

> - It is not clear from the docs whether the "workspace" includes external data & dependencies. 
> - "external dependencies" and "external data" seem to refer, respectively, to stage inputs and outputs that don't reside in the "workspace" but that are nevertheless tracked by dvc. I think it would be really helpful to clarify this in the docs.

TBH at this point we don't really recommend that kind of external data. ext deps are OK but not part of the workspace. And ext outs are being replaced for the `import/add` "to cache" / "to remote" functionality. AND we have #520 to rewrite the Ext Data guide. So I think we can close this (please fully link it to #2197 @iesahin, thanks).
