### ISSUE TITLE
glossary: auto link `dvc <cmd>` strings like in docs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1137]
from md strings in glossary.js

For example in this tooltip, `dvc run` should link to the cmd ref:

![image](https://user-images.githubusercontent.com/1477535/79055881-216ae600-7c16-11ea-90f0-9310082101be.png)

**Comment by jorgeorpinel** [comment]
for example in this tooltip, `dvc run` should link to the cmd ref:

![image](https://user-images.githubusercontent.com/1477535/79055881-216ae600-7c16-11ea-90f0-9310082101be.png)

**Comment by shcheklein** [comment]
Related #https://github.com/iterative/dvc.org/issues/1045 - it should go first. We don't want to bring any complicated processing to the client side.

**Comment by jorgeorpinel** [comment]
I can also use proper md links in all glossary md text and close this with that. WDYT?

**Comment by shcheklein** [comment]
don't like the idea, tbh - we'll have to support this (in case we change something). Let's wait on #1045 first.

**Comment by shcheklein** [comment]
this is fixed now!

**Comment by jorgeorpinel** [comment]
Cool, we just need to remove all the manual links now. Added to #1431
