### ISSUE TITLE
windows: Git Bash doesn't support \ new lines...

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1144]
We recommend Cmder in https://dvc.org/doc/user-guide/running-dvc-on-windows, but for example if you copy and paste the command below, it won't work (with the default, single-line paste):
```
dvc run -f prepare.dvc \
          -d src/prepare.py -d data/data.xml \
          -o data/prepared \
          python src/prepare.py data/data.xml
```
Result:
![image](https://user-images.githubusercontent.com/1477535/79181156-5a9b8580-7dd1-11ea-9326-3aaf2e237b7f.png)
Sounds like WSL just got another victory?

**Comment by shcheklein** [comment]
Yeah, we have a ticket #134 - probably that is the most appropriate way to solve this. 

I'm fine to mention WSL along with Cmder with all the caveats.

**Comment by shcheklein** [comment]
I wonder if there is some compat mode that can be enabled to deal with this in Cmder.

**Comment by jorgeorpinel** [comment]
Yes, actually it has multi-line paste, by default Shift+Insert. It pastes line by line and does Enter between each one.

**Comment by jorgeorpinel** [comment]
Butttt it has this limitation:

![image](https://user-images.githubusercontent.com/1477535/79280342-c0414d80-7e75-11ea-8596-d1ae9c35c6cf.png)

**Comment by jorgeorpinel** [comment]
OK I guess that keeps Cmder on top... Closing for now.
