### ISSUE TITLE
broken external links at community tutorials page

### ISSUE THREAD

**Issue by sudodoki** [iterative/dvc.org#1146]
At https://dvc.org/doc/tutorials/community you see all the links are pointing to dvc site and 404 although `content/docs/tutorials/community.md` is featuring proper external links.

Tried investigating root cause, might be something in redirects-list.json &         src/utils/shared/redirects.js

Also, not 100% relevant (and sure :)), but in gatsby-config both `external-link-plugin` & `gatsby-remark-external-links` are used which might be doing similar things

**Comment by jorgeorpinel** [comment]
Great find! It applies to the first 3 links and to the last one. We'll investigate this ASAP...

**Comment by jorgeorpinel** [comment]
@iAdramelk @pavelgrinchenko this doesn't seem to be a problem with the markdown or with the redirect list. The links in code are correct so the link checker doesn't catch these 404s. Maybe it's a Gatsby problem indeed?

**Comment by jorgeorpinel** [comment]
p.s. seems to be replacing host names that have subdomains (e.g. `blog.codecentric.de` or `www.linkedin.com`) for the server host name.

**Comment by jorgeorpinel** [comment]
p.p.s. it's affecting all external links everywhere in the website e.g. http://localhost:8000/doc/understanding-dvc/resources#articles

**Comment by sudodoki** [comment]
@jorgeorpinel not sure it's broken the same way in develop & build mode, but

This is happening for
1) external links
2) that end with trailing `/`
Because of redirect rule being applied and returning only relative part of URL

Details: 
`<Link>` component is calling `getRedirect` [here](https://github.com/iterative/dvc.org/blob/master/src/components/Link/index.tsx#L93) and 
this ["^/(.+)/$"](https://github.com/iterative/dvc.org/blob/master/redirects-list.json#L29) pattern is being checked against `path` part of external URLs omitting the host, returning relative urls that are being rendered instead of original external url.

So as a quickfix, can just remove trailing `/` from external links to avoid this and might need to modify redirect matching/using results logic

**Comment by iAdramelk** [comment]
@pavelgrinchenko Can you please check it?

I think @sudodoki is right, we should probably reapply host for the links if it's not equal to the current site or return original link without removing / for such links, but maybe I'm missing some edge case there.

**Comment by pavelgrinchenko** [comment]
@jorgeorpinel I made PR with fix, could you [review it](https://github.com/iterative/dvc.org/pull/1151)

**Comment by shcheklein** [comment]
@pavelgrinchenko thanks! 🙏  Merged.

@sudodoki 

> external-link-plugin & gatsby-remark-external-links

names are confusing indeed, buy yes, we need both - one to support custom HTML in blog (it is a a custom plugin we wrote), second one - is regular gatsby that deals with ext links.

Good catch, btw. Thanks for the report.

**Comment by shcheklein** [comment]
@pavelgrinchenko it looks like it is still broken :(

**Comment by sudodoki** [comment]
@shcheklein at which page are you seeing same behavior? https://dvc.org/doc/tutorials/community links from original issue seem fixed.

**Comment by shcheklein** [comment]
@sudodoki links are fixed, but when I click them they still redirect me to dvc.org Not Found. Is it only me? 🤔

**Comment by pavelgrinchenko** [comment]
@shcheklein I forgot to add domain check to click handler... [Here is another fix ](https://github.com/iterative/dvc.org/pull/1154)

**Comment by pavelgrinchenko** [comment]
@shcheklein Hm, seems this logic outdated there at all as we are already replacing original href with redirected when it's necessary. So I removed it from the click handler

**Comment by jorgeorpinel** [comment]
Awesome, geat fix. Thanks guys! And thanks again @sudodoki

**Comment by jorgeorpinel** [comment]
Oops only the URLs are fixed. It works OK when you Cmd/Ctrl+click but regular click changes the page to dvc.org 404 still...

**Comment by jorgeorpinel** [comment]
Cc @pavelgrinchenko 

p.s. I tried with no cache

**Comment by shcheklein** [comment]
It works for me now. Not sure what was the issue after the deployment, but it works. @jorgeorpinel could you please confirm and reopen if it is still broken?

**Comment by jorgeorpinel** [comment]
It works OK for me now as well.
