### ISSUE TITLE
link check: CI verision does not work properly

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1148]
Example

https://dvc.org/uploads/images/2020-02-10/image.png

was detected here:

https://app.circleci.com/pipelines/github/iterative/dvc.org/2946/workflows/f15ce218-150d-4504-a5a3-647e8e721f43/jobs/2994

**Comment by shcheklein** [comment]
@casperdcl 

I think a few things are wrong with these scripts:

1.

```
changed="$differ --name-only :^redirects-list.json" 
```

should it be 

```
changed=$("$differ --name-only :^redirects-list.json" )
```

2.  Here:

```
$(dirname "$0")/link-check.sh <($differ -U0 -- "$file" | grep '^\+')
```

This a nice stuff, but I think it creates a temp `fd` that you can read only once - means that only the first link from the diff is detected.

Not sure if there are any other problems ...

**Comment by shcheklein** [comment]
Also, 

```
sed -nE 's/.*href=["'"'"'](\/[^"'"'"']+?)["'"'"'].*/\1/p' "$@" | xargs -n1 -II echo ${base_url}I
```

sed on Mac does not like `+?` - what was your intention here?

**Comment by casperdcl** [comment]
> ```
> changed="$differ --name-only :^redirects-list.json" 
> ```
> 
> should it be
> 
> ```
> changed=$("$differ --name-only :^redirects-list.json" )
> ```

Absolutely not. No idea what this is. Definitely not a valid command. Accidental garbage committed in 847d4ad84b7870c104573bec ? @pavelgrinchenko did you mean to do this? The original line was simply: `changed="$($differ --name-only)"`

Were you trying to exclude the `redirects-list.json` file? (In that case you should use the same method used to exclude the `exclude-links.txt` file.)

> ```
> $(dirname "$0")/link-check.sh <($differ -U0 -- "$file" | grep '^\+')
> ```
> 
> This a nice stuff, but I think it creates a temp `fd` that you can read only once - means that only the first link from the diff is detected.

Yes, I was very aware of this and opted for lazy programming since it's only ever an issue with running on git-diffs (a bit of extra pain for devs to fix one link at a time if there are multiple broken links in a single diff). Can definitely fix this.

**Comment by shcheklein** [comment]
> Absolutely not. No idea what this is. Definitely not a valid command.

gotcha

> Were you trying to exclude the redirects-list.json file? 

yes, it looks like so

> In that case you should use the same method used to exclude the exclude-links.txt

for redirects probably it's better to make an exception and exclude it in the script?

> Yes, I was very aware of this and opted for lazy programming since it's only ever an issue with running on git-diffs

got it, as well ... if it is too much effort - let's keep it as is

**Comment by casperdcl** [comment]
> sed on Mac does not like `+?` - what was your intention here?

Similar to https://github.com/iterative/dvc.org/issues/1123#issuecomment-614900920, this was never intended to be run locally, and certainly not on a mac.

Could probably replace `+?` with `*?`. The intention is to convert these two cases:

- `href="/relative-url"` => `https://dvc.org/relative-url`
- `href='/relative-url'` => `https://dvc.org/relative-url`

Using `*?` would mean

- `href=""` => `https://dvc.org/`

rather than (previously)

- `href=""` => `` (i.e. not tested)

I don't have particularly strong opinions on this.

**Comment by casperdcl** [comment]
> for redirects probably it's better to make an exception and exclude it in the script?

Yes I think we're both talking about the same thing. To be clear:

- `exclude-links.txt` defines links to skip checking
- the whole `exclude-links.txt` file itself is never checked
- I'm suggesting also having the whole `redirects-list.json` file itself never checked

**Comment by shcheklein** [comment]
> I'm suggesting also having the whole redirects-list.json file itself never checked

yep, that would be great

**Comment by shcheklein** [comment]
> I don't have particularly strong opinions on this.

yep, same. But it looks it is the only thing (if pcre is installed and it's quite easy) that prevents this script from running on Mac (granted you didn't have intention to support it locally, but even for devs to debug the script itself you have to run it at least somehow ).

Also, forgive me my  lack of regex knowledge, but why can't we just use `+` there (without making it lazy)?

**Comment by shcheklein** [comment]
Btw, I think it would be great for exclude-list to support path to a file to exclude. Again, if it's not that much effort. It's not nice to hard code some file within the script itself.

**Comment by pavelgrinchenko** [comment]
> Were you trying to exclude the redirects-list.json file?

Yes. Why it works: https://stackoverflow.com/questions/5685007/making-git-log-ignore-changes-for-certain-paths/21079437#21079437
But you definitely can handle it in another way if you think it would be better

**Comment by casperdcl** [comment]
yes, it's missing a crucial `--` and also probably we should have a file-exclusion list as well as a link-exclusion list. Will fix.

**Comment by casperdcl** [comment]
> Also, forgive me my lack of regex knowledge, but why can't we just use `+` there (without making it lazy)?

from the original #958, it's called recursive/balancing groups regex. Techically [only `.NET` has full balancing groups support](https://en.wikipedia.org/wiki/Comparison_of_regular-expression_engines#Part_2) though [some things including pcre support recursion](https://en.wikipedia.org/wiki/Comparison_of_regular-expression_engines#Part_1). There's been recent work on https://pypi.org/project/regex/ which means `pip install regex` may potentially work, but this would still 1. require python and 2. potentially not work (the last time I tried the `regex` lib it didn't have the features required).

**Comment by shcheklein** [comment]
@casperdcl 

`echo 'href="/"'| sed -nE 's/.*href=["'"'"'](\/[^"'"'"']+)["'"'"'].*/\1/p'`

outputs nothing (not tested)

`echo 'href="/relative-url"'| sed -nE 's/.*href=["'"'"'](\/[^"'"'"']+)["'"'"'].*/\1/p'`

outputs:

`/relative-url`

If that was the intention, what is the case we need the `+?` for? That's what I'm still missing probably.

**Comment by casperdcl** [comment]
oh I thought you were talking about `+?` => `*?`.

If you mean dropping the `?`, that's fine. I think you would still need to replace `*` => `+` for macs, though.

**Comment by shcheklein** [comment]
`+?` -> `+` works for me on Mac

**Comment by casperdcl** [comment]
curious, ok. I've seen reports in the past where mac users needed `*` => `+`. Anyway will fix.
