### ISSUE TITLE
blog: post authors twitter account

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#1161]
I've noticed that after moving out of Medium, fewer people start following me on Medium and Twitter.
Medium followers - very expected. Twitter - not.

We should drive more followers to the author's profiles and @dvcorg profile. Also, we can deploy the email subscription somewhere (it might be not enough to have it on the very bottom of the page).

It can be done by incorporation of author twitter accounts next to author avatar/image or have it on the author page.

@andronovhopf what do you think?

PS: It might be related to #1120

**Comment by andronovhopf** [comment]
We could have the author names link to their twitter, maybe? Or have a separate link next to the avatar. Both are good.

And yes to adding another field to subscribe to email updates. The only one I can find right now is at the bottom of the community page. Possible we could make a header/hero image for the community page about it?

**Comment by shcheklein** [comment]
all good points, we def need subscribe way more visible - some nice pop-up at the very bottom? let's create a separate ticket for this, @andronovhopf ?

**Comment by chaytanyasinha** [comment]
I think we can provide the name of the author's name with the link of their twitter handles for mentioned issue.So that users can reach to them by just clicking their name.
Please give suggestions if this is good or any other plan.
And may I work on this issue?

**Comment by shcheklein** [comment]
@chaytanyasinha hi! before we jump into implementing this we need to come with some design idea. Where do you see these links fit? can you make a screenshot with an idea? Also, we should keep in mind this related issue #1120

**Comment by chaytanyasinha** [comment]
@shcheklein
Actually I was thinking of the author's name with link that just by clicking the name they can move to their handles as I can see it will be quite difficult to fit another column their

**Comment by shcheklein** [comment]
@chaytanyasinha so, it'll contradict with #1120 I believe, right?

**Comment by chaytanyasinha** [comment]
@shcheklein Yeah right. So any other ideas?

**Comment by rogermparent** [comment]
@shcheklein I think @chaytanyasinha's idea would work well as a quick fix while we all work out the design of individual Author pages at #1120. I could implement this very quickly, and it wouldn't be an issue to replace that link when we finally decide what we want on #1120's pages.

Maybe we should have a generic author link field so people can choose which social media page they prefer? I'd also make it optional, of course.

**Comment by rogermparent** [comment]
#1341 implements the behavior of Author markdown files accepting an optional `link` frontmatter field. If specified, their name on blog posts will be a `Link` component pointing to the value.

The value of `link` could be anything, but from what I can tell will usually be a Twitter link- in which case, make sure to use the full URL including `https://`. This is the most basic implementation, but if we want something more advanced I can easily build on it.
