### ISSUE TITLE
guide: mention .dvcignore doesn't apply to external deps

### ISSUE THREAD

**Issue by benjamintanweihao** [iterative/dvc.org#1172]
As above.

UPDATE: Skip to https://github.com/iterative/dvc.org/issues/1172#issuecomment-670323285

**Comment by jorgeorpinel** [comment]
Hmm. I'm not sure I get this Benjamin. Can you provide an example? I don't think .dvcignore applies to any dependencies since they are already tracked with DVC.

**Comment by Zenix27** [comment]
where should this be mentioned, in the `External [Dependencies.md`

**Comment by jorgeorpinel** [comment]
We would first need to confirm what this issue means. I personally didn't fully understand it as can be seen from my question above. If you'd like to play with .dvcignore and external dependencies, maybe you can clarify what the problem seems to be. Thanks

**Comment by jorgeorpinel** [comment]
p.s. more info on these topics: https://dvc.org/doc/user-guide/external-dependencies and https://dvc.org/doc/user-guide/dvcignore

**Comment by sarthakforwet** [comment]
Hey I wanna take this . Could you assign me this?

**Comment by jorgeorpinel** [comment]
Hi @sarthakforwet! No, I think this is about what kind of files you can list inside .dvcignore. Like I mentioned in https://github.com/iterative/dvc.org/issues/1172#issuecomment-629425955, to figure this out you'll first need to play with external dependencies and .dvcignore, and see how these 2 features intersect, then compare to out docs and see if anything is missing from there. Keep in mind all this is relatively easy to test with a dummy DVC project in your local machine. If you go for it, please feel free to reach out to me on Discord (sent you an email with that info) for guidance.

**Comment by jorgeorpinel** [comment]
I checked with something like `dvc run -n stgnm -d /ignored/external/path -o out cmd /external/path out` (also with relative ignored external path, both cases in `.dvcignore`) and indeed `run` doesn't care that they're ignored.

I wonder if this is a core bug rather though. Should I transfer it over to the `dvc` repo @efiop @shcheklein ? Thanks

**Comment by jorgeorpinel** [comment]
P/s from iterative/dvc/issues/3656 being marked `nice-to-have` I assume this is not a bug after all.

We should mention it in docs indeed. BTW it's the same for external outputs: `.dvcignore` has no effect on them.
