### ISSUE TITLE
document multistage dvcfile

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1173]
iterative/dvc#3584 implemented multistage dvcfile. Need to document about it (let's see how it solidifies).

**Comment by jorgeorpinel** [comment]
Wow this is huge. Do you gus know when the release is? If it's as big as I think, we should probably hold on releasing the version until we have at least corrected the existing docs that show DVC-file examples including get started and dvc run cmd ref.

Cc @shcheklein @efiop

**Comment by jorgeorpinel** [comment]
p.s. unless the change is backwards compatible but I understand that's not the case.

**Comment by skshetry** [comment]
@jorgeorpinel, it is backwards compatible at this point, but it's not yet clear if it will remain for 1.0 release.

**Comment by dsuess** [comment]
If you're not already working on this, I'd like to take a crack. Can you give me some pointers where I can find what the new file layout should look like? I've noticed that the options like `cached` or `persist` have moved...

**Comment by skshetry** [comment]
Hi @dsuess. Thank you for taking interest in this, but we are still iterating on this and is not complete yet. You can find more discussions on iterative/dvc#3584.

**Comment by skshetry** [comment]
Closing it, as this issue has become a bit redundant.
