### ISSUE TITLE
cmd: update metrics/plots docs per recent changes

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1175]
- [x] Changes found in iterative/dvc/pull/3658, iterative/dvc/pull/3577, et al.
- ~~Use term "scores" everywhere for old metrics, and "metrics" for `dvc plot` ones (per https://github.com/iterative/dvc.org/pull/1186#discussion_r415371959) — or whatever the final terminology ...~~ Extracted to #1442
- [ ] Complete the [Plot template](https://dvc.org/doc/command-reference/plots#plot-templates) description: It can be JSON or HTML and it's a combo of Vega schema + special DVC-specific anchors (per https://github.com/iterative/dvc/pull/3830#pullrequestreview-415640978)

**Comment by chaytanyasinha** [comment]
May I work on this issue @jorgeorpinel

**Comment by jorgeorpinel** [comment]
Thanks for your interest in helping us address this @chaytanyasinha! Usually I'd say of course but in this case I failed to note that there's someone already working on it and a long, complex discussion about it (https://github.com/iterative/dvc/issues/3409#issuecomment-627895106) so it's not really a great introductory issue.

But please, take a look at this list (or browse some other labels) and see if you want to contribute any other one: https://github.com/iterative/dvc.org/labels/good%20first%20issue

**Comment by chaytanyasinha** [comment]
Sure @jorgeorpinel

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc/pull/3830#pullrequestreview-415640978 we probably also need to improve the Plot template explanation. Notice that I'm currently doing some updates in #1283, hopefully soon to be merged. Updated issue desc.
