### ISSUE TITLE
rss: no title, no image in the feed for new posts

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1177]
<img width="1000" alt="Screen Shot 2020-04-22 at 1 05 11 PM" src="https://user-images.githubusercontent.com/3659196/80028515-162b7c00-849a-11ea-8f24-679c865d8835.png">

**Comment by rogermparent** [comment]
The title issue was introduced by models, which I got squared away, but I actually can't quite pin down where images broke- or if they're actually broken.
What RSS reader do we use to test on?

**Comment by shcheklein** [comment]
It's feedly. May be the problem is the way we embed them. It might be not related even to your changes. If you don't see a clear connection and simple fix - let's postpone fixing this.
