### ISSUE TITLE
analytics: should we strip queries?

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1179]
dvc.org/blog/a-public-reddit-dataset

should be probably the same as

dvc.org/blog/a-public-reddit-dataset?fbcid=aassdfsdfsdf

(Need to check if it's a good practice or not)

**Comment by jorgeorpinel** [comment]
Hi. What's the bug in this ticket? Thanks

**Comment by shcheklein** [comment]
Check that on GA we track pages with and w/o query strings properly

**Comment by julieg18** [comment]
Looking at other sites' analytics, the queries are almost never tracked.
