### ISSUE TITLE
link-check: trim exclusions

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#1184]
The exclusions list (`scripts/exclude-links.txt`) may have links that no longer exists in the codebase. Should check for this (CI and maybe pre-commit).

**Comment by casperdcl** [comment]
seem to be no longer needed:

```
  http://localhost:3000/
  http://ogp.me/ns
  https://blog.$
  https://dvc.org/img/<filename>.gif
  https://dvc.org/uploads/images/2020-02-10/image.png
  https://example.com/path/to/data
  https://remote.dvc.org/dataset-registry/a3/04af...
  https://s3-us-east-2.amazonaws.com/dvc-s3-repo/
```

**Comment by jorgeorpinel** [comment]
We need a script to check the link checker script's exclusion list 😆

**Comment by jorgeorpinel** [comment]
> localhost:3000

It's localhost:8000 now.

**Comment by shcheklein** [comment]
Alos, let's exclude all JS test file automatically. That will simplify the list.

**Comment by casperdcl** [comment]
That's a lot more to exclude then. #1189 should catch everything on CI :)
