### ISSUE TITLE
link-check: full cycle issues

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1191]
Here https://app.circleci.com/pipelines/github/iterative/dvc.org/3117/workflows/a076061d-75c2-49c0-842c-b1e324524312/jobs/3165

```
ls: cannot access '*.css': No such file or directory
ls: cannot access '*.jsx': No such file or directory
ls: cannot access '*.tsx': No such file or directory
ls: cannot access '*.ts': No such file or directory
```

and: 

```
error Command failed with exit code 2.
```

**Comment by casperdcl** [comment]
Ah the good ol' `set -eo pipefail` plus `yarn` itself checking exit codes. Will fix tmrw (well, later today) as I should probably sleep.
