### ISSUE TITLE
doc engine: fix scroll bar for the content sidebar

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1198]
We want for buttons to always stay on the screen and the sidebard to have its own scrollbar.

<img width="1440" alt="Screen Shot 2020-04-28 at 6 46 10 PM" src="https://user-images.githubusercontent.com/3659196/80554046-c3adfc00-8980-11ea-83aa-d55bd0b6a3ce.png">

**Comment by jorgeorpinel** [comment]
I thouoght it was only me because I use 125% zoom! But yep, I can confirm this on Windows/ Chrome as well:

![image](https://user-images.githubusercontent.com/1477535/80557384-590ab980-899c-11ea-9886-801f6700275b.png)

**Comment by shcheklein** [comment]
@jorgeorpinel it looks like a different problem(?) though. Create a separate ticket for this please.
