### ISSUE TITLE
core.loglevel doesn't exist but remains in docs

### ISSUE THREAD

**Issue by woodshop** [iterative/dvc.org#1199]
When setting the config option for `loglevel` (either programmatically or by editing the config file) my command returns the following error:
```bash
ERROR: configuration error - config file error: extra keys not allowed @ data['core']['loglevel']
```

As far as I can tell, core.loglevel was removed in https://github.com/iterative/dvc/pull/3321. However the current docs for `dvc config` continue to list this as a valid configuration option.

**Comment by shcheklein** [comment]
@woodshop good catch! Would you mind doing a PR? you can just click the Edit on Github button, remove it and submit an update online.

**Comment by woodshop** [comment]
Sure thing. Might not get to it for 24 hours though.
