### ISSUE TITLE
blog: can't develop/build locally on Win

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1204]
I'm on Windows (Git Bash on Cmder). I cleaned up mode modules, buid, cache, etc. to build from scratch. I ran `yarn` from scratch, which went well. I ran `yarn develop` and it built in a few minutes, no errors. But I get this when I go to http://localhost:8000/blog:

![image](https://user-images.githubusercontent.com/1477535/80777793-f9dbaf00-8b2b-11ea-9677-0955f37b1536.png)

(The rest of the site seems to work.)

Then I tried `yarn build` but it throws an error:

![image](https://user-images.githubusercontent.com/1477535/80778422-0a8d2480-8b2e-11ea-8693-de456e53f652.png)

**Comment by rogermparent** [comment]
Oh no! This must be my fault. I'm pretty sure with the Model resolvers we're doing path resolution of the sharp images in a way that works on Linux but not Windows. I'll get on this ASAP!

**Comment by rogermparent** [comment]
I have a possible fix in [this branch](https://github.com/iterative/dvc.org/tree/fix-windows-paths), but I need you to test it because I don't have any Windows machines to do so.

**Comment by jorgeorpinel** [comment]
It works for me Roger! Thanks a lot. I'm just going to merge your branch to the blog stuff I'm working on , if you don't mind. So the fix to this issue will be included in my coming PR, but your commit will be there.

**Comment by rogermparent** [comment]
Sounds fine to me!
