### ISSUE TITLE
user-guide: add pachyderm to related-technologies

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#121]
Probably after #576?

https://dvc.org/doc/dvc-philosophy/related-technologies

**Comment by shcheklein** [comment]
It's hard to put every existing tool to that page. I would instead put a link to the matrix and that blog post with some of these tools overview and mention that it's not the purpose of this page to cover everything.

**Comment by shcheklein** [comment]
Closing this. Pachyderm is a very different tool, and even though people asking us about the difference, probably not the right place to keep the full list of tools in this space.
