### ISSUE TITLE
сommunity banner is outdated

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#1214]
https://dvc.org/community

Is it the time to remove the banner about Pawel's talk?

Off-topic: The banner is huge (1/2 MB). It takes time to upload. It might be better to use smaller banners next time.

**Comment by shcheklein** [comment]
cc @andronovhopf

**Comment by shcheklein** [comment]
Closing in favor of #1277 . We'll set banner expiration date or remove it completely.

**Comment by andronovhopf** [comment]
SureI FYI I just got a banner made for our mailing list, so planning to
make a PR for that tomorrow or Tuesday
