### ISSUE TITLE
blog: tags URL should be under blog prefix

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1222]
https://dvc.org/tags/heartbeat -> https://dvc.org/blog/tags/heartbeat

- [ ] Don't forget to update existing links
- [ ] Check RSS (do we have it/need for tags?)

**Comment by rogermparent** [comment]
I ripgrepped for `tag/` and changed everything that matches to `blog/tag/`, which should take care of existing content.
We currently don't use tag data for any feeds, and I'd say adding tags to feeds would warrant another issue entirely.
