### ISSUE TITLE
blog links: mark external links with icon automatically

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1227]
Same as in the docs, e.g.:

![image](https://user-images.githubusercontent.com/1477535/80940733-46caba00-8da6-11ea-83ab-e0f79d430fde.png)

**Comment by shcheklein** [comment]
blog is not the same as docs though, have you seen something similar in other blogs?

**Comment by shcheklein** [comment]
I don't think we need this in blog. Closing this for now.
