### ISSUE TITLE
nav: add internal navigation sidebar to blog posts?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1228]
Blog posts tend to be organized in H2/3 headers. It would be nice to have a bar on either side (preferably right side like in docs) for internal navigation. It could be available only when there's enough space in the margin.

This is how it looks in docs:
![image](https://user-images.githubusercontent.com/1477535/80941092-19cad700-8da7-11ea-8061-d30eef55770b.png)

**Comment by shcheklein** [comment]
Not sure about this one. It's not docs. This content will force writers to care too much about these subsection titles. A lot of existing posts will look really terrible.

**Comment by jorgeorpinel** [comment]
Hmmm true. I guess it's not a common blog feature. We can always put links from the intro to other sections when we want people to be able to jump right to the main content.
