### ISSUE TITLE
blog: "number of comments" cache is too aggressive

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1232]
Caching is too aggressive. It should be around 1 minute at most (?). Right now it takes too long to wait to see the new value.

(it might be even that we don't reset it until the redeploy)

**Comment by shcheklein** [comment]
Making it p1 to at least check that we don't cache it infinitely. That would be a major p-0.

**Comment by rogermparent** [comment]
Looks like it's 900s (15m) right now. Let me get the github link to the exact point in `comments.js`

**Comment by shcheklein** [comment]
Let's test it on one of the older posts? to make sure that redeploy is not required at least

**Comment by shcheklein** [comment]
Fixed by #1250
