### ISSUE TITLE
links in image captions can't contain underscore

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1239]
E.g. Try linking to https://static.fossee.in/scipy2019/SciPyTalks/SciPyIndia2019_S011_Storing_a_few_versions_of_a_5GB_file_in_a_data_science_project_20191130.mp4 from an image caption. You get:

![image](https://user-images.githubusercontent.com/1477535/81038745-befbb300-8e6c-11ea-88c9-6e2b7475f1db.png)

because the caption is surrounded by underscores `_`, probaly.

**Comment by shcheklein** [comment]
does %-encoding solve the problem in this case? it can be a good solution then.

**Comment by jorgeorpinel** [comment]
Nope 🙁 

![image](https://user-images.githubusercontent.com/1477535/81040036-14858f00-8e70-11ea-90fa-81ef515c8956.png)

**Comment by jorgeorpinel** [comment]
Wait...

**Comment by jorgeorpinel** [comment]
Nope, `_` doesn't get encoded.

**Comment by jorgeorpinel** [comment]
Wait...

**Comment by jorgeorpinel** [comment]
Yes, that works! But you have to manually replace with `%5F` since URL encoders online at least won't encode `_`. In this case I just used `https://static.fossee.in/scipy2019/SciPyTalks/SciPyIndia2019%5FS011%5FStoring%5Fa%5Ffew%5Fversions%5Fof%5Fa%5F5GB%5Ffile%5Fin%5Fa%5Fdata%5Fscience%5Fproject%5F20191130.mp4`.

**Comment by shcheklein** [comment]
it's probably still a bug I would say, it's just we have a reasonable workaround here

**Comment by jorgeorpinel** [comment]
This hasn't been a problem again so closing (esp. since there's a workaround).
