### ISSUE TITLE
Sample Code wget broken

### ISSUE THREAD

**Issue by JoeMcGrath** [iterative/dvc.org#125]
Following the tutorial steps from `https://github.com/iterative/dvc.org/blob/master/static/docs/get-started/connect-code-and-data.md` leads to this command: `wget -q -O - https://dvc.org/s3/get-started/code.tgz | tar zx`which is unsuccessful.

Running wget to display full console shows that a 403 is returned when trying to access the bucket.

**Comment by shcheklein** [comment]
@JoeMcGrath thanks for the report! It should be fixed now. I think we did an update of that file just a few hours ago and forgot to make it public again. Please try again, and let me know if it works for you now.

**Comment by JoeMcGrath** [comment]
@shcheklein I can confirm its now available to download - thanks!
