### ISSUE TITLE
Gitpod should clone a fork

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1253]
> Extracted from https://github.com/iterative/dvc.org/pull/1226#issuecomment-624418719 and https://github.com/iterative/dvc.org/pull/1226#issuecomment-624437520

I tried using Gitpod from https://dvc.org/doc/user-guide/contributing/docs#development-environment to submit a change. It was all working nicely, (I even installed a VS Code plugin to the IDE.) But after committing with Git, I'm unable to push because I didn't grant Gitpod permission to push directly to dvc.org

![image](https://user-images.githubusercontent.com/1477535/81135210-c5e1fe80-8f1c-11ea-8ee8-497c7c540ed6.png)

Open source contributors will never have this permission. Can it be made so a fork is created in their accounts first, and then Gitpod launched from there?

---

For example, I tried with another account I own, @AyokVoluntarios, which doesn't have push access to this repo, but it also cloned the upstream directly:

![image](https://user-images.githubusercontent.com/1477535/81138738-a81a9680-8f28-11ea-9a74-cf5bc9ebce63.png)

So again, even if I tell Github to let Gitpod push to my repos, I simply can't do it from that account.

![image](https://user-images.githubusercontent.com/1477535/81138947-75bd6900-8f29-11ea-8189-dcdc2c18f8d7.png)

The user would need to configure the Git remote and branch manually from the IDE. Do you know whether that's the only solution, @nisarhassan12? Thanks

**Comment by nisarhassan12** [comment]
> I tried using Gitpod from https://dvc.org/doc/user-guide/contributing/docs#development-environment to submit a change. It was all working nicely, (I even installed a VS Code plugin to the IDE.) But after committing with Git, I'm unable to push because I didn't grant Gitpod permission to push directly to dvc.org

Thanks, @jorgeorpinel This is happening maybe because you have not granted Gitpod the permissions to do so. You can manage the access control here: https://gitpod.io/access-control/

![image](https://user-images.githubusercontent.com/46004116/81167793-45b8a900-8faf-11ea-9daf-c1095dda9f45.png)


> Open source contributors will never have this permission. Can it be made so a fork is created in their accounts first, and then Gitpod launched from there?

When a repo is opened where you don't have push access and you have made a change and are about to commit, A prompts appears from where one can fork and then push to his fork. Another way to fork is `F1` > `Fork`. I think it would be nice if it's documented in the project contributing guide.

![image](https://user-images.githubusercontent.com/46004116/81168766-1014bf80-8fb1-11ea-89a1-d74a24d134b8.png)

**Comment by jorgeorpinel** [comment]
> You can manage the access control

Unfortunately Gitpod wants access to manage repo settings and development keys so I don't feel comfortable giving it those permissions from my account, since I have admin access to the repo. Maybe for a developer in an org this would be OK but they will probably have a local dev env anyway.

![image](https://user-images.githubusercontent.com/1477535/81215225-9d024d80-8f9e-11ea-8267-fb2d6c548baa.png)

> When a repo is opened where you don't have push access and you have made a change and are about to commit, A prompts appears from where one can fork and then push to his fork. Another way to fork is F1 > Fork. I think it would be nice if it's documented in the projects contributing guide.

Yes, we would need to document this in the Gitpod block quote in https://dvc.org/doc/user-guide/contributing/docs#development-environment, would you like to send a PR @nisarhassan12? Feel free to use a `<details>` hidden section (example in https://dvc.org/doc/tutorials/get-started/configure)

But it may be turning a little complicated. Not sure how useful it will result. It's definitely a good option to have but... Casual contributors can make small changes directly from Github, and regulars will probably want to run things locally. For example it takes much longer to run the local dev server on Gitpod than on my Windows laptop. But anyway, if you can help us explain the whole process including forking etc up till the pull request is submitted (hopefully it's only a few steps) that would be great.

**Comment by jorgeorpinel** [comment]
I'm removing the note for now, please revert https://github.com/iterative/dvc.org/pull/1195/commits/87906e25832197da18f700be49e1a6d0885b7e7d and complete the guide when possible. Thanks

**Comment by nisarhassan12** [comment]
Thanks! I'll make a PR soon.

**Comment by jorgeorpinel** [comment]
No rush

**Comment by jorgeorpinel** [comment]
Thank you!

**Comment by nisarhassan12** [comment]
Hey @jorgeorpinel I have already made this PR https://github.com/iterative/dvc.org/pull/1262

**Comment by shcheklein** [comment]
Closing this, see motivation here https://github.com/iterative/dvc.org/pull/1262#issuecomment-631160576
