### ISSUE TITLE
cmd ref: -R flag for update command

### ISSUE THREAD

**Issue by nik123** [iterative/dvc.org#1259]
Command reference for `update` command should contain `-R`/`--recursive` flag.

See issue https://github.com/iterative/dvc/issues/3511 and PR https://github.com/iterative/dvc/pull/3760 in the core repo.

**Comment by jorgeorpinel** [comment]
Thanks. It will be updated if/when the flag is implemented and released. Currently it doesn't exist in the command. Best

**Comment by shcheklein** [comment]
@jorgeorpinel not sure why did we close this? https://github.com/iterative/dvc/pull/3760 there is core repo PR @nik123 has prepared. So, we indeed need a ticket.

**Comment by jorgeorpinel** [comment]
I didn't realize there was a PR for this and thouoght nik was a user reporting a bug 😅 

Updating the docs is a checkbox in the core repo PR too but yeah sure, doesn't hurt to have this too.

**Comment by shcheklein** [comment]
@jorgeorpinel that checkbox says " ... or issue, at least ..." :)

**Comment by nik123** [comment]
@jorgeorpinel sorry, it may not have been clear that there is PR for this. I've updated description with link to original PR.

**Comment by jorgeorpinel** [comment]
Thanks!
