### ISSUE TITLE
user-guide: describe our python version support policy

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#1278]
We will be dropping 3.5 in 1.0 release https://github.com/iterative/dvc/issues/3765#issuecomment-626844095 soon, and we'll need to explicitly clarify in our docs what's our python version support policy.

WHAT IS OUR POLICY? TBD

**Comment by jorgeorpinel** [comment]
Good idea. In https://dvc.org/doc/user-guide/contributing/core? Or maybe somewhere in https://dvc.org/doc/install

Note that it's possible to publish docs that are not found in the navigation sidebar, but they can be linked to from any page. We're considering doing that to some existing docs such as https://dvc.org/doc/user-guide/privacy

**Comment by chaytanyasinha** [comment]
@jorgeorpinel I feel like we should add it to https://dvc.org/doc/user-guide/privacy

**Comment by r0cketr1kky** [comment]
Hi @jorgeorpinel , can I take this up?

**Comment by efiop** [comment]
@shcheklein @jorgeorpinel I don't think that this is a "good first issue". We ourselves don't have a very clear plan for this.

**Comment by jorgeorpinel** [comment]
@chaytanyasinha @r0cketr1kky thanks for your interest. It seems like we don't really know our policy yet so this can't be worked on yet. Please try to find another one, feel free to contact me on Discord for direct guidance 🙂

**Comment by jorgeorpinel** [comment]
@efiop mabe you want to assign this to someone who will be defining the policy for now, at least until it's decided?

**Comment by efiop** [comment]
@jorgeorpinel Yeah, I'll assign to myself for now.

**Comment by shcheklein** [comment]
Looks like stale. Closing since I doubt we'll get to it soon.
