### ISSUE TITLE
guide: document run-cache

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#1289]
So far affected commands are run/repro which create and/or use run cache. And `push/pull/fetch/potentially status`) that transfer ~~(options for that are hidden for now)~~ run cache to/from remote. Run cache is located in `.dvc/cache/runs`.

**Comment by efiop** [comment]
Will also need to update run-cache flags in run/repro to explain them through the run-cache concept.

**Comment by sarthakforwet** [comment]
Hey there I wanna work on this issue . Could you assign me this ?

**Comment by efiop** [comment]
Hi @sarthakforwet ! I don't think it is suitable for contribution, as it is a WIP feature. Please check out `need-help` and `good-first-issue` labels, they should have something more suitable :slightly_smiling_face:

**Comment by jorgeorpinel** [comment]
Hi @sarthakforwet indeed please further explore the issues for something that seems a little smaller and more defined. I believe I sent some specific links in my GSoD email reply to you to some recommended issue labels. Feel free to reach out to me directly via email or on Discord for help on issue selection it you're still unsure. Thanks!

**Comment by jorgeorpinel** [comment]
A suggested place to start is to add an "execution and reproduction" section to the `dvc run` cmd ref. similar to this: https://github.com/iterative/dvc.org/pull/1464/files

**Comment by jorgeorpinel** [comment]
More info that would be good to include for this ticket, from https://github.com/iterative/dvc.org/pull/1448#discussion_r443124577:

> 1. Run-Cache can generate outputs in a suitable condition and that too indirectly (eg: only on run/repro), whereas a lockfile will always provide you with outputs without rerunning.
> 2. RunCache can generate lockfile. Even though you have a run-cache, you should still use lockfile because for the outputs.
> 3. get/import commands work well only if you have a lockfiile.

(Thanks @skshetry)

**Comment by jorgeorpinel** [comment]
Hello! So this continues to be a major discrepancy between released DVC and published docs. I know it's being worked on but at least basic mentions of this should exist in the docs for now. Is it still the plan for someone from engineering to submit a draft proposal adding such mentions? Thanks! Cc @efiop @shcheklein

**Comment by efiop** [comment]
@jorgeorpinel Likely no drafts until experiments are here or https://github.com/iterative/dvc/issues/4223 .

**Comment by jorgeorpinel** [comment]
Hi @efiop! I'm finally finishing up some basic docs for this (sort of needed to doc `dvc exp`). Quick questions:

> potentially status

1. `status` didn't end up working with the run-cache at all right?

2. `dvc gc` doesn't have a way to specifically DO, or DO NOT collect outputs referenced in the run-cache, right?

Thanks

**Comment by efiop** [comment]
1. Correct, not yet.

2. Correct.

**Comment by jorgeorpinel** [comment]
Feel free to reopen or make another issue if/when the run-cache implementation/terminology/etc change, or if more docs should be written. Thanks
