### ISSUE TITLE
we are getting 301 on direct URLs

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1302]
Again (we are solving this over and over again with Gatsby), we are getting 301s if you enter:

dvc.org/doc
dvc.org

in the browser.

It potentially affects SEO, it affects performance.

We need to put some CI check in place to prevent this from happening again.

**Comment by rogermparent** [comment]
I want to tackle this, but I'm not sure how exactly to replicate this problem. I can't get anything but 200s on either URL.
Is your browser automatically prepending `www.`? There's an explicit redirect entry for that.

**Comment by shcheklein** [comment]
My bad, @rogermparent . Browser redirects to https from http by default. `curl -v https://dvc.org` works absolutely fine.
