### ISSUE TITLE
Wrong item highlighted in the right menu

### ISSUE THREAD

**Issue by iKBAHT** [iterative/dvc.org#1306]
Str:
1) go to https://dvc.org/doc/command-reference/diff
2) click to "Example" item in the right menu

Actual:
"Example: Checking workspace changes" item will be highlighted

Expected:
"Example" item will be highlighted

Some ideas:
https://github.com/iterative/dvc.org/blob/master/src/components/Documentation/RightPanel/index.tsx#L44
A peculiarity of the navigation algorithm

**Comment by jorgeorpinel** [comment]
I think this is basically a duplicate of #753. @iKBAHT please add details in that one and close this one? thanks
