### ISSUE TITLE
ambassador team page

### ISSUE THREAD

**Issue by elleobrien** [iterative/dvc.org#1311]
Would it be easy to add a page for ambassador profiles? This might be an additional perk of joining. 

For example, Fedora has profiles for ambassadors (and other community members): 

https://fedoraproject.org/wiki/User:Mribeirodantas

Not that we need badges or this level of detail; just a "masthead" of sorts?

**Comment by shcheklein** [comment]
@andronovhopf it's a great idea! we would need to start with some UX - where do we want put that page? how do we get people there? 

We had another idea with @SvetaGr - create a "wall of love" - people sharing tweets about us, companies that use the product, etc ... may be ambassadors could be part of that page?

again, not sure about the name for page and where do we put it yet. So, let's start with that :)

**Comment by utkarshsingh99** [comment]
I think it would be ideal to have a new section in the Community Page for both these ideas.
A section like **Be an Ambassador** right before the **Learn** section would be appropriate, since it looks more relevant to being part of the community, I guess.
Also, the opening "Get the DVC Newsletter" wall image might seem like a repetition for subscribe and we can replace it with the Wall of Love, showing a collage of tweets on DVC.

**Comment by julieg18** [comment]
Are we still interested in creating an ambassador page/section somewhere? cc @iterative/websites, @jendefig

**Comment by jorgeorpinel** [comment]
Maybe as part of https://dvc.org/community

**Comment by jendefig** [comment]
@julieg18 Yes!  We need to work toward this end.  I really would like to have a place where Ambassador Profiles are shown as Elle originally mentioned.  I think it would be better if we could have a "Meet Our Ambassadors" section and you see a pic with their faces, name, title, and country they are from with a flag.  Then you can click on it to get their full profile, contact, etc.  

In the Community Pages current state, I think it would be logical after the Testimonials.  But before this [we need to finish this.](https://github.com/iterative/dvc.org/issues/2603).

**Comment by shcheklein** [comment]
Not relevant at the moment.
