### ISSUE TITLE
coding style guidelines missing from Docs and Website Page 

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc.org#1314]
The link in the text in `coding style guidelines` on the page [Docs and Website page](https://dvc.org/doc/user-guide/contributing/docs) which ideally should list principles and guidelines seems to be a dead in-page link. 

The referred link is https://dvc.org/doc/user-guide/contributing/docs#code-style-guidelines on clicking on the text, but it seems that there is no such section marked on that markdown file.

There is a mention of Prettier's usage for code formatting, but that has been put under [Development Environment](https://dvc.org/doc/user-guide/contributing/docs#development-environment).
Maybe we can add another section named as `Code Style Guidelines`, just like [Doc Style Guidelines](https://dvc.org/doc/user-guide/contributing/docs#doc-style-guidelines-javascript-and-markdown), moving the info and steps related to Prettier into it, and refer it through `coding style guidelines`

**Comment by jorgeorpinel** [comment]
> The link in the text in coding style guidelines on the page Docs and Website page which ideally should list principles and guidelines seems to be a dead in-page link.

Good catch @utkarshsingh99, it should link to `#doc-style-guidelines-javascript-and-markdown`. Would you like to submit a quick PR for this?

> There is a mention of Prettier's usage for code formatting, but that has been put under Development Environment.

That mention is OK there, as running Prettier is (automatically) part of the dev env. It's mentioned again in the doc style guidelines section. But if you have a strong opinion on how to avoid duplication here feel free to include this change in your PR.

> Maybe we can add another section named as Code Style Guidelines, just like Doc Style Guidelines

Hmm that's probably not necessary, the existing doc style guidelines section applies both to JavaScript and Markdown.

**Comment by utkarshsingh99** [comment]
Yeah, I would be happy to make a PR for this.
Will do this by tomorrow (IST)

**Comment by jorgeorpinel** [comment]
OK thanks and I'm glad you seem to be taking a deep dive into some of our docs. I'm a little worried that we only have another 10 days left in the month though so hopefully you can explore a more substantial issue from https://github.com/iterative/dvc.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 for example and try to address it so we still have time to interact and then work on your GSoD project ideas after that.

**Comment by jorgeorpinel** [comment]
Hey @utkarshsingh99 actually I'm fixing this in f0c0ac45. Please focus on the `good-first-issue` list. Thanks

**Comment by utkarshsingh99** [comment]
Sure. 
Glad to know this was resolved. :)
Should I close this issue then?

**Comment by jorgeorpinel** [comment]
> Should I close this issue then?

No, it will be closed automatically when my PR is merged. Thanks
