### ISSUE TITLE
define the spaces/tabs policies and create checks.

### ISSUE THREAD

**Issue by mvshmakov** [iterative/dvc.org#1315]
There is a mixture of tabs/spaces in the repo. It would be better if there is only one unified standard for all of the codebase/documentation. In addition, it is a good practice to introduce some CI/pre-commit checks considering this convention.

The issue was revealed in this PR: https://github.com/iterative/dvc.org/pull/1305

**Comment by shcheklein** [comment]
@mvshmakov what bothers me here is that we already have `useTabs` set to false:

```
  "tabWidth": 2,
  "useTabs": false,
```

in the https://github.com/iterative/dvc.org/blob/master/.prettierrc

and we do run it on a pre-commit hook that is installed when you run `yarn`.

I think the only place we allow spaces are code blocks. And probably prettier ignores them (and rightfully so). It feels there is some overlap between your editor settings and our `.prettierrc`. What editor do you use? Could you share the settings for it?

**Comment by mvshmakov** [comment]
@shcheklein I guess I have found the issue. I use Visual Studio Code with custom config, which you can see here: https://pastebin.com/qEjpgKsV. It has a section `"prettier.useTabs": true` which I totally have forgotten of. I suppose you are right about setting overlapping and it was totally my bad.

**Comment by jorgeorpinel** [comment]
I think both VSC and Prettier let tabs in code blocks alone. There's 53 instances of this in content/docs right now.

**Comment by jorgeorpinel** [comment]
If there's a way to enforce tab->space with Prettier then I would support the no-tab policy. Otherwise I vote actually to use tabs in sample output. Maybe I'm not getting why that is a problem?

**Comment by shcheklein** [comment]
@jorgeorpinel I think it's already enforced in our settings? (`useTabs: false`) prettier probably just ignores code blocks

**Comment by jorgeorpinel** [comment]
OK, so my point is if Prettier and IDEs ignore tabs in code blocks (which makes sense) trying to enforce this will be difficult and for starters I don't see why it's desirable. If anything having tabs in sample output is in a way more realistic, as that's what `dvc`/other commands print to stdout.

**Comment by noahbrenner** [comment]
I generally prefer to create an [.editorconfig](https://editorconfig.org/) file. Since Prettier [also uses this file](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options), that allows `.editorconfig` to be a central location to configure both your editor/IDE and Prettier.

**Comment by jorgeorpinel** [comment]
Thanks @noahbrenner but I think still Prettier and IDEs will ignore tabls in code blocks, regardless of how the tab->spaces policy is configured.

**Comment by noahbrenner** [comment]
@jorgeorpinel That makes sense. It wouldn't fix existing codeblocks, but I'd expect that an `.editorconfig` file would at least help avoid creating more instances of this issue in the future (assuming that all contributors have Editor Config plugins for their IDEs, which might not be a good assumption). That doesn't eliminate the need for other automated checks and fixes, it's just another potential tool to help the process along.

**Comment by jorgeorpinel** [comment]
I'm guessing we are OK to close this since there have been no other comments in a long time, but lmk if you have additional thoughts please. Thanks!
