### ISSUE TITLE
use-cases: add "Ways to organize global storage"

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#133]
E.g. `first` and `second` are different git projects, that share the same dvc remote

```
# first
dvc add data
dvc push

# second
cp path/to/first/data.dvc .
dvc pull
```

**Comment by efiop** [comment]
Also, as a submodule:

```
# project1
dvc add model.pkl
dvc remote add mygs gs://bucket/prefix -d
dvc push model.pkl.dvc
git add model.pkl.dvc .gitignore .dvc/config
git commit -s "add model"
git push

#project2
git submodule add https://github.com/user/project1 # note that it doesn't have to be github
cd project1
dvc pull model.pkl.dvc
cd ..
# Now you can access your model.pkl at ./project1/model.pkl
```

**Comment by dashohoxha** [comment]
It seems that `dvc import` has made obsolete this way of data sharing between projects.
I am closing this issue. Please feel free to reopen in case I have missed something.

**Comment by jorgeorpinel** [comment]
Not the first example, which doesn't require a Git repo. The question is where to include this example in the docs...

**Comment by jorgeorpinel** [comment]
Maybe as an **Example: Simulating import without Git**  in the `dvc import` cmd ref?

**Comment by jorgeorpinel** [comment]
It seems this is indeed obsolete now, since we have `dvc get` even for non DVC and non Git projects.

**Comment by jorgeorpinel** [comment]
If I'm wrong please add it as a checkbox in this epic: #820
