### ISSUE TITLE
ci: Restyled doesn't work correctly with forks (outside contributors)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1330]
Noticed in https://github.com/iterative/dvc.org/pull/1316#issuecomment-631283253

Explained in https://github.com/iterative/dvc.org/pull/1321#issuecomment-632304028

> Hmmm this is strange. I thought Restyled used to make PRs into PR branches (meta) but this is going straight to master. In this case the original PR (#1316) is from an outside contributor so maybe that's the reason? Same problem with #1329 and #1319.
>
> #1310 in contrast worked properly, as a PR into the feature branch (inside the upstream).

**Comment by shcheklein** [comment]
I'm not sure this a bug - this is by design. Most likely it was done so that maintainers in the main repo see the restyled PR.

**Comment by shcheklein** [comment]
The idea is that it creates a duplicate PR that will be "following" the main one. And in this case when main one is ready maintainers are supposed to merge the "follower".

**Comment by jorgeorpinel** [comment]
> I'm not sure this a bug - this is by design. The idea is that it creates a duplicate PR that will be "following" the main one.

OK. If it keeps up to date with the original PR then that would be logical, especially if it closes itself out if the formatting is fixed by the collaborator. I guess it can't open a PR to the fork since it doesn't have the user GH account permissions. I'll keep an eye on how this works in the future.
