### ISSUE TITLE
add Windows mode to the documentation examples

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc.org#134]
There was recently an issue raised at the community channel related with the way Windows handle paths / interprets slashes; it ocurred while reading the tutorial, so I'm assuming there's no clear awareness of Windows's shell on the docs.

**Comment by shcheklein** [comment]
Ideally I think next step should be to implement a switch for the documentation - to show Windows/Linux mode.

**Comment by jorgeorpinel** [comment]
BTW #759 is a duplicate of this. But there's more info over there so I'll close this one. Thanks
