### ISSUE TITLE
Missing Katacoda tutorial link for Get-started

### ISSUE THREAD

**Issue by kurianbenoy** [iterative/dvc.org#1347]
Why is the interactive tutorial button of  Katacodo not being mentioned for get-started example when 
there is a get started tutorial in Katacoda?

https://www.katacoda.com/dvc/courses/get-started

Is there something missing in the Katacode tutorial in the current form, which needs an update?

**Comment by jorgeorpinel** [comment]
Good observation. However we are completely rewriting the Get Started now. See https://github.com/iterative/dvc.org/pull/1074 so yes, that Katacoda is totally outdated. Probably all of them in fact :/ we haven't touched them in almost a year.

**Comment by kurianbenoy** [comment]
Ok, awesome!
