### ISSUE TITLE
remove WebDAV as a remote option

### ISSUE THREAD

**Issue by djwessel** [iterative/dvc.org#1355]
#1187 Added a reference to WebDAV support to the docs, however WebDAV is not yet supported iterative/dvc#1153

Context: 714405205080539168

**Comment by jorgeorpinel** [comment]
OK done in 3cfbf9ba. We can just revert that commit to restore the WebDAV info later.

**Comment by jorgeorpinel** [comment]
So iterative/dvc/pull/3647 is merged but this isn't released @efiop (assuming you know from Discord conversation)?

**Comment by efiop** [comment]
@jorgeorpinel That PR is not merged. Contributor closed it and promised to send a new one later. We can safely remove webdav from docs for now :slightly_frowning_face:
