### ISSUE TITLE
term: stop using "DVC-file" and "stage file"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1366]
> Extracted from #1255 

After 1.0, the term DVC-file only refers to raw/initial data versioned with `dvc add/import/import-url`. however users seem to mostly refer to such files as "dvc file" or `.dvc` file or just `[data].dvc`. Since we have all these alternatives, let's remove the formal term DVC-file? Also since there's not `dvc.yaml` (pipelines file) which adds to the confusion.

We could also address the "import stage" check box from #608:
> -  Eliminate "import stage" term. Just use imported .dvc file or something like that

~~I suggest we always use the specific `[data].dvc` form in our docs.~~

See these changes as an example of what to do: https://github.com/iterative/dvc.org/pull/1370/commits/1008321bb58a6fc23514e12cfa6b97d0d41f27e6

UPDATE: Decided for `.dvc` file instead. See https://github.com/iterative/dvc.org/issues/1366#issuecomment-634975331 just below.

UPDATE: Similarly, we should stop using "stage file" in favor for `.dvc` file as well.

UPDATE: Do not include instances in DVC command output examples.

UPDATE: See https://github.com/iterative/dvc.org/issues/1366#issuecomment-643123274 for known progress

**Comment by shcheklein** [comment]
Agreed. I haven't seen the `[data].dvc` form though - looks too complicated. We can just use `.dvc` files - very explicit and clear.

**Comment by jorgeorpinel** [comment]
@utkarshsingh99 I think this chore is a little too boring TBH, I don't want you to suffer with this any more! Can you just please remind us the list of files that have been done so far up to your 2nd PR (#1408)? Thanks again for the help, BTW! I'll take it from there.

> If you want to upload the remaining changes you have to a new branch in your fork and open a draft PR so I can take it over that would also be OK, up to you.

**Comment by utkarshsingh99** [comment]
Sure.
1. **Command Reference**
  - _PR 1 #1372_ 
     - add.md
     - get-url.md
     - get.md
     - init.md
     - move.md
     - repro.md
  - _PR 2 #1408_ 
     - fetch.md
     - import.md
     - import-url.md
     - list.md
     - pull.md
     - push.md
     - remove.md
     - status.md
     - update.md
2. **API Reference**
  - _PR 1 #1372_ 
     - get_url.md
3. **Install**
  - _PR 1 #1372_ 
     - plugins.md
4. **User-Guide**
  - _PR 2 #1408_
      - dependency.md
      - dvc-project.md
      - external-dependency.md
      - import-stage.md
      - output.md
