### ISSUE TITLE
config: document the way config files play together, add some how-tos or examples?

### ISSUE THREAD

**Issue by kopytjuk** [iterative/dvc.org#1368]
EDIT by @shcheklein 

Repurposed from a few issues - both come from some misunderstanding/lack of proper docs on how config files (default vs local vs system vs global) play together.

https://github.com/iterative/dvc.org/issues/1368#issuecomment-634456922

------------------------

Currently, there are only two ways to handle secrets (e.g. connection strings, tokens, etc)

1. Use `.dvc/config.local` file. Since this file is not shared among developers in Git, a team has to agree on a local configuration to pull/push data.
2. Use a single environment variable, e.g. `AZURE_STORAGE_CONNECTION_STRING` - but if one has different storage destinations, one variable is not enough.

It would be very handy to use `.dvc/config` but with own placeholders for secrets:

```
['remote "my-azure-remote"']
url = azure://my-container/dvc/
connection_string = $MY_SECRET
```
If the right secret is set, we can share `.dvc/config` without revealing secrets in Git.

**Comment by kopytjuk** [comment]
> It's not a well known or documented feature of DVC, but DVC merges sections with same name from different configs. What it means in our case ...

Hey, thank you for your idea - that "merging" behaviour was not known to me - seems like a good solution.

**Comment by jorgeorpinel** [comment]
Checking back on this, for now I made a small update to the `dvc config` ref. (see https://github.com/iterative/dvc.org/pull/3359) but the larger change will be to address https://github.com/iterative/dvc.org/issues/340 which includes this one. Closing as dupe
