### ISSUE TITLE
doc: replace `dvc` code block lang. for `cli`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1369]
We use ` ```dvc ` for all kinds of console session examples throughout blocks, not just DVC commands (sometimes there's no DVC command in the block). Maybe we should change to ` ```cli `? or ` ```console ` (standard)

This applies to Markdown file processing.

UPDATE: See https://github.com/iterative/dvc.org/issues/1369#issuecomment-1144532818 below.

**Comment by shcheklein** [comment]
My 2cs. It's too specific too `dvc` I would say - it's literally bash + dvc syntax. `cli` or `console` are too generic? and can overlap with existing highlighters?

**Comment by jorgeorpinel** [comment]
Yes maybe you're right.

> can overlap with existing highlighters?

There are other built-in highlighters? I thought we only had dvc, usage, py, json, and yaml

**Comment by shcheklein** [comment]
yep, there are some taken already https://prismjs.com/#supported-languages

**Comment by jorgeorpinel** [comment]
Nice. So neither `cli` nor `console` are taken (the latter I know Github has but it's custom to them). Only `bash` and `shell` are taken.

**Comment by jorgeorpinel** [comment]
> It's too specific too dvc I would say - it's literally bash + dvc syntax

Yes but what if in the future we want to support special highlighting in the YAML file since there are some DVC schema specific fields in .dvc files and dvc.yaml? We would just extend the `yaml` highlight right? Same for `bash` in that case, we should just use the existing one and extend it. Except we have users in all sorts of shells, not just Bash, thus I vote for `console` (copying GH) or just `cli` which can be based of `bash`.

But anyway this is a minor detail over all. No strong opinion or any urgency

**Comment by shcheklein** [comment]
Good point, @jorgeorpinel ! I think `console` is good then. I wonder how will GH highlight it.

**Comment by MerlynMShelley** [comment]
> We use `` ```dvc `` for all kinds of console session examples throughout blocks, not just DVC commands (sometimes there's no DVC command in the block). Maybe we should change to `` ```cli ``? or `` ```console `` (standard)
> 
> This applies to Markdown file processing.

Yep, in workflows it's quite easy to understand the standard ```console``` to describe a console session.

**Comment by MayankGoel28** [comment]
Just to be clear, this means all the codeblocks which use `` ```dvc`` will now be `` ```console``?

**Comment by MayankGoel28** [comment]
@jorgeorpinel is this a generic substitution of all `` ```dvc`` to `` ```console``? Wanted to confirm as there's some discussion on this. If so, I can apply a regex script to do so.

**Comment by jorgeorpinel** [comment]
Hi @MayankGoel28 and sorry for the delay (we're really busy recently releasing DVC 1.0). No, this would require customization of the JS engine code first, and then also changing the md content, yes.

**Comment by jorgeorpinel** [comment]
This will be resolved by #3396 but we can keep this open to update the contents (mass-replace ` ```dvc` for ` ```cli `.
