### ISSUE TITLE
add a note about reflinks and how space is calculated in the tutorial

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#139]
In our article https://dvc.org/doc/tutorial/define-ml-pipeline , we use `du` to show that space taken by the repo didn't double. That works with hardlinks, but `du` is not smart enough when it comes to reflinks, which it counts as separate full-blown filse and accounts for their size two times(for the cache file and for the reflink), which makes it confusing for the mac users https://github.com/iterative/dvc/issues/1442 . We should add a note about it.

**Comment by efiop** [comment]
Note: to prove that no duplication occurs, we could use `df` utility to see that free space on the drive indeed didn't decline by the file size that we are adding.

**Comment by kurianbenoy** [comment]
Can I work on this issue?

**Comment by shcheklein** [comment]
@kurianbenoy absolutely, feel free to start working on this! Join the dvc.org/chat and #dev-docs channel if you need any help.

**Comment by kurianbenoy** [comment]
Add docs in tutorials about various link types in this page as well when documentation is [ready for this](https://github.com/iterative/dvc.org/issues/265).

**Comment by mroutis** [comment]
Someone got confused on Discord because the tutorial implies a cache type of `hardlink / symlink / reflink`
https://discordapp.com/channels/485586884165107732/485596304961962003
