### ISSUE TITLE
docs: support CSV/TSV language highlighting/autoformatting in Markdown

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1390]
UPDATE: Jump to https://github.com/iterative/dvc.org/issues/1390#issuecomment-638990359

---

I get `warn Query takes too long:` (among other warnings) several times when running `yarn develop`. Sometimes more, sometimes less. They seem to always be related to blog posts.

Here's an example:

```
...
warn code block language not specified in markdown. applying generic code block
warn unable to find prism language 'csv' for highlighting. applying generic code block
warn Query takes too long:
File path: C:/Users/poj12/dvc.org/src/templates/blog-home.tsx
URL path: /blog/page/3
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 3,
        "nextPage": "/blog/page/4",
        "previousPage": "/blog/page/2"
    },
    "skip": 16
}
warn Query takes too long:
File path: C:/Users/poj12/dvc.org/src/templates/blog-home.tsx
URL path: /blog/page/4
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 4,
        "previousPage": "/blog/page/3"
    },
    "skip": 25
}
```

**Comment by jorgeorpinel** [comment]
I guess the first 2 warnings are not about the blog. Since `csv` is not in https://prismjs.com/#supported-languages should we just remove that language from our block quotes and use plain ones?

**Comment by rogermparent** [comment]
This is a new feature introduced in a Gatsby patch update we upgraded to a bit ago- I get them too, and I'm pretty sure everyone will with our current setup. 

The site's building as it did before, but unlike before it's warning us about the specific queries that take an above-average time to build. You can see it's usually indexes because those pages have the most image transforms: not only do we use `gatsby-transformer-sharp` there, but there's actually two different `big` and `small` queries that make four transforms each, doubling the amount of transforms on an already transform-heavy page.

**Comment by jorgeorpinel** [comment]
OK so maybe we can just discuss about the CSV/TSV highlighting in this issue. Is it easy to add even when not supported by prism? It would be pretty useful for `dvc plots` examples.

**Comment by rogermparent** [comment]
@jorgeorpinel Seems like both Prism and the Gatsby plugin we use it with support adding custom language definitions. I can't imagine CSV/TSV would be too difficult to add to that, but the question is then *what do we even highlight*? Especially in TSV.

Alternatively, we could add a custom language for `dvc plots` examples specifically such that we highlight DVC-relevant data.

Another more advanced alternative would be to make a rich component that replaces `csv` type blocks, displaying the data in a table with something like a switch or toggle button to allow users to view/copy the code.

**Comment by jorgeorpinel** [comment]
Glad to read that.

> the question is then what do we even highlight?

Yeah good point. Just the headers and commas or tabs I guess... Ha. Probably not worth it unless the columns could actually be aligned to look like a table or transformed into an md table somehow — and I'm not sure we really need/want that.

> rich component that replaces csv and tsv type blocks, displaying the data in a table with something like a switch or toggle button

Yes exactly. But I guess it's just a nice-to-have feature request at this point. Not a priority

**Comment by shcheklein** [comment]
> rich component that replaces csv and tsv type blocks, displaying the data in a table with something like a switch or toggle button

the only thing I would do is may be some highlighting and font size, but we should not be transforming code blocks into anything fancy. Code blocks preserve the formatting, you should be able to copy/paste the value from them as is.

**Comment by jorgeorpinel** [comment]
> GitHub previews csvs as a table

@rogermparent how can we see that, BTW? Here's a `csv` code block, it's not transformed:

```csv
h1,h2,h3
val1,val2,val3
val4,val5,val6
```

> you should be able to copy/paste the value

A fancy widget could have a 📋 icon to copy the values.

But yeah again, I don't think something fancy is needed either. Maybe just a custom highlighter to align the columns (if possible), bold the headers, and color the commas, something like:

```json
*h1* ,  *h2* ,  *h3*
val1 ,  val2 ,  val3
val4 ,  val5 ,  val6
```

**Comment by rogermparent** [comment]
> @rogermparent how can we see that, BTW? Here's a csv code block, it's not transformed:

I meant when you open a .csv file in a repository, not in comments. Markdown and yaml files similarly display frontmatter. I don't think we have a csv in this repo, but [Markdown files definitely do something similar with frontmatter](https://github.com/iterative/dvc.org/blob/master/content/authors/dmitry_petrov.md). I could be misremembering this happening with CSV.

**Comment by rogermparent** [comment]
[Here's an example of GitHub's rich CSV preview from another repo](https://github.com/goodby/csv/blob/master/example/user.csv)

**Comment by shcheklein** [comment]
> Here's an example of GitHub's rich CSV preview from another repo

so, this is exactly a code block. Code blocks should be preserved for the reasons I mentioned above. I think we can apply only colors, fonts, may be some whitespaces but carefully.

> A fancy widget could have a 📋 icon to copy the values.

I think we are breaking a convention here if we create something "fancy"

**Comment by julieg18** [comment]
`prismjs` now supports `csv` highlighting. Here is how it looks on dvc.org:

![image](https://user-images.githubusercontent.com/43496356/147122751-bc20e009-3b5f-487e-9fad-7266591b75ce.png)

Though, with our default prismjs styling, the text barely changes, we can update the color/background-color/font of the commas or the text if desired.

**Comment by jorgeorpinel** [comment]
Looks like it just color-codes tokens vs separators. Better, but table alignment would really be ideal. We can always do that part manually or with something like https://stackoverflow.com/a/51471616/761963
