### ISSUE TITLE
docs: remove condescending/scary language

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1394]
> Continuation of #608

Here's a good article about this: https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p#what

TL;DR: Presenting something as "extremely simple" (with the intention of selling a benefit) may result in the reader feeling intimidated, esp. if they don't find the topic simple.

Examples

```
simply
easy
basically
clearly
everyone knows
just
obviously
of course

As you/we can see, ...
It's well known
```

Some of these have legitimate uses like "just" as a quantifier e.g. _just one thing_ vs. as a qualifier e.g. _you can just xyz_.

To fix: _simply_ removing it works in most cases. If the intention was to emphasize something, be more descriptive e.g. _now this can be easily done_ -> _this feature aims to makes the process easier_.

**Comment by kurianbenoy** [comment]
Can I work on this task?

**Comment by mformihir** [comment]
After running [alex](https://alexjs.com/), I've quite a lot of occurrences of condescending language, there are too many files to change at once.

Some examples of files that contain condescending language are: 
[checkout.md](https://dvc.org/doc/command-reference/checkout)
[commit.md](https://dvc.org/doc/command-reference/commit)
[config.md](https://dvc.org/doc/command-reference/config)
[destroy.md](https://dvc.org/doc/command-reference/destroy)
(and many more)

Committing changes to too many files at once might be hard to review. Should I list all the files here and then start fixing one by one, or should I propose multiple changes over a single PR, @jorgeorpinel ?

**Comment by jorgeorpinel** [comment]
Nice tool @mformihir! Let's give #1396 some time first, since it's already trying to address this issue, and come back to your report after that.

**Comment by jorgeorpinel** [comment]
p.s. You may want to find something else to work on in the context of GSoD for now.

**Comment by mformihir** [comment]
Should I go for this now, @jorgeorpinel ?

**Comment by jorgeorpinel** [comment]
@mformihir only if you can find condescending language that's not included among these changes, which are already in progress by another person: https://github.com/iterative/dvc.org/pull/1396/files

Other than that any issue you find that doesn't seem to be in progress by anyone else is fair game, no need to wait for my confirmation if you're reasonably certain. Just send a PR 🙂 

Also, no need for a huge contribution. A small PR would be best, and once it's merged we can work on other small ones. the point here is to see how we collaborate (in the context of the GSoD applications). Thanks

**Comment by jorgeorpinel** [comment]
@mformihir actually! Yes, please take on this issue as it has been dropped by the previous person attempting to address it. You can probably start by copying some of the changes in https://github.com/iterative/dvc.org/pull/1396/files (but please review all the comments in that PR because some changes weren't correct).

**Comment by jorgeorpinel** [comment]
P/s And again, no need for a huge contribution. A small PR would be best, even if it only addresses this issue partially. Thanks

**Comment by mformihir** [comment]
@jorgeorpinel Alright! I'll start out with small ones.

**Comment by iesahin** [comment]
We have some `simply` in docs: 
<img width="1728" alt="Screen Shot 2022-05-18 at 19 42 12" src="https://user-images.githubusercontent.com/476310/169097086-2ba4544f-df24-40db-99c6-563df528bf03.png">

**Comment by iesahin** [comment]
But not many "of course"s

<img width="1728" alt="Screen Shot 2022-05-18 at 19 50 47" src="https://user-images.githubusercontent.com/476310/169098514-e518bcac-d047-4b69-8e0e-5f879bc280a4.png">

**Comment by casperdcl** [comment]
idk about the [examples listed in the OP](https://github.com/iterative/dvc.org/issues/1394#issue-631044269) as being "scary" but they are definitely too verbose/distracting for docs IMO. Make things sound like an informal blog rather than a concise user-oriented give-me-a-solution-to-my-problem-now style.
