### ISSUE TITLE
rewrite interactive tutorials

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1400]
Introduction of interactive tutorials was an important and good step, but content and structure is in a pretty bad shape. We need to:

- Integrate the repo with them into dvc.org repo?
- [ ] Review and delete overlapping, too niche scenarios
- [ ] Review other tutorials content - we do strange things there (like use of `--no-scm` which is clearly not important) in the get started, etc.

I suggest we start by focusing on Get started scenario first (after the new Get started is implemented).

Then we need to decide on the docs end what are we doing with technical Use Cases, Tutorials, etc - we need to find some name for these "DVC recipes" (DVC applies to different real world situations), put all of them here and try to implement (reuse) interactive tutorials for them.

We need to create a some common framework to put example from command reference in to Katacoda. It means for example that we have multiple scenarios per page. Probably we will have some common code that runs before each scenario.

Making the first part - reviewing and writing Get Started a p1.

**Comment by kurianbenoy** [comment]
Just had a small quick thought in my mind, As a download button, can we give an option to download the docs as PDF?
cc: @jorgeorpinel @shcheklein

**Comment by shcheklein** [comment]
@kurianbenoy check this one https://github.com/iterative/dvc.org/issues?q=is%3Aissue+is%3Aopen+epub+

**Comment by iesahin** [comment]
> Integrate the repo with them into dvc.org repo

I can work on this one. Would you like to preserve the git history of [katacoda-scenarios](https://github.com/iterative/katacoda-scenarios) here? It can be possible to add it as a subtree or submodule to the base repo but I don't think it's necessary.  @shcheklein @jorgeorpinel

**Comment by jorgeorpinel** [comment]
> Would you like to preserve the git history of katacoda-scenarios here?

Only if they work (for the most part) on DVC 1.0, in which case the existing ones could be copied to the `v1` branch of this repo. Then merge that to `master` (latest) so we can start updating them for 2.0 there.

Please no submodules/trees. What file structure are you thinking? Thanks

**Comment by iesahin** [comment]
Actually I'm thinking to copy mentioned repo to the root of this one and put a file describing the root of the scenario tree to katacoda as described [here](https://www.katacoda.community/git-repository-structure.html#moving-katacoda-content-to-sub-directory). 

I think it would not worth it to preserve the git history. I'll just do a single commit to `v1` and update on `master`. Is this plan OK?

**Comment by shcheklein** [comment]
@iesahin is there a strong reason to migrate it into the single repo? If not, I would not worry too much about it and keep it in the second repo, I think we can create even a separate ticket to discuss that.

**Comment by jorgeorpinel** [comment]
It's the first check box in this issue's description @shcheklein 🙂 but I do agree that's not very important or impactful. Actually updating the scenarios should be the first thing to do here.

> Is this plan OK?

Seemed reasonable @iesahin except for katacoda.yaml (I'd just mention it in the README). But anyway, let's leave that subtask for later (updated issue desc.).

**Comment by jorgeorpinel** [comment]
Hi @iesahin 👋 just for visibility, what's the overall status of this epic? I know the Get Started scenarios are all updated 🎉. What about Examples and Tutorials? Do you need help reviewing/deciding anything on those fronts? Is there a roadmap of which new scenarios (if any) will be added? Thanks!

**Comment by iesahin** [comment]
Hi @jorgeorpinel I'll continue updating examples and tutorials. I containerized the GS scenarios and will continue to build containers for each scenario to test them continuously. Thanks.

**Comment by jorgeorpinel** [comment]
Thank you!

**Comment by shcheklein** [comment]
@iesahin what is the status of this? can we now close it and move other things to a separate tickets?

**Comment by iesahin** [comment]
There are tutorials besides the Get-Started and they need improvement but I think these should be with the individual tickets. As we improve GS docs, we need to apply parallel content to the scenarios. I think we can close this now.
