### ISSUE TITLE
nav: can't have 2 items with the same name, apparently

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1406]
I added this to top level of sidebar.json:

```json
  {
    "slug": "get-started",
    "source": "get-started/index.md",
    "children": [
      "1",
      "2",
      "3"
    ]
  },
```
without removing the other Get Started inside Tutorials:

![image](https://user-images.githubusercontent.com/1477535/84068010-fa1e6400-a98d-11ea-8c42-9329ef361802.png)

But the link of the added on in the top level goes to /doc/tutorials/get-started 😕 

![image](https://user-images.githubusercontent.com/1477535/84068239-49649480-a98e-11ea-85e1-28c941a77362.png)

I have to change the slug to something else for it to work properly, e.g. /doc/getting-started is OK.

**Comment by jorgeorpinel** [comment]
Any chance you could make a quick diagnostic @rogermparent ? 🙂 Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel can we survive with just making it unique for now? does not look like a big deal to me

**Comment by rogermparent** [comment]
The issue might actually just be this redirect because of the particular page you're making.
https://github.com/iterative/dvc.org/blob/5a58811a1dac48dfbfbb92dde91558056ad274d1/redirects-list.json#L22

**Comment by jorgeorpinel** [comment]
Hey thanks Roger, yeah I also noticed that recently (https://github.com/iterative/dvc.org/pull/1412#issuecomment-643519893) so let me double check whether this is even a valid issue...

**Comment by jorgeorpinel** [comment]
Yeah sorry, it was just the redirect 😋
