### ISSUE TITLE
cmd ref: doc plots diff --targets with revisions usage

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#1425]
Mixing `--targets` option and providing multiple `revisions` for `dvc plots diff` might end messy.
Eg:
`dvc plots diff --targets t1.json t2.csv HEAD v1 v2` - parser does not know how to handle that.

We should include some note for `dvc plots diff` to hint possible use cases:
`dvc plots diff HEAD v1 v2 --targets t1.json t2.csv`
`dvc plots diff --targets t1.json t2.csv -- HEAD v1 v2`

Related https://github.com/iterative/dvc/issues/3962

**Comment by jorgeorpinel** [comment]
Thanks, interesting. I'm not sure I get this though. The title talks about --template + multiple revs, but the example uses multiple --targets and multiple revs.

**Comment by pared** [comment]
@jorgeorpinel thanks :sweat_smile:

**Comment by jorgeorpinel** [comment]
Haha np! Got it, so it's a question of ordering the cmd arguments/options correctly, right? OK thanks for reporting this!
