### ISSUE TITLE
sidebar dropdown toggle

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc.org#1427]
It would be good if the user is able to toggle the dropdowns containing sub-pages.
For example, 
![Screenshot from 2020-06-12 09-07-17](https://user-images.githubusercontent.com/32031518/84462264-330b5100-ac8c-11ea-9031-2a019520fd46.png)
Let's say I need to go back to the `Tutorials` section to view another page.
I tried clicking back on the `Command Reference` again to collapse it rather than scrolling all the way up in the sidebar.
But it just displays the home page of `Command Reference`. Maybe if clicking on the arrow next to it could collapse it and then display `Command Reference`'s page, the sidebar would be more intuitive.

It's not a really big issue I guess, and not many users might navigate the way I do perhaps, just thought I should let you guys know, though.
That being said, the sidebar and docs page is definitely already quite intuitive. Just a feature request :v:

**Comment by shcheklein** [comment]
@utkarshsingh99 good points and a good feature request. It will definitely improve UX and can make it more intuitive.

**Comment by ashiishme** [comment]
I would like to contribute on this feature request.

**Comment by shcheklein** [comment]
@ashiishme thanks! that would be great!
