### ISSUE TITLE
document about jsonschema for dvc.yaml

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1429]
I'll add a small note later on mentioning that jsonschema is available for `dvc.yaml`, after 1.0 docs is complete. I'll assign this to myself.

Related: https://github.com/iterative/dvc/pull/4028, https://github.com/iterative/dvc/issues/4027

**Comment by jorgeorpinel** [comment]
Cool, should we also publish the JSON schema as an independent file in dvc.org and link to it from our note?

**Comment by skshetry** [comment]
@jorgeorpinel, I'm thinking of adding to the catalog of [schemastore](https://github.com/SchemaStore/schemastore). This way, many ide will download that by automatically based on filepath match (eg: when you open `dvc.yaml`), and user won't need to configure anything at all.

Jetbrains supports this out of the box, VSCode and Atom needs yaml extension for this support (they support json already by default).

So, maybe, I will create a separate repo for the schema, where I'll add some tests and that will hopefully get mirrored to the schemastore.

**Comment by shachibista** [comment]
Please consider https://pydantic-docs.helpmanual.io/

**Comment by skshetry** [comment]
@shachibista, yes we are using `pydantic`. In fact, waiting for a release there.

**Comment by skshetry** [comment]
@shachibista, this is still a WIP though. And, we have too many schemas already.
