### ISSUE TITLE
basic concepts: pipeline stages

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1431]
Other than explaining what a pipeline stage is, this can help us group 2 terms that are used extensively and sometimes confusingly throughout docs: `.dvc` files (formerly DVC-files) and `dvc.yaml` — which already have their own guide so maybe this can just use that page instead of a new basic concepts one. Not sure

See more context: https://github.com/iterative/dvc.org/pull/1408#issuecomment-643121300:

> Mentioning dvc.yaml and .dvc (everywhere) is too noisy

### Automatic linking

> Maybe should be a separate issue

- [x] `dvc.yaml` could be like a command name (done in #1370), which automatically links to its user guide. #1137
- [x] Not sure about `.dvc` file — I think here we don't want to link automatically. #1137
- [ ] dvc.lock ?
- ~~"stage" could have a tooltip and glossary entry.~~ Extracted to #1579
- [x] remove all existing manual links from dvc.yaml, dvc.lock, and .dvc file.
- "orphan stage" ~~we could link manually to dvc add~~ (term will be removed)
- "import stage" ~~to dvc import~~ (term will be removed)

Jump to https://github.com/iterative/dvc.org/issues/1431#issuecomment-658384344 for an update.

**Comment by shcheklein** [comment]
@rogermparent let's start on this next, when you have time

**Comment by jorgeorpinel** [comment]
Would be nice to decide on #1395 first too! I guess I should prioritize #550 to facilitate all this...

**Comment by rogermparent** [comment]
It seems like the most streamlined way to do this is add `dvc.yaml` as a glossary `abbr` target, giving the Tooltip a small entry that links to the full page. 

For example, the Tooltip content could be:

> The primary configuration file of DVC.
> 
> [Read the full syntax here](https://dvc.org/doc/user-guide/dvc-files-and-directories#dvcyaml-file)

I don't know how true that is, but I believe it gets the idea across.

If this is the kind of implementation we want, this change should be pretty simple. I can also use ripgrep to go through all existing content and change all the existing references to `dvc.yaml` to `abbr`s.

I can get a PR up soon showcasing this implementation.

**Comment by shcheklein** [comment]
I don't like the idea of using abbr - we'll have a lot of noise in the Markdown files. Let's link `dvc.yaml` (and other) inline code blocks instead automatically.

**Comment by rogermparent** [comment]
That's a reasonable concern, I'll check if we have an existing Remark plugin that has that behavior and make a new one if we don't.

**Comment by shcheklein** [comment]
@rogermparent yes, we do this already for `dvc add` kind of links, there should be code around for this.

**Comment by rogermparent** [comment]
Found it, thanks!

**Comment by rogermparent** [comment]
From what I understand, there's three currently proposed entries for the automatic linker
* [x] dvc.yaml could be like a command name, which automatically links to its user guide
* [ ] "orphan stage" we could link manually to dvc add
* [ ] "import stage" to dvc import

There's also

* [ ] "stage" could have a tooltip and glossary entry.

which I can do, but is notably separate from the rest and may need another Issue as Glossary entries need to wait for tooltip content where auto-linker entries have everything they need in the description.

**Comment by jorgeorpinel** [comment]
> "orphan stage" we could link manually to dvc add

Don't worry about that one. We got rid of the term.

>  "import stage" to dvc import

We won't be using that term either in the future, just import .dvc file possibly. So probably also no special work needed there.

>  "stage" could have a tooltip and glossary entry.

That's the content part of this issue. I guess it should be a separate issue, let's just leave it unchecked for now?

**Comment by jorgeorpinel** [comment]
Chnged to p1 since all the `docs-engine` work here has been done by @rogermparent from what I understand. Thanks Roger!!!

**Comment by jorgeorpinel** [comment]
Also added to the issue description (content related):

> remove all existing manual links from dvc.yaml, dvc.lock, and .dvc file.

Is dvc.lock also auto-linked now, @rogermparent ? If not where do we add it? Thanks

**Comment by jorgeorpinel** [comment]
> "stage" could have a tooltip and glossary entry.
which I can do, but is notably separate

Extracted this to #1579 Roger, so that your PR closes this one 🙂
