### ISSUE TITLE
ref: GDrive supported by `open()`

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#1435]
Mention that `gdrive` now supports `open()` from https://github.com/iterative/dvc/pull/3916

**Comment by jorgeorpinel** [comment]
This means that https://dvc.org/doc/api-reference/open supports GDrive now yes? That would be a very quick update prob.

**Comment by casperdcl** [comment]
I believe so... been so long ago I can barely remember :sweat_smile:
