### ISSUE TITLE
plots: add smooth template example

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#1439]
https://github.com/iterative/dvc/pull/4046#issuecomment-644437731

CC @pared @dmpetrov

**Comment by jorgeorpinel** [comment]
Probably also mention the smooth template is available in the section where templates are explained as well.

**Comment by pared** [comment]
@dmpetrov can we use the plot from original issue? https://github.com/iterative/dvc/issues/3906?

**Comment by shcheklein** [comment]
@pared @efiop can you take this please?

**Comment by efiop** [comment]
Added to the sprint, will try to take a look.
