### ISSUE TITLE
term: call metrics "metrics" and plots "plots"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1442]
There's a couple issues with terminology around the concept of _metrics_.

Conceptually, regular (scalar) metrics and plots (continuous metrics) are both metrics, so we have phrases like "Type of metrics" as well as using the term "metrics" in the plots command references. I think this is confusing.

Instead of having to explain that there are types of metrics and one we call just metrics in most places and the other we call "plots" (but still use "metric files"), we could just skip this explanation altogether and only call metrics metrics, and plots plots. This includes "metrics file" and "plots file".

Why even merge these 2 concepts into one? Sure, we can mention the word "metrics" once or twice in the plots cmd ref index, but that should be enough. The commands themselves do very different things anyway and the format requirements for each kind of file are very different.

> Keep in mind that metrics and plots are also 2 kinds of special outputs, and this will be explained in the `dvc run` cmd ref (see #1420).

---

- [x] Additionally (extracted from https://github.com/iterative/dvc.org/pull/1420#pullrequestreview-432035519), we ended up with complicated rules as to which terms to use for singular and plural "metrics file" and "metric files". I think we should not say singular "metric" at all because sometimes there's not enough context and it sounds like we're talking about int'l distance units (as in kilometers). Using plural "metrics" always is an easier rule we'll always remember, same as "plots", because that's the name of the commands themselves.

> p.s. this may also affect the core repo (output strings).

**Comment by jorgeorpinel** [comment]
Cc @dmpetrov and @andronovhopf your thoughts are appreciated! (This is not currently a priority though, of course.)

**Comment by jorgeorpinel** [comment]
p.s. we also use "parameters files" all over https://dvc.org/doc/command-reference/params and it seems fine.

**Comment by dmpetrov** [comment]
This is the right direction. We need to come up with clear separation. Metrics & plots files are the best that I can think of right now.

**Comment by jorgeorpinel** [comment]
I think the terms are fine, even when plots are metrics technically. We just probably don't need to stress that and keep saying "types of metrics: scalar metrics which we just call metrics and continuous ones that we call plots". We can just remove these confusing explanations I think, and make the difference implicit by only using the term "(DVC) metrics" for scalars and "(DVC) plots" for continuous/charts.

The same overlap exists between other concepts technically, like "remote storage" and "cache" but we never (no longer at least) call remote storage "remote cache" or explain that there can be multiple caches, one local or external for your project, and distributed copies (possibly partial) in remote storage...

This kind of explanations while correct, complicate the docs unnecessarily. Some things we can leave as implicit knowledge I think.

**Comment by jorgeorpinel** [comment]
@dberenbaum @iesahin let's discuss this one? Still relevant, even more with image file plots support... (see https://dvc.org/doc/command-reference/plots)

Rel. https://github.com/iterative/dvc.org/issues/2572

**Comment by dberenbaum** [comment]
@jorgeorpinel Do you think the discussion in https://github.com/iterative/dvc.org/issues/2956 addresses this?
