### ISSUE TITLE
Missing requirements.txt in code.zip sample archive

### ISSUE THREAD

**Issue by bench** [iterative/dvc.org#145]
In your getting started, a sample kit is provided to test `dvc run` comment.

Unfortunately, the zip file **code.zip** does not contains the requirements.txt file needed by pip.

**Comment by pared** [comment]
Hi @bench! You are talking about [this](https://dvc.org/doc/get-started/example-pipeline) tutorial?

**Comment by efiop** [comment]
Hi @bench !

@pared I suppose it is the one from https://dvc.org/doc/tutorial/preparation, it indeed doesn't have requirements.zip in it but uses it in the tutorial. Fixing it right now.

Thanks for the feedback! 🙂

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc-doc-get-started/commit/945876d803500d16d04aeabeb8503583a9dbc037 . Fixed code.zip is deployed. @bench  Please feel free to try it out 🙂

**Comment by bench** [comment]
Hi @efiop and @pared !
I was pointing this page https://dvc.org/doc/get-started/connect-code-and-data in which we were asked to wget on https://dvc.org/s3/get-started/code.zip. But it seems you fixed it too.

Also, maybe you could setup an issue template on your repository?

In any case, thank you for your responsiveness and your job, dvc is a great tool.

**Comment by efiop** [comment]
@bench Glad it works now :)

Great idea! Created https://github.com/iterative/dvc.org/issues/146 for that.

Thanks a lot for the feedback! 🙂
