### ISSUE TITLE
tutorials -> get started: .gitignore file not found

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc.org#1463]
In the Getting Started section, `dvc init` creates a `.dvc` folder with `.gitignore` and `config`.
But there is no creation of a .gitignore in the root folder of the project.
In the [Data Versioning page](https://dvc.org/doc/tutorials/get-started/data-versioning#data-versioning), we try to add a `.gitignore` file that has not been created.  
> git add .gitignore data/data.xml.dvc
> git commit -m "Add raw data"

![Screenshot from 2020-06-21 08-40-33](https://user-images.githubusercontent.com/32031518/85215795-f2ea5380-b39a-11ea-9991-289edcde47b8.png)

**Comment by shcheklein** [comment]
@utkarshsingh99 good catch! please, feel free to fix it, but please install the pre-commit hook (or alternatively don't forget to merge restyled PRs into you own)

**Comment by utkarshsingh99** [comment]
Okay. So I guess we need to modify the command from 
> git add .gitignore data/data.xml.dvc

to 

> git add data/data.xml.dvc data/.gitignore

Am I right?

**Comment by shcheklein** [comment]
yep!
