### ISSUE TITLE
docs: command-reference: add `dvc daemon` command

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#147]

**Comment by shcheklein** [comment]
@efiop  why would we want to include this into docs? It is not part of the UI/UX and is not supposed to be run by a user, right?

**Comment by efiop** [comment]
@shcheklein Right, but it is a part of our CLI, so we should at least add a doc stating that it is a service command.

**Comment by shcheklein** [comment]
Why bother? I would actually hide it from the help as well. I don't quite understand what is the reason to show it there to be honest.

**Comment by efiop** [comment]
Agreed.
