### ISSUE TITLE
cmd ref for dvc remove is out of date

### ISSUE THREAD

**Issue by nik123** [iterative/dvc.org#1490]
1. `dvc remove` description should be updated according to implementation (once  https://github.com/iterative/dvc/issues/4094 is resolved)
1. `--outs` description should be updated according to implementation.
1. `.gitignore` should probably be mentioned/described in examples.

Context:

1. https://github.com/iterative/dvc/pull/4074#issuecomment-647903614
1. https://github.com/iterative/dvc/issues/4094

More problems not mentioned in context above:
1. Extra params mentioned in cmd ref: `-p`, `-f`.
1. There is no shorthand for `--outs` (i.e. `-o`) in the core repo whereas it is mentioned in cmd ref.
1. cmd ref description is also out of date.

**Comment by jorgeorpinel** [comment]
Thanks @nik123 let's resolve iterative/dvc/issues/4094 first and then reflect the latest strings and behavior in docs after that issue is closed 🙂

**Comment by nik123** [comment]
@jorgeorpinel I have updated description with few more problems I've detected.
