### ISSUE TITLE
docs - get started: git contents inaccurate 

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/dvc.org#1492]
In the tutorial page, https://dvc.org/doc/start/data-pipelines#dependency-graphs-dags, the files listed to be committed into git may be inaccurate.
Here is the list of my unstaged files:
![Screenshot from 2020-06-24 08-11-25](https://user-images.githubusercontent.com/32031518/85492156-5c17d400-b5f2-11ea-97ef-a0a684dbb731.png)
vs the list of files that the tutorial wants me to commit:
- .gitignore
- dvc.lock
- dvc.yaml

Does the tutorial specifically want me to commit on these 3 files and not the other files in src, and params.yaml?
Maybe we can specify a reason if that's the case or add the files in the list.

**Comment by jorgeorpinel** [comment]
Hi @utkarshsingh99 are you talking about this part?

![image](https://user-images.githubusercontent.com/1477535/85502651-61066480-b5ad-11ea-972a-a4d5db9b73ed.png)

Other than maybe changing .gitignore for data/.gitignore, I think "incude" implies this list is non-inclusive. The idea is that by this point the user understands what to do on their own. Not sure it's a good assumption but we don't want to teach Git.

**Comment by jorgeorpinel** [comment]
"This" should be "These" though!

**Comment by utkarshsingh99** [comment]
Alright. Also, interestingly, I do have a `.gitignore` in the root of my project.

**Comment by jorgeorpinel** [comment]
That's because of the `train` stage in **⚙️ Expand to add more stages**.

**Comment by jorgeorpinel** [comment]
> "This" should be "These" though!

Would you like to update this @utkarshsingh99 ?

**Comment by jorgeorpinel** [comment]
> "This" should be "These" though!

Hi. Has this been addressed? Can we close this issue? Thanks!

**Comment by utkarshsingh99** [comment]
Yes, I will address this mistake in the draft PR.
Sorry for the delay. Is it okay if I mention it in that PR? Maybe I should rename the issue as well

**Comment by jorgeorpinel** [comment]
> Is it okay if I mention it in that PR?

I'm not sure what you mean. Please link #1494 as the fix to this issue.

**Comment by jorgeorpinel** [comment]
Actually it's such a small thing... I see you've addressed it there. Let's just close this now. Thanks
