### ISSUE TITLE
dag: rewrite explanation of what pipelines are

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1500]
Extracted from https://github.com/iterative/dvc.org/pull/1496#pullrequestreview-437828132:

> all this text is pretty bad :( let's ... rewrite it
(referring to the description of what pipelines are [in the `dag` ref.](https://dvc.org/doc/command-reference/dag#directed-acyclic-graph))

Also, note from https://github.com/iterative/dvc.org/issues/608, that we have to:

> - [x] Decide whether to use term pipeline, DAG, dependency graph, and when, and apply. See #1383 (comment)

UPDATE: Let's use "pipeline" as much as possible (per https://github.com/iterative/dvc.org/issues/1500#issuecomment-649895248).

**Comment by shcheklein** [comment]
I would use pipeline (and it's fine that command is called dag). It's user friendly.

**Comment by sahilbhosale63** [comment]
@jorgeorpinel Can I work on this issue?

**Comment by jorgeorpinel** [comment]
@sahilbhosale63 yes but this requires a good understanding of pipelines. Have you completed the Get Started yet? If so feel free to give it a shot and submit a PR.

And TBH right now the most valuable contribution would be to address one of the check boxes under **Next priorities** in #1255. Some of them are a little tedious (e.g. replace text across files) but you could just apply part of the needed changes so your PR is not to huge, it would still be useful. **In fact we prefer small PRs for GSoD-related contributions for now.**

**Comment by jorgeorpinel** [comment]
TBH though, right now the most valuable contribution would be to address one of the check boxes under **Next priorities** in #1255. Some of them are a little tedious (e.g. replace text across files) but you could just apply part of the needed changes so your PR is not to huge, it would still be useful. **In fact we prefer small PRs for GSoD-related contributions for now.**

**Comment by jorgeorpinel** [comment]
This will be addressed in https://github.com/iterative/dvc.org/issues/2883.
