### ISSUE TITLE
get-started: `cache: false` explanation

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1508]
https://github.com/iterative/dvc.org/blob/2fb72f734677f6e256f6d42e07c7079ac9769f98/content/docs/start/experiments.md#L51-L52

The `cache: false` is an *intention* to do what's explained, it's not what it **means** though.

**Comment by shcheklein** [comment]
@skshetry not sure I follow, could you elaborate please? (or even better suggest the way you think it should be).

**Comment by skshetry** [comment]
With `cache: false`, caching of the output is skipped by DVC and is usually done either if the file are small enough or needs to be versioned directly with git.

**Comment by shcheklein** [comment]
ah, I see ... to be honest, I think it's fine to keep it simple, in 99.9% cases this is cache false means that those files are indeed tracked directly with Git. I haven't see any other cases yet at least.

We can do something like "In this case cache: false means that those files are small enough to be versioned with Git".

**Comment by skshetry** [comment]
Still, `cache: false` does not mean that those files are small enough or is versioned by Git. Probably, it's one of the usecase of it, but it is not what it **means**.

**Comment by shcheklein** [comment]
> Still, cache: false does not mean that those files are small enough or is versioned by Git. Probably, it's one of the usecase of it, but it is not what it means.

yep, still in this case it's totally fine since we talk about metrics and plots file specifically - Get started is not command reference - no need to be mathematically precise.

**Comment by skshetry** [comment]
@shcheklein, it's under "Expand to see what happens under the hood", so, we can explain that detail, or we could rephrase it as,
> With `cache: false`, DVC skips caching the output as we want "metrics.json" to be versioned by Git

Also, I see that `Data Pipelines" explains all the flags, but "Experiments" does not explain what `-M` and `--plots-no-cache` is, and why `-M` is  being used instead of `-m` and `--plots-no-cache` instead of `--plots`.

**Comment by shcheklein** [comment]
@skshetry I don't have a strong opinion on this - to my mind both ways (the current one and the one you suggested) are fine for this section and the meaning more or less the same. So, feel free to make a PR. The essence is the same - we version files directly with Git since, and we do this usually when they are small enough. I would still try to keep language simple and mention that files are small though.

> Also, I see that Data Pipelines explains all the flags, but "Experiments" does not explain what

I would say it's a bit of a legacy that we explain flags in such details. But good point, and we can add that info if it's hidden.

**Comment by utkarshsingh99** [comment]
If you are going ahead with this change, can I take this up?

**Comment by shcheklein** [comment]
@utkarshsingh99 absolutely! feel free to create a PR.
