### ISSUE TITLE
ref: add remote example in gc ref

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#154]
`dvc gc` has two fundamental modes - local and remote. We should be extremely clear about what does each mode do and what it does not do.

> See https://github.com/iterative/dvc/issues/1266#issuecomment-433332445

**Comment by jorgeorpinel** [comment]
Is this still relevant since `dvc gc` is being rewritten? Or can you provide a little more details on what to talk about in the example? Thanks

**Comment by shcheklein** [comment]
Yes, this is still relevant. `dvc gc` has two fundamental modes - local and remote. We should be extremely clear about what does each mode do and what it does not do.

**Comment by iesahin** [comment]
I'll write an example based on an SSH remote. I think that's more straightforward than other options. 

Or should I use a local remote? We may need to reflect (maybe in a separate example) the use of `--projects`.

**Comment by shcheklein** [comment]
@iesahin better to use an artificial ("local") remote for simplicity, or S3 if we go being realistic but not-that-easy-to-reproduce

**Comment by jorgeorpinel** [comment]
> reflect (maybe in a separate example) the use of --projects

Good idea but unrelated here. Maybe contribute that one to #2064

**Comment by iesahin** [comment]
> Good idea but unrelated here. Maybe contribute that one to #2064

What I mean is something related to this option in `gc`.  

![Screenshot from 2021-02-20 14-33-24](https://user-images.githubusercontent.com/476310/108594048-acfde900-7388-11eb-9b7b-25198c0d1324.png)

You may have multiple projects sharing the same remote cache and if you don't mention all of them in `-p` option, you may delete the other projects' artifacts sharing the same space.

**Comment by jorgeorpinel** [comment]
Woah I didn't even remember about that option. May be OK to leave that out. Let's 🙏 try to get a good basic example for `gc -c/r` and then maybe mention `--projects`. Not critical
