### ISSUE TITLE
install: use multi-platform widget instead of a section per OS

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1555]
Similar to https://spacy.io/usage#quickstart

> Extracted from https://github.com/iterative/dvc.org/pull/1553#discussion_r452816422

**Comment by jorgeorpinel** [comment]
Probably solved by https://github.com/iterative/dvc.org/issues/759

**Comment by julieg18** [comment]
We now have markdown tabs which should solve this! Do we want to keep this issue open as a reminder to update the doc pages or just close it since we have #2939.

**Comment by shcheklein** [comment]
I don't think tabs are enough in this case. Checkboxes are not covered and we need to check if so many layers of tabs are easy to maintain and they look reasonably well.

We can take a look at how this is implemented in spaCy btw on the Markdown level (if it's open at all).
