### ISSUE TITLE
user guide: add a note about how cache directory is structured

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#156]
E.g.

> directory name is a first 2 symbols for the checksum for any cache file. For example, if you dvc add data and see md5 for it being 123456789, then cache file for it will be under .dvc/cache/12/3456789 on your local machine and prefix/12/3456789 on your remote storage.

**Comment by Dhiraj240** [comment]
@shcheklein @efiop will you assign this to me? I will give it a try and in future, I will probably ask some queries but before that, I would like to figure out some areas.

**Comment by shcheklein** [comment]
@Dhiraj240 hey, any updates on this issue?

**Comment by Dhiraj240** [comment]
Sorry for being late but I am setting the local environment on my laptop, most probably by tomorrow I will update as I was busy with my semester exams.

**Comment by shcheklein** [comment]
@Dhiraj240 any updates on this? Can someone else pick this task?

**Comment by algomaster99** [comment]
@shcheklein I can take this up. But I don't know how it works in remote storage so I'll take a look at that first. :smile:.

**Comment by shcheklein** [comment]
@algomaster99 sure! I've reassigned. Feel free to ask any questions via our common channels. Thanks!
