### ISSUE TITLE
cmd: update pending target arg descriptions

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1574]
> Extracted from https://github.com/iterative/dvc.org/pull/1384#issuecomment-657744994

Need to double check the following commands to see whether their `targets` support files/dirs ... repro, run, (un)freeze, remove, unprotect, update, and metrics/plots show

- May imply core repo output string updates as well.

**Comment by imhardikj** [comment]
@jorgeorpinel I checked the above commands with file/dirs:
- `repro`: currently being worked on in #1861 
- For  `unfreeze`, `freeze`, `remove`, when I tried them with files/dirs as `targets` this was the output:
`` ERROR: failed to freeze/remove `foobar`- "Stage `foobar` not found inside `dvc.yaml` file" ``
- `update`: directories were working when  used with `dvc update -R` else same error as above
- `unprotect` already excepts files/dirs
- Similarly `metrics show ` also accepts metrics files as `targets`.
- `run`: doesn't have `targets` argument

Does this require updating `targets` description in the `update` command or rather just the `-R` option desc.

**Comment by jorgeorpinel** [comment]
> Similarly metrics show also accepts metrics files as targets.
What about plots show? I'll look into that.

> Does this require updating targets description in the update command

No, that cmd ref seems to have complete info about -R and dir targets already.

Looks like no major changes are needed...
