### ISSUE TITLE
glossary: create "stage" entry

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1579]
and replace all the links from "stage" to the `dvc run` cmd ref for `<abbr>` tags, so the term gets a tooltip.

**Comment by shcheklein** [comment]
@jorgeorpinel @utkarshsingh99 could you please give a little bit more motivation for this? sounds a bit excessive to be honest.

**Comment by shcheklein** [comment]
I see, I read it intially as we need to replace `dvc run` with abbr

**Comment by shcheklein** [comment]
probably because I saw the PR first :)

**Comment by jorgeorpinel** [comment]
Yeah I guess I wasn't clear enough. Changed the description a bit now.

**Comment by iesahin** [comment]
Added a stage entry to https://github.com/iterative/dvc.org/tree/ug-basic-concepts-feb-21

**Comment by jorgeorpinel** [comment]
Thanks @iesahin. You can just link this issue to the PR from that branch, when there's one.

**Comment by iesahin** [comment]
This is fixed in 87942d00f706a76cfb1241d12b8a80c5f1f7872e in PR #2208
