### ISSUE TITLE
docs: auto-link .dvc/* to files & dirs guide

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1580]
> Extracted from https://github.com/iterative/dvc.org/pull/1576#issuecomment-658927239

Add .dvc/ -> https://dvc.org/doc/user-guide/dvc-internals — or even //.dvc/[^/]// if regexps are allowed (to catch things like .dvc/cache and .dvc/config).

- [ ] Will also require removing a bunch of manual links for the corresponding change

**Comment by rogermparent** [comment]
I checked for all links containing code quotes which contain `.dvc`, and I don't see any links in the codebase that would fit this pattern that haven't already been taken care of by the non-regex `.dvc` matcher.

`simpleMatcher` does support regexes though, so I can absolutely add this feature!

**Comment by jorgeorpinel** [comment]
I'm not sure I understand your comment Roger 🙂 Are you saying there's no instances of `.dvc/` in the docs?

> I can absolutely add this feature!

Good to know! Please do so when you think the time is right. It's been marked as a p2 so up to you. Thanks

**Comment by rogermparent** [comment]
> I'm not sure I understand your comment Roger slightly_smiling_face Are you saying there's no instances of `.dvc/` in the docs?

As far as I can tell from a regex search, there are no linked code quotes containing the text `.dvc` which aren't _just_ `.dvc`. There's one link that contains `.dvc/config` in `get_url`, but it links to that specific file on a GitHub repo.

Here's my deadgrep output:

```
Search term: \[.*?\.dvc.*?\] change
[...]

content/docs/api-reference/get_url.md
94   ([`get-started/data.xml.dvc`](https://github.com/iterative/dataset-registry/blob/master/get-started/data.xml.dvc))
104  ([`.dvc/config`](https://github.com/iterative/dataset-registry/blob/master/.dvc/config))

content/docs/user-guide/basic-concepts/dvc-project.md
18   [`.dvc/` directory](/doc/user-guide/dvc-files-and-directories), as well as

content/docs/user-guide/dvc-files-and-directories.md
13     [`.dvc` file](#dvc-files) per large data file or dataset directory being
185    [`.dvc` files](#dvc-files).
222  `deps` and `outs` entries of [`.dvc` files](#dvc-files)).

content/blog/2020-04-16-april-20-community-gems.md
115  ### Q: [How can I remove a `.dvc` file, but keep the associated files in my workspace?](https://discordapp.com/channels/485586884165107732/485596304961962003/689827778358673469)

content/blog/2020-03-24-march-20-community-gems.md
39   ### Q: [Is there a recommended way to save metadata about the data in a `.dvc` file?](https://discordapp.com/channels/485586884165107732/563406153334128681/685105104340386037) In particular, I'd like to save summary statistics (e.g., mean, minimum, and maximum) about my data.
82   ### Q: What's the best way to orgnize DVC repositories if I have several training datasets shared by several projects? Some projects use only one dataset while other use several. [Can one project have `.dvc` files corresponding to different remotes?](https://discordapp.com/channels/485586884165107732/563406153334128681/670664813973864449)

content/blog/2019-09-26-september-19-dvc-heartbeat.md
279  ### Q: [What’s the right procedure to move a step .dvc file around the project?](https://discordapp.com/channels/485586884165107732/563406153334128681/606425815139221504)

content/blog/2019-06-26-june-19-dvc-heartbeat.md
215  [https://remote.dvc.org/get-started](https://remote.dvc.org/get-started) is made

content/blog/2019-11-05-october-19-dvc-heartbeat.md
161  ### Q: [Is there a way not to add the full (Azure) connection string to the .dvc/config file that is being checked into Git for using dvc remotes](https://discordapp.com/channels/485586884165107732/485596304961962003/595586670498283520)? I think it’s quite unhealthy to have secrets checked in SCM.

content/blog/2020-06-29-june-20-community-gems.md
26   ### Q: I just upgraded to DVC 1.0. I've got some pipeline stages currently saved as `.dvc` files. [Is there an easy way to convert the old `.dvc` format to the new `dvc.yaml` standard?](https://discord.com/channels/485586884165107732/563406153334128681/725019219930120232)
```

**Comment by jorgeorpinel** [comment]
> there are no links containing the text .dvc which aren't just .dvc

Gotcha, OK. Thanks.

From the grep, the instance of `.dvc/config` may be a problem I guess? Or is `simpleMatcher` smart enough to let manual links alone? Applies also to all the blog questions.

We should also just remove some of those links e..g "`.dvc/` directory" and "`.dvc` file(s)" but for the latter ones we already have an issue.

**Comment by rogermparent** [comment]
Code quotes that are already within links don't get auto-linked, so we're okay on that one.

the '.dvc/ directory' and '.dvc file' ones are left alone because they are within the file that's being linked, and so would rather use a fragment link over a real link.

The only real change I see to do there is change the "`.dvc` directory" link in `content/docs/user-guide/basic-concepts/dvc-project.md` to be handled by the auto-linker, and maybe changing the "`.dvc` file" links to only link the `.dvc` bit so those are consistent with the auto-linked `.dvc` links.

**Comment by jorgeorpinel** [comment]
Maybe we're talking about different things.

We have many instances of `.dvc/`, `.dvc/config`, `.dvc/cache` for example, and those could be linked automatically to the corresponding section(s) of the Metafiles guide.

Once that is a feature, we can remove all the manual links around those texts. Same with any manual "`.dvc` file/dir" left — somewhat unrelated but should've been done for that other similar PR before.

**Comment by jorgeorpinel** [comment]
I think this could still be useful but given its low priority and that it's been a long time since last discussed I'm closing it as stale.
