### ISSUE TITLE
katacode: md5 is not available in the container

### ISSUE THREAD

**Issue by yevgenypats** [iterative/dvc.org#1585]
looks like there is a small bug in the interactive tutorial https://katacoda.com/dvc/courses/get-started/versioning

in step 6/6 - a command is specified `md5 data/data.xml` which I believe should be `md5sum data/data.xml` and it should be preinstalled via `apt install coreutils`

**Comment by jorgeorpinel** [comment]
P/s in fact it's easy to contribute such a change in https://github.com/iterative/katacoda-scenarios/blob/master/get-started/versioning/step6.md . It can even be done directly from Github. Would you like to try?

**Comment by shcheklein** [comment]
I think this is fixed already.
