### ISSUE TITLE
external link icon after image

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1594]
https://dvc.org/doc/use-cases/data-registries

<img width="701" alt="Screen Shot 2020-07-18 at 11 48 45 AM" src="https://user-images.githubusercontent.com/3659196/87859802-bf90db00-c8ec-11ea-9206-82dea80583da.png">

**Comment by rogermparent** [comment]
Looks like these external link icons are applied through CSS `::after` through an `a[target='_blank']` selector, so we just have to make another selector to suppress that `::after` on image links.
