### ISSUE TITLE
katacoda broken

### ISSUE THREAD

**Issue by sp7412** [iterative/dvc.org#1595]
### Please provide information about your setup
Visited: https://dvc.org/doc/start and clicked on "Run in Katacoda". All the tutorials are broken.

**Comment by shcheklein** [comment]
@sp7412 we are aware that some of them are outdated and working on fixing them (see #1586 ). Could you give us details which one specifically was broken for you?

**Comment by sp7412** [comment]
Anytime they reference the run command, the flag -n is missing and the command fails.

**Comment by shcheklein** [comment]
@sp7412 yep, instead of Dvcfile and `-f` there should be `-n <stage_name>` now. Pretty straightforward fix related to the DVC 1.0 release.

**Comment by shcheklein** [comment]
Duplicate #1586
