### ISSUE TITLE
blog: enable short anchor links?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1618]
We use really long headers in some pages, especially Monthly Gems questions e.g.:

https://dvc.org/blog/june-20-community-gems#q-i-just-upgraded-to-dvc-10-ive-got-some-pipeline-stages-currently-saved-as-dvc-files-is-there-an-easy-way-to-convert-the-old-dvc-format-to-the-new-dvcyaml-standard

Would it be valuable for these to be capped at a certain length, and perhaps add a random number or something like that? E.g. replace the above with:

https://dvc.org/blog/june-20-community-gems#q-i-just-upgraded-to-123456

**Comment by ashiishme** [comment]
Can I pick this? :slightly_smiling_face:

**Comment by shcheklein** [comment]
@ashiishme sure, feel free to take it! thanks :)
