### ISSUE TITLE
cmd: explain init dvc nested dvc projects/repos and relationship to --subdir

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1638]
## Report

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/1638#issuecomment-665745290

---
> Context: https://discord.com/channels/485586884165107732/563406153334128681/737729577992061059

```console
$ mkdir test && cd test
$ git init && dvc init
  # So far so good
$ mkdir dir && cd dir
$ git init && dvc init
  # No problem (expecting ERROR?)

$ cd ..
$ dvc destroy -f
$ dvc init
  # No problem (should WARN?)
```

- (2nd example above:) should it be enforced or warned in dirs that contain a subdir with a dvc repo?
- ~~Also, should it also be enforced even with `dvc init --no-scm`?~~ OK no point in this, but maybe should be mentioned in the docs.

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.2.1+b14ad4.mod
Python version: 3.8.2
Platform: Windows-10-10.0.18362-SP0
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
Filesystem type (workspace): ('NTFS', 'C:\\')
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by jorgeorpinel** [comment]
Actually the descriptions of --subdir is accurate, "--subdir must be provided to initialize DVC in a subdirectory of a Git repository." and "initialize the DVC project in the current working directory, even if it's not the Git repository root."

---
I guess the confusion really is about nested DVC projects. Are there restrictions? Guidelines? How does it relate to `--subdir`? Probably worth a new **Description** subsection and/or an **Example**.

**Comment by shcheklein** [comment]
@jorgeorpinel that should potentially explain this https://dvc.org/doc/command-reference/init#how-does-it-affect-dvc-commands ?

**Comment by jorgeorpinel** [comment]
I think not. That's still part of the --subdir use case explanation. Nested DVC repos is a separate matter (with some overlap). That's exactly the confusion I'm trying to clear 🙂

**Comment by shcheklein** [comment]
I guess it starts with the `On the other hand, if there are nested DVC projects, e.g.:` part? What else exactly do we need there?

**Comment by jorgeorpinel** [comment]
Good point: the "nested" term is used with regard to DVC projects already, yes. But I'm talking also about nested DVC repos.
