### ISSUE TITLE
doc: mention that multiple dvc.yaml files are supported

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1641]
> Extracted from https://github.com/iterative/dvc.org/pull/1615#discussion_r463373449

Note needed probably in
- https://dvc.org/doc/user-guide/dvc-files-and-directories,
- https://dvc.org/doc/command-reference/run, and
- maybe https://dvc.org/doc/command-reference/repro

Anywhere else?

**Comment by skshetry** [comment]
Can we prioritize this? :slightly_smiling_face:

**Comment by skshetry** [comment]
If it's not possible for now, I can work on this next week.

**Comment by shcheklein** [comment]
> If it's not possible for now, I can work on this next week.

@skshetry that would be great! feel free to take it :)

**Comment by jorgeorpinel** [comment]
@skshetry hi did you ever get around to this? Thanks

**Comment by jorgeorpinel** [comment]
UPDATE: Never mind I see this is only hinted casually in `dvc run` but I added some more notes as part of #2075

**Comment by jorgeorpinel** [comment]
Closed by #2075.

**Comment by skshetry** [comment]
Closed by f5978df3a1cb52320f51b0430e6fa02136f310ab

**Comment by jorgeorpinel** [comment]
I guess I forgot to actually click on "close" 😬 

Ty
