### ISSUE TITLE
doc: arguments `--stdin` and `--all` for `dvc check-ignore` cmd

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc.org#1674]
linked to Related to PR iterative/dvc/pull/4323

**Comment by jorgeorpinel** [comment]
Thanks! Quick note: if opening a PR immediately for these, there's prob no need for the issue. But doesn't hurt either. Thanks

**Comment by jorgeorpinel** [comment]
p.s. I think the relevant link here is https://github.com/iterative/dvc/issues/4321 right? Which is merged 👍

**Comment by jorgeorpinel** [comment]
I mean https://github.com/iterative/dvc/pull/4323 🤦
