### ISSUE TITLE
ref: add a description on how GDrive remote data is shared 

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1690]
Try different workflows, shared folders, shared drive (advanced)

https://discordapp.com/channels/485586884165107732/485596304961962003/742998672400449556

+ 

https://discordapp.com/channels/485586884165107732/485596304961962003/743193799445971036

> If it requires my google account to pull data from the dvc remote, how can I share data with others? I have setup a dvc repo with dvc remote as my Google drive folder. The folder is set with anyone with the link can edit option. I could successfully push and pull. Everything is fine.

**Comment by jorgeorpinel** [comment]
Related: #1699
