### ISSUE TITLE
cmd ref: status: ignoring cache that is not in local cache nor in remote

### ISSUE THREAD

**Issue by nik123** [iterative/dvc.org#1701]
UPDATE: Jump to https://github.com/iterative/dvc.org/issues/1701#issuecomment-678632753

---
Command reference for `status` should probably describe situation when target is missing both in local cache and remote. 

Target missing both in cache and remote may happen if Alice executes `dvc add data.csv`, `git add data.csv`, `git commit` and `git push` but doesn't execute `dvc push` and Bob executes `dvc status -c data.csv` on another machine.

For context see https://github.com/iterative/dvc/issues/4383
 
~~UPDATE: Jump to https://github.com/iterative/dvc.org/issues/1701#issuecomment-678561146 for summary.~~

**Comment by nik123** [comment]
It should be probably described in "Examples" section but I was unable to come up with nice and simple one therefore it's only issue and not PR.

**Comment by jorgeorpinel** [comment]
Good idea for a note or example. We could also clarify the bullet list in the Description: some bullets are confusing e.g. "new" inside "changed deps or changed outs", and the explanation of "not in cache" seems contradictory.

**Comment by jorgeorpinel** [comment]
OK so in summary, we agree to add a _missing_ bullet to https://dvc.org/doc/command-reference/status#comparison-against-remote-storage 🙂
