### ISSUE TITLE
blog: competitor blog analysis and a list of features that we can implement. 

### ISSUE THREAD

**Issue by umnikovas** [iterative/dvc.org#1707]
I made a competitor blog analysis and made a list of nice to have features on our blog platform:
You can look at it from [here](https://whimsical.com/GzT5jpfTyi2NfJL2DBK63G@AhRp651J2qYFaDMyJ7ZPexSR9)

I want to open a discussion about where should I contribute my design skills first. 
Rate issues according to there effort and probable benefits. 

After ill finish deploying design here:
#1364 
I'm planning to have something more to work on.

Here is a list of suggestions and as I saw, some of them have open issues already. 

<h2>Main blog page</h2>

1. **Use tags as another source of navigation**
We have a tag component that leads to a theme page of the tag. 
Make a tag block that is visible on the blog main page.
I can make a mockup for this feature. 
As a nice to have the option, we could add a tag count. So the user could know how much there are articles with this tag, but I don't know how much effort will it take on the dev team.
I think we can reuse the component from article page.
![image](https://user-images.githubusercontent.com/21154132/90851485-3d4a7980-e3b8-11ea-9429-01aa1e618fd5.png)
 Current Issue:
#1657 

2. **Rewrite the content in the subscribe block**
Think we can try to add some text that can describe the value.
I think сurrent text is weak, this part :
we won't spam you
looks like an excuse. The user could frame on the word spam. Recall bad times from it, and probably won't subscribe either.</br> 
It's just my opinion, and I don't like to change things for the sake of changing.
I think we can try to experiment on changes here.  Like with a/b testing when we will get the audience somewhere in the future.

3. **Article items can have tags**
User can use them for navigation
Something like this:
![image](https://user-images.githubusercontent.com/21154132/90851837-38d29080-e3b9-11ea-9f01-3661eb1a31c6.png)

4. **Share button in the card component**
It's a nice to have option. Probably it could boost some conversion in sharing, but probably only on some small level. 
![image](https://user-images.githubusercontent.com/21154132/90851889-628bb780-e3b9-11ea-8671-e86435f7e27c.png)

5. **Position the subscription block on 1st screen, or in the article flow**
Can boost a little bit of conversion in subscription rate. But to be precise we need to test it. 
![image](https://user-images.githubusercontent.com/21154132/90852017-b5656f00-e3b9-11ea-8ca1-0b6b5a82f9a8.png)

6. **Consistent illustration style**
This illustration style communicates the brand voice to the user and makes it easier to distinguish articles from one another. 

7. **Clean UI**
Remove the clutter. I think we can remove the grey background, revise the layout of cards. The page would look more cleaner and probably more content-rich.

8. **Dedicated blog domain/subdomain**
We can use another header for navigation in the blog, but it probably could be useful only if we will have a big amount of articles on lots of themes.

<h2>**Article page**</h2>

1. **Autor block at the end of the article**
Probably it's one possible route to take, read the article, and then get engaged with the author... 
![image](https://user-images.githubusercontent.com/21154132/90852308-77b51600-e3ba-11ea-933d-7188c41209cd.png)

2. **Related articles**
Use the tag info to summon the article that uses the same tags. Sort them by the time they were created. Use 3 articles for desktop
![image](https://user-images.githubusercontent.com/21154132/90852547-15104a00-e3bb-11ea-9f4a-7100920d07b2.png)

3. **Comments in the article**
I think this kind of mechanic makes it easier for readers to leave feedback on the article. They will have context at hand and can refer to it when posting something.  
Something related is in this issue
#1116 
But I think best for it to look like this:
![image](https://user-images.githubusercontent.com/21154132/90852431-cfec1800-e3ba-11ea-8acc-ec347ace680e.png)
But I think I need more research on this issue. As at first glance, it looks very complex.

<h2>Accesibility</h2>
1. **Blog page**
The var(--color-gray) if used on desc. text does not pass accessibility standards. Some of the text that uses this color is harder to read in some cases. And probably it's an issue for google search rankings also (needs research). 

To pass standarts we can use this variable: var(--color-gray-dark)
![1](https://user-images.githubusercontent.com/21154132/91063194-02bf3600-e671-11ea-88c5-c6f7d116d2a5.jpg)

And by doing so we could get a more accessible and clean design
![image](https://user-images.githubusercontent.com/21154132/91063500-6e090800-e671-11ea-9bd9-3619d8303176.png)

I will open a new Issue for accessibility, where I will try to find all places where we have problems with text contrast, and what can we do about it.

**Comment by shcheklein** [comment]
Some great points here! I would prioritize it like this:

1. Improving subscription block (better message, move it to the top, etc)
2. Comments at the end of the article, we even have a ticket for that already!
3. Some low-hanging fruits like UI, accessibility, fonts, etc
4. Tags navigation, share button
5. Author page, related posts at the end.

**Comment by julieg18** [comment]
Are we still interested in implementing these features (list only shows features that don't already have an issue opened)? 

- [ ] Improve Subscription Block
  - [ ] Improve message
  - [ ] Position the subscription block on 1st screen or in the article flow
 - [ ] Refactor cards, making things look more cleaner and content rich
 - [ ] Use darker text color for accessibility
 - [ ] Place tags in blog post cards
 - [ ] Show how many articles have certain tag
 - [ ] Add sharing button to blog post hero
 - [ ] Add author block at end of article
 - [ ] Add "Related Articles" at end of article

cc @iterative/websites, @jendefig

**Comment by rogermparent** [comment]
> Are we still interested in implementing these features? The list only shows features that don't already have an issue opened.

I think most of these are good ideas that we'll eventually want, particularly the tag-related ones. Some are lower priority than others, in fact from a glance most are p2, but they're still desirable.

**Comment by jendefig** [comment]
@julieg18 I agree with @rogermparent From my perspective, most important to prioritize:
() Improve Subscription block for better visibility site wide
() Add sharing button to blog post hero
() Add author block
() Related articles would be great too!
