### ISSUE TITLE
Edit HTTP remote related posts regarding strong and weak etag

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#1730]
After https://github.com/iterative/dvc/pull/4372 we started supporting weak etags.
Need to update the documents related.

- [x] https://dvc.org/doc/user-guide/dvc-files-and-directories
- [x] https://dvc.org/doc/user-guide/external-dependencies
- [x] https://dvc.org/doc/command-reference/import-url

**Comment by sarthakforwet** [comment]
Hey @pared! I am willing to work on this issue. If you're not currently working on this, please guide me what exactly I need to update. Thanks!

**Comment by pared** [comment]
HI @sarthakforwet! 
So, in the articles I linked, there are mentions about strong Etag and links to explanation what strong vs weak etag is. We simply need to get rid of `strong Etag` and replace them with `Etag` and we no longer need to link to the explanaition.

**Comment by jorgeorpinel** [comment]
So it's not important to say we support both strong and weak eTag? I'm not familiar with the difference but does saying "we support eTag" imply "both weak and strong"? Thanks

**Comment by jorgeorpinel** [comment]
OK sure maybe use the term "HTTP ETag" and link to https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation

**Comment by pared** [comment]
@sarthakforwet, so as @jorgeorpinel mentioned, ideally we should replace "strong Etag" mentions with `HTTP ETag` and link to wiki article on etags.
