### ISSUE TITLE
Blog index queries take long enough to trigger Gatsby warnings

### ISSUE THREAD

**Issue by rogermparent** [iterative/dvc.org#1733]
Split off from #1727 

My hypothesis copied from there:

>  I think the queries that are warned about for taking too long are taking a while because they're fetching a huge amount of data even when the image transforms are cached.
> For example, take an index page has 8 thumbnails with our current setup that gives each thumbnail two sourcesets with 4 images: that means gatsby-transformer-sharp, even with working cache, reads the cache and the FS to provide 64 image paths along with any extra blur-up data for each image. While this certainly isn't long as it takes when the images are actually resized, it's still much more intensive than the average query and enough to make them take long enough to get flagged by Gatsby.
> 
> the problem isn't very scary with cache, it just takes comparatively much longer than the average query that grabs some basic page content from a markdown file that's already been read to memory. That's why the warning only occurs in the Heroku containers and not local builds- the difference in computing power is enough to drive the time below Gatsby's warning threshold. The warning is much scarier than the thing it's warning about.

While worth looking at, I believe this takes less priority than the other split issue #1732, as that one actually causes the build to multiply in length when it happens.

I believe, the first step to fixing this would be trying to use one source set in blog index thumbnails instead of two. I haven't tested this yet, though.

**Comment by julieg18** [comment]
@rogermparent , are we good to close this now that we are at Gatsy 4? I'm not seeing any blog warnings anymore 🤔

**Comment by rogermparent** [comment]
I think I still see them on Heroku during full rebuilds, but I don't think there's much more we can do here- at least not enough to warrant an Issue. I've already done the thumbnail change earlier, so at least all action items in this ticket have been taken.
