### ISSUE TITLE
user-guide: clearly specify that state db is only used locally

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#175]
Sometimes people do not understand that SQLite is used only for optimization and they think that DVC uses a binary format (please use translate): https://www.facebook.com/permalink.php?story_fbid=1151521948337039&id=100004377340065&comment_id=1151533428335891&reply_comment_id=1153257634830137

Why don't we make it clear and extract `.dvc/status` file outside DVC project like `/var/dvc/my-project-SOME_UNIQ_ID`?

**Comment by efiop** [comment]
Agreed, moved to dvc.org.

**Comment by shcheklein** [comment]
I think it's solved since we moved SQLLite files under `.dvc/tmp` now.
