### ISSUE TITLE
plots: update docs

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#1800]
after iterative/dvc#4602 we accept any target for `dvc plots`. Reflect that in docs.

- [x] UPDATE: pending one thing (from https://github.com/iterative/dvc.org/pull/1809#issuecomment-708029242):

> if we explain in the plots concept itself (plots ref. index) that plots are not only dvc.yaml based, people won't expect dvc.yaml to be present in the first place.
It's better to specify at the top level that plots files by definition could be anywhere.

**Comment by jorgeorpinel** [comment]
Feel free to include in #1797

**Comment by jorgeorpinel** [comment]
Updated the description a little ^
