### ISSUE TITLE
docs: automatic tooltips

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1802]
Could we just apply the underline and tooltip to every single instance of each term in the glossary automatically? So we don't need to manage `<abbr>` tags (under /doc/ only)

Pro: Easier to maintain docs
Pro: More consistent

Con: May be too much (too many underlines and tooltips everywhere)
^ Fix: only apply to the first instance in each H2/H3 section, or only after n characters have passed since the last instance of the same term (or something like that)

**Comment by jorgeorpinel** [comment]
WDYT @rogermparent?

**Comment by rogermparent** [comment]
> Con: May be too much (too many underlines and tooltips everywhere)

I agree that this would be too much without the fix, but with a fix sounds like a good idea.

> Fix: only apply to the first instance in each H2/H3 section

This would be best done via a remark transformer, as the whole AST is given to a plugin so dividing into "sections" between headings and operating on them individually should be possible in the current engine.

> or only after n characters have passed since the last instance of the same term

While possible, this one opens up the possibility of re-links in odd places and involves much more algorithm tweaking than the section-based limiters.

We could also consider only auto-linking the first instance of a term per page.

**Comment by jorgeorpinel** [comment]
One per H2 would cover 90% of the cases.

**Comment by julieg18** [comment]
I'm a little confused about this issue. I thought we already had automatic tooltips. What this issue made before we had them? If so, are we good to close this?

**Comment by jorgeorpinel** [comment]
We don't have automatic tooltips @julieg18 . We have to specify them with `<abbr>` tags. This is about not needing to specify that component, rather that it's automatically applied to (some) glossary terms.
