### ISSUE TITLE
feature videos on DVC sites

### ISSUE THREAD

**Issue by elleobrien** [iterative/dvc.org#1807]
From a chat with @shcheklein:

We can add links to our YouTube channel in a few places on the DVC site, and also maybe on cml.dev and iterative.ai. 

- [ ] Add link to YouTube channel close to the video on our landing page 
- [ ] Add a footer: "Subscribe to our channel to learn about MLOps!"
- [ ] Maybe something on our Community page? Could replace one of the sections that is underused (maybe Events, since this is a bit unused during COVID times?)
- [ ] Make room for Getting Started videos in each of the four [Getting Started docs](https://dvc.org/doc/start).

Where we may need some design support:
- Placing a link/banner in the right place on our landing page
- Finding good spots on the cml.dev and iterative.ai site to encourage checking out the videos 
- On docs pages that will have a video embedded, where does it make sense to add it? Should it be on the top or bottom of the page?

**Comment by julieg18** [comment]
We have links to youtube on all our site's footers and/or headers, have an issue (#2603) opened for adding youtube to our community page, and have added youtube videos to our docs!
