### ISSUE TITLE
community: Contribute should have a clear link to docs/"Contributing to DVC"

### ISSUE THREAD

**Issue by brainless** [iterative/dvc.org#1827]
Hello everyone,

As an interested contributor, when I click on top navigation `Community > Contribute` I should see a clear CTA or link to [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core). This being the starting page for developers who are interested should be visible in the main sites Contribute page in my opinion. If the team agrees, then I will create a PR.

Thank you

**Comment by jorgeorpinel** [comment]
Good idea @brainless ! Maybe where it says "We welcome contributions to our code and docs." it could be changed a little to link to both https://dvc.org/doc/user-guide/contributing/core and to https://dvc.org/doc/user-guide/contributing/docs.

**Comment by iswarmondal** [comment]
Hey is this issue still active? 
I'm new to open source and want to give it a try.
What do you think @jorgeorpinel?

**Comment by jorgeorpinel** [comment]
Pull requests are very much welcome @iswarmondal . Please see https://dvc.org/doc/contributing/docs first.
