### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1831]
https://github.com/iterative/dvc.org/runs/1190845913

**Comment by jorgeorpinel** [comment]
Addressed the internal one in #1831

**Comment by sarthakforwet** [comment]
@shcheklein @jorgeorpinel can you please tell how can I reproduce this issue? 
Looking at the link check job, it shows that the links are broken in `linux.md`, `windows.md`, `macos.md` and `running-dvc-on-windows.md` But those files seemed to work fine with all links in them. Thanks!

**Comment by shcheklein** [comment]
@sarthakforwet I think we can close this, it looks like we just got one actual broken link fixed, and others are just flaky. We have a ticket I think to improve the link checker itself to retry a few times and a few days before reporting broken links //cc @rogermparent

**Comment by rogermparent** [comment]
@shcheklein I haven't opened a ticket yet, but there is a feature in the works for basically keeping track of the amount of times a link has failed, and only failing the whole test if a link is dead for two tests in a row. I haven't considered time-based forgiveness, but that's also possible once persistence is working.
