### ISSUE TITLE
update status command output description

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#185]

**Comment by shcheklein** [comment]
We've changed the command output recently, added new options, doc should be updated accordingly

**Comment by sanidhyamangal** [comment]
@shcheklein  can I work on this issue? if yes can you please provide me with some more specs regarding this ticket?

**Comment by shcheklein** [comment]
@sanidhyamangal sure! thanks for your help. The best to start is to try some experiments, for example, using the https://github.com/iterative/example-get-started project. Also, it might make sense to check the code - `dvc/dvc/repo/status.py` and `dvc/dvc/stage.py:863` - and see what possible values it returns now. If you have have any questions, please joint the dvc.org/chat and use #dev-docs or #dev-general to get fast help.

**Comment by sanidhyamangal** [comment]
@shcheklein sure will give it a try.
