### ISSUE TITLE
cmd ref: add a few lines about cache and no-commit in `dvc run`

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#186]
`--no-commit` + `dvc commit` introduced a new way of iterating, it's an important to put a paragraph in the description or even a separate section.

**Comment by jorgeorpinel** [comment]
Hey @shcheklein . There's several mentions of "cache" and `--no-commit` in https://dvc.org/doc/command-reference/run. What did you mean? Thanks

**Comment by shcheklein** [comment]
`--no-commit` + `dvc commit` introduced a new way of iterating, it's an important to put a paragraph in the description or even a separate section.
