### ISSUE TITLE
connect Code and Data section: clarify `dvc run/repro` command

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#187]
See discussion at https://discordapp.com/channels/485586884165107732/485596304961962003/546947809341865986

**Comment by shcheklein** [comment]
from the discussion:

> also what is -d or -o
> or how you can add -M
> to store metrics
> and also that metrics file can be in any format, just make sure that you generate the same metrics and the same file every time

> a little more details on what run is doing and its basic required parameters I think here would help
I hope I am being helpful here with the feedback

**Comment by shcheklein** [comment]
Fixed.
