### ISSUE TITLE
remote: Document support for WebHDFS

### ISSUE THREAD

**Issue by tomasfarias** [iterative/dvc.org#1899]
Support for WebHDFS has been discussed in https://github.com/iterative/dvc/issues/4687 and is being implemented in https://github.com/iterative/dvc/pull/4747.

Documentation should be updated to reference WebHDFS as an alternative to HDFS: anywhere HDFS is used, WebHDFS can be used instead. It should be mentioned that the advantage of using WebHDFS over pure HDFS is it eliminates the requirement of having `libhdfs` installed.

**Comment by jorgeorpinel** [comment]
OK @tomasfarias thanks! If you can remind us when iterative/dvc#4747 is merged, that would be great.
