### ISSUE TITLE
metrics: document behavior of accepting any parsable file

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#1909]
After iterative/dvc#4446 `dvc metrics` commands accept any viable target, metric file does not have to be specified in `dvc.yaml`.
`plots` has this functionality already documented it #1800.
Related to #1809, iterative/dvc#4761

**Comment by jorgeorpinel** [comment]
Is this still relevant @pared @dberenbaum ? Thanks

**Comment by pared** [comment]
@jorgeorpinel yes, it is
in https://dvc.org/doc/command-reference/metrics#description we imply that one needs to mark the output as `metric` in order to use `dvc metrics` command on it. This is not a requirement. I don't think that's super important to mention that it works on files not specified as metrics, though it would be good to mention it. It shouldn't be a big change, sorry for leaving it to hang for so long.

**Comment by jorgeorpinel** [comment]
Looks like this is already mostly done per https://github.com/iterative/dvc.org/pull/3387#pullrequestreview-924066307 but thanks for #3387 as well! Lmk if you need help finishing that one up. Closing this.
