### ISSUE TITLE
formatting for italic text is broken

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1910]
https://dvc.org/doc/command-reference/remote/modify#available-parameters-for-all-remotes

`Or a local remote (a directory in the file system):`

got formatted into:

<img width="673" alt="Screen Shot 2020-11-05 at 9 30 26 AM" src="https://user-images.githubusercontent.com/3659196/98275635-b2eecc00-1f49-11eb-8864-25bff6899fad.png">

**Comment by jorgeorpinel** [comment]
It thinks it's an image caption I guess. Those should only activate after an MD image like `![]() _{Caption}_`

**Comment by rogermparent** [comment]
We've got a fix in #1911, [confirmed on the deploy](https://dvc-landing-fix-italic--gn9wkr.herokuapp.com/doc/command-reference/remote/modify#available-parameters-for-all-remotes)!
