### ISSUE TITLE
provide guideline or mechanism to resolve conflicts in DVC files on merge

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#192]
When we change something (let's say a stage command) in one branch (experiment) and want to propagate this change to the derived branch it's easy to get a merge conflict in a DVC file.

Usually merge strategy `theirs` (git merge -X theirs) do the job. 

We need to think if it's always the case. We should specify a guideline how to resolve these conflicts. If there are some ideas how to avoid them, let's discuss this. Right now it's frustrating and unclear how to manage these conflicts.

**Comment by dashohoxha** [comment]
> When we change something (let's say a stage command) in one branch (experiment) and want to propagate this change to the derived branch it's easy to get a merge conflict in a DVC file.

For small changes, I think that cherry-pick would be better and safer than a merge.

From what I have seen (and I have zero ML experience, I have just read some DVC tutorials), we merge a branch A onto a branch B when we want to completely overwrite B with A, for example when we merge the branch with the best metrics onto branch master. In this case it is safe to use the merge strategy `theirs`. Then, after making as well a `dvc checkout`, all the data and pipelines will be up to date (or at least most of them).

**Comment by jorgeorpinel** [comment]
I think this is done! See https://dvc.org/doc/user-guide/merge-conflicts

Closing for now.
