### ISSUE TITLE
docs: add `dvc add --glob` to command reference 

### ISSUE THREAD

**Issue by ju0gri** [iterative/dvc.org#1928]
Add the new argument supported by  `dvc add` `--glob` to the documentation with usage examples.

Related to: iterative/dvc#4816

Per https://github.com/iterative/dvc/pull/4864

**Comment by jorgeorpinel** [comment]
Please see some initial questions in https://github.com/iterative/dvc/pull/4864#pullrequestreview-528893719. Feel free to answer there or here. Thanks @ju0gri !
