### ISSUE TITLE
cases: training on a remote machine (SSH)

### ISSUE THREAD

**Issue by ghost** [iterative/dvc.org#194]
for example, `ssh` to a remote machine, `git clone / pull` to get your code, then `dvc pull` to download your dataset, and `dvc repro` or `dvc run` to start training your models

**Comment by Naba7** [comment]
An almost similar example is https://dvc.org/doc/use-cases/data-and-model-files-versioning and https://dvc.org/doc/use-cases/share-data-and-model-files and ``versioning`` in ``getting-started`` explains it. 
I am sorry Can you explain this a little bit more?

**Comment by shcheklein** [comment]
@Naba7 the point here is in connecting your local environment with a remote one. DVC helps running an expensive training remotely, while you can keep doing some stuff locally. DVC commands in this scenario help you moving pulling/pushing data across different machines.

**Comment by Naba7** [comment]
Can I take this up? I am not sure if I can do it,but I'll give it a try.

**Comment by shcheklein** [comment]
@Naba7 sure! You can take our NLP tutorial or get-started as a base example, and show step by step how to run it remotely via SSH or on S3 EC2 using tools like [spotty](https://github.com/apls777/spotty).

**Comment by dashohoxha** [comment]
Maybe these two interactive examples are related to this:
- https://katacoda.com/dvc/courses/examples/shared-server
- https://katacoda.com/dvc/courses/examples/ssh-storage

@mroutis what do you think?
Can we close this issue?

**Comment by shcheklein** [comment]
@dashohoxha I don't see how are they related, tbh. Also, I'm not sure I understood what https://katacoda.com/dvc/courses/examples/ssh-storage is about from reading the description - and it lacks any additional information inside that can help to "feel" the motivation behind it.

**Comment by shcheklein** [comment]
This is not a use case actually by the way it's written. Title should be changed to make it a use case, or it can be part of the user guide.

**Comment by shcheklein** [comment]
E.g. use case can be something like: "Training on a remote machine", "Organizing CI system for ML", etc

**Comment by shcheklein** [comment]
Not sure what @mroutis had initially in mind.

**Comment by mroutis** [comment]
Sorry for the late response!

@shcheklein , changing the title

**Comment by jorgeorpinel** [comment]
Closing in favor of #2544.
