### ISSUE TITLE
start: provide code samples, make it more actionable

### ISSUE THREAD

**Issue by JIoJIaJIu** [iterative/dvc.org#1943]
It would be great that every chapter of [Get Start](https://dvc.org/doc/start) provides instruction how to prepare a needful repo structure to proceed further
At this moment it's hard to init needful structure if you start not from the first chapter

In one chapter such approach is applied - https://dvc.org/doc/start/data-management/data-pipelines
> Expand to download example code.

- [x] but it's not enough and the user needs to do few additional steps to proceed further:
* run `git init`, covered with `Please also add or commit the source code directory with Git at this point`
* run `dvc init`
* fetch `data/data.xml`

- [ ] Also if I would like to proceed [Experiments chapter](https://dvc.org/doc/start/experiment-management/experiments) I need to have `model.pkl` there. But adding `model.pkl` is marked optional a the previous chapter [Data Pipelines/Dependency graphs (DAGs)/Expand to add more stages](https://dvc.org/doc/start/data-management/data-pipelines#expand-to-add-more-stages). So the user can easier skip the step and after get an error in **Experiments**.

Providing at the start of every chapter the steps how to initialize the repo will make chapters independent and help to avoid few errors

**Comment by jorgeorpinel** [comment]
> instruction how to prepare a needful repo structure to proceed further

Yeah, we used to have this in the previous version of the GS. Not sure why we no longer have those since it can be hidden in an expandable section indeed. Let's do this unless you remember a reason for this @shcheklein ?

> Also if I would like to proceed Experiments chapter I need to have model.pkl there. But adding model.pkl is marked optional in the previous chapter

Also true, we should definitely address this part. Could be addressed by the same solution like Guro mentioned.

**Comment by shcheklein** [comment]
We had it back and forth a few times already. Doing it completely reproducible and chapters independent makes it a hands-on tutorial like (which get started is not). It means longer read time, more distractions for users who want to get the idea quick, etc. 

The idea with the recent changes was to use Katacoda extensively to provide such playground (it still out of date btw, which is on of the biggest priorities). 

If Katacoda is not visible we should put links into the expandable sections. It should solve this problem.

> Also true, we should definitely address this part. Could be addressed by the same solution like Guro mentioned.

it's not marked optional. The problem should be addressed in a similar way- change language at the very beginning, may be at the very top of every chapter. Make it super clear "how to use the get started".

**Comment by shcheklein** [comment]
Katacoda - we had another complain recently, btw on Discord.

**Comment by shcheklein** [comment]
Also, don't forget that we have the whole project prepared - iterative/example-get-started that can be taken, any tag can be `git checkout`-ed and it's an ideal starting point.

**Comment by jorgeorpinel** [comment]
Yes, we can just fix the specific issues Guro reported for now.

re Katacoda - Should I take over #1586 from you @shcheklein? I've moved #1400 and #670 to p0 too.

**Comment by shcheklein** [comment]
@jorgeorpinel yep, thanks! It's not p0 though. Let's first wrap up other stuff on our plate.

**Comment by jorgeorpinel** [comment]
We should reconsider and consolidate with https://github.com/iterative/dvc.org/issues/2496 cc @iesahin

**Comment by jorgeorpinel** [comment]
> it's not enough and the user needs to do few additional steps

Being addressed (or not) in https://github.com/iterative/dvc.org/pull/3998

> if I would like to proceed [Experiments chapter](https://dvc.org/doc/start/experiment-management/experiments) I need to have model.pkl there

No longer applicable to https://dvc.org/doc/start/experiment-management/experiments

This is done 🙂

**Comment by jorgeorpinel** [comment]
>  Change language at the very beginning, may be at the very top of every chapter. Make it super clear "how to use the get started".

Hmmm well, I guess this part has not been addressed but I'm not sure it's still wanted. I've started  https://github.com/iterative/dvc.org/pull/4000 to discuss and address this.
