### ISSUE TITLE
ref: example for `list .` (local repo as target)

### ISSUE THREAD

**Issue by BurnzZ** [iterative/dvc.org#1963]
The current examples in https://dvc.org/doc/command-reference/list only show how to view the contents of a tracked Git repository.

I think it's also worth denoting examples of how to view remote storages, like:

```
$ ls *.dvc
data.dvc

$ dvc list . data/some/dirs
data_1.csv
data_2.csv
data_3.csv
```

**Comment by efiop** [comment]
@BurnzZ Just a note that this is not really viewing remote storage. The fact that `.dir` cache file might be on remote storage is an implementation detail. `data.dvc` is local, so we are viewing local project, which that `data` dir is a mere part of.

**Comment by jorgeorpinel** [comment]
Yep. Since remote storage doesn't play in `dvc list`, I'm changing the title of this issue for now.

@BurnzZ can you confirm that what you suggest is an example of `dvc list .` (listing something in the local project)?

I guess that would be useful to show as a short example, althought it's kind of an edge case. Thanks

**Comment by jorgeorpinel** [comment]
For now I've mentioned `.` as a local path `url` example in the description of list, get, and import (see #1982).

**Comment by BurnzZ** [comment]
Hi @jorgeorpinel ,

> can you confirm that what you suggest is an example of dvc list . (listing something in the local project)?

Yes it is, for viewing the local project.

**Comment by jorgeorpinel** [comment]
Reopening per https://github.com/iterative/dvc.org/pull/1982#issuecomment-747851192. Ideas for the example:

> Before you do a partial pull for example. Or listing a specific revision
