### ISSUE TITLE
download button in home page stuck at DVC 1.9.1

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1964]
> Context: https://github.com/iterative/example-repos-dev/issues/17#issuecomment-731834544

The latest is 1.10.1 as of now, see https://github.com/iterative/dvc/releases/

**Comment by jorgeorpinel** [comment]
Is this internal to the docs engine, or a problem with the release process from the core repo? Cc @efiop 🙂

**Comment by efiop** [comment]
Yes, was waiting for chocolatey package to get approved. Now it is, so updating the links right now.
