### ISSUE TITLE
code snippets in documentation not available on Github

### ISSUE THREAD

**Issue by richardxy** [iterative/dvc.org#198]
DVC documentation contains many examples that refer to some code snippets, such as 
`dvc run \
        -d prepare.py -d data.xml \
        -o data.tsv -o data-test.tsv \
        python prepare.py data.xml`

But the file prepare.py can't be found on its Github repo. It would be very helpful for users to understand how the code snippets were written so that can be used in 'dvc run'. 

Hope all the "*.py" files or other code examples would be available in Git repo. Thanks for the great work!

Richard

**Comment by robogeek** [comment]
I am currently going through the DVC commands and updating the documentation.  Thank you for the feedback.

Generally speaking for now think of these as examples of what can be done, rather than precisely replicatable things. 

I certainly get that you want replicatable examples, and will keep this in mind.

**Comment by richardxy** [comment]
Great! Thank you very much!

**Comment by shcheklein** [comment]
@richardxy could, you give a little bit more context ... which part of the documentation you are referring to in this issue?

**Comment by richardxy** [comment]
I said it as a general impression for all parts of the documentation (particularly in "dvc run" part, I guess). When a .py file is referred in an example of command, but without seeing the py file, a person may not understand how such a script should be written.

**Comment by richardxy** [comment]
btw, I really like the tutorial https://dvc.org/doc/tutorial/define-ml-pipeline, which has the code downloadable from S3. Even so, it would be still nice to be able to read the code files on Github without downloading and unzipping the code package.

**Comment by shcheklein** [comment]
@richardxy would be great if you could take a look at this command reference https://dvc.org/doc/commands-reference/checkout . We've made example for it runnable and available on Github. Let me know if you understand the doc, is it easy enough to reproduce, any feedback. Thanks!

**Comment by jorgeorpinel** [comment]
I think we can close this issue @shcheklein ? We don't intend to have exact reproducible examples in all docs, just in some cmd ref examples, how-tos, and tutorials.

**Comment by shcheklein** [comment]
@jorgeorpinel sure! feel free to close this!
