### ISSUE TITLE
docs: update `metrics show`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#1996]
Just creating a reminder for now

https://github.com/iterative/dvc/pull/4706

**Comment by jorgeorpinel** [comment]
Hi @dberenbaum ! Is this still relevant? Thanks

**Comment by dberenbaum** [comment]
Sadly it looks like it ☹️ . The format of examples in https://dvc.org/doc/command-reference/metrics/show#examples looks very outdated.
