### ISSUE TITLE
page for performance tips

### ISSUE THREAD

**Issue by johnnychen94** [iterative/dvc.org#1997]
Similar to Julia's https://docs.julialang.org/en/v1/manual/performance-tips/, I believe it will help others more if there's s page for dvc's best practice tips.

#1994 (when I was born lol) is one thing I noticed during using s3 remotes. I also noticed that ssh remotes are slower than s3(minio) by 3x in my 1000M LAN network, which also might worth a mention.

Similar to the troubleshooting page https://dvc.org/doc/user-guide/troubleshooting, it can be a very concise FAQ page with URL points to detailed explanation, e.g.,:

```markdown
## commit your `dvc.lock` together with your code changes

Even if DVC is powerful in tracking the experiment data, you still need to prepare your git
commit carefully, otherwise, you'll easily be lost in the git history.
It's a good practice for future reviews to rebase your commits regularly and make sure `dvc.lock` changes
always co-exists with real code changes.

## parameterize your workflow for scalability and flexibility

...
```

**Comment by shcheklein** [comment]
Good suggestions @johnnychen94 ! We do have a page with tips for Windows https://dvc.org/doc/user-guide/running-dvc-on-windows but never had time to do a general sections ... to some extent because there are too many edge cases and it's hard to distill some general patterns.

> I also noticed that ssh remotes are slower than s3(minio) by 3x in my 1000M LAN network, which also might worth a mention.

Could you chime in here - https://github.com/iterative/dvc/issues/4732 ? I think this is all part of the bigger problem - the underlying library is pretty bad unfortunately .

**Comment by jorgeorpinel** [comment]
If we keep this we could add a check box to #72 and close here.

**Comment by shcheklein** [comment]
@jorgeorpinel I'm fine with either - your call!

**Comment by jorgeorpinel** [comment]
Nah never mind. Thinking about it, the request here is about performance tips, not really best practices.

**Comment by jorgeorpinel** [comment]
Something like tis would definitely go in the User Guide. But it would be great to compile a good amount of these tips before considering adding them.

Another place people can learn about these is in GitHub itself, as there's probably lots of closed issues in the core repo that relate to performance. Yet another option is to write blog posts about these things like https://dvc.org/blog/dvc-vs-rclone

**Comment by johnnychen94** [comment]
Hmmm, I thought it could be easier for users to find out what they should be aware of; a page with DVC tips(performance or best practice) can really serve as an index page.

This issue seems to be duplicated to #72 so feel free to close this.

**Comment by jorgeorpinel** [comment]
OK feel free to suggest specific performance tips in #72. Thanks again
