### ISSUE TITLE
freeze DVC 1.0 docs version

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2006]
As we are getting ready for 2.0 release, as @skshetry reminded us, it's better to freeze docs:

- [x] create a branch and a tag for the current state (before we merge any DVC 2.0 changes)
- [ ] create a subdomain for 1.0 docs - v1.dvc.org ? 
- [ ] add selector, mention in the docs that this is the latest version and previous exists (similar to Elastic docs?)

- Consider also #1167 (or close it)

**Comment by jorgeorpinel** [comment]
> create a branch and a tag for the current state (before we merge any DVC 2.0 changes

We can manage a `v1` branch to keep merging some changes there because I'm pretty sure we will continue to make updates that also apply to 1.x for some time. Not sure we need a tag.

> create a subdomain... v1.dvc.org

👍

**Comment by jorgeorpinel** [comment]
Update on this: So far everything on master is also part of `v1` so I've been merging it back. At some point soon they will start to diverge. 2 comments: 1) how about adopting https://mergify.io/features/backports to send back certain changes to v1 after that? 2) Should this issue be prioritized/assigned? Thanks

**Comment by jorgeorpinel** [comment]
Another Q. Can we remove the blog and probably other sections (which may become outdated) from the v1 website?

And should we prioritize or merge #1167 with this one?

**Comment by jorgeorpinel** [comment]
Note: I reprioritized this now that 2.0 docs are done (for the most part).

**Comment by shcheklein** [comment]
Closing this, not important anymore. Also I think we should with a Python style docs (add notes per features) rather than trying to support multiple versions.
