### ISSUE TITLE
How to end `yarn dev` correctly? (on Win/Git Bash)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2018]
After I run it and Ctrl+C out of it, the Node.js process is still running (I have to open Task Manager to see it and kill it). So if the dev server crashes (happens sometimes when I switch Git branches) and I forget, they start adding up in the background.

Per stackoverflow.com/questions/44788982 this may be a problem with Git Bash specifically, but just wanted to double check whether we're missing something to exit gracefully (also mentioned in that SO q&a).

This is very minor.

**Comment by jorgeorpinel** [comment]
@rogermparent feel free to close this when you consider.

**Comment by rogermparent** [comment]
I'll see if I can find a solution online, but I don't actually have a windows dev machine to test on so it'll be difficult for me in particular to investigate.
This issue could possibly stem from a few places; off the top of my head, it could be:

- An issue with Windows running our customizations to dev middleware (I get similar issues when using `gatsby develop` on linux sometimes, but not often and I can still ctrl+C)
- An issue with Windows running the older Gatsby packages we use for image processing
- An issue with Windows running gatsby

**Comment by jorgeorpinel** [comment]
Thanks. Did you check https://stackoverflow.com/questions/44788982/node-js-ctrl-c-doesnt-stop-server-after-starting-server-with-npm-start? There are possible answers there.
