### ISSUE TITLE
cmd: clarify that every dvc.yaml is checked upon `dvc.yaml`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2023]
UPDATE: Skip to https://github.com/iterative/dvc/issues/5089#issuecomment-744675730

# ~~Bug~~ Report

## Description

`repro` fails for any file if there's an error in ./dvc.yaml

### Reproduce

```console
λ cat dvc.yaml
stages:
  hi:
    cmd: echo hello

meta:
  string: "some text"

λ dvc repro tmp/dvc.yaml
ERROR: 'dvc.yaml' format error: extra keys not allowed @ data['meta']
```

Even if tmp/dvc.yaml is valid, `repro` fails because ./dvc.yaml is invalid. AND the message is misleading because "dvc.yaml" here refers to ./dvc.yaml, whereas I'm specifying tmp/dvc.yaml as target (so I would assume that's the one DVC may be referring to).

### Expected

Repro of tmp/dvc.yaml (as long as it's valid).

### Environment information

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.10.2 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by jorgeorpinel** [comment]
- [ ] https://dvc.org/doc/command-reference/repro should explain this behavior
- [ ] https://dvc.org/doc/user-guide/dvc-files-and-directories could mention that all dvc.yaml files in the project are important and should be valid at all times for DVC to function properly.

**Comment by jorgeorpinel** [comment]
@efiop @skshetry @pared I've transferred this to docs but one last concern: I tried a .dvc file as target and it still checked all of the dvc.yaml files in my project for validity first. How is that helpful? There's no way they can affect the .dvc file I specified as target, as it's not a stage but rather just some data tracked by DVC. Thanks

**Comment by efiop** [comment]
@jorgeorpinel There might be another dvc file that is pointing to the same output path, we check for that and that's why we need to collect everything anyway.

**Comment by jorgeorpinel** [comment]
Overlapping output paths... OK got it.
