### ISSUE TITLE
config: incorrect system config path

### ISSUE THREAD

**Issue by johnnychen94** [iterative/dvc.org#2032]
# Bug Report

## Description

According to the documentation, the system config path for Linux is `/etc/dvc/config`, but it seems like the actual config path is `/etc/xdg/dvc/config`.

```console
DVC version: 1.11.8 (pip)
---------------------------------
Platform: Python 3.8.3 on Linux-4.15.0-128-generic-x86_64-with-glibc2.10
Supports: All remotes
```

I'm using Ubuntu 18.04, if that helps.

**Comment by efiop** [comment]
Let me compile the correct list of values for these here at least...

**Comment by shcheklein** [comment]
@efiop yep, that would help if you could write a summary of the change that is needed. Even here in the ticket should be enough.

**Comment by jorgeorpinel** [comment]
/etc/xdg looks liek an Arch Linux thing. It probably changes by distro? I guess we could just make a note about that for Linux

**Comment by efiop** [comment]
Ok, so according to https://github.com/ActiveState/appdirs/blob/master/appdirs.py (we use site_config_dir and user_config_dir), in a simplified version:
--global:
```
Mac: ~/Library/Preferences/dvc/config
Linux: ~/.config/dvc/config or $XDG_CONFIG_HOME/dvc/config
```
--system
```
Mac: /Library/Preferences/dvc/config
Linux: /etc/xdg/dvc/config or $XDG_CONFIG_DIRS[0]/dvc/config
```

@jorgeorpinel `/etc/xdg` is not an Arch thing, it can be on any distro and might even differ between different versions. IIRC i've seen different default XDG_CONFIG_DIRS on different versions of ubuntu before. It can be set to `/etc` too, but it is rather uncommon these days, at least from what've experienced (not at all an expert opinion) :slightly_smiling_face:

**Comment by pmrowla** [comment]
So I just noticed that the docs for mac are incorrect still. 

On mac, the global and system paths should be:
```
global: ~/Library/Application Support/dvc/config
system: /Library/Application Support/dvc/config
```

The discrepancy between using `Application Support` and `Preferences` is that appdirs master branch source uses `Preferences`, but the last actual pypi release uses `Application Support`.

@jorgeorpinel

**Comment by jorgeorpinel** [comment]
Thakns @pmrowla updated. But re `appdirs master branch source uses Preferences`, so does `dvc` installed in any other way (not `pip`) use `Preferences/`? Thanks

**Comment by pmrowla** [comment]
None of the binary packages should be installing from git source either, the only way `dvc` would use `Preferences` is if the user is running it in a virtualenv where they manually install `appdirs` from source.

**Comment by shcheklein** [comment]
@jorgeorpinel this is fixed, right?

**Comment by jorgeorpinel** [comment]
Yes 👍
