### ISSUE TITLE
 <details> element throws error

### ISSUE THREAD

**Issue by elleobrien** [iterative/dvc.org#2035]
I'm using a basic `<details>` element in a new docs page, which works fine in GitHub markdown and seems to be pretty standard usage. 

```
<details>
  <summary>
  S3 and S3 compatible storage (Minio, DigitalOcean Spaces, IBM Cloud Object Storage...)
  </summary>
  explanation goes here
</details>
```

But getting this error message in my local build:

```
src/components/Documentation/Markdown/index.tsx:45
  42 | const firstChild = filteredChildren[0] as JSX.Element
  43 | 
  44 | if (!/^h.$/.test(firstChild.type)) {
> 45 |   throw new Error('The first child of a details element must be a heading!')
  46 | }
  47 | 
  48 | /*
```

Any ideas?

**Comment by shcheklein** [comment]
@elleobrien please check this page sources - it has an example how to put details section together. The markup is slightly different.

**Comment by jorgeorpinel** [comment]
It expects a header element (e.g. `## Title`) as the first child (no need for `<summary>`)
