### ISSUE TITLE
guide: make proper DVC File guide + separate reference?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2059]
Some/parts of the docs in https://dvc.org/doc/user-guide/dvc-files feel more like a reference than a guide. While it's arguable whether that is a problem (e.g. other docs in that section have the same situation), it seems we agree that an actual guide for writing dvc.yaml would be great to have, since it's such a major component of DVC projects. Some ideas (from https://github.com/iterative/dvc.org/pull/2052#pullrequestreview-558335370):

> we could separate the dvc.yaml format explanation?
Like dvc.yaml short reference, then a section about "stage definition" explaining what key/value it takes, then "variables/parametriation" and then introduce loops. This way, concepts will get built (up on)

> split it into subsections - one about regular simple pointers .dvc, second about dvc.yaml and start writing a proper guide in it, start building proper structure

> similar docs (spacy, ansible, etc...
> I like [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v2/). Examples with one or two lines of text
> to write intro and help people write the yaml themselves, that fusion in [spacy](https://nightly.spacy.io/usage/projects) projects is nicer.
> we could also take a look at [pypyr](https://pypyr.io/docs/): They have separated the yaml definitions nicely into sections/concepts

And from https://github.com/iterative/dvc.org/pull/2052#pullrequestreview-562269533

> we should have this references, there should be some general description, then basic layout, then other syntax like templating, loops, etc. Again, let's refer to some good examples that describe languages

And https://github.com/iterative/dvc.org/pull/2052#issuecomment-757025327

>  The biggest concern is still structure... these titles (inside [DVC Files](https://dvc.org/doc/user-guide/dvc-files)) do not look good to me... They should higher level.
> - .dvc file - is clearly a reference thing. Where do we put it?
> - do we need two seprate dvc.yaml sections?
> - advanced-dvc.yaml - is too heavy and a mix of a reference (precise spec) and guide (story-like)

**Comment by jorgeorpinel** [comment]
Oh, and:

> I'm also thinking we will need to split dvc.yaml from .dvc files in the guide (as a 3rd level in the main nav) so these H3s become H2s and are shown in the right-hand nav
> we'll just need to repeat the Outputs and Dependencies sections in both pages (.dvc file outs/deps are a little different from those in dvc.yaml anyway so that would be more correct even if there's overlap).
From https://github.com/iterative/dvc.org/pull/2052#pullrequestreview-558335854

**Comment by jorgeorpinel** [comment]
@shcheklein I moved all pending structure discussions from #2052 to here (see desc.). On your Q from https://github.com/iterative/dvc.org/pull/2052#issuecomment-757025327:

> do we need two separate dvc.yaml sections? why do we consider basic templating and advanced feature?

Ideally not (let's come up with a definite org here) but for now it works so we clearly separate the 2.0 features into https://dvc.org/doc/user-guide/dvc-files/advanced-dvc.yaml.

And we can call it "basic" templating but the explanation takes a while (params files, global vars, local vars, etc. etc.) so maybe it's not that basic. But if we completely extract the reference part then yeah, it should be able to fit in the single dvc.yaml guide along with multi-stages — it will still be long though but maybe that's OK/inevitable.

**Comment by skshetry** [comment]
@jorgeorpinel, something wrong with the docs? The direct link downloads the html page for me.

**Comment by skshetry** [comment]
@jorgeorpinel, you might need to change it to `Advanced dvc-yaml` 🙂

**Comment by jorgeorpinel** [comment]
o_O yeah I guess the URL shouldn't end in `.yaml` ... That's a bug! You can load it from https://dvc.org/doc/user-guide/dvc-files though. Will address separately... Thanks @skshetry

**Comment by jorgeorpinel** [comment]
Fix in #2090 (please merge when you can @shcheklein)

**Comment by jorgeorpinel** [comment]
> I don't understand why we don't use right-side TOC instead. I find traversing through those pages difficult

@skshetry yes maybe a single dvc.yaml guide with several H2 headers (even if it's long) will be part of the solution here. But one more reason we sometimes avoid that you can see in cmd refs with multiple **Examples** (e.g. https://dvc.org/doc/command-reference/remote): you may notice there are some issues such, like having to scroll in a small space (see also #723, #753).

> Can dvc.yaml fit a single page - good question. I really hope so, I'm though worried that about some points...

@shcheklein it could be one guide page and one reference page somewhere else. I think we may need to extract the reference part to a new top section for DVC File/Format refs though (DV "Language" ref). Put .dvc, dvc.yaml/lock, .dvcignore, and maybe even .dvc/ dir (internals) there... But let me finish researching other docs sites and come up with a final proposal ⌛

**Comment by shcheklein** [comment]
@jorgeorpinel 

> you may notice there are some issues such, like having to scroll in a small space (see also #723, #753).

those glitches should not determine layout to my mind in any way. Those are issues that should be fixed.

> But let me finish researching other sites and come up with a final proposal ⌛

yep!

**Comment by jorgeorpinel** [comment]
#### Pending research (1/2)

On the terminology, I'm going for "`${}` expression", "replace", "generate" (details in https://github.com/iterative/dvc.org/pull/2052#discussion_r557595088)

**Comment by jorgeorpinel** [comment]
#### (2/2)

On the organization of docs (Can dvc.yaml fit a single page?), here are some raw results:

- **Helm** has
  (1) a long, monolithic "Topic" (guide + ref) for [Charts](https://helm.sh/docs/topics/charts/) (`Chart.yaml`), and
  (2-13) a series of [guides](https://helm.sh/docs/chart_template_guide/) about templating elsewhere. No dedicated schema ref.
  Verdict: 👎 Their docs lack easy nav menus and seem pretty hard to browse/revisit. The topic is spread across at least 13 pages.

- **Kubernetes**
  (1) [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) (K8s [objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) e.g. `pod.yml`) are explained in the "Overview/Configuration" section.
  (2) A disconnected how-to [Config. Pod w/ ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) page is provided too.
  (3) An entirely separate site for the underlying [API ref](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) exists as well.
  Verdict: 🙆‍♂️ Considering their huge docs, you can find what you need (not super easy: the left nav is complicated). The right-side ToC nav helps explore long pages.

- [spaCy Projects](https://nightly.spacy.io/usage/projects) (`project.yml`) is all
  (1) stuffed into a single, very long page. The top section is an intro guide, and the remaining sections mix guide + ref.
  Verdict: 🙆‍♂️ Smart graphic design helps a lot (e.g. `project.yml` samples floated right, clear schema ref. tables). But the page is way long and all the nav (external and ToC) is all on the left side, while the right side has space to spare
  > BTW their project.yml looks a lot like our dvc.yaml (fields `description`, `vars`, `commands` with `deps/outputs`)

- **Ansible** _playbooks_ (`playbook.yml`) are mentioned heavily in (1-4) several descriptive docs in their [User Guide](https://docs.ansible.com/ansible/latest/user_guide/index.html) (and in other docs later), and finally described properly in (5) a buried [guide](https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html). There's ([6](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html), [7](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html)) a couple related references in different places (the latter one has the YAML schema)
  Verdict: 👎 Too many guides in many places to cover all the playbook features. The familiar readthedocs-site could be a good thing but the nav is super complicated.

-

**Comment by jorgeorpinel** [comment]
- `docker-compose.yml` is introduced in the [Compose docs](https://docs.docker.com/compose/), but the [Compose file ref](https://github.com/compose-spec/compose-spec/blob/master/spec.md#volume-top-level-element) (partly a guide too) is a GH repo.
  Verdict: 👎 The Compose docs are short and sweet but the actual schema ref. on GH is hard to navigate (seems lazy to have it there)

- **pypyr** pipelines (`pipelinename.yaml`) are introed in the [CLI ref](https://pypyr.io/docs/cli/run-a-pipeline/) and explained shortly after in their own [section](https://pypyr.io/docs/pipelines/pipeline-structure/) of docs (mix of guide + ref).
  Verdict: 👍 Single place to learn the schema and go back to as a ref. The docs site UI is so-so though.
  > That said it's obviously a simple project so it's easier to organize effectively.

**Comment by jorgeorpinel** [comment]
See #2098 for a WIP proposal to address all this.

p.s. what about https://dvc.org/doc/user-guide/dvc-internals and https://dvc.org/doc/user-guide/dvcignore, shuold we move them into the **DVC Files** nav section?

**Comment by jorgeorpinel** [comment]
> about dvc.yaml and start writing a proper guide in it, start building proper structure

Question on this: won't it be pretty repetitive with https://dvc.org/doc/start/data-pipelines (once we rewrite that page)? Meaning, how should the basic dvc.yaml User Guide do differ from the Get Started: Data Pipelines?

**Comment by shcheklein** [comment]
The purpose of the get started is to give a brief overview, it can be actionable so that people can try it. In our case it's already too long (mostly because we tend to grow all the documents and from time to time we need to dry them)

The purpose of the User Guide is to provide comprehensive information (e.g. language spec). To some extent even Command Reference can be considered part of the User Guide for example.

It means that these document should be very different in language, in how they are structured, otherwise something is probably not right.
