### ISSUE TITLE
doc: change `run` mentions to `dvc.yaml` or `stage add` + `repro`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2076]
> Based on work in #2075

We should be emphasizing writing/generating `dvc.yaml` files instead of using `dvc run`, yet there's~~still around 50~~ several `run` links and examples throughout docs:

Links 

- [x] Many cross ones in the cmd ref. - #2997
- [x] Plenty in 3 Use Cases
- [ ] Another bunch to review throughout User Guides

Examples

- [x] Some can stay (as `stage add`) but not all.
- [x] #3309
- [ ] Around a dozen in the User Guide.

Many should be replaced by hand-written dvc.yaml files and at least one with a dvc.yaml file generation script (new example in `dvc root` per https://github.com/iterative/dvc.org/pull/1637#discussion_r463117077)

---
ADDITION from https://github.com/iterative/dvc.org/issues/2578:

- [ ] State this clearly in the docs, and the why (advanced `dvc.yaml` features?)
  Try to use a descriptive rather than prescriptive explanation...

`stage add` is still clearly useful, perhaps even preferred for certain cases:

- Simple stages or beginner users e.g. `dvc stage add -n test echo test`
- Programmatic stage generation, esp. to "bootstrap" a pipeline structure (to manage manually later)

**Comment by jorgeorpinel** [comment]
@iesahin would you be interested in moving this epic along since you were working on #3183 ?

**Comment by iesahin** [comment]
As we have closed #2997, let me check this, thank you.

**Comment by jorgeorpinel** [comment]
#2997 was mainly about references, this one is for use cases and guides. I can take care of the use cases though... ⌛

**Comment by jorgeorpinel** [comment]
> I can take care of the Use Cases... ⌛

Actually there's nothing worth changing there so that section is checked off now. Thanks

**Comment by daavoo** [comment]
I would add to the list the main page https://dvc.org/

**Comment by dberenbaum** [comment]
I don't see any remaining instances of `dvc run` 🎉 . Closing this one.
