### ISSUE TITLE
Version of Windows installer on the main page is not up-to-date

### ISSUE THREAD

**Issue by DiPaolo** [iterative/dvc.org#2078]
https://dvc.org/ links to Windows DVC installer which actual release date is 24 Nov 2020 (v1.10.2). While the most recent version is 1.11.10.

This is a bit confused. Especially right now, when there was a critical bug fix for Windows users (iterative/dvc#5012) recently which has been rolled out in the version 1.11.3 of DVC.

![image](https://user-images.githubusercontent.com/3266815/103744058-b2e57800-502f-11eb-89fd-1c82ff49fb75.png)

**Comment by DiPaolo** [comment]
BTW the same is for all other platforms on the same page.

**Comment by efiop** [comment]
Sorry for the inconvenience, fixing...

**Comment by efiop** [comment]
Updated to 1.11.8. We will update to 1.11.10 when homebrew and chocolatey packages are released (likely later today). Thank you for the feedback! :pray:
