### ISSUE TITLE
Add the Glossary page

### ISSUE THREAD

**Issue by DiPaolo** [iterative/dvc.org#2083]
### Goal
To collect all known and important terms within the project, the product and its usage, and put all of them on the new 'Glossary' page. Also, add a link to the page on the top level in the left navigation menu.

Similar things are provided by many products. Just few examples:
NumPy - https://numpy.org/doc/stable/glossary.html
AWS - https://docs.aws.amazon.com/general/latest/gr/glos-chap.html

### Rationale
- There are some unclear terms used everywhere in scope of the product. This is especially unclear for beginners who are just  starting to use DVC. Such unclear terms may confuse users. For me as a newbie personally, such confusing terms are: stage, DVC-file. And the problem is that I cannot find a place with the exactly one term for each of these words.
- There are discussions between developers in comments to some issues where different understanding of the same terms takes place. The Glossary page could be a place to refer to as the reference.

**Comment by jorgeorpinel** [comment]
@DiPaolo thanks, I'm going to move this to https://github.com/iterative/dvc.org/issues/1395#issuecomment-759063436 though. Let's shat there.
