### ISSUE TITLE
start: Data Access mentions tracking models without clarifying what kind

### ISSUE THREAD

**Issue by onavsaber** [iterative/dvc.org#2096]
I was reading the documentation on [Data Access](https://github.com/iterative/dvc.org/blob/master/content/docs/start/data-access.md). It starts by mentioning that 
```quote
Okay, now that we've learned how to track data and models with DVC and how to version them with Git, next question is how can we use these artifacts outside of the project?
```
However, the previous tutorial [Get Started: Data Versioning](https://github.com/iterative/dvc.org/blob/master/content/docs/start/data-versioning.md) only shows how to track data and tracking models are not demonstrated.

**Comment by jorgeorpinel** [comment]
The assumption is that the model is a file (probably). So the process would be the same as with the example `data.xml` use throughout https://dvc.org/doc/start/data-versioning.

**Comment by onavsaber** [comment]
I see. Thanks for the clarification. I was thinking whether or not the models are handled differently from the data, for example, like MLflow. 

Maybe a clarification like what you mentioned can be added.

**Comment by jorgeorpinel** [comment]
Yep we can definitely clarify!
