### ISSUE TITLE
dvc.org: reference to not existing title

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc.org#2102]
https://dvc.org/doc/user-guide/dvc-internals
![image](https://user-images.githubusercontent.com/47358913/105040223-9fe09800-5a72-11eb-8700-98ebc7488cf2.png)
The link `here` points to `https://dvc.org/doc/user-guide/dvc-files#structure-of-the-cache-directory` which is a reference to a non-existing title (probably moved somewhere else?)

**Comment by jorgeorpinel** [comment]
Ah yeah good find, thanks! It actually points to `/doc/user-guide/dvc-files-and-directories#structure-of-the-cache-directory` which redirects to `dvc-files`... Will fix!
