### ISSUE TITLE
add licencing info about using images/logos

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#211]
We see more and more people asking for permission to use our logos/charts in their articles about dvc. Looks like we could provide licencing info on dvc.org ourselves, so that people don't have to ask us explicitly.

**Comment by ryokugyu** [comment]
which license is used to share the logos/ charts?

**Comment by shcheklein** [comment]
there is no specific license. It something like this https://github.com/logos . As for the images - use them with a reference to the website.

**Comment by ryokugyu** [comment]
we need a specific article for this as GitHub has?
or just to add a section in the existing docs.

**Comment by shcheklein** [comment]
@ryokugyu I'm not sure. what's your take on it? Could you check other open source projects, or projects like Kong, Prisma.io, etc.

**Comment by ryokugyu** [comment]
@shcheklein some have a seperate section for logos like you mentioned prisma.io has. 
but, kong has not.

imho, let's add a section titled as `Logos` under `/doc/understanding-dvc/resources` section and share logos/images. also, including how to embed the DVC logo on a web page.

**Comment by shcheklein** [comment]
@ryokugyu could you share some links?

I don't like the idea of mixing it with Resources. They are different.

**Comment by ryokugyu** [comment]
Ubuntu: https://design.ubuntu.com/downloads/

OSI : https://opensource.org/logo-usage-guidelines

GitHub: https://github.com/logos

They all have seperate pages for it.

**Comment by shcheklein** [comment]
@julieg18 let's take some information from this ticket and close this when we are done with the Iterative website? Also, I think we'll need to add links to the brand page in all the footers.

**Comment by casperdcl** [comment]
related https://github.com/iterative/iterative.ai/issues/290
