### ISSUE TITLE
install: Minimum `pip` version should be specified at 19.0+ for dev envs

### ISSUE THREAD

**Issue by gth828r** [iterative/dvc.org#2112]
Hello, and thanks for the great project and excellent documentation!

I just walked through the development environment setup on Ubuntu 18.04 and I ran into some issues that prevented the environment from successfully being set up when following the documented instructions. I traced it down to a version requirement in pygit2 (see https://github.com/libgit2/pygit2/issues/999#issuecomment-614691503 and https://www.pygit2.org/install.html) that pip needs to be at version 19.0+. In my case, I was using the default Ubuntu 18.04 pip version, which is woefully behind that.

In my case, I simply ran the following in my virtual environment to get things back on track:
```
pip install --upgrade pip
```

The minimum pip required version of 19.0 should likely be specified in the development environment setup document in the user guide. Optionally, the above command could be recommended to arrive at an appropriate version.

**Comment by shcheklein** [comment]
@gth828r thanks! good catch, we should mention it as a note in docs indeed

@efiop just to let you know about this, may be something should be done on the DVC end - e.g. can we require a specific pip version?

**Comment by efiop** [comment]
@shcheklein I don't think we can, as pip isolates itself from the env of setup.py(or requirements) when installing stuff. Let's just add a note to the docs, same as pygit2 guys. We might need to add it to the docs for regular installation after 2.0 release too.

**Comment by shcheklein** [comment]
@efiop sounds good, thanks!

**Comment by jorgeorpinel** [comment]
Added note in https://github.com/iterative/dvc.org/pull/3360. Hoping pip 19 is still the minimum?

**Comment by gth828r** [comment]
According to the [pygit2 documentation](https://www.pygit2.org/install.html) there is now some type of dependency on pip 20.3+:
> This requires pip 20.3 or later, otherwise pip will try to install the source distribution, and likely fail to find a matching version of libgit2.

I tried it out, and I believe **you need at least pip 20.3** on a fresh dvc dev environment install to get all of the dvc unit tests to pass.

When installing from pip 20.0.2 (default on Ubuntu 20.04), I saw a lot of red text and some warning messages at the end of the attempted pip install. The unit test summary was as follows:
```txt
18 failed, 2450 passed, 14 skipped, 2 xfailed, 3 warnings in 180.76s (0:03:00)
```

I then uninstalled dvc, upgraded pip to the latest (taking me to version to 22.0.4), and reinstalled dvc. The unit test summary:
```txt
2468 passed, 14 skipped, 2 xfailed, 3 warnings in 183.64s (0:03:03)
```

I once again uninstalled dvc, downgraded to pip 20.3, and reinstalled dvc. The unit test summary:
```txt
2468 passed, 14 skipped, 2 xfailed, 3 warnings in 207.47s (0:03:27)
```

**Comment by jorgeorpinel** [comment]
Oh I missed the part about this being needed for dev envs. Updated https://github.com/iterative/dvc.org/pull/3360/files#diff-aebae5b1898c8c22e5acce05e3fa8787ed2711205cfa66ca5c92709c12c8e13b
