### ISSUE TITLE
docs: add a note that brew install doesn't work on Apple Silicon M1

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2113]
# Bug Report

I have issued 

```sh
brew install --build-from-source dvc
```
on a macOS Big Sur system. Homebrew downloaded the required packages. 

```sh
==> Installing dependencies for dvc: icu4c, boost, libffi, swig, llvm@9, brotli, gflags, glog, autoconf, automake, libtool, abseil, c-ares, protobuf, re2, grpc, lz4, gmp, isl, mpfr, libmpc, gcc, openblas, gdbm,
 readline, sqlite, tcl-tk, python@3.9, numpy, rapidjson, snappy, thrift, zstd and apache-arrow
```

However while building `swig` I got 

```
==> Installing dvc dependency: swig
==> Pouring swig-4.0.2.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Cellar/swig/4.0.2: 727 files, 5.5MB
llvm@9: The x86_64 architecture is required for this software.
```

BTW `pip` version seems to be installed fine.

**Comment by efiop** [comment]
@iesahin Transferred the issue to our docs repo.

**Comment by efiop** [comment]
For the record: looks like arm bottle is coming soon https://github.com/Homebrew/homebrew-core/pull/69837#issuecomment-767935617

**Comment by efiop** [comment]
Hi @iesahin ! Looks like it should be available now https://github.com/Homebrew/homebrew-core/pull/69837 , could you give it a try, please?
