### ISSUE TITLE
document `stage:add`

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2134]
A few questions regarding documentation:
1. How should we approach documenting `dvc stage add`? Duplicate most of the stuffs?
2. Should we remove `dvc run` or duplicate contents?
3. How about adding a deprecation warning in the docs for `dvc run`?

Related: https://github.com/iterative/dvc/pull/5350

**Comment by shcheklein** [comment]
I would keep for now both + note in the `dvc stages add` that it's available since 2.0

after the release, let's get rid of `dvc run` (and hide it in DVC itself)

**Comment by jorgeorpinel** [comment]
Yeah both for now and I can worry about phasing out `run` later. Let's just make a separate issue for that please. I'll add both to the #2026 `epic`. Just please confirm `stage add` is officially part of the 2.0 release (I don't see it in https://github.com/iterative/dvc/issues/5367).

**Comment by jorgeorpinel** [comment]
> I don't see it in iterative/dvc#5367

Maybe it's part of what "Run" refers to?

**Comment by dberenbaum** [comment]
@jorgeorpinel Good callout! It was hidden under low-level issues in iterative/dvc#5367, but it's now a separate checklist item.

**Comment by jorgeorpinel** [comment]
OK. Added this to the docs epic.
