### ISSUE TITLE
deep tutorial: check that it can run on Python 2

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#214]
User reported that our xml_to_tsv.py fails on python2 because of encoding issues in open().

https://discordapp.com/channels/485586884165107732/485586884165107734/558296626381324324

Reminder: code for tutorial is stored here https://github.com/iterative/dvc-doc-tutorial and should be deployed from there.

**Comment by robogeek** [comment]
IIRC I ran into the same issue and did not say anything.  On my systems python2 is the default, so my scripts sometimes start with:

```
PYTHON=python3.6
PIP=pip3
```

**Comment by AJ-54** [comment]
Hey @efiop, I ran the code by forking and cloning the repo on my system and running the xml_to_tsv.py file and got this error 

Input file data\Posts.xml does not exist
Usage:
        python posts_to_tsv.py

**Comment by efiop** [comment]
@AJ-54 Do you have `data\Posts.xml` though?

**Comment by AJ-54** [comment]
No @efiop , I cloned https://github.com/iterative/dvc-doc-tutorial and this does not contain any data\Posts.xml file

**Comment by efiop** [comment]
@AJ-54 You can't use that code as a standalone script. It is for https://dvc.org/doc/tutorial. The https://github.com/iterative/dvc-doc-tutorial is just a repo that code is being deployed from.

**Comment by AJ-54** [comment]
Well, Thanks @efiop I understood it. I searched for 'posts.xml' all inside the  https://dvc.org/ but could not find the file. Can you help me out here?

**Comment by efiop** [comment]
@AJ-54 It is described in the tutorial itself https://dvc.org/doc/tutorial/define-ml-pipeline :slightly_smiling_face: The point of this ticket is to go through full tutorial on python2 to make sure that it works.

**Comment by AJ-54** [comment]
Thanks for the help @efiop, I downloaded and made the required data folder and pasted the posts.xml file in it and ran the xml_to_tsv.py file in python 2 and the file ran successfully without any errors. I got a tsv file in the same folder by name Posts.tsv  . So, I think there is no error anywhere in the code

**Comment by efiop** [comment]
@AJ-54 Thanks for trying it out! :slightly_smiling_face: But the point of this ticket is to go through the _full tutorial_ on python 2, not only that single script.

**Comment by AJ-54** [comment]
@efiop yes, I am on my way to do that.

**Comment by kurianbenoy** [comment]
Can I work on this?

**Comment by shcheklein** [comment]
@kurianbenoy sure! thanks for your help! :)

**Comment by kurianbenoy** [comment]
I have been trying to run the [Tutorial](https://dvc.org/doc/tutorial) in python2 . I have encountered some issues so far:
1. https://github.com/iterative/dvc.org/issues/333, so I could run in python2 till `  $ dvc run -d code/featurization.py -d code/conf.py \
            -d data/Posts-train.tsv -d data/Posts-test.tsv \
            -o data/matrix-train.p -o data/matrix-test.p \
            python code/featurization.py`
2.  When I glanced through the rest of the portion, I found that in page https://dvc.org/doc/tutorial/sharing-data the repo `$ git clone https://github.com/dmpetrov/classify.git` does not exist. On looking by, I think this is the [new repo](https://github.com/dmpetrov/new_tag_classifier). @dmpetrov  can you please confirm

**Comment by jorgeorpinel** [comment]
Hi! Is this still something we care about since Python 2 I think will be deprecated in 2 months? Just checking.

**Comment by shcheklein** [comment]
@jorgeorpinel yep, let's close it. May be update our docs to specify that we haven't tested on Python 2 and do not recommend using it?

**Comment by jorgeorpinel** [comment]
OK adding notes in a new PR that will close this issue.

**Comment by jorgeorpinel** [comment]
I guess I'll just close it now.
