### ISSUE TITLE
mismatch in default permissions for newly created or downloaded cache files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2153]
In https://github.com/iterative/dvc.org/blame/b2149f1bb09cad948c420733313343eeece4e2ba/content/docs/command-reference/config.md#L176, the octal permissions `0o664` don't match the human-readable permissions `rw-r--r--`. It seems like `0o664` should be change to `0o0644`.

However, it seems like the defaults depend on the user's umask, and the docs assume a `0o022` umask. Would it be better to state something like the default permissions will depend on the umask?

@efiop

**Comment by iesahin** [comment]
I can fix this one but is umask behavior a bug in DVC core or something to be mentioned? If cache permissions should be `0644` regardless of umask, we can ignore to mention it IMO.

**Comment by dberenbaum** [comment]
Are you asking whether we need this sentence: `The default is `0o664`(rw-r--r--) for files and `0o755`
  (rwxr-xr-x) for directories.` IMO, we could probably just remove it since it seems like DVC is trying to respect the default system permissions, and that would solve the issue.
