### ISSUE TITLE
`import/get(-url)`: complete `--job` description

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2156]
We should clearly define the logic behind defaults, e.g. like @isidentical mentioned we do the following for the `import-url`:

> For import-url, it goes with --jobs => remote.jobs => core.jobs => BaseTree.JOBS

while what we mention (in [import](https://dvc.org/doc/command-reference/import#-j), [get](https://dvc.org/doc/command-reference/get#-j)) is only `remote modify jobs` and `BaseTree.JOBS` (defaults). So, part about `core.jobs` is missing. Which might be important since it can be used to override the behavior globally for example.

**Comment by jorgeorpinel** [comment]
> For import-url, it goes with --jobs => remote.jobs => core.jobs => BaseTree.JOBS

Is it the same process for get, import-url, get-url? Maybe you can help us confirm @dberenbaum ? Thanks!

**Comment by dberenbaum** [comment]
This looks stale, so I'm closing, but feel free to reopen if I'm mistaken
