### ISSUE TITLE
basic concepts: length limit for the document

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2162]
I think there should be a limit for Basic Concepts docs, say 100 words for each. Otherwise they'll begin to collect all the information and will basically be a replica of the user guide. 

Also a soft limit of 10-20 words should be set for tooltips. We don't want the user to read another document fully while reading a page.

**Comment by iesahin** [comment]
![Screen Shot 2021-02-09 at 12 52 21](https://user-images.githubusercontent.com/476310/107346909-4e0db980-6ad6-11eb-8381-15a64f82070b.png)

Also should we put self-referencing links like this in tooltips? A click-to-go link with an emoji can be applied to all like 
`[📖](/doc/user-guide/concepts/data-pipelines)`

**Comment by jorgeorpinel** [comment]
I agree with the principle of keeping concept pages focused on the conceptual part and leaving other explanations for the user guide (not sure though, let's just iterate on these and see) but not on hard word count limits. Same for tooltips: we shoot for a single paragraph so the render tooltip is small relative to the website, but no need for a word count, probably.

> put self-referencing links like this in tooltips? 

Great idea if this could be automated into the tooltip UI. I'd keep that feature request only for this issue for now (I'll label it accordingly, please update title and description). Thanks

**Comment by shcheklein** [comment]
For some items we don't have any information whatsoever. It's the only place to put it. E.g. what is a remote storage, what is cache, their relation to each other, etc.

**Comment by iesahin** [comment]
> we shoot for a single paragraph so the render tooltip is small relative to the website, but no need for a word count, probably.

I'm thinking about a rule of thumb to put pages under BC or UG. BC docs could be initial paragraphs for UG docs for most of the time. I see that BC is *user-level & conceptual* documents whereas UG is more detailed, application oriented but I can write longer and longer with repeating myself and adding examples. 

This issue is actually about learning your preferences. I'll put a soft limit of 200 words for docs and 30 words for tooltips for *myself*. At the end if something remains to be said, we can always add another paragraph. Thank you.

**Comment by shcheklein** [comment]
> This issue is actually about learning your preferences. I'll put a soft limit of 200 words for docs and 30 words for tooltips for myself. At the end if something remains to be said, we can always add another paragraph. Thank you.

No strong preferences, I think. We can definitely start with any limit and iterate on the length, and structure. 

> At the end if something remains to be said, we can always add another paragraph. Thank you.

agreed.
