### ISSUE TITLE
concepts: doc garbage collection in cache and/or remote concept pages

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2169]
We need a garbage-collection document that shows what is meant by it for various remote types and cache. 

Relates to #550

**Comment by jorgeorpinel** [comment]
Sounds more like a guide or how-to to me? Garbage collection doesn't seem to fall in the "DVC Concepts" category.

> BTW we also want to do this with remote configurations, which currently are buried in https://dvc.org/doc/command-reference/remote/add#supported-storage-types and https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type

**Comment by shcheklein** [comment]
It can be part of the Remote storage and/or cache concept to my mind to start with.

**Comment by iesahin** [comment]
I'm thinking about describing how it's different than Python or Git garbage collection that mainly works locally. This can be a part of remotes as well, yes, thanks.

**Comment by jorgeorpinel** [comment]
`dvc gc` is pretty similar to `git gc` in principle but the default behavior is quite different, as we don't actually delete anything unless certain flags are given. Probably no need to mention GC in programming languages? That has to do more with memory management so it could result confusing.

**Comment by jorgeorpinel** [comment]
> the default behavior is quite different

BTW that's under discussion iterative/dvc/issues/2325

**Comment by jorgeorpinel** [comment]
(so may not be worth it spend too much effort on this for now)

**Comment by iesahin** [comment]
Oh, that discussion is huge 😲 I'm not going forward on this until I read more about it. (BTW, with the current cache architecture I think it's not possible to solve space/security dichotomy. Cache should be another _fully managed_ git repository with branches for different projects and files should _know_ where they are used but I won't go into that topic here 😃 )
