### ISSUE TITLE
concepts: links to related docs in concepts pages

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2171]
At the end of each document we can have a _Further Reading_ section that lists the documentation related to that concept. These can also link to relevant blog post sections. 

Part of #550

**Comment by jorgeorpinel** [comment]
Good idea. But can we make this issue a checkbox in #550 instead? 🙂 Thanks

**Comment by iesahin** [comment]
Actually pages in #2177 has Further Reading links. They may be updated in time but this will be closed after that PR is merged anyway.

**Comment by jorgeorpinel** [comment]
OK. Please link this issue (or any other) to the PRs that will close it. https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by iesahin** [comment]
#2197 adds Further Reading section to BC workspace document

**Comment by jorgeorpinel** [comment]
Thanks @iesahin please check that link on how to link them (special term + this issue's number in the PR's description) 🙂

**Comment by jorgeorpinel** [comment]
Closing as part of #550 `epic`.
