### ISSUE TITLE
Discrepancy between cloud and local `yarn format-check`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2179]
I'm using `yarn v1.22.10` locally and prettify with `yarn format-all`. `format-check` passes in my setup like

![Screen Shot 2021-02-11 at 12 03 41](https://user-images.githubusercontent.com/476310/107618188-37946900-6c62-11eb-85b5-b4b8fb2ae905.png)

When I submit for a PR, it fails for styling checks. [The differences are in final commas in lists.](https://github.com/iterative/dvc.org/pull/2178/files/c7cb92be18e970db379a8790bc0d651c45fa118b)

<img width="1964" alt="Screen Shot 2021-02-11 at 12 14 08" src="https://user-images.githubusercontent.com/476310/107618470-ab367600-6c62-11eb-8a3f-053b85c1162f.png">

Then when I pull and check these locally, it fails. 

![Screen Shot 2021-02-11 at 12 15 25](https://user-images.githubusercontent.com/476310/107618601-e042c880-6c62-11eb-962b-9eec1dedae1e.png)

CircleCI also seems to follow my local setup and fails for these two files.

<img width="1487" alt="Screen Shot 2021-02-11 at 12 20 26" src="https://user-images.githubusercontent.com/476310/107619073-a6be8d00-6c63-11eb-9bf1-f5120de541d7.png">

It seems restyled bot uses an old version of prettier for markdown. Is there a way to turn it off in some cases?

**Comment by jorgeorpinel** [comment]
@iesahin do you have some node experience as to determine what changes or clarifications we need about this in https://dvc.org/doc/user-guide/contributing/docs#development-environment ?

**Comment by jorgeorpinel** [comment]
Np if not, just curious

**Comment by shcheklein** [comment]
It looks like we are using an older version, @iesahin mind trying to bump it to '^2.2.1', as described here https://docs.restyled.io/available-restylers/ and see if it fixes the discrepancy. I think it's better to run it for all the files and make a separate PR.

**Comment by iesahin** [comment]
I think that's not about version of prettier @shcheklein The most recent Markdown prettier is from 2017. However [in .prettierrc](https://github.com/iterative/dvc.org/blame/master/.prettierrc#L5)  trailingCommas are defined as _none_ and the [default value seems to be *es5* after 2.0.0](https://prettier.io/docs/en/options.html#trailing-commas)

I'll remove trailingCommas line and check whether restyling works similar to the local setup in my next PR. 😄 Adhering to the defaults is a better strategy in my opinion.

**Comment by iesahin** [comment]
I have almost zero node experience @jorgeorpinel but here the culprit seems to be `.prettierrc` I linked above. 😃 No need to change anything in that document.

**Comment by iesahin** [comment]
I submitted #2194 for this. There was a difference in options between 

https://github.com/iterative/dvc.org/blob/d54388af2946a420507b35e313dbcc066b861581/.prettierrc and https://github.com/iterative/dvc.org/blob/20a8a6cceb7089c82fa467d144a0d17388004817/.restyled.yaml

and this was probably causing prettier in restyled.io run differently than local setup.

**Comment by jorgeorpinel** [comment]
Sounds good, thanks for the fix!
