### ISSUE TITLE
cmd: More examples for `dvc gc` is needed to show how cloud/remote garbage collection works

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2181]
Currently `dvc gc` [cmd ref](https://github.com/iterative/dvc.org/blob/5f61a8a1169b8034fcdf4a191f4cc4336e568299/content/docs/command-reference/gc.md) has a single example that shows a local cleanup. It needs more examples to show caveats for the cloud and remote cleanup.

**Comment by shcheklein** [comment]
It think it's a duplicate https://github.com/iterative/dvc.org/issues/154 ? @iesahin please feel free to chime in that one to expand it a bit
