### ISSUE TITLE
Error when running training step in tutorial

### ISSUE THREAD

**Issue by rpelliard** [iterative/dvc.org#220]
Hello,

On this page of the tutorial: https://dvc.org/doc/get-started/pipeline, when running the command 
```
dvc run -d src/train.py -d data/features \
              -o model.pkl \
              python src/train.py -d data/features model.pkl
```

I get the following:

```
Running command:
	python src/train.py -d data/features model.pkl
Arguments error. Usage:
	python train.py features model
```

Looking at `train.py`, it looks like the `-d` causes the mistake and is not necessary.

It also looks like the command is missing a `-f train.dvc` to be consistent with the instructions that follow.

edit: just submitted a PR to fix https://github.com/iterative/dvc.org/pull/221

**Comment by shcheklein** [comment]
Fixed by #221 . Kudos @rpelliard !
