### ISSUE TITLE
syntax highlighting don't always seem to work

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2215]
When working on #2208, I had to indent or de-indent to make syntax highlighting work for `stage:add`.

See: https://github.com/iterative/dvc.org/pull/2208#discussion_r578121470

Maybe it's the issue with the subcommand?

**Comment by jorgeorpinel** [comment]
Hey @skshetry is #1509 basically part of this one? 🙂

**Comment by skshetry** [comment]
@jorgeorpinel, this is about syntax highlighting in the Usage. If you ordered them in a different way or indented them in a different way, highlighting would just fail.

See https://github.com/iterative/dvc.org/pull/2208#discussion_r578121470 and https://github.com/iterative/dvc.org/pull/2208#discussion_r578121864.

**Comment by jorgeorpinel** [comment]
OK. It looks like it's no longer happening. Please approve #2461 which will close this 👍
