### ISSUE TITLE
ref: add --out for local targets

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2220]
UPDATE: I see this is actually possible now (2.0). We should document it!
~~Q: Does the same apply to `import-url`?~~

---

Currently `add -o` only applies to "transferred" (external) data — straight-to-cache/remote functionality.

Since we're allowing `add` to move target data paths now, why not enable it for `targets` in the workspace too? E.g.:

```console
$ ls
yowassup
$ dvc add ./yowassup -o nicername
...
$ ls
yowassup  nicername  nicername.dvc
```

Other than UI consistency, there could be actual use cases for this like tracking copies of a same dataset that you know will have variations in different stages/pipelines (may work well with `foreach` stages).

\+ I assume enabling this at this point is as easy as removing the restriction that prevents it.

**Comment by jorgeorpinel** [comment]
Docs should also clarify that `-o` by itself implies "skip workspace" (straight-to-cache).

**Comment by jorgeorpinel** [comment]
Hi @isidentical. Could you maybe point to the PR where this was introduced? Not critical but could be helpful. Thanks

**Comment by isidentical** [comment]
> Since we're allowing add to move target data paths now, why not enable it for targets in the workspace too

It is already supported.

**Comment by isidentical** [comment]
> Hi @isidentical. Could you maybe point to the PR where this was introduced? Not critical but could be helpful. Thanks

iterative/dvc/pull/5301

**Comment by jorgeorpinel** [comment]
> already supported

Yep thanks @isidentical that's why I had already moved this to the docs repo 🙂 

Thanks for the core PR link!
