### ISSUE TITLE
Breaking changes in 2.0

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2228]
Need a list of all breaking changes in 2.0 to post with release

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/2228#issuecomment-789251163 for summary.

**Comment by dberenbaum** [comment]
See https://github.com/iterative/dvc/pulls?q=is%3Apr+label%3Abreaking-change

**Comment by jorgeorpinel** [comment]
Will this be blogged?

**Comment by dberenbaum** [comment]
Probably so. Thoughts @dmpetrov ?

**Comment by dberenbaum** [comment]
**Summary/questions on breaking changes:**

https://github.com/iterative/dvc/pull/5187 @efiop 
What is the breaking change? Did behavior change for stages without deps or outs?

https://github.com/iterative/dvc/pull/5128 @skshetry

Is this the only breaking change?

> The only thing that makes v1 -> v2 incompatible is the parametrization syntax (foreach .. do and vars can be made compatible). As an example, if user were using ${TMPDIR} in the cmd, v2 will start complaining considering it as a parametrization syntax rather than an env var and they'd have to escape them with \ (as, \${TMPDIR}).

Let me know your feedback on this proposed summary: "Environment variables inside the `cmd` of a stage using `${VAR}` syntax must be escaped as `\${VAR}` in 2.0 due to the use of `${}` syntax for templating."

https://github.com/iterative/dvc/pull/5063 @skshetry 
When was `set` supported? What was the syntax for it? Was this an "experimental" feature? I'm wondering if this actually needs to be documented as a breaking change for the release.

https://github.com/iterative/dvc/pull/4910 @pmrowla 
Similar to the one above, since experiments have been only implemented so far as an experimental feature, do we need to document changes to them as "breaking" for the release?

**Comment by pmrowla** [comment]
I don't think the experiments change needs to be documented as breaking, that PR and the notes on the wiki page were flagged as breaking for any users that had been testing the experimental feature already

**Comment by isidentical** [comment]
iterative/dvc#5527 dropped support for external outputs in google storage, and also changed the default checksum from md5 to etag.

**Comment by dberenbaum** [comment]
> [iterative/dvc#5187](https://github.com/iterative/dvc/pull/5187) @efiop
> What is the breaking change? Did behavior change for stages without deps or outs?

Stages without dependencies will not always run as if changed. Instead, use `--always-changed`.

Thoughts on the wording @efiop?

> [iterative/dvc#5063](https://github.com/iterative/dvc/pull/5063) @skshetry
> When was `set` supported? What was the syntax for it? Was this an "experimental" feature? I'm wondering if this actually needs to be documented as a breaking change for the release.

Experimental feature - doesn't need to be documented.

**Comment by dberenbaum** [comment]
Updated breaking changes summary:

* Dropped support for external outputs in Google Cloud Storage and changed the default checksum from md5 to etag.
* Dropped support for login with p12 files on service authentication for Google Drive.
* Stages without dependencies will not always run as if changed. Instead, use `--always-changed`.
* Environment variables inside the cmd of a stage using `${VAR}` syntax must be escaped as `\${VAR}` in 2.0 due to the use of `${}` syntax for templating.

**Comment by jorgeorpinel** [comment]
Note that for now at least these are listed in https://github.com/iterative/dvc/releases/tag/2.0.0 so users can potentially find the info from dvc.org/doc (clicking on changelog and scrolling).

**Comment by jorgeorpinel** [comment]
Oh. It's also published on https://dvc.org/blog/dvc-2-0-release so is this issue addressed?

**Comment by dberenbaum** [comment]
Yup, thanks for pinging me on this one!

**Comment by VOvchinnikov** [comment]
Are there any plans to restore the support for external outputs for Google Cloud Storage any time soon? Or at all, for that matter?
That would've been greatly appreciated 😃

**Comment by daavoo** [comment]
> Are there any plans to restore the support for external outputs for Google Cloud Storage any time soon? Or at all, for that matter?

Hi @VOvchinnikov , do you mind opening a feature request in https://github.com/iterative/dvc-gs

**Comment by VOvchinnikov** [comment]
@daavoo not at all, will do just that, thanks!
