### ISSUE TITLE
Document `--checkpoint` flag

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2253]
Document `--checkpoint` flag in `stage add` and other commands. @jorgeorpinel @pmrowla @skshetry

**Comment by jorgeorpinel** [comment]
> --checkpoint flag in stage add and other commands

Adding to #2242 @dberenbaum but I can only find that flag in `stage add`.

**Comment by jorgeorpinel** [comment]
Wait. It's in the code base, but not coming up in `stage add -h` yet. Maybe it's hidden? We could find the core issue that will enable it instead, and manage the docs from there.

https://github.com/iterative/dvc/blob/cf1070a531456a267c3b57a35d17795397437699/dvc/command/stage.py#L253-L259

**Comment by jorgeorpinel** [comment]
See https://github.com/iterative/dvc/pull/5263#pullrequestreview-609171552

**Comment by dberenbaum** [comment]
Thanks @jorgeorpinel. Looks like it's suppressed. I can open a core issue to get that sorted.
