### ISSUE TITLE
Exp Get Started

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2268]
Child issue of #2266 

# Proposed requirements
* Introduce experiments features
* Provide easy-to-understand example
* Show basic value of experiments

# Proposal

### Phase 1

The existing get started guide was updated to:

1. Add a new "Experiments" page at the end, which adds to the existing project with `exp` features.
2. Change the previous "Experiments" page to "Metrics, parameters, and plots"; update the wording to reflect that this page's purpose is to introduce tracking metrics, parameters, and plots, not to suggest a workflow for running experiments.
3. Update the project with additional parameters, metrics, and plots to make it a more complete ML project example and provide enough opportunities for parameter tuning to show the value of `exp`.

**Status**: Completed

### Phase 2

A distinct guide for getting started with experiments separate from other docs. Details TBD.

**Status**: Under consideration

# Questions

* What kind of example project is best?
* Which experiment features should it include?
* Should checkpoints be separate?
* How distinct should it be from other get started sections and DVC features?
* Where would a new get started example fit into doc structure?

# Comments

I don't yet have a clear vision of the value added by a new get started page or project, and I have some reasons to prefer keeping it as is (besides the obvious less work involved):
* The current doc fits into the site structure, and it's unclear where a new standalone get started page could go
* No feedback yet on how well the existing page works or what needs to be addressed
* The updated project reflects a common class of models for which hyperparameter tuning experiments are common
* A deep learning project would focus primarily on checkpoints, and many users will only be interested in either checkpoints or parameter tuning (covering both may be overwhelming and unnecessary for many)
* Parameters and metrics are necessary prerequisites, which are introduced in the previous page
* Skipping other get started pages is easy using the project repo's Git tags, although this could be made more explicit so that know that they can jump around to any relevant page

**Comment by shcheklein** [comment]
@dberenbaum this looks great!

> The current doc fits into the site structure, and it's unclear where a new standalone get started page could go

My biggest concern (the last two points in your list) about the current page that it builds on top of all the previous pages, while I think experiments are powerful enough to serve as one of the primary entry points (and explain other features, including data management from the experiments POV). It feels that we hide it too much, it feels like it's an auxiliary feature, etc.

> No feedback yet on how well the existing page works or what needs to be addressed

we can (and probably should) analyze the funnel (GA) - how many people come to different pages. Do some experiments (try to drive people directly to the Experiments page) and see what's going, are there any complains, how do people read that page and where do they navigate from it, etc

> A deep learning project would focus primarily on checkpoints, and many users will only be interested in either checkpoints or parameter tuning (covering both may be overwhelming and unnecessary for many)

... it can also cover `dvclive` scenarios?
