### ISSUE TITLE
cases: Experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2270]
~~Child issue of #2266~~

Proposed requirements

- Identify potential opportunities to use experiments
- Show value added by experiments

Questions

- Is this needed as a separate section?
- Are example projects needed for this?
- Who is the target user to read this over other exp docs?

**Comment by jorgeorpinel** [comment]
My first Q here is what Is the use case we want to write? "Experiment Management" could be it but it's a bit broad and not obvious to differentiate with the existing guide (#2269).

**Comment by jorgeorpinel** [comment]
Ideas for slightly more specific use cases:

- Hyperspace exploration (examples + params & metrics)
- Tuning/Optimization (same as above I guess)
- Visualizing Data Science (experiments + metrics/plots)

@dmpetrov and @shcheklein probably have better suggestions.

**Comment by jorgeorpinel** [comment]
This one was probably useful too! Esp. https://github.com/iterative/dvc.org/issues/2270#issuecomment-793269476

**Comment by dberenbaum** [comment]
I was thinking we could open new issues when we have specific use cases in mind ready to develop, but no problem if having this open as a placeholder with some ideas is helpful for you.

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc.org/issues/2490#issuecomment-843685144:

> Idea: **Experiments tracking/management** - here we should sell W&B, MlFlow, etc - rapid iterations, live metrics + other metrics + navigation

I'm still unclear whether an experiment-related use case would be a higher priority than a modeling-related one (#2490)

Cc @shcheklein

**Comment by jorgeorpinel** [comment]
But I would think the ML model direction has been waiting for a use case for longer so I'd go for that first.

**Comment by shcheklein** [comment]
The initial title was `Exp Use Case` which is different from the `Experiments direction` to me, unless I'm missing something. It's one vs many.

**Comment by jorgeorpinel** [comment]
Sorry for the confusion. This one is meant also as a container of several use case ideas related about the experimentation process. There are some ideas in https://github.com/iterative/dvc.org/issues/2270#issuecomment-793269476 above, but less developed than https://github.com/iterative/dvc.org/issues/2490#issuecomment-845449951. I think that other direction has waited much longer for a use case so I'm focusing on that, but if you guys want me to consolidate both tickets I can do so.

**Comment by jorgeorpinel** [comment]
Closing in favor of #2544 epic.
