### ISSUE TITLE
cmd ref: clarify metric file type auto detection and it's relationship with `-x` (add, modify, show subcommands)

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#229]
JSON metric files are detected by `dvc metrics` based on their file extensions (see iterative/dvc/issues/1553).

> E.g. if we see that output has .json suffix, we could safely assume that it is --type json without explicitly specifying it.

**Comment by shcheklein** [comment]
Related to https://github.com/iterative/dvc/pull/1809 and https://github.com/iterative/dvc/issues/1553

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc.org/pull/228#issuecomment-478690046

**Comment by jorgeorpinel** [comment]
Sorry, auto detection of? Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel have you checked the links here https://github.com/iterative/dvc.org/issues/229#issuecomment-478666994 by any chance? I think those should describe the case more or less.

**Comment by jorgeorpinel** [comment]
Got it. Updated title and description. Thanks

**Comment by srishti-nema** [comment]
Hey @jorgeorpinel , I want to work on this issue. Can I take this up?

**Comment by jorgeorpinel** [comment]
Yeah @srishti-nema sure! Now that I read this issue I'm not sure how introductory it is 😅 but it should be a good challenge. Are you already familiar with DVC metrics? See https://dvc.org/doc/command-reference/metrics

**Comment by srishti-nema** [comment]
I saw [this](https://github.com/iterative/dvc.org/pull/228#issuecomment-478912209) and thought we need to make changes in the docs of repro command. Also, the show() documentation has not been updated yet according to [#228](https://github.com/iterative/dvc.org/pull/228), do I need to make changes there?

**Comment by jorgeorpinel** [comment]
> I saw this (iterative/dvc.org/pull/228) and thought we need to make changes in the docs of repro

Hmmm good find, yes maybe the `-m` option of `dvc repro` in https://dvc.org/doc/command-reference/repro#options could use updating as well. But again, this issue's main goal is stated in the title, and involves the `dvc metrics add/modify/show` subcommands.

But I'm starting to think this whole issue may be outdated though, as it's over a year old. For starters, we only support JSON metrics right now (soon to add YAML).

Let's ask @shcheklein or @efiop to confirm.

Meanwhile @srishti-nema I recommend you either a) learn how to use DVC metrics and try to reproduce this issue (JSON metric type autodetection by file extension when -t isn't provided to `dvc metrics show` for example) and figure out whether all the documents we've mentioned are up to date; or b) pick another issue. Thanks

**Comment by shcheklein** [comment]
I think it's not relevant anymore.
