### ISSUE TITLE
remote: where do I find key id and secrets for other remotes

### ISSUE THREAD

**Issue by Instantnoodles-madman** [iterative/dvc.org#2298]
> I'm a bit lost where the original source of these two keywords, but they are what work instead of

they come from the `remote modify` docs - https://dvc.org/doc/command-reference/remote/modify (S3 section)

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/1994#discussion_r533906459_

for other s3 (not Amazon),how to set key_id and secret?

**Comment by shcheklein** [comment]
@Instantnoodles-madman could you give us a bit more details? what storage are you trying to use? is it S3-compatible?

**Comment by jorgeorpinel** [comment]
> how to set key_id and secret?

@Instantnoodles-madman Please see https://dvc.org/doc/command-reference/remote/add#supported-storage-types for basic configuration of each remote type.

For specific ways to configure authentication on each one, the expandable sections in https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type have all the details.

Does that answer your question?

**Comment by Instantnoodles-madman** [comment]
> @Instantnoodles-madman could you give us a bit more details? what storage are you trying to use? is it S3-compatible?

Yes，my storage is s3-compatible, but it is different from aws-s3  ,and it is corporate intranet
What should I do, I want to use dvc

**Comment by shcheklein** [comment]
@Instantnoodles-madman there is the `Click for S3 API compatible storage` section in the https://dvc.org/doc/command-reference/remote/add#supported-storage-types and here https://dvc.org/doc/command-reference/remote/modify . It has some information on how to setup an S3 compatible storage. Please let us know if you have more questions.

**Comment by Instantnoodles-madman** [comment]
> @Instantnoodles-madman there is the `Click for S3 API compatible storage` section in the https://dvc.org/doc/command-reference/remote/add#supported-storage-types and here https://dvc.org/doc/command-reference/remote/modify . It has some information on how to setup an S3 compatible storage. Please let us know if you have more questions.

I did the configuration according to the guide,but there is wrong when i execute 'dvc push'
the.wrong is:  500 when calling the listobjects operation (reached max retires:4):internal server error

**Comment by shcheklein** [comment]
@Instantnoodles-madman could you share then a bit more details, let's first start with the `dvc push -v` log please (please make sure you replace any important information in the log with `****` or something).

also, `500` is the Internal Server Error, what storage do you use? Can it happen that it doesn't support certain operations (means not fully S3 compatible)?
