### ISSUE TITLE
how to: "update your pipeline by editing DVC-files"

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#230]
See https://github.com/iterative/dvc/issues/1800#issuecomment-478994887 .

Might be worth publishing under "Best Practices" https://github.com/iterative/dvc.org/issues/72 .

**Comment by Naba7** [comment]
Can I take this up? I will first summarize it then write markdown for it.

**Comment by shcheklein** [comment]
@Naba7 sounds good. But it should be part of the User Guide section - "Updating DVC-files" - or something like this.

**Comment by Naba7** [comment]
@shcheklein 

How to update your pipeline by editing dvc files

1)using dvc move to edit file paths of outputs or dependencies.
2)editting by hand the outputs paths
3)dvc run to make edits in the dependency files

If your source file is a data file, then use dvc move:
dvc move
dvc move is used if a file or a directory has been added to DVC with dvc 
add. the source file or directory is moved to its destination path, renamed 
and corresponding DVC-file is updated.

If your source file isn't data file then use dvc run. If you use dvc add then git mv command
then your path isn't updated. So, using git mv is not an option.

dvc run is used to create a dvc pipeline. It can be shown in a connected graph.
While running dvc run and executing commands with [-f,-o,-O,-m,-M] you can edit your files
and directories by hand. dvc run connects each individual staged commands to a graph.


is this okay? or any edits

**Comment by ryokugyu** [comment]
@shcheklein @Naba7 
imo, lets try to avoid editing by hands.  
use `dvc run` and `dvc commit` options. such as `--no-exec` options.
for more reference, visit [here](https://github.com/iterative/dvc.org/issues/460).

lately, I was busy with college evaluations.  Also started writing an article `Editing DVC pipelines`  [in this pull request](https://github.com/iterative/dvc.org/pull/479).

**Comment by Naba7** [comment]
@ryokugyu Yes, I will mostly prefer dvc run and dvc commit but the user should know that it can be editted by hand. Well, I will add *most-preferable* under dvc run section, what say?

**Comment by jorgeorpinel** [comment]
Closing in favor of #72
