### ISSUE TITLE
Decouple checkpoints and make_checkpoint

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2319]
### References to checkpoints all refer to or imply use of `make_checkpoint()`

https://dvc.org/doc/command-reference/exp/run:

> Then, in the corresponding code, either call the dvc.api.make_checkpoint() function (Python), or write a signal file (any programming language) following the same steps as make_checkpoint() — please refer to that reference for details.

https://dvc.org/doc/user-guide/experiment-management references checkpoints only in the context of "in-code" checkpoints:

> Place in-code checkpoints that mark a series of variations, forming a deep experiment.

> Checkpoints in source code

> To track successive steps in a longer experiment, you can write your code so it registers checkpoints with DVC at runtime. This allows you, for example, to track the progress in deep learning techniques such as evolving neural networks.

https://dvc.org/doc/api-reference/make_checkpoint obviously references `make_checkpoint()` 😄 , but the example includes a lot of explanation of checkpoints that probably belongs elsewhere.

### `make_checkpoint()` is not the only way to use checkpoints
* As noted in #2292, a regular stage with an output set to `checkpoint: true` can be used to generate a single checkpoint each run.
* As noted in the quote from https://dvc.org/doc/command-reference/exp/run above, signal files may be used to generate checkpoints (we probably need another issue to document this better).
* `dvclive.next_step()` can generate checkpoints.

I'm not even sure that `make_checkpoint()` will be the primary way to use checkpoints in the future (I'd probably prefer to use the other options that won't break if I run my command outside of dvc).

Regardless of how we document these options and which ones we suggest, we should keep the general concept of checkpoints separate from the `make_checkpoint` and the other ways to invoke checkpoints.

**Comment by jorgeorpinel** [comment]
Thanks for the structured docs feedback! This will be pretty helpful to address #2292 but otherwise, I'm not sure we need 2 issues?

> make_checkpoint() ... the example includes a lot of explanation of checkpoints that probably belongs elsewhere.

I think I addressed this in https://github.com/iterative/dvc.org/pull/2300/commits/1be2070642d90483754741ad3b467c2fbbdb9838. PTAL

**Comment by dberenbaum** [comment]
> Thanks for the structured feedback @dberenbaum! This will be pretty helpful to address #2292, but otherwise, I'm not sure we need to keep both issues?

Sure, I guess I realized the smaller issue in #2292 first and later realized it's part of this larger issue. Feel free to consolidate them however you want.

> I think I addressed this in [1be2070](https://github.com/iterative/dvc.org/commit/1be2070642d90483754741ad3b467c2fbbdb9838) (WIP). PTAL

Great! There still might be more that can be cut from that example, but hard to say until other sections on checkpoints are expanded, so let's revisit later.

**Comment by jorgeorpinel** [comment]
Added a checkbox over there 👍
