### ISSUE TITLE
external-outs: mention `dvc add url`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#232]
Currently, we only mention that you can specify your remote output in the `dvc run` command, but we don't say anything about an ability to `dvc add` your remote files.

**Comment by AJ-54** [comment]
How to add this? I mean, inside each code block where we have written dvc remote, dvc config, dvc run or it should be added as a separate block at the end???

**Comment by efiop** [comment]
Hi @AJ-54 !  Thanks for looking into this! :slightly_smiling_face:  Would probably add that in each block in https://dvc.org/doc/user-guide/external-outputs along with `remote/config/run`, just to make it easier to navigate.

**Comment by AJ-54** [comment]
Can you provide me a sample as to how to incorporate this? For example, consider Amazon S3. what will be the code of dvc add URL for this one? 
As I don't know the functionality, I am assuming that I can do this only after you tell me for at least one example.
Thanks for the mention @efiop!

**Comment by efiop** [comment]
@AJ-54 For example
```
    # Add S3 remote to be uses as cache location for S3 files
    $ dvc remote add s3cache s3://mybucket/cache

    # Tell dvc to use the 's3cache' remote as S3 cache location
    $ dvc config cache.s3 s3cache

    # Add data on S3 directly
    $ dvc add s3://mybucket/mydata

    # Run the stage with external S3 output
    $ dvc run \
              -d data.txt \
              -o s3://mybucket/data.txt \
              aws s3 cp data.txt s3://mybucket/data.txt
```

**Comment by AJ-54** [comment]
I have made a pull request by performing the required changes as understood by me.
Kindly have a look @efiop and suggest changes if required.
Thank you for the coordination!!
