### ISSUE TITLE
ref: example to track multiple copies of the same cache entry?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2326]
Is the following a use case we may want to document (as an exmple in https://dvc.org/doc/command-reference/import-url)?

```console
$ md5sum ../data
6137cde4893c59f76f005a8123d8e8e6  ../data
$ dvc import-url ../data data1
$ dvc import-url ../data data2
$ dvc import-url ../data data3
$ md5sum data?
6137cde4893c59f76f005a8123d8e8e6  data1
6137cde4893c59f76f005a8123d8e8e6  data2
6137cde4893c59f76f005a8123d8e8e6  data3
$ tree .dvc/cache
.dvc/cache
└── 61
    └── 37cde4893c59f76f005a8123d8e8e6
```

Only one cache entry was created, but there's 3 outputs (and .dvc files) in the workspace that share it. Wondering if there are uses for this or if it's just a side effect.

**Comment by shcheklein** [comment]
This is not specific to the `import-url`. This is how DVC's storage is organized in a content-addressable way. It means pretty much that if content is the same (has the same md5) it has the same address (file path).

**Comment by jorgeorpinel** [comment]
Right, `import-url` here just works as an example then. But is this a wider use (for any commands e.g. `add` or manually writing .dvc files + `commit`) we should consider documenting? Maybe there's a reason to multiply a dataset to develop "mutations" in a pipeline starting from a single cached file/dir.

**Comment by shcheklein** [comment]
It might be, not sure it deserves a whole example to be honest. May be mention somewhere that it's possible and there is no contradiction - someone could import multiple times, or multiple versions of the same dataset into different destionations.

**Comment by jorgeorpinel** [comment]
Prob not needed then.
