### ISSUE TITLE
ref: `cmd` should be able to create at `repro`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#233]
From https://github.com/iterative/dvc/issues/1800#issuecomment-480059069

> another factor contributing to my problems with dvc repro has to do with particularities around listing file folders as outputs in a .dvc file.
>
> This may seem obvious, but if file folders are listed as outputs in a particular stage, users need to ensure that the command for that stage includes a means of checking for the folder's existence and creating it if it doesn't exist. Otherwise dvc repro will fail due to a FileNotFoundError when that stage's command is executed (because dvc repro will have deleted those folders before executing the stage's command).

**Comment by Zenix27** [comment]
I can work on this

**Comment by jorgeorpinel** [comment]
@Zenix27 lets focus on one issue at a time please. Do you prefer this or #540? Thanks

**Comment by Zenix27** [comment]
Let's work on this for now and I've gone through https://dvc.org/doc/user-guide/contributing/docs

**Comment by jorgeorpinel** [comment]
Sounds good, so please open a PR that mentions this issue when ready and lmk if you need any help in the meantime. You can find me on Discord directly. Thanks

**Comment by shcheklein** [comment]
I haven't see that many people complaining about it + a lot of things have changed (e.g. we focus more on `dvc exp run` now). Let's come back to this if we see this is still an issue.
