### ISSUE TITLE
DVC badge

### ISSUE THREAD

**Issue by Casyfill** [iterative/dvc.org#234]
thought it would be great to have a DVC badge - mainly for devs to note we're using it
![dvc](https://img.shields.io/badge/dvc-945DD5.svg)

**Comment by casperdcl** [comment]
We finally have [shields.io](https://shields.io) & [simpleicons](https://simpleicons.org/?q=dvc) support! :tada: Here's what your README can look like:

# My Project README.md

[![Tests](https://github.com/iterative/dvc/actions/workflows/tests.yaml/badge.svg)](https://github.com/iterative/dvc/actions/workflows/tests.yaml)   ![DVC](https://img.shields.io/badge/-tracked-white.svg?logo=data-version-control&link=https://dvc.org)   [![DVC](https://img.shields.io/badge/-Data_Version_Control-white.svg?logo=data-version-control&style=social)](https://dvc.org)   ![DVC-accuracy](https://img.shields.io/badge/dynamic/json?logo=data-version-control&colorA=black&colorB=F46737&label=Model%20Accuracy&url=https://github.com/iterative/get-started-experiments/raw/main/metrics.json&query=categorical_accuracy)

Yes, yes the accuracy metric example above is dynamic and not hard-coded :rocket:


<details>

![DVC](https://img.shields.io/badge/-tracked-white.svg?logo=data-version-control&link=https://dvc.org)
`![DVC](https://img.shields.io/badge/-tracked-white.svg?logo=data-version-control&link=https://dvc.org)`

[![DVC](https://img.shields.io/badge/-Data_Version_Control-white.svg?logo=data-version-control&style=social)](https://dvc.org)
`[![DVC](https://img.shields.io/badge/-Data_Version_Control-white.svg?logo=data-version-control&style=social)](https://dvc.org)`

![DVC-accuracy](https://img.shields.io/badge/dynamic/json?logo=data-version-control&colorA=black&colorB=F46737&label=Model%20Accuracy&url=https://github.com/iterative/get-started-experiments/raw/main/metrics.json&query=categorical_accuracy)
`https://img.shields.io/badge/dynamic/json?logo=data-version-control&colorA=black&colorB=F46737&label=Model%20Accuracy&url=https://github.com/iterative/get-started-experiments/raw/main/metrics.json&query=categorical_accuracy`

</details>

**Comment by 0x2b3bfa0** [comment]
Wow! That's amazing! 🎉  Perhaps related to https://github.com/iterative/cml/issues/219?

**Comment by jendefig** [comment]
Ooooo!  Que fancy!  Love it @casperdcl !!!  Is there a reason why you chose the purple? Not finding fault, just wondering.  I am a fan of purple.

**Comment by daavoo** [comment]
I think a `View in Studio` badge would be also a nice touch for our example repos. 

Currently, unless someone has already created a public view, it is kind of tedious to go from a  Github repo to a Studio view.

cc @iterative/studio

**Comment by jorgeorpinel** [comment]
Closing for now (please reopen if I'm missing something)

> I think a View in Studio badge would be also a nice

@daavoo mind opening that in https://github.com/iterative/studio-support/issues ?

**Comment by jorgeorpinel** [comment]
Maybe somewhere in https://dvc.org/doc/user-guide/contributing ? Please do/open new issue/reopen this one & self assign or otherwise, as you see fit. Thanks
