### ISSUE TITLE
blog: tag cloud

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2356]
> From https://github.com/iterative/dvc.org/issues/2340#issuecomment-809898588

- Have a tag cloud feature, or any graphic way to navigate blog post tags (see GraphQL query in https://github.com/iterative/dvc.org/issues/2340#issuecomment-810398961)
- Ignore single-use labels by default.
- But we should probably have a list somewhere that shows off all Tags.

**Comment by julieg18** [comment]
#1657 also has some discussion around this subject

**Comment by julieg18** [comment]
Since #1657 seems to discuss the same thing, I'm going to go ahead and close this.
