### ISSUE TITLE
guide: Sharing Experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2367]
The utility of `dvc exp push` and `dvc exp pull` isn't all that clear now. It would be great to develop a typical scenario to show how sharing experiments is useful.

Ideas:
* If several experiments have similar metric values and I want to share with my team before deciding which experiment to choose.
* If I need to keep a record of alternative experiments that I tried to document/audit my model development process.

Extracted from #2269.

**Comment by jorgeorpinel** [comment]
I'd go for a guide on this (there are some exp-related use case ideas in https://github.com/iterative/dvc.org/issues/2270#issuecomment-793269476).

I think we'll want to make https://dvc.org/doc/user-guide/experiment-management a section and have sub-pages. This can be one of them.
