### ISSUE TITLE
user-guide: add "Define remote through another remote"

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#237]
From https://github.com/iterative/dvc/issues/1614
Related https://github.com/iterative/dvc.org/issues/108

**Comment by jorgeorpinel** [comment]
Where do you think this example, note (or full page?) could be located @efiop? Other than in get/import (that's #108). Thanks

**Comment by efiop** [comment]
@jorgeorpinel Again, sorry for the delay. I think it might be worth creating a user-guide page for it and reference it in all the commands that support remote:// notation.

**Comment by jorgeorpinel** [comment]
No worries, thanks for the follow up. I read https://github.com/iterative/dvc/issues/1614#issue-410750987 and I think probably this would be a relatively short note or section so not sure its worth a full new guide. Maybe just another section of `dvc remote add`

**Comment by shcheklein** [comment]
This is too complicated, I haven't seen a need for this tbh. Let's not document this for now.

**Comment by efiop** [comment]
Well, users are using this and this is the only appropriate method available right now. Reopening.

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc.org/issues/4804
