### ISSUE TITLE
ref: doc `params/exp show/diff --param(-deps)`

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#2371]
After https://github.com/iterative/dvc/pull/5550 we support showing param dependencies for `params` and `exp` commands.

**Comment by jorgeorpinel** [comment]
Are you able to self-assign @pared, or should I triage this? Np either way

**Comment by jorgeorpinel** [comment]
@pared feel free to contribute something to #2421 (if you have a chance) and I'll polish it up. Thanks

**Comment by pared** [comment]
Close after #2421 and #2442 are merged.
