### ISSUE TITLE
remote: 2 Qs about Azure params

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2376]
> Continues https://github.com/iterative/dvc.org/pull/2226#issuecomment-806200723

1. What about `AZURE_STORAGE_CONNECTION_STRING` and `AZURE_STORAGE_CONTAINER_NAME`?
2. What happens first, Azure "default credential" or Microsoft account login?

**Comment by jorgeorpinel** [comment]
On 1. @isidentical you mentioned the env vars are still supported. OK but which ones do we recommend? `remote modify` doesn't mention them at all, and `remote add` doesn't mention any of the new stuff.
Please notice 2. above as well. Thanks

**Comment by jorgeorpinel** [comment]
> we should be supporting AZURE_STORAGE_CONNECTION_STRING directly
From https://discord.com/channels/485586884165107732/563406153334128681/832317518852653137

Right, we support them. What I'd like to understand is why there's the old env vars (`AZURE_STORAGE_CONNECTION_STRING`, `AZURE_STORAGE_CONTAINER_NAME`) and at the same time new env vars (`AZURE_STORAGE_ACCOUNT_NAME`, etc.) some of which seem similar. Maybe we just missed including the old ones in the update to `remote modify`? And again is connection_string still the easiest option that we want to feature in `remote add`? Thanks

**Comment by isidentical** [comment]
> On 1. @isidentical you mentioned the env vars are still supported. OK but which ones do we recommend? remote modify doesn't mention them at all, and remote add doesn't mention any of the new stuff.

So basically environment variables are automatically supported, with the pattern of `AZURE_STORAGE_{CONFIG_VAR}`. Here is a list;
https://github.com/iterative/dvc/blob/ca7a02d5220ab85bbde12a85604e0f9a7fad61ca/dvc/fs/azure.py#L58-L70

- `AZURE_STORAGE_CONNECTION_STRING` (connection_string)
- `AZURE_STORAGE_ACCOUNT` (account_name)
- `AZURE_STORAGE_KEY` (account_key)
- `AZURE_STORAGE_SAS_TOKEN` (sas_token)

The `AZURE_STORAGE_CONTAINER_NAME` is not an authentication option but rather something that we use if there is no bucket specified in the path (? is this still needed, this part is kept for the backward compatibility from the old code). https://github.com/iterative/dvc/blob/ca7a02d5220ab85bbde12a85604e0f9a7fad61ca/dvc/fs/azure.py#L44-L46

**Comment by isidentical** [comment]
> Right, we still support that. What I'd like to understand is why there's the old env vars (AZURE_STORAGE_CONNECTION_STRING, AZURE_STORAGE_CONTAINER_NAME) and at the same time new env vars (AZURE_STORAGE_ACCOUNT_NAME, etc.) some of which seem similar

I am not sure what you mean by old/new vars, though the list I just shared should contain all the env variables we officially support (and they don't overlap).

**Comment by jorgeorpinel** [comment]
> environment variables are ~~automatically~~ supported, with the pattern of `AZURE_STORAGE_{CONFIG_VAR}`

Ah very useful info, thanks! Will update docs.

> The AZURE_STORAGE_CONTAINER_NAME is not an authentication option but rather something that we use if there is no bucket specified in the path (? is this still needed, this part is kept for the backward compatibility

Sounds like we should remove it! ⌛ 

> not sure what you mean by old/new vars

`AZURE_STORAGE_CONTAINER_NAME` is an old env var it seems. Anyway, got it now, thanks @isidentical .

**Comment by jorgeorpinel** [comment]
> Sounds like we should remove it

@isidentical 🐸🎩 could you update the Azure instructions in https://dvc.org/doc/user-guide/contributing/core#testing-remotes ? I'll take care of the other instances of `AZURE_STORAGE_CONTAINER_NAME` in docs. Feel free to commit to #2390

**Comment by jorgeorpinel** [comment]
> Here is a list: https://github.com/iterative/dvc/blob/ca7a02d5220ab85bbde12a85604e0f9a7fad61ca/dvc/fs/azure.py#L58-L70

Oh one more Q @isidentical:

You didn't include `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, or `AZURE_CLIENT_CERTIFICATE_PATH` in your list. In the code I see the first 2 are OK but not sure about the third. Is it actually `AZURE_CLIENT_SECRET` (line 73)? (If you commit to the PR maybe update that too if the `remote modify` we merged ref is wrong.)

**Comment by jorgeorpinel** [comment]
Hi @0x2b3bfa0 do you know if there's another way to setup Azure for CML other than with the `AZURE_STORAGE_CONTAINER_NAME` env var? https://dvc.org/doc/cml/cml-with-dvc and https://dvc.org/doc/cml/self-hosted-runners mention that var but it seems to be legacy on DVC at least.

**Comment by jorgeorpinel** [comment]
@isidentical please also notice question 2. "What happens first, Azure "default credential" or Microsoft account login?" Thanks agian

**Comment by 0x2b3bfa0** [comment]
Good question, @jorgeorpinel! I assume that your links refer to these two storage-specific snippets:

https://github.com/iterative/dvc.org/blob/0d72e5882e1f8679338a3b897dcaaf1e17620bdb/content/docs/cml/cml-with-dvc.md#L84-L87
https://github.com/iterative/dvc.org/blob/930b2c7b49ad7f131a164482c6d7e9e50a384f5f/content/docs/cml/self-hosted-runners.md#L141-L144

These environment variables are being directly interpreted by the platform-specific runner, so you can change them to whatever you want without breaking anything. The only requirement is that they work with DVC, obviously. 😄

**Comment by jorgeorpinel** [comment]
> The only requirement is that they work with DVC, of course.

Oh I see. OK, I'm removing the `AZURE_STORAGE_CONTAINER_NAME` lines in ad188e31, since the recommended way to setup the remote is to include the container name in the `azure://` URL.

**Comment by isidentical** [comment]
> @isidentical please also notice question 2. "What happens first, Azure "default credential" or Microsoft account login?" Thanks agian

Microsoft account login is part of the default credentials flow (it includes many different methods which are tried in order).

**Comment by jorgeorpinel** [comment]
Got it @isidentical. I clarified this a bit more in #2407 (should close this issue).

The only pending Q is https://github.com/iterative/dvc.org/issues/2376#issuecomment-821755139 ☝️ 

> You didn't include AZURE_TENANT_ID, AZURE_CLIENT_ID, or AZURE_CLIENT_CERTIFICATE_PATH in your list. In the code I see the first 2 are OK but not sure about the third. Is it actually AZURE_CLIENT_SECRET (line 73)?

**Comment by jorgeorpinel** [comment]
p.s. I see those env vars (and others) are [built into](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python) the Azure DefaultCredential process (clarified in docs). OK, all good here!
