### ISSUE TITLE
site closes when clicking a link from the hamburger menu

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2394]
### How to reproduce
1. Open https://dvc.org using "**Open in a new tab**" in the context menu from your phone (or, in a responsive mode from console). Please don't type, just use that earlier link.
2. Open hamburger menu and click on either "Doc" or "Blog".

### Expected
The page opens correctly.

### Actual
The site just closes. 

---

This happens because we are calling the `window.close()` in the `HamburgerMenuIcon`. I am not sure why it happens on a newly opened tab only (somewhere we are opening a new window based on that?).

https://github.com/iterative/dvc.org/blob/f08efbf5d3e25a56551437f557fb28fd0690427f/src/components/HamburgerMenu/index.tsx#L43-L49

This also adds ugly warnings to the console:
```console
Scripts may close only the windows that were opened by them.
```

**Comment by shcheklein** [comment]
I can't reproduce it on Mac (Chrome in a responsive mode)/iPhone, but can confirm warnings in the console. @skshetry what browser do you you use?

**Comment by skshetry** [comment]
@shcheklein, did you use the "Open in a new tab" option for the above link?

**Comment by julieg18** [comment]
I noticed the warnings while updating the hamburger menu and updated the code to stop using the `close()` method. @skshetry, can you confirm that the bug is gone?

**Comment by skshetry** [comment]
Can confirm that it's fixed, and I don't see an error in the console either. Thanks, @julieg18. Closing ...
