### ISSUE TITLE
URLs that contain anchors with reserved chars break the website

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2395]
broken page and:

`Error: SyntaxError: Failed to execute 'querySelector' on 'Document': '#option!134' is not a valid selector.`

on 

https://dvc.org/doc/command-reference/gc#option!134

Priority depends on if we have titles (anchors with `!` and other funny symbols).

**Comment by jorgeorpinel** [comment]
There are such symbols in some titles but they get removed from the anchors (at least `!` and `?`), e.g.
- https://dvc.org/doc/command-reference/init#when-is-this-useful
- https://dvc.org/doc/cml/cml-with-dvc#for-github-actions-users-try-the-setup-dvc-action

**Comment by jorgeorpinel** [comment]
But it's probably an invalid URL in general with anything other than `[A-Za-Z/-._~]` right?

**Comment by shcheklein** [comment]
Yep, doesn't matter anyway, website should not be breaking at least and handle things gracefully.

I would check all anchors that we have to see if we have any (allowed by RFC) symbols that break it. For now making it p1

**Comment by jorgeorpinel** [comment]
Oh I see. I thought it was an URL problem but in fact it looks like special (unreserved) chars only break the site (at loading) when in anchors, indeed.

> I would check all anchors that we have to see if we have any (allowed by RFC) symbols that break it.

Checked all docs headers with regex `^##* .*[;/?:@&=+$,\-_.!~*'()]` (from 2.2 and 2.3 in the RFC) — one ocurence of each char — and they all get removed in anchors (except `-()` which are fine), so 👍 on that front.
