### ISSUE TITLE
ref: clarify `exp apply` behavior

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc.org#2397]
Noticed this issue while reviewing https://github.com/iterative/dvc.org/pull/2383

The docs for `dvc exp apply` currently state that:

> Restores the results of a given experiment (name or hash are accepted, see dvc exp run for details) into the workspace. This means changing the appropriate metafiles, parameter files, metrics, plots, and corresponding DVC-tracked data.
>
> This is similar to dvc checkout, but for dvc experiments.

- [x] 1. `exp apply` will restore the changes to *any* (git or DVC tracked) file from a given experiment. It is not specific to DVC-related files and data. Rather than a simple `dvc checkout`, it's closer to:

```
git checkout <exp-sha>
dvc checkout
```

(specifically, it's more like a `git stash apply` or `git merge --no-commit` than `git checkout`, but typical DVC users are probably not familiar with those commands)

- [ ] 2. The docs should mention that `exp apply` is potentially destructive, and will overwrite any uncommitted changes to the user's (git) workspace, if they conflict with whatever changes exist in the experiment.
  UPDATE: Jump to https://github.com/iterative/dvc.org/issues/2397#issuecomment-827930004

**Comment by shcheklein** [comment]
> and will overwrite any uncommitted changes 

will it drop changes that do not conflict?

**Comment by pmrowla** [comment]
@shcheklein no, any changes which don't conflict will be left alone. It basically just does a git merge/checkout with `--theirs`, meaning that if there are conflicts the version from the experiment is automatically preferred.

Originally, `exp apply` would error out on any conflicts and had a `-f/--force` option to do the `--theirs` overwrite automatically. But based on feedback from @dmpetrov, the typical use case for `exp apply` meant that users would just always need to run it with `--force`.

**Comment by shcheklein** [comment]
I would clarify this. It's important that changes are not wiped out but rather merged with the experiment. I'm a bit worried that pretty much silently user may end up with a mix of changes here.

Does it makes sense to go even further and do `reset --hard`  ?

**Comment by jorgeorpinel** [comment]
> important that changes are not wiped out but rather merged with the experiment. I'm a bit worried

Should we transfer to the core repo for now? I'll address part 1. for now (in #2417)

**Comment by pmrowla** [comment]
Merging/preserving the changes in an unrelated file is a useful feature IMO, especially with regard to the ability to create branches off of existing checkpoints. If I make a code change in one file and then want to test the changes against some other checkpoint branch, I can just `exp apply` the checkpoint and do `exp run`. To me this feels like a similar workflow to

```
<make changes in some code against one branch>
git checkout <branch> # checkout a different branch, those changes will be preserved and now applied to the newly checked out branch
```

With `git checkout`, it will preserve the changes unless there is a conflict w/the new branch - which is the same behavior we have with `exp apply`.

**Comment by jorgeorpinel** [comment]
> ability to create branches off of existing checkpoints

Wouldn't `exp branch` be a better/easier route for this? (Maybe less efficient)

> With git checkout, it will preserve the changes unless there is a conflict

True, and `git stash apply` works similarly.

Up to you guys (but again, seems like a core issue/discussion). For now I have a Q on 1., @pmrowla :

> exp apply is potentially destructive, and will overwrite any uncommitted changes to the user's (git) workspace

This seems to contradict with another https://github.com/iterative/dvc.org/pull/2417#discussion_r619906850:

> It may also fail if there are git conflicts between changes in your workspace and in the experiment... We try to automatically resolve the conflicts by [`git merge --theirs`], but sometimes git may still fail to auto-resolve them.

A bit confused 🙃

**Comment by pmrowla** [comment]
Yes it is essentially `git merge --theirs`. `git merge --theirs` is destructive (it forcefully overwrites any of your conflicting changes)

**Comment by dmpetrov** [comment]
> `git merge --theirs` is destructive (it forcefully overwrites any of your conflicting changes)

it is dangerous but ok. inconsistency (mix of changes) might be even a bigger problem: 

> Does it makes sense to go even further and do `reset --hard` ?

It makes a lot of sense here. 

@pmrowla what do you think about this even more aggressive (but consistent) strategy?

**Comment by shcheklein** [comment]
A suggestion/idea - run stash before doing hard reset, to make sure that nothing is completely lost and it can be reversed/merged.

**Comment by dmpetrov** [comment]
> A suggestion/idea - run stash before doing hard reset, to make sure that nothing is completely lost and it can be reversed/merged.

🤔 good idea.
However, it might confuse a user if he/she is an active stash user. Is there a way to reduce the confusion?

**Comment by pmrowla** [comment]
I'm still not convinced that doing the hard reset is what users would want here?

Let's say I've run some checkpoints and now I see that I want to change some params and re-run from a specific intermediate point. If I prefer editing my params files manually (vs using `-S`) I think I should be able to do

```
vim params.yaml # edit params
exp apply <intermediate-checkpoint>
```

in either order (which is consistent with being able to edit code and then use `git checkout <different-branch>` in either order). With `reset --hard`, I have to do the `exp apply` first or else I lose my changes.

We could consider doing `git stash` automatically, but if the user is unaware of this behavior or just forgets to always use `stash drop/pop` afterwards we will end up filling up their stash with a ton garbage entries very quickly.

**Comment by pmrowla** [comment]
> > ability to create branches off of existing checkpoints
> 
> Wouldn't `exp branch` be a better/easier route for this? (Maybe less efficient)

Also, @jorgeorpinel I missed this comment earlier. With regard to  `ability to create branches off of existing checkpoints` I wasn't talking about Git branches, I was talking about being able to make modifications to an intermediate checkpoint, and then start a new "checkpoint branch" off of that point which contains those modifications. Using `exp branch` here would forces users to create full Git branches for this kind of experimentation, which would defeats the purpose of the entire experiments feature in the first place.

**Comment by jorgeorpinel** [comment]
OK! I'm still confused as to when `exp apply` can fail though. We currently say it may fail depending on Git being able to merge, but it should never fail if it overwrites conflicts with `--theirs`? 

However, since the behavior may change soon, we can fix the docs once that is decided. Mind transferring this to the core repo, guys? Or please clarify what other doc updates are needed. Thanks!

**Comment by pmrowla** [comment]
Maybe I'm misremembering something, but I think there's still certain edge cases where using `--theirs` can fail and still require manually fixing conflicts (mostly involving binary files being tracked with git)?

**Comment by dmpetrov** [comment]
> We could consider doing `git stash` automatically, but if the user is unaware of this behavior or just forgets to always use `stash drop/pop` afterwards we will end up filling up their stash with a ton garbage entries very quickly.

@pmrowla you are right. it creates another layer of complexity. let's not do that.

**Comment by jorgeorpinel** [comment]
> but I think there's still certain edge cases where using --theirs can fail

I don't think `git merge --ours/theirs` can fail (unless there are file system issues or something else not worth considering). https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-ours indicates that it's a forceful operation. I'll update the docs accordingly 👍 - a5de50ba

**Comment by jorgeorpinel** [comment]
> The docs should mention that exp apply is potentially destructive, and will overwrite any uncommitted changes to the user's (git) workspace, if they conflict with whatever changes exist in the experiment.

This is already indicated in https://dvc.org/doc/command-reference/exp/apply now so let's close the issue 👍
