### ISSUE TITLE
Improve explanation of error handling for interrupting checkpoints

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2399]
See https://github.com/iterative/dvc-checkpoints-mnist/pull/2 for background.

Here's the scenario:

1. My script includes a checkpoint (using `make_checkpoint()` or similar) but no error handling for keyboard interuptions.
2. I run an experiment and interrupt it with ctrl-c, which returns a non-0 exit code.
3. I resume the experiment.

If there were changes between the last time `make_checkpoint()` was called and when the experiment was interrupted, step 3 will create a new experiment because there was no final cleanup checkpoint applied at the end of step 2 (if the script exited cleanly with a 0 exit code, there would be a final cleanup checkpoint).

I couldn't figure this out until @pmrowla explained it, so IMO it's not going to be clear to users. Since we recommend this ctrl-c workflow in the docs and in our examples, I think we need to better document it. Thoughts?

**Comment by pmrowla** [comment]
Also should be noted that this is really only an issue for workspace runs, since in temp dir/queue runs the unsaved extra modifications at the end are just discarded entirely.

**Comment by shcheklein** [comment]
@dberenbaum do we know what part of the documentation it affects? (new User Guide section by @flippedcoder , command reference?)

**Comment by dberenbaum** [comment]
It potentially impacts:

* https://dvc.org/doc/command-reference/exp/run#checkpoints
* https://dvc.org/doc/api-reference/make_checkpoint
* maybe the doc @flippedcoder is working on

We will have to consider whether it need to be reflected in each of these sections. I think any examples should include error handling for keyboard interruption between checkpoints if ctrl-c is part of the expected workflow. Also, we should probably explain in detail somewhere. For example, https://dvc.org/doc/command-reference/exp/run#checkpoints states:

> You can now use dvc exp run to begin the experiment. If the process gets interrupted (e.g. with [Ctrl] C or by an error), all the checkpoints so far will be preserved. When a run finishes normally, a final checkpoint will be added (if needed) to wrap up the experiment. 

This could probably be more detailed about how interruptions should be handled and why.

**Comment by jorgeorpinel** [comment]
> should be noted that this is really only an issue for workspace runs

Good point but I'd rather skip that note as it complicates docs and handling errors is a good practice anyway 🙂 

> https://dvc.org/doc/command-reference/exp/run#checkpoints

Updated in b0fe6188 (part of #2417 which I started for other reasons but was already touching that text). It would now read:

> All checkpoints registered at runtime will be preserved even if the process gets interrupted (e.g. with `[Ctrl] C`, or by an error\*). A final checkpoint will be added (if needed) to wrap up the experiment.
>
> \* The stage command should return a non-error exit code (`0`) for the final checkpoint to be generated. Otherwise, it will not be possible to continue this experiment as described below (it will restart from scratch).
>
> Following uses of `dvc exp run` will continue from this point...

**Comment by jorgeorpinel** [comment]
> -  https://dvc.org/doc/api-reference/make_checkpoint

It's funny because we had the interrupt exception in the [example](https://dvc.org/doc/api-reference/make_checkpoint#example-every-100th-iteration) code but decided to remove it during review for simplicity 😆  So should I re-add it (and possibly make a short note about it)?

> - maybe the doc @flippedcoder is working on

As for #2373, maybe under **Registering checkpoints in your code** as a hidden `<details>` section? Something like "What happens if my loop gets interrupted?" perhaps. There's no mention of the final checkpoint either BTW. I suggest you open a review on that PR @dberenbaum and consider it solved here.

I looked and see no other existing docs where this should be mentioned.

**Comment by jorgeorpinel** [comment]
> see no other existing docs where this should be mentioned

Well... Maybe the examples in https://dvc.org/doc/dvclive/usage and https://dvc.org/doc/dvclive/dvclive-with-dvc should handle exceptions then? But it's not checkpoint-specific. Cc @pared

**Comment by dberenbaum** [comment]
> It's funny because we had exception handling in the [example](https://dvc.org/doc/api-reference/make_checkpoint#example-every-100th-iteration) py code originally, but decided to remove it during review for simplicity 😆

Yup, my fault there! I vote to add it back, I didn't understand the implications at the time I suggested it.

> As for #2373, maybe under **Registering checkpoints in your code** as a hidden `<details>` section? Something like "What happens if my loop gets interrupted?" perhaps. There's no mention of the final checkpoint either BTW. I suggest you open a review on that PR @dberenbaum and consider it solved here.

👍

**Comment by jorgeorpinel** [comment]
> Yup, my fault there! I vote to add it back

No worries, I think we all missed the implications and agreed to remove it. OK, reinstated in c54813b5.

**Comment by pared** [comment]
@jorgeorpinel I think there should be some pointer in `dvclive` section to exception handling, though I am not sure it should be explained extensively there - main point there is to pass the knowledge on `dvclive` usage. So I would think about something like 
`What happens if I interrupt my code? Check here`

**Comment by jorgeorpinel** [comment]
Cool. I'll leave it up to you @pared. I personally don't think a change is needed in that case, but it wouldn't hurt either.

**Comment by jorgeorpinel** [comment]
Not sure this is closed actually, would you mind re-assessing @dberenbaum ?

**Comment by dberenbaum** [comment]
I think #2417 is good, at least for now.
