### ISSUE TITLE
remote add: review Azure section

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2406]
From https://github.com/iterative/dvc.org/pull/2390#issuecomment-824519403:

> I'm not sure we communicate properly defaults, available options, etc.

Context: after updating and rewriting the Azure section in https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type we noticed that this remote is pretty complicated, and it's not clear what the recommended/assumed auth method should be, and which others if any to include in `remote add`.

See also #1859.

**Comment by jorgeorpinel** [comment]
Please clarify if I didn't fully get the idea, @shcheklein. Thanks

**Comment by jorgeorpinel** [comment]
p.s. I tried to throw this into #2407 but other than minimal copy edits I'm not seeing a problem in `remote add` now, given that it has a clear indication that there are more auth methods to consult in `remote modify`. And since we need to move all this content elsewhere anyway per #1859 I'd vote to close this one 🙂 WDYT @shcheklein ?

**Comment by shcheklein** [comment]
@jorgeorpinel okay, to clarify. I think my point is that we need something in `dvc remote add` as we have for S3. We don't show any modify commands at all. We just refer readers to `dvc remote modify` like this:

> By default, DVC expects your AWS CLI is already configured. DVC will be using default AWS credentials file to access S3. To override some of these parameters, use the parameters described in dvc remote modify.

same applies here I think?

The only other remote that goes into too many details (+does `dvc remote modify` a lot) is `Aliyun OSS` which is far from being the most popular.

**Comment by jorgeorpinel** [comment]
OK I see. From a recent conversation with @isidentical I thought the expected auth method was specifying an Azure connection string. But OK, that's easier, updated in 9a427465 (please check #2407).
