### ISSUE TITLE
`master` builds are failing

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2411]
As noted in https://github.com/iterative/dvc.org/pull/2377#issuecomment-824484545 (and probably earlier), the `build` script stopped working at some point ([first failed build](https://dashboard.heroku.com/apps/dvc-org-mm-checkpoints--lv46zp/activity/builds/bbf0a0dd-36cc-4752-8694-48bc68111c21)) in `master`. This means we can't deploy anything to production. The error is

```
       [4/4] Building fresh packages...
       error /tmp/build_7f109913/node_modules/sharp: Command failed.
       Exit code: 1
       Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
```

CI tests are all passing though. This only happens with `build` and on ~~prod~~ our cloud, it seems.

**Comment by jorgeorpinel** [comment]
Cc @rogermparent

**Comment by jorgeorpinel** [comment]
> stopped working at some point (first failed build

Actually that's on another branch (not merged yet). The first time it failed on `master` was [this one](https://dashboard.heroku.com/apps/dvc-org/activity/builds/6560e6e1-3a0a-4a89-94b2-21d4a1f193ea), in case it helps (same error though).

> This means we can't deploy anything to production

Or PR review apps

**Comment by shcheklein** [comment]
@julieg18 could you please give this one a try? it's a p0 for us.

**Comment by julieg18** [comment]
It looks like the error may have something to do with the `sharp` module. Do you think upgrading packages that have the `sharp` module to a higher dependency could fix the build?

**Comment by jorgeorpinel** [comment]
@julieg18 feel free to try it out and open a PR with a branch directly on this repo (not from a fork) so that an automatic deployment is triggered on our cloud. If the build works there it should work on prod.

**Comment by shcheklein** [comment]
@julieg18 feel free to do any experiments, package updates/downgrades, etc- don't worry about breaking something.

**Comment by julieg18** [comment]
Looks like I don't have permission to push to the repo 🤔

**Comment by shcheklein** [comment]
@julieg18 you have it now!

**Comment by iesahin** [comment]
FYI, `sharp` module is why I had to give up installing the site on mac M1. @rogermparent has said that some customization was applied to image generation code and we can't directly upgrade to higher versions. @julieg18 

@shcheklein @jorgeorpinel

**Comment by julieg18** [comment]
> FYI, `sharp` module is why I had to give up installing the site on mac M1. @rogermparent has said that some customization was applied to image generation code and we can't directly upgrade to higher versions. @julieg18 

That makes sense. Since I did get some errors on my pull request🤔

**Comment by rogermparent** [comment]
I pinned all our gatsby `sharp`-related plugins to an old version (quite old, now!) because our weird hand-rolled S3 caching mechanism depends on the simple `public`-dependent image caching that the gatsby image plugins used before the Jobs API V2 was introduced. For some reason, after that update the cache would always be invalid no matter what files we preserve.

The hand-rolled S3 cache script is in [`scripts/deploy-with-s3.js`](https://github.com/iterative/dvc.org/blob/36984599c95d1c969476f35a0d98e0dcb5c93dde/scripts/deploy-with-s3.js), which is what is used to invoke the site build in the `heroku-postbuild` npm script in `package.json`

**Comment by iesahin** [comment]
From the looks of the script and what you tell here, a major upgrade may take too much time. 

BTW, my local Ubuntu 20.04 installation also builds fine. ✅ 

@rogermparent

**Comment by julieg18** [comment]
@rogermparent, so if I'm understanding correctly, upgrading the `sharp` package stops the `master` builds from failing, but will most likely break the caching? And instead of just upgrading the `sharp` package, we could upgrade Gatsby from 2 to 3?

**Comment by rogermparent** [comment]
> @rogermparent, so if I'm understanding correctly, upgrading the `sharp` package stops the `master` builds from failing, but will most likely break the caching? And instead of just upgrading the `sharp` package, we could upgrade Gatsby from 2 to 3?

If you can get away with just upgrading `sharp`, our current packages still accept it, and if fixes things, that's a fine solution. However, if it involves upgrading `gatsby-plugin*sharp` it'll probably break caching.

**Comment by julieg18** [comment]
The `gatsby-*-sharp` package did use the `sharp` package so I did upgrade that one when I was trying to fix the `build`. But since that probably breaks caching, looks like we'll need to try something else.

**Comment by rogermparent** [comment]
> The `gatsby-*-sharp` package did use the `sharp` package so I did upgrade that one when I was trying to fix the `build`. But since that probably breaks caching, looks like we'll need to try something else.

We don't necessarily have to ditch it just yet, if you've fixed builds we can at least get an emergency patch in that makes things work while we fix caching.

**Comment by rogermparent** [comment]
> Good to know, I haven't tried a local build yet but I suspect it'll work there too.

I was correct, builds succeed on my Linux box.
