### ISSUE TITLE
`exp run`: internal data committing performance implications

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2418]
Per https://github.com/iterative/dvc/pull/5859 (released in [2.1.0](https://github.com/iterative/dvc/releases/tag/2.1.0))

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/2418#issuecomment-854183969

> Data dependencies are now dvc commited internally when stashing an experiment so that any modifications to that data dep are preserved in both workspace and tempdir runs (previously the changes were dropped entirely by the exp run dvc checkout step).

Implications to consider documenting:
- [x] Mention the `git stash` "trick" somewhere
- [ ] Large changes to data dependencies in the workspace may slow down experiment queueing
- ~~Even if the run fails after this step, the new cached entries will remain, and metafiles will point to them (seen as Git changes)~~ Also true of `repro` which is already linked from `exp run` ref.

**Comment by jorgeorpinel** [comment]
Cc @pmrowla (forgot to tag you originally it seems). Thanks

**Comment by jorgeorpinel** [comment]
Cc @dberenbaum do you think we should document any of this? Thanks

**Comment by dberenbaum** [comment]
It would be nice to document how data dependencies are handled, but only if we have a document that goes in-depth about the experiments implementation. I don't see a good place for it today. Since it is now pretty consistent with `dvc repro` behavior, I don't think it's that important to document it unless/until we see that it becomes an issue.

**Comment by jorgeorpinel** [comment]
I guess the title of this issue was misleading. I improved it now. This is in general about the whole staging->committing mechanism for tmp/queued experiments. It's not documented at all. The change in question (https://github.com/iterative/dvc/pull/5859) just reminded me of the feature? as a whole.

I think it should be added to https://dvc.org/doc/command-reference/exp/run#queueing-and-parallel-execution and maybe as an example too.

**Comment by dberenbaum** [comment]
It seems like this comes down to the discussion of how much we want to expose the implementation details. With the changes in #5859, it seems like the behavior is consistent across temp and workspace runs with the exception of gitignored files (is that a separate issue?), and it's also consistent with `dvc repro`.

We also already have `How are experiments queued` there, so I'm not sure how much further we need to go. Are there particular concerns that you worry users might have?

I'm not against including it, but it doesn't seem high priority to me since I haven't heard much related feedback from users on it.

**Comment by jorgeorpinel** [comment]
Maybe I'm confused about https://github.com/iterative/dvc/pull/5859 due to the language there "commited internally when **stashing** an experiment". Only tmp/queued exps are stashed internally right @pmrowla ? The original issue (https://github.com/iterative/dvc/issues/5593 point 2) had nothing to do with tmp/queued exps actually.

**Comment by jorgeorpinel** [comment]
p.s. so yeah if https://github.com/iterative/dvc/pull/5859 just addresses iterative/dvc#5593 point 2 then the only thing to doc for that would be "that large changes to data dependencies in the workspace may slow down experiment queueing" per https://github.com/iterative/dvc/pull/5859#issuecomment-824952003 — which is why this issue exists in the first place 😬 

The staging->stashing mechanics are a separate question, sorry for the confusion!

**Comment by jorgeorpinel** [comment]
p.p.s. on

> the whole staging->committing mechanism for tmp/queued experiments. It's not documented at all.
> with the exception of gitignored files (is that a separate issue?)

Actually it was documented already by https://github.com/iterative/dvc.org/pull/2398 😅

**Comment by jorgeorpinel** [comment]
> large changes to data dependencies in the workspace may slow down experiment queueing

Update: the deeper info on queued exps in now in https://dvc.org/doc/user-guide/experiment-management/running-experiments#the-experiments-queue. Do we still want to add this note? In hindsight I feel like it should be intuitive (as long as we're explaining how experiments work correctly). WDYT @dberenbaum, close this?

**Comment by jorgeorpinel** [comment]
>  feel like it should be intuitive

Wait why does this apply especially to queued exps and not all exps again? This isn't clear.

**Comment by pmrowla** [comment]
This affects all experiments, I'm not sure where the queue specific idea came from. One-off workspace or `--temp` runs are still queued internally, but they just get popped from the queue and run immediately afterwards.

**Comment by dberenbaum** [comment]
Right, it's not about the queue, it's about clarifying that any "dirty" data in the workspace will be cached at the start of `exp run`. I think this is probably worth mentioning somewhere if it's not already.

**Comment by jorgeorpinel** [comment]
> It's about clarifying that any "dirty" data in the workspace will be (committed and) cached at the start of exp run. I think this is probably worth mentioning somewhere if it's not already.

**Comment by jorgeorpinel** [comment]
> It's about clarifying that any "dirty" data in the workspace will be (committed and) cached at the start of exp run. I think this is probably worth mentioning somewhere if it's not already.

The most obvious place is in https://dvc.org/doc/command-reference/exp/run since it currently does not go into execution details, deferring to the `repro` ref. for that. Do you guys want to take care of that update since it's the cmd ref?

If I find other places to mention this I'll make a quick PR.

**Comment by jorgeorpinel** [comment]
UPDATE: Never mind, I added the note myself in #3271 since it's the same as the change I was doing for the guide anyway. Will just need your review and perhaps discussing other related questions there... Thanks

**Comment by dberenbaum** [comment]
> * Mention the `git stash` "trick" somewhere

This seems like a separate issue. No strong opinion.

> * large changes to data dependencies in the workspace may slow down experiment queueing

True, but why is it slower than `dvc repro`? Both commands save the dependencies to the cache. AFAIK, the additional step is having to checkout that data into a temp directory. Can't remember if there is a checkout step in workspace runs.
 
> * Even if the run fails after this step, the new cached entries will remain, and metafiles will point to them (seen as Git changes)

This is also true for `repro`.

**Comment by jorgeorpinel** [comment]
> Mention the git stash "trick" somewhere

Oh that's already somewhere in there. I think in a hidden section.

> is it slower than dvc repro? Both commands save the dependencies to the cache

Wait so `repro` behaves the same? I thought this was `exp run`-specific per https://github.com/iterative/dvc/pull/5859 ... Back to confusion state 😖 

> the additional step is having to checkout that data into a temp directory. Can't remember if there is a checkout step in workspace runs.

Let's discuss in #3271?
