### ISSUE TITLE
Postmortem: failing `master` builds

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2427]
This ticket contains a postmortem about an issue we were having with creating `build`s on the cloud a couple days ago.
## High Level Summary

Our `master` `build`s started failing last week, starting with [this one](https://dashboard.heroku.com/apps/dvc-org/activity/builds/6560e6e1-3a0a-4a89-94b2-21d4a1f193ea). We noticed once we attempted to deploy a branch on a pull request.

@rogermparent was able to realize the issue was with the specified node version in our `package.json` and once his [pull request](https://github.com/iterative/dvc.org/pull/2420) for updating `package.json` was merged, `build`s were once again successful!

## Timeline

* 2021-4-20 @jorgeorpinel `build` failed while he was working on pull request #2377 
* 2021-4-20 @jorgeorpinel merged his pull request to master to see if master `build` would pass, but `build` still failed 
* 2021-4-22 @jorgeorpinel opened an issue(#2011)
* 2021-4-24 I noticed that the `build` was unable to compile the `sharp` package and worked on a pull request(#2416) for upgrading the `sharp` package(this pull request would have most likely caused cache errors and caused some TS errors as well)
* 2021-4-26 @rogermparent found out why `sharp` was unable to be compiled and opened a pull request for fixing the issue(#2047)
* 2021-4-26 Pull request #2047 was merged to main, and `build` were now passing and code was deploying correctly

Perf indicators:
* Time to notice: About a day
* Fix Developed After: 6 days
* Resolved After: 6 days

## Impact
* We were unable to make any updates to DVC.org
* We were unable to deploy any pull request code for testing

## Root cause analysis
@rogermparent was able to figure out the issue:
* Node released version 16, and our package.json `engines.node` value was `>=12.0.0`, telling Heroku to use the latest node version when it ran `build`. 
* Some change in Node 16 made it unable to compile our current version of the `sharp` package([sharp](https://www.npmjs.com/package/sharp) is an image processing library), causing our `build` to fail when Heroku attempted to run the command.
* Roger updated the package.json `engines.node` to equal `"<=15.x"`, telling Heroku to use a node version below `15`
* Once the `package.json` was updated, `build`s were no longer failing
* This exact issue will not happen again unless we somehow use `>` in our version specifier again.

## Prevention and next steps
* Maybe we could come up with some sort of test that checked if `build` was compiling correctly once in a while.
* Maybe we could setup some way to be notified when something like our node version is updated. 🤔

**Comment by julieg18** [comment]
This is my first postmortem, any comments/improvements are appreciated! 😄

**Comment by rogermparent** [comment]
Looks good! We should probably mention that the change to `engines: {node: "<=15.x"}` means this exact issue isn't going to happen again unless use `>` in a version specifier again.

We may want to check that no other projects use `>=` for their Node version resolution.

While the fix I made patches up the immediate issue, it does bring to light that we pinned `sharp` and everything downstream of it (including Gatsby) a _while_ ago so our packages are starting to get quite old. I think a proper fix that lets us get on Node 16+ involves:

1. Upgrading `sharp` and `gatsby` to the latest version.
2. Diagnose and resolve any issues 1 causes with our custom caching mechanism.

This could be tracked under a ticket called "Upgrade to Node 16" or "Update to Gatsby 3". Effectively, both names are for the same problem: unpinning our held-back image processing and solving our cache issues that come from them.

**Comment by shcheklein** [comment]
@julieg18 looks great! thanks. I would include you in the story - you spent some time researching and made a good attempt to  upgrade dependencies. This is an important piece of this puzzle.

**Comment by jorgeorpinel** [comment]
Thanks for the info!

> 2021-4-22 @jorgeorpinel merged his pull request to master to see if master build would pass

I think it must have started earlier because the first "Automatic deployment of dvc-org failed." from Heroku is from April 21 ([this build](https://dashboard.heroku.com/apps/dvc-org/activity/builds/6560e6e1-3a0a-4a89-94b2-21d4a1f193ea)).

Anyway, TBH I don't think we noticed the builds were failing at that point, since all our CI checks were green.

> come up with some sort of test that checked if build was compiling correctly once in a while.

We do have those emails from Heroku. We can also use papertrailapp.com (or some other add-on) for custom alerts.

**Comment by shcheklein** [comment]
A few points:

- We do have a channel for this #websites-ops, it was clear that build is failing. We need to improve it - de-noise, filter, etc (if needed) and follow.
- We do get those emails from Heroku. - Yep

> We can also use papertrailapp.com

my take - we have quite enough, pepertrail is also set, but it's mostly about collecting logs.

**Comment by julieg18** [comment]
> This could be tracked under a ticket called "Upgrade to Node 16" or "Update to Gatsby 3". Effectively, both names are for the same problem: unpinning our held-back image processing and solving our cache issues that come from them.

@rogermparent, I can create a ticket for upgrading to v3. Iterative.ai is at v3, but CML.org isn't. Do we need to consider upgrading CML.org as well?
>We may want to check that no other projects use > or >= for their Node version resolution.

Iterative.ai and Cml.org don't have a `engines` in their package.json. Which I believe means they use the latest version by default. Should we consider adding engines to either of them, so they don't risk breaking on an upgraded version of `node`?

**Comment by rogermparent** [comment]
> Iterative.ai and Cml.org don't have a `engines` in their package.json. Which I believe means they use the latest version by default. Should we consider adding engines to either of them, so they don't risk breaking on an upgraded version of `node`?

For Heroku specifically, the default is a specific stable version , which is currently v14. It could be good to explicitly define the latest node we can use and then pin to that version (i.e. try 16, if it fails, do 15) and then that'd future proof us in the long term while being able to take advantage of the latest node features when we want to.

**Comment by julieg18** [comment]
> For Heroku specifically, the default Node is a moving target that's relatively stable, currently v14. It could be good to explicitly define the latest node we can use and then pin to that version (i.e. try 16, if it fails, do 15) and then that'd future proof us in the long term while being able to take advantage of the latest node features when we want to.

So if I'm understanding correctly, we should try to set are engines to something like `<=16.x`? `<=15.x` if it fails?

**Comment by rogermparent** [comment]
> So if I'm understanding correctly, we should try to set are engines to something like `<=16.x`? `<=15.x` if it fails?

It would probably be best to narrow it down with `16.x`/`15.x` when we can, `dvc.org` is a unique case because CircleCI uses Node 12 still and will break without `<=` - that may be easily fixable, but I haven't touched CircleCI much.

**Comment by julieg18** [comment]
So it would look like: `engines: { node: "16.x" }`?

**Comment by rogermparent** [comment]
> So it would look like: `engines: { node: "16.x" }`?

Yep! That's how it looks in the [Heroku docs](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version)!

**Comment by shcheklein** [comment]
Closing, we are creating actions in the #2579
