### ISSUE TITLE
Footer not staying at bottom of page in 404 page

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2430]
There is a gap between the footer and the bottom of the page, starting at `610px` screen width:

![image](https://user-images.githubusercontent.com/43496356/116540588-f77f7280-a8af-11eb-9c3f-9363bc7ee35a.png)

**Comment by jellebouwman** [comment]
I noticed this behaviour on the [enterprise page](https://dvc.org/enterprise) too - seems like the `<body>` tag does not fill up the entire page.

<img width="1281" alt="Screenshot 2021-05-31 at 16 35 47" src="https://user-images.githubusercontent.com/32744870/120210896-97724800-c230-11eb-90c1-0bd70b2d3bf8.png">

**Comment by jorgeorpinel** [comment]
```csv
footer {
    position: absolute;
    bottom: 0;
}
```
does the trick but maybe it's not so easy for some reason?

**Comment by julieg18** [comment]
> does the trick but maybe it's not so easy for some reason?

Would work for fixing the 404 page, but would break the footer in other places. But, I think there is way to fix this by adding some CSS to a page wrapper 🤔
