### ISSUE TITLE
guide: all the ways to use checkpoints

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2432]
As shown in https://github.com/iterative/dvc-checkpoints-mnist under "Switch between scenarios," there are multiple different ways to integrate checkpoints into a project:

* Using dvclive
* Using make_checkpoint
* Using a manually created signal file
* Only including `checkpoints: true` in `dvc.yaml` without any in-code checkpoints (but this seems like an unlikely scenario that might be unnecessary or useful just to show the basics of how checkpoints work - see https://github.com/iterative/dvc.org/issues/2292)

There is already a link in https://dvc.org/doc/user-guide/experiment-management to that example repo. Is this sufficient for now? Should the user guide provide more explanation rather than leave it in the readme of the example repo?

**Comment by jorgeorpinel** [comment]
> There is already a link in https://dvc.org/doc/user-guide/experiment-management to that example repo. Is this sufficient for now?

And soon #2373

I think it's sufficient for now. But ideally we should have an Experiments guide sub section with better separated pages (each shorter but covering more things as a whole), IMO.

**Comment by jorgeorpinel** [comment]
p.s. basically #2269 haha

**Comment by jorgeorpinel** [comment]
Should we merge this issue with https://github.com/iterative/dvc.org/issues/2769?

**Comment by dberenbaum** [comment]
Need to improve checkpoints in core before spending time improving docs.

**Comment by jorgeorpinel** [comment]
Thanks for the grooming @dberenbaum ! 🐩
