### ISSUE TITLE
DVC README

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2433]
Review the README in https://github.com/iterative/dvc since it is the first thing some users see, and it includes sections like "Comparison to related technologies" that may need to be updated and/or integrated into dvc.org.

UPDATE: See some ideas in #2443

**Comment by jorgeorpinel** [comment]
Should we merge or clearly separate with #2443?

**Comment by dberenbaum** [comment]
I vote to keep separate since #2443 is more general about the structure of a readme and applies across products. This one is specifically a need to review the dvc readme. I view #2443 as more of an epic/discussion ticket and this one as a narrower one under that, but as long as we end up reviewing the dvc readme, I'm open to however you want to structure the tickets.

**Comment by dberenbaum** [comment]
I see you and @casperdcl already came to the same conclusion in #2443! Yay, more agreement!

**Comment by jorgeorpinel** [comment]
Closing in favor of #2443
