### ISSUE TITLE
Setup Universal Header/Footers

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2440]
* [Draft Design Mockup](https://www.figma.com/file/FOc5Lm4yy41tSu3GXpqEVN/Websites?node-id=0%3A1)
* Once design is completed, we need to update our header/footer to match design

**Comment by arcticbear** [comment]
Design update:
+ Added states with opened header's dropdown menus
+ Updated social links order
+ Replaced the company label in the header to the tooltip / hint (works for desktop and tablet, for mobile we can show just a fixed label near the logo)

https://www.figma.com/file/FOc5Lm4yy41tSu3GXpqEVN/Websites?node-id=413%3A1

**Comment by arcticbear** [comment]
Design update (mockups available on the same link):
+ Replaced the company label in the header back to the fixed one
