### ISSUE TITLE
ref: which remotes can be configured via environment variables?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2445]
> From https://github.com/iterative/dvc.org/pull/2415#discussion_r626199728

We only mention env vars for S3, Azure, and OSS (in https://dvc.org/doc/command-reference/remote/modify).

- Are those the only ones that support env var-based configuration?
- What is the full list of env vars supported in each one? (we have links for S3 and Azure, and a list of 3 specific ones for OSS)

**Comment by jorgeorpinel** [comment]
Hi @efiop, would you know this or where to look/ who to ask? Thanks

**Comment by efiop** [comment]
@jorgeorpinel Pretty much needs a deep dive into corresponding libraries to see what they accept beyond what dvc passes directly. No simple answer here :slightly_frowning_face:
