### ISSUE TITLE
install: missing `[webdav]` and `[hdfs]` from `pip` instructions

### ISSUE THREAD

**Issue by natephysics** [iterative/dvc.org#2449]
In the following documentation, there's a missing option for pip install dvc[webdav]. 

https://github.com/iterative/dvc.org/blob/master/content/docs/install/linux.md

https://github.com/iterative/dvc.org/blob/master/content/docs/install/windows.md

**Comment by shcheklein** [comment]
Yes, we have some extras that are not documented: 

https://github.com/iterative/dvc/blob/master/setup.py#L131

**Comment by jorgeorpinel** [comment]
Does this also apply to `conda`? Cc @efiop thanks

**Comment by efiop** [comment]
@jorgeorpinel webdav is not included into conda at all, as there is no corresponding dependency package there. We'll likely just wait for webdav4 and then introduce a conda package for it too.
