### ISSUE TITLE
docs: better image processing (similar to blog)

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#2469]
**This issue has been created for unresolved PR comments on #2455 This issue is intended to be closed before the public release.**

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/2455#discussion_r630528533_:

I think this is about retina-like display support. Unlike the blog engine, DVC.org doesn't process images properly. And effective you have to put extra white-background and do 2xWidth to them not look blurry and at the same moment be smaller then the viewport, or even of the same size but not blurry. E.g. https://dvc.org/doc/use-cases/versioning-data-and-model-files here images are wrong (not enough width to properly render them on the retina-like displays).

> In blog we have a special logic and additional Markdown support for this (check the contributors guide).

Let's get the image processing logic on docs to be on par with the blog's one cc @julieg18 @rogermparent

**Comment by jorgeorpinel** [comment]
Extracted the img resizing part to #2468 (I think it's needed anyway)

**Comment by julieg18** [comment]
@rogermparent, is there a particular reason why the docs don't have image processing?

**Comment by rogermparent** [comment]
> @rogermparent, is there a particular reason why the docs don't have image processing?

Not that I know of, as a lot of this engine was implemented before I got here. My guess is that it's due to how this site originated in Next.js, which doesn't have an equivalent to `gatsby-image` (or at least not at the time).
