### ISSUE TITLE
start: improvements

### ISSUE THREAD

**Issue by flippedcoder** [iterative/dvc.org#2474]
- [x] Remove the Sharing experiments section from Get Started > Experiments

We should remove the [Sharing experiments section](https://dvc.org/doc/start/experiments#sharing-experiments) since it adds more complexity to the Get Started tutorial than there needs to be since users have to set up a Git remote as well as a DVC remote. We don't go over this at any other point in the tutorial.

If a user clones the get started repo, it works fine, but if they are following along there are some roadblocks they might run into with getting things set up. For example, I ran into a weird credentials issue with my Git remote and ended up working with @dberenbaum to do a crazy workaround.

Overall, it clouds up the purpose of this section which is running experiments.

- [x] Update the `git add` command for Get Started > Metrics, Parameters, and Plots

In the [Comparing iterations section](https://dvc.org/doc/start/metrics-parameters-plots#collecting-metrics), users can get empty Old and Change values when they run `dvc metrics diff` because the `dvc.lock` and `dvc.yaml` are missing from the `git add`.

We need to update the command to be `git add dvc.lock dvc.yaml scores.json prc.json roc.json`.

**Comment by dberenbaum** [comment]
@flippedcoder Do you mind separating these whenever you have a chance? We try to be pretty strict about keeping issues logically separate so that one part of an issue doesn't block the rest of the issue from being resolved.

**Comment by jorgeorpinel** [comment]
Checkboxes could also work, or be a good first step.

**Comment by jorgeorpinel** [comment]
May also be good to see if we can consolidate with #1943.

**Comment by jorgeorpinel** [comment]
We should also consolidate this one with https://github.com/iterative/dvc.org/issues/2496 cc @iesahin

**Comment by jorgeorpinel** [comment]
@iesahin if you could also double check which parts of this are still/most relevant and consolidate into https://github.com/iterative/dvc.org/issues/2496 that would be great.
