### ISSUE TITLE
swipe on mobile: feature or a bug?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2476]
Accidental touches on my phone were changing the pages (in dvc.org/doc). Is it something that we intended to support or was it accidental?

Without any animations/indications, I was not able to figure out what happened for a while. Maybe the sensitivity could be reduced as well.

**Comment by julieg18** [comment]
I think it's a feature looking at this [code](https://github.com/iterative/dvc.org/blob/master/src/components/Documentation/Markdown/index.tsx#L156) in the Documentation components.  Looking at the docs on my phone, it does seem like the sensitivity could be reduced. Some kind of indication on what is happening may lower confusion as well 🤔

**Comment by jorgeorpinel** [comment]
Interesting! It's a cool feature since the nav isn't always visible in mobile although then again not something very common so Idk if people will even think to use it once we reduce the sensitivity. But definitely shouldn't go off accidentally when you're trying to scroll (that's the bug part).
