### ISSUE TITLE
start: A new GS:Experiments document with `get-started-experiments`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2479]
Katacoda [GS:Experiments scenario](https://katacoda.com/dvc/courses/get-started/experiments) employs [`dvc-get-started`](https://github.com/iterative/dvc-get-started) to introduce experiment features already. The scenario uses [`dvcorg/doc-katacoda:experiments`](https://hub.docker.com/repository/docker/dvcorg/doc-katacoda) container. 

Let's upgrade [GS:Experiments documentation](https://dvc.org/doc/start/experiments) to have a parallel content with the scenario. 

This will also allow to run [`markdown-code-runner`](https://github.com/iterative/markdown-code-runner) on the page to get _automated tests_ for the commands in the documentation content, for the first time. 

Related #2474 
Related iterative/example-repos-dev#38
Related iterative/example-repos-dev#44

@flippedcoder @jorgeorpinel @shcheklein @dberenbaum

**Comment by jorgeorpinel** [comment]
> I will cancel #2497

But there's lots of feedback there. Is it possible to preserve it? Thanks

**Comment by iesahin** [comment]
> > I will cancel #2497
> 
> But there's lots of feedback there. Is it possible to preserve it? Thanks

I'll keep them for the new document, they are valuable for me. Thanks.
