### ISSUE TITLE
ref: azure: fix cloud config docs

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2485]
Specifically `dvc remote modify`:

- [x] Link `all env var` does not cover _all_ vars (remove for now)
- [x] We need to list actually available vars - e.g. I see `AZURE_CONFIG_DIR` - do we mention it?
- [x] AZURE_STORAGE_CONNECTION_STRING, AZURE_STORAGE_CONTAINER_NAME - what else?
- [x] Small style bug with code block
- [x] dvc end: check `unable to connect to account for Must provide either a connection_string or account_name with credentials!!` message - it has a few errors in it.

cc @isidentical

**Comment by isidentical** [comment]
pre requisite: iterative/dvc/pull/5833

**Comment by isidentical** [comment]
>  dvc end: check unable to connect to account for Must provide either a connection_string or account_name with credentials!! message - it has a few errors in it.

This message have been replaced with
https://github.com/iterative/dvc/blob/fd76e0991f6dd47e554b874c2efb8c280dee96c0/dvc/fs/azure.py#L93-L99

**Comment by jorgeorpinel** [comment]
Thanks for the info @isidentical, does that need a docs update?

Or is there anything else left in this issue? I see one pending check box in the description.

Thanks

**Comment by isidentical** [comment]
@jorgeorpinel Pending checkbox should be resolved by this: https://github.com/iterative/dvc.org/pull/2703

**Comment by jorgeorpinel** [comment]
Just noticed that, will review. Please link that PR so it closes this issue. Thanks
