### ISSUE TITLE
dvc dag: tag is not properly closed

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc.org#2492]
From the [first paragraph](https://dvc.org/doc/command-reference/dag#directed-acyclic-graph)
```
The connections between stages are formed by the output<s/abbr> of one turning into the 
```

**Comment by shcheklein** [comment]
thanks @isidentical ! (there is an Edit on Github button on each page- please feel free to do quick fixes like this :) )

**Comment by jorgeorpinel** [comment]
I wonder if the build process gives a warning of something about these that we can catch during CI. Ideas @rogermparent ? 🙂 Thanks
