### ISSUE TITLE
contrib: update issue templates

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc.org#2503]
Few moments I noticed being a newcomer. I guess some of this could be improved:
1. Right now templates for issues are not different in anything important. It confused me a bit when I tried to create an issue for the first time.
2. It would be great to have few words there that will help to frame the initial message and encourage to start the discussion. 
3. It is not clear how to write prefix for the issue (`start:`, `ref:`, `docs:`, `guide:`, etc). We could add a hint on that to issue template.

https://github.com/iterative/dvc.org/issues/new/choose

**Comment by jorgeorpinel** [comment]
Agree, we should probably remove the issue types? Just have a general template explaining about the prefixes.

But TBH not a lot of users come open issues, they open PRs directly most of the times. Sometimes tickets get transferred here from the core `dvc` repo. Other than that it's us creating these.

**Comment by aguschin** [comment]
@jorgeorpinel, I just stumbled upon the wiki with your articles about the prefixes and PRs :) https://github.com/iterative/dvc.org/wiki
The last changes were made in Jan 2020. Are they still relevant?

**Comment by jorgeorpinel** [comment]
😮 I forgot we had that ha! It's still relevant. I quickly updated the prefixes and labels one just now.

**Comment by jorgeorpinel** [comment]
Options:
- Remove templates if we don't need them (better than having empty ones)
- Keep them (even if empty) so it shows that we have an organized process?
- Keep empty(ish) + set some default labels i.e. `bug` and `feat-req`
- Keep a single template with a comment about checking Troubleshooting, Contrib guide, or other docs?

I incline to just remove them, as this should apply to all docs repos (soon to be many). WDYT @iterative/docs ?
