### ISSUE TITLE
Using svg in the banner (alert) not working

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#2540]
There was some issue when we used `img`. We were getting Cloudflare alert that the page was offline. It was not breaking all the time, but Ivan noticed it when he was trying to load the page. We replaced the svg img with 🚀 in this [PR](https://github.com/iterative/dvc.org/pull/2532/files) and the alerts went away (page stopped breaking). Any idea why that may have happened and how we can use images if needed?

_Originally posted by @tapadipti in https://github.com/iterative/dvc.org/pull/2510#discussion_r645511991_

**Comment by tapadipti** [comment]
The error was this:
![image](https://user-images.githubusercontent.com/32855442/121302716-ba2eeb80-c917-11eb-853c-362a991fa239.png)

I noticed that I'd missed the leading `/` in the image file path.
It was written as `img src="img/studio-icon.svg"` instead of `img src="/img/studio-icon.svg"`. Probably this was the cause. But not sure how it was working sometimes if this was the issue.

**Comment by tapadipti** [comment]
Hi @rogermparent Could you pls take a quick look at this and see if there could be any issue other than the `/` that I missed?

**Comment by rogermparent** [comment]
> It was written as `img src="img/studio-icon.svg"` instead of `img src="/img/studio-icon.svg"`. Probably this was the cause. But not sure how it was working sometimes if this was the issue.


That explains the issue pretty well, actually: omitting the leading / makes the page search for the image relative to the current page, such that the image would work on the root page but not in a page from any child directory.

**Comment by tapadipti** [comment]
Thanks @rogermparent . Will close this ticket after the next time we change the image in the banner.

**Comment by jorgeorpinel** [comment]
Hi @tapadipti has the banner been updated? Thanks

**Comment by tapadipti** [comment]
Hi @jorgeorpinel No, we've not had to change the image yet.

**Comment by jorgeorpinel** [comment]
HI. Is this still relevant @tapadipti ? I think there's a new way to upload images (cc @yathomasi) but it may only apply to blog posts.

**Comment by rogermparent** [comment]
It does currently only apply to blog posts. It may expand in the future, but I think something like an alert SVG is last on the list for being DVC-ified.

**Comment by jorgeorpinel** [comment]
> we've not had to change the image yet

Seems to me this ticket is no longer needed. Please reopen if the issue resurfaces. Thanks
