### ISSUE TITLE
Next Header Iteration

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2543]
- [ ] Incorporate "Other Tools" popup links into mobile hamburger menu
- [ ] Navbar currently looks pretty heavy with the font weight and multiple items

Comments and discussions about these tasks can be found in pull request #2514

**Comment by arcticbear** [comment]
Thank you for the checklist @julieg18  

We can try the same elements and grid for `Other tools` as for `Community and `Support`. I think the best place for it at the bottom just before the `Get Started` button. Prepared two versions: with colored and white icons. Personally, I prefer the white ones, they consistent with other items and have good contrast with the background. 

As for text, let's try to decrease `font-size` to 16 and `font-weight` to 400 (not sure if that possible with the font we're using on the front-end?). 

You can find mockups for the hamburger menu in the Navbar section on the Components page in [Figma](https://www.figma.com/file/FOc5Lm4yy41tSu3GXpqEVN/Websites?node-id=239%3A233). 

![image](https://user-images.githubusercontent.com/1275731/121446213-b47ae980-c99b-11eb-8423-264a8fa0bfee.png)

**Comment by julieg18** [comment]
Looks our dvc.org font has a `400` weight option!
