### ISSUE TITLE
`exp run`: checkpoints run every time without dep changes

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc.org#2545]
UPDATE: Skip to https://github.com/iterative/dvc.org/issues/2545#issuecomment-857212104

---

Hi!

Im running into an issue that probably is my mistake so I apologise in advance 🙏 
To follow up you just need to fork https://github.com/iterative/dvc-checkpoints-mnist

## Description

Every time I run ```dvc exp run``` I have 10 epochs even I have not changed any dependancy.

### Reproduce

```sh
git clone https://github.com/iterative/dvc-checkpoints-mnist
cd dvc-checkpoints-mnist
dvc init -f
dvc remote add -d myremote...
dvc exp run

git add dvc.yaml dvc.lock dvclive.json train.py
git commit -m '10 epochs'

dvc push
git push
```

Now if I repeat ```exp run``` without any change It should not run like repro, right? However in my case every single time it runs another 10 epochs.

<details><summary>LOG</summary>
<p>

```sh
Running stage 'train':                                                                                                                                 
> python3 train.py
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration 'd64afd6'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '8f532c0'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '9f5b61b'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '1ba2514'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration 'd70a50f'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '450cab5'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration 'a599f5e'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '0043e6c'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '18fda60'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html
Updating lock file 'dvc.lock'                                                                                                                          
Checkpoint experiment iteration '01017c1'.

file:///iterative/dvc-checkpoints-mnist/dvclive.html

file:///iterative/dvc-checkpoints-mnist/dvclive.html
                                                                                                                                                       
To track the changes with git, run:

        git add train.py dvclive.json dvc.lock dvc.yaml
                                                                      
Reproduced experiment(s): exp-b434e
Experiment results have been applied to your workspace.

To promote an experiment to a Git branch run:

        dvc exp branch <exp>
```
</p>
</details>

### Expected

If I don't change any dependency exp run like repro should not run?

### Environment information

```console
DVC version: 2.1.0 (deb)
---------------------------------
Platform: Python 3.8.9 on Linux-4.19.76-linuxkit-x86_64-with-glibc2.7
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: fuse.grpcfuse on grpcfuse
Caches: local
Remotes: s3
Workspace directory: fuse.grpcfuse on grpcfuse
Repo: dvc, git
```

### Extra 

As I curiosity if I do not git commit the list grows everytime.

<details><summary>dvc exp show</summary>
<p>

```
━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━┓
┃ Experiment              ┃ Created  ┃ step ┃ acc    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━━┩
│ workspace               │ -        │ 29   │ 0.9823 │
│ live                    │ 02:18 PM │ 19   │ 0.9831 │
│ │ ╓ 8ce5a03 [exp-fa8ae] │ 02:25 PM │ 29   │ 0.9823 │
│ │ ╟ 75cde7c             │ 02:25 PM │ 28   │ 0.9849 │
│ │ ╟ 8085755             │ 02:24 PM │ 27   │ 0.9857 │
│ │ ╟ 6e4c1c7             │ 02:24 PM │ 26   │ 0.9819 │
│ │ ╟ 23238d4             │ 02:24 PM │ 25   │ 0.9833 │
│ │ ╟ 9ec8896             │ 02:24 PM │ 24   │ 0.9831 │
│ │ ╟ 8ad79a9             │ 02:24 PM │ 23   │ 0.985  │
│ │ ╟ 137d8fd             │ 02:24 PM │ 22   │ 0.9844 │
│ │ ╟ 026104d             │ 02:23 PM │ 21   │ 0.9852 │
│ │ ╟ 3e4dca0             │ 02:23 PM │ 20   │ 0.984  │
│ │ ╟ 2ffa35b             │ 02:23 PM │ 19   │ 0.9827 │
│ │ ╟ d66a0a6             │ 02:22 PM │ 18   │ 0.9849 │
│ │ ╟ 916d1aa             │ 02:22 PM │ 17   │ 0.9857 │
│ │ ╟ d72cf34             │ 02:22 PM │ 16   │ 0.9845 │
│ │ ╟ f5dc213             │ 02:22 PM │ 15   │ 0.9831 │
│ │ ╟ 3d05cc0             │ 02:22 PM │ 14   │ 0.9831 │
│ │ ╟ 60d2f69             │ 02:22 PM │ 13   │ 0.9841 │
│ │ ╟ dab6a6f             │ 02:21 PM │ 12   │ 0.9846 │
│ │ ╟ 2413044             │ 02:21 PM │ 11   │ 0.9862 │
│ │ ╟ 822b2ee             │ 02:21 PM │ 10   │ 0.9839 │
│ │ ╟ 2361ca5             │ 02:20 PM │ 9    │ 0.9834 │
│ │ ╟ 45cb159             │ 02:20 PM │ 8    │ 0.9859 │
│ │ ╟ a68a635             │ 02:20 PM │ 7    │ 0.9864 │
│ │ ╟ 21a2fbd             │ 02:20 PM │ 6    │ 0.9834 │
│ │ ╟ ad05469             │ 02:19 PM │ 5    │ 0.9845 │
│ │ ╟ e0a0577             │ 02:19 PM │ 4    │ 0.985  │
│ │ ╟ 0ea9dc6             │ 02:19 PM │ 3    │ 0.9845 │
│ │ ╟ 35411f9             │ 02:19 PM │ 2    │ 0.9862 │
│ │ ╟ 8c6599b             │ 02:19 PM │ 1    │ 0.9848 │
│ ├─╨ 968da1a             │ 02:19 PM │ 0    │ 0.9855 │
└─────────────────────────┴──────────┴──────┴────────
```

</p>
</details>

**Comment by jorgeorpinel** [comment]
@shcheklein 

> Be explicit at the very beginning `With checkpoints, every time you do exp run, the experiment is resumed from the last checkpoint.`

Updating in https://github.com/iterative/dvc.org/pull/2549 (will close this)

> docs for exp run are long and a a bit too low level

Yeah. I guess we need more Experiment guides besides this [index](https://dvc.org/doc/user-guide/experiment-management) to move out details from the cmd ref... Created https://github.com/iterative/dvc.org/issues/2548 for now.

> Help for the command is misleading and low level also:
`Reproduce complete or partial experiment pipelines.`
It should be probably as simple as `Run or resume an experiment`

Cc @pmrowla want to open a dvc issue for that? (I may change it in the docs in #2549)

> note that this one example repo isn't used much in docs other than linked for a couple places...
@DavidGOrtega may I ask how did you find about the repo?

p.s. note that after #2549 the example repo in question will only be linked from DVCLive docs.

**Comment by jorgeorpinel** [comment]
BTW @DavidGOrtega, on the discussion:

> setup checkpoints to resume training if by any reason it fails

Like when MS Word crashes and you can get back to (most) of your work? :p important to note that it works in that situation too. It's mentioned in https://dvc.org/doc/command-reference/exp/run#checkpoints:

_All checkpoints registered at runtime will be preserved **even if the process gets interrupted** (e.g. with [Ctrl] C, **or by an error***)_ (I'm trying to clarify this doc anyway.)

Maybe there's a terminology misunderstanding. You seem to be expecting only "backup checkpoints" but we mean "progress checkpoints" (more general).

> > this "forever" nature of our checkpoint would end up in an endless training since there is no stoppage
> > fail and train from the last checkpoint covering your expected epochs and not more
> > must have scenario in CML
>
> The forever nature of it is intentional AFAIK
not sure whats the solution

Exactly. The experiment repo in question is hardcoded to run 10 epochs endlessly, but that depends on your code right? You can program it so there's a finite goal. DVC should support both scenarios (we just haven't documented the latter rel. https://github.com/iterative/dvc.org/issues/2432 cc @dberenbaum should we add a bullet?).

**Comment by dberenbaum** [comment]
> Exactly. The experiment repo in question is hardcoded to run 10 epochs endlessly, but that depends on your code right? You can program it so there's a finite goal. DVC should support both scenarios (we just haven't documented the latter rel. #2432 cc @dberenbaum should we add a bullet?)

Yes, I think we need maybe multiple examples for different scenarios, probably in the user guide. See https://github.com/iterative/dvc/discussions/6104#discussioncomment-818356.

**Comment by jorgeorpinel** [comment]
> Cc @pmrowla want to open a dvc issue for that?

https://github.com/iterative/dvc/issues/6186
