### ISSUE TITLE
CML: iterative/cml-action@v1 does not exist

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc.org#2550]
In the CML get started (https://dvc.org/doc/cml/start-github) we have GitHub action that is not working. It looks like a typo, since it's already fixed in the setup-cml repo https://github.com/iterative/setup-cml#usage to be `iterative/setup-cml@v1`

```
# from Github Action logs:
Error: Unable to resolve action `iterative/cml-action@v1`, repository not found
```

Quick search shows three occurrences of this in this repo: https://github.com/iterative/dvc.org/search?q=cml-action . I'm not sure this can be fixed by straightforward change in the scripts which are shown in this search, but if it can be, I can make PR.

![Screenshot 2021-06-10 at 11 47 43](https://user-images.githubusercontent.com/6797716/121494741-ac459d00-c9e1-11eb-97cb-9e82ab4cd9ac.png)

**Comment by casperdcl** [comment]
yup all of https://dvc.org/doc/cml/ is outdated... https://github.com/iterative/cml (readme) really is the only "current" source of documentation I'd trust at the moment

**Comment by shcheklein** [comment]
@casperdcl should we still try to do quick fixes? should we mention at the top that please read README - this info is out of date and is not reliable?

**Comment by casperdcl** [comment]
yes will do a quick pass.

**Comment by jorgeorpinel** [comment]
Side note: normally this issue would be under https://github.com/iterative/cml/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation right? (Prob no need to transfer at this point since the PR is almost merged.)

**Comment by casperdcl** [comment]
Don't think so... the (outdated) docs are in this repo so issues should be opened here I think.
