### ISSUE TITLE
Replace the CSV file with the Pickle file in the documentation

### ISSUE THREAD

**Issue by maggyero** [iterative/dvc.org#256]
https://dvc.org/doc/dvc-philosophy/how-it-works

At step 2, `cnn_train.py` is run and yields the `results.csv` file (???) instead of the `output.p` file mentioned at step 4.

**Comment by shcheklein** [comment]
Fixed by https://github.com/iterative/dvc.org/commit/9194fe303cc9a9a7dd31b133abd8b2afdb6501f6

Thanks @maggyero for the attention to these small details!
