### ISSUE TITLE
guide: Add checkpoints example that runs for a fixed number of epochs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2568]
Extracted from https://github.com/iterative/dvc/discussions/6104#discussioncomment-821276:

> @dberenbaum it sounds like we just need an example that runs forever when some param is set to 0 or None, and for the specified number of epochs if it is set to a positive integer. The workflow would be running it forever to start with, until the user figures out n. Then they just have to set n in params.yaml.
>
> The thing to note would be that for this example, n might not have to be tracked within a DVC stage's params (since it's not really a dependency that changes the stage, it's more like an env var that just controls how many epochs the user wants to generate at a time).

**Comment by casperdcl** [comment]
So essentially https://github.com/iterative/dvc-checkpoints-mnist/issues/13 but fixed num epochs rather than infinite. Good. Very much required for a basic CML long-running job timeout & resuming use case.

**Comment by jorgeorpinel** [comment]
Added to #2548

**Comment by dberenbaum** [comment]
This goes deeper than docs. Need to address checkpoints issues in core before this is worth revisiting.
