### ISSUE TITLE
guide: Params, Plots and Metrics

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2572]
The current documentation includes information on plots and metrics in the command reference for [`dvc plots`](https://dvc.org/doc/command-reference/plots) and [`dvc metrics`](https://dvc.org/doc/command-reference/metrics).  We need a ~~self-contained~~ UG page for all features regarding the plots and metrics. 

- [ ]  Extract details from https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages
- [ ] Extract some details from [params](https://dvc.org/doc/command-reference/params) and [metrics](https://dvc.org/doc/command-reference/metrics) ref. indices. 
  See also https://github.com/iterative/dvc.org/issues/4202
- Maybe clarify the concept of *params** as well.
- ~~Keep in mind conceptual and terminology decisions in https://github.com/iterative/dvc.org/issues/2956~~

### Related

- #2472 contains a page that describes offline usage of Vega libraries
- #2402 is the issue around offline usage
- #2216 contains some information about using plots/metrics without pipelines
- #1442 is terminology issue around plots and metrics
- #1755 asks for clarification where to use DVC or Git to track the plots and metrics
- #1909 is about the capability of `metrics` and `plots` to work with any parsable file
- #1175 is also a terminology issue
- #3818
- #2644

**Comment by daavoo** [comment]
Related?: https://github.com/iterative/dvc.org/issues/2644

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc.org/issues/2815

> We briefly cover those 3 types of files on the [`Project Structure -> Pipeline Files -> Stages` section](https://dvc.org/doc/user-guide/project-structure/pipelines-files#stages). 
However, it feels like the current info in each command reference could be moved to the user guide, potentially extending it.

**Comment by jorgeorpinel** [comment]
> Explain params metafiles
> metrics and plots metafiles

Should these be tasks in https://github.com/iterative/dvc.org/issues/2911 since params, metrics and plots are mainly experiment tracking mechanisms? (Correct me if I'm wrong.)

**Comment by iesahin** [comment]
Conceptually these are rather closer to experiment management. However, I think _metrics_  that's relevant to `dvc exp` commands are covered (implicitly) in `dvc exp show`. `dvc metrics` command is related to pipelines in its current usage.

I think having a separate metrics/plots guide that describes these in pipelines _and_ experiments context may be a better approach.

**Comment by jorgeorpinel** [comment]
OK so there's 2 part to this:

1. Explain params, metrics, and plots in the context of Data Pipelines -- should be part of #2883
2. Review their explanations in the context of Experiments -- should be in #2911

So I still think we could dissolve this issue into tasks in those epics.
