### ISSUE TITLE
guide: Cleaning Up Experiments 

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2592]
The new Get Started Experiments documentation won't contain the details about cleaning up the experiments from the DVC cache or Git objects. 

A UG document that explains the details about the relationship between Git objects for experiments, DVC cache, `dvc exp gc` and `dvc gc` is required.

**Comment by jorgeorpinel** [comment]
@iesahin please list it here: #2548

**Comment by iesahin** [comment]
I only added a reference, Github seems to replace issue/PR refs with their name. Thanks.

**Comment by jorgeorpinel** [comment]
Thanks. Yeah there's some new features then mentioning issues in other issues 🤷
