### ISSUE TITLE
Google Drive remote: add note on required authorization when impersonating users with service account

### ISSUE THREAD

**Issue by mmikolajczak** [iterative/dvc.org#2593]
When using service account with Google Drive storage/remote, files updated by default with service account ownership,
even if the target upload drectory is owned by some other user.
As service accounts itself have a rather low (and as far as we could found unadjustable) storage size quota, this can quickly
become an issue, and as such one would want to upload files with ownership assigned to some other user/entity. 

Fortunately, there is an option to achieve that with DVC, by setting **gdrive_service_account_user_email** in remote configuration. But this also requires some additional setup outside of DVC, in particular delegating domain-wide authority
to a service account in Google Workspace Admin console. While this is described quite well in a following [link](https://developers.google.com/admin-sdk/directory/v1/guides/delegation) present in the docs section on **gdrive_service_account_user_email**, there is no information there on what OAuth Scopes exactely have to be 
authorised for DVC.

I've initially used `https://www.googleapis.com/auth/drive` as the most intuitive one, but it resulted in client errors. Finally I've found in related DVC code [itself](https://github.com/iterative/dvc/blob/ce3a3ab1006d32ac672ec16c0b2994cbab328e83/dvc/fs/gdrive.py), that related the scopes that need authorization are:
- https://www.googleapis.com/auth/drive
- https://www.googleapis.com/auth/drive.appdata

But as it took some configuration double checks, as well as inspecting the actual source code – I think it would be helpful, if docs
mentioned/listed required scopes to be delegated/authorized explicitly.

**Comment by shcheklein** [comment]
Closed by (I hope) #2594 (@mmikolajczak thanks and please confirm that we can close this?)

**Comment by mmikolajczak** [comment]
@shcheklein as far as I can see in DVC code responsible for handling GDrive filesystem, the required OAuth scopes are constant (             "https://www.googleapis.com/auth/drive" and "https://www.googleapis.com/auth/drive.appdata") – and unless that code changes that note should suffice (meaning the issue can be closed).

**Comment by shcheklein** [comment]
Thanks @mmikolajczak !
