### ISSUE TITLE
Add link data registry example in the docs

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc.org#2601]
Hi! We have a good example of data registry https://github.com/iterative/dataset-registry
Should we put a link to it on the related docs page? https://dvc.org/doc/use-cases/data-registries
I think this will help people who is trying to understand how the actual data registry could look like or who just tries to find this example to use it and goes to that docs page from a search engine.

**Comment by jorgeorpinel** [comment]
Hi. It is already linked there:

![image](https://user-images.githubusercontent.com/1477535/124562390-97073700-de04-11eb-8d12-739622d17706.png)

and mentioned in an example:

![image](https://user-images.githubusercontent.com/1477535/124562452-a5ede980-de04-11eb-9235-a46c583ac060.png)

Did you mean making it more prominent? Feel free to submit a PR (or close this issue). Thanks!

**Comment by aguschin** [comment]
@jorgeorpinel, wow, thanks! It seems I completely missed those links) It's great that we have them in place. Closing the issue.

**Comment by jorgeorpinel** [comment]
Sure, np!
