### ISSUE TITLE
blog: (series of) posts on our Documentation Philosophy

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#2607]
Idea behind this is to Document in the Blog section of our website our philosophy behind Documentation, why accurate docs are so important, our commitment to quality, the process by which we maintain the docs, and/or other aspects.  

*****Update*******

Regarding question in Docs meeting on Target Audience:  
- Mainly -> New People that have not used DVC before. - See 5 below.
- Secondarily -> potential contributors/developers, future employees, DS team managers

Regarding Series:
- It would be ideal to hear (read) from each of you if it made sense to break it up into three parts - like maybe the 3 pillars of our docs philosophy or something to that effect.  They could be spaced out and each could deliver a piece.  Shows philosophy, shows values, shows teamwork. Builds trust in brand.
- If not, one post is totally fine

Regarding Capacity: Totally understand you have things you need to prioritize

Why I think this is important:
1.  Introduces more team members to the larger Community. 
2. It is a recurring theme in the Community that we do a great job on our docs.  We need to highlight this.  Celebrate a strength.
3. Feedback from the Community shows that when in the kicking the tires of MLOps tools process, having good docs is important to one's decision making in any tool's favor.  As such this post(s) would act as a confirming stamp for new people.
4. We should be working toward building blog content beyond Heartbeat, Community Gems and the occasional release piece.  
5. As we move forward, I believe defining our values in the Community will become more and more important.  Docs is a good starting place.

**Comment by shcheklein** [comment]
Love the idea @jendefig !

**Comment by jorgeorpinel** [comment]
> It would be ideal to hear (read) from each of you if it made sense to break it up into three parts - like maybe the 3 pillars of our docs philosophy or something to that effect. They could be spaced out and each could deliver a piece.

Let's brainstorm on possible topics then? Then pick one to start with (I can volunteer for that one but may need to pick @shcheklein's brain along the way). Ideas:

- Docs as an Iterative.ai product (which is how we want to see it I think): basically on how we adapt a typical tech dev workflow for our docs (proposal, roadmap, agile, etc.)
- Our custom docs engine: What it provides / why we don't just use sphinx-doc.org, readthedocs.org, gitbook.com, etc. (and haven't from the start). Promote it for other companies?
- Our mix of principles and best practices: picked from sources like https://documentation.divio.com/introduction/ and https://medium.com/memory-leak/documentation-best-practices-b0de3cdc323 as well as our own experience.

**Comment by jendefig** [comment]
Yes!  This looks really great! I like these ideas, especially docs as product, team formation, principles and best practices.  

One thing I didn't mention before, that's been rumbling in my head is that our blog right now is heavy on what and how pieces.  We need to balance with some why and who pieces. These connect values and the team to greater community.  And when I say balance I mean the what and hows will still be like 70% while why and who 30% -ish (up for discussion, but not equally balanced).

**Comment by shcheklein** [comment]
We don't have capacity for this in the near future. Closing this, and we can come back to this later.
