### ISSUE TITLE
Send a alert to Sentry when `/api` sends an error response

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2615]
* Sentry gives us a way to do this with `@sentry/gatsby`([docs](https://docs.sentry.io/platforms/javascript/guides/gatsby/usage/))
* We could update `src/utils/front/api.ts`, sending a Sentry alert after every [`setError` call](https://github.com/iterative/dvc.org/blob/29e5d55bc0965b9919abcc3f747e3f76a010239c/src/utils/front/api.ts#L22). There may be more elegant ways of handling this though.

**Comment by yathomasi** [comment]
We can directly log from the API themselves using [@sentry/node](https://docs.sentry.io/platforms/node/guides/express/)
