### ISSUE TITLE
katacoda: ideas on better integration [SPIKE]

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2623]
We can make notes, and buttons explicit:

https://learn.hashicorp.com/tutorials/waypoint/get-started-docker?in=waypoint/get-started-docker

<img width="611" alt="Screen Shot 2021-07-11 at 11 56 35 AM" src="https://user-images.githubusercontent.com/3659196/125207258-18652c00-e240-11eb-97d6-d1c283ecf960.png">

When you click the button, you can see the Katacoda:

<img width="1237" alt="Screen Shot 2021-07-11 at 12 04 51 PM" src="https://user-images.githubusercontent.com/3659196/125207290-4f3b4200-e240-11eb-8f8d-4a5ceb75420c.png">

**Comment by iesahin** [comment]
I think these integrations require a paid subscription. 

https://www.katacoda.community/embed.html#line-1-include-script-tag

![image](https://user-images.githubusercontent.com/476310/128185915-6d76bbbc-b139-4ef8-be99-b39b309cc1a1.png)

I can research this and implement if you are willing for a paid subscription. @shcheklein

**Comment by jorgeorpinel** [comment]
Questions
- Can we handle Katacoda? (It's time consuming, we already has issues maintaining example repos)
  If so how much traffic is it getting/ could it get?
- Could we replace with Codespaces in the example repos instead?
  And is that easier to "integrate" in docs? E.g. via [Open in Codespaces] button (not sure how to do that)

**Comment by jorgeorpinel** [comment]
I'm closing this since Katacoda died. But mentioning these desired features in https://github.com/iterative/gatsby-theme-iterative/issues/41
