### ISSUE TITLE
docs: redirect `/doc/cml` to `cml.dev/doc`

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#2628]
Now that https://github.com/iterative/cml-website/pull/60 is merged,

- https://dvc.org/doc/cml/ should `301` redirect to https://cml.dev/doc/
- current `/content/docs/cml/` stuff in this repo can be removed

Part of https://github.com/iterative/cml/issues/514

**Comment by jorgeorpinel** [comment]
Please coordinate with me to try and redirect the ranking from Google Search Console too.

**Comment by casperdcl** [comment]
@jorgeorpinel is this (hopefully not impossible) search stuff related to the implementation in this repo, or can it be tackled separately?

**Comment by jorgeorpinel** [comment]
Can def. be tackled separately. There might just be a time window where the ranking redirection is possible.

**Comment by jorgeorpinel** [comment]
We should probably try to add cml.dev to our Google Search Console properties first though... Requires DNS verification cc @shcheklein or @rogermparent yelp

![image](https://user-images.githubusercontent.com/1477535/126522604-ddcd95cd-56a0-476d-ada5-a2bf1beb9242.png)

**Comment by casperdcl** [comment]
> Can def. be tackled separately. There might just be a time window where the ranking redirection is possible. So ideally letr's do both at the same time.

@jorgeorpinel done with implementation (#2658) so please lemme know if you need to coordinate about search console stuff.

**Comment by jorgeorpinel** [comment]
Well up to you really. Do you want to preserve traffic? 🙂 I posted on our chat but didn't have a reply yet. Will tag you.
