### ISSUE TITLE
restyled: looks like there is a discrepancy between prettier and restyled

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2641]
On this file content/docs/user-guide/contributing/blog.md if you try to update it a bit, restyled will complain, while prettier not.

**Comment by jorgeorpinel** [comment]
> if you try to update it a bit, restyled will complain, while prettier not.

I tried in #2774 and everything I'm getting the opposite. Prettier complains (for bad changes) but Restyled always works... ⏳

**Comment by jorgeorpinel** [comment]
Another thing I've noticed is that Restyled sometimes decides not to run e.g. for https://github.com/iterative/dvc.org/pull/2776 (only ran twice 6 days ago https://restyled.io/gh/iterative/repos/dvc.org/pulls/2776).
