### ISSUE TITLE
rf: download (typo) in push

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc.org#2642]
> -a, --all-branches - determines the files to `download` by examining dvc.yaml and .dvc metafiles in all Git branches, as well as in the workspace. It's useful if branches are used to track experiments. Note that this can be combined with -T below, for example using the -aT flags.

in https://github.com/iterative/dvc.org/blob/master/content/docs/command-reference/push.md

**Comment by shcheklein** [comment]
Hey, @karajan1001 ! Thanks, I think the rule for bugs like this is to fix them with the Edit on Github button in the docs, or by creating a PR in a regular way. For small things. It takes more time to create a ticket I think :)

**Comment by karajan1001** [comment]
close for #2652
