### ISSUE TITLE
glossary: add "metrics" and "plots"

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2644]
I think it would be nice to have these 2 concepts available to be used with "abbr" tooltips.

See also https://github.com/iterative/dvc.org/issues/2956#issuecomment-951017753

**Comment by jorgeorpinel** [comment]
Agreed. Are you planning to make an initial PR for this @daavoo ?

**Comment by daavoo** [comment]
> Agreed. Are you planning to make an initial PR for this @daavoo ?

Sure. I will firts try to go over existing docs and issues discussing those terms

**Comment by jorgeorpinel** [comment]
Maybe you wanted to include these in the DVCLive docs? Feel free to add them there only and we'll take care of gradually including them in other docs. No need to overburden you with that part.
