### ISSUE TITLE
add a user guide page about the optimization (advanced mode)

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#265]
In the recent DVC release we are changing the way we are linking DVC controlled files with the working space via https://github.com/iterative/dvc/pull/1841, https://github.com/iterative/dvc/pull/1914 and a potentially a few other PRs.

The motivation for this change could be found here: https://github.com/iterative/dvc/issues/1599

This is a major change and affect the user workflow, cache settings, performance, etc. Sometimes is a way that can make users unhappy - since copying is happening.

Things we need to do here:

- [x] we should write a user guide section about the links (some information can be taken from - the https://github.com/iterative/dvc/issues/1599);
- [x] we need to write a section "advanced mode" or "performance optimization" which should be a brief guide on how to switch DVC into using `hardlinks`, `symlinks`, etc, what caveats ppl should expect (that it's recommended to use protected mode by default and `dvc unprotect` in those cases);
- [x] we should put links to these sections wherever it's appropriate;
- [x] we should update the [config](https://dvc.org/doc/commands-reference/config) doc - introduce new flags;
- [x] we should review and update existing mentions of the `dvc unprotect`;
- [x] [Update a Tracked File](https://dvc.org/doc/user-guide/update-tracked-file) section itself should be updated;

**Comment by mroutis** [comment]
Related: https://github.com/iterative/dvc/pull/1997/files#r283492357

**Comment by jorgeorpinel** [comment]
Thanks for merging #345 Ivan. I still have to double check the last 2 check boxes in this issue though. I'll close again when I do so if you don't mind.

**Comment by shcheklein** [comment]
oops, Github closed it automatically :)
