### ISSUE TITLE
ref: broken image in `plots` smoothing example

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2651]
In https://dvc.org/doc/command-reference/plots#example-smooth-plot

![image](https://user-images.githubusercontent.com/1477535/126387666-a4228c2a-5a9a-40cd-8248-6d059a629d80.png)

**Comment by shcheklein** [comment]
Hmm, I can't reproduce this. We need more details/logs.

**Comment by jorgeorpinel** [comment]
The image is showing now... Blip 🤷
