### ISSUE TITLE
Integrating Testimonial.to into the website

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#2673]
I would like to integrate https://testimonial.to/features into the website?

**What is it***
A way for us to have a "wall of love" with video, text and tweeted testimonials on our website.  

**Things to Consider**
1. Where?  Landing page at bottom with direct to Community page? or Community page? or page of its own?
2. This should probably be on the Iterative site and maybe CML too?

@rogermparent @julieg18 Here is how the integration works with React: https://support.testimonial.to/integration-react

Let's discuss and get going! 😊

**Comment by julieg18** [comment]
Looking at the site, it's basically just an iframe, so I don't see any issues with integrating in any of the websites 😃

**Comment by jendefig** [comment]
@julieg18 If I had to pick of all the things this is the most important because it goes to to focus on User Stories in the 9 month planning.  I will be working on getting this set up in the rest of this week and next.

**Comment by jendefig** [comment]
@julieg18 We now have a Wall of Love ❤️!
Here's the code:

<script type="text/javascript" src="https://testimonial.to/js/iframeResizer.min.js"></script>
<iframe id="testimonialto-iterative-open-source-community-shout-outs-light" src="https://embed.testimonial.to/w/iterative-open-source-community-shout-outs?theme=light&card=base&loadMore=on&initialCount=20" frameborder="0" scrolling="no" width="100%"></iframe>
<script type="text/javascript">iFrameResize({log: false, checkOrigin: false}, "#testimonialto-iterative-open-source-community-shout-outs-light");</script>

**Comment by jendefig** [comment]
I need help with this: https://support.testimonial.to/add-custom-domain

I put it as testimonial.iterative.ai - some things need to be corrected for it to work.  Should I open issue on the iterative side too?

And what's timeline for design to get the Wall of Love up?  Where does it fit in your sprints?
@julieg18 @rogermparent

**Comment by rogermparent** [comment]
> I need help with this: https://support.testimonial.to/add-custom-domain

Looks like that needs some CloudFlare configuration to add CNAMEs- I don't currently have CF access, so @shcheklein or someone else that has it will have to add that in.

> And what's timeline for design to get the Wall of Love up? Where does it fit in your sprints?

Currently the websites team is a bit of a skeleton crew so we don't have any defined sprints. We can bring together our current status on this and get together a plan to get it ASAP. @yalozhkin has anything already been started for this?

We can try throwing together a PR that just kind of sticks it in the community page to get an idea of what it looks like. That should help speed up the design since we'll actually know what we're designing around.

**Comment by rogermparent** [comment]
From a quick test:

Desktop:
![desktop screenshot](https://user-images.githubusercontent.com/9111807/137979039-7a98ea62-a80e-4e95-972f-ec2827d849df.png)

Mobile:
![mobile screenshot](https://user-images.githubusercontent.com/9111807/137979169-9fe6724a-521c-40d0-a093-f596631a39ce.png)

One thing to note: the iframe resizer that the testimonial embed uses doesn't play well with the hide/show behavior of our `Section`s, as when first opened the iframe will be stuck at the initial un-resizes size and only grow when the whole window is resized. We'll have to either put the testimonial embed in a non-collapsible section or rework how the collapsible sections are implemented (possibly just using the `UnmountClosed` component of `react-collapse` on this one specifically).

Not sure if the design will actually entail one of these `Section`s, it just seemed like the most natural place to stick one of these. I'll pop up a PR of what I have for demo's sake, but it's really rough.

**Comment by jendefig** [comment]
> Considering the iframe will be on our site, we may not actually need a custom domain here. Not sure if that's the case, though, I haven't interacted with testimonial yet.

We don't need to mess with the custom domain if it's on our sites.  No need to do unnecessary work here.  I know everyone's in full tilt!

**Comment by shcheklein** [comment]
@julieg18 could you please check if they use trackers/cookies of some sort?

**Comment by julieg18** [comment]
> Sorry I'm confused about what all this means. Are you saying I just need to take off the one that was from LinkedIn?

Yes, we are unable to use any linkedin embeds since they place several cookies which stops dvc.org from being GDPR compliant. Taking off the post from linkedin should fix it. 

> But in reality if people are saying good things about us on LI I would want to include it. So I would have to ask those people if I can share their comment in Testimonial. to? Would that make it ok?

I think we're able to do this as long as we post who wrote and give a link to the linked post that we took it from (not using a linkedin embed). I'll do some research to be 100% sure.

**Comment by jendefig** [comment]
@julieg18 @rogermparent @shcheklein Now that the LinkedIn item is removed, where are we at with getting the Wall of Love up on the website?

**Comment by julieg18** [comment]
> @julieg18 @rogermparent @shcheklein Now that the LinkedIn item is removed, where are we at with getting the Wall of Love up on the website?

I talked to support and we no longer have linkedin and our site is GDPR compliant! They're also going to look into a different way to use LinkedIn posts so we might be able to add LinkedIn posts in the future! I'll start playing around with code to see if we can make the site look nicer and get the dropdown working correctly.

**Comment by jendefig** [comment]
> > @julieg18 @rogermparent @shcheklein Now that the LinkedIn item is removed, where are we at with getting the Wall of Love up on the website?
> 
> I talked to support and we no longer have linkedin and our site is GDPR compliant! They're also going to look into a different way to use LinkedIn posts so we might be able to add LinkedIn posts in the future! I'll start playing around with code to see if we can make the site look nicer and get the dropdown working correctly.

That's awesome @julieg18

**Comment by julieg18** [comment]
Ok, I decreased the card size to small and applied a scroll the iframe, keeping it at a similiar height to the other sections: 

https://user-images.githubusercontent.com/43496356/145110157-1eb6040d-4690-4d5e-94f8-d3ce25028272.mov

How does it look? cc @jendefig

**Comment by jendefig** [comment]
Looks great @julieg18 !!!  So where will this live on the website? On the community page?

**Comment by julieg18** [comment]
> Looks great @julieg18 !!!  So where will this live on the website? On the community page?
> 
> 

Currently it's in a section in the community page. But we could always discuss placing it somewhere else.

**Comment by jendefig** [comment]
> Currently it's in a section in the community page. But we could always discuss placing it somewhere else.

Ok.  So will it have the scroll bar?  I found @roger's PR and it didn't have the scroll bar.  With the scroll bar, I'm good with it being at the top of the page, but with out the scroll bar, I'd prefer the current first section to go first. I don't want people to have to scroll forever to get to the next section.  The scroll bar is good if we can use that.

**Comment by julieg18** [comment]
> Ok. So will it have the scroll bar? I found @Roger's PR and it didn't have the scroll bar. With the scroll bar, I'm good with it being at the top of the page, but with out the scroll bar, I'd prefer the current first section to go first. I don't want people to have to scroll forever to get to the next section. The scroll bar is good if we can use that.

Currently the one with the scroll bar is only on my local computer. I'll push the code in a bit.

**Comment by julieg18** [comment]
Code is pushed!
