### ISSUE TITLE
Possible typo within internal-files.md

### ISSUE THREAD

**Issue by seungwonpark** [iterative/dvc.org#2678]
Though all md5 hashes should be 32 characters long, I happened to find out that there is a hash with 34 characters in the docs.

https://github.com/iterative/dvc.org/blob/master/content/docs/user-guide/project-structure/internal-files.md#directories

Looks like `0b40427ee0998e9802335d98f08cd98f` should be changed to sth like `0b40427ee0998e9802335d98f08cd9` (2 characters shorter). May I try to regenerate the hashes for the docs in the `internal-files.md` ?

**Comment by jorgeorpinel** [comment]
By all means @seungwonpark ! Please edit that file and send a quick PR. Thanks!
