### ISSUE TITLE
concepts: Describe "target" concept

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2698]
It looks we are using "target" in a specific way while describing `dvc repro`, and pipeline related documents. It might a good to define the term in a concept page.

**Comment by shcheklein** [comment]
@iesahin could you please clarify the concern please? some examples would help a lot I think. (I'm already biased and do not feel the problem, heh :) )

**Comment by iesahin** [comment]
While writing `dvc exp run` guide, I noticed that "target" may mean another thing in the context of the experiments: Metrics to reach. If the user starts from the pipelines and learns what we mean by targets, they'll have no problem. But if they are starting from scratch and we tell them about `dvc exp run <target>`, it may also mean "run until the experiment metrics reach a target." Especially within the checkpoints context, where we will discuss/implement this. (e.g. #2244)

I'm assuming the reader is skimming and lazy, BTW. :)

Explaining what we mean by target and using the word solely within pipelines context may be better.

**Comment by shcheklein** [comment]
I would say that if we think that the word _target_ in the context of `dvc exp` usually means a metric to achieve and we use actively nearby with its regular meaning (stage, file, etc), it's better then to use something else for the argument name `dvc exp run <target>` to avoid the confusion. Or use "goal" for the metric. I'm not sure how can the concept explanation help to be honest. Unless I'm missing something.

> using the word solely within pipelines context may be better.

would this alone be enough?

**Comment by jorgeorpinel** [comment]
> we are using "target" in a specific way while describing dvc repro

At least in https://dvc.org/doc/command-reference/repro "targets" refers to the command's argument, specifically defined in the **Options** section.

> I noticed that "target" may mean another thing in the context of the experiments: Metrics to reach

It's fine to use the word "target" in this context too. I don't think a tooltip will help if the worry is disambiguation. The text context should be clear enough. Alternatively you can use "goal" or some other similar term.

On the other hand basic concepts should be DVC-specific and "a metric to reach" relates in general to data science or even other fields, I think.

> better then to use something else for the argument name dvc exp run <target> to avoid the confusion

I honestly don't think this will be confusing (hasn't been so far that I know of). Also, renaming it here would imply renaming it in many other commands and it may not be easy to find another term that covers them all. But if it does end up being confusing we can bring this up again with the core team.

**Comment by iesahin** [comment]
OK, if you both see this as a non-problem, I'm closing this. Thank you for the comments. @jorgeorpinel @shcheklein

**Comment by jorgeorpinel** [comment]
Thank you!
