### ISSUE TITLE
Add Search functionality to Blog

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#2712]
As the content grows, it would be good to have an internal search function for the blog like we do on the docs.

**Comment by julieg18** [comment]
I think this is doable! Are we planning to mimic the design of the doc's search input? Also, where do we want this input to be placed on the blog? The search input for the docs is in the sidebar, but the blog doesn't have a sidebar 🤔

**Comment by shcheklein** [comment]
It means that we need some design input here. Let's put it in the list of things for the design team.

**Comment by julieg18** [comment]
Do we have a deadline or priority level for this issue?

**Comment by jendefig** [comment]
Tomorrow?  Just kidding.  To me this should have always been there.  Now that we have more content, it's much more important.  I know you've got other things to tend to and I don't know how time consuming this is.  If it helps this is how I would rank the issues I have, in importance from greatest to least, but all accomplished by end of quarter. 😬 

1. Landing page release video positioning - Due Nov 17th or at time of release if it gets extended
2. Testimonial.to - ASAP per Dmitry, but he'd put release above it too.
2. Search function for blog - 
3. Add YouTube to Learn line up on the Community Page
4. Educational Course Connection - this is last only because it will not come out until the end of the year.

If you told me, "there's no way we can do all that by the end of the year with everything else," I'd say cut out 2 and 3 and put them in Q1 '22. The rest need to get done.

**Comment by julieg18** [comment]
@DavidGOrtega also mentioned using faceted search!

**Comment by jendefig** [comment]
> 

What does that mean?

**Comment by jendefig** [comment]
> @DavidGOrtega also mentioned using faceted search!

What does that mean?

**Comment by julieg18** [comment]
> What does that mean?

[Faceted search](https://www.addsearch.com/blog/faceted-search/) is a way of searching by applying filters to your search (like how you can narrow down your search on Amazon by selected the color or size you want). We already have tags on our blog posts. Maybe we can show the available tags below wherever we place the search bar, allowing users to select them 🤔

**Comment by jendefig** [comment]
Yes!  I like this idea.  It will send them to more content they didn't even know they were looking for! Please yes!

**Comment by yalozhkin** [comment]
@yathomasi please take a look at the [review](https://www.figma.com/file/Ln51x4Aj6l1LcgcKigN5FT/DVC-Blog_Search-review?node-id=0%3A1).
