### ISSUE TITLE
guide: Add `--glob` and `--recursive` options to Running Experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2730]
It looks there are bugs in `dvc exp run` related to these options. It's better to remove these options from the ongoing guide in #2690. 

## Waiting For

- [x] iterative/dvc#6456
- [x] iterative/dvc#6457
- [ ] ref: Revise `exp run` not to contain any options automatically inherited from `dvc repro`

**Comment by iesahin** [comment]
It looks #6457 isn't going forward, so I'll just add `--recursive` to the guide.

**Comment by jorgeorpinel** [comment]
So will https://github.com/iterative/dvc.org/pull/2846 close this?

**Comment by iesahin** [comment]
I couldn't decide if it closes. It may be better to remove `dvc repro options` statement in the usage text `dvc exp run` command reference and list the supported `dvc repro` options only.

**Comment by jorgeorpinel** [comment]
Sorry @iesahin can you clarify your answer? I did not understand how that's related to this issue about the guide.

Also did you add

> Revise exp run not to contain any options automatically inherited from dvc repro

? Why would that be and how is it related here again? I'm lost, can you re-scope this issue and/or create other ones so they're clear? Thanks

**Comment by jorgeorpinel** [comment]
OK I checked the PR and I think we don't need to cover `--recursive` in the Running Exps guide, just like we don't cover all the `repro` options in it (I think, right?). This is more related to data pipelines.

> list the supported dvc repro options only

Let's definitely create an issue about this. What options are we listing in `exp run` that are actually not supported?

Thanks
