### ISSUE TITLE
guide: Comparing Experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2737]
It may be worthwhile to have a section in the Experiment Management about `dvc exp show`, `dvc exp diff` and their options. 

Related #2548 

- [x] Is https://github.com/iterative/dvc.org/issues/2844 still needed after this?

**Comment by jorgeorpinel** [comment]
I think it could be included in https://github.com/iterative/dvc.org/pull/2752 for now, as comparing them is probably a basic need to manage them. May not even need an explicit section but rather implied throughout that guide.

**Comment by iesahin** [comment]
"Managing" feels too broad for me. It can include everything we write in the "Experiment Management" chapter. 

I understand what you mean by "managing", after we have some set of experiments by running them we compare them, persist them, push them, discard them, etc.

**Comment by jorgeorpinel** [comment]
> "Managing" feels too broad

Yes it's pretty broad you're right. But it should be clear what we mean given the context: listed under "management" and at the same level as "running", "sharing", "removing".

> compare them, persist them, push them, discard them

If there's a better title than "managing" let's change it, but we agree on the contents of the doc I think? Pushing is part of "sharing" though.

**Comment by jorgeorpinel** [comment]
p.s. to clarify, we'll include this in the doc being created in https://github.com/iterative/dvc.org/pull/2752 right? No need to be in the same PR (although it wouldn't hurt).

**Comment by jorgeorpinel** [comment]
I think "Comparing" isn't the best title here. We'll basically include `exp show` and `exp diff` right? So maybe "Listing and Comparing"? Thanks

**Comment by iesahin** [comment]
"Listing and comparing" is rather verbose I think. Users will use these commands to compare the experiments. What other cases do you think of using these commands?

"Comparing experiments" might not be the best title but "Listing and comparing experiments" doesn't also seem that best title too.

**Comment by shcheklein** [comment]
I think comparing should be fine (at the end you list them primarily for that reason?) ... can be also Navigating experiments (in this case `diff` won't fit precisely. Naming is hard :)

**Comment by jorgeorpinel** [comment]
Navigating and Comparing?

Let's get the content first and the name should be easier to decide then 🙂
