### ISSUE TITLE
guide: clarify resuming (checkpoints)

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2742]
In the current checkpoints guide, we talk about resuming the train loop:

> you might want to resume training from a particular one

And then we explain how to use `dvc exp apply`. 

However, we don't highlight where in the code the actual resuming happens, which would be:

```python
    if os.path.exists("model.pt"):
        model.load_state_dict(torch.load("model.pt"))
```

I think that, similar to how we highlight the "checkpoint updating" snippet in [Registering checkpoints in your code](https://dvc.org/doc/user-guide/experiment-management/checkpoints#registering-checkpoints-in-your-code):

> The line torch.save(model.state_dict(), "model.pt") updates the checkpoint file.

We should highlight the "checkpoint resuming" snippet.

**Comment by shcheklein** [comment]
How large of the change are we talking about here? A few lines? @daavoo could you contribute it via edit on GH button?

**Comment by jorgeorpinel** [comment]
Thanks. This would be part of the larger task of revising that whole guide (see #2548). If it's a small change do please feel free to submit it, otherwise maybe just mention in #2548 for now.

**Comment by daavoo** [comment]
> Thanks. This would be part of the larger task of revising that whole guide (see #2548). If it's a small change do please feel free to submit it, otherwise maybe just mention in #2548 for now.
> 
> p.s. I've started this larger task in #2753.

Added an item list to #2753
