### ISSUE TITLE
error: pathspec 'code'' did not match any file(s) known to git

### ISSUE THREAD

**Issue by lunasdejavu** [iterative/dvc.org#276]
My environment is windows 7 x64,
After I followed the step 
```
    $ mkdir classify
    $ cd classify
    $ git init
    $ wget https://dvc.org/s3/so/code.zip
    $ unzip code.zip -d code && rm -f code.zip
    $ git add code/
    $ git commit -m 'download code'
```
it showed the error:
`error: pathspec 'code'' did not match any file(s) known to git`

then I followed the direction from @mroutis  using  the double quotes
git commit -m "download code"
and it worked after all.

**Comment by shcheklein** [comment]
@lunasdejavu good catch! Would you mind to fix it? Just click on the "Edit on Github" button, then edit the file (pen button at the top) and create a PR. No need to do anything out of Github :)

**Comment by jorgeorpinel** [comment]
He also reported that
> du -sh data/* is not working under windows 7
  I am undet Anaconda
  (base) C:\classify> du -sh /data/
  du: illegal option -- h
  ...
> > from https://dvc.org/doc/tutorial/define-ml-pipeline

I can take a look at these and similar cases in the docs when I get back home to my Windows machine. I'll try to find out whether @lunasdejavu is using the Linux subsystem too.

**Comment by jorgeorpinel** [comment]
I could look look for single quotes in console commands all over the docs...

@lunasdejavu what are you using for terminal under Windows 7? Linux Subsystem?

**Comment by lunasdejavu** [comment]
> I could look look for single quotes in console commands all over the docs...
> 
> @lunasdejavu what are you using for terminal under Windows 7? Linux Subsystem?

the latest anaconda

**Comment by jorgeorpinel** [comment]
I created https://github.com/iterative/dvc.org/pull/288 to address this and other instances @shcheklein
