### ISSUE TITLE
Not compatible with in-browser Codespace port forwarding

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2764]
Go to https://github.com/iterative/dvc.org

~~Press `.` or~~ click to start/create a codespace (`master` branch):

![image](https://user-images.githubusercontent.com/1477535/131050402-04af7af7-ba1f-40a2-b612-592f8cff886b.png)

Wait for it to provision/start (it should also run `yarn install` automatically). Run the dev server with `yarn develop` from the TERMINAL:

![image](https://user-images.githubusercontent.com/1477535/131050550-eec8d8c6-9e9e-4cf5-9c7f-b36d03987a9e.png)

HTTP port 8000 is [auto-forwarded](https://docs.github.com/en/codespaces/developing-in-codespaces/forwarding-ports-in-your-codespace) to a special subdomain of githubpreview.dev. Open it:

![image](https://user-images.githubusercontent.com/1477535/131050631-c9aad13f-66df-4d6e-8d63-8ba0fd46b88d.png)
(The URL can be found in the PORTS tab)

The app crashes due to some socket problem:
![image](https://user-images.githubusercontent.com/1477535/131050710-c70b33b3-b5ea-4ea7-95ec-84570a998fd7.png)

Is there a way to fix it? I think the regular app build works but it takes a lot longer. Another workaround is to use [ngrok](https://ngrok.com/).

**Comment by julieg18** [comment]
Looks to be working now!

![image](https://user-images.githubusercontent.com/43496356/146458824-c86fd718-8f28-4805-892d-0c092ccd9430.png)

Is it working on your end?

**Comment by jorgeorpinel** [comment]
Yep. I can confirm it works now. I guess the recent Gatsby update did it. Thanks for following up @julieg18 !
