### ISSUE TITLE
guide: revisit Checkpoints guide(s?)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2769]
> Per task in https://github.com/iterative/dvc.org/issues/2548

Trying to make it broader (more general) yet shorter, and cover all the usage details (extract from cmd ref) in a structured way.

- [x] General text/story review - https://github.com/iterative/dvc.org/pull/2910
- [x] Add info from https://github.com/iterative/dvc.org/pull/2672 to the checkpoints page.
- [ ] Incorporate/merge material from https://github.com/iterative/dvc.org/pull/2753/files
- [ ] Should close https://github.com/iterative/dvc.org/issues/2432
- [ ] Should close https://github.com/iterative/dvc.org/issues/2568
- [x] Remove deep details from https://dvc.org/doc/command-reference/exp/run#checkpoints
- [ ] Sharing checkpoints with `dvc exp push` (here or in the Sharing Exps guide)
(See https://github.com/iterative/dvc.org/issues/2769#issuecomment-912478244)
- [ ] Add Checkpoints sections to all other Exp guides? Per https://github.com/iterative/dvc.org/issues/2769#issuecomment-914207131

---
Decide on these:
- [ ] Keep a separate guide but have some basics in a **Checkpoints** section in each Exps guide (_Running_, _Sharing_, etc.)
- [ ] Maybe https://github.com/iterative/dvc.org/issues/2742
- [ ] Maybe https://github.com/iterative/dvc.org/issues/2568
- [ ] Maybe https://github.com/iterative/dvc.org/issues/2509
- [ ] Maybe https://github.com/iterative/dvc.org/issues/2741

**Comment by daavoo** [comment]
It might be worth adding a mention about how to properly *Share Checkpoints* with `dvc exp push`. 

The current content finishes without sharing the checkpoints and the last section [Adding checkpoints to git](https://dvc.org/doc/user-guide/experiment-management/checkpoints#adding-checkpoints-to-git) will squash the checkpoint commits making them not usable later.

We kind of already have the [Sharing Experiments guide](https://dvc.org/doc/user-guide/experiment-management/sharing-experiments) but it doesn't mention Checkpoints at all.

**Comment by iesahin** [comment]
I think that deserves a dedicated issue @daavoo .

**Comment by daavoo** [comment]
As new Checkpoint specific issues appear (https://github.com/iterative/dvc.org/issues/2797) I think it would make more sense to have a dedicated Checkpoints section on each individual Experiment guide (Running, Sharing, etc.), like https://dvc.org/doc/user-guide/experiment-management/running-experiments#checkpoint-experiments .

**Comment by iesahin** [comment]
I think that's a good idea.

**Comment by jorgeorpinel** [comment]
> deserves a dedicated issue

Oops I saw that issue and collapsed back into here 😅 just noticed your comment.

Should be OK as a task here? We have so many issues already... Hard to keep track.

**Comment by jorgeorpinel** [comment]
> more sense to have a dedicated Checkpoints section on each individual Experiment guide (Running, Sharing, etc.)

Would probably need both its own guide and a small Checkpoints section in each Exps guide.

**Comment by jorgeorpinel** [comment]
Should we merge this issue with https://github.com/iterative/dvc.org/issues/2432?

**Comment by jorgeorpinel** [comment]
@daavoo want to repurpose this to include checkpoint charing info for now? Per https://github.com/iterative/dvc.org/issues/2769#issuecomment-912478244

Otherwise this looks stale (per https://github.com/iterative/dvc.org/issues/2432#issuecomment-1171675345 and https://github.com/iterative/dvc.org/issues/2568#issuecomment-1171673641) and could be closed.
