### ISSUE TITLE
du -sh /data/ is not working under windows 7

### ISSUE THREAD

**Issue by lunasdejavu** [iterative/dvc.org#277]
I am following the [tutorial](https://dvc.org/doc/tutorial/define-ml-pipeline):
d`u -sh /data/`
I am undet Anaconda
```
(base) C:\classify> du -sh /data/
du: illegal option -- h
Usage: du [-abcklsxDLS] [--all] [--total] [--count-links] [--summarize]
       [--bytes] [--kilobytes] [--one-file-system] [--separate-dirs]
       [--dereference] [--dereference-args] [--help] [--version] [path...]
```
what command parameter should I change?

**Comment by shcheklein** [comment]
@lunasdejavu it's an optional command, not running it won't break anything else in the tutorial. I think you can just remove `-h` in your case.

**Comment by lunasdejavu** [comment]
@shcheklein  thanks it works now. I know, but @efiop  asked me to made an issue in Discord yesterday.

**Comment by jorgeorpinel** [comment]
@lunasdejavu what are you using for terminal under Windows 7? Linux Subsystem?
