### ISSUE TITLE
guide: "Cleaning-up Experiments" improvements

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2777]
> Follow-up to #2631

Guide in https://dvc.org/doc/user-guide/experiment-management/cleaning-experiments

- [ ] Possibly copy edit/ summarize more
- [ ] Remove similar examples from the command reference `dvc exp remove` and
  `dvc exp gc`.
- [ ] Rename the page to "Removing Experiments" ?
- [ ] Replace Git plumbing commands in "Removing experiments from remotes". Use `exp remove --cloud` instead. Per https://github.com/iterative/dvc/pull/6471 & https://github.com/iterative/dvc.org/pull/2744
- [ ] Link to https://dvc.org/doc/user-guide/experiment-management/sharing-experiments per https://github.com/iterative/dvc.org/pull/2631#discussion_r700356656

**Comment by jorgeorpinel** [comment]
>  Rename the section to "Removing experiments"

@iesahin I don't see that section in https://dvc.org/doc/user-guide/experiment-management/cleaning-experiments

**Comment by iesahin** [comment]
> I don't see that section

I mean renaming the whole document to "Removing Experiments." I didn't want to rename the file in the middle of the review.

**Comment by jorgeorpinel** [comment]
What's wrong with "cleaning up"? Includes removing and garbage collecting. No strong opinion either way but I don't see a problem with the current title.
