### ISSUE TITLE
Improve DVC Download Link Check Action

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2786]
- [ ]  Currently our download link action checks if links that start with `/download` are successful, but will still pass if no `/download` links are found on the home page. We should find a way to count how many links our action found and fail the action if the amount isn't four.
- [ ] We should also find a way to have our check (the one that checks every hour) see if its already opened a ticket for the same issue before opening another one. 
- [ ] Have some way to either see a branch is before [commit](https://github.com/iterative/dvc.org/commit/ed83e149f3eb1516d1ff03a442fe7eb64950a8a7) (and fail fast?), or see that PR doesn't touch links(mentioned in [pull request](https://github.com/iterative/dvc.org/pull/2791#issuecomment-928283528))

**Comment by iesahin** [comment]
Is it possible to wait for packages to be completed before running the link check in new deployments? Otherwise they will almost always fail.

**Comment by julieg18** [comment]
> Is it possible to wait for packages to be completed before running the link check in new deployments? Otherwise they will almost always fail.

What do you mean by "packages"?

**Comment by jorgeorpinel** [comment]
> find a way to count how many links our action found and fail the action if the amount isn't four

Shouldn't that be a separate check? Not really link related per se. Up to you (do we have more checks?)

**Comment by jorgeorpinel** [comment]
> Is it possible to wait for packages to be completed before running the link check

I think he meant checks and I think that's already been addressed per https://github.com/iterative/dvc.org/pull/2813#issuecomment-916011778,

**Comment by julieg18** [comment]
Research so far for fixing issues:

> * Currently our download link action checks if links that start with `/download` are successful, but will still pass if no `/download` links are found on the home page. We should find a way to count how many links our action found and fail the action if the amount isn't four.

With the way `lychee` works, I don't think there is a way to accomplish this without using a different external package. 

> We should also find a way to have our check (the one that checks every hour) see if its already opened a ticket for the same issue before opening another one.

The only way I could think of doing this is using the [Github rest api](https://github.com/marketplace/actions/github-api-request) to fetch issues with `link-checker` label. If it finds an open issue, it doesn't open a new one.

> Have some way to either see a branch is before commit (and fail fast?), or see that PR doesn't touch links(mentioned in pull request)

Not sure about a solution for this one yet 🤔Though Ivan mentioned having the check end with a neutral instead of a fail depending on if there are failures in dvc.org and pull request site. 

cc @shcheklein @rogermparent
