### ISSUE TITLE
Fix auto-dark mode

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2794]
After the last update, Chrome on Mac converts all the websites into the dark mode automatically. It works fine for dvc.org/cml.dev, but with some small bugs:

<img width="1437" alt="Screen Shot 2021-09-04 at 9 52 59 AM" src="https://user-images.githubusercontent.com/3659196/132102407-9bcbbe74-1f6d-4e21-809b-6f45802f41fb.png">

(white areas that it was not able to convert, and some glitches with icons)

Also, on the landing page we need to review the main image.

**Comment by shcheklein** [comment]
I think that it got enabled with chrome://flags/ - enable dark mode somehow (I didn't do it manually)

**Comment by julieg18** [comment]
`Blog/Feed/Item` components also have white area on overflow:

![image](https://user-images.githubusercontent.com/43496356/132215664-4b6d8538-752e-495f-ae2e-8246a56d2954.png)

**Comment by casperdcl** [comment]
:dark_sunglasses: I didn't know the engine had a dark mode. Can we add a toggle button?

**Comment by julieg18** [comment]
> Can we add a toggle button?

I don't think so, since Google Chrome's dark mode can only be enabled in a user's browser settings.

**Comment by casperdcl** [comment]
I mean a cross-browser toggle button (perhaps for separate issue).

**Comment by julieg18** [comment]
> I mean a cross-browser toggle button (perhaps for separate issue) akin to https://squidfunk.github.io/mkdocs-material/ (next to search bar)

As far as I know, it's possible but I'm not sure how hard it would be to implement. We'd need to decide on a color scheme and update our site's styles accordingly.

**Comment by julieg18** [comment]
Main image should be back to normal for iterative.ai and blog gradients are fixed as well!
