### ISSUE TITLE
Missing "train" stage in the tutorial

### ISSUE THREAD

**Issue by Hongbo-Miao** [iterative/dvc.org#2795]
## Description

Based on the tutorial
https://dvc.org/doc/start/data-pipelines#visualize

when run `dvc dag`, it shows

```
         +---------+
         | prepare |
         +---------+
              *
              *
              *
        +-----------+
        | featurize |
        +-----------+
              *
              *
              *
          +-------+
          | train |
          +-------+
```

However, the tutorial only have parts for "prepare" and "featurize" stages.
It currently does not have a section related with "train" stage like `dvc run -n train xxx`.

### Expected

Expecting a section for "train" stage. Not a big issue. However, it would be great to be consistent! 😃

**Comment by shcheklein** [comment]
Hi, that document has a section `Expand to add more stages.` which add the `train` stage. Intention was to hide it to make the tutorial simpler for users who do not run commands but want to grasp the idea behind pipelines. Each `dvc run` takes too much space.

**Comment by Hongbo-Miao** [comment]
I see, thanks Ivan!
