### ISSUE TITLE
guide: *Share Checkpoints* with `dvc exp push`.

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2797]
It might be worth adding a mention about how to properly *Share Checkpoints* with `dvc exp push`. 

The current content finishes without sharing the checkpoints and the last section [Adding checkpoints to git](https://dvc.org/doc/user-guide/experiment-management/checkpoints#adding-checkpoints-to-git) will squash the checkpoint commits making them not usable later.

We kind of already have the [Sharing Experiments guide](https://dvc.org/doc/user-guide/experiment-management/sharing-experiments) but it doesn't mention Checkpoints at all.

_Originally posted by @daavoo in https://github.com/iterative/dvc.org/issues/2769#issuecomment-912478244_

**Comment by jorgeorpinel** [comment]
Added as checkbox in https://github.com/iterative/dvc.org/issues/2769.
