### ISSUE TITLE
guide: params, metrics and plots metafiles

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2815]
We briefly cover those 3 types of files on the [`Project Structure -> Pipeline Files -> Stages` section](https://dvc.org/doc/user-guide/project-structure/pipelines-files#stages). 

I understand that they can be considered `stage`-related and thus belong on that page. 

However, it feels like the current info in each command reference (`dvc params`, `dvc metrics`, `dvc plots`) could be moved to the user guide, potentially extending it.

**Comment by jorgeorpinel** [comment]
Related to (or part of) https://github.com/iterative/dvc.org/issues/144#issuecomment-841960760

**Comment by jorgeorpinel** [comment]
Should these be tasks in https://github.com/iterative/dvc.org/issues/2911 since params, metrics and plots are mainly experiment tracking mechanisms?

**Comment by jorgeorpinel** [comment]
Hmmm, in fact this looks like a dupe of https://github.com/iterative/dvc.org/issues/2572 !
