### ISSUE TITLE
document pre-push hook

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#282]
https://github.com/iterative/dvc/pull/1951 introduces pre-push hook.
Document the change

**Comment by Naba7** [comment]
Is anyone assigned this? @efiop @shcheklein Can I be assigned this?

**Comment by shcheklein** [comment]
@Naba7 no, no one is assigned! Feel free to start on this. Let us know if you need any help :) Thanks!

**Comment by Naba7** [comment]
@shcheklein  @efiop I read the documentation for pre-push from SCM git but I can't find where to document pre-push as there is already https://dvc.org/doc/commands-reference/push . I took reference from https://dvc.org/doc/commands-reference/checkout , still can't figure out.

**Comment by shcheklein** [comment]
@Naba7 it should be part of this doc - https://dvc.org/doc/commands-reference/install
