### ISSUE TITLE
guide: Managing(?) Experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2844]
Converted to issue from #2752  <-- See text contents

- [ ] Combine and summarize the motivation text in the section index
- [ ] Finish "Handling" Exps guide (mainly about `exp show/compare`)
- [ ] Remove deep details from the command reference that can be moved here instead

Maybe also include (if natural)
- [x] https://github.com/iterative/dvc.org/issues/2736
- [ ] https://github.com/iterative/dvc.org/issues/2737

Other notes
- https://github.com/iterative/dvc.org/pull/2752#pullrequestreview-737794776
- https://github.com/iterative/dvc.org/pull/2752#pullrequestreview-737795264
- https://github.com/iterative/dvc.org/pull/2752#pullrequestreview-737795421

**Comment by jorgeorpinel** [comment]
Added to https://github.com/iterative/dvc.org/issues/2548 for now.

**Comment by iesahin** [comment]
The title can be

- organizing experiments
- operations on experiments
- managing results of experiments 
-

**Comment by jorgeorpinel** [comment]
> The title can be

@iesahin I thought we had discussed that it was better to keep the 2 guides (comparing and persisting) so as I just mentioned above, those 2 will cover everything. I'm not sure about the "Comparing" title BTW, but I'll comment about that on it's issue.

**Comment by jorgeorpinel** [comment]
Looks like we don't need this any more. @iesahin maybe check your original contents in https://github.com/iterative/dvc.org/pull/2752/files in case we still want to rescue anything. Thanks
