### ISSUE TITLE
add documentation for aliyun oss storage

### ISSUE THREAD

**Issue by nanaya-tachibana** [iterative/dvc.org#285]
Documentation for changes in [dvc#1961](https://github.com/iterative/dvc/pull/1961).

**Comment by sanidhyamangal** [comment]
Hello @shcheklein Can I work on this issue?

**Comment by shcheklein** [comment]
@sanidhyamangal absolutely, thanks!

**Comment by sanidhyamangal** [comment]
@shcheklein do I need to add docs in [remote add](https://dvc.org/doc/commands-reference/remote-add#options) ? or this would go somewhere else?

**Comment by shcheklein** [comment]
@sanidhyamangal yes, the biggest change is that file. There are a few place around the Markdown and JS that mention the list of supported remotes. Do the `git grep "SSH"` and see other places, like `pages/features.js` that we need to update. Thanks! :)
