### ISSUE TITLE
guide: Data Management

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2856]
UPDATE: https://github.com/iterative/dvc.org/issues/2856#issuecomment-1278366397

---

This is the plan for data management trail that focuses on:

- Adding data to DVC projects
  & Versioning data in DVC projects
- The cache (local)
- & [Shared cache](https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache) (external)
- Removing data from DVC projects
- \+ Creating remotes (link to config/remotes)
- & Sync with remotes
  See also https://github.com/iterative/dvc.org/issues/2866
- Accessing public datasets and data registries (get, import)
- External data topics (See https://github.com/iterative/dvc.org/issues/563#issuecomment-1198687900)
  + probably address https://github.com/iterative/dvc.org/issues/520

<details>

## Adding data to DVC projects

- Initialize a DVC repository and use `dvc add` to add files. 

- We'll assume MNIST data exist in a folder and will add it. 
 
## Versioning data in DVC projects

- Overwrite Fashion-MNIST data on top of MNIST and update the dataset.
- Go back and forth in Git history to get different datasets in the same folder.

## Creating remotes

- Add a Google Drive folder as a remote.

- Make it default

## Pushing to/pulling from remotes

- Push the cache to the remote we created
- Clone the repository to somewhere (e.g. ssh or local folder) 
- Pull the cache
 
## Accessing public datasets and registries

- Get the Fashion MNIST data from dataset-registry

## Removing data from DVC projects

- Remove certain folders from workspace
- Delete the corresponding cache files

</details>

UPDATE: start with a reorg, see https://github.com/iterative/dvc.org/issues/2856#issuecomment-1110477162 below (may be enough).

**Comment by dberenbaum** [comment]
👍 

The only thing I can think of that you might want to add is `import`/`update`.

**Comment by iesahin** [comment]
> Actually, `import`/`update` might not be necessary since this is GS. In fact, I think you could probably stop the GS doc after "Pushing to/pulling from remotes."

Let me try to write something with the above plan and we can see what's extra. I think "public repository access" may be a good selling point. I believe these documents are like "brochures" and some kind of advertisement. I'm just trying to touch as many points without much technicalities. 
@dberenbaum

**Comment by jorgeorpinel** [comment]
Like, related to the model lifecycle? I mentioned this in the PR (https://www.dominodatalab.com/solutions/model-management/) and it wasn't contested so I assumed I was correct but you guys are the experts! If it doesn't have a special meaning then it doesn't matter. But if it does users and search engines could get confused.

**Comment by jorgeorpinel** [comment]
Looks like we already have a GS page for basic data management in https://dvc.org/doc/start/data-and-model-versioning. Can you recap what are the main differences with this proposal @iesahin ? Thanks

If nothing major, we should probably reuse whatever is still relevant here to plan for a new Data Management GUIDE instead. Rel. https://github.com/iterative/dvc.org/issues/144#issuecomment-844711839

**Comment by jorgeorpinel** [comment]
Data Mgmt is simple enough that covering it in the Get Started and Command Reference has thus far been enough. But having a group of existing content under this "Category" could achieve some goals:

- Help reorg existing content (e.g. [Large Dataset Optimization](https://dvc.org/doc/user-guide/large-dataset-optimization), [Managing External Data](https://dvc.org/doc/user-guide/managing-external-data), etc.)

- Include Remote usage details? See https://github.com/iterative/dvc.org/issues/2866
Or should that be part of a Configuration guide? (rel. https://github.com/iterative/dvc.org/issues/340)

So just doing that reorg of existing content could be a good and quick first step, I think. Then we reconsider all the material proposed above. WDYT?

**Comment by jorgeorpinel** [comment]
re _Help reorg existing content_

Based on the OP here's what we currently have for all the topics mentioned:

> Adding data to DVC projects
& Versioning data in DVC projects

- Covered in https://dvc.org/doc/use-cases/versioning-data-and-models
- and intro-ed in https://dvc.org/doc/start/data-management/data-versioning 

> The cache (local)

- https://dvc.org/doc/user-guide/project-structure/internal-files and
- https://dvc.org/doc/user-guide/data-management/large-dataset-optimization#configuring-dvc-cache-file-link-type
\+ https://dvc.org/doc/command-reference/config#cache

> & Shared cache (external)

- https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache
  \+ https://dvc.org/doc/command-reference/gc#cleaning-shared-cache-or-remote
- https://dvc.org/doc/user-guide/data-management/managing-external-data#setting-up-an-external-cache

> Removing data from DVC projects

- https://dvc.org/doc/user-guide/how-to/stop-tracking-data
\+ https://dvc.org/doc/command-reference/remove, https://dvc.org/doc/command-reference/gc

> Creating remotes (link to config/remotes)
& Sync with remotes

- Intro-ed in https://dvc.org/doc/start/data-management/data-versioning#storing-and-sharing
- More info. in refs under https://dvc.org/doc/command-reference/remote

> Accessing public datasets and data registries (get, import)

- Intro-ed in https://dvc.org/doc/start/data-management/data-and-model-access
- Also covered in https://dvc.org/doc/use-cases/data-registry

> External data topics

- https://dvc.org/doc/user-guide/data-management/importing-external-data
- https://dvc.org/doc/user-guide/data-management/managing-external-data
\+ in refs e.g. https://dvc.org/doc/command-reference/add#example-transfer-to-remote-storage

**Comment by jorgeorpinel** [comment]
> Idea: Emphasize the value by contrasting typical/ ad hoc methods vs DVC project structures (before/after)

My only problem with this idea is that we should drive the value of the product and feature earlier than the user guide. This should be in use cases or in the Get Started if needed. OK to repeat in the UG as a quick summary as well. @shcheklein
