### ISSUE TITLE
guide: `--json/csv` examples in Listing/Comparing Experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2860]
I'll add an example with `jq` to the UG after testing it. 

_Originally posted by @iesahin in https://github.com/iterative/dvc.org/issues/2740#issuecomment-929304537_

**Comment by skshetry** [comment]
If https://github.com/iterative/dvc/pull/6647 gets merged, we'll be prettifying json by default unless you meant to use `jq` for filtering.

**Comment by jorgeorpinel** [comment]
What about `--show-csv`? Per https://github.com/iterative/dvc.org/pull/2740#issuecomment-916902358

**Comment by iesahin** [comment]
I believe JSON is supposed to be used by other commands. Some kind of filtering may be possible, e.g., experiments with a metric higher than a certain threshold.

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc.org/pull/2740#issuecomment-916902358

> I would prefer example outputs for both --show-json and --show-csv over a usage example, since what would be less obvious to users is the format of those JSON and CSV outputs

**Comment by jorgeorpinel** [comment]
> I believe JSON is supposed to be used by other commands

Yes, that's fine but CSV will also have some use cases (otherwise why does it exist) so let's include it too?

**Comment by iesahin** [comment]
There are now examples for these options in #2737

**Comment by jorgeorpinel** [comment]
Great! I think you mean https://github.com/iterative/dvc.org/pull/2862 though? Please link that PR to close this issue if so @iesahin. Thanks
