### ISSUE TITLE
ref: which `repro` options does `exp run` support?

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2861]
`dvc exp run` doesn't support all the options supported by `dvc repro` but the command reference gives this impression in the usage text. 

Need to research which options are supported by `dvc exp run` and list them explicitly. 

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/2861#issuecomment-936707876

**Comment by dberenbaum** [comment]
Let's start with the research. Then we can decide whether to add those options to `exp run` and/or to list only the supported options explicitly.

**Comment by jorgeorpinel** [comment]
> the command reference gives this impression in the usage text

I'm happy to change/remove that `[repro_options ...]` in the cmd reference but that's more of a core repo issue I think?

> Need to research which options are supported by dvc exp run

Are you saying the following is not correct?
"In addition to the following, dvc exp run accepts all the options in dvc repro, with the exception that --no-commit has no effect here."
_From https://dvc.org/doc/command-reference/exp/run#options_

**Comment by iesahin** [comment]
> "In addition to the following, dvc exp run accepts all the options in dvc repro, with the exception that --no-commit has no effect here."

Yes, I say this. At least `--glob` is not supported and won't be supported in the near future. https://github.com/iterative/dvc/issues/6457

Other options may not work and `dvc exp run` behaves differently from `dvc repro` in other cases. https://github.com/iterative/dvc/issues/6718

**Comment by jorgeorpinel** [comment]
OK sounds good @iesahin . Now, a spike usually has a date by which a decision will be taken and I see this is in https://github.com/orgs/iterative/projects/188 (closes in 2 days). If we're not expecting that full list by tomorrow let's unmark this "spike" and mark it `research` please.

I think we can also ask @dberenbaum to try to get this info (when possible) from the core team, so un-assigning you @iesahin . Thanks

**Comment by jorgeorpinel** [comment]
UPDATE: Marked `question` for now. Should we even move it to the core DVC repo?

**Comment by iesahin** [comment]
I believe `[SPIKE]` is for larger research, this one involves to test all `repro` options on `dvc exp run`. Will try to do this today. No need to transfer to the core. Thank you @jorgeorpinel

**Comment by iesahin** [comment]
```
dvc exp run --pull
Verifying data sources in stage: 'data/images.tar.gz.dvc'
ERROR: failed to reproduce 'data/images.tar.gz.dvc': missing data 'source': data/images.tar.gz
```

**Comment by iesahin** [comment]
```
dvc exp run --downstream
ERROR: failed to reproduce 'dvc.yaml': [Errno 2] No such file or directory: '/home/iesahin/github.com/iterative/ede-5/data/images'
```

`dvc repro --downstream` works though.

**Comment by iesahin** [comment]
I'm not sure if `--pull` works.

**Comment by jorgeorpinel** [comment]
Discussed in meeting: probably best to list the options separately in each page.

**Comment by jorgeorpinel** [comment]
Maybe @dberenbaum or @pmrowla can confirm on the 3 pending check boxes above so we can decide what to do here? Specifically: does `exp run` support `--force-downstream/downstream/pull` ? Thanks

**Comment by pmrowla** [comment]
`--downstream` and `--pull` should work the same way that they do in `dvc repro`

But `--downstream` is broken in `repro` in some scenarios, (https://github.com/iterative/dvc/issues/3556) so those same issues w/downstream stage collection will also affect `exp run`

**Comment by dberenbaum** [comment]
Outside of the issue @pmrowla mentioned, I just tested all those options, and they all seem to work the same as in `repro`, so I have checked the boxes.

**Comment by iesahin** [comment]
I think we can wait for #6291 now.

**Comment by dberenbaum** [comment]
@iesahin @jorgeorpinel Why is this closed? Don't we still need to update https://dvc.org/doc/command-reference/exp/run to explicitly list the options supported there and in repro?

**Comment by pmrowla** [comment]
It's already documented in the options section

> In addition to the following, [dvc exp run](https://dvc.org/doc/command-reference/exp/run) accepts the options in [dvc repro](https://dvc.org/doc/command-reference/repro) except for --glob, --no-commit, and --no-run-cache.
