### ISSUE TITLE
why is updater returning 2.6.4 as the latest version?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2869]
```console
$ curl https://updater.dvc.org | jq
{
  "version": "2.6.4",
  "packages": {
    "linux": {
      "deb": "https://github.com/iterative/dvc/releases/download/2.6.4/dvc_2.6.4_amd64.deb",
      "rpm": "https://github.com/iterative/dvc/releases/download/2.6.4/dvc-2.6.4-1.x86_64.rpm"
    },
    "windows": {
      "exe": "https://github.com/iterative/dvc/releases/download/2.6.4/dvc-2.6.4.exe"
    },
    "osx": {
      "pkg": "https://github.com/iterative/dvc/releases/download/2.6.4/dvc-2.6.4.pkg"
    }
  }
}
```

This breaks notifying mechanism in the DVC. I see that it was updated in https://github.com/iterative/dvc.org/pull/2837.

**Comment by iesahin** [comment]
@rogermparent @julieg18

**Comment by julieg18** [comment]
What is `https://updater.dvc.org`? This is my first time hearing of it 🤔

**Comment by shcheklein** [comment]
We should have a CI check for this as well as we did for Download link checks.

**Comment by casperdcl** [comment]
FYI workflow file: https://github.com/iterative/dvc.org/blob/master/.github/workflows/update.yaml

**Comment by rogermparent** [comment]
I've never heard of `updater.dvc.org` either, nor do I know where to go to work on it.

**Comment by casperdcl** [comment]
CC @duijf

**Comment by efiop** [comment]
updater is always updated the last, once all packages of all types are available (e.g. dvc.org only waits for pip and binaries, but not for conda). And we had some problems with conda that got sorted out last week, so didn't update it yet 🙁 Merged now https://github.com/iterative/lambda-latest-version/pull/16 though. I think this could be closed now?

**Comment by shcheklein** [comment]
@efiop thanks! Out of curiosity do we update it manually (make a PR and it gets to AWS)?

**Comment by efiop** [comment]
@shcheklein PR is automatically created, but manually merged and only then automatically deployed to aws.
