### ISSUE TITLE
Improving issue labels and labeling process

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2924]
It looks our labeling system needs some overhaul after the recent _improvement._ There seems to be no system behind the labels and we duplicate or add some irrelevant info. 

![image](https://user-images.githubusercontent.com/476310/137122336-5569eac3-fcda-4483-9cef-b7ea02f96b2f.png)

Do we really need these? `content` tag has 108 open issues (out of 200 total.) Others are duplicating the info in the title. 

`research`, `question` and `discussion` are almost identical semantically. 

![image](https://user-images.githubusercontent.com/476310/137123941-d7c6d41d-d7a5-4b57-9719-0625c8f017ec.png)

![image](https://user-images.githubusercontent.com/476310/137122948-c76a9765-3d7d-488f-9949-eeefa9610ad8.png)

![image](https://user-images.githubusercontent.com/476310/137122996-03c503ad-2360-4ae8-be1d-f53620251508.png)

We now have `dvc` and `dvclive`.

![image](https://user-images.githubusercontent.com/476310/137123137-3d7a04bb-1b40-4849-98c1-e27ceb4115c3.png)

![image](https://user-images.githubusercontent.com/476310/137123200-ec99a86b-4278-43da-948d-f7bd49b6dec2.png)

We also have `enhancement` as if other issues don't enhance anything. We have 108 `enhancement` issues, and 78 of these also have `content` label. 

![image](https://user-images.githubusercontent.com/476310/137123336-a129dbd7-aea3-4235-b91d-3ef7c20cafa3.png)

And those that don't have `content` look they are related to content as well. 

![image](https://user-images.githubusercontent.com/476310/137124730-f55b783b-793d-49bd-b187-fd998b0b45c9.png)

We also have `website`, `eng-blog` and `eng-doc` labels: 

![image](https://user-images.githubusercontent.com/476310/137124218-5f63c680-2af9-401b-809e-7d74b5000852.png)

![image](https://user-images.githubusercontent.com/476310/137124255-75514f35-b4d9-40c7-8f9e-717a9b680ea1.png)

![image](https://user-images.githubusercontent.com/476310/137124305-794f3da0-21d9-43d6-b887-adf0cf70fdb2.png)

I think we can do better than this. 

## Some principles I have in mind

- No duplicate/overlapping information
- No labels without clear semantics. We should be precise and labeling shouldn't take much effort. If you're thinking "which labels are suitable to this?", then we have some unclear semantics somewhere. 
- A label used half of the time is worse than not using it at all. If I click on a label and not sure that it doesn't list all relevant issues, it's worse than not having any such label. 
- Labels for aspects: `status`, `priority`, `size`, `team`
- Each issue should have 1 label from each of the aspects.
- Extra labels _only_ as needed. 

So, let me propose this: 

- Remove `content` and its siblings. 
- Remove `enhancement`. Its semantics is not clear, it may mean content enhancement, website enhancement, DVC core enhancement, etc. 
- Merge `question`, `research`, `discussion` in a single `status: research` label. 
- Create new status labels: `status: triage` (default), `status: deferred`, `status: research`, `status: draft`, `status: reviewing`, `status: waiting core`, `status: abandoned`, `status: wontfix` (Shades of green)
- Priority issues should be limited in number. We should have 2-3 `p1` and 5-10 `p2` issues for the docs team. (Shades of red)
- Size labels: `size: epic`, `size: venti`, `size: grande`, `size: tall`, `size: short`. (Shades of blue)
- Team: `team: docs`, `team: web`, `team: core`, `team: studio`, `team: dvclive`, `team: devrel` (Shades of yellow)

I can provide precise definitions for these, e.g., a `size: short` issue is not expected to have more than 20-30 lines of change, `size: grande` can contain 2-3 `tall` or `short` issues as steps, etc. 

When a new issue arrives, the maintainer decides who will fix this (`team: *`), the status of it (`deferred`, `research`, `wontfix`), the approximate size (`size: *`) and the priority if it should be done in the short term. 

All issues will be required to have a `team:`, a `status` and a `size` label. We can also force for the priority if we add a `p: sometime` kind non-priority label. So when we look at the list, we'll be able to see who's supposed to work on what and in which order and how long it's supposed to take approximately. 

WDYT? @jorgeorpinel @shcheklein @casperdcl @dberenbaum @daavoo

**Comment by casperdcl** [comment]
meta-comment: the new GH project boards seem to solve all the problems discussed above.

- can switch between *kanban* <-> table
- adds separate priority column
  - making `pN` labels redundant
  - can use boards API to convert all `pN` labels to board priorities (of course this means priorities become private/invisible to non-org members)
- adds target date column
- adds customisable columns (which team, notes, milestone, reviewers, etc)
- adds customisable grouping (*kanban* only groups by status)
  - can have save different views (e.g. group by priority, group by assignee, etc.)

**Comment by shcheklein** [comment]
> but then again, do we really need project management stuff to be publicly visible?

yes, in case of open-source we want to keep them visible -- I hope boards will be made public soon, though?

I feel a bit uneasy to have a list of issues completely stripped from any attributes. Also, with a board it means I now have to go to the board to slice and dice. Not saying that board doesn't have its value, feeling is it's not a replacement for basic labels, it's an expansion on top to do product management/project management on different level.

good question though, curious about other opinions on this, or what even GH folks have in mind with these two different systems.

**Comment by iesahin** [comment]
> * can switch between _kanban_ <-> table



> 
> * adds separate priority column
>   
>   * making `pN` labels redundant
>   * can use [boards API](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects) to e.g. convert all `pN` labels to board priorities
> 

I think this is not good. They may have to do this because `p1` etc have no special sorting capability, but if we can't see this as easily as the issue labels, IMHO it's not worth it. 

> * adds target date column

I wouldn't use this. 

> 
> * adds customisable columns (which team, notes, milestone, reviewers, etc)
> 

We could use these. 

> * adds customisable grouping (_kanban_ only groups by status)
>   

and this

>   * can have save different views (e.g. group by priority, group by assignee, etc.)

and this. 

As a matter of principle, I prefer older methods and tools to newly conceived ones. Also, I think the most important question we have is _the definitive place everyone tracks the work._ I'd want a single bookmark that I can track all my issues, and other work. 

Another point is education. The simpler the tool, the shorter it takes onboarding new people.

**Comment by iesahin** [comment]
> yes, in case of open-source we want to keep them visible -- I hope boards will be made public soon, though?
> 

I'd like everything to be made public as much as possible. A 16 y.o. asking a question might show a flaw in my reasoning and having more in the public invites more people to discussion.


> I feel a bit uneasy to have a list of issues completely stripped from any attributes. Also, with a board it means I now have to go to the board to slice and dice. Not saying that board doesn't have its value, feeling is it's not a replacement for basic labels, it's an expansion on top to do product management/project management on different level.
> 

I feel the same. 

> good question though, curious about other opinions on this, or what even GH folks have in mind with these two different systems.

I think labels/tags are almost universal now. Boards etc. are too software/technology dependent, and I feel we should stick to universal tools as much as possible.

**Comment by iesahin** [comment]
> Do we want to introduce `type/research`, `type/discussion`, `type/question`, `type/bug`, `type/story (or epic)`? It feels like it's a different dimension as well compared to status?

Will these change anything in processing the issue?

**Comment by iesahin** [comment]
The basic question in labels is asking "will these labels modify (or help) processing the issue?" Adding `content-start`  label to an issue with the title `start: Add another section` doesn't change anything while processing it, while `team/web` label says "this issue needs some work regarding the website/gatsby/etc, so I may skip (or deal) for the time being."

**Comment by shcheklein** [comment]
> area/... seems rather static.

they are static. We need them to slice issues quickly. It helps a lot (e.g. find everything p1 on doc engine).

**Comment by iesahin** [comment]
> Also, assignments work - you could assign `iterative/dvc` for example.

Am I missing something, or are we not talking about the same kind of assignments here?

![image](https://user-images.githubusercontent.com/476310/138075744-8b3642e5-e8bc-4384-8df5-030bb6526f75.png)

**Comment by iesahin** [comment]
> Labels are important for me for navigation, structuring things and being able quickly slice and dice and find the appropriate backlog of things.

If we need labels for automation, that's fine, but we should automate those. 

I've added `content/start` to all issues with titles having `start:`

```
for iid in $(gh issue list --state all --limit 1000 | rg 'start:' | cut -f 1) ; do gh issue edit ${iid} --add-label 'content/start' ; done
```

Manually setting these labels are error-prone and duplication of work. We can define automated rules for issues like this and I can write a few scripts and cron jobs for setting labels instead of trying to fix them for each new issue.

**Comment by iesahin** [comment]
Added some navigation labels to the proposal. We can increase the number of these as soon as there are rules behind them. 

https://github.com/iterative/dvc.org/wiki/Labels-(v2)#automated-navigation-labels

**Comment by iesahin** [comment]
>  I haven't see the workflow when you assign a ticket to a team, then to a person. 

Assigning to teams feels easier to me. I don't know the priorities and availability of a person, teams are better even if they have a single member. It's "dynamic dispatch" instead of "static dispatch", which looks softer in organizational terms. I don't feel it's right to assign a ticket to Dmitry, but I can _assign_ by labeling it `team/exec` and you, Dave, Dmitry (or who feels themself executive) can look into it when you have time. This is true for most of the other people, e.g., I don't know who is looking into docs related issues in the Studio team, I can ask Tapa about it, but she'll probably want to assign it to another person. This usually takes much longer than adding a label `team/studio` to an issue. 

It doesn't have to be `team/*`, it can be something (1) dynamic (unlike `area/*`), (2) mutually exclusive (so that only one from these kind will be found in an issue.) `who/exec` is possible, we can have `who/*`, `what/*` (instead of `type/*`), `where/*` (instead of `status/*`) `howbig/*` (instead of `size/`) for uniformity, but the current prefixes seem easier to understand to me.

**Comment by iesahin** [comment]
Added more `content/` labels according to the rules in https://github.com/iterative/dvc.org/wiki/Labels-(v2)#automated-navigation-labels 

We have around 100 non-classified open issues.

**Comment by iesahin** [comment]
After discussing with @jorgeorpinel, I believe we can postpone this discussion to the next year.

**Comment by jorgeorpinel** [comment]
Sorry, I didn't have the bandwidth to keep up with this and I see we've adopted something similar to what the dvc repo has (I'm OK with that). Here are some comments for what it's worth.

---

> Labels are important for me for navigation, structuring things and being able quickly slice and dice and find the appropriate backlog of things.

This is what I use them for the most. And even if we could automate that somehow (@iesahin), triage is part of the process too.

> Process is also important- that's what status is for.

Well, navigation is also part of the (planning) process. Statuses are for the execution part of the process I guess. TBH I don't use status labels much for issues, since execution is on our boards.

> it's duplication if we expect prefixes, see above ^^.

@iesahin and I discussed this and we think it's fine to have this duplication because it's still a better way to structure issue/PR titles + you can't see labels on other views e.g. regex issue title search or platforms like VSCode GH extension so we can keep prefixes or other naming conventions for internal convenience.

Let's just make sure they're consistent for now... (I'll review the wiki pages ASAP ⌛)
