### ISSUE TITLE
start: integrate (updated) params/metrics/plots to Experiments Trail

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2925]
We need to update https://dvc.org/doc/start/metrics-parameters-plots after the Experiments Trail.

Related #2479 
Related #2496 
Related #2574 

### Points to discuss

- The current document is a continuation of the pipelines document. Instead, it needs to be built on Experiments. 
- Code blocks with `dvc run` will be rewritten in `dvc stage add` and `dvc exp run`. Or, as the train stage is already there, we can just skip these "stage" discussions and move to params and metrics, plots within experiments. 
- How deep should we go into plotting? 
- It's possible to move to DVCLive and checkpoints quickly with plots and metrics. 

### Tentative Plan

- [ ] start: Add a `model.dense_units` parameter to Experiments Trail in a later section to show how to add params
- [ ] start: Add a section about metrics to the Experiments Trail
- [ ] start: Add a section about plots and show how to generate plots from output files

**Comment by shcheklein** [comment]
Before we jump into coding (writing), could we outline here some specifics:

- new section names
- their structure
- summary of the content (specially intro, how they are connected as a story, etc)

Also, what about `dvclive`? We need to cover that part as well. 

If we are removing metrics and plots from the `data management` trail? We need to cover visualization I guess? Does it makes sense to do here or in a separate trail (Model Management?).

**Comment by shcheklein** [comment]
@iesahin I see some point that you added to the existing document, but they do not answer (at least I can't figure out this, maybe I'm missing something) questions I had. I would start with some very basics - where do we write this, how it is connected to the other parts, what do we cover.

**Comment by jorgeorpinel** [comment]
Hi. What is `status: creating`? Only this issue has that label. Is it needed?

**Comment by iesahin** [comment]
It was about to specify the content that are being written. I'm deleting that.
