### ISSUE TITLE
How to generate dynamic params from a prior stage

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2927]
See https://github.com/iterative/dvc/issues/6805 for context:

> I have faced an issue when I need to repro pipeline when new week starts - because new week brings more data to fit the model on. However, it is turned out that dvc natively does not support such cases when a parameter is a result of some python code (for example x = pandas.Timestamp.today()). As a result, to refit the model automatically I need whether to code some side custom solution which basically follows the same logic dvc does or to pass -f flag manually, which makes this task non-automatic. So it would be very nice if such feature support is added!

We should document how a stage could be used to generate the parameters for these scenarios.

**Comment by jorgeorpinel** [comment]
> > I need whether to code some side custom solution which basically follows the same logic dvc does or to pass -f flag manually, which makes this task non-automatic
>
> We should document how a stage could be used to generate the parameters for these scenarios.

@dberenbaum it's unclear what this process is exactly, could you provide steps?

And maybe it can be an example for now, along or instead of https://dvc.org/doc/command-reference/params#examples-python-parameters-file

**Comment by daavoo** [comment]
Not sure if this is fully related to the original use case, but I added an example dataset that can be updated periodically by using `dvc exp run -S` to update params based on the date. 

In my case I run `dvc exp run -S until=$(date +'%Y/%m/%d')`) using `date` from Github actions:

https://github.com/iterative/dataset-dvc-issues/blob/main/.github/workflows/fetch_issues_weekly.yaml#L27

**Comment by dberenbaum** [comment]
@jorgeorpinel Is there a way to label backlog/low priority issues? I don't think it's a priority right now, but I didn't want to completely lose track of it.

**Comment by jorgeorpinel** [comment]
Most issues are backlog 😅 unless they have a priority label. We do have p2 "nice to have" but even that is higher than no priority I suppose. TBH we don't use them very consciously so far.

**Comment by dberenbaum** [comment]
Closing as stale.
