### ISSUE TITLE
docs: apply more language tabs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2939]
> Follow up to https://github.com/iterative/dvc.org/issues/759

Per tabs system introduced in https://github.com/iterative/dvc.org/pull/2914

### Usage

```md
<!-- /some/page.md -->
<toggle>
<tab title="Foo">

some text about Foo

</tab>
<tab title="Bar">

some text about Bar

</tab>
</toggle>
```

- ~~Put this usage (and other special features) in https://dvc.org/doc/user-guide/contributing/docs ? Coincidentally, we could use tabs to list the special feats~~ UPDATE: https://github.com/iterative/dvc.org/issues/3506

---

<a name="ideas-places"></a>
#### Main use

- [ ] Upgrade Linux-specific terminal/shell or code samples to cover Windows too.
- [ ] Installation page sections https://dvc.org/doc/install
- [ ] #3311 
- [ ] Throughout for params in different formats (guides, refs)
- [ ] Throughout for metrics/plots in different formats (guides, refs)
- [ ] Throughout for some `--json/csv/md` options (guides, refs.)

#### Other ideas (exploratory)

- [ ] Throughout (some) examples of https://dvc.org/doc/user-guide/project-structure/pipelines-files to show writing dvc.yaml vs. using `stage add` -- +& related guides/refs. ([ex](https://dvc.org/doc/user-guide/how-to/add-deps-or-outs-to-a-stage#example))
- [ ] To show different ways for [Registering checkpoints](https://dvc.org/doc/user-guide/experiment-management/checkpoints#registering-checkpoints-in-your-code) (currently only DVCLive is shown, not signal files/`make_checkpoint()`).
- [ ] Try in Examples of https://dvc.org/doc/user-guide/external-dependencies and https://dvc.org/doc/user-guide/managing-external-data (and https://dvc.org/doc/user-guide/contributing/core#testing-remotes)
- [ ] Try in https://dvc.org/doc/user-guide/what-is-dvc#core-features and/or https://dvc.org/doc/user-guide/related-technologies (pages could  be merged)
- [x] ~Try for the feature highlights in https://dvc.org/doc/use-cases/ci-cd-for-machine-learning -- make the page shorter/cleaner~
- [ ] Try in subsections of https://dvc.org/doc/use-cases/data-registries#using-registries
- Maybe for Experiment Tracking tool comparison (instead of table)
- Note: may be useful for #2866
- ~~Maybe `exp list` vs `exp show` or `exp show` vs `exp diff` in [Comparing Exps](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments)? Per needs of #2995~~
- Maybe for `.dvc/tmp/` subfolders in https://dvc.org/doc/user-guide/project-structure/internal-files
- Maybe Modify vs Update sections in https://dvc.org/doc/user-guide/how-to/update-tracked-data
  And metafiles in https://dvc.org/doc/user-guide/how-to/merge-conflicts
- Maybe GC project vs service accounts in https://dvc.org/doc/user-guide/setup-google-drive-remote
- Maybe file linking methods in https://dvc.org/doc/user-guide/large-dataset-optimization

**Comment by daavoo** [comment]
I see https://github.com/iterative/dvc.org/pull/2877 (adding example outputs for each) as a good candidate for this format

**Comment by jorgeorpinel** [comment]
Note: I updated the description with the list I came up with. Forgot to let you all know!

> Try for the feature highlights in https://dvc.org/doc/use-cases/ci-cd-for-machine-learning

WDYT @casperdcl ?

**Comment by jorgeorpinel** [comment]
> exp list vs exp show in https://dvc.org/doc/user-guide/experiment-management/comparing-experiments? Rel. #2995

WDYT @iesahin ?

**Comment by shcheklein** [comment]
What about Windows/Linux for code snippets - do we have this item in the list?

(seems the most obvious in DVC case)

**Comment by jorgeorpinel** [comment]
> What about Windows/Linux for code snippets

Good point. I didn't list that since we try to have pretty generic console samples but I'm sure lots of them are still very POSIX/GNU-specific. Added a checkbox to review them and apply tabs where/if needed.

**Comment by jorgeorpinel** [comment]
Cc @tapadipti any places you think this could help condense https://dvc.org/doc/studio pages? Thanks

**Comment by iesahin** [comment]
> > Maybe `exp list` vs `exp show` or `exp show` vs `exp diff` in [Comparing Exps](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments)? Per needs of #2995
> 
> WDYT @iesahin ?

These commands are not "identical" in the sense that when you learn/use one, the other becomes obsolete. The use cases that we can employ these commands alternatively are limited. Also, our hidden content in other places causes confusion sometimes. I don't want these to be hidden behind tabs.

**Comment by jorgeorpinel** [comment]
OK let's just keep it in mind as a possible way to make some sections shorted AFTER each command has been introduced and only if different commands are used as precise alternatives for some task/example.

**Comment by iesahin** [comment]
IMO, we should limit tabs to:  
- Same commands in different shells/OSes
- Same function in different languages/frameworks (e.g. DVCLive/checkpoints usage in Keras/PyTorch/...)

It's rare to have such uses in basic DVC commands, e.g., it's possible to get the list of remote experiments with ˋdvc exp showˋ but we normally use ˋdvc exp listˋ for this.

**Comment by tapadipti** [comment]
> Cc @tapadipti any places you think this could help condense https://dvc.org/doc/studio pages? E.g. any lists of anything that represent alternatives for some end could be candidates. Thanks

I just skimmed through the Studio docs, and currently I do not see sections with alternates that are suitable for placing in tabs, coz the Studio commands/instructions are the same across all platforms/OSes/etc. However, I think that as the doc evolves, there will be sections that can utilize tabs. Thanks @jorgeorpinel for tagging me.

**Comment by jorgeorpinel** [comment]
> IMO, we should limit tabs to...

OK. I'd generalize this rule of thumb to something you mentioned elsewhere @iesahin : Any list of alternatives where the reader only needs to see one (a clear favorite) to get the point. This probably means code/terminal examples 90% of the time at least but who knows, other situations may apply.

I updated the [list in the description](#ideas-places) per this rule.

**Comment by shcheklein** [comment]
Should we put summary of this into the docs contributing guide (also update it to describe how do these tabs in the Markdown)?

**Comment by jorgeorpinel** [comment]
That is also a check box in the description @shcheklein 😬

**Comment by jorgeorpinel** [comment]
> Throughout Get Started code snippets (e.g. https://github.com/iterative/dvc.org/pull/3215)

Cc @iesahin
