### ISSUE TITLE
Website: Landing page release video positioning - Light Weight Experiments

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#2949]
We need to figure out how we should add the explainer videos for releases to the landing page of the corresponding website for the release for a period of time.

Should we:

1. Just put where the current video is?
2. Put higher up on page in some kind of New! block?
3. Other ideas

We will be trying this out for the first time for the **November 17th** Release of Lightweight Experiments - (which will likely be re-named) So that's the deadline.

**Comment by yalozhkin** [comment]
@jendefig @julieg18 please take a look:

![image](https://user-images.githubusercontent.com/454947/139877266-4ddb2ee9-84e0-4573-aa6e-99be3f7013d4.png)

**Comment by dberenbaum** [comment]
To provide some more context, I think the reason to consider adding this video to the landing page is because it's a high-level concept video, not because we want to be able to show what's new with each version of DVC. That could be interesting, but I don't think it's the right focus for now.

We need to refresh the whole landing page with updated content, but I don't think we can do it before the release. Other options:
* Have the current video and new video available in the same area for now.
* Wait until we can refresh the landing page to add the new video.
* Other ideas?

**Comment by rogermparent** [comment]
> Have the current video and new video available in the same area for now.

Maybe we could have multiple videos in selectable tabs? It wouldn't put the new video as "front and center" as I'm sure we'd like, but it would probably be easy to slip into the design and we wouldn't have to worry about making lots of extra room.

**Comment by jendefig** [comment]
> > Have the current video and new video available in the same area for now.
> 
> Maybe we could put tabs above the current video that allow for selecting different videos? It wouldn't put the new video as "front and center" as I'm sure we'd like, but it would probably be easy to slip into the design and we wouldn't have to worry about making lots of extra room.

The tab idea is interesting, but I think in this case per @dberenbaum's comments, we would want the new video to show first and tab back to the existing?

**Comment by yalozhkin** [comment]
> To provide some more context, I think the reason to consider adding this video to the landing page is because it's a high-level concept video, not because we want to be able to show what's new with each version of DVC. 

Well, as I see it now:
* The idea about videos is not just a connection between version history and the landing page;
* A video is a knowledge content that would help people to discover new features (or promote existing ones);
* Publishing new has no strict schedule.

Am I right?

In this case, **using a dedicated section** like _Did you know?_ with all the videos would work better than just a single touchpoint button _What's new_.

**Comment by jendefig** [comment]
> In this case, **using a dedicated section** like _Did you know?_ with all the videos would work better than just a single touchpoint button _What's new_.

I like the idea of "*Did you know?*"

**Comment by dberenbaum** [comment]
> Publishing new video has no strict schedule.

Let's run that by @dmpetrov. I don't have authority to say that 🤣 .

**Comment by jendefig** [comment]
@yalozhkin @rogermparent @dberenbaum 
New change per our meeting to day with @dmpetrov, we need to put the video in the hero on November 18th. (release date as of now, may change, but we are doing our utmost to keep it there).  It should stay there for a week.  If we can make it perfect, great!  If not, that's ok too, we will only keep it there for a week.  The goal is to drive traffic in the first week and it needs to be in the hero. 

Also like the floating button.  Let's use this too and it will direct to the [blog post](https://github.com/iterative/dvc.org/pull/2979) @dave is writing.

**Comment by dberenbaum** [comment]
To add to what @jendefig said, it would be great to have the hero for Nov 18th and the floating button if possible.

The dedicated section is still something we want, but that can come later.

**Comment by jorgeorpinel** [comment]
Are we set on 2.8.3? What about a good minor version bump i.e. 2.9 @dberenbaum ? Just a thought

**Comment by dberenbaum** [comment]
I leave version numbers to @efiop usually 😄 . What do you think? Is it mentioned anywhere, or does it otherwise make a difference to users?

**Comment by jorgeorpinel** [comment]
Looks nicer/ Makes more sense IMO if we're making noise about the release

![image](https://user-images.githubusercontent.com/1477535/141355819-7ed8a5fb-24c7-4e74-b3f2-f2ea21fccb8c.png)

**Comment by jendefig** [comment]
@yalozhkin @julieg18 Checking in on this.  What's the status?

**Comment by daavoo** [comment]
> Are we set on 2.8.3? What about a good minor version bump i.e. 2.9 @dberenbaum ? Just a thought

The blog would be about the lightweight experiments (not about any other DVC features that might be present in a release ) so, does the "product  release" need to be associated with a "semantic versioning release" number? 

Couldn't just use some git tag `i.e. Lightweight-Experiments` as an alias for referencing (if it's really needed to be tracked in git history).

**Comment by yalozhkin** [comment]
@julieg18 @jendefig created several variants for implementation:

* A dedicated section with multiple videos somewhere on the page
* Just a single video on the hero section instead of the graphics
* Multiple videos on the hero section
* A single video in the popup opened from the bottom left button

![image](https://user-images.githubusercontent.com/454947/141520848-431287f9-d4da-4dd4-85b7-6ce902f20b36.png)

- [ ] Could you please discuss, pick one variant @jendefig 
- [ ] Also, I think you can start coding the desktop @julieg18 
- [ ] On the next design iteration, I will assemble tablet/mobile views for the selected variant @yalozhkin 

Figma: [project](https://www.figma.com/file/3tt5YlGb4rwdptxMq9x54O/dvc.org-website?node-id=13%3A253) file

**Comment by dberenbaum** [comment]
> The blog would be about the lightweight experiments (not about any other DVC features that might be present in a release ) so, does the "product release" need to be associated with a "semantic versioning release" number?
> 
> Couldn't just use some git tag `i.e. Lightweight-Experiments` as an alias for referencing (if it's really needed to be tracked in git history).

Agree that the release doesn't have to be closely associated with a version number, but we will at least be using `dvc exp init`, so it might be useful to at least say this feature is available in DVC>=2.9.

@yalozhkin I don't think it's worth putting the version number in the floating button.

**Comment by dberenbaum** [comment]
@yalozhkin Based on discussions about the release, I vote for the single-video hero + modal for now, and then we can revisit and take them down or change it after a few weeks. I think the dedicated section will be the way to go when we redesign the website.

**Comment by jendefig** [comment]
> @yalozhkin Based on discussions about the release, I vote for the single-video hero + modal for now, and then we can revisit and take them down or change it after a few weeks. I think the dedicated section will be the way to go when we redesign the website.

I agree with @dberenbaum ➕

**Comment by rogermparent** [comment]
Regarding the modal, are we thinking of having it appear on every page, or just on the landing page? My assumption from modal + hero is that we do, but I'd just like to confirm since that will change the development process a bit.

**Comment by dberenbaum** [comment]
I think just the landing page is enough. Don't want to be so aggressive as to be annoying. It just gives users a way to see it without scrolling.

**Comment by jendefig** [comment]
@julieg18 @yalozhkin We have more time on this now.  We have had to move the Release Date to November 30th past Thanksgiving as the video won't be ready in time for the 18th.  So we should plan to have this ready on the 29th.

**Comment by yalozhkin** [comment]
Created a standalone [Figma spec](https://www.figma.com/file/3tt5YlGb4rwdptxMq9x54O/dvc.org-Hero?node-id=51%3A1784) for the video in the hero only:
![Uploading image.png…]()

@jendefig @julieg18 @dberenbaum @rogermparent

**Comment by jendefig** [comment]
Looks great @yalozhkin!  So am I correct in understanding that these are desktop, tablet, and two mobile views?

**Comment by dberenbaum** [comment]
Looks good @julieg18! I added a couple comments to the PR.

**Comment by yalozhkin** [comment]
The responsive states:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/454947/143900212-e485c6b2-b0b6-4eda-b445-43c0a643c780.png">

The same Figma [project](https://www.figma.com/file/3tt5YlGb4rwdptxMq9x54O/dvc.org-Home?node-id=51%3A1784).
