### ISSUE TITLE
how-to: update tracked files inside tracked directories

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2952]
[How to Update Tracked Data](https://dvc.org/doc/user-guide/how-to/update-tracked-data) currently focuses on single files and it would be nice to extend the examples to cover similar scenarios when the user wants to `Modifying content` / `Replacing files` targeting files inside a tracked directory.

**Comment by daavoo** [comment]
> Have you noticed users having this question in support channels?

Yes, I have.

**Comment by jorgeorpinel** [comment]
Merging into https://github.com/iterative/dvc.org/issues/3297
