### ISSUE TITLE
ref: clarify about types of metrics/plots

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2956]
> Follow up to https://github.com/iterative/dvc.org/pull/2839#pullrequestreview-785065676

Both the [metrics](https://dvc.org/doc/command-reference/metrics#types-of-metrics) and [plots](https://dvc.org/doc/command-reference/plots#types-of-metrics) cmd refs. explain 2 types of "metrics" (metrics and plots) -- done to to keep both references connected.

Calling plots a kind of metric is [already confusing](https://github.com/iterative/dvc.org/issues/1442). Furthermore, in #2839 the concept of "2 types of plots files" was introduced (data series rendered with Vega vs. arbitrary image files) to [the latter](https://dvc.org/doc/command-reference/plots#description), which may be confusing.

- Also, the [plots usage block](https://dvc.org/doc/command-reference/plots#synopsis) needs wrapping to avoid scroll

  ![image](https://user-images.githubusercontent.com/1477535/139963190-c7c8ec0f-3ae2-47a0-92a1-dc63fea64398.png)

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/2956#issuecomment-1081481662

**Comment by jorgeorpinel** [comment]
Maybe we need to put the types of metrics in a proper metrics/plots guide and not explain the concepts in the ref...

@dberenbaum do you think we the core team should address this for now, or plan for a guide? Thanks

**Comment by jorgeorpinel** [comment]
> why don't we decide how to describe them here
I don't think we should describe any kind of plots as metrics.

OK in this case we mainly have to edit the command refs. for both [metrics](https://dvc.org/doc/command-reference/metrics) and [plots](https://dvc.org/doc/command-reference/plots), and unlink them (don't call plots metrics).

Then we need to incorporate this approach to https://github.com/iterative/dvc.org/issues/2925
Cc @iesahin 

Finally, to consider it as well for https://github.com/iterative/dvc.org/issues/2572

**Comment by iesahin** [comment]
I have separated plots from metrics/params to describe them more independently in https://www.notion.so/iterative/Visualization-and-DvcLive-6feae9d35b5b430e8eefa7cf18f62638 

A _visualization_ section can describe plots as CSV files or plots as images, as you see fit.

**Comment by jorgeorpinel** [comment]
> we mainly have to edit the command refs. for both metrics and plots, and unlink them (don't call plots metrics)

Should we expect a PR from the core team on this? Or do we consider it docs work as the feature is already documented (in a way we don't love).

**Comment by dberenbaum** [comment]
We need to actually update some of the help text in the core repo, and then to update the command ref. So at least some of it needs to happen from the core team, and then we can see whether it makes sense to have the docs team take over some of it. @pared Do you want me to create an issue and/or PR in the core repo, or do you want to do it yourself?

**Comment by dberenbaum** [comment]
@pared Reminder on this issue. Could you take a look at updating the core help text for plots?

**Comment by jorgeorpinel** [comment]
Thanks for the follow-up!

**Comment by pared** [comment]
Sorry, assigning to myself, will try to handle it this week.

**Comment by dberenbaum** [comment]
Waiting on https://github.com/iterative/dvc/issues/7086

**Comment by jorgeorpinel** [comment]
Migrating main points from https://github.com/iterative/dvc.org/issues/1442:

> we could just skip this explanation altogether and only call metrics metrics, and plots plots.
Why even merge these 2 concepts into one? ... the format requirements for each kind of file are very different.

> We need to come up with clear separation.

> even when plots are metrics technically. We just probably don't need to stress that
The same overlap exists between other concepts technically, like "remote storage" and "cache" but we never call remote storage "remote cache"

**Comment by jorgeorpinel** [comment]
> Waiting on https://github.com/iterative/dvc/issues/7086

@dberenbaum @pared it's not obvious how that issue relates to the terminology discussion here. Could someone briefly explain the plan? Thanks

**Comment by jorgeorpinel** [comment]
> Maybe we need to put the types of metrics in a proper metrics/plots guide

BTW the guide part should be covered in https://github.com/iterative/dvc.org/issues/2572 so we can limit this issue to the cmd ref. indeed + maybe mentions in the Get Started if needed.

**Comment by pared** [comment]
> @dberenbaum @pared it's not obvious how that issue relates to the terminology discussion here. Could someone briefly explain the plan? Thanks

I think that the main cause for this is that after iterative/dvc#7086 the concept of the plot will be even more ephemeral than it was till now, and there was no point in modifying the docs until we implement it. What I mean by that is that in the beginning plots were directly tied to some data series. After iterative/dvc#6431 that no longer holds, because we started supporting binary files too. Once we implement iterative/dvc#7086 plot will be either a binary (images) or a sum of two elements: `data series` + `config` defining how particular data has to be handled in order to provide a visual aid. That will lead us to the redefinition of what a plot is and how it relates to metrics.

**Comment by jorgeorpinel** [comment]
> Once we implement https://github.com/iterative/dvc/issues/7086 plot will be either a binary (images) or a sum of two elements: data series + config defining how particular data has to be handled

Thanks for the context! Still the underlying conceptual/terminology problem remains basically unchanged: both `dvc metrics` and `dvc plots` work with project "metrics" (e.g. an AUC curve is basically a metric but you use `pltos` for that). Even for binary file `plots`, I think we assume people will generate custom charts that show them metrics on their project, not any image output.

However my thinking now is that there's not much we can do on the docs side other than de-emphasize the connection between `metrics` and `plots` to avoid terminology confusion (as mentioned in https://github.com/iterative/dvc.org/issues/2956#issuecomment-1077019111).

Otherwise this is a core discussion and could be moved to the core repo as such. One idea: could all metrics and plots functions get mixed into `dvc metrics show/plot/diff/config`? Prpbably a long forgotten discussion already, but WDYT @dberenbaum @pared

**Comment by jorgeorpinel** [comment]
Oh. No, I don't agree that the obvious solution is to separate the concepts because plots are conceptually types of metrics (general meaning of the word "metrics"). Again thinking of the example of an AUC-ROC curve: These are clearly model metrics (right?).

But if that's what you decide then sure, we can just call `metrics` metrics and `plots` plots, and never mix the terminology: we can use terms like "performance measurement" instead of "metrics" in the context of `plots`. Does that sound like a plan then?

**Comment by dberenbaum** [comment]
> Again thinking of the example of an AUC-ROC curve: These are clearly modeling metrics (right?).

Maybe I'm odd, but I wouldn't call an AUC-ROC curve or anything other than a scalar value a metric 🤷 .

> But if that's what you decide then sure, we can just call `metrics` metrics and `plots` plots, and never mix the terminology: we can use terms like "performance measurements" instead of "metrics" in the context of `plots`. Does that sound like a plan then?

Sure. We can discuss further if needed once we have a PR to review.

**Comment by jorgeorpinel** [comment]
> I wouldn't call an AUC-ROC curve or anything other than a scalar value a metric

Ah then indeed we should try a more general term like "performance measure" to separate the terminology 🙂 

I updated the labels as this may involve more than just the cmd ref but no need to work on anything outside of small/strategic word changes in the cmd ref on your end @pared (we'll take it over from there). Thanks!

**Comment by shcheklein** [comment]
I don't see a big problem either, though I'm biased already. I remember initially I also had a lot of doubts.

I think partially this confusion comes from the fact that in loggers like W&B you would log _metrics_ and then plot them online over time. Plots is something that is built on top of data that you log, including scalars, etc.

But they also have a way to log plots - https://docs.wandb.ai/guides/track/log/plots . Even though in the description they would say: "These simple charts make it easy to construct basic visualizations of metrics and results.". Not sure if that affects how this data is stored internally though or it's just a bunch of convenience functions.

And we mix a bit files with data (scalar or not) with plots (spec of a graphical representation). It means that we can't make a plot on top of metrics files? To show its trend for example? Or a plot that takes data from multiple outputs. Etc. It might make sense to detach plot specs from the outputs.

**Comment by pared** [comment]
> It might make sense to detach plot specs from the outputs.

@shcheklein 
This is a good point, especially that after iterative/dvc#7086 one will no longer have to specify something as a plot output to create a visualization out of that.

**Comment by jorgeorpinel** [comment]
> loggers like W&B you would log metrics and then plot them

That's the connection between metrics and plots I had on the back of my mind as well, but not something DVC does at the moment.

**Comment by jorgeorpinel** [comment]
I think this will no longer be a concern after the changes in https://github.com/iterative/dvc.org/pull/3691 are merged.
