### ISSUE TITLE
doc: shorter links to user-guide

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2967]
Hi, I need a few shortlinks for the following, which I need for `dvc exp init`.

1. https://dvc.org/doc/user-guide/project-structure/pipelines-files
2. https://dvc.org/doc/user-guide/experiment-management/running-experiments

I'd prefer something like `https://dvc.org/doc/pipelines-files` or even `https://dvc.org/pipelines-files`. Or, something else that is much shorter and still readable/understandable.

Here's how we display it right now in `dvc exp init`:
[![asciicast](https://asciinema.org/a/RU9HNkdfuq40zKvSsAOgYTygg.svg)](https://asciinema.org/a/RU9HNkdfuq40zKvSsAOgYTygg)

Looking at the dvc's code, we only seem to have short links for `man.dvc.org` which redirects to command-reference. We could also have something similar like `https://guide.dvc.org/running-experiments` (though it's 2 characters lengthier than `https://dvc.org/doc/running-experiments`).

**Comment by casperdcl** [comment]
I'd say "user guide" needn't show up in the URL at all (`dvc.org/doc/user-guide/experiment-management` => `dvc.org/doc/experiment-management`)

**Comment by shcheklein** [comment]
> I'd say "user guide" needn't show up in the URL at all ever

I think I miss your point. What if we have `get-started/experiment-management` and `user-guide/experiment-management`

> We can also have two letter redirects /gs, /uc, /cr for other sections.

I won's solve the `experiment-management/running-experiments` problem in the initial @skshetry 's concern.

-------

I still think we need to create a simple custom url shortener which anyone could use to their benefit. I don't see a particular reason to keep it about docs specifically (leak very specific docs structure into it).

**Comment by iesahin** [comment]
> > We can also have two letter redirects /gs, /uc, /cr for other sections.
> 
> I won's solve the `experiment-management/running-experiments` problem in the initial @skshetry 's concern.


```
dvc.org/doc/user-guide/experiment-management/running-experiments > dvc.org/ug/exp/run
```

**Comment by rogermparent** [comment]
Seems like the way we're talking about this entails a more elaborate system that just throwing in some `redirects-list` entries, but considering such a system may take a while, would it be better for now to just use `redirects-list` entries with some convention that the new solution will follow?

**Comment by shcheklein** [comment]
> would it be better for now to just use redirects-list entries with some convention that the new solution will follow?

sounds good to me!

> dvc.org/ug/exp/run

we are still polluting the global URL space with the docs structure. 

Let's use some common third-level URL `s.dvc.org` or some designated global namespace - `dvc.org/s` for this please. 

After that it will up to the author to put a link they like there. It can be even `s.dvc.org/ug/exp/run`

**Comment by casperdcl** [comment]
> > I'd say "user guide" needn't show up in the URL at all ever
> 
> I think I miss your point. What if we have `get-started/experiment-management` and `user-guide/experiment-management`

I was replying to a tangential discussion (https://github.com/iterative/dvc.org/issues/2967#issuecomment-954642910).

In terms of this mostly unrelated issue (#2967, i.e. bespoke one-off shortlink), DVC team should open a PR?

> I still think we need to create a simple custom url shortener which anyone could use to their benefit. I don't see a particular reason to keep it about docs specifically (leak very specific docs structure into it)
>
> Let's use some common third-level URL `s.dvc.org` or some designated global namespace - `dvc.org/s` for this please.
> 
> After that it will up to the author to put a link they like there. It can be even `s.dvc.org/ug/exp/run`


I'd say that's another separate tangential meta issue, but fully agree.

**Comment by iesahin** [comment]
> we are still polluting the global URL space with the docs structure.

Ok. We can use `dvc.org/s/ug/...` for the time being, and move to `s.dvc.org/ug/...` when the new domain is ready to serve. Given the time and configuration constraints, this looks like the simplest approach.

**Comment by shcheklein** [comment]
`s.dvc.org` is done (it's fast to create domains like this).

**Comment by iesahin** [comment]
Is it a `CNAME` for the `dvc.org` domain? We'll use redirects as usual?

**Comment by shcheklein** [comment]
> We'll use redirects as usual?

Yep

**Comment by jorgeorpinel** [comment]
> which I need for dvc exp init.
>
> https://dvc.org/doc/user-guide/project-structure/pipelines-files
> https://dvc.org/doc/user-guide/experiment-management/running-experiments

Hi. So is this closed by https://github.com/iterative/dvc.org/pull/3001? I don't see those 2 specific redirects in there.

**Comment by iesahin** [comment]
https://dvc.org/doc/user-guide/experiment-management/running-experiments is now https://s.dvc.org/g/exp/run 

https://dvc.org/doc/user-guide/project-structure/pipelines-files is https://s.dvc.org/g/project-structure/pipelines-files

If you need shorter versions to these, please let me know or just submit a PR with s.dvc.org domain. @skshetry
