### ISSUE TITLE
Introduce git helpers?

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2969]
For #2856 , should we introduce some of the existing options to reduce friction with Git? In particular:

* `core.autostage`: staging changes to DVC files.
* `install`: install hooks for checkout, commit, and push.

These options might be too in-depth for getting started, but they also seem hard to find today despite being useful for many (maybe most) users to reduce the pain of duplicating DVC and Git commands.

**Comment by iesahin** [comment]
We could use some hover notes that are shown across the documentation. We can create them like `<hover>git-helpers</hover>`  and these boxes tell these optional-but-not-necessarily-recommended features. 

Otherwise, IMHO, linking to another page distracts the user, telling them in the main text breaks the narrative, putting them in a hidden section makes these unnecessarily valuable :) These can be thought as "common footnotes across the site"

**Comment by jorgeorpinel** [comment]
I think we're overcomplicating this.

To summarize, the question is whether to keep featuring a bunch of `git add/commit` samples in our docs (especially Get Started/ Data Management) or to introduce/assume `dvc install` more, right?

The easiest first step is to find a place to link to `install` from the current https://dvc.org/doc/start/data-and-model-versioning and submit a PR proposal. And to mention `core.autostage` in https://dvc.org/doc/command-reference/install + link to the `config` ref.

**Comment by iesahin** [comment]
Another point that `hover` functionality may prove useful is issues like #2970 . We can put little boxes on options like `--local`, that tell "this is optional, we use it for such and such."

**Comment by dberenbaum** [comment]
Related: https://github.com/iterative/dvc/discussions/6929.

> And to summarize the larger question, is it whether to keep featuring a bunch of `git add/commit` samples in our docs (especially Get Started/ Data Management) or to introduce/assume `dvc install` more?

That wasn't initially my question, but it's a good question. First, it's probably more applicable to `autostage` than `dvc install`. `dvc install` reduces DVC commands, not Git commands.

Even for `autostage`, I wouldn't rush to do this. It would be a big change and one that might not make sense for users who miss that part or who started using DVC before we made the change. Also, glancing through the examples, I think the Git commands are mostly helpful by showing when `.dvc` or `.gitignore` files were modified.

When I mentioned lowering the barrier to entry, it could be by eventually eliminating these Git commands and not bothering to explain `.dvc` files and the details of how DVC works at first, but I'm not so sure I even like that idea, and I don't think we should go that far now.
