### ISSUE TITLE
Use `--local` for basic remote setup?

### ISSUE THREAD

**Issue by vladiliescu** [iterative/dvc.org#2970]
Hi there, not sure if this is a bug or a feature, but the [docs](https://dvc.org/doc/start/data-and-model-versioning) are suggesting to store `.dvc/config` in git. 

Which seemed fine at first, but then I noticed that my Azure Blob Storage account (i.e. my Azure username) is also stored in `.dvc/config`, which means it would end up in git. Which is not ideal for team collaboration scenarios. What's less ideal (read: **really** scary) is that connection strings entered using `dvc remote modify blah connection_string ...` also end up in `.dvc/config`, making them end up in git, making them end up in interesting places for open source projects.

Am I doing something obviously wrong? I wouldn't expect the getting started docs to go very deep into security issues, but I wouldn't expect them to store connection strings in source control either.

**Comment by jorgeorpinel** [comment]
> ```
> dvc remote modify myremote account_name 'myuser'
> # my Azure email account is stored in .dvc/config, and in git
> ```

OK so the problem is that we should use `--local` more in the auth setup examples of https://dvc.org/doc/command-reference/remote/add#supported-storage-types right? Indeed not all use it atm. Probably we assumed endpoints and usernames aren't secrets but it's safer to assume they are.

List of possible updates:

S3-compatible:
`dvc remote modify myremote endpointurl \`

Azure:
`dvc remote modify myremote account_name 'myuser'`

Aliyun:
`dvc remote modify myremote oss_endpoint endpoint`

--

However for SSH and (Web)HDFS it's not clear what to do about

```
dvc remote add -d myremote ssh://user@example.com/path
dvc remote add -d myremote hdfs://user@example.com/path
dvc remote add -d myremote webhdfs://user@example.com/path
```

I guess also add those with `--local` since the user is in the remote `url`?

**Comment by jorgeorpinel** [comment]
p.s. @vladiliescu are you planning to contribute a PR? If so you can do so easily with the [Edit on GH] button right from the doc in question.🙂 But if not no problem, we'll get to it.

![image](https://user-images.githubusercontent.com/1477535/139999976-cfb6d0db-4ebd-41ca-baac-4391dca67121.png)

**Comment by shcheklein** [comment]
> but it's safer to assume they are.

I don't think we should be doing this. `url`, `name`, `endpoint` - it's expected that user would want to save and share them. `--local` should excessive.

**Comment by jorgeorpinel** [comment]
So we don't see this as a problem?

> `dvc remote modify myremote account_name 'myuser'`
my Azure email account is stored in .dvc/config, and in git

If so please close this ticket. Thanks

**Comment by shcheklein** [comment]
> So we don't see this as a problem?

I can't answer about that specific item. 

What I'm saying that a lot of them should not have `--local`.

Solution for this ticket could be a mention at the top of the page, or somewhere else in advance that please don't store secrets in Git, there is `--local`, etc.

If you feel that we have enough of those notes, I'm also fine to close this.

**Comment by iesahin** [comment]
IMHO a single sentence note at this point about `--local` might be good, if we won't have `<abbr>` like  hover boxes. 

![Screenshot_20211110-165333_Firefox](https://user-images.githubusercontent.com/476310/141125922-0aeee9f6-91b3-4d89-969f-25578233d35d.jpg)

**Comment by jorgeorpinel** [comment]
> Solution for this ticket could be a mention at the top of the page, or somewhere else in advance that please don't store secrets in Git, there is --local, etc.

OK but if we ask people not to store secrets and then give an example where we're storing private info (an email address) in Git, that wouldn't be consistent. Especially since people may go straight to the code blocks and not really read all the text and notes.

**Comment by jorgeorpinel** [comment]
> What I'm saying that a lot of them should not have --local.

Yeah, we are only talking about those with private info I think.

**Comment by jorgeorpinel** [comment]
Anyway... I reviewed all `--local` usage in https://github.com/iterative/dvc.org/pull/3027. PTAL

**Comment by iesahin** [comment]
> OK but if we ask people not to store "secrets" (subjective) and then give an example where we're storing private info (an email address) in Git, that wouldn't be consistent.

I didn't get the point. Email addresses are not "secret." What we mean by "secret" are the passwords, AWS connection configuration etc. Those are used primarily with `dvc remote add` or `remote modify`. 

I think for any remote configuration example, `--local` can be shown in the example with a note "if you want to share your credentials, you can remove `--local`" in the text. The default copy/paste result should be using `--local` for secrets.

**Comment by jorgeorpinel** [comment]
> Email addresses are not "secret."

That's up to each user to decide. The author in this issue specifically stated their email is considered private and shouldn't be in Git ever. to me even just to avoid SPAM that makes sense as a best practice, TBH.

Secret/private, whatever the term, the point is (not) storing it in Git.

**Comment by jorgeorpinel** [comment]
BTW https://github.com/iterative/dvc.org/pull/3027 is merged and the note has been added. I'd put `--local` in more places (better to be safe than sorry) but oh well, we can wait and see if other people complain about this. Closing!
