### ISSUE TITLE
document Python version requirements?

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2975]
I couldn't find any reference to the minimum/maximum Python versions DVC can run on. Should we put this somewhere?

**Comment by jorgeorpinel** [comment]
Python 3.6+ I think. According to https://dvc.org/doc/user-guide/contributing/core#development-environment

> Should we put this somewhere?

Good call but would only be relevant for `pip` and `conda` installs, right?

**Comment by iesahin** [comment]
Yeah, but we may also have an upper limit, like Python 3.10. Some required libraries are not upgraded for some time.

Also, I saw a notice that DVC dropped 3.6 support, but I need to search it a bit.

**Comment by iesahin** [comment]
It looks this is a low priority, closing to focus on other tasks.

**Comment by jorgeorpinel** [comment]
I mean we could give this to the core team if we all agree it's pretty important. WDYT @dberenbaum ?

**Comment by dberenbaum** [comment]
I would say it's nice to have although not a high priority judging by the lack of community questions/interest. @efiop would probably have to answer what versions are officially supported.

**Comment by daavoo** [comment]
For reference, the "ground truth" for the minimum supported Python version is here: https://github.com/iterative/dvc/blob/master/setup.cfg#L31

**Comment by efiop** [comment]
setup.cfg is the ground truth,  correct. So our docs are out of date, created https://github.com/iterative/dvc.org/pull/3029

**Comment by dberenbaum** [comment]
So we "officially" support 3.10?

**Comment by efiop** [comment]
@dberenbaum Yeah, some updates are still rolling out (conda, pygit2, etc), but that is an ongoing process. dvc itself does support 3.10
