### ISSUE TITLE
Make Youtube Embeds GDPR compliant

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2980]
Currently, we use Youtube embeds for videos on the site. But Youtube is using cookies to track user's info. If we don't want to have to ask a user's permission to play Youtube videos, we'll need to find an alternative to youtube. Youtube does offer `youtube-nocookie.com`, but that just places tracking info in local storage and adds cookies once the user presses play. 

cc @shcheklein @rogermparent

**Comment by julieg18** [comment]
We could definitely use a different video platform, but we would be forced to copy over any youtube videos we want to post on our website over to that platform. And we would less traffic on our youtube channel 🤔 Maybe we should consider turning our youtube embeds into links to youtube? We could use the youtube API and CSS to make it look like a video (allowing us to not have to update our website layouts), but when you click on it opens a new tab to youtube. @iterative/websites, what do you think?

**Comment by rogermparent** [comment]
> We could definitely use a different video platform, but we would be forced to copy over any youtube videos we want to post on our website over to that platform. And we would less traffic on our youtube channel thinking

Agreed, would be a rough time to port all videos we want to embed as well as trying to enforce no youtube embeds throughout the site.

> Maybe we should consider turning our youtube embeds into links to youtube? We could use the youtube API and CSS to make it look like a video (allowing us to not have to update our website layouts), but when you click on it opens a new tab to youtube.

I don't think this is quite what we'd want, I get the impression most people like to have the embeds within the site instead of bringing the user to another site which makes it more likely they'll bounce after.

Maybe we could re-tune our youtube-embeds such that the iframe src is not loaded until the user clicks a button? I found some inspiration [from this article](https://cookieplugins.com/en/embedding-gdpr-compliant-youtube-videos/) and threw together a little demo:

https://user-images.githubusercontent.com/9111807/147594671-99f8f993-07d3-4141-9c7e-fa18af8bd895.mp4

We'll have to provide our own background image if we want one, but this method of loading ensures that the child iframe can't even load if we don't want it to, ensuring that no user info can be stored and we stay GDPR compliant while keeping videos embedded in the website.

**Comment by julieg18** [comment]
> Maybe we could re-tune our youtube-embeds such that the iframe src is not loaded until the user clicks a button?

That would definitely be an improvement but I believe to be GDPR compliant, we would need to notify the user that clicking on the button sets trackers. If we want to keep youtube embeds on the site, maybe we could notify the user by showing a tooltip so the user wouldn't need to make extra clicks 🤔

**Comment by shcheklein** [comment]
Tooltip when I hover the play button?

One option to consider - open it the new window on the youtube domain?

**Comment by julieg18** [comment]
> Tooltip when I hover the play button?

Yes! If we want to keep youtube embeds on our site, we would need to notify the user that clicking on the youtube video would add trackers to their browser. One way that came to mind was adding a tooltip when you hover over the play button, letting the user know that clicking play would add trackers, keeping things GDPR compliant!

> One option to consider - open it the new window on the youtube domain?

Yes, I mentioned this option earlier! We can have the site open a link to youtube when a user clicks on the video. It keeps our site tracker free and we won't have to notify the user of anything :)

**Comment by shcheklein** [comment]
I think tooltip like that works. We would need to take care of the blog and docs for the embedded videos I think.

**Comment by julieg18** [comment]
> I think tooltip like that works. 

Sounds good! We'll need a design for the tooltip and as for the video background... We could keep it a dark screen (like in @rogermparent's example) , design a custom image, or even use the youtube api to fetch the the videos` thumbnail (though that method would add extra requests for the website).

> We would need to take care of the blog and docs for the embedded videos I think.

I can think of a way to do this with the docs engine. As for the blog, it may need some kind of custom plugin 🤔

**Comment by yathomasi** [comment]
We can also have this option to remember the choice for next time.

![image](https://user-images.githubusercontent.com/20840228/147645266-6e654eba-75cf-44ef-994e-38978fd67ce9.png)

**Comment by julieg18** [comment]
Did some further research about using `youtube-nocookie`. Weirdly enough, I can't seem to find any official information from Google or Youtube about the local storage data that `youtube-nocookie` sets. All that Google says for sure in statements is that no cookies will be placed until a user presses play. But they don't mention local storage at all. As far as I can tell, they also never mention offically that `youtube-nocookie` is GDPR compliant, just stating that it helps with the cookies. 

Looking outside of Google/Youtube, I'm reading mixed opinions. Some say that `youtube-nocookie` isn't GDPR compliant, most referring to [this report by cookie bot](https://www.cookiebot.com/media/1136/cookiebot-report-2019-ad-tech-surveillance-2.pdf) (pg 6). Others say it is, but they never mention anything about local storage, possibly hinting they didn't know YouTube places anything in local storage 🤔 

Personally, I don't think it's GDPR compliant. Even if the data that its setting in the local storage doesn't track anything from the user, we still need to let the user know that clicking on the youtube videos activates youtube's cookies.

**Comment by shcheklein** [comment]
To be GDPR compatible (in a sense that you don't have to show the message) doesn't mean that you could not use cookies at all. It depends on how those cookies (and local storage) are being used.  Google mentions briefly that they do not use them to personalize. We would need to check what do they actually do with them. May be we would need to check their privacy policy and terms of use.

Can we create a PR to research this a bit? It seems it would be beneficial anyway to switch to the nocookie domain.

**Comment by julieg18** [comment]
> Can we create a PR to research this a bit?

Sure, I'll open an issue! 

>  It seems it would be beneficial anyway to switch to the nocookie domain.

Agreed! I can update all the youtube urls by running a regex on our site and open a PR. But would we want some kind of tool that does this for us in the future or just check over future docs/blogs pages as they are created, making sure they are using the nocookie domain? 🤔

**Comment by julieg18** [comment]
Looked into and tested the `gatsby-remark-embedder` and it looks like we can add a custom transformer that overwrites the default youtube transformer, easily updating your blog and doc embeds!
