### ISSUE TITLE
GSoD'19 Applicant - Tapasweni Pathak

### ISSUE THREAD

**Issue by tapaswenipathak** [iterative/dvc.org#299]
Hi folks,

I am a GSoD'19 applicant, have read [the ideas list](https://blog.dataversioncontrol.com/dvc-project-ideas-for-google-summer-of-docs-2019-defe3a73b248) and have PRed for most of the tasks. I have participated in multiple SoC/WoC and have been involved w/ open source since years. I have worked with Jupyter and ML. I am fully familiar with these areas. DVC.org is great fit for me but as a product new for me. 

On docs I like detailed docs having every step present so that the user can be spoon feeded, makes it easily usable. Docs should have all useful information.

## Ticket's list described in dvc.org blog

- https://github.com/iterative/dvc.org/issues/53
- https://github.com/iterative/dvc.org/issues/96
- https://github.com/iterative/dvc.org/issues/144
- https://github.com/iterative/dvc.org/issues/194

## Projects I am interested in / Remaining tickets

- Improving command reference https://dvc.org/doc/commands-reference
  I think you mean tutorial updates as the ticket you linked is [this](https://github.com/iterative/dvc.org/issues/198). I read all the [command reference docs](https://dvc.org/doc/commands-reference/) present and everything has examples I think, please let me know if I am missing anything. From the ticket tutorial needs the code files.

- https://github.com/iterative/dvc/issues/1487

  PRing!

## PR's list

- https://github.com/iterative/dvc.org/pull/292
- https://github.com/iterative/dvc.org/pull/293
- https://github.com/iterative/dvc.org/pull/294
- https://github.com/iterative/dvc.org/pull/296

With this I have covered the example tickets present in the blogs, would love knowing what you think. I will close few more [tickets](https://github.com/iterative/dvc.org/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) from the list during the application period. Thanks for the read!

**Comment by shcheklein** [comment]
@tapaswenipathak closing this as not an issue :) Welcome to the community though. We'll review your PRs and let you know. My recommendation would be to focus on one ticket from a single group - so that you can learn our workflow, out expectations, etc.

**Comment by tapaswenipathak** [comment]
On Wed, 8 May 2019, 11:17 p.m. Ivan Shcheklein, <notifications@github.com>
wrote:

> @tapaswenipathak <https://github.com/tapaswenipathak> closing this as not
> an issue :) Welcome to the community though. We'll review your PRs and let
> you know. My recommendation would be to focus on one ticket from a single
> group - so that you can learn our workflow, out expectations, etc.
>

Ok sure. I will mostly be closing all open tickets given in the application
ideas list, I will make sure you put as less effort as possible, Thanks!
