### ISSUE TITLE
guide: "Comparing Experiments" improvements

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2995]
> Extracted from https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-781399419 etc.

Rel. https://dvc.org/doc/user-guide/experiment-management/comparing-experiments

General
- [x] Needs detailed copy editing. E.g. [missing "the"](https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-783752862), disjointed paragraphs, unnecessary scrolling blocks, etc. ([another e.g.](https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-784000442))
- #3160 ?
- [ ] Review "baseline" concept. Apply to explanations and branch names?
  Per https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-781399419
- [ ] Cover `exp show` first (`exp list` later).
  Per https://github.com/iterative/dvc.org/pull/2862#discussion_r730339949

Specific ideas
- [ ] Address https://github.com/iterative/dvc.org/pull/2908#pullrequestreview-775523131 .
- [ ] Cover `deps/dependencies` column. See #3220 
- [ ] Absorb [#list-experiment-names-to-use-in-scripts](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments#list-experiment-names-to-use-in-scripts) into [#list-experiments-in-the-workspace](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments#list-experiments-in-the-workspace).
- [ ] Consider tabs when commands are used as alternatives in specific example tasks (e.g. `exp show` vs `exp diff`).
- [ ] Include/mention `--only-changed` per https://github.com/iterative/dvc.org/pull/2966 .
- [ ] Avoid terms "git ref" and "attached". (Use "based on" for consistency?)
- [x] `--sort/order-by/no-timestamp` sections may be too detailed. Hide or just mention + link to ref.
- [ ] Merge JSON and CSV sections more somehow (tabs?).
- [x] Shorten JSON/CSV output sample blocks and remove corresponding schema descriptions (comprehensive examples are enough). (See https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-783758097 and below.)
- [ ] Format CSV samples if possible (even if that's not how they're output exactly)
- [x] Clarify `exp diff` sections to separate cases: workspace vs. `HEAD`, rev A vs rev B, etc. (See https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-783894016 and below.)
- [ ] Distinguish experiments that ran vs queued ones (`exo show/list`).

**Comment by jorgeorpinel** [comment]
@iesahin could you prioritize the general points as part of phase 1?

**Comment by iesahin** [comment]
I have split the doc into two in #3011 @jorgeorpinel. It may be easier this way, PTAL.

**Comment by jorgeorpinel** [comment]
Let's discuss as agreed @iesahin 🙂 

> Its too long. It’s hard to make sense w/o additional help /structure.

💡 instead of grouping sections by command, let's consolidate them into major actions e.g. **Review existing experiments** can cover basic `exp show` and all of `exp list`. Feel free to leave some things out from sample blocks (just mention options, etc.)

The other 2 general check boxes should be straightforward to address. I think.

**Comment by jorgeorpinel** [comment]
@iesahin do you need another thing to start in parallel this sprint? Addressing some tasks in there would be a good candidate. Feel free to put it in the current board if so.

**Comment by iesahin** [comment]
Let me check this, thank you Jorge.

**Comment by iesahin** [comment]
I've added #3160 to write a synopsis section.

**Comment by daavoo** [comment]
In https://github.com/iterative/dvc.org/pull/3220 new type of column `depencendies`/`deps` is included. Should we add a checklist here ?

**Comment by iesahin** [comment]
I've added, thank you for pointing this @daavoo

**Comment by jorgeorpinel** [comment]
Not planned for this quarter unfortunately @daavoo . Let's definitely update any ref. changes missed by the core team, and if possible guide updates as well, or at least if you can create a `bug` report on those, we can prioritize that. Thanks
