### ISSUE TITLE
`dvclive`: Document image support 

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3013]
Version [0.4.3](https://github.com/iterative/dvclive/releases/tag/0.4.3) of `dvclive` added support to logging images, following `dvc` support for it.

**Comment by daavoo** [comment]
I was considering waiting for https://github.com/iterative/dvc.org/issues/2956 to have a consistent narrative

**Comment by jorgeorpinel** [comment]
Looks like there's consensus in https://github.com/iterative/dvc.org/issues/2956#issuecomment-951017753. Only call scalars metrics. Plots can be different things (plots files and the corresponding plot visualization vs image files). Does that help?

**Comment by dberenbaum** [comment]
@daavoo Is that enough info to get started on this? I don't think you should wait for #2956 since rewording those docs is not as high priority as documenting this new feature.
