### ISSUE TITLE
Mention `exp apply --no-force` option in "Persisting Experiments"

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3028]
The option is only mentioned in the command reference but we don't have examples or motivations behind the usage. 

I think it would be nice to add a mention to the option in the "Persisting Experiments" user guide.

> @pmrowla I hadn't noticed the `--no-force` argument. On reflection, switching between experiments would necessitate use of a `--force` flag if it existed, and I guess that use-case is considered the most common.
> 
> I will monitor how I use `exp apply` for now, and whether I can easily encorporate `--no-force` into my workflow.
> 
> _Originally posted by @mattlbeck in https://github.com/iterative/dvc/issues/6930#issuecomment-970712018_

**Comment by jorgeorpinel** [comment]
I'm surprised it's not in https://dvc.org/doc/user-guide/experiment-management/persisting-experiments. I guess we skipped some options @iesahin ?

This has previously been discussed in https://github.com/iterative/dvc.org/issues/2397 so I'm going to merge the issues... ⌛

**Comment by jorgeorpinel** [comment]
Hmmm actually that other issue should be closed as it referred to the cmd ref. This one can be about the user guide.

**Comment by jorgeorpinel** [comment]
So, I think the default behavior should be definitely noted (that it destroys current changes i.e. the Git working tree) and it is (in [the ref](https://dvc.org/doc/command-reference/exp/apply)), but we could rephrase to make it clearer there.

We should add this explanation to the guide as well. I'm surprised it was left out of https://dvc.org/doc/user-guide/experiment-management/persisting-experiments actually. Did we leave out many other options from guides @iesahin ? Thanks

**Comment by iesahin** [comment]
As far as I can tell, there is none.

![SmartSelect_20211129-181032_Firefox](https://user-images.githubusercontent.com/476310/143892829-2fd63d3e-0c9e-4be7-99bd-d38a4dfabe13.jpg)
