### ISSUE TITLE
guide: Write a metrics guide for non-DVCLive scenarios

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3041]
In the newer GS:Experiments trail, we are removing detailed metrics introduction due to DVCLive/Keras integration. Instead, we can have a guide that describes the manual metrics functionality.

**Comment by jorgeorpinel** [comment]
@iesahin please make it a check box in https://github.com/iterative/dvc.org/issues/2572 instead 🙂 (those bullets should all be check boxes I think?) Thanks!
