### ISSUE TITLE
Add `<figcapture>` element

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3061]
... we should add support/styling to the `figure`/`figcaption` elements or some sort of custom component that emulates what this is doing- the ability to caption code blocks does seem valuable.

_Originally posted by @rogermparent in https://github.com/iterative/dvc.org/pull/2782#pullrequestreview-821508373

---

Currently images automatically generate a caption but this can not be easily placed by itself (without an image), for example for md tables or any other graphic that's used as a figure:

![image](https://user-images.githubusercontent.com/1477535/144499281-c106a526-9fe8-4e73-9743-a539d854ba2c.png)

**Comment by shcheklein** [comment]
Link doesn't work. Let's add more context in the ticket please. Very hard to understand the motivation and why it's needed.

**Comment by jorgeorpinel** [comment]
Updated link and description.
