### ISSUE TITLE
font: hard to read

### ISSUE THREAD

**Issue by adhadse** [iterative/dvc.org#3063]
I don't know if this issue should be here or not, or if I am the only one experience this "minor" problem but the font "BrandonGrotesque" used on docs makes it much harder to read.

I agree it might be to keep consistency across the website, but to me the first thing comes is the doc. **And looking at font which is supposed to be used for landing page, getting used on docs doesn't make sense**.

Please change it, or give your thoughts.

**Comment by iesahin** [comment]
Thank you @adhadse. What would you recommend as a more legible font?

**Comment by jorgeorpinel** [comment]
@adhadse can you confirm it looks like this? Have you tried zooming in with your browser (Ctrl+) ?

![image](https://user-images.githubusercontent.com/1477535/144944147-6da1f30e-9442-449a-b357-1d19d6e24d4e.png)

What do you think about Tahoma?

![image](https://user-images.githubusercontent.com/1477535/144944089-6a736d09-e6c2-4993-9fae-843891f874a0.png)

Or Arial?

![image](https://user-images.githubusercontent.com/1477535/144944119-2a2575b0-a4b3-49e5-8b96-6c4645784c4b.png)

Thanks

**Comment by adhadse** [comment]
@jorgeorpinel Yes the font does look like what you have shown in first screenshot. 

"Arial" is proprietary font from Microsoft, and Tahoma is also a Microsoft origin. I would request you to use to some open font available via[ Google fonts](https://fonts.google.com/).

Currently I am just using fonts style as can be seen on [Pandas doc](https://pandas.pydata.org/docs/) site: 

```css
font-family: -apple-system, BlinkMacSystemFont, Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,Liberation Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
```
Result:
![image](https://user-images.githubusercontent.com/56764399/145579714-e5da0266-6e56-4410-bd5e-78481444b5a9.png)

Good enough to me, what do think? @jorgeorpinel @iesahin

**Comment by jorgeorpinel** [comment]
Thanks @adhadse we'll share your recs with the website's team cc @rogermparent (not sure who to ask 😬)

**Comment by iesahin** [comment]
Much appreciated @adhadse TBH, I like the current font more than the example you provided. We'll consider changing it though. The website team is already notified. Thank you very much for reporting this.
