### ISSUE TITLE
ref: Update `dvc run` references in `dvc freeze` and `dvc unfreeze`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3070]
To be updated examples are:

- https://github.com/iterative/dvc.org/blame/master/content/docs/command-reference/freeze.md#L47

 - https://github.com/iterative/dvc.org/blame/master/content/docs/command-reference/unfreeze.md#L45

**Comment by jorgeorpinel** [comment]
Thanks @iesahin . You know we can just keep the epic (https://github.com/iterative/dvc.org/issues/2997) and check boxes in there.

**Comment by iesahin** [comment]
I'm creating these issues from those checkboxes. When these are done, they are checked as well. It feels easier to track this way. @jorgeorpinel
