### ISSUE TITLE
start: clarify rel. between `exp run` and `repro`. 

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3072]
This is reported by @tapadipti (Related: iterative/example-repos-dev#98) 

4. `If you used dvc repro before` section in the doc is a little unclear. Does `dvc exp run` replace `dvc repro`? If yes, can we state this clearly? Also would be great to change this statement `We use dvc repro to run the pipeline...` to `dvc repro runs the pipeline...`

**Comment by shcheklein** [comment]
Could that section be removed completely?

**Comment by iesahin** [comment]
My intention in #3051 is also to remove it completely, because `dvc exp init` lets you a "pipeline-free" experimentation, to an extent, and without pipelines we don't need to mention `dvc repro`. @shcheklein

**Comment by iesahin** [comment]
I've removed the section in #3051.

**Comment by jorgeorpinel** [comment]
I no longer see the section in https://dvc.org/doc/start/experiments . Can we close this @iesahin ? Thanks

**Comment by iesahin** [comment]
Closing the issue after #3155.
