### ISSUE TITLE
Use same/similar engine for blog and documentation

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3076]
Currently, the blog and docs have different engines (or they generate the final html in different ways). Should we look into having the blog use the same engine (or an engine similiar) to the docs engine? Not only would this simplify our markdown engine code, it would also be easier to give the blog custom components like the `external-link`. cc @rogermparent

**Comment by jorgeorpinel** [comment]
Not sure, they're different applications. As long as all products can use the same docs engine once/if they need special features and their own copy of the same blog engine, maybe that's a better goal?

**Comment by rogermparent** [comment]
I've brought this up a few times, and I'm still for it, but I do think that it's a lower priority than making the docs engine sharable especially where only dvc.org has a blog. 
After the docs repackaging is done, it could be a good idea to try changing the blog to remark- particularly if we decide to run multiple blogs on different sites.

**Comment by julieg18** [comment]
> Not sure, they're different applications. As long as all products can use the same docs engine once/if they need special features and their own copy of the same blog engine, maybe that's a better goal?

While they are different applications, the engines are both essentially doing the same things. Turning markdown pages into HTML.

**Comment by jorgeorpinel** [comment]
OK well if it makes sense technically and only the styling really changes then sure, up to you guys 🙂

**Comment by julieg18** [comment]
> OK well if it makes sense technically and only the layout and styling really changes then sure, up to you guys 🙂

I'm pretty sure there wouldn't be any visible changes if we did this :)

**Comment by jorgeorpinel** [comment]
I meant if layout and styling are the only differences between docs and blog engines.
