### ISSUE TITLE
Improve code samples copy-pastability

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#310]
Two things here:
- use css for padding instead of 4 leading spaces everywhere,
- wrap parts we want to skip like `$` with `<span style="user-select: none">...</span>`.

**Comment by Suor** [comment]
*P.S.* This is mostly dup of #213.

**Comment by shcheklein** [comment]
Thanks, @Suor . Moved the first part to a separate issue. 213 is in progress by @ProjGoodF . I'm closing this as a dup.
