### ISSUE TITLE
Use `dvctable` syntax for all tables

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3104]
We are using `dvctable` syntax for some of our tables but we still have about 25 (16 in docs, 9 in blog) tables that are still using `dvc` syntax without any styling. We should work towards styling all of our tables with `dvctable`.

**Comment by shcheklein** [comment]
Yes, we want to update them.

**Comment by rogermparent** [comment]
Some info from #3173:

These are the remaining tables with the old style:

```bash
$ rg "┏━"
content/docs/api-reference/make_checkpoint.md
129:┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓

content/docs/command-reference/exp/branch.md
59:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓

content/docs/command-reference/exp/diff.md
85:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓

content/docs/command-reference/exp/apply.md
60:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
124:┏━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓

content/docs/user-guide/experiment-management/checkpoints.md
279:┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┓
328:┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┓
407:┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┓

content/blog/2021-02-18-dvc-2-0-pre-release.md
198:┏━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
314:┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓
344:┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓
375:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓

content/blog/2021-03-03-dvc-2-0-release.md
150:┏━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
266:┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓
296:┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓
327:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━┳━━━━━━━━┳━━━┓

content/docs/command-reference/exp/gc.md
73:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
105:┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓

content/blog/2021-05-28-may-21-community-gems.md
92:┏━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
```

The ones in `content/docs/user-guide/experiment-management/checkpoints.md` are the same as `dvctable` tables but without the syntax defined, but the others are `dvc` language that include shell lines with the commands that create those tables. Should the tables of those be split into `dvctable` blocks, or should we change `dvc` syntax to highlight tables no matter where they are in the code block?

**Comment by iesahin** [comment]
> Should the tables of those be split into `dvctable` blocks, or should we change `dvc` syntax to highlight tables no matter where they are in the code block?

I believe having a separate `dvctable` definition is better for customizability. DVC command outputs are more liberal and that may cause weird regex/formatting problems in corner cases.

**Comment by yathomasi** [comment]
Yes, it's better to have those code blocks be split into `dvc` and `dvctable`. We wouldn't want to make the regex definition more complex. 
We might need more step-by-step explanations after the split.
