### ISSUE TITLE
Revert Landing Page back to normal

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#3108]
@iterative/websites We need to revert the landing page to how it was before.  Question though.  Would it be possible to keep the modal if it can auto feed what's in the blog?  If it's something we have to keep changing, then nevermind, just revert.  But if it can be auto populated with what's the latest blog post, it may be worth keeping.

**Comment by julieg18** [comment]
> @iterative/websites We need to revert the landing page to how it was before. Question though. Would it be possible to keep the modal if it can auto feed what's in the blog? If it's something we have to keep changing, then nevermind, just revert. But if it can be auto populated with what's the latest blog post, it may be worth keeping.

I'll revert the video! As for the the model, it should be doable. I'll look into it!
