### ISSUE TITLE
Revisit and move `Related Technologies`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3129]
I think it’s very good content but it seems it’s a little hidden. 

I know it's right below `User Guide` but I really think this kind of comparison could be something people might want to read on the first arrival not only to docs but even `dvc.org`. 

I could also be updated to include more “competitor” and/or “based on DVC” tools (i.e. dagshub) to better reflect the "ecosystem" around DVC, including our own tools (VSCode extension, Studio)

**Comment by jorgeorpinel** [comment]
We could combine it with https://dvc.org/doc/user-guide/what-is-dvc

**Comment by daavoo** [comment]
It is now in https://dvc.org/doc/user-guide/what-is-dvc
