### ISSUE TITLE
use css for padding instead of 4 leading spaces in code blocks

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#313]
From https://github.com/iterative/dvc.org/issues/310

**Comment by kurianbenoy** [comment]
Is this applicable for react web page which hosts the dvc website?

**Comment by shcheklein** [comment]
@kurianbenoy yes. This is related to these indents in the code blocks. Right now they are done manually by including spaces.

<img width="663" alt="Screen Shot 2019-05-12 at 1 23 54 PM" src="https://user-images.githubusercontent.com/3659196/57587400-3ea0ad00-74b9-11e9-83e1-cc30a39f50ad.png">

**Comment by kurianbenoy** [comment]
@shcheklein we have only so far padded Get Started section, should I manually remove 4 leading spaces in other sections also?
