### ISSUE TITLE
install: `pip` method (silently) requires Python 3.7

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3134]
It probably makes sense for us to make it clearer what the minimum supported python version is, it's currently only stated in the venv/pipx note:

> We strongly recommend creating a virtual environment or using pipx (on Python 3.7+) to encapsulate your local environment.

It would be better if it was noted more explicitly that 3.7+ is a hard requirement.

But beyond that, IMO it should be safe for us to assume that anyone choosing the "install via pip" method (as opposed to using the binary or conda packages) should already understand how to set up a python/pip environment on their machine...

Users that aren't familiar with managing python themselves will probably be using the system packages (or conda) which handles all of that for them.

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/7181#issuecomment-1001956032_

**Comment by jorgeorpinel** [comment]
p.s. by "silently" I mean that if you have Python 3.6 `pip install dvc` will work but you'll get the last version which was supported on Python 3.6 (which is DVC 2.8.1) and you may not even notice so, or if you do you won't necessarily know why that happened.

**Comment by pmrowla** [comment]
> p.s. by "silently" I mean that if you have Python 3.6 `pip install dvc` **will work** but you'll get the last version which was supported on Python 3.6 (which is DVC 2.8.1) and you may not even notice so, or if you do you won't necessarily know why that happened.

There's no way for us to really do anything about this in DVC though. 2.8.1 is a valid DVC version for pip to install in python 3.6, so there's nothing to really warn the user about.

**Comment by jorgeorpinel** [comment]
> no way for us to really do anything about this

We can document it 🙂
