### ISSUE TITLE
Improve our element `outline` design

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3150]
Here is what our default outline looks like:

![image](https://user-images.githubusercontent.com/43496356/148130045-35d808a8-6094-485b-b636-46128aea5c86.png)

We can update:
* the color
* the length between the element and the outline (currently at 5px)
* the width of the outline itself
* the border type

border type options:

![image](https://user-images.githubusercontent.com/43496356/148130365-f028fe1c-c15a-419d-ac72-b380d2546890.png)

cc @iterative/websites

**Comment by jorgeorpinel** [comment]
What are outline elements for? Is there an example deployed or needed somewhere? Thanks

**Comment by jorgeorpinel** [comment]
What are outline elements for? Is there an example deployed or needed somewhere? Thanks

**Comment by iesahin** [comment]
There is no dash line in my FF/macOS for that "Other Tools"

![Screen Shot 2022-01-05 at 15 14 56](https://user-images.githubusercontent.com/476310/148216160-c8296efc-5438-4b8b-887b-a28fe1b6d756.png)

**Comment by julieg18** [comment]
Outlines are shown on most focusable elements when you navigate dvc.org with a keyboard. You can see outlines if you start pressing the `tab` key in dvc.org:

https://user-images.githubusercontent.com/43496356/148228595-f2fc635d-205a-48d8-9736-f023954b8557.mov

**Comment by jorgeorpinel** [comment]
> Outlines are shown on most focusable elements when you navigate dvc.org with a keyboard

Got it! 

> There is no dotted line in my FF/macOS for that "Other Tools"

Did you hit the tab key a few times @iesahin ? works for me (on Win/FF)

![image](https://user-images.githubusercontent.com/1477535/148314764-370ac8cd-50f5-4bff-91e7-4ef2ef7e0b47.png)

**Comment by jorgeorpinel** [comment]
This seems like a design question, should we relabel? I'll excuse myself 😬

**Comment by yathomasi** [comment]
Since we are taking keyboard navigation into account, we can also discuss on adding hidden `skip to content` navigation. 

We can find this implemented on most of the sites. An example is this Github itself, you can see if you start keyboard navigation by pressing `tab` button.
A similar implementation can be found on Reddit, Youtube, CSS-tricks, dev.to, and so on.

**Comment by julieg18** [comment]
> Since we are taking keyboard navigation into account, we can also discuss on adding hidden `skip to content` navigation.
> 
> We can find this implemented on most of the sites. An example is this Github itself, you can see if you start keyboard navigation by pressing `tab` button. A similar implementation can be found on Reddit, Youtube, CSS-tricks, dev.to, and so on.

Great idea! You should open an issue for adding this and we can discuss it from there!
