### ISSUE TITLE
Typo in `/doc/command-reference/exp/init`?

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3158]
There is a `--models` option in the [`/doc/command-reference/exp/init` synopsis](https://dvc.org/doc/command-reference/exp/init#synopsis):

![image](https://user-images.githubusercontent.com/43496356/148585585-9893c3b9-6f97-4e90-bbb3-0ce9491677fa.png)

But in [the options list](https://dvc.org/doc/command-reference/exp/init#options), there is a `--model` but not `--models`:

![image](https://user-images.githubusercontent.com/43496356/148585688-40b75d12-f778-409f-82b5-409e670cdf9e.png)

Is is a typo? Does the command take in only one of these or both?

**Comment by dberenbaum** [comment]
Thanks @julieg18, good catch! It should be `--models` in both places. I can submit a PR.
