### ISSUE TITLE
Update tables that aren't `dvctable`-language to new horizontal format

### ISSUE THREAD

**Issue by rogermparent** [iterative/dvc.org#3174]
We'll probably want to update all those tables since even the `dvc`-language ones are still `exp show` tables where the given output would be different, but that can wait for a later PR.

It does seem that some of those tables, particularly the ones in `content/docs/user-guide/experiment-management/checkpoints.md` (I don't see any in other files), are supposed to be `dvctable` but the author didn't add the `dvctable` language.

_Originally posted by @rogermparent in https://github.com/iterative/dvc.org/issues/3173#issuecomment-1010371363_

**Comment by julieg18** [comment]
Is this the same as #3104?

**Comment by rogermparent** [comment]
:facepalm: Yeah, more or less, I should've checked. Thanks!
