### ISSUE TITLE
tabs: way to have same height in all elements

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3179]
Currently the height of the Toggle element varies depending on the active tab. This makes sense as the default behavior, not to make any assumptions.

Could it have a prop to enable a stable height across all tabs though? It'd have to be the tallest one I suppose.

- [ ] Port to other engines if implemented 🙂

**Comment by jorgeorpinel** [comment]
p.s. should we create an **iterative/web** team for tagging on these? @rogermparent @julieg18

**Comment by julieg18** [comment]
> Could it have a prop to enable a stable height across all tabs though? It'd have to be the tallest one I suppose.

Makes sense, it would make tab switching be less jerky. We should be able to implement this! But what if we looked into making the content of a tab behave like a details component? Have the content of the tab expand smoothly instead? Then we could just apply that to all tabs without needing any props 🤔

**Comment by jorgeorpinel** [comment]
> what if we looked into making the content of a tab behave like a details component? Have the content of the tab expand smoothly

Such an animation would definitely improve the default behavior. I may still want this feature on top but it would be more of a nice-to-have at that point 🙂  Up to you.

> We do! **iterative/websites**

Oh lol k

**Comment by jorgeorpinel** [comment]
> I may still want this feature on top but it would be more of a nice-to-have at that point 🙂

Well... I just tried using tabs [at the end of a doc](I may still want this feature on top but it would be more of a nice-to-have at that point 🙂) and the side menus move a lot with the height. I don't see how an animation would help there -- it'd still be quite distracting. Equal/max height may be the best way to go after all @julieg18 ?

**Comment by julieg18** [comment]
> Well... I just tried using tabs [at the end of a doc](I may still want this feature on top but it would be more of a nice-to-have at that point 🙂) and the side menus move a lot with the tab changes (if you scroll down enough to see the page footer). I don't see how an animation would help there -- it'd still be quite distracting. Equal/max height may be the best way to go after all @julieg18 ?

Sounds good! We'll put our focus on adding a prop for equal tab height.

**Comment by yathomasi** [comment]
I have tried setting the height of the tab to maximum content height, which introduces the possibility of having a large gap. 
Here is the demo video:
https://user-images.githubusercontent.com/20840228/150820948-b9dde230-d08c-409d-a63b-5ad871eaf7c5.mov

So, I think we need to introduce some maximum default height which of course will introduce a scrollbar. Will that be okay?
Here is the demo video:

https://user-images.githubusercontent.com/20840228/150822440-1ce69473-5bf8-484e-8c00-a89e7b1e7222.mov

Also, we may also have props in case we want height more than the maximum default height.

cc @jorgeorpinel  @julieg18

**Comment by shcheklein** [comment]
@yathomasi could we explore other docs/products with tabs, share some links, etc - how do they do this?

as we discussed today during the call, I would also to better understand how big of a problem it is.

If this is about configuring - Windows vs Linux vs Mac - IMO it becomes less of a problem since you switch once, and don't pay attention to the other tabs.

If tabs are being used instead of sections, and there is an expectation for users to read all of them to get the comprehensive meaning of the page, that's where it becomes a problem. But it's not clear that this use case is the right one for tabs in the first place

cc @jorgeorpinel - what's your take?

**Comment by jorgeorpinel** [comment]
> introduces the possibility of having a large gap

Yeah I was thinking equal max height would have to be enabled via a prop.

> we may also have props in case we want height more than the maximum default height

OK, this could be an alternative solution, which prop would that be? Do you mean something like `<tab height="30m">` with some hardcoded dimension? Thanks @yathomasi 

> how big of a problem it is

@shcheklein not a big problem unless we use tabs near the end of a page. Per https://github.com/iterative/dvc.org/issues/2939 we're trying to avoid very creative uses of tabs: mainly focus on language or format switching (users would only switch once mostly), at first at least.

**Comment by yathomasi** [comment]
I have opened a [pull request in cml.dev](https://github.com/iterative/cml.dev/pull/193) as cml.dev seems to use the toggle more. I ended up providing a simple implementation that uses height as a prop on the toggle component.

**Comment by jorgeorpinel** [comment]
Cool, thanks! That works. Please link this issue to the PR that ports that feature over. Thanks @yathomasi !

**Comment by jorgeorpinel** [comment]
Looks like this is resolved by https://github.com/iterative/dvc.org/pull/3257. Thanks again @yathomasi
