### ISSUE TITLE
[spike] cases: address Sharing Data

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3186]
https://dvc.org/doc/use-cases/sharing-data-and-model-files is currently a step-by-step guide.

- Is there a use case? If so rewrite the page to express it.
- Where do we put the current content?
- Is the figure useful out there? If so make sure to find it a new home.

**Comment by iesahin** [comment]
The current content could be made into a How-To. 

I think a shorter UC could be written around the image.

**Comment by shcheklein** [comment]
Questions:

- it looks like it a bit too basic and generic for how to?
- do you have any idea about the use case around the image title? what content we would to include there?

**Comment by jorgeorpinel** [comment]
> idea about the use case around the image ~~title~~
caption [_Data is stored in storage you control, separate from code._]

@shcheklein I think it's a basic part of efficient data management for DS: controlling data like code (versioning), but in separate buckets, yet automatically linked via DVC.

BTW this is briefly covered in https://dvc.org/doc/use-cases/versioning-data-and-model-files already:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1477535/153655748-78b4f877-6e84-41fd-9335-1ed5e02e1dc6.png">

The _sharing_ aspect of it (current use case title) stems as an added benefit of that strategy. At the same time sharing may be a more relatable use case... 🤔

**Comment by jorgeorpinel** [comment]
> The current content could be made into a How-To.
it looks like it a bit too basic and generic for how to?

Yeah I think it will be included eventually in https://github.com/iterative/dvc.org/issues/2866. I added a checkbox there so we can feel free to remove the step-by-step info here or rewrite as needed for the Use Case format.

**Comment by jorgeorpinel** [comment]
We decided that the best route is to repurpose the image completely for a new use case along the lines of "Organizing Team Datasets" but since there are other use case ideas in the pipeline we'll add this to #2544 and remove this page for now.
