### ISSUE TITLE
Unify the logic to handle when clicking outside a certain element eg: dropdown, menu, modal, etc

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#3209]
We have multiple places where we have actions to handle when we click outside a certain element. This is used especially on dropdowns and modals where we want to close them after we click outside those specific elements.

We can make a reusable component or hook and use it wherever applicable and also start using them on future similar implementations.

cc @iterative/websites

**Comment by julieg18** [comment]
Similiar to [iterative.ai#370](https://github.com/iterative/iterative.ai/issues/370) which is about creating a reusable hook/component for nav popup logic. Should we close one of these issues?

**Comment by yathomasi** [comment]
@julieg18  thanks for pointing that out. Sure, closing this in favor of [iterative.ai#370](https://github.com/iterative/iterative.ai/issues/370). Once done we can migrate to all the websites.

**Comment by yathomasi** [comment]
I was also thinking the same before closing this issue.
Since most active involvements happen around the dvc.org repo, it would be more noticeable, easy to search, mention. Also, we are already following the approach of implementing first on `dvc.org` and then resuing over other repos. 

But, using another repo for a common issue can also be better, as that could be easy to view.

For this particular one, I found the issue explained over [iterative.ai#370](https://github.com/iterative/iterative.ai/issues/370) more descriptive with the image as well.

**Comment by shcheklein** [comment]
Yep, I we agree we can transfer it as-is to that repo.

**Comment by julieg18** [comment]
> Folks, qq - how do we consolidate tickets like this - should we agree to keep general tickets that could affect all the websites in the dvc.org repo? or create a separate one (commons, etc?) 

I do tend to use dvc.org when I create an issue that is for all websites, but it makes a lot of sense to make some kind of commons repo to hold all issues that are for all the sites. It's happened in the past that we've forgotten to update one site because the issue got closed before all websites we're updated 🤔
