### ISSUE TITLE
standard way to refer to DVC-files and other terms

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#321]
There 's several ways in which the docs refer to **DVC-files** (meaning the stage files created by `dvc add`, `dvc run`, etc, with the `.dvc` file extension).

Standardize everything to "DVC-file(s)" throughout the docs EXCEPT if the phrase is used for OTHER DVC-related files (not stage files) i.e. in "[DVC Files and Directories](https://dvc.org/doc/user-guide/dvc-files-and-directories)":

- [x] "DVC file" and plural "DVC files". <-- Do NOT use for stage files

- [x] "DVC-file" and its plural "DVC-files". <-- Use this one

- [x]  "`.dvc` file(s)" or "`.dvc` file extension" <-- Avoid except in single doc where DVC-files are described
- [x] "stage file(s)" <-- Avoid except when in the context of data pipelines
   > ^ Partially extracted this case to #423
- [x] DVC "metafile(s)"/"meta file(s)" <-- Avoid except in single doc where DVC-files are described

~~UPDATE: Other interesting phrases to review are:~~ See #432

**Comment by jorgeorpinel** [comment]
Side note: I'm already changing `.dvc` for `.dvc/` (see https://github.com/jorgeorpinel/dvc.org/commit/cda4582e6d4479fe96cc74a6224c5b2e5670f0f5) when it refers to the directory to help ease "DVC" naming confusions throughout the docs.

**Comment by shcheklein** [comment]
Sounds good, @jorgeorpinel . I think all these small things worth mentioning in some section of the Contributing guide? What do you think? Something like a "terminology guideline" (is there a better name for this)?

**Comment by jorgeorpinel** [comment]
Good idea. Maybe "terminology conventions" ...

OR it could be a new doc called **Glossary** and in the docs contribute guidelines we just mention to "utilize the terminology listed in the glossary(linked) consistently". Please assign me here to confirm (:

**Comment by jorgeorpinel** [comment]
p.s. I just noted the term "stage file(s)" is also widely used in the docs for this one.

**Comment by jorgeorpinel** [comment]
Sorry, 2 of the checkboxes in the original description weren't completed with the PR that closed this. Reopened this issue and opened PR #433
