### ISSUE TITLE
Problems with anchor links in some pages (`exp show` ref. for now)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3226]
i. Anchor links don't work once you're in https://dvc.org/doc/command-reference/exp/show. Click anything on the ToC (right sidebar) or option links from the Synopsis, for example. Consistently fails for me on all browsers, at least!

**Expected**: they should work 🙂 

- [ ] Are there any other pages with this problem?

---

ii. Loading a specific anchor in a new window (same as clicking a link from another page in docs) goes to the wrong height.

Example: https://dvc.org/doc/command-reference/exp/show#-n

![image](https://user-images.githubusercontent.com/1477535/151287770-d61f5331-424e-45dc-b970-56cc05971f5b.png)

> **Confirmations**: [Chrome](https://www.webpagetest.org/result/220127_AiDcS1_a228a0d7fd2b5279a57b3d8b74854d92/1/screen_shot/#step_1), [FF](https://www.webpagetest.org/result/220127_AiDc3E_a47df97f5ecaaf42560dca7e45ff0bf6/1/screen_shot/#step_1).

**Expected**: correct scrolling, e.g. for https://dvc.org/doc/command-reference/exp/diff#--all :

![image](https://user-images.githubusercontent.com/1477535/151288239-b9a3148d-7f55-41fd-83ae-6cdb345c3b30.png)

**Comment by julieg18** [comment]
I think I found the issue! Pushing a fix now!

**Comment by jorgeorpinel** [comment]
Thanks @julieg18 

> The code that scrolls to the desired element runs only when all the images on the page loads in
> For the fix, I'm just turning off the lazy loading in the images.

Would it be possible to change the scrolling behavior so it doesn't wait until all images are loaded instead? I mean, there was probably a reason to have that lazy loading on. Maybe just wait for the images that are been requested initially? Or would that not guarantee jumping to the right place?

Totally up to you.

**Comment by julieg18** [comment]
> Would it be possible to change the scrolling behavior so it doesn't wait until all images are loaded instead? I mean, there was probably a reason to have that lazy loading on. Maybe just wait for the images that are been requested initially? Or would that not guarantee jumping to the right place?
> 
> Totally up to you. Just wondering

It wouldn't guarentee the right place. (for example: 172px was the right spot at first to scroll to when the image was 0px tall but once the image is now 600px tall, 172px is now 600px off). Lazy loading is definitely useful and can save page load time and I'm planning to bring this issue up next doc meeting! We may not end up needing it for the docs atleast since the docs don't have that many images compared to the blog :)

**Comment by shcheklein** [comment]
Agreed, we can disable lazy load here ... or may be there other ways (allocate space with some empty div?)

**Comment by rogermparent** [comment]
I also had the thought of changing the logic to keep lazy loading, but fixing the broken behavior takes priority and since the lazy-load fix is a one-liner it can very easily be undone should we do something more robust.
