### ISSUE TITLE
`dag`: link from/to DVC Experiments guides and refs?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3230]
_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/3218#discussion_r793866795_

Should the `dvc dag` command be emphasized or at least mentioned from `dvc exp` funcionality? And vice versa

- [ ] Any other commands we want to emphasize in the context of DVC Experiments? (So far mainly `stage add` and `gc` are mentioned, I think... Maybe `metrics/plots`)

**Comment by jorgeorpinel** [comment]
WDYT @dberenbaum @iesahin ? Thanks

**Comment by dberenbaum** [comment]
Sorry, even after looking at the original comment, the motivation for this isn't clear to me. Do you mind explaining your thinking?

**Comment by iesahin** [comment]
I believe `dvc dag` is more related to `dvc stage` set of commands than `dvc exp`.
