### ISSUE TITLE
ref: `import-url/update --jobs` affects uploading with `--to-remote`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3233]
> `--jobs` (also) affects the uploading when using `dvc import-url --to-remote` so the description should be updated. This also affects `dvc update`.

_Originally posted by @daavoo in https://github.com/iterative/dvc.org/pull/3199#pullrequestreview-864414392_

**Comment by jorgeorpinel** [comment]
AFAIK --to-remote "streams" chunks of the data via the local env into the remote. Do you mean that --jobs affects this whole transferring strategy (both download and upload) but has no effect for downloading regular imports (no --to-remote) @daavoo ? Thanks

**Comment by jorgeorpinel** [comment]
I think the intuitive behavior \*shoud\* be that `--jobs` affects both downloading and uploading with or without `--to-remote`. If anyone can confirm we'll update the refs cc @dberenbaum @efiop thanks

**Comment by daavoo** [comment]
It affects both, I meant to say `--jobs` **also** affects the uploading

**Comment by jorgeorpinel** [comment]
Would you like to contribute this reference fix @daavoo ?
