### ISSUE TITLE
Postmortem: broken anchor links in `/command-reference/exp/show`

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3241]
This ticket contains a postmortem about the broken anchor links in `/command-reference/exp/show` page.

## High Level Summary

We are unsure how long the anchor links were broken (probably after #3105 was merged). We fixed it by turning off lazy loading on images.

## Timeline
Times are written in UTC.

2021-7-8 #2620 was merged, adding lazy loading to doc images (I think. It might have been when we upgraded Gatsby from 2 to 4)
2022-1-11 #3105 was merged, adding images to the bottom of the page and breaking the scrolling code. 
2022-1-27 4:09AM @jorgeorpinel noticed the issue and opened #3226
2022-1-27 12:30PM @julieg18 started her workday and spotted the issue
2022-1-27 1:30PM @julieg18 pushed a fix and opened #3229
2022-1-27 5:01PM @emre approved and merged #3229

Perf indicators:

* Time to notice: Probably about 16 days
* Time for websites team to start working on the issue: 8 hours and 21 minutes
* Fix Developed After: 1 hour
* Resolved After: 3 hours and 31 minutes

## Impact

None of the anchor links in `/command-reference/exp/show` were working. There might have other broken doc pages though (it would need to be a lengthy page with images at the bottom.)

## Root Cause Analysis

Our scrolling code moves the page to the desired element only runs when all images have been loaded in. Since images near the bottom of the page were set to lazy loading, they didn't load in (not until a user starts scrolling lower) and the scrolling code never ran, breaking the anchor links. 

## Prevention and next steps

* Maybe try to test newly updated doc pages on dvc.org after prs are merged?

cc @iterative/websites

**Comment by shcheklein** [comment]
Thanks @julieg18, that's helpful ... I would say if that part were a bit more critical we could have considered implemented something like Cypress tests? That can be a tricky thing in this case though, no sure. We can write a ticket and research if there are some simple ways to write tests for this.
