### ISSUE TITLE
prism: new or expanded DVC highlighter for Windows

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3278]
do a proper `dvc` highlighter that supports Windows (Command Prompt format, similar to Prism `powershell`)

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/3273#discussion_r805091274_

**Comment by jorgeorpinel** [comment]
CC @iterative/websites

**Comment by casperdcl** [comment]
This is effectively just `$` vs `>`, right?

**Comment by julieg18** [comment]
> his is effectively just $ vs >, right?

Possibly. Depends if we want to use powershell commands in some of our code blocks. Our `dvc` highlighter extends on `bash` and doesn't highlight windows commands properly. If we want to use powershell commands, then we'd need to create or extend our dvc highlighter to work with `powershell`, not just `bash`. 
But if we just want to focus our code blocks on just using commands that work on both `bash` and `powershell`, we can probably just update our `dvc` highlighter to just check for `$` or `>` in the beginning of a line.
