### ISSUE TITLE
plots: explicit template generation (DVC 2.9.4)

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#3295]
Document and adjust existing `plots` docs to the new way of handling templates:
https://github.com/iterative/dvc/pull/7108

**Comment by jorgeorpinel** [comment]
@pared you can just take care of the cmd ref but if you see discrepancies in the Get Started please let us know too (cc @iesahin). Thanks

**Comment by jorgeorpinel** [comment]
Hi @pared I feel like you submitted a PR for this already. Did you? If not please try to ☝🏼
