### ISSUE TITLE
start: Revise params and metrics hidden sections in GS:Experiments

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3296]
It looks like a good improvement. I think it makes sense to move both - params and metrics details up (close to the first time they are mentioned, may be combining them into one section)

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/3197#pullrequestreview-883888970_

**Comment by jorgeorpinel** [comment]
Is this closed by https://github.com/iterative/dvc.org/pull/3324 ?

**Comment by iesahin** [comment]
Yup, thank you for pointing this. @jorgeorpinel
