### ISSUE TITLE
add: new files to tracked directories

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3297]
This is a pretty basic scenario and while it's mentioned in https://dvc.org/doc/start/data-and-model-versioning#making-changes there's no specific example about it. There's https://dvc.org/doc/command-reference/add#example-directory and also https://dvc.org/doc/user-guide/how-to/update-tracked-data but neither show this specific scenario.

> From [user feedback](https://discord.com/channels/485586884165107732/943360450698043463/943647854231171082)

**Comment by daavoo** [comment]
Related https://github.com/iterative/dvc.org/issues/2952?

**Comment by jorgeorpinel** [comment]
Yes @daavoo definitely one and the same. This one is broader so should we close that one you created before in favor of this one? You were definitely first to notice though!

**Comment by walternat1ve** [comment]
would be cool if you update the docs. this is something users are interested in at least since 2021

**Comment by dberenbaum** [comment]
@walternat1ve Thanks for bringing this up. I actually think this issue has been addressed in https://dvc.org/doc/user-guide/data-management/modifying-large-datasets. Does that help you?

**Comment by dberenbaum** [comment]
Closing since this issue is complete as noted above
