### ISSUE TITLE
Support `mermaid.js` for diagrams

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3300]
[mermaid.js](https://mermaid-js.github.io/mermaid/#/) can be used to add/replace diagrams to the documentation. As Github issues and PRs are recently began to support mermaid, we can use the diagrams extensively in the docs, and maintenance becomes easier than adding images.

**Comment by jorgeorpinel** [comment]
Can it be styled/ branded?

**Comment by daavoo** [comment]
> Can it be styled/ branded?

Yes https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes

**Comment by jorgeorpinel** [comment]
Nice. Thinking about this. Is is worth integrating mermaid.js generation into our engine(s) vs. who ever wants to use it generating the graphics themselves and using the image files in the site?

**Comment by daavoo** [comment]
> Is is worth integrating mermaid.js generation into our engine(s) vs. who ever wants to use it generating the graphics themselves and using the image files in the site?

Not sure about worth it because can't tell how much effort would it take, but integrating the generation would ensure style consistency and reduce the overall size of the site (afaik it would be more lightweight than pushing images)

**Comment by rogermparent** [comment]
There's a [Gatsby Remark plugin for mermaid](https://www.gatsbyjs.com/plugins/gatsby-remark-mermaid/), so unless it's somehow broken we could likely just drop it in!

**Comment by iesahin** [comment]
> Is is worth integrating mermaid.js generation into our engine(s) vs. who ever wants to use it generating the graphics themselves and using the image files in the site?

e.g. instead of the ASCII diagram in https://dvc.org/doc/user-guide/experiment-management/sharing-experiments we can use mermaid to have a proper one. Currently creating diagrams requires another workflow, adding this to the usual Git process will work better IMO.

**Comment by jorgeorpinel** [comment]
I don't oppose this since it seems easy. I'd just like to see a list of places where we can update and/or enhance-with diagrams first. Maybe make this into an epic @iesahin ?

**Comment by iesahin** [comment]
> I'd just like to see a list of places where we can update and/or enhance-with diagrams first.

I think all pages can start with a diagram and revolve around it. Even simple diagrams may be more interesting for the user rather than a paragraph of text. 

I plan to use them for all GS pages to describe the workflow, for example. 

> Maybe make this into an epic

Yep, after adding the functionality, we can have epics.

**Comment by yathomasi** [comment]
As Roger mentioned there is already a plugin for gatsby so adding the functionality should be easy. 

So, as Jorge mentioned would it be better to list the places where we can improve or add using the mermaid. If the list is very small maybe [mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/edit/) could be enough.

I also think we may use it more once it is available.

**Comment by jorgeorpinel** [comment]
> If the list is very small maybe [mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/edit/) could be enough

I vote to try this first and if/when the no. of diagram grows, revisit making it a native engine feature.

**Comment by iesahin** [comment]
Mermaid-live-editor looks cool, but the intention behind to support mermaid is to show code blocks in `mermaid` format as diagrams, not replacing Miro or PowerPoint or however we're producing the diagrams now.

When I write a diagram description, I'd like them to appear in production without any `img` (or `![](...)`) tags. We will be able to see the content of diagrams in the file itself, this will make to update/conform them to changes much more streamlined.

**Comment by jorgeorpinel** [comment]
You could use images for now and paste the mermaid code in a comment in the markdown pages. Then once there's enough diagrams to consider this as a built-in feature it'd be easy to migrate (uncomment the code + delete the image files). I just don't think we should pre-optimize for something we're not sure we'll be using that much.

**Comment by iesahin** [comment]
If I'll go on using images now, why bother to keep a separate set of invisible and possibly misleading set of mermaid code? 😄  I'd just go on using images.

**Comment by yathomasi** [comment]
Again,
> I also think we may use it more once it is available.

@iesahin can we make a quick list of places we can replace and possibly use later, if the list seems significant enough then I also consider this as a nice to have feature.  But at the same time, if it's not significant enough then I think we don't want to bloat our engine too.
