### ISSUE TITLE
Add a new highlighter that skips lines starting with `$`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3306]
Our intention is to add some automation to document generation. Currently, for a set of commands below, we run the command and add the output by copy/paste. I think it's possible to add **semi-automated** command blocks. 

An example workflow is like: 

- Run a script `dvc-doc-runner.py` that takes the source blocks in `dvcoutput` format, get commands from the lines starting with `$`, run them and update the block by commands and outputs. Note that, as we run the script manually, there is no need for site generator (Gatsby) to run these scripts everytime. We only run them when we need. 
- Commit files that are updated by the script to Git, and submit a PR as normal. 
- The highlighter will only show the lines **without** `$`. Hence not the commands, but the outputs will be shown. 

For example, for two command blocks like: 

````
```dvc
$ dvc exp show
```
````

````
```dvctableoutput
$ git clone https://github.com/iterative/example-dvc-experiments /tmp/ede
$ cd /tmp/ede
$ dvc exp show --no-pager --json | custom-script-to-draw-table.py
<<<colored table>>>
```
````

The lines with `$` in `dvc` will be shown, but the lines with `$` in `dvctableoutput` won't be shown in the HTML output. Only the remaining part with table `<<<colored table>>>` (or output) will be shown. This will enable to automate the outputs in the UG and GS on demand, quickly. Also it won't add DVC as a dependency to the site generation. 

It can have two flavors, one derived from `dvc` that shows the command output as is, one from `dvctable` that shows the colored tables.

_Originally posted by @iesahin in https://github.com/iterative/dvc.org/issues/2770#issuecomment-1026653714_

**Comment by jorgeorpinel** [comment]
Ideally we could extend the `dvctable` highlighter hopefully without need to run any commands or clone repos? Just copy-paste the output and it colors it automatically.

> From https://github.com/iterative/dvc.org/issues/2770#issuecomment-1040948187

**Comment by iesahin** [comment]
Copy-paste doesn't work as expected, there are terminal/shell dependent control characters for colorful output and I usually redirect it first to a file, then copy the contents from an editor. We can add another control character, like `€` to run some lines in `dvc` blocks, but not show them to the reader. 

````
```dvctable
€ git clone https://github.com/iterative/example-dvc-experiments /tmp/ede
€ cd /tmp/ede
€ dvc exp show --no-pager --json | custom-script-to-draw-table.py
$ dvc exp show
<<<dvc exp show output from first 3 lines>>>
```
````

This one will run the first 3 lines, but show the line starting with `$` only, and its output.
