### ISSUE TITLE
`start`: Update `dvc run` references in various GS pages

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3309]

**Comment by jorgeorpinel** [comment]
There's already check boxes for this in https://github.com/iterative/dvc.org/issues/2076 .

**Comment by iesahin** [comment]
Yes, and I created this from that checkbox actually :)

**Comment by iesahin** [comment]
It looks most of the references are in `data-pipelines` and `params-metrics-plots` document. The latter is already rewritten, and I'll rewrite the former.

**Comment by jorgeorpinel** [comment]
Only https://dvc.org/doc/start/metrics-parameters-plots is missing now, I think.

**Comment by iesahin** [comment]
#3050 replaces that page completely.
