### ISSUE TITLE
start: update command blocks with tabs for Windows 

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3311]
- [ ] Update https://dvc.org/doc/start/data-and-model-access with tabs
- [x] Update https://dvc.org/doc/start/data-and-model-versioning - #3273
- [ ] Update https://dvc.org/doc/start/data-pipelines with tabs
- [ ] Update https://dvc.org/doc/start/experiments with tabs
- [ ] Update https://dvc.org/doc/start/metrics-parameters-plots with tabs

**Comment by jorgeorpinel** [comment]
Idk, it kind of depends on the discussions going on in https://github.com/iterative/dvc.org/pull/3273. WDYT @shcheklein ?

**Comment by shcheklein** [comment]
@jorgeorpinel I think tabs make the most sense for Windows. Not sure why we should be concerned about using them this way. Or may be I don't understand the context ... could you please clarify?

**Comment by jorgeorpinel** [comment]
@shcheklein we weren't sure whether it was worth it to make Windows tabs just to change paths such as `/tmp` which don't work on Windows but we discussed this last retro and decided to DO create those tabs. However making tabs just to change `/` for `\` we decided would be too much. For historical context see https://github.com/iterative/dvc.org/pull/3273#pullrequestreview-880425596 or just review the PR 🙂

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc.org/pull/3326#issuecomment-1083207710

> Our statistics show we have very few Windows cmd users, anyone who's interested in DVC is using it on WSL probably. I think we can deprioritize this.

Fair point but it's probably still worth it for the Get Started, as we had decided earlier. Maybe it'll help onboard more Windows users this way.
