### ISSUE TITLE
Make `<details>` blocks linkable

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3314]
> I assume ability to link to a specific section? Fair enough, but let's do it quick - just move all into section or make expandable blocks linkable - I think it should not be a problem and we could do it quick cc @iterative/websites 

From @shcheklein in #3299 

This should be doable since we use a custom component to create our expandable sections!

**Comment by jorgeorpinel** [comment]
Can they auto-expand when opening them via #anchored link ?

**Comment by julieg18** [comment]
> Can they auto-expand when opening them via #anchored link ?

I think it would be a little more difficult to implement, but still doable!

**Comment by VinayakRugvedi** [comment]
I have used this beautiful package https://www.npmjs.com/package/rc-collapse to implement and manage accordions.
@julieg18 You can probably consume this or draw some insights/inspiration from this package for your custom component.

@jorgeorpinel @julieg18 
Yeah, we can auto-expand them using #anchored link (assuming this link navigates to the section hosting these details)
The section upon mount checks if it's in the view from the fragment URL and can appropriately initialize its state which decides if the detail block should be extended or not.

I hope this helps.
Thanks!

Further, I would love to discuss and contribute in whatever scope possible
