### ISSUE TITLE
remove indentation in all code blocks in markdown files

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#334]
We use padding for first level indentation in code block since [this PR](https://github.com/iterative/dvc.org/pull/330) got merged.

For example consider this codeblock:

``````
```dvc
    $ pip install gitpython
    $ pip install git+git://github.com/iterative/dvc
```
``````
#### Output

![Screenshot from 2019-05-15 12-59-49](https://user-images.githubusercontent.com/35191225/57756670-5ecaa900-7711-11e9-92ba-ddf1480a8078.png)

#### Expected Output

![Screenshot from 2019-05-15 13-00-37](https://user-images.githubusercontent.com/35191225/57756712-76099680-7711-11e9-8d93-dd25423dd4f0.png)

This can be fixed by removing the unnecessary 4 spaces indentation we have given under every code block.
Since there are a lot of files, I recommend a smart way to fix it. For example a bash script could be made to run over all `.md` files and remove the indentation.
Keep in mind that we don't have to completely remove indentation. Just the first level. For example:
``````
```js
    function sum(a, b) {
        return a+b
    }
```
``````
converts to:
``````
```js
function sum(a, b) {
    return a+b
}
```
``````
not this:
``````
```js
function sum(a, b) {
return a+b
}
```
``````

**Comment by ryokugyu** [comment]
I want to work on this issue. Please assign this task to me.

**Comment by shcheklein** [comment]
hi, @ryokugyu ! That would be great. Thank you. I'll assign it to myself to lock the issue. Feel free to proceed with it.

**Comment by ryokugyu** [comment]
I wrote a script for the removal of unnecessary indentation. But there is too much inconsistency in the files.

Have to remove them manually. Will you suggest me something else?

**Comment by shcheklein** [comment]
> Will you suggest me something else?

Do you mean something else to work on?

**Comment by ryokugyu** [comment]
I will be manually removing them. 
For future, mention on contribute doc, not to use 4-space indentation on documentation.

**Comment by shcheklein** [comment]
Fixed  by @ryokugyu .
