### ISSUE TITLE
ref: multi-experiment support for `exp push/pull`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3340]
Please update https://dvc.org/doc/command-reference/exp/push and [pull](https://dvc.org/doc/command-reference/exp/pull) (and any other refs. affected) ~~but please create an issue still so we can check whether other docs need updates too.~~

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc/issues/7206#issuecomment-1061428244_

p.s. related to https://github.com/iterative/dvc/issues/5489

**Comment by jorgeorpinel** [comment]
I guess other than thee cmd ref. we may need to update https://dvc.org/doc/user-guide/experiment-management/sharing-experiments cc @iesahin want to take that?

**Comment by karajan1001** [comment]
related to https://github.com/iterative/dvc/issues/5489

> * [ ]  I guess other than thee cmd ref. we may need to update https://dvc.org/doc/user-guide/experiment-management/sharing-experiments cc @iesahin want to take that part?

**Comment by dberenbaum** [comment]
Opened #3593 to address. It looks like we missed many points in the guide to update.

@karajan1001 Let's make it part of the process to review all of this as soon as the core PR is merged 🙏 .
