### ISSUE TITLE
add detail for DVC version in `dvc version` command

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#335]
```dvc
$ dvc version    
DVC version: 0.40.0+45f94e
Python version: 3.6.7
Platform: Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
```

The DVC version detail can be elaborated and made clearer to understand. An explanation of the git hash can be one addition.

**Comment by shcheklein** [comment]
Some context and explanations: https://discordapp.com/channels/485586884165107732/565699007037571084/578083097099239424
