### ISSUE TITLE
how: move `.dvc` files when their data is not checked out

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3354]
From https://github.com/iterative/dvc/issues/7318:

> Assume that the file `video121.mpeg` is tracked by `video121.mpeg.dvc`. If one wants to move it to folder `subdir` it depends on whether `video121.mpeg` is checked out.
> 
>   >  1. If `video121.mpeg` is checked out, then `dvc move video121.mpeg subdir/` must be used to do it safely.
>  >
>  >  2. If `video121.mpeg` is not checked out, then `mv video121.mpeg.dvc subdir/` can be used. `dvc move video121.mpeg.dvc subdir/` does not work.

Can we document somewhere that doing `mv video121.mpeg.dvc subdir/` is safe when files aren't checked out? Possible places to document this:

* https://dvc.org/doc/user-guide/how-to/update-tracked-data
* https://dvc.org/doc/command-reference/move

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/3354#issuecomment-1081293810 below.

**Comment by jorgeorpinel** [comment]
Interesting.

Shouldn't `dvc move video121.mpeg subdir/` work with or without the data being checked out though?

**Comment by dberenbaum** [comment]
> Shouldn't `dvc move video121.mpeg subdir/` work with or without the data being checked out though?

🤔 I think it's a good idea, but it's not what I would expect today. Currently, all DVC operations today operate on the data that is available in the workspace, including `dvc move`. From https://dvc.org/doc/command-reference/move:

> [dvc move](https://dvc.org/doc/command-reference/move) behaves like mv src dst, moving src to the given dst path, but it also renames and updates the corresponding [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) file appropriately.

So moving `src.dvc` file without moving `src` itself seems out of scope of the current command. I don't see anywhere that the docs indicate that this behavior is supported, but I could be missing somewhere.

**Comment by jorgeorpinel** [comment]
> moving src.dvc file without moving src itself seems out of scope

Wait I didn't mean that exactly @dberenbaum . I meant `dvc move` could still work if the data isn't checked out by just moving the .dvc file to the new location. Then when you `fetch/pull` the data will be placed there. This is a core question though.

**Comment by dberenbaum** [comment]
> In fact moving the .dvc file manually works even if the data is checked out right? It'll just change the state of the project.

Not sure I follow. This seems like it would lead to a lot of unexpected behavior. The checked out data would become untracked, and the .dvc file would show that the data is missing.

Not sure this is important, though. It sounds like we are in agreement on the changes.

> This may also deserve some notes in cmd refs? E.g. it's not 100% clear from https://dvc.org/doc/command-reference/move that the data file is expected to be present.

Sounds good.

> Wait I didn't mean that exactly @dberenbaum . I meant `dvc move` could still work if the data isn't checked out by just moving the .dvc file to the new location. Then when you `fetch/pull` the data will be placed there. This is a core question though.

Yup, makes sense. In that case, my point was that you are not `moving src to the given dst path` since `src` does not exist locally, but it seems more like a semantic distinction than a meaningful one.

**Comment by jorgeorpinel** [comment]
> > dvc move could still work if the data isn't checked out by just moving the .dvc file to the new location
>
> seems more like a semantic distinction

So should we open a core issue to discuss that with the DVC team or nah?

> > moving the .dvc file manually works even if the data is checked out
>
> seems like it would lead to a lot of unexpected behavior

If the data is referenced in a dvc.yaml file yes but my point is you * could * do it -- up to you if you break your own project 😆 . But again, if the data is NOT checked out moving the .dvc file manually can also cause that unexpected behavior (if you don't update dvc.yaml files) so... to double check do we want to recommend this method? Does `dvc move` update dvc.yaml files too???

You know what let me try all this... ⌛

**Comment by jorgeorpinel** [comment]
OK I tried it and moving the .dvc file does work regardless of whether the data is checked out or not. The project status changes and if you `dvc checkout`, the data is placed in the right location. If the data was previously checkout in the old location, that one is deleted.

The only issue is that the .gitignore file doesn't get updated this way (unlike with `dvc move` which only works when the data is checked out) so it could lead to accidentally committing data to Git.

**Comment by jorgeorpinel** [comment]
In summary I think we should update https://dvc.org/doc/user-guide/how-to/update-tracked-data to cover moving tracked data **in general** -- both via `dvc move` and manually WDYT?

**Comment by iesahin** [comment]
I think `dvc move` could work with `.dvc` files and update the tracked file too. 

Currently it reports an error,

```
$ dvc move images.tar.gz.dvc ..
ERROR: failed to move 'images.tar.gz.dvc' -> '..' - DVC file 'images.tar.gz.dvc' cannot be an output.
```

but just moving the `.dvc` file only (if the tracked file is not found) and updating `.gitignore` should be easier.

**Comment by jorgeorpinel** [comment]
Yeah... I guess @iesahin is right. Let's not encourage unintended problems.

@dberenbaum do we want to document the manual process since it involves editing .gitignore as well (whether the data is cached or not) ?

Otherwise feel free to close this or transfer it to core @dberenbaum 

As for mentioning `move` in the existing How-to, see #3403

**Comment by dberenbaum** [comment]
Sounds good. The core issue is already there in #7318, so let's just close this one.
