### ISSUE TITLE
guide: explain technical details of exp commands

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3364]
Some of the experiment commands can take a long time to run, and it's unclear why without knowing the inner workings of the commands.

From https://discord.com/channels/485586884165107732/485596304961962003/953651174639276062:

> Also I would love to read up on what exactly is happening under the hood with each command. I.e. the fact that untracked files have anything whatsoever to do with dvc's inner workings is super useful to know

**Comment by dberenbaum** [comment]
More narrowly, it seems like it would be useful to mention that untracked files can slow the exp commands.

**Comment by jorgeorpinel** [comment]
> mention that untracked files can slow the exp commands

Moved to new task in #2911

Can you elaborate on how/why this happens though? Thanks
