### ISSUE TITLE
Update `cml` container images and workflows on blog posts

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/dvc.org#3373]
The following blog posts contain references to deprecated `cml-py3` container images, which should probably be amended or, at least, supplemented with a callout providing historical context.

### `2020-07-07-cml-release.md`
https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-07-07-cml-release.md?plain=1#L124

https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-07-07-cml-release.md?plain=1#L145

### `2020-07-16-devops-for-data-scientists.md`

https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-07-16-devops-for-data-scientists.md?plain=1#L261

### `2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md`
https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md?plain=1#L78

https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md?plain=1#L90

https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md?plain=1#L102

### `2020-11-25-november-20-community-gems.md`
https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2020-11-25-november-20-community-gems.md?plain=1#L192

### `2021-03-03-dvc-2-0-release.md`
https://github.com/iterative/dvc.org/blob/154f114adf42831f3b82db79bd6b732ceb26aa6b/content/blog/2021-03-03-dvc-2-0-release.md?plain=1#L83

**Comment by shcheklein** [comment]
@iterative/cml can someone from the CML team take it?

**Comment by casperdcl** [comment]
Yes "CML Release" and "CML Self hosted runners on demand" are in the top 10 most visited blog pages here.

**Comment by 0x2b3bfa0** [comment]
Tentative fix on #3375
