### ISSUE TITLE
admonitions titles take too much precious space 

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#3381]
<img width="714" alt="Screen Shot 2022-03-23 at 2 17 25 PM" src="https://user-images.githubusercontent.com/3659196/159797335-700060c3-ed6e-45e8-90b4-4fc9c7181465.png">

It's 40% of the whole item. I would say icon alone should be enough. Or show the tooltip when you hover.

**Comment by jorgeorpinel** [comment]
I vote for icon alone on the left side for now.

**Comment by julieg18** [comment]
Makes sense! Would we like to make the title optional or take it off entirely? Both can be done pretty easily :)
