### ISSUE TITLE
admonitions: replace current ad hoc notes

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3382]
> Follow-up to https://github.com/iterative/dvc.org/issues/3153 / https://github.com/iterative/cml.dev/pull/210

Many are in Markdown block quotes, often starting with "Note:" or "Note that" or with an [emoji](https://dvc.org/doc/user-guide/contributing/docs#general-language-guidelines). Sometimes emojis are used in short paragraphs (not in block quotes) too which could be replaces as well.

~~Also, Update Docs Contrib guide to include [usage info.](https://github.com/iterative/cml.dev/pull/210) (and note https://github.com/iterative/dvc.org/pull/3422#discussion_r845022361)~~ UPDATE: https://github.com/iterative/dvc.org/issues/3506

**Comment by jorgeorpinel** [comment]
Note: done for DcLive in https://github.com/iterative/dvc.org/pull/3379 !

**Comment by iesahin** [comment]
What's the priority of this?

**Comment by jorgeorpinel** [comment]
None really, let's take it as we go.
