### ISSUE TITLE
details: unique anchors shouldn't change with content order

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3383]
> Follow-up to https://github.com/iterative/dvc.org/issues/3314

Per https://github.com/iterative/dvc.org/pull/3329#issuecomment-1077311398, the way unique anchors are generated for `<details>` blocks (based on the first child's content + an incremental index if needed) can be problematic. Eg. a block is no 1 in the page, someone links to it, and later the content get's rearranged such that the block is now no 2. The link is now incorrect (goes to a previous block, not the one we want).

Maybe we should require an `id` or some other prop that's supposed to be unique and use it in the anchor somehow. This way they're predictable and stable.

Additionally, should we use a `title` prop for the anchor base instead of the first child's text?

**Comment by jorgeorpinel** [comment]
p.s. not a high priority probably but it could eventually cause super low-visibility bugs. For now let's try not to repeat headers in `<details>` blocks! Cc @iesahin

**Comment by jorgeorpinel** [comment]
> should we use a title prop for the anchor base instead of the first child's text?

Can you put emojis in `title` though? 😅 

![image](https://user-images.githubusercontent.com/1477535/159864995-1fc65298-9884-4cbc-9c5d-71c4e74b899b.png)

**Comment by yathomasi** [comment]
> Maybe we should require an `id` or some other prop that's supposed to be unique and use it in the anchor somehow. This way they're predictable and stable.

#3352 was for the approach mentioned but was closed in favor of #3329. The considerations were [mentioned before the merge](https://github.com/iterative/dvc.org/pull/3329#issuecomment-1070953981). 
We made the assumption such changes within a page will be **rare** and also we can try to make the titles unique on their own.

> Additionally, should we use a `title` prop for the anchor base instead of the first child's text?

Yes, sure it will be consistent with other blocks as well. I will be submitting a pr on this.

> Can you put emojis in title values though? 😅

Yes. It should be working just fine. 

 PS: if we are still thinking, we should be using `id` for making the link unique then we should proceed with the idea early because we also wouldn't want the current links with numbering also expire don't work.

**Comment by jorgeorpinel** [comment]
> The considerations were https://github.com/iterative/dvc.org/pull/3329#issuecomment-1070953981.

Yes but as you can see my realization and [reply to that](https://github.com/iterative/dvc.org/pull/3329#issuecomment-1077311398) happened after the merge 🙂  thus this issue.

> We made the assumption such changes within a page will be rare

Unfortunately it's not that rare. We reorder content sections sometimes -- wouldn't want to be limited in that aspect anyway.

> I will be submitting a pr on this.
we should proceed with the idea early

Agree. Thanks and sorry for the unintended back and forth!

**Comment by yathomasi** [comment]
> > I will be submitting a pr on this.
> > we should proceed with the idea early
> 
> Agree. Thanks and sorry for the unintended back and forth!

So, you mean we should consider the `id` as prop which we will set manually to make it unique ?

**Comment by jorgeorpinel** [comment]
Yes, both `title` and `id` -- maybe the latter is optional just for when we want/need to make it unique.

**Comment by yathomasi** [comment]
> Yes, both `title` and `id` -- maybe the latter is optional just for when we want/need to make the anchor unique.

The solution for this was kinda already submitted on #3352 
That was under review before it was closed. Further improvement can be made on that.
@jorgeorpinel can you take a quick look over that and decide a similar implementation should work?
