### ISSUE TITLE
auto file deletion on cloning in windows

### ISSUE THREAD

**Issue by sanidhyamangal** [iterative/dvc.org#339]
I tried to clone this repo on multiple machines running on windows platform, but due to some notations in the format of <filename>:<additiontag>.md it was automatically deleted and instead a cache file was downloaded creating havoc.

**Comment by shcheklein** [comment]
@sanidhyamangal good catch! Looks like we need to rename the files and drop `:` in them.

**Comment by sanidhyamangal** [comment]
@shcheklein  I think my pr #332 resolves this issue and since I have updated ```sidebar.json``` as well so I don't think there are any other changes.
