### ISSUE TITLE
guide/analytics: mention IP

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#3397]
https://dvc.org/doc/user-guide/analytics#what is missing mention of user's IP address

/CC @skshetry @JIoJIaJIu @iterative/docs

**Comment by casperdcl** [comment]
from @shcheklein:

We don't actually want or need to collect IPs, so should remove this. Should this be issue be moved to the core DVC repo?

**Comment by skshetry** [comment]
It's not an issue on the DVC side.

**Comment by iesahin** [comment]
Does DVC collect IP addresses in the most recent version? @skshetry

**Comment by casperdcl** [comment]
I think @skshetry is trying to say DVC itself doesn't but the upstream analytics package might and we should change it.

Who can look into this?

**Comment by iesahin** [comment]
From the [looks of it](https://github.com/iterative/dvc/blob/main/dvc/analytics.py), IP addresses are a side effect of using `requests` to send the report, and not collected explicitly. There is this `user_id` that might be problematic though. 

I think we should fix IP on the side of analytics server.

**Comment by jorgeorpinel** [comment]
> Who can look into this?

Transfer to core DVC repo I guess?

**Comment by iesahin** [comment]
We decided to keep the current information as-is, as we're planning to remove GA. (See [comment](https://github.com/iterative/dvc.org/pull/3401#discussion_r843305650))
