### ISSUE TITLE
guide: extract part of  the`config` cmd ref.

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#340]
The [Configuration sections](https://dvc.org/doc/commands-reference/config#configuration-sections) is too long for the cmd ref. Probably the best route is to extract the parts of the current cmd ref description and all the config options into a new User Guide, and leave the rest in the cmd ref.

> From https://github.com/iterative/dvc.org/pull/331#pullrequestreview-236975854

---

UPDATE from https://github.com/iterative/dvc.org/issues/1368#issuecomment-634456922:

> It's not a well known or documented feature of DVC, but DVC merges sections with same name from different configs

^ This can be part of the intro or index to the configuration guide.

- [x] Include basic remote storage config info and/or link to https://dvc.org/doc/user-guide/data-management/remote-storage

**Comment by ryokugyu** [comment]
@shcheklein anyone working on it? 
if not please assign me this issue.

**Comment by shcheklein** [comment]
@ryokugyu no, but let's hold on for a while. We are still deciding on the exact structure. Are you looking for something next to contribute?

**Comment by ryokugyu** [comment]
@shcheklein yes, i am looking for something to contribute.

**Comment by shcheklein** [comment]
How about this one - https://github.com/iterative/dvc.org/issues/306 ? It's a good one, with a nice description and really valuable. Just mention that you are working on it if you decide to take it. Thanks :)

**Comment by ryokugyu** [comment]
sure, let me dig it. i will need some help for this.
I am working on it.

**Comment by ryokugyu** [comment]
@shcheklein is the structure decided?

**Comment by shcheklein** [comment]
@ryokugyu no, not yet. @jorgeorpinel has simplified the config section significantly, so this is issue not that pressing now.

**Comment by jorgeorpinel** [comment]
I've updated the issue description to include.

> Probably the best route is to extract the parts of the current cmd ref description and all the options into a new User Guide, and leave the rest in the cmd ref.

What do you guys think? Sorry took so long!

**Comment by shcheklein** [comment]
@jorgeorpinel yep, agreed. I would start probably by writing User Guide and taking some parts from the commands reference. When it's ready we'll clean the CR sections and put the appropriate links.

**Comment by jorgeorpinel** [comment]
@ryokugyu still around/interested?

**Comment by ryokugyu** [comment]
@jorgeorpinel Still around 😄 Was busy with placement session, got placed today only! 😺  Let's work on this.

**Comment by jorgeorpinel** [comment]
All yours @ryokugyu ! Please lmk if you need any more details. You can also find me on Discord as **jorgeorpinel**.

**Comment by jorgeorpinel** [comment]
p.s. congrats on your placement!

**Comment by jorgeorpinel** [comment]
Another important aspect to include, from https://github.com/iterative/dvc.org/issues/1368#issuecomment-634456922 👍🏼 

> if we define a remote (name and all settings) in a local config (for security concerns) all other team members have to agree on the url and potentially name for the remote as well.
It's not a well known or documented feature of DVC, but DVC merges sections with same name from different configs...
in the regular .dvc/config
in the local config - .dvc/config.local
...
same idea, but you should be using --system or --global configs
the config behavior could use some documentation

Also relates to #2866

**Comment by dberenbaum** [comment]
Lowering priority
