### ISSUE TITLE
blog/cml: docker GPU usage

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#3408]
from https://discuss.dvc.org/t/cml-self-hosted-runners-on-demand-with-gpus/462/2 - `docker run` commands may be missing `--gpus all`

**Comment by 0x2b3bfa0** [comment]
Right solution, wrong description?

**Comment by 0x2b3bfa0** [comment]
Legacy containers had `cml-runner` as the default command; hence, there was no need to supply it. The new ones require the [sub]command to be explicitly set.
