### ISSUE TITLE
`exp`: CI runs require unshallow clone (fetch-depth: >1)

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3416]
Summary: `dvc exp` commands will not run in CML or other Github actions (and probably the same on other Git servers?) because they will only fetch the head commit by default, which is insufficient for internal `git merge`s. The solution is in https://github.com/iterative/dvc/issues/7547#issuecomment-1088702706.

Not sure where to document this or even whether it belongs in DVC, CML, or both. @casperdcl Maybe you have thoughts?

**Comment by casperdcl** [comment]
For CML workflows, [`cml ci`](https://cml.dev/doc/ref/ci) is best.

In non-CML cases, unshallow clones are needed (`actions/checkout` with `fetch-depth: 0`)

**Comment by dberenbaum** [comment]
I never noticed `cml ci` before, looks great. I'm still unsure where it would be best to recommend using this when running `dvc exp` commands on cml or other ci workflows.

**Comment by daavoo** [comment]
> I'm still unsure where it would be best to recommend using this 

What about creating a new section in https://dvc.org/doc/user-guide/troubleshooting , catching the specific exception on DVC side, and make it point to that URL

**Comment by jorgeorpinel** [comment]
Which `exp` commands/ scenarios exactly do not run in shallow clones? Thanks

**Comment by jorgeorpinel** [comment]
p.s. I'm guessing mostly `exp branch/apply`? If so we can make a small note in those refs and in https://dvc.org/doc/user-guide/experiment-management/persisting-experiments

**Comment by dberenbaum** [comment]
No, unfortunately even `exp run` (see the discussion linked from the original comment) needs a non-shallow clone.

**Comment by jorgeorpinel** [comment]
OK. Hmmm I'm not sure we need to much of a change other than perhaps a small note in [asdfasdfasfa](https://dvc.org/doc/user-guide/experiment-management/experiments-overview) and https://dvc.org/doc/command-reference/exp (/init). Seems like an edge case, or have you noticed this being a common issue out there outside of CML?

https://cml.dev/doc/cml-with-dvc should probably note this and recommend `cml ci`? Cc @casperdcl

**Comment by daavoo** [comment]
> Seems like an edge case, or have you noticed this being a common issue out there outside of CML?

It's an issue in many CI scenarios (with or without CML) because the default behavior in both GitHub (https://github.com/actions/checkout) and GitLab (https://docs.gitlab.com/ee/ci/large_repositories/#shallow-cloning) is a shallow clone.

**Comment by casperdcl** [comment]
> Not sure where to document this or even whether it belongs in DVC, CML, or both

definitely docs in both because

> It's an issue in many CI scenarios (with or without CML).

Makes sense to put in:

- [ ] https://dvc.org/doc/user-guide/experiment-management/experiments-overview
- [ ] https://dvc.org/doc/command-reference/exp
- [x] [cml.dev/doc/cml-with-dvc](https://cml.dev/doc/cml-with-dvc) (good catch; thx) https://github.com/iterative/cml.dev/pull/223
