### ISSUE TITLE
docs(command-reference): `plots` example has unrecognized arguments

### ISSUE THREAD

**Issue by lcbm** [iterative/dvc.org#3425]
**Description**

In the  [plots#example-tabular-data](https://dvc.org/doc/command-reference/plots#example-tabular-data) command reference documentation, the user is instructed to run the command below in order to plot the difference of a metric between the current project version and the previous commit:

```
$ dvc plots diff -d <file> HEAD^
# the expected output should be something like: 
file:///Users/usr/src/dvc_plots/index.html
```

Considering that the `-d` argument for the `dvc plots` command does not exist, the user is confronted with the following:

```
$ dvc plots diff -d <file> HEAD^
ERROR: unrecognized arguments: -d
...
```

**Steps for Reproduction**

Follow the instructions in the [plots#example-tabular-data](https://dvc.org/doc/command-reference/plots#example-tabular-data) command reference documentation.

**Environment information**

```
λ dvc doctor
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
Supports:
	hdfs (fsspec = 2022.3.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2022.3.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: ssh, local
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git
``` 

**Additional Information (if any):**

N/A

**Comment by lcbm** [comment]
I'll be fixing this issue, forking repo right now :)

**Comment by jorgeorpinel** [comment]
Thanks @lcbm
