### ISSUE TITLE
Icons for admonishments get parsed into first HTML element

### ISSUE THREAD

**Issue by RCdeWit** [iterative/dvc.org#3429]
https://github.com/iterative/dvc.org/pull/3371 introduced admonishments. While very nice, I ran into a few oddities while using them. Right now I am incorporating them through raw HTML rather than MD.

```
<admon type="warn">
In this example we are using a <code>t2.micro</code> AWS EC2 instance. At the time of writing this is included in the AWS free tier. Make sure that you qualify for this free usage to prevent unexpected spending. When you specify a bulkier <code>cloud-type</code>, your expenses will rise.
</admon>
```

Because backticks don't get parsed within the HTML element (or e.g. `[link](ref)`) I simply used `<code></code>` this has the side effect of prepending a warning emoji to the first code element:

![Screenshot 2022-04-08 at 12 23 29](https://user-images.githubusercontent.com/7165065/162417879-ae77ed79-ab65-4772-8fbd-dbfbb7ffcc46.png)

I circumvented this by explicitly using a `<p>` element, but I'm not sure what the intended behavior here is.

```
<admon type="warn">
<p>
In this example we are using a <code>t2.micro</code> AWS EC2 instance. At the time of writing this is included in the AWS free tier. Make sure that you qualify for this free usage to prevent unexpected spending. When you specify a bulkier <code>cloud-type</code>, your expenses will rise.
</p>
</admon>
```

**Comment by daavoo** [comment]
It also works if you add some empty lines:

```
<admon type="warn">

In this example we are using a <code>t2.micro</code> AWS EC2 instance. At the time of writing this is included in the AWS free tier. Make sure that you qualify for this free usage to prevent unexpected spending. When you specify a bulkier <code>cloud-type</code>, your expenses will rise.

</admon>
```

**Comment by daavoo** [comment]
> It also works if you add some empty lines:
> 
> ```
> <admon type="warn">
> 
> In this example we are using a <code>t2.micro</code> AWS EC2 instance. At the time of writing this is included in the AWS free tier. Make sure that you qualify for this free usage to prevent unexpected spending. When you specify a bulkier <code>cloud-type</code>, your expenses will rise.
> 
> </admon>
> ```

This also makes markdown syntax (i.e. backticks links) work

**Comment by RCdeWit** [comment]
Oh, that also fixes the URLs that didn't get parsed. Interesting!
Am I misunderstanding the mechanics? I.e.: is this how we want it to work?

**Comment by rogermparent** [comment]
> is this how we want it to work?

It's an unfortunate downside of using `gatsby-transformer-remark` in our engine, as it's not quite built for custom components like something like MDX is, the parser is very finicky about how components are written.

**Comment by julieg18** [comment]
> It's an unfortunate downside of using gatsby-transformer-remark in our engine, as it's not quite built for custom components like something like MDX is, the parser is very finicky about how components are written.

Correct! Empty lines are a must when using our custom HTML components. Since I don't think there is anything we can do about it on our end, going to go ahead and close this issue!
