### ISSUE TITLE
`exp`: baseline -> parent [term]

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3432]
The docs in pages like https://dvc.org/doc/command-reference/exp/list and https://dvc.org/doc/command-reference/exp/show seem to use both parent and baseline to describe the commit from which an experiment derives. We should decide on a single term and use it consistently.

**Comment by jorgeorpinel** [comment]
Yes. We introduced "baseline" more recently in the User Guide and then into some option descriptions in the Cmd Ref and now we have both terms.

Q. Are they always interchangeable? I vote for "baseline", but we should keep "parent" if it makes more sense in specific contexts (as long as "baseline" is also used nearby, ideally).

Cc @iesahin thouoghts?

**Comment by jorgeorpinel** [comment]
> "Parent" is more implementation-based (used by tech team in cmd refs).

If we go for "baseline" we probably want to update the tool's help outputs as well? I think that phrases like "parent commit" are used in a few places.

**Comment by daavoo** [comment]
> > "Parent" is more implementation-based (used by tech team in cmd refs).
> 
> If we go for "baseline" we probably want to update the tool's help outputs as well? I think that phrases like "parent commit" are used in a few places.

The issue I see is that in data science "baseline" has an established meaning and I think it doesn't match the meaning in DVC context.

**Comment by jorgeorpinel** [comment]
> in data science "baseline" has an established meaning

What's that? From what I can see [here](https://datascience.stackexchange.com/a/30914/82454) it's pretty close to the main use case of `dvc exp`.

> A baseline is the result of a very basic model/solution. You generally create a baseline and then try to make more complex solutions in order to get a better result.

**Comment by daavoo** [comment]
> What's that? From what I can see [here](https://datascience.stackexchange.com/a/30914/82454) it's pretty close to the base use case of dvc exp

Let's say you are in a DVC project where the current status is an already complex model (let's say it has `conv_units=128`). 

If you run `dvc exp run --set-param conv_units=64`, we would be referring as `basline` to an experiment that, IMO, doesn't fit the description:

> A baseline is the result of a very basic model/solution. You generally create a baseline and then try to make more complex solutions in order to get a better result.

**Comment by jorgeorpinel** [comment]
OK if "baseline" implies very basic (even when that's subjective), then let's go with "parent". Agree @dberenbaum @iesahin ?

**Comment by dberenbaum** [comment]
Yup, sounds good. Thanks @jorgeorpinel @daavoo!

**Comment by dberenbaum** [comment]
This hasn't seemed like it's caused much confusion. Closing.
