### ISSUE TITLE
Sentry error `Duplicate slug:`

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#3463]
There are sentry errors mentioning duplicate slug on some pages.
[Link to error](https://sentry.io/organizations/iterative/issues/3218353592/?referrer=slack)

**Comment by jorgeorpinel** [comment]
Can't access that link. Can you list the pages that cause duplicate slugs? Thanks

**Comment by julieg18** [comment]
> Can't access that link. Can you list the pages that cause duplicate slugs? Thanks

None of the pages actually have duplicate slugs. But for some reason, Sentry is still sending the error on pages that should be working correctly. For now, we're still looking into why this error is happening and none of the pages need to be updated :)

**Comment by shcheklein** [comment]
Closing as stale
