### ISSUE TITLE
how: mention how to `gc` in share-a-dvc-cache

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3464]
See https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache

Running `gc` with shared cache setup can be dangerous (i.e. https://github.com/iterative/dvc/issues/7610)

We should mention the appropriate options (i.e. https://github.com/iterative/dvc/issues/7610#issuecomment-1104832471)

**Comment by jorgeorpinel** [comment]
Good find. We probably just need a warning (admonition) about it in that page? Plus we could take the opportunity to update the existing notes in that doc to proper admonitions 😬

**Comment by jorgeorpinel** [comment]
UPDATE: I see that's exactly what #3467 does 🙂
