### ISSUE TITLE
start: Update dvclive screenshots for more readability in Visualization

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3470]
The images under the [DVCLive section](https://dvc.org/doc/start/experiments/visualization#autogenerating-plots-from-deep-learning-code) should have more readable axis labels. (See [review comment](https://github.com/iterative/dvc.org/pull/3050#discussion_r850526328 ))

**Comment by jorgeorpinel** [comment]
TBH I thought that the top text with a sample of the plots data you had manually added. That's pretty unreadable so we could just remove it but keeping it is also OK since the tool does print that.

Otherwise I guess the image gives a general idea of plots being shown so it's probably OK.
