### ISSUE TITLE
embed the video on the 'doc' page itself

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc.org#349]
Stumbling upon this page https://dvc.org/doc/understanding-dvc/resources.
![dvc](https://user-images.githubusercontent.com/16274905/57963509-b865ea00-7942-11e9-9e6d-1f69118430fd.PNG)

The links look like a static image. And, also upon clicking on the image, we are redirecting to YouTube page. 

We can embed the video on the DVC page itself, rather than opening a new target. 
It will impact user browsing experience.

**Comment by shcheklein** [comment]
@ryokugyu sounds good! I would also improve the formatting a little bit - use table for videos? or move titles above videos to improve readability.

**Comment by ryokugyu** [comment]
I will suggest:

- Position the video in the middle of the page. Something like, 
<iframe width="560" height="315" src="https://www.youtube.com/embed/4h6I9_xeYA4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
- If we embed the video from YouTube itself, no need to add titles. Still, if anyone wants to add title, it must be in <bold>.
- And most importantly, if any links from outside the website, please set _target=blank.
