### ISSUE TITLE
guide: move "Privacy Policy for Access to Google APIs" into GDrive section

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc.org#3517]
I've found this page that seems to be missing in dvc.org sidebar: https://dvc.org/doc/user-guide/privacy
Was it hidden for a reason or it should be added to the sidebar?
![image](https://user-images.githubusercontent.com/6797716/167175302-d6992c1b-304d-4d9d-bb16-b1e21216526b.png)

**Comment by shcheklein** [comment]
It was intentional, now I think we can move as a subsection under the GDrive page itself and change redirects accordingly.

**Comment by iswarmondal** [comment]
Hey is this issue still open? I'm new to open source and want to have a try on this.
What do you say @shcheklein?

**Comment by jorgeorpinel** [comment]
Feel free to @iswarmondal . Lmk if you have questions. Thanks!

**Comment by iswarmondal** [comment]
@jorgeorpinel sure thanks.

**Comment by L-theorist** [comment]
Is the issue closed or are you at it @iswarmondal?
