### ISSUE TITLE
rewriting install.md

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc.org#356]
re-writing install.md for better readability and enhanced user experience.
 
https://github.com/iterative/dvc.org/blob/master/static/docs/get-started/install.md

in this manner [nodejs-package-manager-documentation](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages)

Rather than using the hidden code snippets, a section for each type of installation.

After rewriting, the old and new pages are like this
![Screenshot (23)](https://user-images.githubusercontent.com/16274905/57986455-dfcbcc80-7a92-11e9-91b6-13dd6c8d83d9.png)

**Comment by shcheklein** [comment]
I think it would complicate navigation and break the point of the get started.

Get started is made to be:

- really simple to read and follow - each page should be one-two screens at most.
- it covers the most common flow (with expandable sections for advanced cases). In this case pip is considered the best way (arguably) to install DVC and all other options should be considered if you really need them. The point is - all these sections are not made equal and there is a good reason to collapse some of them and emphasize another.

Also, it's far from obvious which option is easier - to see all options at once and click it, or scroll the whole page. We can use the nav menu to the right but it would be too complicated and hard to read as well.

**Comment by algomaster99** [comment]
@shcheklein In my opinion, accordions are a great idea show installation instructions! There's one suggestion though. We can close other sections, if one is triggered. This could be a better way to emphasize the instructions. I am not sure though :sweat_smile: .

**Comment by shcheklein** [comment]
closing this for now. @algomaster99 don't think it's a major improvement and/or a priority right now to be honest. Thanks for the suggestion though 👍
