### ISSUE TITLE
style: remove H4 **Usage** blocks from API and DVCLive refs.

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3568]
The main use of H4s now is **Usage** headers in the API and DVCLive references (which can easily be changed to H2 or H3 indeed). Cc @daavoo

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/issues/3536#issuecomment-1130310008_

**Comment by jorgeorpinel** [comment]
@daavoo I'm taking care of the API ref in #3569, want to do the same for DVCLive?

**Comment by daavoo** [comment]
> @daavoo I'm taking care of the API ref in https://github.com/iterative/dvc.org/pull/3569, want to do the same for DVCLive?

Will do

**Comment by shcheklein** [comment]
@jorgeorpinel @daavoo what is the priority for this? Please let's be mindful about the large items and that help is needed in a lot of places.

**Comment by jorgeorpinel** [comment]
Not a priority at all. But I already took care of it in #3569 (sorry for the distraction @daavoo) -- took a couple min.
