### ISSUE TITLE
blog: add RSS link

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#3570]
There's an RSS feed apparently (https://dvc.org/blog/rss.xml). Should add the link next to the email signup?

/CC @rogermparent

**Comment by jorgeorpinel** [comment]
I assume this is for the blog? And we're exploring CMS options so may not be relevant soon.

**Comment by rogermparent** [comment]
It'll still be relevant, most if not all of the CMSes we're exploring are headless, and will feed their data into Gatsby to be consumed by `gatsby-plugin-feed`.

**Comment by rogermparent** [comment]
Confirmed with a search that there's no link anywhere! I'll make a quick PR to pop one in.
