### ISSUE TITLE
Remove "please"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3571]
> On the opposite end of #1394

Should we remove and avoid "please" from all or parts of the docs? Reasons

- It's unnecessary as long as our docs are already friendly
- We don't currently use it consistently so the tone changes from page to page

Thoughs @iterative/docs ? May apply to other content as well.

**Comment by BhaswatiRoy** [comment]
Hello @jorgeorpinel 
Do you mean removing "please" from these texts too? 
We can also rephrase the sentences in such a way that they are friendly without the requirement of the "please" word
![image](https://user-images.githubusercontent.com/78029145/212476466-b5e9b0c1-072c-4194-bce3-c597a1ecbbfd.png)
![image](https://user-images.githubusercontent.com/78029145/212476482-9bcabbd0-589f-4719-9a17-68ebdb1a9526.png)
I can work on this!

**Comment by jorgeorpinel** [comment]
Thanks for your interest @BhaswatiRoy . Yes we'd want to review every instance of "please" or similarly exaggerated friendly tone. Feel free to open a PR removing/changing the phrases you can find.

**Comment by BhaswatiRoy** [comment]
Hello @jorgeorpinel 
I have submitted the pr by rephrasing all sentences containing "please" in the docs section.
