### ISSUE TITLE
`cli` highlighter (update `dvc`)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3589]
[mlem.ai has](https://github.com/iterative/mlem.ai/issues/59) a `cli` Prism language that includes `dvc`, `cml`, and `mlem` commands (along with regular `shell` stuff).

- [x] Can we get it ported here @iterative/websites ?

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/3577#discussion_r881118100_

Also,

- [ ] Update existing `dvc` blocks? At least those that use other commands, from Linux tools to CML.

**Comment by jorgeorpinel** [comment]
p.s. and for that matter is there some sort of process to propagate engine updates across its implementations? Would be nice it we had an actual upstream/downstream forking structure setup I think.

**Comment by yathomasi** [comment]
The docs-engine port is ready to get merged https://github.com/iterative/dvc.org/pull/3396. So, it will be there once merged.

**Comment by jorgeorpinel** [comment]
Reopening for the check boz about updating `dvc` -> `cli`
