### ISSUE TITLE
header overlaps id links

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#3591]
e.g. using the link to [repro --pull](https://dvc.org/doc/command-reference/repro#--pull), the `--pull` entry is hidden under the header banner and you need to scroll up to actually see it.

![image](https://user-images.githubusercontent.com/10780059/170260239-cb5536bf-2019-4f0d-a033-e870fbbfce9f.png)

**Comment by shcheklein** [comment]
Hmm, it works fine for me. What is the browser / system @casperdcl ?

**Comment by casperdcl** [comment]
odd can't reproduce now.

It was firefox on ubuntu.
