### ISSUE TITLE
guide: update to use exp show --drop/keep

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3592]
https://dvc.org/doc/user-guide/experiment-management/comparing-experiments#customize-the-table-of-experiments still references `--include-params` and similar options instead of `--drop`/`--keep`.

**Comment by dberenbaum** [comment]
Also in https://dvc.org/doc/user-guide/experiment-management/persisting-experiments#create-a-git-branch-from-an-experiment

**Comment by daavoo** [comment]
Do you want me to jump into this? 

There is https://github.com/iterative/dvc.org/issues/3118 and during the P.R. updating the ref I recall being told to wait for user guide updates.

**Comment by dberenbaum** [comment]
Sorry, missed that #3118 exists.

@iesahin Should we pinging you for issues like this one and #3340, or should the core team be handling themselves?
