### ISSUE TITLE
add JS linter, integrate with CircleCI

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#360]

**Comment by algomaster99** [comment]
@shcheklein 
![Screenshot from 2019-05-31 06-37-51](https://user-images.githubusercontent.com/35191225/58612973-fadbdf00-82d1-11e9-9e84-ef8ed4a3fb53.png)
I think I can't integrate continuous integration test. :confused:

**Comment by shcheklein** [comment]
@algomaster99 same as with CodeClimate thingy, let me take a look and enable it.

**Comment by shcheklein** [comment]
@algomaster99 I've enabled the integration and added the initial version of the config file.

**Comment by shcheklein** [comment]
We do run `yarn lint-check` now in CI.
