### ISSUE TITLE
Allow more than `dvc` to be uppercased in our `sidebar.json` slugs

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#3601]
Currently, our sidebar automatically uppercases the word `dvc` in our `sidebar.json` slugs (aka the slug [`running-dvc-on-windows`](https://github.com/iterative/dvc.org/blob/master/content/docs/sidebar.json#L179) gets the title of [`Running DVC on Windows`](https://dvc.org/doc/user-guide/running-dvc-on-windows)).

We want to be able to uppercase more than just dvc though ([`api`, `cml`](https://github.com/iterative/dvc.org/pull/3599#discussion_r884224938), [`ml`](https://github.com/iterative/dvc.org/pull/3599#discussion_r884190953), etc.).

Should be doable with a little `sidebar.js` refactoring!

**Comment by jorgeorpinel** [comment]
Is this an engine-level feature? Meaning should it ported to https://github.com/iterative/gatsby-theme-iterative ? Thanks BTW!

**Comment by julieg18** [comment]
Yes, it should be! I've already opened a pr for it. See [gatsby-theme-iterative#22](https://github.com/iterative/gatsby-theme-iterative/pull/22)
