### ISSUE TITLE
add codeclimate integration for JS

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#361]

**Comment by algomaster99** [comment]
@shcheklein I wanted to work on this but I think it can only be integrated by the admins of org. Do we need to pay for their service?

**Comment by shcheklein** [comment]
@algomaster99 makes sense, I'll take a look and enable it for the org. I hope we don't need to pay since the project is open and we don't need to run a lot of checks in parallel right now.

**Comment by shcheklein** [comment]
done, it's integrated now. No need to commit any configs for this.
