### ISSUE TITLE
blog: confusing page header

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3610]
TBH it looks like the top article is (always) titled **Data Version Control in Real Life**:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1477535/171349934-892416e2-dc71-443f-96e6-4132b0e0cce4.png">

Options I see:

1. Replace that text with something more obvious like "DVC Blog".
2. Replace it dynamically with the top blog title (more space for `descriptionLong`) -- may need design input.
3. Remove it completely.
4. Close this issue.

WDYT @jendefig ? Thanks

**Comment by jorgeorpinel** [comment]
> Replace it dynamically with the top blog title (more space for descriptionLong) 

Would also address #2386... In fact I'm closing that one...

**Comment by yathomasi** [comment]
Actually, we are migrating the blog posts to iterative.ai. I have started the process( and here is the [issue](https://github.com/iterative/iterative.ai/issues/475))

I believe we will have categories and I think we can update the section. Here is my rough sketch (tabs plus tags). If we go with a similar concept it will be the necessary enhancement.

<img width="671" alt="Screen Shot 2022-06-02 at 22 48 05" src="https://user-images.githubusercontent.com/20840228/171684764-da144bbf-0257-49bd-9bc0-b65767587149.png">

**Comment by jorgeorpinel** [comment]
OK so feel free to close or transfer this issue then. Thanks for the info!

**Comment by jendefig** [comment]
The top of the page has bothered me for some time too @jorgeorpinel.  Also that it is off-center.  But given the upcoming merge to the Iterative blog, I think we can get by as is for now.

**Comment by yathomasi** [comment]
> OK so feel free to close or transfer this issue then. Thanks for the info!

Closing this issue for https://github.com/iterative/iterative.ai/issues/475. Let's discuss any ideas or concepts for the blog page there.

**Comment by yathomasi** [comment]
> OK so feel free to close or transfer this issue then. Thanks for the info!

Closing this issue for https://github.com/iterative/iterative.ai/issues/475. Let's discuss any ideas or concepts for the blog page there.
