### ISSUE TITLE
blog: automatically include admonitions with upcoming events

### ISSUE THREAD

**Issue by RCdeWit** [iterative/dvc.org#3632]
It would be nice to automatically include invitations for upcoming events as admonitions in blog posts. This would help people who read our blog to find out about office hours, meetups, and release parties we're planning.

[Example from the GitLab blog](https://about.gitlab.com/blog/2022/06/07/best-life-best-work/):

![Screenshot 2022-06-09 at 10 25 24](https://user-images.githubusercontent.com/7165065/173017726-c82fae4c-66d6-4790-a75e-1e54a388eb0c.png)

Events are listed here: https://dvc.org/community#events
Although the overview is currently empty.

**Comment by yathomasi** [comment]
It's really a good idea. 

Regarding the approach, I think we can have a custom placeholder eg: `<event>` so that it can be placed in a suitable place on the blog. We could fetch random or specify a certain event. We can discuss further on level of customization we want. And, it can be hidden based on the date field. 

WDYT?

**Comment by julieg18** [comment]
> It would be nice to automatically include invitations for upcoming events as admonitions in blog posts.

Great idea! A couple questions on this:

* Where exactly do we want the admonition to appear on a blog post? Do want it to appear in the beginning or end? Or maybe we want to the blog post writer to decide where they want an admonition?
* Do we want this admonition to appear on every blog post or only in certain ones?

**Comment by RCdeWit** [comment]
My thoughts:

- I'd prefer the author to specify where the admonition is inserted
- As a result, the author can decide per blog post whether there should be an event admonition there at all
- I think by default the admonition should show the next upcoming event, with an option to specify a different one. Past events shouldn't be shown.
