### ISSUE TITLE
.yarn folder is not gitignored

### ISSUE THREAD

**Issue by iswarmondal** [iterative/dvc.org#3652]
#### According to the official documentation of the yarn package manager few changes are needed to be done in the gitignore
`.yarn/*`
`!.yarn/patches`
`!.yarn/releases`
`!.yarn/plugins`
`!.yarn/sdks`
`!.yarn/versions`
`.pnp.*`

#### Was that intentional? If not then I would like to take a look at the problem.

**Comment by yathomasi** [comment]
HI @iswarmondal, which version of `yarn` are you using?

**Comment by iswarmondal** [comment]
> HI @iswarmondal, which version of `yarn` are you using?

I'm using `yarn 3.1.1`.

**Comment by yathomasi** [comment]
> I'm using yarn 3.1.1.

We have our project setup with yarn version `1.*` and we don't have any plan to upgrade it as of now. 

cc: @iterative/websites

**Comment by yathomasi** [comment]
> While we don't have plans to upgrade, it wouldn't hurt to add `yarn` folders to `.gitignore` if the project can still be run correctly with users that have a higher version of yarn.

Yes, we can have the yarn folder gitignored but the higher version of yarn would also change the `yarn.lock` file and I think `yarn install` with different versions of yarn will always bring conflict with the changed `yarn.lock` file.
So, I would recommend tools like [volta](https://volta.sh/) so that you can easily switch between the different versions of yarn.

> are you having any other issues working with `dvc.org` locally besides `.gitignore` not ignoring the `yarn` related folders?

+1

**Comment by iswarmondal** [comment]
Thanks, @julieg18 and @yathomasi, I am having some issues with contributing to dvc.org docs files.

Here's the GraphQL error I'm facing, I'm not proficient in GraphQL so I couldn't understand what's this.

`Field "sourcePath" of type "File" must have a selection of subfields. Did you mean "sourcePath { ... }"?`

![image](https://user-images.githubusercontent.com/73457704/173980530-6dfbe68b-cb96-4fcf-a369-f638c417b323.png)

and here's another ReactJS error I'm facing.

`Gatsby.js development 404 page
There's not a page or function yet at /doc/user-guide/managing-external-data`

I've looked through the docs and didn't found anything there.

**Comment by yathomasi** [comment]
> Here's the GraphQL error I'm facing, I'm not proficient in GraphQL so I couldn't understand what's this.
> 
> `Field "sourcePath" of type "File" must have a selection of subfields. Did you mean "sourcePath { ... }"?`

Does this happens on running the cloned/forked version or did you upgrade packages or made any changes? I couldn't reproduce this on my end.

**Comment by shcheklein** [comment]
Closing as stale
