### ISSUE TITLE
ref: `exp init --type=dl` no longer exists

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3656]
... we missed a cmd ref update somewhere because it's still mentioned in a few places of https://dvc.org/doc/command-reference/exp/init

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/issues/3430#issuecomment-1154944423_

- [ ] Update to `checkpoints` anywhere the option/value are mentioned.

**Comment by dberenbaum** [comment]
Sorry, looks like I missed this from https://github.com/iterative/dvc/pull/7703#discussion_r870136194
