### ISSUE TITLE
add repro -R to docs, fix -R description in other commands

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc.org#367]
DVC repro -R: Reproduce all stages in the specified directory.

Issue https://github.com/iterative/dvc/issues/1989 
PR https://github.com/iterative/dvc/pull/2030

**Comment by shcheklein** [comment]
Wait until  iterative/dvc#2030 is merged.

**Comment by shcheklein** [comment]
Also, mention that we have changed -R for pull/push/gc/checkout that it now accepts not only dirs but files as well.

**Comment by kurianbenoy** [comment]
Can I work on this? as now dvc#2030 is merged

**Comment by shcheklein** [comment]
@kurianbenoy that would be great! :) thanks.

**Comment by efiop** [comment]
There is no `-R` in `dvc gc`. Need to remove that from docs.

**Comment by RahulR19** [comment]
> 
> 
> There is no `-R` in `dvc gc`. Need to remove that from docs.

From where should I remove this

**Comment by RahulR19** [comment]
There is no -R in [(https://dvc.org/doc/commands-reference/gc)]

**Comment by RahulR19** [comment]
There is no -R in [](https://dvc.org/doc/commands-reference/gc)

**Comment by RahulR19** [comment]
There is no -R [here](https://dvc.org/doc/commands-reference/gc)

**Comment by shcheklein** [comment]
I think this is resolved already by @jorgeorpinel
