### ISSUE TITLE
Get started data pipeline misses dvc init

### ISSUE THREAD

**Issue by Chichilele** [iterative/dvc.org#3676]
Hi,

It think this file content/docs/start/data-management/pipelines.md misses the dvc init (or the downloaded zip should have the .dvc folder)

**Comment by shcheklein** [comment]
The index page has it - https://dvc.org/doc/start

Clearly this index page (the first part of it?) should belong here https://dvc.org/doc/start/data-management

And https://dvc.org/doc/start/data-management should become a separate section

cc @jorgeorpinel @iesahin
