### ISSUE TITLE
integrate husky and pretty-quick for pre-commit hook

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#372]
[This comment](https://github.com/iterative/dvc.org/issues/363#issuecomment-494248378) justifies the usage of husky pre-commit hook over `pre-commit` package.

UPDATE: In summary the husky config file would probably look like:
```json
"husky": {
  "hooks": {
    "pre-commit": "lint-staged" 
    },
},
"lint-staged": {
  "static/docs/**/*.md": [ "prettier --write"],
}
```

**Comment by jorgeorpinel** [comment]
Yes! I think we don't need Python and whatever applies the pre-commit hook should re-use the `prettier` version installed in node_modules/ so `husky`/`lint-staged` would work unless anyone has a better suggestion.

- [ ] Let's then also update the [doc contrib](https://dvc.org/doc/user-guide/contributing-documentation#development-environment) guide to reflect these changes.

**Comment by algomaster99** [comment]
@jorgeorpinel I can update the documentation once your PR is merged.

**Comment by algomaster99** [comment]
@jorgeorpinel okay! So I'll integrate husky/lint-staged as soon as possible if you are not working on it and update the docs too.

**Comment by jorgeorpinel** [comment]
Awesome. Please remember to remove all traces of Python if it's not used for anything else in this repo (which I think is the case).

**Comment by jorgeorpinel** [comment]
Hey, I just noticed the prettier docs have a guide on how to easily install lint-staged and husky: https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged

**Comment by algomaster99** [comment]
Lint-staged is dropped since it wasn't bailing out after formatting files. It was staging the files and committing it.

**Comment by jorgeorpinel** [comment]
Hi @algomaster99 ! I'm not sure this is working as expected so reopening:

When I add changes to git and then commit, if files are automatically formatted those automatic changes should NOT be staged automatically I think, but they are currently. Not sure it's a huge deal but is it possible to change the setup so automatic formatting isn't automatically staged to git?

Thanks

**Comment by algomaster99** [comment]
@jorgeorpinel Okay, I will try that changes don't get staged.

**Comment by jorgeorpinel** [comment]
That would be super useful. Please lmk if you get stuck or need any help 😃
