### ISSUE TITLE
Katacoda is closed

### ISSUE THREAD

**Issue by alexmojaki** [iterative/dvc.org#3722]
### Report

On pages such as https://dvc.org/doc/start there are links to [Run in Katacoda](https://katacoda.com/dvc/courses/get-started). That page now gives a 404:

> Thank you to the Katacoda community for your years of support. Katacoda.com is now closed. Learn more about this decision and access interactive learning on O’Reilly [here](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html).

That last link says:

> we can no longer support katacoda.com for public use, and we’ll be shuttering the site on June 15, 2022.

**Comment by shcheklein** [comment]
@alexmojaki thanks, yes, we are aware - https://github.com/iterative/katacoda-scenarios/issues/70 and we will the links soon. Thanks for the report! :)
