### ISSUE TITLE
ref: `dvc data status`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3732]
### Report

See https://github.com/iterative/dvc/pull/7943. 

@skshetry Let's start on this ASAP so that if there are concerns about the UI, they can be raised early.

**Comment by jorgeorpinel** [comment]
That would be neat! You can make it a draft PR for now and we can have product/ QA discussions on top of it. Thanks!

**Comment by dberenbaum** [comment]
@jorgeorpinel Saugat is out but the core PR should be nearly ready to merge. If you have time, please play around with it or even just check out the comments in the PR to see some example output.

**Comment by jorgeorpinel** [comment]
After looking into it I'm not too worried about docs. Mainly we need the new command reference and to review existing references of `dvc status` to decide which ones to replace. As for the reference, probably the more complicated part will be to decide which useful examples to include. On the long run the issue I see is the overlap with `dvc status` but that's more of a product question.

**Comment by dberenbaum** [comment]
> On the long run the issue I see is the overlap with `dvc status` but that's more of a product question.

Even for the command ref for the initial PR, this is probably the biggest question that we need to address. My take is that we recommend `dvc data status` as a better option whenever you are focused on the status of the data and not the pipeline stages. `dvc status` is still needed if you have want the status of those pipeline stages (we had plans to have a `dvc stage status` command or similar but it's nor prioritized right now).

**Comment by jorgeorpinel** [comment]
Wrt the command namespaces, since the basic commands like `add` and `push` relate more to data management, it would make sense for `dvc status` to give the new data status IMO. And to move the existing pipeline status command into `dvc stage status`. But that could break backward compatibility so it's probably tricky... Anyway, just a thought.

**Comment by dberenbaum** [comment]
Yeah, maybe for 3.0. Ideally, we would have an improved `dvc stage status` and can deprecate the existing `dvc status`.
