### ISSUE TITLE
guide: rename "Pipelines Files" to `dvc.yaml` (& `dvc.lock`)

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3734]
See https://dvc.org/doc/user-guide/project-structure/pipelines-files

Per https://github.com/iterative/dvc.org/pull/3691#discussion_r908916486, `dvc.yaml` is no longer strictly a "pipelines file" (it includes non-pipeline info like `plots`, for example). We should consider how to name/organize the terms/docs to reflect this.

**Comment by jorgeorpinel** [comment]
I think the simplest strategy is to remove the term "pipelines file" everywhere. WDYT @dberenbaum @shcheklein ?

**Comment by dberenbaum** [comment]
Yeah, we also have `dvc.lock` in there, but since the page is already called "Pipelines Files (dvc.yaml)," just removing "pipelines files" seems best.
