### ISSUE TITLE
cache-dir under command-references shows no content

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc.org#374]
![Screenshot (24)](https://user-images.githubusercontent.com/16274905/58186916-6a027380-7cd3-11e9-9715-ebf644ce246d.png)

https://dvc.org/doc/commands-reference/cache-dir\

This link on the dvc website is showing irrelevant data. no data about cache-dir present here.

**Comment by shcheklein** [comment]
Good catch @ryokugyu ! Thanks.
