### ISSUE TITLE
Small typo in checkout.md

### ISSUE THREAD

**Issue by huang06** [iterative/dvc.org#3747]
### Report

There's a small typo in the `dvc fetch` description.

<https://dvc.org/doc/command-reference/checkout#examples>

> We run `dvc fetch` with the `-aT` flags to get the DVC-tracked data from all Git branches and tags from [remote storage](/doc/command-reference/remote) to the <abbr>cache</abbr>. This way it's all available for the `checkout` examples below.

It should be:

We run `dvc fetch` with the `-aT` flags to get the DVC-tracked data ~~from~~ **for** all Git branches and ...

**Comment by jorgeorpinel** [comment]
Hmmmm. Thanks @huang06 but I'm not sure this needs fixing 🙂 

DVC reads metafiles **from** different Git revisions, not _for_ them. "For" could also work (figurative speech), but "from" is more correct.

Sorry
