### ISSUE TITLE
Google Drive remote documentation

### ISSUE THREAD

**Issue by ei-grad** [iterative/dvc.org#381]
Just creating the docs issue for the upcoming iterative/dvc#2040 which would bring the Google Drive support.

Some things to mention:

1. There are 3 types of URLs:

    1. Subfolder in the "My Drive" folder:

           gdrive://root/Datasets/my-dataset

    2. Folder by ID (recommended):

           gdrive://1r3UbnmS5B4-7YZPZmyqJuCxLVps1mASC

        (get it from the last part of URL https://drive.google.com/drive/folders/{here})

    3. Dataset named "my-dataset" in the hidden application folder:

           gdrive://appDataFolder/my-dataset

        (this one wouldn't be visible through Google Drive web UI and
         couldn't be shared)

2. OAuth2, client ID and quotas, we need something like this: https://rclone.org/drive/#making-your-own-client-id

3. There is an `oauth_id` option in remote config section, which could contain arbitary identifier and is meant to be used to allow different Google user accounts usage for different remotes.

**Comment by shcheklein** [comment]
` rclone already has a high quota and I will continue to make sure it is high enough by contacting Google.` - @ei-grad do you know what the default limits are? Should we contact google to raise these limits?

**Comment by ei-grad** [comment]
![image](https://user-images.githubusercontent.com/78607/59185524-5ed79080-8b79-11e9-8f7b-830a5a70650c.png)

> Should we contact google to raise these limits?

I don't think it would be needed in near future. Usecase of rclone is a bit different from DVC's. But it may be a good idea to setup a monitoring somehow to see if DVC's default quota is overused, so we could contact them early.

**Comment by ei-grad** [comment]
@dmpetrov may have a better understanding if GDrive backend would be heavily used by something like a webinar or class lessons in the groups of students... Probably 10+ users syncing a big repo would affect each other, so maybe we have to give the instructions for the teachers to recommend to use the separate client tokens per student in such scenarios.

**Comment by ei-grad** [comment]
We also can go to the dark side and create some client tokens in advance, and chose between them randomly :).

**Comment by shcheklein** [comment]
@ei-grad makes sense, thanks!
