### ISSUE TITLE
document `dvc import` and `dvc get` (previously `pkg` commands)

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#385]
UPDATE: See description in https://github.com/iterative/dvc/pull/2160 instead.

---
OLD: Some introductory descriptions for DVC packages (from Discord):

> You have project named `awesome_project`, which has `awesome_data` in  it
  pkg will allow you to "import" the project
  `dvc pkg import awesome_project://awesome_data` (syntax may be incorrect)

> 1. Any DVC repo is a _package_. Outputs inside packages can be called _artifacts_ (that we'll also be able to work with)
> 2. There will be a set of commands to import/export these _packages_ across different repositories and from a repository to a file system ~~(just a data artifact)~~
> 3. basic use cases include things like: dataset registry (reuse a single dataset in multiple project, while having a single point of responsibility for the dataset itself), easy mechanism to pull a data artifact w/o doing `git clone` + `dvc pull data.dvc`, etc
> 4. in the future (no need to focus on this for now) any set of DVC files will be considered as package, thus making pipelines reusable

**Comment by jorgeorpinel** [comment]
Main references found in core repo:
- https://github.com/iterative/dvc/issues/1772
- https://github.com/iterative/dvc/pull/2012
- https://github.com/iterative/dvc/pull/1742

Also, funny: `dvc pkg` doesn't have a `-h` option. Is that normal? Opened https://github.com/iterative/dvc/issues/2065

**Comment by efiop** [comment]
@jorgeorpinel Sorry for the rush, the PR that this relates to is https://github.com/iterative/dvc/pull/2012 , which is not merged yet. I've just created this task in advance.

**Comment by jorgeorpinel** [comment]
Oh. @shcheklein asked me to give this one priority. Are you saying I should wait for that PR to close first Ruslan? Makes sense to me 😃

**Comment by shcheklein** [comment]
@jorgeorpinel this is a priority :) we will see if we merge it before pkg code is merged or not. It will also take some time to get the docs for it done end-to-end. It's a big feature.

**Comment by efiop** [comment]
Note: also need to make sure to add a note that old `import` was moved to `import-url`.
