### ISSUE TITLE
cases: split and complete Data Registry (combine with pipelines)

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3888]
### Report

The current https://dvc.org/doc/use-cases/data-registry#building-registries is focused on `dvc add` / `.dvc` files workflow.

However, the same pattern can be applied using outputs of `dvc.yaml`, allowing users to introduce preprocessing steps in the Data Registry repo. 
This possibility is not obvious when following the current page.

UPDATE: Jumo to https://github.com/iterative/dvc.org/issues/3888#issuecomment-1236273489.

**Comment by jorgeorpinel** [comment]
TBH the bottom part of the doc with very specific steps doesn't really belong in the use cases section of the docs. We should first think about where that could live (maybe a how-to? or a blog?) and then update it once it's moved.

That said the registry is mainly meant as a data management tool AFAIK so combining with pipelining may be confusing to 90% of the readers here. You could also use [chained imports](https://github.com/iterative/dvc.org/issues/2610) instead, I believe (i.e. import from some other DVC project into the registry, and then import from the registry for usage), and avoid having dvc.yaml/lock in the registry. Maybe that's a better pattern to include?

**Comment by shcheklein** [comment]
I think a quick way to do this is to split the "hands on" part into a tutorial underneath the use case (similar to versioning).

**Comment by jorgeorpinel** [comment]
> the same pattern can be applied using outputs of dvc.yaml

I suppose we still don't cover this.

**Comment by jorgeorpinel** [comment]
Do we want to?
