### ISSUE TITLE
Migrate Community page to Iterative.ai

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#3898]
### Report

We should migrate the Community page to Iterative.ai as the Community covers more than DVC.

**Comment by yathomasi** [comment]
I am linking all the scattered related issues with Community Page. 
1. https://github.com/iterative/dvc.org/issues/3898 
2. https://github.com/iterative/dvc.org/issues/3897
3. https://github.com/iterative/dvc.org/issues/2603
4. https://github.com/iterative/dvc.org/issues/2576

We can follow the exact order. (2&3 can be considered on a single iteration.)

**Comment by dberenbaum** [comment]
@jendefig Closing since I don't think this is in the plans now but feel free to reopen

**Comment by jendefig** [comment]
Ya.  This is way old. 🕸️ The migration isn't necessary with the upcoming change to dvc.ai (which is where it should ultimately go).  But all the rest of the things on the list were supposed to be done. I was surprised the Events section was not removed.  The entire Community page is way out of date. There's no way I can manually keep it up to date.  These things should feed automatically.

**Comment by yathomasi** [comment]
If we are looking to show the latest events or videos from the source mentioned, we should be able to integrate them with the websites by using their APIs. Also, they would reflect the status on those websites so we won't need to update them in the websites manually.

Right now we don't have a community page(or any similar page) on dvc.ai and no plan to add them soon. We need to bring this up/prioratize if we really want this.
