### ISSUE TITLE
merge conflicts: wording issue

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#3915]
### Report

https://dvc.org/doc/user-guide/how-to/merge-conflicts#how-to-merge-conflicts-in-dvc-files

> How to Merge Conflicts in DVC Files

I find this confusing because you don't "merge" conflicts, you fix/resolve/solve them. Maybe it could be interpreted as:
"How-to: Merge conflicts in DVC Files", but I still find it confusing.

**Comment by yathomasi** [comment]
Also, for append-only merge, we need to make it clear it would only work one way around. (pasting from a discussion)
> BTW, I did try merging with dvc-driver but it looks like it would only work if we merge `current branch` to the `main` not the other way around. But, in our case, we merge `main` to `current branch` .

**Comment by jorgeorpinel** [comment]
I don't see the wording issue TBH. Have users reported confusion? The resulting commit is a merge regardless of how you get there.

@yathomasi mind sending a quick edit to the text you refer to?

**Comment by shcheklein** [comment]
My 2cs - when I actually consciously read it (after @skshetry ) created a ticket I though this is a bug. It looks like a bug to me (word is missing). `How to resolve merge conflicts  ...` - the proper way. You don't indeed "merge conflicts"

**Comment by jorgeorpinel** [comment]
True. We should add word "Resolve".

**Comment by jorgeorpinel** [comment]
I just did this since it requires link and redirect updates. See #3915. Thanks

**Comment by yathomasi** [comment]
> @yathomasi mind sending a quick edit to the text you refer to?

The issue must be because of `main` branch had some deleted/renamed files but the `append-only` merge-driver only addresses file addition. So, it should be fine.
