### ISSUE TITLE
fix automatic linking to `dvc cmd subcmd`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#392]
Currently code blocks like `dvc remote modify` or `dvc pkg install` are converted to a link to the parent command reference, with an (often inexistent) `#` anchor to the subcommand (e.g. `/doc/commands-reference/remote#modify`)

Option 1: fix the automatic linking so the docs engine can link to subcommands correctly.

Option 2: change all references to subcommands in docs using regular md links (e.g. `[dvc remote modify](/doc/commands-reference/remote-modify)`)

**Comment by shcheklein** [comment]
Yep, we need to wait until this one is solved https://github.com/iterative/dvc.org/issues/305 because it will change the way we put URLs together.

**Comment by jorgeorpinel** [comment]
So happy this is working now! Just missing to update the `dvc` fenced code block CSS so the entire command is blue unlike now:

![image](https://user-images.githubusercontent.com/1477535/62815486-f9534200-bade-11e9-9d7d-504087e41ac1.png)

**Comment by shcheklein** [comment]
> So happy this is working now!

kudos @iAdramelk !

> Just maybe missing to update the dvc fenced code block CSS so the entire command is blue unlike now

@jorgeorpinel yep, it's a separate small thingy :) let's create a ticket for this.
