### ISSUE TITLE
ref: compare `dvc data status` to similar commands

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3928]
### Report

We can add some more context in https://dvc.org/doc/command-reference/data/status to compare it to:

* `dvc status`: `dvc data status` includes comparison to Git HEAD and doesn't show how pipelines have been modified. It's a more high-level command that shows what paths need to be committed to the repo.
* `git status`: `dvc data status` is a companion command for `git status`. Together, they show the full repo state. We should have an example that includes both `git status` and `dvc data status`.

**Comment by jorgeorpinel** [comment]
`dvc list .`?
