### ISSUE TITLE
mention in tutorial about ls -i meaning

### ISSUE THREAD

**Issue by kurianbenoy** [iterative/dvc.org#394]
```
$ ls -i data/Posts.xml.zip
78483929 data/Posts.xml.zip

$ ls -i .dvc/cache/ec/
78483929 88519f8465218abb23ce0e0e8b1384
```

In [tutorial page](https://dvc.org/doc/tutorial/define-ml-pipeline), where we mention this code block, we can tell that it prints the index no of each file, and inode in cache and data/ is same. 

Should I mention @shcheklein this as a comment in code block, or in documentation?

**Comment by shcheklein** [comment]
Yep, makes sense. I would explain after the code block this and the emphasize that number it the same.
