### ISSUE TITLE
pipelines: broken link

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc.org#3945]
### Report

Last link on this page https://dvc.org/doc/user-guide/project-structure/internal-files  (Avoiding unexpected behaviour) links to https://dvc.org/doc/user-guide/data-pipelines/defining-pipelines#avoiding-unexpected-behavior, which does not exist anymore.

Note that this is also linked in other places:

```console
content/docs/command-reference/run.md
222:  ([not recommended](/doc/user-guide/data-pipelines/defining-pipelines#avoiding-unexpected-behavior)).

content/docs/command-reference/repro.md
166:  ([not recommended](/doc/user-guide/data-pipelines/defining-pipelines#avoiding-unexpected-behavior)).

content/docs/user-guide/project-structure/internal-files.md
171:  /doc/user-guide/data-pipelines/defining-pipelines#avoiding-unexpected-behavior
```

**Comment by jorgeorpinel** [comment]
Hm. Seems like this was introduced accidentally in #3414... Fixing
