### ISSUE TITLE
pipelines: broken link

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc.org#3949]
### Report

On this page: https://dvc.org/doc/user-guide/pipelines#pipelines
> See [Get Started: Data Pipelines](https://dvc.org/doc/start/data-management/pipelines) for a hands-on introduction to this topic.

the get stsarted link is broken: https://dvc.org/doc/start/data-management/pipelines

**Comment by dtrifiro** [comment]
Hijacking this issue to also report that searching for `import file or directory` returns this broken link:

https://dvc.org/doc/start/data-management/access#import-file-or-directory

**Comment by jorgeorpinel** [comment]
> the get stsarted link is broken: https://dvc.org/doc/start/data-management/pipelines

Yep. It's my bad: I didn't include link updates or a redirect in https://github.com/iterative/dvc.org/pull/3943 (to keep the PR simple). Fixing... ⏳ 

Thanks @dtrifiro

**Comment by jorgeorpinel** [comment]
> searching for import file or directory returns this [broken link.](https://dvc.org/doc/start/data-management/access#import-file-or-directory)

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1477535/190532250-e198202a-45da-4b98-93ac-f9bba7abde09.png">

This is a problem with Algolia, I think (the internal search engine we use). It takes time to update links when we change URL paths. Any way to force update it @rogermparent ? Thanks
