### ISSUE TITLE
document optimization and caveats running DVC on Windows

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#395]
Context is here: https://github.com/iterative/dvc/issues/2047

It should be a separate page in user guide.
There should be a link in a few places to this page - get started, tutorial, etc.

**Comment by efiop** [comment]
This one https://github.com/iterative/dvc/issues/2132 would fit nicely there as well.

**Comment by vibhor98** [comment]
Hi @shcheklein, as recommended,  I'm working on this issue. Thanks!
