### ISSUE TITLE
RSS feed: useful? replace?

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#4032]
### Report

Working [on this](https://github.com/iterative/dvc.org/issues/3833#issuecomment-1273463900) today and going through landing page.  Noticed the RSS feed link under the email entry box is broken.

 
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/34289199/194960290-f61741d9-eb8d-4934-b631-869ab21b3e1e.png">

**Comment by rogermparent** [comment]
Is it? That looks like an RSS feed to me.

**Comment by jorgeorpinel** [comment]
Thanks @jendefig ! It's supposed to look like that 😋

**Comment by jendefig** [comment]
Okie dokie.  I'm totally lost.

**Comment by jorgeorpinel** [comment]
Hehe no worries. What it means is that if for example you install an in-browser reader like [this extension fro Chrome](https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp/related?hl=en), then when you open https://dvc.org/blog/rss.xml it looks like this:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1477535/195245581-36be321a-24d2-4fee-b8ce-9219b654dc76.png">

**Comment by rogermparent** [comment]
It's an easy mistake to make! Very few people use RSS these days.

> if for example you install an in-browser reader

One important thing to know is that RSS readers started as external applications, so people could get email-like notifications for new website content without having to actually go to every website and check- this is the primary reason we offer RSS and don't just direct people to a human-readable page.

**Comment by jendefig** [comment]
@rogermparent @jorgeorpinel Thanks for this explanation.  
I don't use them, but did try to back in the day when they became popular and I remember just clicking on something that enabled me to add to my RSS feed, but I never saw any code.  I would have immediately left and never used it.  I must have had an in-browser reader.

**Comment by rogermparent** [comment]
Even if RSS is on the way out, it's because of other technologies that take the same "slot" like [JSON Feed](https://www.jsonfeed.org/).

**Comment by jorgeorpinel** [comment]
Do we have/want a JSON feed?

**Comment by rogermparent** [comment]
Have: not currently, unless somehow one of the Gatsby libraries does it automatically- even if so, we don't link to it.
Want: not high priority, but if someone asks for it we could do so. I think we were asked about RSS which is why we have it now. Maybe we'd introduce it if feeds get overhauled for any other reason.

**Comment by jendefig** [comment]
If i'm not mistaken, the reason the RSS feed was added in the first place was because of [this Slack message](https://iterativeai.slack.com/archives/CFB1AJV8U/p1652954128915579) about a way for people to see the kind of mail they will get easily before signing up.  The RSS was the low-hanging fruit.  But if it's not useful we could ditch in exchange for doing a page as mentioned in the thread. Is there a way to tell how many hits we get on the RSS button?

**Comment by yathomasi** [comment]
I don't think replacing it with any other format will do any good.  We can leverage the RSS feed to send emails to our subscribers and I can see [Mailchimp provides such automation](https://mailchimp.com/help/share-your-blog-posts-with-mailchimp/). We can collaborate if we want to get this done.

**Comment by shcheklein** [comment]
Ppl still use RSS for automation (e.g we are subscribed to SO questions about DVC and publish them into Slack), crawlers use them to extract snippets, etc. I would not remove this, I think it's good to provide all the basic ways of publishing. Unless it gives us some headaches, but ASAIK it comes pretty much our of the box with Gatsby?

**Comment by rogermparent** [comment]
> it comes pretty much our of the box with Gatsby?

Not quite "out of the box" since we have to translate blog post nodes into feed data, but it's much easier than the average feature especially where we already have it set up. Definitely not replacing the RSS feed, like I mentioned earlier in the thread I think our viable choices are either sticking with what we have now or including additional formats like JSON feed, and we've got enough on our plate that this can sit as it is for a while.
