### ISSUE TITLE
exp run: clarify behavior for untracked files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4044]
### Report

In the docs and in the help text and warnings for `exp run`, we should clarify that only files tracked by Git or DVC will be included as part of the experiment. Otherwise, users can end up surprised when a queued/temp experiment fails because some file from the local workspace is missing, or when they apply some experiment to the workspace and find it doesn't include some file the expected.

cc @dtrifiro @pm

**Comment by shcheklein** [comment]
Should DVC make it clear also - detect files, put a message on the screen?

**Comment by dtrifiro** [comment]
Note that current behaviour of `TempDirExecutor` to [warn if untracked files exist](https://github.com/iterative/dvc/blob/3bbf8fa7d2c517af6b98e2d26f44c2618398e248/dvc/repo/experiments/executor/local.py#L60-L66) (but only if untracked files exist [after reproduction](https://github.com/iterative/dvc/blob/3bbf8fa7d2c517af6b98e2d26f44c2618398e248/dvc/repo/experiments/executor/base.py#L559-L569))


> Should DVC make it clear also - detect files, put a message on the screen?

We could do that, although it could be a bit spammy imho. In case we decide to detect untracked files, performance considerations should be taken into account (e.g. see https://github.com/iterative/dvc/pull/7786).
