### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc.org#4055]
### Report

Sometimes I work into the night (especially now as the nights are getting longer in the northern hemisphere) and the white background sometimes makes me think twice before opening the dvc documentation :-)

I'd love to see the option to switch the DVC (and CML and MLEM, ...) docs to a color theme e.g. like that of the DVC blog.

**Comment by jorgeorpinel** [comment]
It's something we plan to consider. Will keep this issue open to follow up as needed by the web team.

For now I can recommend using a browser extension. For Chrome I like [Deluminate](https://chrome.google.com/webstore/detail/deluminate/iebboopaeangfpceklajfohhbpkkfiaa?hl=en-US) (smart invert images mode works for me on dvc.org/doc):

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1477535/196812265-08042697-8586-455a-aade-5748c599ee61.png">
