### ISSUE TITLE
Studio: LWMM with data (DVC)

### ISSUE THREAD

**Issue by mvshmakov** [iterative/dvc.org#4064]
Related to https://github.com/iterative/studio/issues/4104

>  Explain the overall flow
 Explain dvc init and why it's used
 Explain Path to the directory for the model file

Docs should explain the `Local Path` field recently added to the Iterative Studio:

<img width="603" alt="Screenshot 2022-10-25 at 14 21 25" src="https://user-images.githubusercontent.com/28868855/197748786-6aef7c51-e6a2-4015-ac03-b48345856f5b.png">

**Comment by jorgeorpinel** [comment]
>  Explain the overall flow
 Explain dvc init and why it's used
 Explain Path to the directory for the model file

Are all these done?

> Docs should explain the Local Path field recently added

Where is this part of the UI currently documented? Thanks

**Comment by mvshmakov** [comment]
> Are all these done?

Yes, with https://github.com/iterative/dvc.org/pull/4065

> Where is this part of the UI currently documented?

@jorgeorpinel it is here: https://github.com/iterative/dvc.org/pull/4065/files#diff-bc25449bc604f60a96fd8e003ac7befdd719fcd0c63a388ae7976182abfe6426R41-R42
