### ISSUE TITLE
guide: `dvc.yaml` is about more than pipelines

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4083]
### Report

https://dvc.org/doc/user-guide/project-structure/dvcyaml-files is focused on pipelines. With coming changes to the experiments onboarding experience that will introduce top-level params and metrics in addition to the existing plots, it's time to broaden the scope of how we describe dvc.yaml. 

It can be a general configuration file for ML experiments. This enables users to:

- Describe experiment tracking info: pipelines, parameters, metrics, and plots.
- Configure that info in human-readable files that can be modified before, during, or after experiments.
- Manage the configuration alongside code and data in Git.
- Use DVCLive to configure it, but also have flexibility to manually configure additional outputs (like adding plots that aren't supported by DVCLive).
- Use the tool of your choice to consume this schema and visualize/compare experiments (CLI, VS Code, Studio, CML, IPython/notebooks in the future).

**Comment by jorgeorpinel** [comment]
Related to #3896. Should we try to combine them?

**Comment by dberenbaum** [comment]
Makes sense! Added a comment to #3896. Closing this one.
