### ISSUE TITLE
guide: clarify that some Hydra features are always on

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#4103]
... I worry that this conflates different Hydra features. We are trying to separate different Hydra features in the docs (see https://iterative.ai/blog/dvc-hydra-integration#what-dvc-users-gain-from-the-integration for more explanation):
1. Overrides (change, append, or remove)
2. Use "choice" sets and ranges for grid search
3. Composition

The first two are used implicitly by `dvc exp run` regardless of whether `hydra.enabled = true`.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/4041#discussion_r1014637414_

**Comment by jorgeorpinel** [comment]
Currently the [main Hydra guide](https://dvc.org/doc/user-guide/experiment-management/hydra-composition) states that you can (should) enable the feature(s) with `dvc config hydra.enabled True`.

**Comment by jorgeorpinel** [comment]
Not sure where to clarify this. Let's merge #4041 and decide then? Cc @daavoo

**Comment by dberenbaum** [comment]
> Currently the [main Hydra guide](https://dvc.org/doc/user-guide/experiment-management/hydra-composition) states that you can (should) enable the feature(s) with `dvc config hydra.enabled True`.

Yes, that's the guide for Hydra _composition_. 

For overrides and grid search (features 1 and 2 above), Hydra is more of an implementation detail than an integration. Nothing needs to be enabled, and users don't have to use Hydra to take advantage of those features. Hydra is just the backend of how DVC supports parameter overrides.

**Comment by jorgeorpinel** [comment]
I see. And overrides, grid search are already documented in https://dvc.org/doc/command-reference/exp/run but not in the UG. Maybe we can repurpose this issue to do that? (Unless there's already an issue about it out there...)

Also, should we mention that the overrides and grid search features of `exp run` come from Hydra in the config composition guide? (and that those are always on by default) Or does that go full circle back into your original concern @dberenbaum ? 🤓

**Comment by jorgeorpinel** [comment]
> Unless there's already an issue about it out there.

Added a check box to https://github.com/iterative/dvc.org/issues/2768 instead. Closing this for now unless you want to follow up DB

**Comment by dberenbaum** [comment]
Sounds good, @jorgeorpinel. I'll rely on your expertise here on whether more clarification is needed. I think I'm too "inside" to have a good feel for how it reads.
