### ISSUE TITLE
use single quotes for `pip install` commands with square brackets

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#414]
Related to #402 and #412 .

`pip install -e dvc[all]` fails when ZSH is being used

`pip install -e 'dvc[all]'` should be working everywhere sh, bash, zsh.

Check that it's actually working and update our docs.

**Comment by J0** [comment]
`pip install -e '.[all,tests]'` works for me on zsh

**Comment by Naba7** [comment]
Can I be assigned this issue @shcheklein ?

**Comment by Naba7** [comment]
Can I be assigned this issue @shcheklein ?

**Comment by shcheklein** [comment]
@Naba7 sure! thanks. feel free to fix it.

**Comment by Naba7** [comment]
Hey @shcheklein Its really nice to say thanks but I kind of like DVC and want to explore and know about the stuff happening around,so there is no need to say thanks.

**Comment by algomaster99** [comment]
@shcheklein 
> `pip install -e '.[all,tests]'` works for me on zsh.

I think this can be closed.

**Comment by shcheklein** [comment]
@algomaster99  `... and update our docs` - that's the primary goal of this ticket :)

We need to go put [something] into single quotes.

**Comment by algomaster99** [comment]
@shcheklein why do we need to put it in single quotes if it is working without them? The docs already don't include them in signle quotes.

**Comment by shcheklein** [comment]
@algomaster99 it does not work w/o them on ZSH

**Comment by algomaster99** [comment]
@shcheklein Okay, I'll make the changes but test it once again just to be sure. :)
