### ISSUE TITLE
Experiments onboarding

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4149]
### Report

Depends on https://github.com/iterative/dvclive/pull/366.

Possible updates to reflect new experiments onboarding workflow:

- [x] https://dvc.org/doc/dvclive/get-started#dvc-integration: should "just work" inside a dvc repo; may need to clarify what to do for an existing pipeline
- [x] https://dvc.org/doc/start/experiment-management/experiments: update to use this simplified workflow; show steps to convert to full pipeline? What repo should we use? Do we even need a repo?
- [x] https://dvc.org/doc/user-guide/experiment-management: update so it doesn't assume `dvc exp run` workflow
- [x] `dvc exp save` command ref @dtrifiro (https://github.com/iterative/dvc.org/issues/4148)
- [x] Top-level metrics/params in https://dvc.org/doc/user-guide/project-structure/dvcyaml-files (edit: and https://github.com/iterative/dvcyaml-schema/issues/26) @skshetry 
- [x] `Live(save_dvc_exp=True)` API ref in https://dvc.org/doc/dvclive/api-reference/live @daavoo  (https://github.com/iterative/dvc.org/pull/4162)
- [x] https://github.com/iterative/dvc.org/issues/4409

**Comment by jorgeorpinel** [comment]
> /doc/start/experiment-management/experiments: update to use this simplified workflow

Some updates were done [in #4166](https://github.com/iterative/dvc.org/pull/4166/files#diff-b196875e58377957cb01bf618e3c65a93604d9cf9a89b7e138443cd6e71830bb) (left some [comments](https://github.com/iterative/dvc.org/pull/4166#pullrequestreview-1227052261) there) but they only mention the alternative workflow.

**Comment by jorgeorpinel** [comment]
I removed a couple people who seem to have contributed their parts but not sure about the remaining points.

Also is this still p1 based on those? (I guess they're kind of the most important ones 😅 -- make `exp save` the happy path in GS and UG).

**Comment by daavoo** [comment]
> I removed a couple people who seem to have contributed their parts but not sure about the remaining points.
> 
> Also is this still p1 based on those? (I guess they're kind of the most important ones 😅 -- make `exp save` the happy path in GS and UG).

@jorgeorpinel I think It is not as much about `exp save`, I think It is about this workflow https://iterative.ai/blog/exp-tracking-dvc-python

**Comment by dberenbaum** [comment]
> Also is this still p1 based on those? (I guess they're kind of the most important ones 😅 -- make `exp save` the happy path in GS and UG).

Yup, haven't gotten to this yet, but we need to overhaul the experiments guide and incorporate this workflow into the work happening on https://github.com/iterative/dvc-get-started-cv, which should replace https://github.com/iterative/example-dvc-experiments.
