### ISSUE TITLE
start: get the data needed for the Pipelines page

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#4153]
### Report

Starting in https://dvc.org/doc/start/data-management/data-pipelines and following the instructions is difficult, because it assumes you have the data gotten back in https://dvc.org/doc/start/data-management/data-versioning#expand-to-get-an-example-dataset, specifically:

```console
$ dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
```

Should we repeat that here, or link to the previous page? @dberenbaum 

> Context: https://discord.com/channels/485586884165107732/1047152728641650709/1048144098768453663

p.s. should we check all pages to see if you can start anywhere? Cc @shcheklein

**Comment by shcheklein** [comment]
No, I don't think so. It requires a complete redesign and a different approach. If we consider pipelines a separate independent large feature we should do a separate "trail" that starts right away with `dvc stage ` as a first command.

**Comment by dberenbaum** [comment]
> Should we repeat that here, or link to the previous page? @dberenbaum

Yep, since right now https://github.com/iterative/dvc.org/blob/869d2088b1e26e030b7eee495424d01252928a11/content/docs/start/data-management/data-pipelines.md?plain=1#LL35C4-L35C4 implies that you can start from scratch.

**Comment by shcheklein** [comment]
Folks, can we achieve the same by rephrasing / removing some content, not adding more clarifications? (it explodes eventually, since we'll have to clarify every small detail, on every page, etc).

**Comment by dberenbaum** [comment]
What about replacing that details section with a link to the previous page? I don't think we can get around linking or mentioning where to start.

**Comment by jorgeorpinel** [comment]
> If we consider pipelines a separate independent large feature we should do a separate "trail" that starts right away with dvc stage

I always thought we needed this trail separate TBH.

> replacing that details section with a link to the previous page?

But OK, yes for now let's just cover this specific hole with some linking... ⏳

**Comment by shcheklein** [comment]
> yes for now let's just cover this specific hole with some linking... ⏳

please let's not do this. First it's a distraction, and also we don't want this long term.

**Comment by jorgeorpinel** [comment]
Well, feel free to close this issue (and #4155) 🙂
