### ISSUE TITLE
Metrics, Parameters and Plots tutorial is broken after DVCLive 1.0 release

### ISSUE THREAD

**Issue by FarisElghlan** [iterative/dvc.org#4154]
### Report

The following page contains a link to source code that is not compatible with DVC 1.0:
https://github.com/iterative/dvc.org/blob/main/content/docs/start/data-management/data-pipelines.md

See breaking changes in DVC 1.0 mentioned here: https://github.com/iterative/dvclive/releases/tag/1.0

The `evaluate.py` script from `https://code.dvc.org/get-started/code.zip` should be updated. Currently it contains the following issues:
- `live.log_plot` should be changed to `live.log_sklearn_plot`
- `live.log` should be changed to `live.log_metric`
- `live.log_metric` no longer calls `live.make_summary`, so a call to `live.make_summary` (or `live.next_step`?) should be added (at the end of the script?). Otherwise, the file `evaluation/metrics.json` will not be created (this file is expected to be created in this tutorial: https://github.com/iterative/dvc.org/blob/main/content/docs/start/data-management/metrics-parameters-plots.md see `-M evaluation/metrics.json`)

The command mentioned on this page https://github.com/iterative/dvc.org/blob/main/content/docs/start/data-management/metrics-parameters-plots.md is incorrect (or at least does not match with the filenames specified in the script):
```bash
$ dvc run -n evaluate \
  -d src/evaluate.py -d model.pkl -d data/features \
  -O evaluation/plots/metrics \
  -M evaluation/metrics.json \
  --plots-no-cache evaluation/plots/prc.json \
  --plots-no-cache evaluation/plots/sklearn/roc.json \
  --plots-no-cache evaluation/plots/sklearn/confusion_matrix.json \
  --plots evaluation/plots/importance.png \
  python src/evaluate.py model.pkl data/features
```

- `evaluation/plots/prc.json` should be: `evaluation/plots/precision_recall.json` (or this line in the script should be changed: `prc_file = os.path.join("evaluation", "plots", "precision_recall.json")`)
- `evaluation/plots/importance.png` should be: `evaluation/importance.png` (or this line in the script should be changed `fig.savefig(os.path.join("evaluation", "importance.png"))`)

**Comment by daavoo** [comment]
@shcheklein Looks like ` https://code.dvc.org/get-started/code.zip` doesn't match the latest status of https://github.com/iterative/example-get-started

**Comment by dberenbaum** [comment]
It's been updated now. Thanks for reporting @FarisElghlan!
