### ISSUE TITLE
guide: gdrive should mention `gdrive_acknowledge_abuse`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4184]
> dvc 2.14.0 is out with `gdrive_acknowledge_abuse` config option. Please give it a try
> 
> ```
> $ dvc remote modify myremote gdrive_acknowledge_abuse true
> ```

maybe it makes sense to add it to the hands on tutorial

_Originally posted by @aliahari in https://github.com/iterative/dvc/issues/7832#issuecomment-1351644063_

**Comment by aliahari** [comment]
Actually I meant here: https://dvc.org/doc/start/data-management/data-versioning
In the video tutorial google drive is used as the storage and without the above mentioned command probably the ones who just started to use DVC with the help of the videos will stock at this issue. My suggestion would be either to mark the video as not up to date similar to some other videos in the docs or add a small hint about this issue. I would be also glad to contribute to the update of how to page

**Comment by dberenbaum** [comment]
@aliahari Thanks again! I do think it could be useful in the how to guide if you want to contribute it there 🙏 .

@jorgeorpinel What do you think about the video? Should we mark these as out of date or remove them until we can refresh them?

**Comment by jorgeorpinel** [comment]
I think we can consider this closed? Not sure we'll be able to update the video soon -- those tend to get outdated soon so let's just try to avoid documenting 3rd party tools in videos in the future 🙂

**Comment by aliahari** [comment]
I agree and I think we can close the issue
