### ISSUE TITLE
dvc version: incomplete information

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc.org#420]
![Screenshot (36)](https://user-images.githubusercontent.com/16274905/59120629-865d0c00-8973-11e9-9821-342ee95f6c35.png)

But, it mentions  [here](https://github.com/iterative/dvc.org/blob/master/static/docs/commands-reference/version.md)
that `filesystem type ` and `cache` information will be shown too. 
There is no output like this.  Also mentioned the issue in https://github.com/iterative/dvc/issues/2105. 
@shcheklein is it needed to create a separate section for Windows platform here?

**Comment by shcheklein** [comment]
@ryokugyu I believe, the version with this change is not released yet, please try the development version:

either this way: https://dvc.org/doc/user-guide/development
or this: https://dvc.org/doc/user-guide/contributing

I'm not sure I understand your concern re the Windows section.

**Comment by ryokugyu** [comment]
But, I have installed the development version only. @shcheklein That's why I mentioned it here.
Also, I again updated to the latest version, but still the same problem persists

![Screenshot (37)](https://user-images.githubusercontent.com/16274905/59144887-e9918180-89f9-11e9-973d-7b12b1cbb07f.png)
.

**Comment by efiop** [comment]
@ryokugyu From your screenshot the dvc version that you are using is 0.40.2, which is definitely not the upstream version since the latest release was 0.41.3. I suppose you are not installing dvc correctly from the upstream. Continuing discussion on discord.
