### ISSUE TITLE
Studio: do not document DVC plot formalities

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#4201]
Wrt https://dvc.org/doc/studio/user-guide/projects-and-experiments/visualize-and-compare

We ~~may not need~~ shouldn't have to document this DVC feature in Studio at all. We can just mention plots, where they can come from and _maybe_ how flexible they can be, and then link to https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#plots for formalities.

I also think the qualifier "top-level" (vs "stage-level") has very little meaning in the context of Studio. Let's just call them all _plots_ regardless of how DVC codified them?

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/issues/4121#issuecomment-1362506405_

**Comment by jorgeorpinel** [comment]
Cc @tapadipti + @dberenbaum: for your consideration

**Comment by tapadipti** [comment]
IMO, it is important that Studio docs can give enough information for users to understand the plots functionality - at least where and how the plots are defined. That is the approach we have taken for the Studio docs in general - do not get into details of dvc commands, but give enough info such that if someone knows how to use dvc, they can rely on Studio docs to visualize their projects and don't need to visit dvc docs for this. So, I think what we have now is ok.

If we want to remove details of top-level plots, then for consistency of approach, we should only mention that **there is a `Plots` button in Studio that opens the `Plots` panel**. All other plots details and examples should be removed.

**Comment by jorgeorpinel** [comment]
Well, I think we can basically start the doc at https://dvc.org/doc/studio/user-guide/projects-and-experiments/visualize-and-compare#how-to-generate-plots. Everything before that is re-documenting DVC IMO.

We're even conflating things a little by presenting plot formats as a Studio feature: "Iterative Studio can work with two types of plots files in your repository". Or maybe that's what we want? But in that case, then DVC is an implementation detail in Studio docs and we should hide it to some extent.

Let's take this opportunity to discuss a little and decide a general strategy going fwd (+ ideally we can retrofit some existing docs, esp. if it simplifies things). Cc @shcheklein

**Comment by tapadipti** [comment]
By that logic, we should also not provide example snippets on using DVCLive in the [live metrics docs in Studio](https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots). Or explain GTO config files in the [model registry docs in Studio](https://dvc.org/doc/studio/user-guide/model-registry/assign-stage). While that is good separation of concerns, it also makes the Studio docs much less self-sufficient. So, I still prefer providing some more details than what you have suggested. But yes, let's discuss and decide what is the best long term approach.

**Comment by shcheklein** [comment]
I'm totally fine with Studio being more self-contained. We can let Tapa drive and decide on this.

**Comment by jorgeorpinel** [comment]
> should also not provide example snippets on using DVCLive

Doesn't seem comparable to me @tapadipti: That section ([Send and view live metrics and plots](https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots#send-and-view-live-metrics-and-plots)) only has an example DVCLive code block to give an idea of how to set it up. It doesn't substitute https://dvc.org/doc/dvclive/api-reference/live.

The doc I refer to ([Visualize and Compare Experiments](https://dvc.org/doc/studio/user-guide/projects-and-experiments/visualize-and-compare)) contains a longer, exhaustive specification that pertains to a DVC feature, overlapping a lot with [Supported plot file formats](https://dvc.org/doc/user-guide/experiment-management/visualizing-plots#supported-plot-file-formats).

> Or explain GTO config files in the model registry docs in Studio

Agree (we should avoid). We can just mention them and link to https://mlem.ai/doc/gto/user-guide#configuring-gto for instance.

It's not only about separation of concerns but also maintainability\* of the docs -- in fact **the Studio doc in question is already outdated** (doesn't specify YAML 1.2 or mention SVG).

I realize that this possibly applies to (multiple) existing docs. But I don't expect that we'll go find & fix everything when/if we agree on new directions. We can just apply going forward and as we notice them.

> \* _To a lesser extent this is also about some level of consistency in the approach to writing docs (as suggested in our framework, which we can always revisit)._

**Comment by jorgeorpinel** [comment]
Also, I totally get that Studio docs need to be self-contained. I don't think my suggestion is contrary to that notion.

**Comment by tapadipti** [comment]
@jorgeorpinel How about we agree to pay attention to this in docs updates going forward? So, before merging future updates, we will review them to avoid duplicating other products' details. When I'm next working on the plots doc, I can try to also remove some of the duplicates. Makes sense?

**Comment by jorgeorpinel** [comment]
Yes, that's a good approach given our capacity ATM. I do the same with "framework changes" for DVC, docs, for example. Thanks

**Comment by tapadipti** [comment]
@jorgeorpinel Then can we close this issue? (coz we won't make this a separate effort, but a part of regular docs work)
