### ISSUE TITLE
params: clarify when they're granular

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#4202]
> Given that params defined at the top-level [do not support granularity](https://github.com/iterative/dvc/issues/8371#issuecomment-1304544916).

The only issue is that we currently tend to explain parameters as a "granular kind of dependency". So we should review these existing, older texts out there or find some other distinction like calling top-level params "general param files", or something else.

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/4180#discussion_r1055235028_

See full https://github.com/iterative/dvc.org/pull/4180#pullrequestreview-1227318059 for other suggestions.

---

Related to https://github.com/iterative/dvc.org/issues/2412 ?

**Comment by jorgeorpinel** [comment]
Specific places where this explanation exists now:

- https://dvc.org/doc/user-guide/glossary (find "Parameters"; also all tooltips use this) - text:
  >They can be tracked as granular dependencies for stages of DVC pipelines (defined in dvc.yaml). 
- https://dvc.org/doc/user-guide/pipelines/defining-pipelines#parameter-dependencies - text:
  > A more granular type of dependency is the parameter...
  Params are granular dependencies because DVC only invalidates stages when the corresponding...
- https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#parameters (by the bottom) - text:
  > Params are a more granular type of stage dependency

Cc @skshetry @dberenbaum

**Comment by dberenbaum** [comment]
For dependencies, they are granular. Top-level params are not dependencies of any stage. We can further clarify, but I'm not sure I see anything inaccurate here.

**Comment by jorgeorpinel** [comment]
> I'm not sure I see anything inaccurate

The problem I see is in the context because we now have these "top-level params" that are not really parameters in the way we've defined them before (granular dependencies) but they're called the same. Maybe each page is consistent internally but not vs. each other. In fact this causes internal inconsistencies e.g. rn https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#params has a tooltip (param dep text) in the context of top-level params:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1477535/209247217-fcabbe2c-01cc-4c73-abe7-7ef95c5a4559.png">

**Comment by jorgeorpinel** [comment]
What's the purpose of top-level param definitions again?

And I guess they all share a file-type definition (JSON/YAML/TOML key-pair files) so perhaps we can address via https://github.com/iterative/dvc.org/issues/2572#issuecomment-1323292963 or even make a new reference section called File Formats (along with the CLI and APR refs).
