### ISSUE TITLE
git clone authentication

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc.org#4212]
Do you think we should specify that DVC does not support interactive auth, and so credentials must be saved somewhere and automatically available when running Git commands to access a private repo?

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/issues/4211#issuecomment-1367386231_

**Comment by dberenbaum** [comment]
I think we should make this a broader troubleshooting to explain common issues users might face when DVC needs to authenticate a Git repo. Some example issues that could be covered (I think there have been more):

* https://github.com/iterative/dvc/issues/9012
* https://github.com/iterative/dvc-ssh/issues/20

Things to include:
* DVC will read from credential helpers; suggest to use those.
* DVC does not support interactive authentication, so the credentials must be stored somewhere already (like from having git cloned separately) before you can use them.
* Keep in mind that local/repo-specific config will not be used when cloning another repo.
* Mention known limitations like https://github.com/iterative/dvc-ssh/issues/20.

**Comment by dberenbaum** [comment]
We also claim that `exp push/pull` only support SSH auth, which I don't think should be true anymore.
