### ISSUE TITLE
Animated logo carousel with users & customer companies

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#4214]
We are ready to start exploring the design of the logo carousel for the DVC Home page redo.  The folder with logos is [here](https://drive.google.com/drive/folders/16d-HpXBBg8oYhQqTxU44EgdlZ_jlf1d3?usp=sharing).  We are still working on collecting them.  I would like to see it be a relatively thin line between sections, one logo high, so that it doesn't take up too much space and people can continue to digest the rest of the material on the site.  Also, this way it would look like it's never-ending.

_Originally posted by @jendefig in https://github.com/iterative/dvc.org/issues/3833#issuecomment-1362019112_

**Comment by dberenbaum** [comment]
@jendefig @shcheklein Is this still a p1, and what's the status?

**Comment by jendefig** [comment]
I think that we have enough logos now that we could make this look right.  I just need @jurv11 to give me the rest of the labels from Studio side that we have permission to use that aren't already on the iterative.ai site.

We can add to them as time goes on.

**Comment by jendefig** [comment]
@yathomasi We have enough logos now so that this would be desirable to get finished, including permission for Huggingface which will be great.  I talked to @shcheklein and If we could get just this part of the web redesign over the finish line, that would be great as it will likely be pretty impactful, and then we will hold on the other sections we need to complete.

**Comment by omesser** [comment]
FYI looks like huggingface brand logos are not single colour: https://huggingface.co/brand
@jendefig  - I can't upload the assets to the [DVC Permitted logos](https://drive.google.com/drive/folders/16d-HpXBBg8oYhQqTxU44EgdlZ_jlf1d3) due to permissions

**Comment by jendefig** [comment]
@omesser I already put the logo in SVG form and now PNG in the folder!
