### ISSUE TITLE
there's ambiguity between the terms "stage" and "stage file"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#423]
(Emanating from #321)

- Directly affects `dvc add`, `dvc import`, and `dvc run` command refs.
- Indirectly affects many other docs where these terms are used. See for example the description of the `dvc lock` cmd ref.
- ~~Look also double check the usage of the term "step(s)" (which should be **stages**).~~ Related: #448

**Definitions**

From @mroutis:

> You can say that **_stage_** is a node on a pipeline, and pipelines are the weakly-connected-component subgraphs of a DAG.
> 
> Internally, on the source code, _stage_ is whatever is related to a file ending with .dvc (DVC-file or "**stage file**"). It doesn't imply a "command" or an "action", so dvc add will create a .dvc file describing the path and checksum of a file, without any instructions to generate such output

**Aproach**

From @shcheklein:

> for the documentation we should be thinking from the user perspective first. For example, it means that stage term can be confusing for ppl who are using it to manage data

**Comment by jorgeorpinel** [comment]
After much reviewing the docs AND the core repo code I think the best way to clarify all this would be to
a) Abolish the usage of the term "DVC-file" to eliminate one of the 3 synonyms.
b) Always use "stage file" for files with `.dvc` extension, and "_orphan_ stage file" when necessary for the ones created by the `dvc add` command (without `deps`).
c) Use the term "stage" with the base name of their stage files (e.g. "the `evaluate` stage" corresponds to "stage file `evaluate.dvc`")

Thoughts @shcheklein ?

**Comment by shcheklein** [comment]
My take on this is that orphan stage file and even stage file are too complicated. I would use them only when we deal with pipelines. We should try as much as we can to avoid using terms like stages when we are introducing `dvc add` in the get started, for example.

I agree re the `.dvc`. 

We can consider converting DVC-file and DVC-files into links automatically to the DVC File section.

**Comment by jorgeorpinel** [comment]
My latest PR (#433) already standardizes all the docs as much as possible to "DVC-file" and always links to the DVC-File Format doc in the first occurrence of the term in each doc.

The thing is that the code calls DVC-files "stage files" although I have a pending PR to alleviate that (See https://github.com/iterative/dvc/pull/2112) but internally objects are still called `StageFile` and the term `stage` is used interchangeably in some command outputs. That's why I think sticking with "stage file" even if it's a `dvc add` file with no dependencies is the easiest way to avoid confusion having too many synonyms.

**Comment by shcheklein** [comment]
@jorgeorpinel I don't think it's a problem at all. It makes sense that on a code level we have a way deeper understanding and can use "advanced" terminology. From the user perspective it should be simple, it should be resonating with their needs, etc. We are not optimizing DOCs to be "compatible" with DVC code conventions.

**Comment by jorgeorpinel** [comment]
I think this is resolved now. Both terms "stage" and "stage file" still exist when appropriate, especially in pipeline-related docs.
