### ISSUE TITLE
create glossary

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#424]
From https://github.com/iterative/dvc.org/issues/321#issuecomment-491665471

- [x] Create new **Glossary** ~~doc~~ with definitions to relevant DVC concepts and terms. Use appropriate links to other docs in these definitions.
- [ ] Mention to "utilize the terminology listed in the glossary(linked) consistently" in the docs contrib guide.

---
UPDATE: Main terms that can be grouped in single entries, and related terms to connect with or disambiguate from (ideas):
- Workspace, DVC project - related: SCM repository, working directory
- DVC meta files and directories (in '.dvc/' dir) - related: DVC config file, DVC cache
- Data artifact, data - related: versioning
- DVC cache, cache, "the cache" - related: file checksum, file link, innode, remote cache
- DVC-file - related: stage file, `.dvc` file extension, `Dvcfile` file name, _orphan_ stage file
- DVC remote, remote cache - related: remote location (see external deps/outs guides), cache
- Pipeline, data pipeline - related: command chain, pipeline stage
- Stage, pipeline stage - related: stage file, DVC-file
- DAG, computational graph, command chain - related: pipeline
- Metric?
- DVC workflow? - related: workflow, Git workflow, experiment workflow

(but in alphabetical order)

**Comment by kurianbenoy** [comment]
I would like to work on this after completing #396

**Comment by shcheklein** [comment]
@kurianbenoy sure! but let's coordinate here first with @jorgeorpinel, what terms we should put into Glossary, their definitions, etc.

**Comment by algomaster99** [comment]
To start the list, here are a few suggestions:
- Pipeline/computation graph
- Cache and workspace
- Metric
- Dvcfile

**Comment by ryokugyu** [comment]
@kurianbenoy let's work together on it. I am also working on a tutorial which is about to complete.

**Comment by ryokugyu** [comment]
> To start the list, here are a few suggestions:
> 
> * Pipeline/computation graph
> * Cache and workspace
> * Metric
> * Dvcfile

Further, 
* repro
* staging
* remote
* lock 
* workflow

**Comment by shcheklein** [comment]
Related #296 . I would say glossary should be very simple and it's main purpose probably to serve as an index and as a guide for contributors. While #296 should introduce DVC concepts like cache, workspace, etc in more details.

**Comment by algomaster99** [comment]
@shcheklein  Who is working on this? I can take this up if it is unassigned. :)

**Comment by shcheklein** [comment]
@kurianbenoy have you started working on this? @algomaster99 it would be great, please coordinate with @jorgeorpinel on this as well.

**Comment by jorgeorpinel** [comment]
Thanks for all the interest guys. I came up with this suggestion mainly for some key concepts that aren't really explained in user guides and which probably don't need a full doc each. All of the terms you have listed above I think are already well explained though, so they may not need a glossary entry. Or maybe we can just list them in the glossary without a description, just linked to an appropriate user guide/get started chapter/command ref.

We need to explore the docs in full to find DVC-specific concepts that aren't explained anywhere yet. Maybe the DAG? Stage vs. stage file (aka DVC-file), stage file vs. DVC-file, DVC-file vs `Dvcfile`, orphan stage file, things like that. Things that need disambiguation I guess.

**Comment by jorgeorpinel** [comment]
p.s. should we discuss the details on Discord so everyone in the team can comment and to keep this issue from growing too long in its comments?

**Comment by jorgeorpinel** [comment]
Hi. Please see the updated description and notice that a good way to browse for terms that should probably be listed in the glossary and linked to in their original documents is searching for `**bold**` and `_underline_` terms.

Should we also remove all these **bold**/_underline_ and just link instead @shcheklein ? As well as search for the terms everywhere to find instances that are NOT currently **bold**/_underline_ in order to link those too.

I think at least the first occurrence of glossary terms in each document should be linked and subsequent ones can remain with bold or underline. I also vote to switch to use only _underline_ since **bold** is already widely used to emphasize some phrases in the docs. (BTW all this could perhaps be done automatically in the future.)

**Comment by shcheklein** [comment]
I agree with both - linking it once and removing bold, italic, etc. We definitely should be doing this automatically. I would prefer to have something like Github does when you specify `Fixes ###` - it provides a hover message + and a nicely done way to highlight the link.

**Comment by jorgeorpinel** [comment]
Sounds like the glossary relates to several special features desired that would have to be built into the docs engine.  Perhaps the glossary should be based on a JSON file instead of an MD file, and from therer the engine can load all the terms in order to provide links, tooltips, and generate the glossary page?

cc @algomaster99

**Comment by algomaster99** [comment]
@jorgeorpinel Even I was thinking this! Yeah, will try doing that way.
