### ISSUE TITLE
guide: top-level dvc.yaml sections

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4251]
### Report

Update docs to better reflect that params, metrics, and plots may be either parts of stages or independent entries in dvc.yaml.

**Comment by jorgeorpinel** [comment]
Related to #2572?

We have also discussed moving some or all of https://dvc.org/doc/user-guide/project-structure into a new "File Format Reference" section. Thoughts?

**Comment by dberenbaum** [comment]
Closing in favor of #2572

**Comment by skshetry** [comment]
I wish we had a good name for this. Top-level plots/params/metrics is an odd naming,
even more so in the internals. :)

**Comment by jorgeorpinel** [comment]
Agreed. Has been discussed too but probably merged in that way to docs as a temporary measure. In general I think we can avoid using special names that emphasize technical details like where the plots/params/metrics are defined in a YAML file. They're all still just regular plots/params/metrics.

**Comment by skshetry** [comment]
But I think the problem goes beyond just the naming, we have two places to write a metadata for plots/params/metrics. Maybe we should just document the top-level ones, and slowly deprecate the stage-level from DVC.

**Comment by skshetry** [comment]
Or maybe call top-level ones simply plots/metrics/params and stage-level ones to be Pipeline artifacts/plots/metrics/params?

**Comment by dberenbaum** [comment]
@skshetry Maybe better to discuss in https://github.com/iterative/dvc.org/issues/3763?
