### ISSUE TITLE
Correct documentation URL in dvc <command> -h

### ISSUE THREAD

**Issue by kurianbenoy** [iterative/dvc.org#427]
```
dvc metrics -h
usage: dvc metrics [-h] [-q | -v] {show,add,modify,remove} ...

Commands to add, manage, collect and display metrics.
documentation: https://man.dvc.org/metrics
```

- I would like to fix this bug. So assign me the bug

**Comment by efiop** [comment]
@kurianbenoy What is the bug?

**Comment by efiop** [comment]
The link is correct, it is just a more nicely-looking shortcut.

**Comment by shcheklein** [comment]
It's also about having a stable link which does not depend on the documentation structure.

For example, as part of the #305 we are moving commands like `command-reference/remote-add` to `command/remote/add`. It easy to change the way we redirect `man.dvc.org` and make sure these links still work on older DVC versions.
