### ISSUE TITLE
Studio: live metrics step to push baseline commit first

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4279]
Can we add a step or call out somewhere that the baseline commit from which you start experimenting must be pushed or Studio won't show anything?

**Comment by dberenbaum** [comment]
cc @tapadipti

**Comment by dberenbaum** [comment]
No @tapadipti. If anything, we probably need to think of how to notify users from DVCLive without generating too much noise @daavoo.

**Comment by daavoo** [comment]
> need to think of how to notify users from DVCLive without generating too much noise @daavoo.

Need to revisit the response errors from the API as last time I check they were too generic to distinguish this issue from others.

**Comment by tapadipti** [comment]
@dberenbaum @daavoo do we need to create a new issue for https://github.com/iterative/dvc.org/issues/4279#issuecomment-1415886808?

**Comment by daavoo** [comment]
> @dberenbaum @daavoo do we need to create a new issue for [#4279 (comment)](https://github.com/iterative/dvc.org/issues/4279#issuecomment-1415886808)?

@tapadipti I think we are already discussing it in https://github.com/iterative/studio/issues/4940#issuecomment-1418923336
