### ISSUE TITLE
cases: update Shared Dev Server with an optimization link

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#429]
UPDATE: See summary in https://github.com/iterative/dvc.org/issues/429#issuecomment-553118884 below.

More context here - https://discuss.dvc.org/t/share-nas-data-in-server/180/4?u=shcheklein

**Comment by jorgeorpinel** [comment]
@shcheklein what optimization link? Sorry, I read the discussion not sure what's missing from the shared dev server use case. Do you mean this part mostly?

```console
$ dvc config cache.type "reflink,symlink,hardlink,copy" # to enable symlinks to avoid copying
$ dvc config cache.protected true # to make links RO so that we you don't corrupt them accidentally
```

(Perhaps in an expandable details section?)

**Comment by shcheklein** [comment]
@jorgeorpinel yes, mostly enabling different link types. It's a very important part of that case. Without enabling symlinks and understanding consequences (needed protection) that case does not make much sense. I would not make it expandable, but try to keep it within a paragraph and link to other docs.

**Comment by jorgeorpinel** [comment]
We could even rethink the name of this use case, think about the actual use case.
