### ISSUE TITLE
kwargs are now explicity in DVCLiveLogger

### ISSUE THREAD

**Issue by francisquintallauzon** [iterative/dvc.org#4294]
Per https://github.com/iterative/dvclive/pull/455

The [pytorch-lightning](https://dvc.org/doc/dvclive/api-reference/ml-frameworks/pytorch) documentation suggests that DVCLiveLoggers has `kwargs` as input parameters : 

    **kwargs - Any additional arguments will be used to instantiate a new [`Live`] instance. If `experiment` is used, the arguments are ignored

It does not seem to be the case since the introduction of DVCLive 2.0 where the following parameters are now explicitly available: 
```
- run_name: Optional[str] = "dvclive_run",
- prefix="",
- experiment=None,
- dir: Optional[str] = None,  # noqa pylint: disable=redefined-builtin
- resume: bool = False,
- report: Optional[str] = "auto",
- save_dvc_exp: bool = False,
```

Furthermore, in a separate PR to be created `dvcyaml: bool = True` is suggested to be added to the list of DVCLiveLogger parameters. 

Towards the end of the page, the example given should also be updated to reflect the update to DVCLiveLogger parameters.  This is the part of the document that should be updated.  

```
## Examples

- Using `**kwargs` to customize [`Live`].

```python
from dvclive.lightning import DVCLiveLogger

trainer = Trainer(
    logger=DVCLiveLogger(dir='my_logs_dir'))
trainer.fit(model)
```
```

**Comment by jorgeorpinel** [comment]
Rel. https://github.com/iterative/dvc.org/pull/4286 Cc @daavoo 🙂

**Comment by shcheklein** [comment]
@daavoo is it still relevant?

**Comment by dberenbaum** [comment]
I think we can close this one. It's technically correct that the pytorch lightning DVCLiveLogger takes explicit kwargs rather than `**kwargs`, but that is only because we couldn't make it work with `**kwargs`. The intent is to be consistent with the other ML framework callbacks, which all accept `**kwargs` as a way to specify any other `Live.init()` kwargs.
