### ISSUE TITLE
broken links dvc-philosophy in documentation

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#430]
I found a section in documentation which seems to be broken.
- [https://dvc.org/doc/dvc-philosophy/](https://dvc.org/doc/dvc-philosophy/).

**Comment by shcheklein** [comment]
should be changed to https://dvc.org/doc/understanding-dvc/

**Comment by algomaster99** [comment]
@shcheklein I think it only came as suggestions when searched. So only the API needed an update. Hence closing this :)
