### ISSUE TITLE
docs: automatic linking of "DVC-file(s)" to /doc/user-guide/dvc-file-format ?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#435]
From https://github.com/iterative/dvc.org/pull/433#pullrequestreview-248880490

**Comment by jorgeorpinel** [comment]
I'm not convinced this is a good idea as some docs include the terms DVC-file/DVC-files multiple times and it's not always necessary to link them. All docs should already have at least the first occurrence linked manually.

**Comment by shcheklein** [comment]
k, closing it for. Let's see how it goes. It might be useful to show some glossary references on the right side?

**Comment by jorgeorpinel** [comment]
Glossary references on a side pane or in tooltips would be nice.
