### ISSUE TITLE
command-reference: obsolete state.dir and index.dir config options

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#4385]
### Report

Per https://github.com/iterative/dvc/pull/9151

**Comment by dberenbaum** [comment]
@efiop Are we ready to submit a PR and close this one?

**Comment by efiop** [comment]
@dberenbaum Yes, will do along the way with https://github.com/iterative/dvc/issues/9249

**Comment by hfawaz** [comment]
I am running dvc in an env with read only file system so I cannot do anything inside `/var` I am gonna downgrade dvc then to the last version it was working for me

**Comment by efiop** [comment]
@hfawaz Could you elaborate on your scenario in https://github.com/iterative/dvc/issues/9249 , please?

**Comment by hfawaz** [comment]
@efiop I am in an env with `Read-only File system` with no sudo rights 
So I cannot write in `/var` at all

**Comment by efiop** [comment]
@hfawaz Could you elaborate what that env is? Some kind of container/kubernetes, etc? Is `/tmp` writable?

**Comment by efiop** [comment]
@hfawaz Latest dvc release has `core.site_cache_dir` option https://github.com/iterative/dvc/pull/9298
