### ISSUE TITLE
standardize "remote" related terms

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#440]
Review consistency in usage of terms "remote" vs "data remote" vs "DVC remote" (or even "DVC data remote") throughout docs. Eliminate unnecessary synonyms.

**Comment by dashohoxha** [comment]
@jorgeorpinel is this issue still relevant?

**Comment by jorgeorpinel** [comment]
Yes but it's already listed in #608 actually. Thanks for heads up!
