### ISSUE TITLE
guide: update experiments guide

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4401]
### Report

Meta-issue to track changes needed for the exp guide:

- [x] Add page/section for params and metrics (close #2572)
- [x] Add page/section for artifacts?
- [x] [Running](https://dvc.org/doc/user-guide/experiment-management/running-experiments) (close #2768)
  - [x] Clarify distinction between running in Python and using exp run
  - [x] Explain why to use exp run -- pipelines, run-cache, tuning, queuing, grid search
  - [x] Show grid search
  - [x] Deemphasize checkpoints
  - [x] Show VS Code examples
  - [x] Include cloud experiments
- [x] [Comparing](https://dvc.org/doc/user-guide/experiment-management/comparing-experiments) (close #2995)
  - [x] Focus on exp show, VS Code, and Studio
  - [x] Deemphasize exp list
- [x] [Sharing](https://dvc.org/doc/user-guide/experiment-management/sharing-experiments)
  - [x] High-level workflow for live sharing, pushing, persisting with branch/PR
  - [x] Studio examples
- [ ] Add page/section for advanced experiment configuration?
  - [ ] Templating, dict unpacking, advanced dvc.yaml features (close #2313)
  - [ ] Hydra composition
- [ ] Combined page for managing experiments (sharing/persisting/cleaning)?
  - [x] https://github.com/iterative/dvc.org/issues/4626
- [x] Drop checkpoints guide?
- [x] Incorporate Studio and VS Code more
- [ ] Emphasize how experiments save you from managing git commits

**Comment by daavoo** [comment]
> Add page/section for params and metrics (close
https://github.com/iterative/dvc.org/issues/2572)
> Add page/section for artifacts?

🤔 Does it need to be tied to the experiments guide? 

At this point, I feel like those concepts are not really worth a user guide but rather a good reference (the user guide always ends ups being a reference anyhow) so maybe individual sections of https://github.com/iterative/dvc.org/issues/4381

>  Add page/section for advanced experiment configuration? 

👍 

>  Combined page for managing experiments (sharing/persisting/cleaning)?

👍 

>  Drop checkpoints guide?

👍

**Comment by dberenbaum** [comment]
> 🤔 Does it need to be tied to the experiments guide?
> 
> At this point, I feel like those concepts are not really worth a user guide but rather a good reference (the user guide always ends ups being a reference anyhow) so maybe individual sections of #4381

For params and metrics, a page is probably too much, but I was thinking we should somewhere introduce the concept of how to do "advanced" params and metrics that don't use DVCLive. That could then point to the reference for details. WDYT?

For artifacts, I think it depends on what @aguschin is working on and how much we want to incorporate that into the experiments workflow.

**Comment by dberenbaum** [comment]
@daavoo Would you make it part of `Explain why to use exp run -- pipelines, tuning, queuing, grid search` or a separate item somewhere else?

**Comment by daavoo** [comment]
> @daavoo Would you make it part of `Explain why to use exp run -- pipelines, tuning, queuing, grid search` or a separate item somewhere else?

An item in that list would make sense

**Comment by dberenbaum** [comment]
> Combined page for managing experiments (sharing/persisting/cleaning)?

@daavoo @omesser We have this in the get started now with https://dvc.org/doc/start/experiments/experiment-collaboration. What do you think we need in the guide? Should we frame it as "collaboration"? Or maybe something like "collaboration with git"? I think a lot of this is about showing how you can use experiments in your git workflows to do more than track and compare them. For example, you can apply/checkout, push/share, or do more advanced git workflows like branch/merge on top of other changes.

**Comment by dberenbaum** [comment]
> * Add page/section for advanced experiment configuration?

I'd like to revisit this after looking at pipelines since it crosses both areas. Opened #4670.
