### ISSUE TITLE
Experiment sharing

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4440]
### Report

With https://github.com/iterative/dvc/issues/9074 and https://github.com/iterative/studio/issues/5050 (along with its related stories/issues), we need to document how to share experiments from DVC to Studio. This should include:

- [x] dvc ref: update `dvc config`, `dvc exp push`, and `dvc exp remove` to reflect Studio features (@skshetry).
- [x] studio: @tapadipti what do you think we need to update, if anything?
- [ ] dvc start: update https://dvc.org/doc/start/experiments/experiment-management (thoughts @daavoo?)
- [x] dvc guide: update https://dvc.org/doc/user-guide/experiment-management/sharing-experiments (related to #4401) (@dberenbaum)

**Comment by tapadipti** [comment]
In Studio docs, we should update:
- [Get started: Run and track experiments section](https://dvc.org/doc/studio/get-started#run-and-track-experiments) should mention dvc exps
- [Prepare your repositories section](https://dvc.org/doc/studio/user-guide/projects-and-experiments/what-is-a-project#prepare-your-repositories) should mention dvc exps in addition to live experiments
- [Git history and live metrics section](https://dvc.org/doc/studio/user-guide/projects-and-experiments/what-is-a-project#prepare-your-repositories) should be updated to mention dvc exps

**Comment by dberenbaum** [comment]
I'll take the last item (DVC exp guide). @skshetry @tapadipti @daavoo Could you take the others? 🙏

**Comment by tapadipti** [comment]
I'll work on the second item (studio docs).

**Comment by dberenbaum** [comment]
@daavoo What do you think on the get started docs? We could add something showing experiments in Studio, or we can wait until we have capability to create a PR from Studio (in that case, let's create a separate issue for it).

**Comment by daavoo** [comment]
> or we can wait until we have capability to create a PR from Studio (in that case, let's create a separate issue for it).

Maybe we could wait for that and the ability to remove exps from the UI, so the update would be to add Studio tabs to https://dvc.org/doc/start/experiments/experiment-collaboration ?

**Comment by dberenbaum** [comment]
Let's call this done and open a separate issue to discuss how to incorporate into get started. It's not blocking anything since we have everything documented elsewhere.
