### ISSUE TITLE
exp run: Explicitly document `repro options`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#4495]
### Report

https://dvc.org/doc/command-reference/exp/run doesn't document or list all the actual options of the command but instead mentions `repro options` in the Synopsis and a small note:

<img width="690" alt="Captura de pantalla 2023-04-26 a las 12 47 23" src="https://user-images.githubusercontent.com/12677733/234552900-c05391ce-1b43-492d-a9f7-df316f31d021.png">

<img width="685" alt="Captura de pantalla 2023-04-26 a las 12 47 37" src="https://user-images.githubusercontent.com/12677733/234552927-586b6907-1a1c-40c8-9070-cb7c3a9b4e68.png">

The page should be self-contained and list all options, matching the `dvc exp run -h` output in the CLI.

During support duty, at least a couple of times I answered questions where the users were not aware of `dvc exp run` supporting a flag that is par of those `repro options`.

**Comment by dberenbaum** [comment]
Semi-related to https://github.com/iterative/dvc/issues/7866. I think this gets us closer to having a single command for running pipelines.
