### ISSUE TITLE
no `git push` in the docs

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#452]
I have not found any `git push` command in Get Started and in other places. I understand the motivation behind - users should know how to work with Git and we don't want to spend time to set up Git remote in the docs.

However, some user might be confused. They might not know Git enough. Or they might decide that `dvc push` executes `git push`.

It might worth clarifying this in the docs.

**Comment by Naba7** [comment]
We have clarified the difference in ``git-push`` and ``dvc-push`` in commands-reference/install.md. Anyway there is no specified mention of ``git-push`` in getting-started. I would love to take this up.

**Comment by shcheklein** [comment]
@Naba7 sure! But, please, let's first outline specific changes you would like to make here first.

**Comment by Naba7** [comment]
@shcheklein  I think of adding ``git push`` under ``share data`` in ``getting-started`` as of:
 - Explaining what is ``git push`` : Updating the remote references with the local references.
 - Can add some of the flags that are also used with ``dvc push``

**Comment by shcheklein** [comment]
@Naba7 sorry for the delay!

I would say it's worth mentioning this in the following places:

1. `dvc push` command reference. https://dvc.org/doc/commands-reference/push
2. https://dvc.org/doc/get-started/share-data like you mentioned. Just expand an existing note here. 

No need to explain git push in both place. Link to it in the command reference should be enough.

**Comment by ryokugyu** [comment]
@shcheklein in the tutorial, we can show usage of  both `dvc push` and `git push`

**Comment by shcheklein** [comment]
@ryokugyu `git push` is implied, I'm not sure we should complicate every code snippet with it

**Comment by Naba7** [comment]
> @Naba7 sorry for the delay!
> 
> I would say it's worth mentioning this in the following places:
> 
>     1. `dvc push` command reference. https://dvc.org/doc/commands-reference/push
> 
>     2. https://dvc.org/doc/get-started/share-data like you mentioned. Just expand an existing note here.
> 
> 
> No need to explain git push in both place. Link to it in the command reference should be enough.

Alright. No problem, you must be busy with other work :)

1. I will explain ``git-push`` in https://dvc.org/doc/get-started/share-data more vividly.
2. I will mention the link of SCM git-push in commands-reference.
