### ISSUE TITLE
Docs: DVC Get started changes

### ISSUE THREAD

**Issue by omesser** [iterative/dvc.org#4520]
A pass of changes after many complaints / ambiguities about how the get-started tutorial "flows" (or doesn't) about its length, and organization.

```[tasklist]

- [ ] #4460
- [ ] #4502
- [ ] #4508
- [ ] #4522
- [ ] #4519
- [ ] separate pipelines to their own trail

```

**Comment by shcheklein** [comment]
Closing this as done? We can split the pipeline into a followup (if we don't have a ticket yet).
