### ISSUE TITLE
Next button doesn't work in nested subpages

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4535]
### Report

It's probably easiest to look at the diagram or video below. When there are 3 levels of pages, and the last subpage on level two has sub-sub-pages on level 3, the "next" button goes to the following page on level 1 instead of the sub-sub-page on level3.

* Page 1
  * Subpage 1
  * Subpage 2 <-- "next" from here goes to page 2 instead of sub-sub-page 1
    * Sub-sub-page 1
    * Sub-sub-page 2
* Page 2

https://github.com/iterative/dvc.org/assets/2308172/078e0671-b9c2-4336-b840-1ba20007ff59

**Comment by shcheklein** [comment]
@dberenbaum I think that was fixed by https://github.com/iterative/gatsby-theme-iterative/pull/201 ? We just need to deploy it (@yathomasi had some issues with the websites and Heroku recently, and give an estimate?)

**Comment by dberenbaum** [comment]
Okay I thought I was going crazy because I couldn't find the issue 😄 . Yep, it would be great to deploy it since it makes navigating the experiments get started really confusing.

**Comment by dberenbaum** [comment]
Thanks @yathomasi! I can confirm that it's working as expected now.
