### ISSUE TITLE
Studio guide reorg

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4552]
@tapadipti @omesser @shcheklein Minor suggestions on some ideas to reorganize the Studio user guide and make it a bit less nested/crowded and emphasize what's important. Feel free to take or leave them.

1. Make the "What is a project" and "What is a Model Registry" pages the index pages for https://dvc.org/doc/studio/user-guide/projects-and-experiments and https://dvc.org/doc/studio/user-guide/model-registry.
2. Move "Projects and Experiments" and "Model Registry" out of the guide completely and put them directly under Studio.

**Comment by tapadipti** [comment]
@dberenbaum 
> Make the "What is a project" and "What is a Model Registry" pages the index pages for https://dvc.org/doc/studio/user-guide/projects-and-experiments and https://dvc.org/doc/studio/user-guide/model-registry.

That is how it is now - https://dvc.org/doc/studio/user-guide/projects-and-experiments and https://dvc.org/doc/studio/user-guide/model-registry auto-redirect to the "What is a project" and "What is a Model Registry" pages. Were you looking for something else?

> Move "Projects and Experiments" and "Model Registry" out of the guide completely and put them directly under Studio.

I'm thinking of moving these and all other pages that are under the User Guide directly under Studio (second screenshot below). wdyt?

Current:
--
<img width="274" alt="image" src="https://github.com/iterative/dvc.org/assets/32855442/0f039b73-493d-4177-9706-35cf37468ec8">

New:
--
<img width="269" alt="image" src="https://github.com/iterative/dvc.org/assets/32855442/357cbab0-0765-47a9-8fb3-1168a7a9687b">

**Comment by dberenbaum** [comment]
> Were you looking for something else?

I was thinking of changing from https://dvc.org/doc/studio/user-guide/projects-and-experiments/what-is-a-project to https://dvc.org/doc/studio/user-guide/projects-and-experiments/index so that there is no individual "What is a project" subpage. It's a minor suggestion, so feel free to take it or leave it.

> I'm thinking of moving these and all other pages that are under the User Guide directly under Studio (second screenshot below). wdyt?

I would rather keep the high-level workflows at the top but not list everything there. That way the basic high-level workflows are highlighted and other "details" are deemphasized. So maybe something more like:

* Studio
  * Get started
  * Projects and Experiments
  * Model Registry
  * User Guide
    * Team collaboration (although no strong opinion if you think this is important enough to put outside the guide)
    * Account management
    * Billing and payment
    * Install GitHub app
    * Connect custom Gitlab server
  * Troubleshooting
  * Self hosting

An alternate idea would be to take the get started sections for each workflow and make them their own pages/subpages somewhere. Overall, it feels like it's too hard to see at a glance what the two main Studio workflows are.

**Comment by dberenbaum** [comment]
> But then `User Guide` does not look like the right title for the collection of the rest of the pages, coz it now misses all the major functionalities. Maybe I can drop `User Guide` altogether, and create 2 more high level items:

🤔 The suggestion of moving up those sections is to highlight them, and by adding more top-level sections next to them, it may defeat the purpose.

What do you think is important to highlight at the top level? I think it would be better to focus on that first, and then we can find a name and place to fit everything else.

WDYT?

**Comment by omesser** [comment]
@dberenbaum @tapadipti wdyt about this suggestion:
- We'll take the [what is a project](https://dvc.org/doc/studio/user-guide/projects-and-experiments/what-is-a-project) and [what is a model registry](https://dvc.org/doc/studio/user-guide/model-registry/what-is-a-model-registry) pages, move them to top level, leave the other more specific "guides" under user guide. their content will still link to pages inside user-guide
- move "self hosting" and "troubleshooting" into user guide

So it'll look like this:

Studio
- Get started
- Intro to Projects
- Intro to Model Registry
- Team collaboration
- User Guide
  - Projects and Experiments
  - Model Registry
  - Account management
  - Billing and payment
  - Install GitHub app
  - Connect custom Gitlab server
  - Troubleshooting
  - Self hosting

### Why? considerations:
- identifying with the need to draw attention to those 2 key aspects as high level items (projects/experiments and MR)
- the content itself i organized in user-guide form, so I think it makes sense keeping it under user guide. I can also imagine future/additional similar guides being naturally places under user-guide/projects or user-guide/model-registry so not having them in user guide will be awkward for discoverability imo

**Comment by tapadipti** [comment]
@omesser Thanks for the proposal. It lgtm. One concern I have though is about Team collaboration not appearing inside User Guide. wdyt about splitting this also into intro and user guide pages (like the projects/MR pages)?

**Comment by dberenbaum** [comment]
> * move "self hosting"

This is the only one that raises any concerns for me. I assumed it was on the top level intentionally because people were asking about this/couldn't find this info, so I would just double check how it got to the top level before moving it.

**Comment by shcheklein** [comment]
Thanks folks. Do we still need "Get Started" in a layout like this? (if we decide to go with it). Also "Projects" -> "Experiments" or "Experiment Tracking" ("Project" is not a scenario by itself to my mind).

What is team collabiration btw?

**Comment by tapadipti** [comment]
> > * move "self hosting"
>
> This is the only one that raises any concerns for me. I assumed it was on the top level intentionally because people were asking about this/couldn't find this info, so I would just double check how it got to the top level before moving it.

I don't think there was any particular discussion on why "self hosting" should be at the top level. So I think it's ok to move it one level down. But I'm also ok keeping at the top-level, coz it is more like an "installation guide" than a user guide.


> Do we still need "Get Started" in a layout like this? 

IMO, no. The `Get started` page currently has get started steps for the following sections:
- Run and track experiments
- Manage models
- Collaborate

If the top-level pages indicate these topics, we don't need a separate get started page.

> Also "Projects" -> "Experiments" or "Experiment Tracking" ("Project" is not a scenario by itself to my mind).

Currently, it's called `Projects and Experiments`. I suggest renaming it to `Experiment Management`.

> What is team collabiration btw?

This has the guide on creating teams, inviting members and upgrading teams to paid service with more seats (or downgrading).

**Comment by tapadipti** [comment]
Closed by https://github.com/iterative/dvc.org/pull/4852
