### ISSUE TITLE
bugs in scripts/completion/dvc.bash

### ISSUE THREAD

**Issue by Naba7** [iterative/dvc.org#457]
In ``run.md`` the flag ``--overwrite-dvc-file`` is documented as ``--overwrite-dvcfile`` 

In documentation ``-v`` is used for ``verbose`` rather than ``-V`` 

Some outdated flags still in use as such ``--all-pipelines`` in ``repro`` and there are some more too.
In ``run``  ``--outs-persist``, ``--outs-persist-no-cache`` are flags but not explained in ``Synopsis``

**Comment by shcheklein** [comment]
It looks like it's a problem with the bash script being out of sync, not with docs. Please, reopen it if there is something actually wrong with the docs. For example if there is some option in `dvc command --help` that is not present in docs, or name is wrong, etc.

**Comment by Naba7** [comment]
Actually, the query here is in ``repro`` ``-P`` or ``--all-pipelines`` is described in ``usage`` but not documented in ``Synopsis`` . The same case with ``--outs-persist`` and ``--outs-persist-no-cache`` in ``run``. Other stuff I had mentioned are bugs in scripts.completion/dvc.bash. But the flags mentioned in ``usage`` and not in ``synopsis`` is a bug in docs/commands-reference.
Thanks:)

**Comment by shcheklein** [comment]
@Naba7 let's open a new issue that describes only the problems in docs, please.
