### ISSUE TITLE
remote add: add more details on setting up Azure

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#462]
More context is here https://github.com/iterative/dvc/issues/2200

**Comment by ryokugyu** [comment]
@shcheklein (https://dvc.org/doc/commands-reference/remote-add#examples)[dvc remote add] section needs to be updated?

because in the Azure example, `connection string` is already mentioned.

**Comment by shcheklein** [comment]
@ryokugyu yep, it does not hurt to add more details to remote add and remote modify. For example, we can put a link there to the ticket with screenshots or to some instruction online.
