### ISSUE TITLE
Improve docs around `dvclice/dvc.yaml`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#4644]
Try to make more obvious the differences between the auto-generated `dvclive/dvc.yaml`, a `dvc.yaml` pipeline, and the `dvcyaml` argument of `Live`.

**Comment by dberenbaum** [comment]
Related: https://discord.com/channels/485586884165107732/563406153334128681/1122890201862262916

**Comment by dberenbaum** [comment]
Also related: need to clarify that dvclive folder should be git-tracked, especially since other trackers usually add some similar folder that gets gitignored.
