### ISSUE TITLE
[BUG] The 'DVC Experiments with Iterative Studio' video on YouTube linked in the docs is unavailable because it is private

### ISSUE THREAD

**Issue by jnareb** [iterative/dvc.org#4646]
### Report

In the DVC documentation, in User Guide, in the "Experiments Management" chapter ("DVC Experiments Overview"), there is "Work with DVC Experiments from a GUI" section, which includes "Iterative Studio" subsection:

https://dvc.org/doc/user-guide/experiment-management#iterative-studio

This "Iterative Studio" subsection is composed solely of the YouTube video - but this video is unavailable, because _This video is private_:

https://youtu.be/hKf4twg832g

The video in "VS Code Extension" subsection below works fine.

**Comment by dberenbaum** [comment]
Thanks for the report @jnareb!
