### ISSUE TITLE
flags in usage not documented in synopsis

### ISSUE THREAD

**Issue by Naba7** [iterative/dvc.org#465]
In ``repro`` ``-P`` or ``--all-pipelines`` is described in ``usage`` but not documented in ``Synopsis`` . The same case with ``--outs-persist`` and ``--outs-persist-no-cache`` in ``run``.

**Comment by ryokugyu** [comment]
you mean, not documented in `Usage` section?

**Comment by ryokugyu** [comment]
not documented in `options` sections? @Naba7
