### ISSUE TITLE
Update Model Registry videos

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#4656]
The video included in this page (https://www.youtube.com/watch?v=szzv4ZXmYAs) must be updated, because path to dvc.yaml is missing in the video and the outdated artifacts.yaml is mentioned. @aguschin are there any other changes needed in the video?

        Also, stages now are split into multiple columns -- models table look different.

_Originally posted by @tapadipti in https://github.com/iterative/dvc.org/pull/4638#discussion_r1241909995_

        The video included in this page (https://youtu.be/Vrp1O5lkWBo) must be updated, because the Use --force … checkbox is missing in the video. @aguschin are there any other changes needed in the video?

        models table and MDP have changed a lot, so it will be easier to re-record it completely I guess.

https://github.com/iterative/dvc.org/pull/4638#discussion_r1241917005

**Comment by dberenbaum** [comment]
Can we close this when we upload the new video?

**Comment by tapadipti** [comment]
@dberenbaum There are a few different MR videos in the docs - an overall one, as well as multiple short ones for specific model actions. The overall video can be replaced by the new one. And I think we can take short clips from the new video to replace the model action videos, or remove those videos altogether and just refer to the single overall video. Let me take a look once the new video is up. Then, we can close this issue.
