### ISSUE TITLE
Unable to find page on Managing External Data

### ISSUE THREAD

**Issue by LahiLuk** [iterative/dvc.org#4673]
### Report

While researching how to set up a remote cache, I found quite a few links pointing to a managing-external-data page, e.g., https://dvc.org/doc/user-guide/managing-external-data#setting-up-an-external-cache. However, following this link returns 404. 

I tried finding the info through the docs search, and while it does show four hits for managing external data:
- [Managing External Data](https://dvc.org/doc/user-guide/data-management/managing-external-data#managing-external-data)
- [How external outputs work](https://dvc.org/doc/user-guide/data-management/managing-external-data#how-external-outputs-work)
- [Setting up an external cache](https://dvc.org/doc/user-guide/data-management/managing-external-data#setting-up-an-external-cache)
- [Examples](https://dvc.org/doc/user-guide/data-management/managing-external-data#examples)

none of those pages can be found.

I was wondering whether this info was removed from the docs, or is it just that the URLs changed?

Searching independently, I was only able to find what might be an alternative location for the How external outputs work section - https://dvc.org/doc/user-guide/pipelines/external-dependencies-and-outputs#how-external-outputs-work.

**Comment by dberenbaum** [comment]
It was reorganized and rewritten into the page you mention and https://dvc.org/doc/user-guide/data-management/importing-external-data. Thanks for the notice. I will add an automatic redirect for those links, which I forgot to do when making the change.
