### ISSUE TITLE
VS Code Integration

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4677]
### Report

Thoughts on how to improve VS Code integration in the docs:

- [x] Add more gifs and examples - where?
- [x] Add tab to download button on landing page
- [ ] Add gifs/examples on landing page - show different interfaces we support (vs code, jupyter, etc.)?

**Comment by dberenbaum** [comment]
I think we should close this and come back to the last item as part of/after the landing page redesign. WDYT @shcheklein?

**Comment by shcheklein** [comment]
Sounds good to me!
