### ISSUE TITLE
Studio: Drop support for custom metric/param files from docs

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#4678]
I think we have already committed to dropping it in https://github.com/iterative/studio/issues/5957 and have started taking action on it in https://github.com/iterative/studio/pull/6293. I don't see much downside to dropping it here.

Originally posted in https://github.com/iterative/dvc.org/pull/4638#discussion_r1253416033 and https://github.com/iterative/dvc.org/pull/4638#pullrequestreview-1515007527

**Comment by dberenbaum** [comment]
@tapadipti I don't see any references to customer metrics left. I'm closing but feel free to reopen if I missed something.
