### ISSUE TITLE
Studio: Miscellaneous docs updates

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#4680]
These are the pending items from https://github.com/iterative/studio/issues/2244.
- [x] In the Get Started page, we can add a link to the [Book an Onboarding Call calendly page](https://schedule.iterative.ai/studio-overview).
- [x] Configure view -> Provide link to the “Demo” public view. 
- [x] Explore ML experiments -> Create a new section called Column Actions: Describe column goals (increase/decrease) and other actions available within a column menu. Update the screenshot to show goals
- [x] Visualize and Compare experiments -> Generate metric plots: Describe the layout of the plots panel and update the screenshot accordingly
- [ ] ~Run experiments: Explain the role of CML more clearly~
- [ ] Account management -> Git integrations: Explain what happens when you connect to multiple Git providers - are all the repos listed? Which one is the main Git account? What happens if you delete the first Git account that you connected to - in this case, which one is the main Git account?
- [x] DVC Studio GitHub App Installation: Create a new page group called Connecting to Git providers. Move the GH App page inside this page group. Create pages for GitLab and Bitbucket (they will have very little content - you just have to say that there is noting to be done here except clicking on the buttons to connect).
- [ ] Add a new page group called “Help”. Inside this, create a “Contact Us” page with all the help links (GH, Discord, etc.). Also create a section called Useful Links (that contains links such as the one to the video of the Meetup where we presented about DVC Studio)
- [ ] Troubleshooting: Move it inside the Help page group.

**Comment by dberenbaum** [comment]
@tapadipti Do they still apply? Are they planned to be addressed?

**Comment by tapadipti** [comment]
@dberenbaum yes, most these items are still relevant. I've checked those items that are either complete or are not relevant any more. I'll try to close this soon.
