### ISSUE TITLE
Implement design changes to the dvc.org landing page

### ISSUE THREAD

**Issue by djsauble** [iterative/dvc.org#4705]
### Report

Design here: https://www.figma.com/file/nq7SOejyDtiaoxk4FplvyO/DQL?type=design&node-id=1672%3A154385&mode=design&t=9o2DOwqsok6aiyqa

Requirements here: https://www.notion.so/iterative/dvc-org-landing-page-redesign-e1f01e8975cb46dcada2dd1efd7a7324

Please let @djsauble know when you're ready for a design handoff and we can go over any questions you have prior to implementation.

**Comment by shcheklein** [comment]
thanks @djsauble . @yathomasi I think we'll need to take it the next sprint.
