### ISSUE TITLE
Support/integration with platforms like SageMaker, Databricks, etc.

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4724]
### Report

Starting with SageMaker and Databricks, document how to work with DVC on those platforms. Need to consider how to structure this inside our docs. Some examples are listed below for reference.

SageMaker
* https://docs.wandb.ai/guides/integrations/sagemaker
* https://docs.neptune.ai/tools/sagemaker/
* https://www.comet.com/docs/v2/integrations/third-party-tools/sagemaker/
* https://wandb.ai/wandb/sm-pytorch-mnist-new/reports/Using-AWS-Sagemaker-and-Weights-Biases-Together-on-Digit-Recognition-with-MNIST---Vmlldzo4MTk3Nzg
* https://aws.amazon.com/blogs/machine-learning/track-your-ml-experiments-end-to-end-with-data-version-control-and-amazon-sagemaker-experiments/

Databricks
* https://docs.wandb.ai/guides/integrations/databricks
* https://wandb.ai/kenlee/databricks_demo/reports/Getting-Started-with-Weights-and-Biases-in-Databricks--VmlldzoyMzQyNzAx
* https://aws.amazon.com/blogs/machine-learning/managing-your-machine-learning-lifecycle-with-mlflow-and-amazon-sagemaker/
* https://heartbeat.comet.ml/integrating-comet-and-azure-databricks-4ec97703a2fe

**Comment by dberenbaum** [comment]
For SageMaker, #4756 is a start. Additional areas to address:

- [ ] Model deployment
- [ ] Other data access patterns (related to https://docs.aws.amazon.com/sagemaker/latest/dg/model-access-training-data.html)
- [ ] Caching s3 outputs (requires https://github.com/iterative/dvc/issues/8411)
- [ ] Logging metrics in training jobs (related to https://github.com/iterative/dvclive/issues/638)

**Comment by efiop** [comment]
So now we have some basic entries for sagemaker and databricks, are there any other popular platforms that would benefit from us having at least some basic integration docs?

**Comment by dberenbaum** [comment]
Although there is a lot more we can do here, let's call this complete and open up new issues for future work.
