### ISSUE TITLE
Homepage terminal is buggy after switching from docs

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#4726]
https://github.com/iterative/dvc.org/assets/20840228/d098c71a-8862-41e2-9ede-c4ff94c37b84

How to reproduce:

1. First load any docs page or manually load the docs page
2. Go to the homepage from the navbar

I suspect it's related to the CSS reset mismatch that comes with `gatsby-theme-iterative` for docs and one with the website.

**Comment by Alemaite** [comment]
Hi @yathomasi, I'll give it a shot. Please assign me the task.

**Comment by yathomasi** [comment]
I can't reproduce the issue.
