### ISSUE TITLE
Improvement in the Tutorial documentation 

### ISSUE THREAD

**Issue by 86mm86** [iterative/dvc.org#475]
In the **Merge the model to master** subsection, within the **Reproducibility** section of the **Tutorial** documentation, the sentence

> The merge has a few conflicts. All of the conflicts are related to md5 checksum miss-matches in the branches. You can properly merge conflicts by prioritizing the checksums from the bigram branch. Or you can simply replace all the checksum by empty string

could be improved providing an external link that explains how to solve git merge conflicts (like [this](https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line)) for inexperienced users. In addition a note like 

> Please be sure to remove all conflict markers: <<<<<<<, =======, >>>>>>>

could be helpful.

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/563406153334128681/596363281049059348

**Comment by shcheklein** [comment]
@86mm86 good idea. could you please, edit the doc? there is a button to the right - "Edit on Github". On the top right corner you will see the pen icon - just click and edit it in place. No need to even clone the project :)

**Comment by 86mm86** [comment]
I have edited the doc according to the suggested changes. Please review and comment in case further editing is necessary.

**Comment by shcheklein** [comment]
@86mm86 Yep, I see the fork. But I don't see the commit with the changes. You should press a green button at the very bottom to save the changes.

**Comment by shcheklein** [comment]
fixed  by #476
