### ISSUE TITLE
Clarify how to use dvclive with pipelines

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4769]
### Report

Related to https://github.com/iterative/dvclive/issues/648, @daavoo raised the point that there are places in the docs where we do not make clear how to integrate dvclive into existing pipelines (often people start with a pipeline and then add dvclive):

- [x] https://dvc.org/doc/start/data-management/metrics-parameters-plots: this still uses `repro` and the old stage metrics and plots, and there's no explanation of how this should work if you want to add dvclive or run experiments
- [ ] https://dvc.org/doc/user-guide/project-structure/dvcyaml-files: the stage metrics and plots don't reference dvclive or top-level metrics/plots (and vice versa)
- [ ] https://dvc.org/doc/command-reference/metrics: only mentions stage metrics (no mention of dvclive or top-level metrics) and uses `repro` over `exp run` here and in `metrics diff` examples
- [ ] [edited to add] https://dvc.org/doc/user-guide/pipelines/defining-pipelines: we mention metrics and plots as special kinds of stage outputs, but in other places we don't include them in stage outputs.
- [ ] [edit] https://dvc.org/doc/dvclive: doesn't mention pipelines here or elsewhere in the dvclive docs except one small section in https://dvc.org/doc/dvclive/how-it-works#run-with-dvc.

**Comment by daavoo** [comment]
I don't know if my hypothesis of this being one of the main sources of confusion is True, but taking the freedom to put p1. At the very least it is p1 to mention/link DVCLive and/or experiment get started guide in those places

**Comment by dberenbaum** [comment]
I think part of the problem is that https://dvc.org/doc/start/data-management/metrics-parameters-plots shows what I would now consider an advanced use case where we set `dvcyaml=False` and add custom plots definitions.
