### ISSUE TITLE
cmd ref: describe `update available` output (for import stages) in `status`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#477]
Related https://github.com/iterative/dvc.org/issues/474

UPDATE: Jump to https://github.com/iterative/dvc.org/issues/477#issuecomment-575969853 for some more details.

**Comment by Naba7** [comment]
Can I take up the issue?

**Comment by shcheklein** [comment]
it depends on #185 , there is a PR #416 by @sanidhyamangal that still requires more work.

**Comment by jorgeorpinel** [comment]
Not sure what this one means. @efiop ? Thanks

**Comment by shcheklein** [comment]
Probably for the imported stages `dvc status` can show the `update available` if running the `dvc update` would move it to the new version.

**Comment by imhardikj** [comment]
@jorgeorpinel I can take this up.
