### ISSUE TITLE
document `cache=True` for `DVCFileSystem`

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#4772]
### Report

DVC now supports caching files opened or downloaded from remotes if `cache=True` is set.
It has a caveat for `fs.open`, that it caches actively before yielding the control back to the user. That is, on `fs.open`, it immediately fetches and caches everything and then returns a file-object from the downloaded file.

See https://github.com/iterative/dvc-data/pull/429 and https://github.com/iterative/dvc-data/pull/428.

```[tasklist]
### Tasks
```

**Comment by dberenbaum** [comment]
@skshetry Can you take this one?
