### ISSUE TITLE
lock: mention that `dvc update` is now also setting `locked: True`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#478]
https://github.com/iterative/dvc/issues/2238

**Comment by jorgeorpinel** [comment]
See #474 first

**Comment by jorgeorpinel** [comment]
More details (per https://github.com/iterative/dvc.org/pull/464#pullrequestreview-259780115) update `dvc import-get` command ref. around phrase "A pipeline can be triggered to re-execute based on". Explanation:

"...by default all external dependencies are going to be locked (`lock: true and -rev-lock: <git-commit-hash>` in the DVC-file). It means when you run dvc repro or dvc status they are not going to check the changes automatically. You will need to explicitly call dvc update to fetch the new data, update the `-rev-lock` field."

**Comment by jorgeorpinel** [comment]
Um... In fact we have no mentions of the `rev_lock` property of DVC-files at all in the docs. Should probably also explain what that is.

**Comment by jorgeorpinel** [comment]
> by default all external dependencies are going to be locked...

@shcheklein  @efiop by "external dependencies" do you mean [these](https://dvc.org/doc/user-guide/external-dependencies)? Or files/artifacts imported with `import*` commands?

**Comment by jorgeorpinel** [comment]
Another note here, [from Discord[(https://discordapp.com/channels/485586884165107732/565759186693128202/604029919785255041)

`dvc unlock` "won't cause problems. If you `dvc unlock` imported stage then it will simply be updated by `dvc repro` next time. and it will check dependency on `dvc status` and stuff.

for a locked stage, `dvc update` does `dvc unlock` + `dvc repro` + `dvc lock` basically".
