### ISSUE TITLE
Should use `:` instead of `.` before images?

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#4787]
Discuss and change accordingly.

              Not feeling strongly (this should not block this PR to be clear), but it does look weird IMO (going from `.` to an image demonstrating the above description).
              I would suggest on aligning on `:`  - not necessarily in this PR

_Originally posted by @omesser in https://github.com/iterative/dvc.org/pull/4758#discussion_r1300061514_

**Comment by shcheklein** [comment]
@tapadipti please put proper labels, priority, better context. thanks.
