### ISSUE TITLE
Model deployment

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4789]
Extend the docs to include info about deploying to SageMaker, to reflect the latest status of https://github.com/iterative/example-repos-dev/tree/master/example-get-started-experiments .

Sections to extend:

- [x] https://dvc.org/doc/start/experiments
Maybe a new chapter about deployment. 
- [ ] https://dvc.org/doc/studio/user-guide/model-registry
Maybe extend each corresponding page with info/links about the implementation of example-get-started-experiments
- [ ] https://dvc.org/doc/user-guide/integrations/sagemaker
Add a section about deployment

**Comment by daavoo** [comment]
Edited the description a little bit but the scope is still not quite clear

**Comment by dberenbaum** [comment]
Added a checkbox for the new sagemaker integrations page.

@daavoo What would help clarify the scope?

**Comment by daavoo** [comment]
> Added a checkbox for the new sagemaker integrations page.
> 
> @daavoo What would help clarify the scope?

I talked with @tibor-mach and will be handing this issue over to him, as he will also make some potential changes to the examples.
To me, what is unclear from the scope is how deep to get in each of these sections and how much "sagemake-specifc" we want the content to be.
Hopefully we can get a quick draft with minimal changes to get a feeling and try to cut the scope in parts

**Comment by dberenbaum** [comment]
@tibor-mach @tapadipti Thoughts on the unchecked items in this list?
