### ISSUE TITLE
doc: update all YAML blocks

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#480]
I noticed a lot of the YAML blocks are outdated for example in their indentation, but maybe also in their actual contents?

- [  ] Look for ```yaml code blocks throughout the docs and verify they are correct by reproducing the example commands they come from.

**Comment by ryokugyu** [comment]
updating all the YAML code blocks. @shcheklein @jorgeorpinel

**Comment by jorgeorpinel** [comment]
Cool @ryokugyu, thanks! Just open a PR and reference this issue with `Fixes #480` in the PR description when ready, so we can all help review the changes.

**Comment by ryokugyu** [comment]
> Cool @ryokugyu, thanks! Just open a PR and reference this issue with `Fixes #480` in the PR description when you have changes you'd like us to help review.
already did this. This is the [link](https://github.com/iterative/dvc.org/pull/488) for PR.

> p.s. I guess you can also assign yourself here?
nope.

**Comment by shcheklein** [comment]
Let's go this as we go. No way we can do this at once.
