### ISSUE TITLE
"get started example" tutorial having a bug?

### ISSUE THREAD

**Issue by hk7219** [iterative/dvc.org#481]
I cloned this tut, https://github.com/iterative/example-get-started and tried reproducing the pipeline and am getting "ValueError: source code string cannot contain null bytes" error. I even manually rewrote the code of featurization.py in case some null characters were messing up the source code but to no avail.

**Comment by robogeek** [comment]
Could not reproduce.  I am on a Mac OS X running High Sierra 10.13.6.

I freshly downloaded and ran the project using these steps:

```
git clone https://github.com/iterative/example-get-started egs
pip install -r requirements.txt
dvc pull
dvc repro -f evaluate.dvc
```
