### ISSUE TITLE
Add aliases for common commands

### ISSUE THREAD

**Issue by BradyJ27** [iterative/dvc.org#4825]
### Report

Alias `dvc mv` = `dvc move`
Alias `dvc rm` = `dvc remove`
Alias `dvc exp ls` = `dvc exp list`
Alias `dvc exp rm` = `dvc exp remove`

Fixes: https://github.com/iterative/dvc/issues/9901
Upstream PR: https://github.com/iterative/dvc/pull/9905

**Comment by dberenbaum** [comment]
@BradyJ27 Do you mind creating the docs PR here? Do you need any pointers?

**Comment by BradyJ27** [comment]
> @BradyJ27 Do you mind creating the docs PR here? Do you need any pointers?

Docs PR is open here: https://github.com/iterative/dvc.org/pull/4926 

Is there additional work required?

**Comment by dberenbaum** [comment]
Sorry 🤦 must have missed that one. Thanks! I'll review it now.
