### ISSUE TITLE
Model registry branding

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4836]
### Report

From https://github.com/iterative/dvc.org/pull/4832#discussion_r1316121305, there are questions about how to reference the model registry. For now, we mostly refer to it as the `Studio Model Registry`, but this has a couple drawbacks:

1. It goes against consolidating everything under the DVC name.
2. It's possible to get most of the model registry functionality without Studio.

**Comment by dberenbaum** [comment]
What about simply `Model Registry`? Users already are inside the DVC docs, so it is probably implied that it's the DVC/Studio Model Registry.

**Comment by shcheklein** [comment]
Yep. We can even got with DVC Model Registry?
