### ISSUE TITLE
update dvcignore docs

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#485]
With merging of https://github.com/iterative/dvc/pull/2161
dvcignored is supported in every walk in the code. 
Reflect that in docs.

**Comment by shcheklein** [comment]
@pared please, give a little bit more details on how it should be updated. It's hard to put `walk` into some actionable/writable context for us :)

**Comment by efiop** [comment]
@pared ?

**Comment by pared** [comment]
@shcheklein , @efiop , sorry must have lost this one in my notifications. It will probably be the best if I do this change. Probably summary of what needs to be written down is not so far away from actual change.
