### ISSUE TITLE
Stale secret deletion

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/dvc.org#4855]
It looks like the following GitHub Actions secrets aren't being used in any of your workflows, at least on the default branch:
* ALGOLIA_ADMIN_KEY

Please ping @iterative/security before 2023-09-22 if you'd like to preserve them.

**Comment by yathomasi** [comment]
Thanks @0x2b3bfa0 for the cleanup.

It was used for indexing blogs and blogs doesn't reside here anymore. 

Feel free to delete anytime.

**Comment by 0x2b3bfa0** [comment]
Awesome! Thanks, @yathomasi!
