### ISSUE TITLE
Running DVC commands on Databricks

### ISSUE THREAD

**Issue by alex000kim** [iterative/dvc.org#4859]
### Report

Currently, the docs state:

> Databricks doesn't provide a classic terminal, so you'll need to use magic commands to run DVC commands.

https://dvc.org/doc/user-guide/integrations/databricks#running-dvc-commands

However, Databricks has had [web terminal](https://docs.databricks.com/en/clusters/web-terminal.html) for a while (with a caveat that it needs to be activated by an admin). 

You can see it in action here: https://www.youtube.com/watch?v=5KUWC7ieAwQ

**Comment by efiop** [comment]
I'm not sure how I didn't find it before. 🤦‍♂️ Thank you!
