### ISSUE TITLE
cmd ref: advanced examples for import (and get)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#487]
> The previous PR was too long. We're extracting this part, which is pending and hopefully the last related to `dvc import` and `dvc get`. See https://github.com/iterative/dvc.org/pull/464#pullrequestreview-259871929

- [x] Note that the `import-url` ref and `external-dependencies` guide also needs an update (See https://github.com/iterative/dvc.org/pull/464#pullrequestreview-257721375).

- [x] Create more sample repos for advanced `import` and possibly `get` command example/s. See https://github.com/iterative/dvc.org/issues/487#issuecomment-517520838 below.

- [x] Actually create/update advanced examples for import/get commands.

- ~~Check the `example-pipeline` carefully. It looks like it might be broken now. (Check both examples in fact.)~~ Moved to #564

- [x] Lets also update get started, work on use cases, etc. to incorporate these important new commands (include also `dvc update`).

**Comment by shcheklein** [comment]
Cool. Makes sense. Not the last though - we'll need to update get started, work on use cases, etc. :)

**Comment by jorgeorpinel** [comment]
TODO stemming from

> Lets also update get started...

- [ ] Review validity of open [get-started issues](https://github.com/iterative/dvc.org/issues?q=is%3Aissue+is%3Aopen+label%3Aget-started) when the above is addressed.

**Comment by jorgeorpinel** [comment]
More details/ideas on " Lets also update get started, work on use cases, etc. to incorporate these important new commands, as well as dvc update" (from [this](https://discordapp.com/channels/485586884165107732/565759186693128202/606552306216992771) Discord thread):

- "we can create a repo that serves as a dataset registry and update get started carefully to show how that dataset can be reused".
   e.g. the raw data file we `wget` in current Get Started step 4 https://dvc.org/doc/get-started/add-files
- WIP

**Comment by jorgeorpinel** [comment]
- [ ] Another discussion to consider for get-started updates: https://discuss.dvc.org/t/about-get-started/194

**Comment by jorgeorpinel** [comment]
Note most progress on this issue is currently being done in https://github.com/iterative/example-repos-dev/commits/master.

**Comment by shcheklein** [comment]
@jorgeorpinel let's do PRs to examples-repos-dev, just to see what's happening.

**Comment by jorgeorpinel** [comment]
> let's do PRs to examples-repos-dev 

OK just noticed that Ivan, will roll back and make a PR for the recent changes.

**Comment by shcheklein** [comment]
@jorgeorpinel no need to rollback, let's just address review changes as a separate PR

**Comment by jorgeorpinel** [comment]
Already rolled back and opened #561.

**Comment by jorgeorpinel** [comment]
Started one at https://github.com/iterative/example-repos-dev/pull/6

**Comment by jorgeorpinel** [comment]
Added another example in https://github.com/iterative/dvc.org/pull/679/commits/131af1ea370592c9237f8e55a2e0202c7fe4246d as part of my current PR for a new data registry case. And will add one more example there soon.
