### ISSUE TITLE
Add Kibsi, Sumer Sports and Motorway logo to logo carousel

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#4873]
### Report

The Kibsi logo is approved to be on the website. 
![image](https://github.com/iterative/dvc.org/assets/34289199/1a4fb69e-82c5-4154-a37a-e1ba55282a72)

**Comment by jendefig** [comment]
![image](https://github.com/iterative/dvc.org/assets/34289199/c3c5ac5f-5ff4-467a-ae57-c13c12674c9f)
Sumer Sports logo

**Comment by jendefig** [comment]
Motorway logo
![motorway logo](https://github.com/iterative/dvc.org/assets/34289199/61d73d50-e856-40a4-bc4e-40ad7a7aa9bf)

**Comment by dberenbaum** [comment]
@jendefig What's the status of this?

**Comment by jendefig** [comment]
@dberenbaum I don't know.  This is a question for @yathomasi.
