### ISSUE TITLE
Wrong path in "Metrics, Parameters and Plots" "Get Started" Docs 

### ISSUE THREAD

**Issue by CoffeeMugTwo** [iterative/dvc.org#4901]
Hi all,

I think this path: https://github.com/iterative/dvc.org/blob/b89c074d6faca564e54898247ae42452363f2353/content/docs/start/data-management/metrics-parameters-plots.md?plain=1#L77C22-L77C22 must be changed to `eval/live/metrics.json`, otherwise `dvc metrics show` yields an error claiming it cannot find `eval/metrics.json`.

Result with original `dvc.yaml`:
```
❯ dvc metrics show
DVC failed to load some metrics for following revisions: ''.          
Path
eval/metrics.json

```

Result with changed `dvc.yaml`:
```
❯ dvc metrics show
Path                    avg_prec.test    avg_prec.train    roc_auc.test    roc_auc.train
eval/live/metrics.json  0.9014           0.95704           0.93196         0.97743

```

I'm using python 3.10.12 and dvc 3.24.0.

**Comment by dberenbaum** [comment]
Thanks for the report @CoffeeMugTwo! That path is correct, but unfortunately it looks like the code that you downloaded in https://dvc.org/doc/start/data-management/data-pipelines#setup is outdated. We will get it fixed ASAP. In the meantime, you can find the updated code in https://github.com/iterative/example-get-started.
