### ISSUE TITLE
start: replace model registry gto-action with calling gto directly

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4947]
TBH I wonder what it looks like without the `gto-action`. Calling gto directly in the script could arguably be more transparent and definitely would be more helpful for non-github users.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/4883#discussion_r1366289861_

**Comment by shcheklein** [comment]
Yep, but on the other hand it's a bit annoying that we have to expose and ask people to deal with an extra tool at all.

**Comment by shcheklein** [comment]
folks, please add proper labels
