### ISSUE TITLE
Must the S3 bucket be exclusive to DVC?

### ISSUE THREAD

**Issue by PRoios** [iterative/dvc.org#4954]
I have a project where I use DVC with remote storage on a S3 bucket. I want to use the same bucket for another project.

Would that interfere with DVC if I don't touch any folder/file generated by DVC?

Let's say I upload a new _dummy/dummy.txt_  to the bucket. Would that bother the DVC configuration?

**Comment by dberenbaum** [comment]
It's a good idea to use a path within the bucket that is only used by dvc, but you can use other paths in the bucket however you would like.
