### ISSUE TITLE
cmd ref: update import-url doc

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#496]
After https://github.com/iterative/dvc/pull/2307 `import-url` will lock stages  by default, which could be either `dvc unlock`ed and `dvc repro`ed or simply `dvc update`ed.

**Comment by jorgeorpinel** [comment]
This was updated in a recent PR. See https://dvc.org/doc/commands-reference/import-url

![image](https://user-images.githubusercontent.com/1477535/62336140-2f177b80-b48c-11e9-8f12-5f53129606ca.png)
