### ISSUE TITLE
cmd ref: add info about cache.shared group and available setting, also in use-cases

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#497]
> Per iterative/dvc/pull/2298

Need to update https://dvc.org/doc/use-cases/multiple-data-scientists-on-a-single-machine and https://dvc.org/doc/commands-reference/config to include `cache.shared` config option.

**Comment by ryokugyu** [comment]
@efiop it's still work in progress. 

btw, what does `cache.shared` does?

I am also working on a use case article https://github.com/iterative/dvc.org/pull/455, maybe they are  relatable.

**Comment by efiop** [comment]
@ryokugyu yep, that PR is still work in progress. Let's get back to it when it is merged. I've just created this issue to not forget about modifying docs.

**Comment by efiop** [comment]
from @mazzma12 from https://github.com/iterative/dvc/issues/497#issuecomment-537454636
```
Note that the group between users has to be a primary group and not a secondary. This can be changed by running : usermod -g groupName $USER
```
