### ISSUE TITLE
Get Started Guide on Model Management - post-publishing updates

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc.org#4990]
### Report

Once Studio shows non-model artifacts we need to update the Getting started Guide on Model Management as per [this](https://github.com/iterative/dvc.org/pull/4883#discussion_r1396154061) comment.

Also add references as per [this](https://github.com/iterative/dvc.org/pull/4883#discussion_r1396165589) comment once #4981 is merged

**Comment by tibor-mach** [comment]
Non-model artifacts PR here - https://github.com/iterative/studio/pull/7767

**Comment by shcheklein** [comment]
folks, please add proper labels and priority (if any)

**Comment by dberenbaum** [comment]
> Once Studio shows non-model artifacts we need to update the Getting started Guide on Model Management as per [this](https://github.com/iterative/dvc.org/pull/4883#discussion_r1396154061) comment.

Done.

> Also add references as per [this](https://github.com/iterative/dvc.org/pull/4883#discussion_r1396165589) comment once #4981 is merged

This should be handled by https://github.com/iterative/dvc.org/issues/5052.

Closing this ticket.
