### ISSUE TITLE
Model registry docs - GitLab CICD template to docs

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc.org#4998]
We have GH Actions CICD template [here](https://dvc.org/doc/start/model-management/model-cicd). 

We need the same structure also for GitLab as many of our customers are GitLab users.

To match the GH example, we need a workflow which:
* runs whenever a tag is pushed (this I managed to do with GitLab CI, but probably not very elegantly)
* has two jobs, uses GTO to parse the tag in the first job
* based on that decides whether to run the second job
* the second job uses dvc artifacts get to download the model.

**Comment by shcheklein** [comment]
folks, please add proper labels and priority (if any)

**Comment by dberenbaum** [comment]
Let's consider #4947 as part of this and close that one

**Comment by mnrozhkov** [comment]
@Tibor here is an example of GitLab CI config for Model Management docs: https://github.com/mnrozhkov/example-get-started-experiments/blob/main/.gitlab-ci.yml 

I tried to make it as much similar to what we have in [.github/worklfows/deploy-model-template.yml](https://github.com/iterative/example-get-started-experiments/blob/main/.github/workflows/deploy-model-template.yml)

**Comment by tibor-mach** [comment]
@mnrozhkov Thanks Mikhail! This looks great. For the docs, I would use the simple version.

Just a few notes:
1. [Here](https://github.com/mnrozhkov/example-get-started-experiments/blob/27df6cea099cc991d6bc5ee704e99ee2be7ad7a7/.gitlab-ci.yml#L3C1-L6C25) the comment says the workflow runs whenever stuff is assigned to prod, but if I understand that correctly this just runs whenever you push any tags at all (which is what we want), right?
2. Just a typo [here](https://github.com/mnrozhkov/example-get-started-experiments/blob/27df6cea099cc991d6bc5ee704e99ee2be7ad7a7/.gitlab-ci.yml#L9C1-L9C69) - "modol" instead of "model"
3. Do we need [this rule](https://github.com/mnrozhkov/example-get-started-experiments/blob/27df6cea099cc991d6bc5ee704e99ee2be7ad7a7/.gitlab-ci.yml#L10C1-L12C37)? It seems like a duplicate, since you check the same thing in the deploy-model job. And if we run the parsing job each time any tags are pushed, it can be re-used as is with any other action. Actually, we probably don't need it [in the second job](https://github.com/mnrozhkov/example-get-started-experiments/blob/27df6cea099cc991d6bc5ee704e99ee2be7ad7a7/.gitlab-ci.yml#L33C1-L35C37) either, because we are then checking for the specific condition in the script itself.

Let me know if I'm missing something @mnrozhkov or if these changes (the third one really, the others are just comments) make sense to you. Thanks!

**Comment by dberenbaum** [comment]
Closing per https://github.com/iterative/dvc.org/pull/5061
