### ISSUE TITLE
tutorials: use a simpler tutorial

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc.org#500]
I would change the tutorial for a very simple one, (for example, the one Kaggle uses for their intro to machine learning: https://www.kaggle.com/learn/intro-to-machine-learning – easy to follow, two scripts (featurization / training), and then branching to try another model; then compare metrics of both models. (Training take seconds instead of minutes.)

**Comment by mroutis** [comment]
From discord, @shcheklein :
* it takes ~1 minute to train it
* data is very small
* memory footprint is 4GB as far as I remember
* so, I do agree that we can come with a simpler scenario, def no a top priority right now
```

**Comment by shcheklein** [comment]
To clarify, that message above is about get started, not tutorial :)

**Comment by jorgeorpinel** [comment]
The [message](https://discordapp.com/channels/485586884165107732/565759186693128202/603249113219203075) from Ivan on this was:

> ...no need to **change** tutorial, there is a room for multiple tutorials.

**Comment by ryokugyu** [comment]
@mroutis here is a link for tutorial created by me.

**Comment by shcheklein** [comment]
@ryokugyu can you find some time and finish the repo with your tutorial? It's hard to understand what's going on - I mean even what problem do we exactly solve? There are some leftovers (like `pyc`), etc. Then we can create a blog post out of it and put a link to the documentation.

**Comment by jorgeorpinel** [comment]
Is this issue basically the same as #546 ** build interactive lessons with katacoda** now?

**Comment by shcheklein** [comment]
no, I think this issue comes from the fact that even get started requires some substantial amount of memory to run. I think, to some extent since we already have Tutorial_s_ now users have way more options, including Katacoda. May be we can specify in the NLP tutorials that they require more memory and there other options available?

**Comment by dashohoxha** [comment]
I have noticed that the [MNIST tutorial](https://katacoda.com/dvc/courses/tutorials/mnist) runs well even on low memory (1.5G RAM). Also it has only 3 stages (featurize, train, evaluate). It also describes experimentation by branches, using methods SVM, PCA and CNN.
Maybe this tutorial should be promoted more.

**Comment by shcheklein** [comment]
We don't have the deep tutorial anymore. Only get started. We'll rely on external tutorials for other cases. It's very hard to support and keep updated too many tutorials.
