### ISSUE TITLE
docs: `dvc unprotect` contains `dvc unlink` synopsis

### ISSUE THREAD

**Issue by truh** [iterative/dvc.org#501]
I have just started using dvc today so I'm not sure if this is perhaps intentional.

<img width="783" alt="Screenshot 2019-07-24 at 14 08 56" src="https://user-images.githubusercontent.com/1183303/61792303-bde92000-ae1c-11e9-9048-e9ce6ca52cc5.png">

https://dvc.org/doc/commands-reference/unprotect

**Comment by shcheklein** [comment]
@truh good catch! This is a bug. Can you edit it with the Edit on Github button on the right? You can then click the pen button on Github (top right corner) and edit the doc in-place. No need to clone anything, etc. :)

**Comment by Naba7** [comment]
@truh Can you please edit the issue with `dvc unlock` rather than `dvc unlink`?

**Comment by ryokugyu** [comment]
@Naba7 i didn't get the issue. please explain to me this.
