### ISSUE TITLE
Inform user how to exit pipeline ascii display

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#503]
Context:
https://discordapp.com/channels/485586884165107732/563406153334128681/603890677176336394

https://dvc.org/doc/commands-reference/pipeline-show#options should probably contain note that `q` can be used to exit from `dvc pipeline show --ascii`

**Comment by ryokugyu** [comment]
@pared  we just need to mention that `press q` to exit the ASCII display?

**Comment by efiop** [comment]
Also related to https://github.com/iterative/dvc/issues/1208

**Comment by efiop** [comment]
@ryokugyu Ideally we should mention all the keys: https://github.com/iterative/dvc/blob/0.53.1/dvc/dagascii.py#L126 . arrows(or WASD) for navigation, q for exit.

**Comment by shcheklein** [comment]
@efiop ideally we should put this instruction to the DVC itself as well. Is it possible? It's too confusing for people who are not familiar with CLI that much.

**Comment by efiop** [comment]
@shcheklein Yep, there is an issue that i've linked above.

**Comment by shcheklein** [comment]
@efiop thanks!
