### ISSUE TITLE
Improve UI: feedback after #4737

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#5031]
Some feedback. Not urgent, this can be implemented after the deployment.

- [ ] Remove CML from Other Tools (footer)
- [ ] CLI on DVC has a bit strange color - it's not easy to read
- [ ] Studio --> DVC Studio
- [ ] CLI on DVCX is too fast 😅  It should be 2x slower.
- [ ] Should we replace `by Iterative.ai` to `by dvc.ai`?

Also, why "Product Hunt" header still not removed? :)

_Originally posted by @dmpetrov in https://github.com/iterative/dvc.org/issues/4737#issuecomment-1839965850_

- [ ] DVC star section show loader or sth before it gets data
<img width="207" alt="Screenshot 2023-12-05 at 11 14 28" src="https://github.com/iterative/dvc.org/assets/20840228/5f394542-c3c4-419c-b356-a371236f821e">

- [ ] change dql to dvcx in the DVCX code

**Comment by jendefig** [comment]
88% of people that come to dvc.org do it on a desktop and this is how it shows up
<img width="1745" alt="image" src="https://github.com/iterative/dvc.org/assets/34289199/ff22a095-c9f7-4486-b4ea-e3b1a827ac1c">


Can we do something to shrink the vertical spacing at the top so that we can see the impactful image under it?

**Comment by dmpetrov** [comment]
Somehow I got this today. It was frozen and never displayed correctly. Not sure if it's but or something on my side.

<img width="1600" alt="Screenshot 2023-12-05 at 4 16 07 PM" src="https://github.com/iterative/dvc.org/assets/10081867/d9230bdf-8770-48ac-b96a-1d891ad99747">

**Comment by dmpetrov** [comment]
- [ ] please change `dql` to `dvcx` in the DVCX code

**Comment by dmpetrov** [comment]
> @dmpetrov Is it still not working after reloading?

It does work now (happend only once). I'm afraid that some user can get into this.
