### ISSUE TITLE
Plots templates ref

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#5038]
> Sorry, I missed this one @mattseddon. LGTM although we should consider moving this info out of the CLI ref and focusing less on the `dvc plots` commands here.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/4978#pullrequestreview-1768837444_

**Comment by mattseddon** [comment]
I think the two options for moving the section are:

https://dvc.org/doc/user-guide/experiment-management/visualizing-plots
and/or
https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#plots

The first page is probably a better option. WDYT?
