### ISSUE TITLE
vscode: mention plots debugging tools

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#5057]
From https://github.com/iterative/vscode-dvc/issues/5087:

> 3\. Can we improve documentation to mention existing features for error messages?

**Comment by dberenbaum** [comment]
@mattseddon @mnrozhkov Let's track this step in docs and update plots docs to show how vs code can help debug

**Comment by dberenbaum** [comment]
@julieg18 Could you take this after https://github.com/iterative/vscode-dvc/issues/5087?

**Comment by julieg18** [comment]
@dberenbaum, would creating a video demoing how VSCode shows plot errors suffice?

**Comment by dberenbaum** [comment]
Yep, that would be best I think. Thanks @julieg18!
