### ISSUE TITLE
Update dvc studio integration to use `dvc studio login`

### ISSUE THREAD

**Issue by yathomasi** [iterative/dvc.org#5083]
Should we update this to use `dvc studio login`?

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/5064#discussion_r1441956465_

**Comment by yathomasi** [comment]
@amritghimire @dberenbaum 

I don't think we will use the new auth flow for CI/CD script. 
Is it okay to leave those as it is or do we have another workaround for that case? 
**Current Usage:**
```
run: |
     dvc config --global studio.token ${{ secrets.DVC_STUDIO_TOKEN }}
```

**Comment by dberenbaum** [comment]
You could leave it as is, or there's an environment variable that could be set:

```
env:
  DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
```
