### ISSUE TITLE
docs: missing text elements break <details> section

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#511]
The engine has a feature to automatically make `<details>` sections into expandable boxes e.g.

![image](https://user-images.githubusercontent.com/1477535/62177658-f39d7580-b302-11e9-8832-9637fefd508a.png)

however when there's no text paragraphs or `###` md headers inside `<details></details>`, the result is

![image](https://user-images.githubusercontent.com/1477535/62177706-23e51400-b303-11e9-9ddc-b91098dcee3e.png)

even if there's other contents inside the details section, for example a fenced code block.

**Comment by shcheklein** [comment]
it's expected behavior. `###` defined the name for the expandable section

**Comment by jorgeorpinel** [comment]
Yes I understand. I just think it should just not crate the expandable section when it doesn't find any text to use for the tittle, instead of causing an error. But OK!
