### ISSUE TITLE
Add Banner for promoting meetups

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#5113]
### Report

I'd like to add a banner to the top UNDER the navigation that promotes our upcoming meetups. 

See this from ModelOP
<img width="1780" alt="image" src="https://github.com/iterative/dvc.org/assets/34289199/5b6dcaa9-adf8-4e09-86fd-84a7c6e7f8d0">

Next meetup:
Expert Insights on Developing Safe, Secure, and Trustworthy AI
Webinar | Wednesday, February 14th | 11 am ET

Link to register: https://www.linkedin.com/events/expertinsightsondevelopingsafe-7158518681906413569/about/

Once you get this setup, I can learn how to change them and correct for the next ones.

First choice color on the banner - our orange - #F46737

Note: this shouldn't move anything further down the page!  There's plenty of room under the navigation for it.

**Comment by yathomasi** [comment]
@jendefig 
We already have a banner section above the navbar. I know it's not fancy, but it should work. 

I quickly added the `content`, here is the PR:
- https://github.com/iterative/dvc.org/pull/5115

Preview:

<img width="1728" alt="Screenshot 2024-02-09 at 12 47 07" src="https://github.com/iterative/dvc.org/assets/20840228/5da30632-320b-46a5-8bb0-e3a900e142d3">

PS: If we really want to work on the redesign, we can merge and keep the changes in PR live and work on that.
