### ISSUE TITLE
docs: windows: add mitigation for already existing CRLF

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#5114]
### Report

https://dvc.org/doc/user-guide/how-to/run-dvc-on-windows#how-to-run-dvc-on-windows

we could also suggest using .gitattributes and eol to automatically convert line endings to lf.

**Comment by uditrana** [comment]
Would also add a recommendation to set `core.autocrlf` to False/Input. I think this is the biggest culprit. Even when a repo has all LF file endings... when git checks out them into CLRF it can break `dvc status`.

Git documentation recommends "auto" for Windows users but I think that is wrong for DVC use case

**Comment by aayushk9** [comment]
Hello
After going through https://dvc.org/doc/user-guide/how-to/run-dvc-on-windows#how-to-run-dvc-on-windows
I agree that adding .gitattributes would be a great enhancement, I suggest placing it below this section
![Screenshot 2024-02-09 013808](https://github.com/iterative/dvc.org/assets/96991518/d7cce929-fadc-40dd-9499-6d17b82289af)


I can work on this issue.

**Comment by shcheklein** [comment]
thanks @aayushk9 !

**Comment by aayushk9** [comment]
@shcheklein @efiop I've raised PR, lmk if I need to make any changes.
