### ISSUE TITLE
glossary: no tooltip when there's break lines in <abbr> tags

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#518]
For example the lines

```md
- `etag`: strong ETag response header (only HTTP <abbr>external
  dependencies</abbr> created with `dvc import-url`)
```

won't produce a glossary tooltip. But they should.

If we require `<abbr>` terms to be in a single line, then maybe the automatic linter (`pretty-quick`) that runs on a Git pre-commit hook should enforce that format, like it enforces `quoted text` to be in a single line?

**Comment by jorgeorpinel** [comment]
What do you think @algomaster99? Thanks

**Comment by algomaster99** [comment]
@jorgeorpinel `prettier` and `Rewraps` plugin both take care of it. They put `<abbr>...</abbr>` in one line.
![format](https://user-images.githubusercontent.com/35191225/62531024-37423300-b85f-11e9-94b3-acbcd91be9a4.gif)

**Comment by jorgeorpinel** [comment]
Not when there's a space in the term e.g. `<abbr>data artifact</abbr>`.

**Comment by algomaster99** [comment]
@jorgeorpinel 
One solution I have thought for this is to add `'external\ndependencies'` to the `match` array. Notice that I added a new-line character between the words.

**Comment by shcheklein** [comment]
@algomaster99 I think we can "normalize" the term before trying to match it in JS itself. Remove extra spaces, convert \n to space, tabs to spaces, etc.

**Comment by algomaster99** [comment]
@shcheklein I don't get what you mean by normalize? Can you explain?

**Comment by shcheklein** [comment]
@algomaster99:

```
} else if (props.tag === 'abbr') {
    const text = props.children[0]
    return <Tooltip text={text} />
  }
```

you can do something like:

```
const text = normalize_space(props.children[0])
```

**Comment by jorgeorpinel** [comment]
It's either that or making `prettier` force those tags into a single line, if that's possible. But I'm guessing that's not possible to do with `prettier`, so I second normalizing 🙂

**Comment by jorgeorpinel** [comment]
@algomaster99 I thought of another improvement.

- [ ] The `match` terms should be case insensitive so that for example, both <abbr>Workspace</abbr> and <abbr>workspace</abbr> match `workspace` (without having to also specify `Worspace` in the `match` array.

What do you guys think?

**Comment by jorgeorpinel** [comment]
It would also be nice to have a **Glossary** menu item on the nav bar that opens a page in the docs where all these terms are listed (with `<a name='the-term'>` anchors. This is mainly to link from glossary descriptions (because we can't have tooltips inside tooltips) but may be useful in other cases perhaps? And to read the full list in case anyone is curious. What do you think?

**Comment by shcheklein** [comment]
@jorgeorpinel I think it deserves it's own issue. Not a top priority, but let's create an issue for sure.
