### ISSUE TITLE
retrieve data: another easy way to test `dvc pull`

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#526]
Another easy way to test `dvc pull` (on https://dvc.org/doc/get-started/retrieve-data) may be this:
```
cd ..
git clone example-get-started example-1
cd example-1
ls -al data/
ls -al .dvc/
dvc pull
ls -al data/
ls -al .dvc/
ls -al .dvc/cache/
```
This seems a bit more realistic and convincing than `rm -f data/data.xml`.

**Comment by shcheklein** [comment]
@dashohoxha it more realistic, but will complicate the doc and breaks the flow (you have to leave the dir, clone another one, etc). The point of the get started is to try to keep as simple as possible. The example you provided is a good candidate for the command reference. I would definitely rewrite examples here https://dvc.org/doc/commands-reference/pull to use `example-get-started` repo.

**Comment by shcheklein** [comment]
Related: https://github.com/iterative/dvc.org/issues/528

**Comment by dashohoxha** [comment]
> it more realistic, but will complicate the doc and breaks the flow (you have to leave the dir, clone another one, etc).

I agree. Maybe we should close this issue (in favor of the related one).
