### ISSUE TITLE
cmd ref: use example-get-started repo in pull examples

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#528]
To make examples less abstract. Make them more actionable.

See how they're used in https://dvc.org/doc/command-reference/checkout#examples

**Comment by dashohoxha** [comment]
It seems to me that the example of `checkout` is a good one for `pull` as well.
It can even be referenced from the `pull` page with a link like this: https://dvc.org/doc/commands-reference/checkout#examples

I would even go a step further and say: why not factor out interactive examples from the command pages, and then link to the relevant examples from these pages? An interactive example may be linked from more than one command page, and a command page may refer to more than one example. 

(Maybe I should have started a new issue for discussing this idea, I am not sure.)

**Comment by shcheklein** [comment]
Great question. I think they can be very similar but should emphasize different parts. Also, `pull` can be way simpler. And `dvc checkout` can be simplified by making `fetch -aT` as a preparation step (to warm up the cache).

**Comment by imhardikj** [comment]
@shcheklein  @jorgeorpinel  I can work on this issue. As the title suggests there should be a pull example which uses example-get-started repo. 
Something like this: https://dvc.org/doc/tutorials/get-started/retrieve-data

**Comment by jorgeorpinel** [comment]
> And dvc checkout can be simplified by making fetch -aT as a preparation step (to warm up the cache).

- [ ] This is a good point `dvc fetch could be hidden in the "Click and expand to setup the project" section of https://dvc.org/doc/command-reference/checkout#examples

@imhardikj maybe you can start by doing that and open a PR? It will help you understand wha this issue is about. After that, you can also close this issue in the same PR:

> should I add a pull example which uses example-get-started repo. Something like this: https://dvc.org/doc/tutorials/get-started/retrieve-data

It's good that you checked out that page Hardik, but please ignore it for this issue (it will be changing a lot soon). The main idea here is to come up with a way to use the example-get-started repo for https://dvc.org/doc/command-reference/pull#examples (similar to [cmd-ref/checkout#examples](https://dvc.org/doc/command-reference/checkout#examples)).

**Comment by sarthakforwet** [comment]
Hey @jorgeorpinel  @shcheklein  I have made an example for pull examples using example-get-started repo . Could you please assign this issue to me?

**Comment by imhardikj** [comment]
> And dvc checkout can be simplified by making fetch -aT as a preparation step (to warm up the cache).
> 
@jorgeorpinel  After cloning example-get-started repo when I attempt to run `dvc fetch -aT` it gives an unexpected error. It worked before when I was on version 0.92.0. I tried running this on windows too but it gives same error. I coludn't find anything related to this error and raised thi [issue](https://github.com/iterative/dvc/issues/3857) as I thought it was a bug. I found a similar [issue](https://github.com/iterative/dvc/issues/3812) for `dvc pull`.
> * [ ]  This is a good point `dvc fetch could be hidden in the "Click and expand to setup the project" section of https://dvc.org/doc/command-reference/checkout#examples
> 
In checkout [example](https://dvc.org/doc/command-reference/checkout#examples) if we don't use `fetch -aT` in "Click and expand to setup the project" then `dvc fetch` needs to be used again after `git checkout`.
How should I proceed next w.r.t. checkout example?

**Comment by shcheklein** [comment]
@imhardikj this is known p0 problem in the recent DVC version. We are fixing it already, sorry about this inconvenience.

Could you please rely on 0.92 for now?

**Comment by jorgeorpinel** [comment]
Hey @sarthakforwet thanks! This issue is already being worked on though. I'll get back to you on a different one.

**Comment by jorgeorpinel** [comment]
> > And dvc checkout can be simplified by making fetch -aT as a preparation step (to warm up the cache)...
>
> In checkout example if we don't use fetch -aT in "Click and expand to setup the project" then dvc fetch needs to be used again after git checkout.

@imhardikj fetch -aT is not currently used in the expandable section. The suggestion is to add it there so it can be removed from the block further down. There's an explanation about it under that block too, which would probably need to go away (moved into the expandable section too).

However the fetch + checkout parenthesis would have to go away too (not moved, just gone). Instead maybe we can just link "fetch" and "checkout" in `We can now just run dvc pull that will fetch and checkout the most recent` further above? Just a thought.

**Comment by imhardikj** [comment]
@shcheklein @jorgeorpinel This issue got closed because #1340 was merged. But `dvc pull` hasn't been updated yet. I have updated the title and description of #1340.
I will open a new PR to work on `dvc pull` meanwhile can you open this issue again.

**Comment by shcheklein** [comment]
@imhardikj sure thing! thanks.
