### ISSUE TITLE
user-guide: cache/remote/workspace relationships

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#53]
Describe how these three relate and what they are.

**Comment by shcheklein** [comment]
In the user guide the part about basic DVC concepts is missing. Like described in #144 the User Guide should be starting with some introduction to those concepts with some explanation and how they relate to each other. This introduction should server as a reference when we use these concepts in other documents (e.g. command references, and/or examples, tutorials).

Basic concepts should include:
- working space
- cache
- remote
- dvc file
- etc

**Comment by vibhor98** [comment]
Hi @shcheklein, I'm Vibhor and I'm new to DVC community. I have been contributing to the open source projects since more than a year now. I'm GSoD' 19 aspirant. I would like to take up this issue to create user guide to cover up all the remaining concepts. Shall I go ahead? Thanks!

PS: I have already read DVC documentation and found it really helpful in getting started.

**Comment by shcheklein** [comment]
@vibhor98 hi! welcome to the community. I'm happy to see that you are interested in collaborating with us. Sure, would be great if can make some progress with this. Feel free to do a PR. I would recommend though to start with something simpler just to learn our requirements, learn the workflow, learn DVC, etc. After that jump to this one. Let me know what your thoughts are and if you need our help to pick the issue to start with.

**Comment by vibhor98** [comment]
@shcheklein, thanks for quick response! I completely agree! I would like to start from something simpler and later on take up this one. Can you please help me in picking up simpler issues? Thanks!

**Comment by shcheklein** [comment]
@vibhor98 how about this one - https://github.com/iterative/dvc.org/issues/404? And please, join the chat dvc.org/chat and use #dev-docs channel to ask any question re the DVC.

**Comment by shcheklein** [comment]
@vibhor98 if #404 sounds good, please leave a comment that you are taking it. Thanks!

**Comment by jorgeorpinel** [comment]
We should probably also clarify that DVC remotes are not very much like Git remotes. They are cache backups and not distributed copies of the entire DVC repo. Per https://github.com/iterative/dvc.org/issues/1087#issuecomment-607670846

**Comment by jorgeorpinel** [comment]
Guys, can we close this old one in favor of https://github.com/iterative/dvc.org/issues/550#issuecomment-520541603 ? I feel like the community is mostly aware of these differences/relationships now but adding the concepts section will help too.

**Comment by shcheklein** [comment]
Yes, we can close (the title of #550 is misleading to my mind - it was never about (only) SEO, it about introducing people into concepts and their relationships - like this ticket)
