### ISSUE TITLE
DataChain logo needs to be updated on dvc.org too!

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#5307]
### Report

Remember, we still get most of our traffic here!!!!

Please update DataChain logo instance need pages:
[ ] 2nd section main page
[ ] 3rd section main page
[ ] Docs page

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/75a3e57b-a0e7-4cc2-8c82-707a4d9b08f7">
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/ce19927a-fa6e-4a99-8001-cc637992f9cc">
<img width="716" alt="image" src="https://github.com/user-attachments/assets/57848c38-c857-4c75-a2f5-0d16c3c04e9a">

**Comment by yathomasi** [comment]
- Covered by https://github.com/iterative/dvc.org/pull/5308
