### ISSUE TITLE
Repeated code examples in the `Modifying Large Datasets` chapter

### ISSUE THREAD

**Issue by NeroBlackstone** [iterative/dvc.org#5317]
### Report

In section [Granular modifications](https://dvc.org/doc/user-guide/data-management/modifying-large-datasets#granular-modifications):

https://github.com/iterative/dvc.org/blob/bf0c1eeedd94dc0bf4dda4f7d26c2c8b3bfb856f/content/docs/user-guide/data-management/modifying-large-datasets.md?plain=1#L33-L56

and

https://github.com/iterative/dvc.org/blob/bf0c1eeedd94dc0bf4dda4f7d26c2c8b3bfb856f/content/docs/user-guide/data-management/modifying-large-datasets.md?plain=1#L61-L80

These two code examples are talking about the same thing, right?

**Comment by shcheklein** [comment]
They are similar, but one is about a new file, the second one is about modifying an existing file:

> You can [dvc add](https://dvc.org/doc/command-reference/add) one or more new files or subdirectories to this dataset without re-adding the entire dataset. Let's assume we have one new file in the dataset:

vs

> You can also modify one or more existing files or subdirectories. Let's assume we have overwritten one file in the dataset:

I think it's fine to keep the both for now. Thanks for raising a questions though!
