### ISSUE TITLE
lint: `prettier` introduces `---` in some YAML blocks

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#532]
When a ```yaml block starts with `...`, `prettier` changes that for `---`.

See https://github.com/iterative/dvc.org/pull/530#pullrequestreview-272360547 and https://github.com/iterative/dvc.org/pull/530#pullrequestreview-272360593

**Comment by shcheklein** [comment]
another option is to avoid using `...` ... just use a regular YAML comment?

**Comment by jorgeorpinel** [comment]
Yes good thinking... Changed in 2536b99 (included in my open PR) But why is `prettier` doing that?

@algomaster99 do you think this is fixable? If not feel free to just close the issue guys. Thanks

**Comment by shcheklein** [comment]
I don't know why :) but since we have a workaround, let's close this.
