### ISSUE TITLE
add "How to store data on your own server" tutorial/guide

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#54]
Probably needs a better name.

**Comment by shcheklein** [comment]
@efiop do you recall what this issue is about?

**Comment by ei-grad** [comment]
I guess it is about that dvc needs tutorial on how to use ssh remote.

I have failed with this in fact, a little ashamed to say :).

```
[ ei-grad@ei-grad-msi ~/ml/AffectNetDVC py:dvc git:master* ]
→ dvc push -r hetzner
Preparing to upload data to 'ssh://hetzner.ei-grad.ru/affectnet/'
Preparing to collect status from ssh://hetzner.ei-grad.ru/affectnet/
[#########                     ] 30% Collecting information
Error: failed to push data to the cloud - [Errno 2] No such file
```

**Comment by efiop** [comment]
@shcheklein Yeah, something about storing dvc data on your own server and serving it through ssh/http so it is accessible.

@ei-grad You are probably using an older dvc version there. That bug was fixed not that long ago. Unless it is a new bug :)

**Comment by dashohoxha** [comment]
I have developed an interactive example for this: https://katacoda.com/dvc/courses/examples/ssh-storage
Should we close this issue?

**Comment by jorgeorpinel** [comment]
Nice. Maybe @efiop can just confirm that #784 will indeed close this.

**Comment by shcheklein** [comment]
If it's about "dvc needs tutorial on how to use ssh remote" then it's not "use case" - it' more of a tutorial or a part of the guide.

@dashohoxha your katacoda interactive tutorial is good, but like almost all of them are kinda hard to read as a stand alone thing. They can serve as an illustration to the text document the way they made it now. Also, this specific one seems too complicated - 2-3 pages our of 4 are about managing keys, permissions and stuff - you need it to make it runnable, I get it, but it makes them about SSH, not DVC. In docs we solve this with expandable sections and/or external links to the relevant documents usually.

**Comment by shcheklein** [comment]
Changed the title back. I was confused by the interactive tutorial. Reading through @efiop 's explanations it not about just regular SSH remote usage:

> Yeah, something about storing dvc data on your own server and serving it through ssh/http so it is accessible.

@efiop could you elaborate even further? Do you remember any context for this? I suppose it's not about just an overview of SSH remote options?

**Comment by efiop** [comment]
@shcheklein It is about that. Having an ssh-accessible machine, how to use it as a dvc remote.

**Comment by efiop** [comment]
Thinking about it, I'm no longer sure what was unobvious about that, but I tend to say that about a lot of things 🙂 I also didn't provide any references to discord/whatnot, so we can close it, since the docs have improved so much since the last year when I've posted this issue.
