### ISSUE TITLE
term: SCM -> Git

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#540]
Git is the only SCM supported on DVC and probably will be for a long time. Also, most of the docs use likely Git-specific language such as "tags" and "branches", as well as `git ...` commands in sample code blocks.

- [ ] Try to get rid of "SCM", except perhaps in very general descriptions of data versioning problems. Use "Git" or \`git\` otherwise.
- [ ] Review also sentences/paragraphs where "tag" and "branch" is used for terminology correctness.

**Comment by dashohoxha** [comment]
Also I think that it might be better if the option `--no-scm` of `dvc init` is renamed to `--no-git`, since Git is the only SCM supported and there are no plans (yet) to support any other SCM.

**Comment by shcheklein** [comment]
@dashohoxha good point, we can create an alias probably. Create aa ticket with this suggestion on DVC core repo, let's see what the @iterative/engineering thinks about this.

**Comment by jorgeorpinel** [comment]
Yes, this issue I wrote a while ago before it was decided that only Git would be supported (for the time being). Now I think we should replace all mentions of "SCM" for "Git" or `git`.

**Comment by Zenix27** [comment]
I can work on this.

**Comment by jorgeorpinel** [comment]
Sure @Zenix27 this is a simple one to test our process, thanks! Please make sure you've read https://dvc.org/doc/user-guide/contributing/docs first.

**Comment by srishti-nema** [comment]
Hi @jorgeorpinel , is this issue available?

**Comment by pared** [comment]
Hi @srishti-nema! Seems like as of today, @Zenix27 is working on it now. @Zenix27 can you confirm?

**Comment by Zenix27** [comment]
@pared Not now, @srishti-nema  you can move forward on this for now, I am working on understanding the repro.

**Comment by pared** [comment]
@jorgeorpinel can we assign @srishti-nema to that one?

**Comment by jorgeorpinel** [comment]
Sure, go for it @srishti-nema, thanks.
