### ISSUE TITLE
ui: highlight full DVC commands in fenced code blocks

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#541]
```dvc fenced code blocks in Markdown have custom CSS in the docs engine, but it should highlight in blue the entire `dvc ___ __` command (including subcommand, so up to 3 words). Unlike now:

![image](https://user-images.githubusercontent.com/1477535/62815486-f9534200-bade-11e9-9d7d-504087e41ac1.png)

Commands that currently have subcommands:
- `cache`
- `metrics`
- `pipeline`
- `remote`

Related to #392

**Comment by shcheklein** [comment]
Fixed by the recent migration to Gatsby and prisma.js.
