### ISSUE TITLE
glossary: disable `<abbr>` in `#` headers?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#543]
Having `<abbr>` tags around md headers causes a bad tooltip:

![image](https://user-images.githubusercontent.com/1477535/62818186-84e1c880-bb09-11e9-84f2-ae828703fe08.png)

Should we care? Or simply don't add the tags around headers? Please close this issue if the latter is the case. Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel let's just not use them in the titles. I looks too complicated I would say.
