### ISSUE TITLE
lint: wrap js strings (in src/)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#548]
UPDATE: See https://github.com/iterative/dvc.org/issues/548#issuecomment-544209275.

---

OUTDATED:

String values in JavaScript files are currently not automatically wrapped to 80 chars by the pre-commit hook that runs `pretty-quick`, like all other lines of code. If possible, have the linter do this. E.g.

```es6
const strVar  = "Really long string going over 80 characters. Blah blah blah blah blah blah blah"
let templateLit = `
Another long text
Including lines that go over 80 chars. Blah blah blah blah blah blah blah blah blah blah blah blah
`
```

This would be pretty useful to make sure the `glossary.js` strings are properly wrapped, for example.

**Comment by shcheklein** [comment]
@algomaster99 would be great if you can take a look.

**Comment by jorgeorpinel** [comment]
I'm unable to do this in the Prettier [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGBOA1AQx00wF5MAdEAJTgIBt6BPTe6Ac2xhwEspP2EPpwgA3OMQAcABkxgAFkQJh4ONADpMAIXoF5mAEa79RvYePmzpk8aoUo9OFngBbAA674AGR5ZyAA3sAQSgIGHkJVg5MeAAPGHsASSgwegBXABNhVj44NBjFLEFMMUiZOUU1TR0rC2tLG1qmxpaGtut7QKgQABoQCDcYHnRkUCIcCAB3AAUiBDRkEAJRIQzekAMcZQBrJwBlN2VhZG40uD75GBd6AHV5XzzDsDg9+d8eUV8mRbA0Bb6+GgJDBplt2C4CMgAGYMIF9ABWaFiWi2YF2MD2BBccB8UDg0Nh5xAiNie2EjgAimkwvikDD6HCQIc1BJFgYCAYmGxun03LxYDceBlwsgACzSXkTIE3LZuRZ8vIScTrACO1PgoIGCxQBDQAFo8XAMkb1jg4GqeGbQQRwZC6YS+kCXDwCQyiWhyXAqTTXYyYBzBcL5MgAEx9bgEHj0YQAYQgLghi1CePWaSBABUOdr6UCAL65oA).

**Comment by algomaster99** [comment]
@jorgeorpinel @shcheklein they haven't addressed this issue yet. https://github.com/prettier/prettier/issues/4123 I think we need to manually wrap strings. :confused:

**Comment by jorgeorpinel** [comment]
Thanks for your input @algomaster99 we'll keep this issue open linked to that one you mentioned.

If you have time, please let us know whether you can look into the first checkbox in #461

> - Fix mobile view first

and/or #510

**Comment by algomaster99** [comment]
@jorgeorpinel My exams are on. I will look into it after it :smile:

**Comment by jorgeorpinel** [comment]
If you have time now to research this one @algomaster99 it would be nice, that way we can confirm or remove the issue. Keep in mind we're also using ESlint. This rule can probably address this concern: https://eslint.org/docs/rules/max-len

**Comment by algomaster99** [comment]
@jorgeorpinel ESLint cannot fix this but it can do detect when the line goes above 80 characters. We just need to put `"max-len": [ "error", { "ignoreStrings": false } ],` in configuration.

**Comment by jorgeorpinel** [comment]
Yeah, boo. I tried that rule with `eslink --fix` but it doesn't fix this type of problem, it seems. Well, let's make the issue to fix all the problems it currently reports, at least, and add the rule anyway for the future. Problems:

```console
$ eslint src                
yarn run v1.19.1
$ /Users/drbidibombom/dvc.org/node_modules/.bin/eslint src

/Users/drbidibombom/dvc.org/src/Diagram/index.js
  209:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/Documentation/HeadInjector.js
  10:1  error  This line has a length of 101. Maximum allowed is 80  max-len
  14:1  error  This line has a length of 87. Maximum allowed is 80   max-len
  18:1  error  This line has a length of 95. Maximum allowed is 80   max-len
  22:1  error  This line has a length of 85. Maximum allowed is 80   max-len

/Users/drbidibombom/dvc.org/src/Documentation/Markdown/Markdown.js
  58:1  error  This line has a length of 349. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/Documentation/SidebarMenu/helper.test.js
  260:1  error  This line has a length of 82. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/Documentation/glossary.js
  37:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  46:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  71:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/DownloadButton/index.js
  19:1  error  This line has a length of 91. Maximum allowed is 80   max-len
  23:1  error  This line has a length of 91. Maximum allowed is 80   max-len
  27:1  error  This line has a length of 97. Maximum allowed is 80   max-len
  31:1  error  This line has a length of 100. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/LandingHero/index.js
  145:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  159:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  270:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  294:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/Subscribe/index.js
  32:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  48:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/SubscribeForm/index.js
   8:1  error  This line has a length of 112. Maximum allowed is 80  max-len
  25:1  error  This line has a length of 116. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/Video/index.js
  78:1  error  This line has a length of 102. Maximum allowed is 80  max-len

/Users/drbidibombom/dvc.org/src/styles.js
  78:1  error  This line has a length of 83. Maximum allowed is 80  max-len

✖ 24 problems (24 errors, 0 warnings)
```

**Comment by algomaster99** [comment]
@jorgeorpinel yeah, we have to do it manually first. Once it is fixed, eslint would make sure this error is not there.

**Comment by shcheklein** [comment]
@algomaster99 I think the PR that was merge broke the style of the dvc.org for a few hours:

<img width="1433" alt="Screen Shot 2019-10-28 at 9 15 58 PM" src="https://user-images.githubusercontent.com/3659196/67737433-67195680-f9c8-11e9-99c6-0f3d57b82c39.png">

we don't have a QA team and we trust that engineers do some basic testing. Please, review it again and run it locally every time before we merge or specify [WIP].

I've reverted the changes. Please create a new PR to handle this.

@jorgeorpinel thanks for noticing this!

**Comment by algomaster99** [comment]
@shcheklein 
Sorry, this happened. But I assure it is a very quick fix.

This happened because of writing URLs in `src/Documentation/HeadInjector.js`.
I broke:
```js
<script
  type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/docsearch.js@2.6.2/dist/cdn/docsearch.min.js"
/>
```
into this:
```js
<script
  type="text/javascript"
  src={`
    https://cdn.jsdelivr.net/npm/
    docsearch.js@2.6.2/dist/cdn/docsearch.min.js
  `}
/>
```

The solution could be to:
1. Make use of template literals since we already added to ignore it in `.eslintrc`.
```js
<script
    type="text/javascript"
    src={`https://cdn.jsdelivr.net/npm/docsearch.js@2.6.2/dist/cdn/docsearch.min.js`}
/>
```
2. Or make use of `// eslint-disable-next-line` exactly what we did for that long `svg` tag.
```js
<script
  type="text/javascript"
  // eslint-disable-next-line max-len
  src="https://cdn.jsdelivr.net/npm/docsearch.js@2.6.2/dist/cdn/docsearch.min.js"
/>
```
https://github.com/iterative/dvc.org/pull/715/files#diff-b1d807de8934c24309015d3c1ea18882R58-R59

**Comment by shcheklein** [comment]
@algomaster99 using some special syntax for every URL looks unacceptable to me. Could you please google some discussion how do people deal with this? The most interesting thing here is that prettier broke the code. This looks like a bug to me to be honest.

**Comment by algomaster99** [comment]
@shcheklein Okay, I got it. We could again edit `"max-len": ["error", { "ignoreTemplateLiterals": true, "ignoreUrls": true }],` to ignore URLs too.
Something like this:
```
"max-len": ["error", { "ignoreTemplateLiterals": true, "ignoreUrls": true, "ignoreUrls": true }],
```

**Comment by shcheklein** [comment]
k, looks reasonable

**Comment by algomaster99** [comment]
@shcheklein 
Would you recommend to enclose URLs [here too](https://github.com/iterative/dvc.org/blob/fd8fbbc40d79848db3c5cd4c2bdfb0c5fe4edfd9/src/DownloadButton/index.js#L16) in string rather than template literals just to make the codebase uniform?

**Comment by shcheklein** [comment]
@algomaster99 but they _are_ templates, right?

**Comment by algomaster99** [comment]
@shcheklein Sorry, my bad! Didn't notice. :man_facepalming:

**Comment by jorgeorpinel** [comment]
Did we ever find a full reference of what exactly `plugin:prettier/recommended` does in the ESLint config? Just curious (from https://github.com/iterative/dvc.org/pull/715#issuecomment-547105692).

**Comment by algomaster99** [comment]
@jorgeorpinel https://prettier.io/docs/en/integrating-with-linters.html#recommended-configuration

**Comment by shcheklein** [comment]
@algomaster99 I think it does not answer the question :) Not very helpful link - no information whatsoever.

**Comment by algomaster99** [comment]
@jorgeorpinel @shcheklein 

So there are two packages installed in our project called - `eslint-config-prettier` and `eslint-plugin-prettier`.
1. `eslint-config-prettier` - Its purpose is to switch off all rules which may conflict with prettier configuration. https://github.com/prettier/eslint-config-prettier#special-rules
2. `eslint-plugin-prettier` - Whenever you run `eslint`, this plugin makes sure it will run prettier too. For example, let's say we leave out a semi-colon in our code. Running eslint will return the following log.
![Screenshot from 2019-10-27 12-40-30](https://user-images.githubusercontent.com/35191225/67631047-09491980-f8b7-11e9-9bd4-8951b22dfef9.png)

Now to include these two configurations silmuntaneously, we simply need to add one line in `.eslintrc.json`
```json
{
  "extends": [
    "plugin:prettier/recommended"
  ]
}
```

**Comment by shcheklein** [comment]
@algomaster99 I would clarify though that _special_ rules set is not the full set of rules that are being applied. Probably, this is the full list https://github.com/prettier/eslint-config-prettier/blob/master/index.js . May be there is some other logic around that changes the effective list.

**Comment by algomaster99** [comment]
@shcheklein yes, `eslint-config-prettier` turns off all the rules they have listen in the README . We just switched on `max-len ` for our purpose.
