### ISSUE TITLE
fetch: review sample command output

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#551]
For example from static/docs/commands-reference/fetch.md line 204+:

```
$ dvc checkout
Checking out '{'scheme': 'local', 'path': '.../example-get-started/model.pkl'}' with cache '3863d0e317dee0a55c4e59d2ec0eef33'.
...
```

> Extracted from https://github.com/iterative/dvc.org/pull/549#pullrequestreview-273447046

**Comment by jorgeorpinel** [comment]
The effort for this may be too great. Perhaps we should rather think of a way that will be sustainable in the future to make sure all our code and console examples remain valid as DVC changes. For example generating them all from scripts in a separate `docs-code-examples-dev` Git repo, similar to https://github.com/iterative/example-repos-dev ?

**Comment by shcheklein** [comment]
I would just create a small tickets from time to time to update it. I don't think we need a special machinery around this. At least now. Too much effort.

**Comment by shcheklein** [comment]
As part of this one, I would just grep "{scheme ...}" messages and replace them with human readable versions. It should be straightforward and should not require running all these examples, I hope.

**Comment by jorgeorpinel** [comment]
```
$ dvc checkout
Checking out '{'scheme': ...
```
was just an example. I meant absolutely all the ```dvc code block examples, basically. There's 450 :/

**Comment by shcheklein** [comment]
Yep, I +1 on that it's too much of a scope to update them. But also I'm not sure we need some very specific mechanism to keep them up-to-date. At least for now. Let's just do the best we can when we update docs.

**Comment by jorgeorpinel** [comment]
Fair enough! Hoefuly we can count on users reporting any problems via issues.

**Comment by shcheklein** [comment]
I meant - let's open this particular one open :) Just fix fetch examples. And may be similar outputs around.

**Comment by jorgeorpinel** [comment]
Closing as dupe of https://github.com/iterative/dvc.org/issues/614#issuecomment-546148618.
