### ISSUE TITLE
dvc run option -O

### ISSUE THREAD

**Issue by dzubape** [iterative/dvc.org#557]
Hello! What should I use **dvc run** option **-O** for? It seems, no action behind it.

**Comment by pared** [comment]
Hello @dzubape!
`-O` is the same as `-o` option, but resulting file will not be added under dvc control. It can be used to output files that you not necessarily want dvc to track . For example, in case of small text files, you might want to track  them with git. 
Is this explanation helpful?

PS. We have [help chat](https://dvc.org/chat) where you can ask questions. Usually we respond there faster than or github.
