### ISSUE TITLE
next button skips section entirely

### ISSUE THREAD

**Issue by glema-gpsw** [iterative/dvc.org#559]
If I go to https://dvc.org/doc/tutorial and hit `NEXT`, it won't take me to the `Preparation` item, but rather to https://dvc.org/doc/understanding-dvc. But if I hit `NEXT` again, it will take me to `Collaboration Issues` which is the first item under `Understanding DVC`.
So the `NEXT` button works differently depending on the section. Same thing happens for `Use cases` and `User guides` respectively.

IMHO it would be best to remain inside the Tutorial when hitting `NEXT`.

**Comment by jorgeorpinel** [comment]
Great catch. Let's also review all the Prev/Next buttons throughout docs as some other links also seem outdated (see dupe #571).

**Comment by shcheklein** [comment]
@jorgeorpinel these links are automatically generated, so they should not be out of date. Do you see any wrong examples?

**Comment by jorgeorpinel** [comment]
Hm. No, not any more. It used to be that "Previous" from the change log skipped "Understanding DVC". All good then!
