### ISSUE TITLE
change S3 bucket from old `dvc-share` to new `dvc-public/{prefix}`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#560]
We decided to migrate from an old S3 bucket `dvc-share` to use certain prefixes (folders) in a new `dvc-public` bucket for use in documentation. The prefixes identified now are:

- `code`: For example code archives
- `data`: For sample datasets
- ` remote`: For using as an S3 remote (read-only in examples)

The main use for the bucket is to `wget` (download) files or use as DVC remote (read-only) in the examples throughout command references and Get Started section (as well as in https://dvc.org/doc/commands-reference/get/url) but there are other uses.

- [x] The engine has some hardcoded HTTP 301 redirects pointing to the old bucket. We need to change those.
- [x] All the examples that use either redirected dvc.org URLS or the old bucket directly need to be updated and tested.

---

Spanned from #487

**Comment by jorgeorpinel** [comment]
Also found that

- [ ] http://man.dvc.org/get-url gets redirected to https://dvc.org/doc/commands-reference/get/url (404 Not Found)

**Comment by shcheklein** [comment]
@jorgeorpinel let's create PRs for simple things like get-url right away ... this way we can move faster and granular

**Comment by jorgeorpinel** [comment]
Yes I'm on that process now. Creating git branches etc (:

**Comment by jorgeorpinel** [comment]
Yeah I shouldn't have created this issue. Sorry, my mind slipped! I guess I wanted to leave a record of the actions we're taking thus the full description above ^.

Set to be closed automatically with the new PR now.
