### ISSUE TITLE
dvc.org changelog 0.25 not rendering

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc.org#569]
this page seems to be rendering oddly https://dvc.org/doc/changelog/0.25
I got there after clicking next on the bottom right of https://dvc.org/doc/changelog

**Comment by shcheklein** [comment]
Fixed! thanks!

**Comment by jorgeorpinel** [comment]
Nice catch. Actually I've noticed Prev and Next buttons go to unexpected places some times. E.g. Prev here skips all of "Understanding DVC" and goes to "Tutorial". Opened #571
