### ISSUE TITLE
user-guide: write about managing metrics

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#59]
A small article on how to use `dvc metrics` to manage metrics for your project in the most convenient way.

**Comment by shcheklein** [comment]
What should we highlight for the "most convenient" way? Any hints, tricks on top of what we already have in get started?

**Comment by efiop** [comment]
The current example in 'get-started' is too simple and too specific. I was talking about a more broad article with tips such as `repro -m`.

**Comment by shcheklein** [comment]
Would be beneficial to mention about `repro -m` in the `dvc metrics`. It can go to the #72 as well.

**Comment by shcheklein** [comment]
I think we can close this - we have experiments sections in the Get Started, we have index page in mertics and plots. I think we can do use case about tracking/managing experiments, but it's a separate task. I don't think we need a user guide page for this at the moment.
