### ISSUE TITLE
switch to yarn from npm for package management in nodejs

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#595]
Then you run `npm install` in some cases npm incorrectly updates `package-lock.json` file, which causes bugs then installing app on Mac.

See this ticket for more details: https://github.com/npm/npm/issues/17722
See this discussion for this problem on dvc.org: https://github.com/iterative/dvc.org/pull/585#discussion_r317715747

One posible solution for this problem will be switching to `yarn` from `npm`. `yarn.lock` files didn't have this problem.

**Comment by shcheklein** [comment]
@iAdramelk relevant concern - https://github.com/iterative/dvc.org/pull/597#issuecomment-526487773 . Please take a look when you have a minute.

**Comment by shcheklein** [comment]
Done, thanks @iAdramelk !
