### ISSUE TITLE
import: docs don't mention that a revision can be a tag/branch

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc.org#605]
https://dvc.org/doc/commands-reference/import

The docs don't mention that `--rev` can be a tag or branch.

Ref: https://discordapp.com/channels/485586884165107732/563406153334128681/618485021342433290

**Comment by pared** [comment]
Maybe we should put in in glossary?

**Comment by shcheklein** [comment]
@pared what do you mean by glossary in this context exactly?

**Comment by AlJohri** [comment]
maybe this? https://github.com/iterative/dvc.org/issues/424

**Comment by shcheklein** [comment]
@AlJohri thanks! I'm just trying to understand why glossary and not just commands reference. And what part of the glossary. I think I just didn't expect to see the glossary here :)

**Comment by pared** [comment]
Well, we have this `glossary.js` in project responsible for providing definitions for some more common expressions, like `DVC cache`. I think revision definition should be provided the same way, as this word is used in few places in docs.

**Comment by shcheklein** [comment]
@pared makes sense, thank you for explaining this :)

**Comment by jorgeorpinel** [comment]
We sometimes use "revision", sometimes "version" and they may mean different things. In the context of Git a version or "reference" is [defined by Git itself](https://git-scm.com/book/en/v2/Git-Internals-Git-References), so not sure we want to add to our glossary. But I'll check that we're explaining this in the docs. Thanks

**Comment by jorgeorpinel** [comment]
Will be fixed in #710. See https://dvc-org-pr-710.herokuapp.com/doc/command-reference/import#options.

**Comment by shcheklein** [comment]
My 2 cents on revision vs version. `revision` is a technical term and a way of specifying a version. `version` should be def used when we talk from the user perspective. E.g. Version of a model can be defined by a Git revision (commit, brach name, etc).

Of course this rule is not 100% strict. I think users can understand from the context if we use them interchangeably..

I would double check the difference between revision and reference.

**Comment by jorgeorpinel** [comment]
Good points @shcheklein. Added to #608.
