### ISSUE TITLE
create a collection of simple bash script examples

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#615]
We may call it `dvc-examples` and it will contain simple (minimal) bash script examples that illustrate a single concept or feature.

When we use real life examples (like `example-get-started`), it is often the case that several concepts and features are intertwined. Sometimes this makes it a bit difficult to explain just a single concept/feature without having to explain the others as well (or referring to other explanation pages).

This is where a simple bash script may be useful. It can be minimal and focus just on the concept or feature that needs to be explained (although it may look like an unreal situation). This minimalism may make it easier for the reader to grasp the concept that we are trying to explain.

We can link to these bash examples from the doc pages (command-reference, user-guide, etc.) Moving out examples may also help to keep the doc pages small an uncluttered.

**Comment by shcheklein** [comment]
I think simple bash examples can be useful. Not sure about keeping them in a separate repo and asking ppl follow to an external link - it can make reading docs more complicated to my mind.

Also, some of them might become complicated and not focused on DVC - we will need to run a lot of preparation code - `git init`, `dvc init`, `git commits`, creating tags/branches, come up with some artificial stages, generate some artificial data. 

My take on this, is that we should be including simple bash scripts (as a link to Github or as a snippet is TBD), but we should also keep example-get-started framework, in certain cases it is the easiest way to get data/scripts with `git clone` and ready to show some concept.

> Sometimes this makes it a bit difficult to explain just a single concept/feature without having to explain the others as well (or referring to other explanation pages).

see above. In a lot of cases bash script will be cluttered and unfocused. In a lot of cases (and we should be working to simplify and keep it this way) - example-get-started is made already to show a concept you want to show. Usually, you can illustrate the concept right away. And if not, then the problem not with this framework, but with the way it's used and probably we should update/simplify a specific reference.

**Comment by dashohoxha** [comment]
> but we should also keep `example-get-started` framework

It is absolutely useful. I did not even doubt that. My idea is to add more simple/basic examples, like those that our engineering team uses to explain a situation. I find them useful for educational purposes.

> as a link to Github or as a snippet is TBD

Having them as a separate script has these advantages:
- You can test them easily, to make sure that they work as expected (for example there are no typos).
- You can update them easily to the latest versions of DVC.
- Keeping the doc pages up to date becomes easier.

These scripts should be meant as try-yourself hands-on examples, with commands that should be executed and lots of comments and explanations. They should not be meant as read examples. But you still can get something just by reading them anyway.

**Comment by dashohoxha** [comment]
> These scripts should be meant as try-yourself hands-on examples, with commands that should be executed and lots of comments and explanations. They should not be meant as read examples. But you still can get something just by reading them anyway.

To better explain what I was talking about, I started to write a couple of such examples: https://github.com/dashohoxha/dvc-examples
Then I had the idea of making them interactive.

However, the prize for being able to convert reliably a script to interactive script is that **":;"** has to be used in front of each command, like this:
```bash
## Create a file and track it with DVC:

:; echo 'test 1' > file1.txt

:; cat file1.txt

:; dvc add file1.txt

:; ls -l

:; tree -a

: DVC is now tracking 'file1.txt'.
```

This seems to me a bit clumsy and ugly, but I couldn't find a cleaner solution.
I am not sure anymore if such examples would be useful.
What do you think?

**Comment by dashohoxha** [comment]
By the way, these interactive examples look like a "poor man's katacoda". But since we are already using Katacoda (which is way better), they don't seem to be quite useful.
