### ISSUE TITLE
lock main page scroll when sidebar menu is open on mobile

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#617]
When you open the left-side menu with docs contents and scroll it to the very bottom at some point you start scrolling the document that is hidden behind it. It makes UX feel unpredictable.

**Comment by algomaster99** [comment]
@shcheklein I cannot reproduce this issue.

**Comment by shcheklein** [comment]
@algomaster99 what phone do you use? Did you try to scroll the menu (left-side one, sidebar) to the very bottom of it and then keep scrolling again?

**Comment by algomaster99** [comment]
I have a OnePlus 5 but it has the same behaviour as below
![css](https://user-images.githubusercontent.com/35191225/67137811-a8876480-f258-11e9-9d8b-6b1d4887daac.gif)

**Comment by shcheklein** [comment]
@algomaster99 yep, it looks it's iphone related problem then. Safari engine.

**Comment by shcheklein** [comment]
Not reproducible anymore.
