### ISSUE TITLE
how to: "undo" 'dvc add' + other "how to undo mistakes" recipes

### ISSUE THREAD

**Issue by gwerbin** [iterative/dvc.org#625]
*This issue is 1 of 3 that I was asked to post here, following a conversation on Discord with mroutis and ivan*

I encountered this problem within my first 15 minutes of using DVC: "how do I undo `dvc add`?"

The answer turns out to be:
1. `unprotect` the file, just in case
2. Delete its corresponding .dvc file
3. Optionally run `gc` or look up the MD5 in `data.dvc` and delete it from `.dvc/cache` by hand.

It would be nice if this recipe were included somewhere in the docs.

Part of the reason this procedure was so non-obvious is that I never thought to look in https://dvc.org/doc/commands-reference/add. This turns out to have a complete technical explanation of linking, and what "protect" means in DVC. This document should be referenced early and often, maybe with a sentence like "For a technical explanation of the caching and linking process, see [here](https://dvc.org/doc/commands-reference/add)".

In the meantime, hopefully my [Stackoverflow self-answer](https://stackoverflow.com/a/57967291) will help other users, as well as get the DVC ball rolling on Stackoverflow.

DVC, like Git, admits the possibility of [potentially-destructive beginner mistakes](https://github.com/iterative/dvc/issues/1524). I think it would be good practice to try and anticipate and provide recipes for undoing mistakes, and link to them **prominently** in the getting started documentation.

**Comment by dashohoxha** [comment]
@gwerbin There is an example of how to undo `dvc add` here: https://katacoda.com/dvc/courses/basics/data-management
However this is still unfinished work and not yet advertised on the website of DVC.

**Comment by dashohoxha** [comment]
> In the meantime, hopefully my Stackoverflow self-answer will help other users, as well as get the DVC ball rolling on Stackoverflow.

There is also a stackexchange about DS: https://datascience.stackexchange.com

**Comment by Suor** [comment]
I feel that there should be an easier way)

**Comment by shcheklein** [comment]
@Suor do you meant that there _is_ an easier way already, or rather that it's a good sign to implement one? like `dvc reset` or something?

**Comment by Suor** [comment]
@shcheklein I don't see one, but there probably should be. I am surprised `dvc remove` does something arcane instead of this.

**Comment by Suor** [comment]
BTW, this recipe is also dangerous considering how `dvc gc` operates.

**Comment by shcheklein** [comment]
@Suor agreed! Could you create a ticket for this on the DVC core repo? I also think that using current `dvc gc` is close to nuclear bombing. I would recommend to remove file manually for now.

**Comment by Suor** [comment]
BTW, removing file from cache by hand as suggested in point 3 is also unsafe, that one might be referenced somewhere else.
