### ISSUE TITLE
state which dvc config option (local/global/system) is default

### ISSUE THREAD

**Issue by gwerbin** [iterative/dvc.org#627]
https://dvc.org/doc/commands-reference/config does not state which of `--local` , `--global`, or `--system` is the default, if none of those options is included.

**Comment by gwerbin** [comment]
The default is `--local`, right? I'm happy to make this change myself.

**Comment by shcheklein** [comment]
@gwerbin please, see my comment https://github.com/iterative/dvc.org/pull/628#pullrequestreview-289583585

I think we still can rewrite and clarify it better.
