### ISSUE TITLE
make import-data an official step in get-started

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#634]
See https://dvc.org/doc/get-started/import-data. The last paragraph has "Since this is not an official part of this Get Started..." This should not be the case.

The code example should actually replace the orphan stage from https://dvc.org/doc/get-started/add-files for an import stage. This needs to be updated in https://github.com/iterative/example-get-started also (so actually in [example-repos-dev](https://github.com/iterative/example-repos-dev/blob/master/example-get-started/generate.sh)).

**Comment by Suor** [comment]
This does the same as adding though and we need to demonstrate that too in "Get Started".

**Comment by jorgeorpinel** [comment]
Sure, it's added a few chapters back, in https://dvc.org/doc/get-started/add-files. This issue is to rewrite the history of  ahttps://github.com/iterative/example-get-started/commits/masterdding a commit (and tag) before adding the preparation stage, that replaces data/data.dvc as an import stage.

**Comment by jorgeorpinel** [comment]
Will be addressed in #599
