### ISSUE TITLE
install: example(s) on adding compatible DVC/Git hooks

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#638]
In #629 and https://github.com/iterative/dvc/pull/2505 we introduced exception raising on pre-existing hook. We should explain how Git hook compatible with the ones installed via `dvc install` should look like for users that would like to create their own.

**Comment by jorgeorpinel** [comment]
What are DVC-hooks?

**Comment by pared** [comment]
@jorgeorpinel I think my choice of words to describe it was poor. `DVC-hooks` == `dvc git hooks` installed during `dvc install`

**Comment by jorgeorpinel** [comment]
Thanks for clarifying 🙂 Updated the title, hope I captured the idea correctly.

**Comment by jorgeorpinel** [comment]
@pared hi we don't quite remember the context here. If this is still relevant can you explain a little more what the proposed improvement is? Would it relate mainly to this content? https://dvc.org/doc/command-reference/install

Thanks

**Comment by jorgeorpinel** [comment]
p.s. we're going to close as stale but feel free to reopen if it's still current!
