### ISSUE TITLE
Conf.py is not in the code directory of the sample code

### ISSUE THREAD

**Issue by mrsekut** [iterative/dvc.org#64]
It is a talk of executing the following command in [this part of tutorial](https://dvc.org/doc/tutorial/preparation#getting-the-sample-code).

`$ wget https://dvc.org/s3/so/code.tgz`

By executing this command, `conf.py` is not included in the downloaded `code` directory.

So, if you try to execute the commands in [this part of the tutorial](https://dvc.org/doc/tutorial/define-ml-pipeline#running-in-a-bulk), an error will be displayed.

I got `conf.py` temporarily by referring to [this page](https://blog.dataversioncontrol.com/data-version-control-tutorial-9146715eda46), but since it is tutorial, I thought that it would be better to fix and I set up this issue.

**Comment by efiop** [comment]
Hi @mrsekut !

Great catch! I've re-uploaded `https://dvc.org/s3/so/code.tgz` with all the needed files included.

Thanks,
Ruslan
