### ISSUE TITLE
use-cases: change word in diagram in share-data-and-model-files

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#646]
"Serving" -> "Storage" in https://dvc.org/doc/use-cases/share-data-and-model-files

![image](https://user-images.githubusercontent.com/1477535/65647784-c0f3be80-dfcd-11e9-979a-f72e5f1130fe.png)

**Comment by shcheklein** [comment]
@jorgeorpinel serving is the right word here :) (it's when you need need to open a model file in a Falsk app for example to drive your REST API - you can use `dvc get` or `dvc.api.open` to get the file)

**Comment by jorgeorpinel** [comment]
Cool
