### ISSUE TITLE
should we NOT hardcode dvc.org so much in server.js?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#651]
Specifically in server.js redirects. Should we get the hostname dynamically from the environment instead?

https://github.com/iterative/dvc.org/blob/c049220f41616384cb85e695af869056c8e82e32/server.js#L33-L40

This way also maybe local dev server will be able to provide this redirects (when using a name other than `localhost` in `hosts`).

**Comment by shcheklein** [comment]
the problem here is that we are testing `man.dvc.org` and you can't really test `man.localhost` as far as I remember. But may be there is some workaround to generalize this to work locally.

**Comment by jorgeorpinel** [comment]
You may be able to setup `man.localhost` actually. But I was thinking about a custom local hostname configured in the machine `hosts` file. Or in case the dvc.org domain name changes (unlikely, I know).

In general I just think it's better not to hardcode this kind of thing. Maybe pull it from and env var (and use dot env locally) ?

**Comment by shcheklein** [comment]
@jorgeorpinel yep, sounds reasonable

**Comment by shcheklein** [comment]
With redirects file I think this is solved. If we want local support for this - let's create a separate ticket for testing redirects.
