### ISSUE TITLE
ci: test to check all links

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#652]
We have internal and external links, mainly in our MD files, which tend to change regularly and its easy to break them accidentally for different reasons. We could probably automate this check?

Per https://github.com/iterative/dvc.org/pull/637#pullrequestreview-293487957

**Comment by jorgeorpinel** [comment]
p.s per https://github.com/iterative/dvc.org/pull/637#discussion_r328993919

> There is also this: https://wummel.github.io/linkchecker/ But it seems to be a bit old and bloated.

**Comment by dashohoxha** [comment]
If this issue is still interesting, I may have a look at it and try to build a script.

I did not understand, what was the problem with the other script, that was deleted?

**Comment by shcheklein** [comment]
yep it's definitely useful if it's made part of the CI flow (CircleCI)

**Comment by dashohoxha** [comment]
The script is submitted here: https://github.com/iterative/dvc.org/pull/690

It is not completely robust and reliable, sometimes it may give false-positives, so maybe not suitable for automatic checking and CI. But it may still be useful for manual checking once in a while.

**Comment by jorgeorpinel** [comment]
Thanks. I'm a little behind on my own work but will check it out ASAP.

**Comment by shcheklein** [comment]
@jorgeorpinel @dashohoxha left my comments in the PR. I think it's a good first step, but does not resolve the issue. My major concern, no one will be using it (and someone will just do a PR do delete it like happened already) if it's not integrated into CI system.

**Comment by dashohoxha** [comment]
> My major concern, no one will be using it (and someone will just do a PR do delete it like happened already)

I was actually using the deleted script each time before committing, and it always would find something to fix. But if it was only me that was using it, no problem, I can use a local copy of the script.

> I can accept and merge this, but I feel it won't be used/useful w/o introducing a proper CI setup.

> I think it's a good first step, but does not resolve the issue.

If it is not useful then there is no point in merging it.

Although I tried it manually and it reported a lot of issues (most of them actually are redirection problems, which are not really breaking any thing). It might be useful for manual checking, especially when we restructure the hierarchy of the docs (which we are planning to do).
But again, I can have a local copy and use it for myself.

**Comment by shcheklein** [comment]
> I was actually using the deleted script each time before committing, and it always would find something to fix. But if it was only me that was using it, no problem, I can use a local copy of the script.

why not pre-commit hook? or the yarn command we have now?

> If it is not useful then there is no point in merging it.

I'm not saying that it's not useful. I'm saying that there are extremely high chances that everyone will forget about it later if it's not part of the CI system and even not documented anywhere. It seems to me that it's not that big of a problem to make part of the CI system and run it on changed files? @algomaster99 could you take a look and help @dashohoxha with this?

**Comment by dashohoxha** [comment]
> why not pre-commit hook?

Does this mean that I don't need to check and fix them because the git hooks will do it automatically?

> or the yarn command we have now?

Which yarn command? The one on the one mentioned here: https://dvc.org/doc/user-guide/contributing-docs#doc-style-guidelines-and-tips-for-java-script-and-markdown?
If I have to do to the docs and copy/paste a command, I usually make a small script for it.
By the way, the double star globing syntax mentioned there (`**`) as far as I know does not work by default, needs to be activated/enabled.

> @algomaster99 could you take a look and help @dashohoxha with this?

I would prefer if @algomaster99 takes this script and makes it part of the CI system, because I don't know anything about it.

**Comment by shcheklein** [comment]
@dashohoxha 

> Does this mean that I don't need to check and fix them because the git hooks will do it automatically?

Yep. That's the whole point - it takes care about everything automatically before you do `git commit`.

> Which yarn command? The one mentioned here: https://dvc.org/doc/user-guide/contributing-docs#doc-style-guidelines-and-tips-for-java-script-and-markdown?
If I have to go to the docs and copy/paste a command, I usually make a small script for it.
By the way, the double star globing syntax mentioned there (**) as far as I know does not work by default, needs to be activated/enabled.

I think, yes. @jorgeorpinel can address this question better I believe and concern with **.

> makes it part of the CI system, because I don't know anything about it.

sure, np. Please, address some point in the PR and I'll merge it, will keep this ticket open. We can update the description of the ticket to mention the script.

**Comment by algomaster99** [comment]
@shcheklein sure I will look into it 👌🏼

**Comment by jorgeorpinel** [comment]
Sorry guys, just getting back to this. I think most has been said so let's try to integrate it to CI.

Making scripts for personal use is totally fine of course, but I agree they don't need to be committed if they're not something everyone should be using and integrated to git hooks and/or CI system, or at least documented somewhere as a recommendation (like the shell autocompletion scripts).

> the double star globing syntax mentioned there (**) as far as I know does not work by default.

It seems to be part of the regular Prettier syntax as it's used in several usage examples here: https://prettier.io/docs/en/cli.html

The script did have an error which Ivan already fixed, though.

**Comment by jorgeorpinel** [comment]
Tip: Personal scripts or other files can also "gitignored" in the `.git/info/exclude` file (not to change `.gitingore`.

**Comment by algomaster99** [comment]
@jorgeorpinel @shcheklein @dashohoxha 
![Screenshot from 2019-10-15 02-42-14](https://user-images.githubusercontent.com/35191225/66783417-793dc400-eef5-11e9-9d94-b4ab956b706a.png)

I altered one URL in `version.md` as /doc/**use-guide**/large-dataset-optimization#file-link-types-for-the-dvc-cache but it still gives a `200` response. I am currently figuring out how can we differentiate between actual and `Not Found` pages.

**Comment by jorgeorpinel** [comment]
@algomaster99 will you reuse PR #690 (`check-links` branch)?

**Comment by algomaster99** [comment]
@jorgeorpinel I can use it. Its logic seems correct. But first we need to fix the engine bug.

**Comment by jorgeorpinel** [comment]
Not necessarily. Please see comments in the PR. Thanks

**Comment by shcheklein** [comment]
a good option is to use some external tools - like Hexometer. Any other tools available that will keep monitoring the website?

**Comment by jorgeorpinel** [comment]
> use some external tools - like Hexometer

Good idea. Here's the report:

![image](https://user-images.githubusercontent.com/1477535/72376334-61800280-36d3-11ea-986e-13ae78fc4cf9.png)
> See https://hexometer.com/broken-links/dvc.org

The 6 bad links are:

```
404 https://dvc.org/assets/1ce1117a69b7e41551e0.js
404 https://dvc.org/assets/c1f03f6aff19cf266795.js
404 https://dvc.org/assets/575df23d1a8ff04b8d54.js
404 https://dvc.org/assets/0.4d6f2247fe215b4f7184.css
404 https://dvc.org/assets/07dca80a102d4149e9736d4b162cff6f.ico
```

Which are not from docs or md files. Probably related to `next build`? Idk why they would be broken though.

> See also https://hexometer.com/tools/dvc.org for a full report of the website. Mostly good results, it seems.

**Comment by jorgeorpinel** [comment]
> Any other tools available that will keep monitoring the website?

Well, [Hexometer costs](https://hexometer.com/pricing) for checking continuously and it would only send us reports. I don't think we can integrate in the CI pipeline.

I only know [SAM](https://www.solarwinds.com/server-application-monitor) (includes [Web Link monitor](http://www.solarwinds.com/documentation/en/flarehelp/sam/content/sam-web-link-monitor-sw3326.htm))which is expensive. But probably most APM tools include this?

**Comment by shcheklein** [comment]
I think I'm fine with that tools sending a weekly report or something as a solution.

**Comment by jorgeorpinel** [comment]
OK, we can close this then? Just curious about:

> The 6 bad links are:
>
> 404 https://dvc.org/assets/1ce1117a69b7e41551e0.js
> 404 https://dvc.org/assets/c1f03f6aff19cf266795.js
> 404 https://dvc.org/assets/575df23d1a8ff04b8d54.js
> 404 https://dvc.org/assets/0.4d6f2247fe215b4f7184.css
> 404 https://dvc.org/assets/07dca80a102d4149e9736d4b162cff6f.ico
>
> Which are not from docs or md files. Probably related to `next build`?

**Comment by jorgeorpinel** [comment]
Cc @iAdramelk

**Comment by shcheklein** [comment]
yep, let's close for now (one ticket less 😅 ) .... those come from the `dvc.org/chat` - looks like it's bug in Discord integration?

**Comment by casperdcl** [comment]
I can be assigned here - could add some fixes on top of #690

**Comment by shcheklein** [comment]
@casperdcl just curious, don't you think it can be a bit overkill to support this? Hexometer detects changes once a week I suppose - more or less enough?

**Comment by casperdcl** [comment]
Not sure it's overkill since I think it'll be quick to implement. Hexometer has false positives and doesn't provide instant feedback on a PR...

**Comment by shcheklein** [comment]
@casperdcl kk, let's try this!

**Comment by casperdcl** [comment]
Kewl
