### ISSUE TITLE
add DVC functionality module filer to narrow down docs?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#655]
Similar to the indexed text search available, we could tag all our docs with the different feature modules in DVC – which we have to define first. For example Synchronization, Configuration, Versioning, etc. (Maybe these modules are the same as the new meaning of "use cases" I suggest in https://github.com/iterative/dvc.org/issues/654#issue-499836861.)

Having these tags we could then add a filter in the navigation bar to only show docs related to commands, use cases, etc. related to the selected modules/topics.

**Comment by shcheklein** [comment]
Have you seen something like this in other projects' docs? It feels that it would require a bit of effort to being able to slice docs and keep those "slices" complete, consistent, executable, etc.

**Comment by jorgeorpinel** [comment]
I can't think of any example. I just thought this could be very useful per some talk we had onSlack recently. Defining these modules or topics is also probably something that has already been done and the way the core code may be structured (at least partially), for example the "Sync" functions (pull, push, etc.)

But if we don't have this kind of previous analysis (class diagrams, flow charts, **use cases**, etc) then yes it would be an extra effort, however don't we want to have some basic internal documentation as to the software design? It could be a good initial task for the product design/management drive.

Implementing the actual filter is also an extra effort but I can't think that it's such a huge feat, it just filters the nav bar content dynamically based on tags that we can add to the sidebar.json struct.

I'm also not suggesting this is very high priority BTW. It's kind of a "p3 nice to have" in my view.

**Comment by jorgeorpinel** [comment]
We probably won't need this if we have a good docs content structure. See #1256
