### ISSUE TITLE
make a top-level (user-guide level?) installation page

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#656]
Right now the installation page is a subsection of Get Started: https://dvc.org/doc/get-started/install
I think it should be a top-level section, that includes all the details about installation that are scattered on the other pages (like Bash autocompletion, installation just for testing, installation for development, IDE integrations, etc.

**Comment by shcheklein** [comment]
This should be an UG chapter that will merge all the sections you mentioned. Eventually the one in get started should be simplified and just link to the UG for the details.

There are a few related tickets already to introduce third level properly to the UG.

I don't think there is a need to make it a top level docs section for now. We can reconsider and move out of UG when it's done within the UG first.

Related:  #347 #144
