### ISSUE TITLE
glossary: soft code style constants in tooltip file

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#658]
Soft code all style constants inside `state`.
https://github.com/iterative/dvc.org/blob/c049220f41616384cb85e695af869056c8e82e32/src/Tooltip/index.js#L11

**Comment by jorgeorpinel** [comment]
Do you mean creating a glossary.json config file to load these from? Or maybe in the same glossary.js file?

**Comment by algomaster99** [comment]
@shcheklein What do you suggest?

**Comment by shcheklein** [comment]
@jorgeorpinel I'm not sure I got the question tbh.

**Comment by jorgeorpinel** [comment]
> Do you mean creating a glossary.json config file to load these from? Or maybe in the same glossary.js file?

I was asking Aman what's the meaning of this issue. And assuming I understand it correctly, suggesting to use the existing `glossary.js` file for this.

**Comment by jorgeorpinel** [comment]
@algomaster99 hi! I'm seeing a bunch of style-related values in the `state` of the main component in src/Tooltip/desktop-view.js . Is this what you meant? What is the advantage of doing this vs. just hardcoding the values in the styled components instead? Thanks

**Comment by algomaster99** [comment]
@jorgeorpinel hello! Since there are too many constants, I thought softcoding and explaining them through comments could be beneficial. :sweat_smile:

**Comment by jorgeorpinel** [comment]
Thank you, makes sense.

@shcheklein given that this issue is for a refactoring and we're looking into Gatsby rather now, should we close or remove the priority? Thanks

**Comment by shcheklein** [comment]
It's not Gatsby/Next specific. It's a general programming style issue.

The problem here is that the whole file is written with a lot of "magic" numbers. It's extremely hard to understand why is it, let's say `225` in a certain case. It's extremely hard to change adjust it one place w/o breaking other cases.

The way it should be written - a few fundamental constants and everything else using them to calculate values.

**Comment by jorgeorpinel** [comment]
You're right. The components inside src/Tooltip/ are pretty complicated indeed. In part it is because of the underlying logic, but I want to think they can be refactor to have less repetition indeed.

OK, reestablished the priority here.

**Comment by iesahin** [comment]
There is no such file in `master` anymore. I searched for `class Tooltip extends Component` and nothing found. 

I think we can close this.

**Comment by jorgeorpinel** [comment]
They're in src/components/Documentation/Markdown/Tooltip now. I checked and they look soft coded now so this can stay closed, I think. Can you please confirm when you get a chance @rogermparent ? Thanks
