### ISSUE TITLE
glossary: rewrite tooltip (desktop-view) using "Portals"?

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc.org#663]
React [Portals](https://reactjs.org/docs/portals.html) is a good way to create elements which hover above the DOM. Currently, it is created using `position: fixed` and other relevant styles. I think implementing this will make it more polished.

**Comment by jorgeorpinel** [comment]
What are some example elements that are currently hovering above the DOM? Tooltips? What else? Thanks

**Comment by algomaster99** [comment]
@jorgeorpinel Tooltip but only for mobile view. I tried creating it for desktop too but there were some problems. Refer to [PR](https://github.com/iterative/dvc.org/pull/675).

**Comment by shcheklein** [comment]
@algomaster99 @iAdramelk so, should we just close this then?

**Comment by algomaster99** [comment]
To solve this issue, we will have to position the root element, modal in this case, absolutely w.r.t the text. I couldn't figure out to do so. @iAdramelk do you have any ideas for execution?

**Comment by algomaster99** [comment]
@shcheklein I will have to refer to their code find out how they have done it.
It is working fine though. This issue is opened just to adhere to the conventions. :sweat_smile:

**Comment by iAdramelk** [comment]
@shcheklein I think that we should leave the ticket open, but reduce it's priority. Solving it will require changing the basic layout first, without this changes I also not sure how to solve it right now.

**Comment by jorgeorpinel** [comment]
Per Aman and Alexey it seems this is not high priority. Assigned p2 but maybe doesn't even need a p?

**Comment by fabiosantoscode** [comment]
Maybe we could make the leap and use popper. It's really solid and should be easy to set up:

https://www.npmjs.com/package/react-popper

**Comment by shcheklein** [comment]
not sure it worth spending time on this, tbh. Polishing is definitely not a good primary goal.

**Comment by shcheklein** [comment]
I'm going to close this actually until we have some strong reasons.

**Comment by jorgeorpinel** [comment]
Great logo
![image](https://user-images.githubusercontent.com/1477535/73976397-d66ae480-48ed-11ea-9631-f394495c52c9.png)
