### ISSUE TITLE
react: unexpected URL anchor behavior when reloading a page

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#681]
For example, go to https://dvc.org/doc/user-guide/managing-external-data in a new tab and then scroll down to the examples, and click the 🔗  icon that appears when hovering the cursor over the **Examples** header. This fixes the scroll position to that anchor and adds `#examples` to the URL. Now, reload the page or even select eh address bar and press Enter. The scroll is reset to the top when the page reloads, however the URL remains as https://dvc.org/doc/user-guide/managing-external-data#examples

Only if you completely close the tab and restore it (open it again) will it scroll to the correct location.

> I'm on Version 77.0.3865.90 (Official Build) (64-bit) for Mac.

**Comment by jorgeorpinel** [comment]
Hold on. My report is inaccurate but there's definitely a problem (at least from my browser). Hold on... Will update description above...

**Comment by jorgeorpinel** [comment]
OK, updated!

**Comment by iAdramelk** [comment]
Sorry for late comment. Again, missed everything that was created this week. Maybe we should replace `header` class with some uniq id? this class name also used in tooltips as far as I can see, so `('header')[0]` can potentially lead to conflicts.

**Comment by shcheklein** [comment]
@algomaster99 please, address this concern when you have some time ^^

**Comment by algomaster99** [comment]
@iAdramelk Should we create a separate `const.js` file for keeping constants like this?

**Comment by jorgeorpinel** [comment]
So will #712 be rolled back? Not the best strategy? Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel no, I think it'll be improved a bit.

**Comment by iAdramelk** [comment]
@algomaster99 yes, `const.js` is a good idea.

**Comment by algomaster99** [comment]
Opened a separate issue for moving constants - #714

**Comment by shcheklein** [comment]
I think there is still an improvement required to close this ticket. Ideally it should be done along with the #714 (first step to introduce one constant required for this ticket, do not wait for all of them to be moved).
