### ISSUE TITLE
best-practice: dataset partitioning and/or data compression?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#682]
Both compression and partitioning seem like very relevant topics since we're in the big data field, yet not much of this is covered in our docs. I'm not sure even how many features of DVC support or consider these matters.

~~Needs more exploration and let's definitely wait until after #674 is done.~~

~~Also waiting for feedback on https://github.com/iterative/dvc/issues/1239#issuecomment-535115654~~

Thoughts @iterative/engineering?

**Comment by jorgeorpinel** [comment]
A recent support case involving partitioning (and possibly compression), for example is in [this chat conversation](https://discordapp.com/channels/485586884165107732/563406153334128681/631218018088910849), where they have a Parquet Hadoop-style data warehouse in this given structure:

```
/datawarehouse/date=20190101/file1.parquet
/datawarehouse/date=20190101/file2.parquet
/datawarehouse/date=20190102/file1.parquet
/datawarehouse/date=20190102/file2.parquet
```

and wanted to track and version it in place (externally) as it amounts to PBs of data.

**Comment by efiop** [comment]
@jorgeorpinel What do you mean by partitioning? Could you please elaborate?

**Comment by jorgeorpinel** [comment]
Data files or compressed archives that are divided into several parts like old RAR files allowed you to do, to mention a simple example, or like Apache Parquet [seems to support](https://spark.apache.org/docs/latest/sql-data-sources-parquet.html#partition-discovery) for a more current and data-science-like example. I suppose also Hadoop partitions HDFS data sets to have them distributed in a cluster but honestly I'm not much familiar with Hadoop so I'm not sure whether this would have an impact for `dvc` or whether that kind of partitioning is transparent to 3rd party tools.

**Comment by jorgeorpinel** [comment]
Notes on compression and bundles (archives) from chat with @shcheklein:

> (Compression) ...can work really well for tabular data (CSV/TSV/JSON/text
> ...we can compress on a file level (not a bundle of files). So all files are always compressed the same way
> while preserving deduplication

> The only reason that comes to mind to use bundles (tar for example to avoid CPU costs of compressing images that are already compressed) is to overcome some DVC problems when it has to work with a lot of files in a single directory
> so, it might help performance wise at a cost of extracting it, managing manually these splits, potentially losing deduplication on the remote end if other projects reuse these images (but for example split them into bundles differently)

> Bundle/unbundle them vs having a simple dir, what if I have just one more file - should I wait for more or bundle it alone?, if I want to remove a file from one of the bundles - i will get a new checksum, if I decide to remove half of the files in a bundle should I merge it into another one or keep?
> Bundle == zip archive in that [specific case](https://github.com/iterative/dataset-registry/tree/master/tutorial/ver)
> It’s just compression is a completely separate topic by itself

**Comment by jorgeorpinel** [comment]
Another case of bundling/partitioning was recently mentioned [on Discord](https://discordapp.com/channels/485586884165107732/563406153334128681/638521838347092018). Summary:

> have to group the images on NAS2 into H5 files by SKU to get the upload speed ... they each need to be exploded into images again, one folder per SKU ... need horizontal splits (by [random] SKU) and vertical splits (i.e. across h5 files for train/validate/test) and I need this versioned so i can lookup to see which model a SKU was trained against.

My thought here is to implement some sort of bundler/partitioner middleware that results transparent to DVC. It would need adaptors to known formats like H5, TFRecords, ZIP, etc. I guess.

**Comment by jorgeorpinel** [comment]
Should this be a Best Practice instead of a Use Case? See https://github.com/iterative/dvc.org/issues/72#issuecomment-682868683.

**Comment by jorgeorpinel** [comment]
Hi @efiop @dberenbaum . What do you guys think about this idea? Could it be a good general use case/ entry point for new users interested in solving this?

If not, it is worth keeping the proposal as a prospective "best practice" instead?

Otherwise I'll close this one. Thanks

**Comment by dberenbaum** [comment]
It seems like more of a best practice to me, but I'm still unclear on what the suggestion is. For a use case, it seems like this would need to show off some feature of DVC, but I don't really see how DVC does anything to solve issues of partitioning or compression. If it's about how we suggest users partition or compress data for DVC, then it makes sense as a best practice. Do we actually have some standard recommendation that would make sense as a best practice?

**Comment by jorgeorpinel** [comment]
> Do we actually have some standard recommendation that would make sense as a best practice?

I don't think so. But I know this topic comes up now and then. I think we mainly assume/recommend no compression at least, but some storage platforms can automatically enable it.

As for partitioning I know some large file formats like [Parquet](https://spark.apache.org/docs/latest/sql-data-sources-parquet.html#partition-discovery) (and maybe [HDFS](http://hadoop.apache.org/docs/r1.2.1/hdfs_design.html#NameNode+and+DataNodes)?) allow it (even without compression)

**Comment by jorgeorpinel** [comment]
Closing as I don't think this has come up much and also it will be something we have to document once/if https://github.com/iterative/dvc/issues/829 gets implemented.
