### ISSUE TITLE
image captions in Markdown

### ISSUE THREAD

**Issue by gagejustins** [iterative/dvc.org#685]
It would be cool to have the ability to add captions to images in the docs through Markdown. A caption would: 

- Be centered directly under an image
- Be smaller text than the normal paragraph font size
- Be italicized
- Have narrower margins than the normal paragraph margins

**Comment by shcheklein** [comment]
@algomaster99 could you take a look? https://stackoverflow.com/questions/19331362/using-an-image-caption-in-markdown-jekyll - this link had an example how it can be done without significant changes to the engine
