### ISSUE TITLE
term: word-emphasizing best practice?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#686]
Now we mainly use **bold** words in some docs but not very consistently. There may also be some _italics_ and hopefully no underlines but it's possible (need to check).

Which one of these should we adopt? I think probably just one to keep things simple (so I would incline towards **bold**. What kind of words or phrases should it be applied to?

- [x] Decide (see https://github.com/iterative/dvc.org/issues/686#issuecomment-575966629);
- [x] Note to docs contrib guide (See dfcd3bec); ~~and~~
- ~~Start reviewing all existing docs (a little daunting 😓)~~.

**Comment by jorgeorpinel** [comment]
We should first come to a decision and remove the `question` label, then anyone can help with the rest 🙂

**Comment by jorgeorpinel** [comment]
Looks like we're mostly using bold for **emphasis**, but also italics for special terms like _orphan_ stage file.

**Comment by shcheklein** [comment]
Keep both? I think they just have different meaning. Bold is something you really want someone to read, italic is more like adding "special" before the term? It's a way lighter emphasis.

**Comment by jorgeorpinel** [comment]
Yep, let's keep both. Note added in https://github.com/iterative/dvc.org/pull/931/commits/dfcd3bec3390e7a897edf01de7f8d3e58b837a01.
