### ISSUE TITLE
user-guide: improve Windows POSIX/terminal tips

### ISSUE THREAD

**Issue by LucasErlacher** [iterative/dvc.org#698]
For windows users is necessary past to the same line the command when has `\` in the end of line.

For example:
`dvc get https://github.com/iterative/dataset-registry \
          tutorial/ver/data.zip`

to

`dvc get https://github.com/iterative/dataset-registry tutorial\ver\data.zip`

**It's also necessary use `\` in the path on windows.**

**Comment by shcheklein** [comment]
that's why it's better to keep CLI example as close to one line as possible

Unfortunately, don't see an easy way out of this. Switching modes is too expensive too support at this stage. Open to any other reasonable suggestions.

**Comment by dashohoxha** [comment]
> Unfortunately, don't see an easy way out of this. Switching modes is too expensive too support at this stage. Open to any other reasonable suggestions.

I wonder what doc engine are they using in this tutorial, and how they make it possible to display command snippets with tabs ("Linux/Mac" and "Windows"):
https://dagshub.com/docs/pipeline/#featurization-or-pre-processing

It even seems like it is possible to convert automatically a Linux example to a Windows example.

**Comment by jorgeorpinel** [comment]
@LucasErlacher did you notice our doc on Windows caveats? We recommend POSIX-like terminals in there: https://dvc.org/doc/user-guide/running-dvc-on-windows

Perhaps we should link to this doc more so people are able to find our recommendations easily?

**Comment by shcheklein** [comment]
@jorgeorpinel agreed! the first link I would into install/windows.

**Comment by shcheklein** [comment]
@dashohoxha they are using MkDocs . I doubt that it can automatically translate windows <-> linux. Would be great if you can take a look and see what takes for an editor to supports this, how does it look in their markdown (or what do they use as a format?)

**Comment by jorgeorpinel** [comment]
Added to /install/windows in https://github.com/iterative/dvc.org/pull/725/commits/c0a9e631be3a462794f2187513cfda4974725c13. Not sure there are other appropriate places for this note, actually. But will review and add to that PR if so.

**Comment by jorgeorpinel** [comment]
Sorry, I meant in https://github.com/iterative/dvc.org/pull/725/commits/8afb0fcc009205ab60d8d5c6e132daffbcf743b1. And "that PR" is #725.

**Comment by dashohoxha** [comment]
> how does it look in their markdown (or what do they use as a format?)

Unfortunately I could not find the code of their website/docs. DAGsHub does not seem to be open source (although they offer free service for open source projects).

**Comment by dashohoxha** [comment]
However this discussion has some info about it: https://stackoverflow.com/questions/37606292/how-to-create-tabbed-code-blocks-in-mkdocs-or-sphinx

**Comment by shcheklein** [comment]
@dashohoxha some suggestions look reasonable. We can't probably use direct MkDocs analog - consequent blocks with different language specifications, since we have a single language usually - `dvc` or `usage`, but we can come up with something similar or use something similar to this https://github.com/apache/spark/blob/master/docs/quick-start.md.  I wonder how many code snippets are affected by this? 

let's create a ticker for the engine to add support for this.

**Comment by dashohoxha** [comment]
What if we try a syntax like this:

`````
````dvc
```Linux/Mac
$ cat .gitignore
```
```Windows
$ type .gitignore
```
````
`````

There are 4 backticks for the enclosing `dvc` block. It is a valid markdown syntax and normally it would render like this:

````dvc
```Linux/Mac
$ cat .gitignore
```
```Windows
$ type .gitignore
```
````

The engine should render it with tabs, but even with normal markdown rendering it appears somewhat acceptable.

**Comment by shcheklein** [comment]
@dashohoxha it might be a good option. Please, create a separate ticket for the engine label to add support for tabs. This one will depend on the new one.

**Comment by jorgeorpinel** [comment]
Per this [conversation](https://discordapp.com/channels/485586884165107732/485596304961962003/648394459242954763) I just noticed is that the recommendations in https://dvc.org/doc/user-guide/running-dvc-on-windows may not really be super helpful:

- We should check what POSX features other than `--` and forward slash `/` Git Bash and Anaconda Prompt actually support.
- People may not want to use WSL because apparently it can't access GPUs for training.

Should we remove/de-emphasize/re-think these Windows terminal tips?

**Comment by shcheklein** [comment]
@jorgeorpinel good catch!

**Comment by shcheklein** [comment]
@jorgeorpinel git bash is pretty bad by itself ... let's do some research and recommend one best configuration.

**Comment by shcheklein** [comment]
@jorgeorpinel this is the good recommendation I would test and if it supports all the features we need would recommend it - https://cmder.net/ + git bash + conda

**Comment by jorgeorpinel** [comment]
> recommend it - https://cmder.net/ + git bash + conda

Added in 5c078217 (as part of #915).

By "+ git bash + conda" you mean to not remove those suggestions, but to recommend full Cmder over those alternatives, right? (Feel fee to review in the PR, marked to close this issue.)
