### ISSUE TITLE
user-guide: duplicate dev version docs (with different methods)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#700]
Why is https://dvc.org/doc/user-guide/development there? 😋 

It duplicates https://dvc.org/doc/user-guide/contributing#development-environment, or vice versa.

Which one to keep? They each use a different method. I vote for the latter (scrap GitPython method).

cc @shcheklein and @efiop who seem to have created and edited this page some time ago. Thanks

**Comment by shcheklein** [comment]
so, fist of all - it's confusing, I agree :)

the first dev version targets _users_ who want to install and _use_ the most recent version before the official release

the second one targets _developers_, _contributors_ of the DVC who want to _create a PR_, etc.

So, I would say the first one can be part of the new Install section with a better explanation why it's useful.

**Comment by dashohoxha** [comment]
>  I would say the first one can be part of the new Install section with a better explanation why it's useful.

What if we keep it as it is and just link to it from the install page.
It can be a sentence like this at the end of the install page: "You may also [install it from code](...)."
The link goes to the development section (which I think needs to be reorganized too).

**Comment by dashohoxha** [comment]
> The link goes to the development section (which I think needs to be reorganized too).

For the time being I reintroduced a page for installation from the most recent version: https://dvc-org-pr-695.herokuapp.com/doc/user-guide/install/extra/code
If needed, we can consolidate this page later with the other development pages and change the link.

**Comment by jorgeorpinel** [comment]
So. Ivan is saying user-guide/development is for alpha users, basically. while user-guide/contributing#development-environment is for contributors/developers.

> What if we keep it as it is and just link to it from the install page.

I think the intention is to remove this confusing nav entry (and it's link in the user-guide/index). Ivan's suggestion to embed somewhere in the new user guide is probably the best. Perhaps in the current **Install from code** section of that PR?

Oh, wait. Is that what you just did already in that PR?

**Comment by jorgeorpinel** [comment]
Oh, wait. Is that what you just did already in that PR? But let's remove this doc also then (and links to it)?

**Comment by jorgeorpinel** [comment]
This issue is duplicated in #701
