### ISSUE TITLE
lint: disallow tabs (.md files)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#705]
> Problem discovered in https://github.com/iterative/dvc.org/pull/679#pullrequestreview-303039108

- ~~Can be done with ESlint, apparently: https://eslint.org/docs/rules/no-tabs~~

- [ ] Add the rule in the docs contrib. guide.

**Comment by jorgeorpinel** [comment]
> Can be done with ESlint, apparently...

Actually never mind. That's just for .js files.

Prettier already switches indentation tabs for spaces in .md docs, but if there's a tab mid-line (e.g. in a console command sample fenced code block) they're ignored. Not sure Prettier can fix this...

**Comment by jorgeorpinel** [comment]
p.s. I added

```json
  "rules": {
    "no-tabs": "error"
  }
```

to .eslintrc.json and ran `yarn eslint src`, and it reported a bunch of tabs in .js files... Will open issue to address this.

**Comment by shcheklein** [comment]
@jorgeorpinel I think no tool checks code blocks. Code blocks by definition are pre-formatted. The only way you is to write our own custom plugin that "understands" certain blocks (`dvc` in our case) and format it as well.

**Comment by jorgeorpinel** [comment]
Yeah I didn't think it through originally. We haven't seen this problem much, I don't think, so let's close for now.

**Comment by jorgeorpinel** [comment]
We do have inconsistent use of spaces vs. tabs from sample command outputs... Probably from old DVC version copy/paste and/or people actively substituting tabs for spaces in them before... Not really impactful visually though and we'll have to _update sample dvc command outputs_ #614 at some point anyway though, so not opening an issue about it.
