### ISSUE TITLE
src: remove tabs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#706]
> Detected in https://github.com/iterative/dvc.org/issues/705#issuecomment-543424772

There's 58 tab characters in .js files inside the `src` directory. I believe we don't mean this. Let's replace them with spaces?

BTW we could include

```json
  "rules": {
    "no-tabs": "error"
  }
```

in .eslintrc.json to automatically enforce this at `git commit` and PR CI checks.

> We should also check that this rule is mentioned in our docs contrib. guide.

**Comment by GledsonAfonso** [comment]
Can I try this?

**Comment by shcheklein** [comment]
@GledsonAfonso sure! would be great if you can take it.

**Comment by GledsonAfonso** [comment]
Thanks! I'll try it then.
