### ISSUE TITLE
docs: update/remove progress bar samples

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#707]
> To match this old core repo PR: iterative/dvc/pull/2333.

We still have lots of fenced code samples of console sessions with the old progress bar such as:

```console
$ dvc fetch --with-deps train.dvc
...
(1/4): [##############################] 100% model.pkl
(2/4): [######                        ] 21% data/data.xml
...
```

in https://dvc.org/doc/command-reference/fetch.

The new progress bar (`tdqm`) looks different, and it normally disappears after it's finished. ~~So perhaps we should~~ So let's just remove all these lines from the .md files ~~?~~ ! (Find `[######` in all files.)

**Comment by castonhilcher** [comment]
I'd like to take this if possible, are you wanting all the progress bar removed, including the file and percent, or just the `[######]`

**Comment by jorgeorpinel** [comment]
Thank you @castonhilcher!
