### ISSUE TITLE
documentation of the code

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#718]
Have you ever thought about documenting the code? For Python projects it is usually done with Sphinx:
- https://docs.python-guide.org/writing/documentation/
- https://realpython.com/documenting-python-code/#documentation-tools-and-resources

I have never used Sphinx before, but I can have a look at it, if this sounds interesting.

**Comment by shcheklein** [comment]
@dashohoxha the only place where is can be helpful is `dvc.api`, but even in that case I can hard to integrate it with the existing engine and most likely it won't be useful enough. I would say we should do regular md files and then propagate some bits back to code.

**Comment by dashohoxha** [comment]
> hard to integrate it with the existing engine

Maybe it is not so hard. There are platforms that host for free code docs, like this one: https://readthedocs.org/. Then we can just link from dvc.org to the code docs.

> we should do regular md files and then propagate some bits back to code

This is not the most efficient way because it is guaranteed that it will get outdated soon and there will be discrepancies. In this case we should update the docs, and then go back and fix the comments on the code?

I am reopening the issue because I did not find your reasons for closing it convincing.
Please close it again if you are convinced that this is not a relevant issue.

**Comment by shcheklein** [comment]
> There are platforms that host for free code docs, like this one: https://readthedocs.org/. Then we can just link from dvc.org to the code docs.

I don't like this idea. We need a very very strong reason to use two different platforms. It can be really confusing. Also, I'm not sure how will it solve the integration problem.

> This is not the most efficient way because it is guaranteed that it will get outdated soon and there will be discrepancies. In this case we should update the docs, and then go back and fix the comments on the code?

Public APIs (and this the only place I see the value for this for now - `dvc.api` docs) should stay stable more or less. Also, It's a minor thing to fix md files when doing some changes to DVC code, unless it involves some structural changes, rewriting examples, etc. But again, the challenge usually is not fixing the discrepancy - it's an easy part and we need a very strong reason to introduce a second platform and/or a special mechanism to deal with it. The content itself is way more challenging here.

> Please close it again if you are convinced that this is not a relevant issue.

So may be I'm missing the whole point of the ticket. What do you mean by `documenting the code`? Who would be the target audience for this docs?

**Comment by dashohoxha** [comment]
> I'm not sure how will it solve the integration problem.

There will be simply a link from the DVC website to an external site (like blog or chat), no integration.

> What do you mean by `documenting the code`?

I mean the whole code, not just the API.

> Who would be the target audience for this docs?

Maybe the developers themselves, or potential contributors, or just curious people that want to look at the implementation details.
But I realize that this kind of people can also look at the code itself, so the documentation of the code would not be much useful.
