### ISSUE TITLE
term: don't use "take X under control" phrase

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#719]
Starting with https://dvc.org/doc/command-reference/add, per https://github.com/iterative/dvc/pull/2546#discussion_r337122908 (look at resolution there for final wording).

And look for any other instances.

**Comment by shcheklein** [comment]
@jorgeorpinel does it sound that terrible? :)

**Comment by jorgeorpinel** [comment]
I didn't think so at first also but looked it up and thought about it, and yes, I think it sounds incorrect.

**Comment by shcheklein** [comment]
@jorgeorpinel could you elaborate please?

**Comment by jorgeorpinel** [comment]
1. "To take" already implies "in one's control".
  ![image](https://user-images.githubusercontent.com/1477535/67229531-1d959e00-f401-11e9-8acf-7fd8586d68c5.png)

2. "under control" is an idiomatic phrase that doesn't mean what we are trying to convery
  
![image](https://user-images.githubusercontent.com/1477535/67229620-4e75d300-f401-11e9-9f98-3612b4d08e97.png)

and we are mixing these 2 confusions together in a single phrase. 😋

**Comment by shcheklein** [comment]
@jorgeorpinel good points that hard for me to "feel". Waiting for good suggestions on how do we replace this :)

**Comment by jorgeorpinel** [comment]
Yeah TBH it wasn't intuitive at first to me either.

I think just use the term "track" as in "tracked by DVC" is the easiest fix to this. See for example https://github.com/iterative/dvc/pull/2546#discussion_r337128743.
