### ISSUE TITLE
ui: forward slash / focus the search bar

### ISSUE THREAD

**Issue by ghost** [iterative/dvc.org#722]
It is sort of common to focus the search bar when hitting forward slash (`/`), making it easier to navigate a webpage in a keyboard-only way.

Not sure how to implement this but a quick search threw this one: https://github.com/greena13/react-hotkeys

**Comment by shcheklein** [comment]
@mroutis could you give an example? webpage that works like this?

**Comment by mroutis** [comment]
GitHub, dev.to, duckduckgo

**Comment by shcheklein** [comment]
@mroutis awesome! thanks.
