### ISSUE TITLE
engine: open external domain links in a new tab

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#729]
Use a special symbol :after: the link that go to an external resource.

Also, I think, we should use a new tab to open them.

**Comment by jorgeorpinel** [comment]
Why not just use HTML? `<a href=... target="_blank">` ?

**Comment by shcheklein** [comment]
@jorgeorpinel yep, that can be exactly the solution we are looking for 👍 . The only thing left is to integrate it into engine - generate different link with or w/o target blank.

**Comment by jorgeorpinel** [comment]
I mean we can just enter HTML into the .md files. Or do you want to extend the MD language like `[external](link)_blank` ?

Another option would be to open links that go outside the website domain (dvc.org) in a new tab by default and let the

**Comment by jorgeorpinel** [comment]
and let the user Cmd+click the other ones

**Comment by shcheklein** [comment]
> Another option would be to open links that go outside the website domain (dvc.org) in a new tab by default

Yep. And I think the engine can detect those and put _blank automatically.
