### ISSUE TITLE
add `gc --all-commits` to docs

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#730]
Per https://github.com/iterative/dvc/pull/2643

**Comment by Suor** [comment]
This was never meant to be documented nor used. The goal of `--all-commits` is a ready to use implementation, we decided to only make it public with a proper UI, which is still undecided.

So this one should be closed.

**Comment by shcheklein** [comment]
@efiop @Suor 👍 , you should hide it from the command line then.
