### ISSUE TITLE
docs: support items without nav sidebar entry

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#731]
In some cases it might be useful to hide (not-show) a page on the left-side menu.
For example in the "Installation" page, the pages about "completion" and "plugins" are referenced from the index page of installation, but I wish they were not shown on the sidebar menu.

Currently this is not possible (unless I have missed something).
This could be specified for example with a field like `"label": false,` or `"label": null,` or `"label": "",`

**Comment by jorgeorpinel** [comment]
Seems to me like a nice-to-have feature: Having the files there but with no entry in sidebar.json

However I don't agree that neither `/doc/user-guide/install/completion` nor `...plugins` should be hidden from the sidebar. They help users discover those topics by navigating the side bar. In fact can't find any element in the navigation at the moment that shouldn't be listed.

**Comment by jorgeorpinel** [comment]
p.s. The problem with those 2 entries is that they are repeated as stand-alone User Guides since #695 was merged.

**Comment by jorgeorpinel** [comment]
p.s. The problem with those 2 entries is that they are repeated as stand-alone User Guides since #695 was merged. This is reported in #701.

**Comment by shcheklein** [comment]
Not sure I see any valuable use case for this for now. Closing this. Will revisit if have a real use case for this.

**Comment by jorgeorpinel** [comment]
BTW this is now possible on Gatsby I think. Are there any pages we want to hide from the docs @shcheklein? Maybe the Google API Privacy Policy (per https://github.com/iterative/dvc.org/issues/144#issuecomment-584441916)

**Comment by rogermparent** [comment]
You're correct, this has been possible since the Models PR. All MD source files will become pages, and if they aren't added to the sidebar they won't show up automatically, fulfilling this behavior.
Should the docs implementation change (and it probably will eventually), I'll keep this feature in mind when changing anything as to not break it so you should be safe to use it.
