### ISSUE TITLE
update: how to update specific rev import? Clarify docs.

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#735]
UPDATE: See https://github.com/iterative/dvc.org/issues/735#issuecomment-545320373 and under for concepts that should be better explained in docs.

---

```console
$ dvc version
DVC version: 0.63.4
Python version: 3.7.4
Platform: Darwin-19.0.0-x86_64-i386-64bit
Binary: False
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('apfs', '/dev/disk1s5')
Filesystem type (workspace): ('apfs', '/dev/disk1s5')

$ mkdir test && cd test
$ dvc init --no-scm
...
$ dvc import --rev cats-dogs-v1 \
             git@github.com:iterative/dataset-registry.git \
             use-cases/cats-dogs
Importing 'use-cases/cats-dogs (git@github.com:iterative/dataset-registry.git)' -> 'cats-dogs'
Output 'cats-dogs' didn't change. Skipping saving.                                                                                                           
Saving information to 'cats-dogs.dvc'.
$ ls
total 8
drwxr-xr-x  3 usr  staff    96B Oct 22 14:05 cats-dogs/
-rw-r--r--  1 usr  staff   340B Oct 22 14:05 cats-dogs.dvc
$ tree cats-dogs --filelimit 3      
cats-dogs
└── data
    ├── train
    │   ├── cats [500 entries exceeds filelimit, not opening dir]
    │   └── dogs [500 entries exceeds filelimit, not opening dir]
...
$ dvc update cats-dogs.dvc
Saving information to 'cats-dogs.dvc'.
$ tree cats-dogs --filelimit 3
cats-dogs
└── data
    ├── train
    │   ├── cats [500 entries exceeds filelimit, not opening dir]
    │   └── dogs [500 entries exceeds filelimit, not opening dir]
...
```

Notice how the last command still counts 500 images each in cats-dogs/data/train cats/ and dogs/, however the latest version of `cats-dogs.dvc` in https://github.com/iterative/dataset-registry/tree/master/use-cases should track 1000 files in each.

**Comment by jorgeorpinel** [comment]
Moved to iterative/dvc.org/issues/735

**Comment by shcheklein** [comment]
@jorgeorpinel agreed on updating docs! (as usual, haha :))

I would clarify though that `dvc update` _updates_ the DVC-file and data when branch name is specified as a revision.

It does not update only when you explicitly told it to use an exact commit. It should be the same as regular package managers behave if you specify them a link to an exact commit on Github. Their update logic will keep them as is. And will be updating only if you use a branch name as a rev.

**Comment by jorgeorpinel** [comment]
Agreed. I like the package manager analogy. Maybe we should've called these features `dvc pkg install/update` after all haha. 😋

**Comment by jorgeorpinel** [comment]
Adding details on all this to the docs in https://github.com/iterative/dvc.org/pull/679/commits/131af1ea370592c9237f8e55a2e0202c7fe4246d!

Should we also open a ticket to give special output from the command itself when it detects a fixed `rev` field in the DVC-file, and this rev hasn't changed? (An alert suggesting it may be necessary to re-import instead of updating if the rev is a tag or SHA commit)

**Comment by shcheklein** [comment]
It can be just a status message (not WARNING or something like that - since there is nothing wrong) that this file is up to date since exact commit is specified and there is nothing to update.

**Comment by shcheklein** [comment]
@jorgeorpinel 🙏
