### ISSUE TITLE
scripts: update autocomplete instructions

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#736]
We are now including bash and zsh completion scripts into our deb, rpm and brew packages. So users of those don't need to get the scripts by-hand.

**Comment by dashohoxha** [comment]
@ptisserand I think that you should first understand the different modes of installation, and even try out some of them if possible. You should also familiarize yourself with the installation of tab completion.
Only after that you might be able to modify properly the installation instructions on that page.

But maybe someone else can explain you better, I am not sure.

**Comment by shcheklein** [comment]
@ptisserand yes, this is an update to the `completion.md` to mention that in certain cases completion is enabled out of the box. I would just write a simple sentence before each section - Ubuntu/Mac/etc ...

**Comment by jorgeorpinel** [comment]
@ptisserand thanks for your interest! On second thought this was not such a great first issue though.

**Comment by jorgeorpinel** [comment]
I'm addressing this in https://github.com/iterative/dvc.org/pull/725/commits/a0cb947053b8e72d348aa44814688978ea91b6ec.
