### ISSUE TITLE
docs: should not need index files in every parent sidebar element

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#738]
> From https://github.com/iterative/dvc.org/issues/727#issuecomment-545756811 with e.g. /doc/user-guide/contributing
> Also related to #305

Using ` "source": false,` on `sidebar.json` doesn't work unless it is the top level (e.g. `get-started` or `understanding-dvc`). In other levels, this breaks the engine.

Consider also automatically generating a list of H2s in child documents when no `source` field is used for a parent `slug`.

- And finish #727 after this.

**Comment by shcheklein** [comment]
index.js -> index.md? (or actually just index file, since it can have a custom name). Also, I would mention that `source: false` should be just working for 2+ level of the items in sidebar.

**Comment by jorgeorpinel** [comment]
> `source: false` should only be working for 2+ level of the items in sidebar

Why not the top level as it works now, @shcheklein? Maybe I'm not getting this comment.

**Comment by shcheklein** [comment]
oh, it's my "russian" english when I'm typing too quick :) ... what I wanted to say is that `source: false` must work for all levels, including top level.
