### ISSUE TITLE
docs: move /get-started index to root and /install above /get-started

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#747]
(Probably after #738)

I like that **Get Started** is the first section in our docs, but ~~its 2nd page links to **Installation** for the user to go and figure out how to best install the tool. This may kind of break the continuity of get-started from the very beginning.~~ Perhaps if we have **Installation** on top in the left side bar, most users will already have DVC installed by the time they get to the Get Started -> Initialize page.

**Comment by jorgeorpinel** [comment]
From https://github.com/iterative/dvc.org/pull/734#issuecomment-546538772:

> had to revert it back since it affected the way `dvc.org/doc` (main page) looks like. Before it was using Get Started index as a default one and it was crafted to look nice and it makes sense to start with get started :) Install index page is not ready to be a front page for the docs website. Need more work here.

Good point, https://dvc.org/doc/get-started has introductory notes to the entire docs. So maybe these should be moved into a docs/index.md to open as a docs landing page? And then move install above get-started.

**Comment by shcheklein** [comment]
yep, good idea, @jorgeorpinel ! Then we can make Agenda in the Get Started to be an index page of the Get Started itself.

Probably some changes to the engine are required to make it work.

**Comment by dashohoxha** [comment]
> it makes sense to start with get started :)

If the user clicks the "Get Started" button, then it will go to the get-started, no matter whether it is the first item on the menu or the second. However if he clicks the "DOC" link to go to the UG or Command Reference, then he still gets Get Started (expanded), which effectively hides the rest of the docs.
