### ISSUE TITLE
tutorials: install DVC as pip requirement?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#760]
Since we are recommending venv'd `pip` (or `pipx`) as a way to install DVC on Linux at least, and since our `versioning`, `pipelines`, and `deep/preparation` tutorial pages use Python in a `virtualenv`, we could simply add DVC into requirements.txt and remove notes/links about DVC installation (only present in `versioning` and `pipelines`).

We should probably also add a note that git-scm.com is required to follow these tutorials.

**Comment by shcheklein** [comment]
The only concern that users will be unaware about the way DVC is installed. And usually they should prefer installing it globally via package, brew, or conda. We are hiding this information behind some magic. Also, this we way we are hiding already installed DVCs, right?

**Comment by welenofsky** [comment]
Not sure if I was off base on this. I couldn't find an existing requirements.txt in this repo.

**Comment by jorgeorpinel** [comment]
Thank you so much @welenofsky sorry my bad actually, I didn't explain the task well. The requirements.txt files exist inside zip files downloaded from other places, not in this repo. This is probably not that good a first issue as I thought but I'll review your or asap anyway and we'll find a way to incorporate it. Maybe we'll just end up improving the docs for now. I'll get back to you...

**Comment by jorgeorpinel** [comment]
Thank you so much @welenofsky sorry my bad actually, I didn't explain the task well. The requirements.txt files exist inside zip files downloaded from other places, not in this repo. This is probably not that good a first issue as I thought but I'll review your or asap anyway and we'll find a way to incorporate it. Maybe we'll just end up improving the docs for now. I'll get back to you...

**Comment by welenofsky** [comment]
@jorgeorpinel That explains where the file was. Whoops! Okay, I just pushed up the removal of that  requirements.txt file.

**Comment by jorgeorpinel** [comment]
I'm adding notes about Git and DVC installation in #763 (per https://github.com/iterative/dvc.org/issues/214#issuecomment-548183856)

Will leave notes and help incorporate your PR as well, Justin.

**Comment by jorgeorpinel** [comment]
@welenofsky please see this https://github.com/iterative/dvc.org/pull/761#issuecomment-548561984 and lmk if its something you would be able to do, no worries either way.
