### ISSUE TITLE
mention that cache options could be used besides `remote modify` params

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#764]
At least type can be specified and is taken into account for `dvc remote modify` command SSH remotes. More details here: https://github.com/iterative/dvc/issues/2704

UPDATE: See more details in https://github.com/iterative/dvc.org/issues/764#issuecomment-548979449 below.

**Comment by jorgeorpinel** [comment]
iterative/dvc#2704 is a little confusing. Would be great if this issue was self-contained with a summery of what and why to improve the `remote modify` cmd ref.

**Comment by shcheklein** [comment]
@jorgeorpinel we have a list of options that are applicable for different remotes provided via expandable sections [here](https://dvc.org/doc/command-reference/remote/modify#examples) (btw, name should be changes to Available Options).

In case of remote data management, when you that remote as a remote cache, specifically for SSH you can specify some options that are not mentioned in that list:

```
dvc remote add sshcache ssh://user@example.com:/cache
dvc config cache.ssh sshcache
dvc remote modify sshcache type symlinks,reflinks,copy
```

`type` in this case is similar to the regular cache config type we have. Not sure about reflinks though, @mroutis and @efiop could clarify that.

I can imagine that `protected` should make sense in this case as well. Not sure about `slow_link_warning`.

**Comment by mroutis** [comment]
@shcheklein , `reflinks` are supported :)

**Comment by mroutis** [comment]
@shcheklein , `protect` make sense but is not enable, I was talking about it on https://github.com/iterative/dvc/issues/2542 could you take a look?

**Comment by jorgeorpinel** [comment]
Hi. Per [this support case](https://discord.com/channels/485586884165107732/485596304961962003/752478399326453840) we should probably document all the cache link types that are supported per remote location, and explain how caching works for external outputs.

> Also added a checkbox about this in epic #520

**Comment by dberenbaum** [comment]
Since external caching is no longer supported, closing this one
