### ISSUE TITLE
term: when/why did we go from DOCS to DOC?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#767]
And from URL `/docs` to `/doc` (which now requires a redirect BTW) ?

I haven't researched this but "Docs" sounds better to me. "Doc" sounds like going to the doctor. 😆

Will look out there though...

**Comment by jorgeorpinel** [comment]
On the other hand I guess "documentation" doesn't have an 's', so "Docs" would be short for "documents"... which is not the right term.

**Comment by jorgeorpinel** [comment]
- AWS uses "Documentation" as text and `docs` in the URLs (i.e. docs.aws.amazon.com). See https://aws.amazon.com/.
- Same as Java. See https://www.oracle.com/technetwork/java/javase/overview/index.html
- Python uses python.org/doc/ as a landing page, but docs.python.org for its documentation URL. Strangely it also uses both term "Docs" and "Documentation" as link texts in https://www.python.org/ 😆
- Git uses "Documentation" as text, and both `/doc` AND `/docs` for the URLs...

From this basic research I would suggest using the full work "Documentation" in as text and going back to `/docs/...` is the URL but no strong opinion, actually. Thought anyone?

**Comment by shcheklein** [comment]
Don't think it worth changing this tbh :) looks like doc and docs are both fine

**Comment by shcheklein** [comment]
Closing this for now, can return to this later :)
