### ISSUE TITLE
glossary: review "DVC repository" term

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#782]
> Extracted from https://github.com/iterative/dvc.org/pull/679#pullrequestreview-313614107

"DVC repository" was introduced in the glossary during the writing of the data registry use case. It can be confusing since usually DVC projects are also Git repositories. Should we just remove this term and use something like "Git repository containing the DVC project"?

We could also keep it but "be more explicit about the difference". Let' s decide and address.

**Comment by jorgeorpinel** [comment]
> ...be more explicit about the difference

(between "DVC project" and "DVC repository", I assume.)

@shcheklein could you clarify what we mean by this?  Thanks!

**Comment by shcheklein** [comment]
Ah, I see it already has a kind-a back-reference to the `DVC Project` at the very beginning. I think we can close this, @jorgeorpinel . Sorry, about confusion.

**Comment by jorgeorpinel** [comment]
Ok. We can also consider:

> Should we just remove this term and use something like "Git repository containing the DVC project"?

What do you think? That would probably be the least confusing. Closing for now.
