### ISSUE TITLE
lint: switch pretty-quick for lint-staged in pre-commit hook?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#788]
> Extacted from https://github.com/iterative/dvc.org/issues/716#issuecomment-550666828

We're now using `lint-staged` for ESLint in the pre-commit hook (see #776) and it seems it also supports Prettier so it would be cleaner to only use this tool and stop using `pretty-quick`.

Please refer to the `lint-staged` [README](https://github.com/okonet/lint-staged#automatically-fix-code-style-with-prettier-for-javascript--flow-typescript-markdown-or-html) and figure out the necessary changes to package.json by testing locally. (And remove `pretty-quick` dependency, update yarn.lock.)

**Comment by theashraf** [comment]
Can I take this one?

**Comment by jorgeorpinel** [comment]
By all means @theashraf. Thanks!

**Comment by jorgeorpinel** [comment]
Per okonet/lint-staged/pull/745 we are currently unable to implement this, but the corresponding PR can be left open for future review.

**Comment by jorgeorpinel** [comment]
This was already done in #790 but we are missing the `--bail` functionality in `lint-staged`. So if/when it gets implemented (see okonet/lint-staged/pull/745), we can continue that same PR.

**Comment by shcheklein** [comment]
@jorgeorpinel is this one solved with the recent migration (+the lates #776 PR)?

**Comment by jorgeorpinel** [comment]
lint-staged won't be supporting the same behavior as pretty-quick so we can just keep both tools. Closeable!
