### ISSUE TITLE
dissolve the section use-cases of the docs

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#793]
The PR https://github.com/iterative/dvc.org/pull/784 deprecates the pages https://dvc.org/doc/use-cases/sharing-data-and-model-files and https://dvc.org/doc/use-cases/shared-development-server. So, after this PR is merged, these should be removed.

If they are removed, use-cases is left with only two pages:
- https://dvc.org/doc/use-cases/versioning-data-and-model-files
- https://dvc.org/doc/use-cases/data-registry

The first one is too generic to be a use-case. Data Versioning is rather a core feature of DVC, it is it's cornerstone. I cannot imagine a case where DVC is used without data versioning. The content of the page is just a description of this feature followed by an example (and it also recommends to read the Versioning tutorial).
So, I think that this page can be removed.

The second page is about the case when DVC is used only as a dataset catalog, for versioning and publishing data, containing no data processing or stages. This page could be moved to the User Guide, maybe in the section HowTo (like: How to Build and Use a Data Registry).

If use-case pages are moved or deleted, then we should also fix any URLs from the other pages where they might be used. Maybe we need to do any URL redirections too, I am not sure (see also: https://github.com/iterative/dvc.org/issues/757).

**Comment by jorgeorpinel** [comment]
Please refer to https://github.com/iterative/dvc.org/pull/784#issuecomment-553581869, https://github.com/iterative/dvc.org/pull/784#issuecomment-553694886, and https://github.com/iterative/dvc.org/pull/784#issuecomment-554040880.

**Comment by dashohoxha** [comment]
I think that it is better to discuss this issue here, instead of discussing it as comments to a PR.

**Comment by jorgeorpinel** [comment]
Sorry, it's not a separate issue. Please don't reopen this. Thanks

**Comment by jorgeorpinel** [comment]
p.s. we can discuss on Discord, please ping us there if you prefer.

**Comment by jorgeorpinel** [comment]
p.p.s. or email

**Comment by dashohoxha** [comment]
> p.s. we can discuss on Discord, please ping us there if you prefer.

I don't think that Discord is a better place for discussing issues.

You closed the issue without any proper discussion, without any explanations or reasons, without having any consensus on it (at least I was not aware of such a consensus). That's why I reopened it.
And the label "invalid" seems rude to me for an issue or a discussion.
