### ISSUE TITLE
improve dvc import fixed revisions example

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#796]
[This section](https://dvc.org/doc/command-reference/import#example-fixed-revisions-re-importing) is confusing, probably because it misses a step. These are the steps I expect:
- importing a particular version (this one is missing)
- updating
- rebinding a revision

That would read as a story unfolding.

The other thing is that we start from some yaml, not from a command, which is also confusing. Should we include those yamls at all? Or include but hide in a bubble.

**Comment by shcheklein** [comment]
@Suor could you please share a link? :)

**Comment by Suor** [comment]
@shcheklein linked "this section" in the original message.

**Comment by jorgeorpinel** [comment]
> importing a particular version (this one is missing)... we start from some yaml...

As you noticed, the example starts by providing a sample DVC-file fragment of a specific `rev` import. We don't always have end-to-end reproducible commands in our examples. (They're not tutorials.) I'm not sure whether its better to keep them as short as possible, or as complete as possible. This is an interesting question though, and whatever guidelines we decide will involve reviewing lots of command examples for consistency.

> updating

The `dvc update` examples are in https://dvc.org/doc/command-reference/update

**Comment by Suor** [comment]
> As you noticed, the example starts by providing a sample DVC-file fragment of a specific rev import, which implies a particular version has been already imported.

This is a part of the problem, using `rev` is supposedly common case, but we don't show/example it. 

> We don't always have end-to-end reproducible commands in our examples. 

Showing the result and not showing a command doesn't make sense to me. This makes it hard to read.

**Comment by jorgeorpinel** [comment]
Good points. I'll add an explicit example of `dvc import --rev ...`. It's a small addition anyway and it will improve readability like you suggest.

Regarding update examples, those require import first, but import doesn't require update. The example in question simply has not much to do with updating, so why would we add an update command example here? We simply mention that "for static refs such as tags (unless manually updated), or for SHA commits, `dvc update` will not have any effect on the import."

**Comment by Suor** [comment]
The explanation for reimport requires update. Now it looks like you are explaining how to solve a problem, which doesn't exists and so you are forced to mention update anyway, only you do it later breaking the linearity of the story.

I think some duplication in related help pages is ok as long as this pages are not meant to be read consequentially, like Get Started. People get there randomly and need a comprehensible story anyway.

**Comment by jorgeorpinel** [comment]
Of course repetition and cross-usage of commands in their examples is OK, we do this a lot already. I'm not opposed to using update for that reason, there's just nothing to update in this example, and we wouldn't want to create a special scenario in the import cmd ref just so we can have an update example – This is what I meant when I mentioned that update examples are in the update cmd ref.

Can you give a more specific suggestion on what update example you would add to this doc?

Also, I don't think examples have to be linear among them, if that's what you mean. Again, command refs are not tutorials or get started chapters. Each example should be "linear" internally though – in the sense that it should be logical and easy to understand – that I agree with.

**Comment by jorgeorpinel** [comment]
Please check the PR @Suor. I added the `--rev` example and also improved the references between this example and `dvc update`, hopefully you find it more cohesive now.

**Comment by jorgeorpinel** [comment]
p.s. you can see the actual PR version rendered in https://dvc-org-pr-800.herokuapp.com/ 🙂

**Comment by Suor** [comment]
> Can you give a more specific suggestion on what update example you would add to this doc?

Just a couple of lines: If the branch or tag "..." has moved you can update an artifact by:
```dvc update stage.dvc```

> Also, I don't think examples have to be linear among them,

Yeah, but each example itself should be, or at least it shouldn't have any gaps what make it harder to comprehend.

**Comment by jorgeorpinel** [comment]
> If the branch or tag "..." has moved you can update an artifact..

The problem is that this example now starts with a `dvc import` example that uses an actual tag.

See https://dvc-org-pr-800.herokuapp.com/doc/command-reference/import#example-fixed-revisions-re-importing

We'd need to make the example more abstract (not reproducible), so the `--rev` can be ambiguous (branch or tag). Not sure this is better.

**Comment by Suor** [comment]
We can leave it with tag and just say:

In the case it moves/reassigned you may use `dvc update` to update both the stage and its artifact. This is probably more useful when you refer a branch not a tag.

In case of a tag you might want to switch it ...

---

I don't want to make it more abstract either.

**Comment by jorgeorpinel** [comment]
OK. I've updated the wording to be more positive, like your suggestion. Please review the PR again. Let's move this discussion to the PR. Thanks
