### ISSUE TITLE
remote: ssh: add a note about sftp root

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#802]
We've seen a few users (https://github.com/iterative/dvc/issues/2755#issuecomment-555385560, https://github.com/iterative/dvc/issues/2535) getting confused by their sftp server being configured with a root directory that differs from a physical root. We will try to find a programmatic way to detect that https://github.com/iterative/dvc/issues/2812 , but we should document it none the less.

**Comment by shcheklein** [comment]
@efiop could write a summary here and suggest a place to put it? since you have some fresh context in this.

**Comment by efiop** [comment]
@shcheklein https://github.com/iterative/dvc.org/pull/803
