### ISSUE TITLE
doc sidebar menu on mobile, don't close it on navigate

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#808]
~On main page there is no top menu, so no way to go into docs unless you type it into address field~

Additionally, to switch to a submenu of other than currently open menu you need to open menu twice:
- open menu
- hit top level item
- it closes
- open menu
- hit next level item

**Comment by shcheklein** [comment]
@Suor  The is a "burger" top menu already that has docs in it or am I missing the point of the issue?

**Comment by Suor** [comment]
@shcheklein the burger top menu shows the bottom plate.

**Comment by shcheklein** [comment]
@Suor but it has Docs in it, right? To be precise - it has everything we would need to show?

**Comment by Suor** [comment]
@shcheklein No it has nothing we need to show, it is the bottom plate.
![dvc-org-bottom-burger](https://user-images.githubusercontent.com/284103/69262721-3e9a0c00-0bc4-11ea-875e-319f16b37bb1.png)

**Comment by shcheklein** [comment]
How about the Documenation link right in the center?

**Comment by Suor** [comment]
:) I looked at it several times and didn't see it until you mentioned. Maybe my internal adblock is just too strong. Or maybe it's a broken expectation - I expect grey text on white saying "docs", I expected menu not a plate.

**Comment by jorgeorpinel** [comment]
This seems like a UI/UX design more than anything else. I personally have nothing against showing the footer in the burger menu but I would then hide the footer from mobile view when you scroll down. Who knows. Need a designer.

**Comment by shcheklein** [comment]
Kk, we can definitely redesign it a bit. I would inverse colors for example as a first step.

**Comment by jorgeorpinel** [comment]
I left your comment an inverted thumbs up, Ivan.

**Comment by shcheklein** [comment]
Repurposed this to focus on docs menu issues only. Burger top menu has been redesigned.
