### ISSUE TITLE
cmd ref: link from remote add to remote modify

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#809]
[This section](https://dvc.org/doc/command-reference/remote/add#supported-storage-types) in `remote add` docs touches on some `remote modify` functionality, since you need it to set up some of the remotes, but it's incomplete.

I suggest adding something like "See full list of remote options you may modify at `remote modify` page" in the end of the section.

**Comment by shcheklein** [comment]
Looks good - for simple things like this, it would easier to PRs right away? :)

**Comment by jorgeorpinel** [comment]
It seems this is no longer the case at least for S3 and S3 API sections after a recent regular update. But I added the rest of the links in ec92b7a4 now (part of #931, which will close this).
