### ISSUE TITLE
docs: get-started: use proper naming scheme for dvcfiles

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#81]
As discussed with @dmpetrov and @shcheklein , we should explain in the get started that you should name your dvcfile with accordance to what stages they describe are doing. I.e. if you have a "preparation" stage with script "preparation.py", you should name your dvcfile as "preparation.dvc"(unless the project is organised in a "directory per stage" format, where you could use "Dvcfile" as a default dvc file name).

**Comment by shcheklein** [comment]
Added a note here [Connect Code and Data](https://dvc.org/doc/get-started/connect-code-and-data):

```
We don't do it here and in the next chapters to keep commands as simple as possible, but it's recommended to use -f optional argument that dvc add provides to specify a meaningful stage name.
```

Should be enough for now, considering that example has been redone using `-f` everywhere and [this issue](https://github.com/iterative/dvc/issues/1092).

**Comment by efiop** [comment]
Great! Thank you!
