### ISSUE TITLE
docs: use-cases: versioning: add a note about replacing/modifying data

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#82]
https://github.com/iterative/dvc/issues/599#issuecomment-418654625

**Comment by shcheklein** [comment]
@drorata could you please clarify why do we need this section https://dvc.org/doc/user-guide/update-tracked-file#updating-generated-files ?

**Comment by drorata** [comment]
I guess what I have in mind is, for example, the case where a model is persisted to the disk and it is desired to track it. In this case, the file is generated during the run of some code and can change while breaking the cache.

**Comment by shcheklein** [comment]
Thanks, for your answer, @drorata.

Let's imagine for example that we have a `train.py` script that takes some `data.tsv` and produces a `model.pkl` file. If you create a stage DVC file like this:

```
dvc run -f train.dvc -d data.tsv -d train.py -o model.pkl python train.py 0.2
```

then if you run `dvc repro train.dvc` it will automatically remove `model.pkl` file before running the command. It should be safe and in this case no need to run `dvc remove` or something else.

Do you mean that even though there is a `train.dvc` file (which essentially takes inputs and outputs under DVC control) you still sometimes want to run `python train.py` manually, or even the same command again:

```
dvc run -f train.dvc -d data.tsv -d train.py -o model.pkl python train.py 0.3
```

(may be providing slightly different parameters)?

Is it the case you were thinking about?

**Comment by drorata** [comment]
This is indeed the case I have in mind. So far I used dvc for tracking data files and artifacts, and skipped the `dvc run` part. Therefore, I found myself running `train.py` manually and potentially corrupting my cache.

**Comment by shcheklein** [comment]
@drorata gotcha! thank you for the clarification. It's a valid use case and worth mentioning. I'm not sure if we need a separate section specifically for that, especially it's confusing a little bit because we also have `dvc repro` and `dvc run` that manage intermediate artifacts. Let't me think and do mention this case in the documentation. I'll let you know to check if it's fine with you. Thanks again!

**Comment by shcheklein** [comment]
@drorata check this document again https://dvc.org/doc/user-guide/update-tracked-file, I put a note about generated files at the very beginning, otherwise it's easy to miss it and it's not very well connected with the content above. Let me know if you have other ideas.

**Comment by drorata** [comment]
See #88
