### ISSUE TITLE
import: allows to download/copy also files that are not output

### ISSUE THREAD

**Issue by Baranowski** [iterative/dvc.org#835]
Documentation update necessary after PR https://github.com/iterative/dvc/pull/2889 for issue https://github.com/iterative/dvc/issues/2862

I will do this

**Comment by shcheklein** [comment]
thanks @Baranowski 🙏

**Comment by Baranowski** [comment]
I'm planning to do this after the corresponding dvc PR is accepted, or at least when it's close to being accepted. Just to avoid back-and-forth if there are changes in the supported functionality.

If you prefer me to write the docs update right away, please let me know.

**Comment by shcheklein** [comment]
@Baranowski sounds like a plan to me! No need to push it ahead of time.
