### ISSUE TITLE
add info about pager on Windows

### ISSUE THREAD

**Issue by xliiv** [iterative/dvc.org#836]
Let's add some info about using pager (`less`) on `Windows`.

This is important because of
https://github.com/iterative/dvc/issues/2807

The solution should go
> Maybe in dvc.org/doc/user-guide/running-dvc-on-windows? Linked to from dvc.org/doc/command-reference/pipeline/show and other appropriate places of course. Please open an issue on dvc.org repo for this!

from https://github.com/iterative/dvc/pull/2815#discussion_r352928507

**Comment by jorgeorpinel** [comment]
@xliiv do you know have a suggestion on what pager we should recommend for Windows? Or does this issue require research? Thanks

**Comment by xliiv** [comment]
@jorgeorpinel i would recommend `less`, it's installed with `git` on which we rely, do we? at least, it is installed on my `windows`.

**Comment by jorgeorpinel** [comment]
DVC doesn't absolutely require Git. You can run `dvc init --no-scm` and skip the versioning features.

If `less` is installed with Git on Windows, it's probably buried somewhere in the Git installation directory and hard to figure out on every system.

What about https://chocolatey.org/packages/Less ?

**Comment by xliiv** [comment]
> What about [chocolatey.org/packages/Less](https://chocolatey.org/packages/Less) if not?

this should work, good idea :+1:
