### ISSUE TITLE
display the interactive tutorials

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#837]
Enhance the website engine to be able to display interactive tutorials from: https://github.com/iterative/katacoda-scenarios

They are basically Markdown files with some minor extensions, so this should not be very difficult in principle.

Those lessons can be played on a Docker container based on ubuntu-18.04 (some instructions for the users would be nice).

**Comment by shcheklein** [comment]
@dashohoxha do you remember what was the idea behind this ticket?

**Comment by dashohoxha** [comment]
I don't. You can close it.
