### ISSUE TITLE
create a user-guide section for "DVC Internals"

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#838]
This section will basically reorganize and contain some of the existing pages/sections:

- DVC Files and Directories

  https://dvc.org/doc/user-guide/dvc-files-and-directories

  https://github.com/iterative/dvc.org/issues/175

- Structure of Cache Directory

  https://dvc.org/doc/user-guide/dvc-files-and-directories#structure-of-cache-directory

- DVC-file Format

  https://dvc.org/doc/user-guide/dvc-file-format

  https://github.com/iterative/dvc.org/issues/68

- How DVC Understands Data Changes

  https://github.com/iterative/dvc.org/issues/576

- Updating DVC-files

- Anonymized Usage Analytics

  https://dvc.org/doc/user-guide/analytics

**Comment by shcheklein** [comment]
Unless I'm missing the meaning of "internals", only `Structure of Cache Directory` can be considered one. May be "How DVC Understands Data Changes".

**Comment by dashohoxha** [comment]
> Unless I'm missing the meaning of "internals"

In my opinion "internals" are all the things that are related to implementation details, and could be changed one day (maybe to improve performance or something else) without changing the functionality of the interface (commands and their options).

So, I think that internal may also be considered the content of DVC-files (`*.dvc`), although we explain it starting from the Get Started. I would also regard the content of the directory `.dvc` as internal.

**Comment by shcheklein** [comment]
> In my opinion "internals" are all the things that are related to implementation details, and could be changed one day (maybe to improve performance or something else) without changing the functionality of the interface (commands and their options).

that's absolutely correct! That's how I understand this as well.

> So, I think that internal may also be considered the content of DVC-files (*.dvc), although we explain it starting from the Get Started.

yep, DVC-file is a public interface. It can be edited manually. We need to support backward compatibility, etc

> I would also regard the content of the directory .dvc as internal.

Just some portion of it (like cache dir). `config` for example is a public interface again.

So, please adjust the description and let's see if we have enough material and what can we do with it.

**Comment by jorgeorpinel** [comment]
Idk. Most of this is covered in https://dvc.org/doc/user-guide/dvc-files-and-directories and https://dvc.org/doc/user-guide/dvc-file-format. Maybe its best to have them separate to keep the guides short-medium sized

- #68 **describe the way DVC checksums are calculated** can be a short note in one or 2 existing docs.
- #576 **elaborate the explanation how dvc understands a file's status** can also be just an improvement to `dvc status` cmd ref.
- "Updating DVC-files" do you mean the same as https://dvc.org/doc/user-guide/updating-tracked-files ?
- Why merge the **Anonymized Usage Analytics** doc?

> In my opinion "internals" are all the things that are related to implementation details...

I think our User Guide super section serves this purpose.

As I see no updates after Ivan's comment above, I vote to close this one for now. Feel free to re-open if there are more details.

**Comment by jorgeorpinel** [comment]
p.s. **user-guide: new "Basic Concepts" doc(s)** #550 may also help cover any gaps that motivated this issue.
