### ISSUE TITLE
cmd ref: document dir support for import-url and get-url

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#841]
After https://github.com/iterative/dvc/pull/2894 we automatically support s3, gs, local, ssh directories in import-url and get-url.

NOTE: just trying to not forget about this, will try to contribute a PR myself if I can.

**Comment by shcheklein** [comment]
@efiop 

thanks!

if you don't have time please put a summary of what files/places should be updated.

**Comment by efiop** [comment]
@shcheklein Right, good point! I'm mostly worried about command reference for get-url and import-url. The latter one mentions dirs, but doesn't specify that only s3, gs, ssh and local dirs are supported. I've updated the examples in the command help https://github.com/iterative/dvc/pull/2907

**Comment by jorgeorpinel** [comment]
Oops @efiop I see you have a few of these 😅 maybe someone else in the core team can help you initiate the draft PRs for some of them? 🙂 Up to you guys of course.

**Comment by jorgeorpinel** [comment]
Actually, this one seems pretty straightforward, we can probably do it from scratch ourselves so I'll unassign you. Please just lmk if there are any got-cha's to keep in mind with this new feature.

**Comment by jorgeorpinel** [comment]
> we automatically support s3, gs, local, ssh directories in import-url and get-url

@efiop so just HDFS and HTTP are **not** supported, right? Because both references already say "Download a file or directory from any supported URL" so the change would be actually to say that only certain remotes are supported for dirs.

**Comment by jorgeorpinel** [comment]
UPDATE: See https://github.com/iterative/dvc.org/pull/931/commits/394e9c80e81a6b18b8823f236c6b8356ada75118. Feel free to review in #931.

**Comment by efiop** [comment]
@jorgeorpinel Correct, only those mentioned currently support directories. The rest - doesn't.
