### ISSUE TITLE
contributing docs are not actionable enough

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#843]
Development environment does not contain exact instruction on how to set it up, e.g.:
```bash
git clone git@github.com:<username>/dvc.org.git
cd dvc.org

# The next two lines are only obvious to someone who used node before
npm install
npm install -g yarn  # Instead of going to yarn website as we say now
yarn dev 
```

Also it is far from obvious that git pre-commit hook is installed inside `npm install`, unless you look at its output closely.

**Comment by shcheklein** [comment]
Have simplified and changed the doc a little bit, @Suor PTAL. I'm not sure why do we need `npm install` before installing yarn?

**Comment by jorgeorpinel** [comment]
Hmmm, now it reads

> Make sure you have the latest version of Node.js and Yarn are installed:

It's the right intention but that sentence is wrong. I'll remove "are" in my regular doc updates PR. Otherwise seems complete now. `git clone` and `cd`, install Node and Yarn, and run `yarn` and `yarn dev`. But I will separate the last 2 commands as they do different things.

**Comment by Suor** [comment]
What's the point making people read ads about yarn instead of simply providing them with a command `npm install -g yarn`?

**Comment by shcheklein** [comment]
@Suor it's already here, right - https://dvc.org/doc/user-guide/contributing/docs :)

**Comment by shcheklein** [comment]
@Suor my question was about `npm install` itself (comes before `npm install -g yarn` in your description)

**Comment by Suor** [comment]
Oh, I see. Much better now)

**Comment by Suor** [comment]
This might be closed unless you guys have something more in mind.

**Comment by Suor** [comment]
@shcheklein I used `npm install` because this is what you usually do with a Node.js project. `yarn` replaces that.

**Comment by shcheklein** [comment]
so, closing this as it fixed and even improved by @jorgeorpinel it the most recent WIP regular updates PR
