### ISSUE TITLE
links to subsections don't work on contributing page

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#849]
Links to subsections here https://dvc.org/doc/user-guide/contributing give 404

**Comment by shcheklein** [comment]
Also, I'm getting this:

<img width="945" alt="Screen Shot 2019-12-09 at 3 55 36 PM" src="https://user-images.githubusercontent.com/3659196/70483107-5ca8ad00-1a9c-11ea-9ec5-3d325678cbe8.png">

if click back from the 404

**Comment by shcheklein** [comment]
Closed by #853 I'll create a separate issue for the height calculation if needed.
