### ISSUE TITLE
SEO: individualized content previews for DVC pages (and maybe /doc pages)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#857]
Currently preview of contents for all DVC pages has the same info:

![image](https://user-images.githubusercontent.com/1477535/70675736-ded0d700-1c3e-11ea-9c30-11a45df55073.png)

Maybe it could have the actual title of each page at least? Ideally also a short excerpt of the beginning of the page contents.

**Comment by shcheklein** [comment]
👍 Any ideas how should we customize it depending on a link? The most obvious one - title. Not sure about snippet and image.

**Comment by jorgeorpinel** [comment]
Yeah well we have a markdown parses so other than a custom title such as **Data Registry | Use Cases | DVC**, the text preview could be the first paragraph from the md contents (After H1), truncated to some length.

**Comment by shcheklein** [comment]
I wonder if we can use an image to put that custom text + logo. And use generic text - so that users always see what DVC is.

**Comment by jorgeorpinel** [comment]
As for research, these excerpts at least in Slack come from the `<meta name="description"` tag. I guess we could find out what other metadata Google, Bing, etc pay attention to. Maybe `<meta name="keywords"`? I understand that's mostly ignored by search engines now a days (they have algorithms to extract keywords from the actual contents instead).

**Comment by jorgeorpinel** [comment]
> can use an image to put that custom text + logo

This is probably possible on more advanced engines, but image rendered text wouldn't help search result ranking.

**Comment by shcheklein** [comment]
Yeah, probably I don't care that much about SEO per se (they are good at extracting information), more about user experience when you send a link, share a link.

**Comment by jorgeorpinel** [comment]
There's `<meta name="thumbnail"`, or more advanced [PageMaps](https://support.google.com/customsearch/answer/1628213) for G we can try.

**Comment by jorgeorpinel** [comment]
Related: #982

**Comment by MerlynMShelley** [comment]
Hi, 
The ```meta``` tag is the most important factor for search engines to find out the core meaning if the website. For that we have to enable the [open graph protocol](https://ogp.me/) with our customised JavaScript engine I hope. I would like to work on this issue.
Thank you.

**Comment by MerlynMShelley** [comment]
> Currently preview of contents for all DVC pages has the same info:
> 
> ![image](https://user-images.githubusercontent.com/1477535/70675736-ded0d700-1c3e-11ea-9c30-11a45df55073.png)
> 
> Maybe it could have the actual title of each page at least? Ideally also a short excerpt of the beginning of the page contents.

I hope ```<meta property="og:site_name"> ``` is missing in the site. Adding this meta tag would resolve the issue. I will raise a pull request on this.
Thank you.

**Comment by MerlynMShelley** [comment]
> As for research, these excerpts at least in Slack come from the `<meta name="description"` tag. I guess we could find out what other metadata Google, Bing, etc pay attention to. Maybe `<meta name="keywords"`? I understand that's mostly ignored by search engines now a days (they have algorithms to extract keywords from the actual contents instead).

It is, ```<meta property="og:site_name"> ``` is missing in the site. So we would get the individualised content on the preview.

**Comment by MerlynMShelley** [comment]
Hi Team,
I have submitted a pull request to this issue. Kindly check. Thank you.

**Comment by MerlynMShelley** [comment]
>  Any ideas how should we customize it depending on a link? The most obvious one - title. Not sure about snippet and image.

I have made the pull request that could fix this issue. Please check here,
SEO: individualized content previews for DVC pages #1379
Thank you.

**Comment by MerlynMShelley** [comment]
> I wonder if we can use an image to put that custom text + logo. And use generic text - so that users always see what DVC is.

Yes, I understand this.

**Comment by jorgeorpinel** [comment]
> The meta tag is the most important factor for search engines to find out the core meaning if the website.

As noted in https://github.com/iterative/dvc.org/pull/1379#issuecomment-636387293 and https://github.com/iterative/dvc.org/pull/1379#issuecomment-636542906 that seems to relate more to #1119. Let's move the conversation there?

> I have submitted a pull request to this issue. Kindly check.
> I have made the pull request that could fix this issue. Please check here,

Yeah, don't worry, we get the notifications and emails from GH. No need for 2 comments about this 😋 but thanks a lot for the contribution

**Comment by MerlynMShelley** [comment]
> Currently preview of contents for all DVC pages has the same info:
> 
> ![image](https://user-images.githubusercontent.com/1477535/70675736-ded0d700-1c3e-11ea-9c30-11a45df55073.png)
> 
> Maybe it could have the actual title of each page at least? Ideally also a short excerpt of the beginning of the page contents.

![Screenshot_20200607_161407](https://user-images.githubusercontent.com/46276713/83966777-f6310a00-a8d9-11ea-8782-33559f11e040.jpg)
When I share I blog link in slack, it's displaying the page title and the image in a smaller size. If we further want to increase the size of the image, we have to work with the Twitter summary of cards with larger dimensions of the picture. So please help me in knowing the absolute requirement of this issue @jorgeorpinel also I have raised a pull request before on this issue with some additional twitter cards on #1379. Kindly help me in this regard to understand the SEO requirement. Thank you

**Comment by MerlynMShelley** [comment]
![Screenshot_20200607_201626](https://user-images.githubusercontent.com/46276713/83972173-48832280-a8fc-11ea-9b5e-3e1e042b8d36.jpg)
@jorgeorpinel @shcheklein 
I can't add image at #1379 so I am referencing here.

**Comment by jorgeorpinel** [comment]
Hey @MerlynMShelley thanks. TBH pasting these long vertical emails is not very easy to read so I hid you comment. Can't you just copy/paste the key text from there or paste a link to the reference? I also don't really understand what it is about or why you cant comment in #1379, which BTW is now closed. Don't you have another PR open for this?

> Sorry, it's been a few really busy weeks and I'm not keeping close track of things, will need your help to make sure everything you comment is easy to read and in the right context.

**Comment by jorgeorpinel** [comment]
> If we further want to increase the size of the image, we have to work with the Twitter summary of cards with larger dimensions of the picture

Why is this a Twitter-specific issue? Thanks

> help me in knowing the absolute requirement of this issue

The custom image idea comes from https://github.com/iterative/dvc.org/issues/857#issuecomment-565226918 but the goal is to keep both the basic description of DVC and also the excerpt from each page in these previews somehow. It's not a perfectly defined requirement, it needs a creative solution, probably. Any suggestions?

It's a good point that the blog previews already have custom excerpts, it seems cc @shcheklein @rogermparent how can we replicate that everywhere?

**Comment by jorgeorpinel** [comment]
> why you cant comment in #1379, which BTW is now closed. Don't you have another PR open for this?
Sorry, it's been a few really busy weeks

I see that was your only PR @MerlynMShelley, but it got complicated and was closed. Are you planning to try again with a smaller PR so it's easy to review and follow up on? Or do you prefer to work on something else? I've seen you've commented in https://github.com/iterative/dvc.org/issues/1119#issuecomment-640201071, for example.

Again, this week will probably be a little difficult to work with you very closely so if you have a small, specific, complete contribution you'd like to make, please send a PR 🙂 otherwise let's touch base in a few days.

**Comment by jorgeorpinel** [comment]
> providing that component the data we want to display in the other templates should do the trick

Sounds worth a shot 🙂

**Comment by jorgeorpinel** [comment]
Closing in favor of #1785
