### ISSUE TITLE
document `hardlink_lock` config option

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#858]

**Comment by jorgeorpinel** [comment]
Description or link to context please 🙂

**Comment by efiop** [comment]
@jorgeorpinel https://github.com/iterative/dvc.org/pull/867 here is the patch.

**Comment by jorgeorpinel** [comment]
Ah yes, sorry, I keep not noticing those automatic links. My brain is trained to ignore them :b

![image](https://user-images.githubusercontent.com/1477535/70978967-01fbec00-206e-11ea-9d39-6a9b51036a8c.png)

**Comment by efiop** [comment]
@jorgeorpinel THere is also "May be fixed by #867" in the header.
