### ISSUE TITLE
improve `formatting` aspect of contribution process

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#861]
CAUTION!!! RANT! Say you edit a doc right on the github (this is how we recommend it to users), you create a PR with it and you see that the tests failed. You figure out that this is a formatting issue, so you clone your branch in order to fix it. But you have no idea how to fix it, so you go to https://dvc.org/doc/user-guide/contributing/docs , follow through the hell of installing yarn (not that trivial, ruby usually has a lot of issues on my machine) in hope that it will fix it through pre-commit hooks, but it doesn't fix it. So you again lurk through the docs to discover this cryptic command somewhere in the bulk of text(not even in its own code block!):
```
yarn prettier --write '{static,src}/**/*.{js,jsx,md}'
```
Ok, I run it, but it now fixes not only my code, but also some bits and pieces that we've merged unfixed previously!

I'm sorry guys, but this is not friendly, even for me. We should try to simplify this. What I suggest:

1) Bring back `yarn format` command to be able to just format everything in 1 shot.
2) Make formatting MANDATORY, so that it is always in-check and contributors are not confused by the `prettier` fixing someone else's code.
3) Use restyled #804 (if possible) to automatically reformat, so that you could simply merge its formatted PR without having to ask the user to reformat and without breaking the formatting on the `master` by merging his incorrectly formatted PR.

Please feel free to correct me if I'm missing anything, I'm not actively involved in the internals. 🙂

**Comment by jorgeorpinel** [comment]
You're right but we haven't really seen this problem happen AFAIK. Anyway, as you mentioned, #804 should fix this, so can we close this issue in favor of that one? Perhaps extracting any valuable details from here into there.

> Make formatting MANDATORY

It is mandatory, what do you mean?

**Comment by efiop** [comment]
@jorgeorpinel If it is already mandatory (it checks the whole project, so CI will fail on master if formatting is broke) then ok. CLosing.

**Comment by jorgeorpinel** [comment]
We did have an error in our CI checks until a few days ago so it wasn't checking everything but now it definitely is 🙂
