### ISSUE TITLE
cases: DVC in Production

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#862]
> Inspired by https://github.com/iterative/dvc/issues/2212 and https://www.reddit.com//r/MachineLearning/comments/ea0825/d_experiment_management_in_kubernetes/

We don't have any explanation on how to work in "production":
1. How to bring an artifact when CI/CD is done? GitLab build materials? Temporary bucket/storage and custom script?
2. Best practices of sharing cache in k8s.

**Comment by jorgeorpinel** [comment]
There's just a few mentions to model deployment in the **Versioning Data and Model Files** and **Data Registries** use cases for now:

![image](https://user-images.githubusercontent.com/1477535/70945585-5f5e5180-200a-11ea-8146-d501368fe70f.png)

But yes definitely an advanced use case about all this would be great!

**Comment by jorgeorpinel** [comment]
Here's another good inspiration for this use case: https://peckofpickledpojos.wordpress.com/2020/08/09/learning-dvc-by-trial-and-error/#comment-5

Bumping priority a little.

**Comment by jorgeorpinel** [comment]
@dmpetrov I read both context links. Here are some answers, please confirm if this makes sense:

> How to bring an artifact when CI/CD is done? GitLab build materials?

The recommended way to sync pipeline status updates back from production to the master DVC repo would be to `git commit` (in a release branch) from prod. It can be part of the GH/GL CI job.

Question: what happens with multiple prod envs, as `git pull/merge --ours` could be needed, which might result in overwriting each other's commits. Does each env get a Git branch?

> Temporary bucket/storage and custom script?

Why not remote storage? That's DVC's feature for syncing caches.

One trick would be to setup the dev env's remote storage = a prod env cache, this way there's no 3rd data store (if no backups are needed and to reduce transfers).

> Best practices of sharing cache in k8s.

Unfortunately I'm not super familiar but can't all the containers be setup to share a common drive? Then just https://dvc.org/doc/use-cases/shared-development-server#configure-the-external-shared-cache

p.s. TBH these specific Q & As would be better for a Best Practice page than for a use case (rel #72). We can have both but we need to be a bit higher-level for the use case (currently discussing in #2490).

**Comment by jorgeorpinel** [comment]
Closing in favor of #2544.
