### ISSUE TITLE
dvc push: Wrong keys 'ask_password'

### ISSUE THREAD

**Issue by xiaolongtang** [iterative/dvc.org#87]
Hi 
I set remote with ssh. I set url and ask_password true. When I dvc push, I will get error. 

The error message:
Error: Initialization error: Config file error: Key 'remote "myremote"' error:
Wrong keys 'ask_password' in {'url': 'ssh://XXX@xxx:/home/XXX/dvc',
 'ask_password': 'true'}

Thank you for helping me out.

**Comment by efiop** [comment]
Hi @xiaolongtang !

What version of dvc(`dvc --version`) are you using?

Thanks,
Ruslan

**Comment by xiaolongtang** [comment]
Hi @efiop 
It is 0.18.15

Thank you.

**Comment by efiop** [comment]
Thanks for clarifying! The version you are using is too old and lacks the `ask_password` config option. Could you please upgrade? I.e. if you've installed dvc with pip, then the command would be `pip install --upgrade dvc`. Btw, there is an issue with the latest released 0.19.2 in that it will ask a few times for a password on `dvc pull` unless you specify `-j 1` option with it. I am releasing 0.19.3 right now with a fix for that. It should be ready in an hour or so, I'll remind you with a message here when it is ready.

Thanks,
Ruslan

**Comment by xiaolongtang** [comment]
Hi @efiop 
It is working after I upgrade the dvc. 

Thank you so much.

**Comment by efiop** [comment]
No worries :) Thank you for the feedback! Btw, 0.19.3 is out. Please upgrade :)
