### ISSUE TITLE
glossary: tooltip position breaks when word is at left edge of p

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#870]
<img width="1231" alt="Screen Shot 2019-12-16 at 4 05 22 PM" src="https://user-images.githubusercontent.com/3659196/70953415-01d40000-201e-11ea-99b5-1bee6989ccc5.png">

**Comment by jorgeorpinel** [comment]
Yeah weird. But they all work fine except the the one in the [**Examples: Get a Git-tracked model file**](https://dvc.org/doc/command-reference/get#example-get-a-dvc-tracked-model-file) section. I don't see anything special about the md code around it... Have  you seen any other broken ones @shcheklein? @algomaster99 are you around to at least diagnose the cause of this by any chance? Thanks

**Comment by jorgeorpinel** [comment]
I found another one in https://dvc.org/doc/command-reference/gc#examples:

![image](https://user-images.githubusercontent.com/1477535/70955059-58dcd380-2024-11ea-923d-125723d982d5.png)

The only commonality I see is that the underlined texts are both near the left edge of `#markdown-root > div.markdown-body`

**Comment by jorgeorpinel** [comment]
Yeah if you change the width of the window to force any underlined text to the very left edge of the paragraph, the tooltip position breaks:

![image](https://user-images.githubusercontent.com/1477535/70955266-14056c80-2025-11ea-92fe-1f92157a28bb.png)
