### ISSUE TITLE
sync: prepare troubleshooting guide for `Too many open files` error

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#871]
Related:
https://github.com/iterative/dvc/pull/2866
https://github.com/iterative/dvc/issues/2473

Need to prepare short information about why `Too many open files` happens and how to solve it, as this information is too long for exception message.

After this issue is solved, need to improve log message to include a link to the explanation

**Comment by jorgeorpinel** [comment]
Where would you put this info? If it will fit in a single paragraph I recommend using existing docs, probably some of the command references. It can be repeated in a few ones wherever it's appropriate (e.g. remote and push perhaps)

**Comment by pared** [comment]
@jorgeorpinel I guess push and pull are the most "threatened" operations, maybe there?

**Comment by jorgeorpinel** [comment]
Sounds good. Maybe also `checkout` since it can include `pull`. Consider adding the note in the `remote` index page too. Thanks

**Comment by pared** [comment]
@jorgeorpinel remote seems to be about remote command, not remote as entity per se, so I am not sure we should put some note there, what do you think?

**Comment by shcheklein** [comment]
@jorgeorpinel @pared I think with these errors that are edge cases in a regular workflow we should docs "event-driven". Event happens -> link -> troubleshoot section that help to understand and overcome. We don't need to put a lot of links and duplicate this around. It is not scalable.

I suggest we actually introduce `error.dvc.org/{code}` shortcut and use then in DVC. They should redirect to specific Troubleshooting sections.

**Comment by jorgeorpinel** [comment]
> Event happens -> link -> troubleshoot section that help to understand and overcome. ...
> I suggest we actually introduce error.dvc.org/{code} shortcut and use then in DVC.

Great idea!

So no links at all in this case even from `pull` or `push` cmd refs?

**Comment by jorgeorpinel** [comment]
> remote seems to be about remote command

@pared actually https://dvc.org/doc/command-reference/remote is an index page to list the sub commands and we also use it to explain what DVC remotes are – which by the way may be a bad thing and we should introduce a user guide about DVC remotes instead... Not sure. But anyway, sounds like we don't want links from anywhere inside the docs.

**Comment by shcheklein** [comment]
Agreed to create an issue in the DVC core project and link it in the message.

**Comment by jorgeorpinel** [comment]
I think this is still open, will be closed by an ongoing PR.
