### ISSUE TITLE
user-guide: explain locking mechanisms that we use

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#876]
https://github.com/iterative/dvc.org/pull/867#discussion_r358671217 E.g. repo lock `.dvc/lock`, rwlock, etc. 

UPDATE: More details in https://github.com/iterative/dvc.org/issues/876#issuecomment-568627696

**Comment by jorgeorpinel** [comment]
Nice. And link from "file locks" in https://github.com/iterative/dvc.org/blob/master/static/docs/command-reference/config.md#core as well as other places where they may be mentioned in docs 🙂

**Comment by jorgeorpinel** [comment]
> From https://github.com/iterative/dvc.org/issues/880#issue-541863812

#868 introduces a note about parallel execution (involving repo locks) which feels like it comes out of the blue, as no basic explanations about locking mechanisms can be found.

To further complicate things, the dvc lock command reference talks about locking but this is a completely different topic. Not sure how to eliminate that ambiguity but at least explaining repo locking in a new doc (linked to existing docs where appropriate) and clearly noting these things are separate in both docs would be great.
