### ISSUE TITLE
locking: explain the different mechanisms, disambiguate

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#880]
> Extracted from https://github.com/iterative/dvc.org/pull/868#pullrequestreview-335680058

I don't think repo locks are explained in the docs much if at all. #868 introduces a note about parallel execution (involving repo locks) which feels like it comes out of the blue, as no basic explanations about locking mechanisms can be found.

To further complicate things, the `dvc lock` command reference talks about locking but this is a completely different topic. Not sure how to eliminate that ambiguity but at least explaining repo locking in a new doc (linked to existing docs where appropriate) and clearly noting these things are separate in both docs would be great.

**Comment by shcheklein** [comment]
looks like a duplicate of the #876

**Comment by jorgeorpinel** [comment]
Right... We just have more details and context here. I'll move it over. Thanks
