### ISSUE TITLE
cmd ref: document target granularity for push/pull/fetch/checkout/status -c et al.

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#886]
Context: iterative/dvc/issues/2458, and PRs iterative/dvc#3002 and iterative/dvc/pull/3309

UPDATE: See also https://github.com/iterative/dvc.org/issues/886#issuecomment-629416738

**Comment by jorgeorpinel** [comment]
A quick draft PR for this would also be great as a couple users have asked about it recently I think but docs are still outdated. I'll get to it eventually if not.

**Comment by efiop** [comment]
@jorgeorpinel Adding to the next sprint, will try to get to it.

**Comment by jorgeorpinel** [comment]
@efiop do you remember if `dvc list` also supports granularity? Yes right? I think also we should include that info, as well as with `import` and `get` 🙂

**Comment by efiop** [comment]
@jorgeorpinel It will support it fully after https://github.com/iterative/dvc/pull/3825 . Sorry for this hanging for so long, been meaning to get to this for a long time. Definitely need to sort this out for 1.0.
