### ISSUE TITLE
app: use Next.js dynamic routing?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#888]
We currently implement our own custom routing mechanism based on pages/doc.js, public/static/docs/sidebar.json, src/utils/sidebar.js, etc. to find and render markdown files.

We could instead try using the built-in [dynamic routing](https://nextjs.org/docs/routing/dynamic-routes) form Next which would mean having a pages/doc/ directory with an `[item].js` file in it. I think we could also use `await import` instead of `await fetch`.

Idea based on https://dev.to/tinacms/creating-a-markdown-blog-with-next-js-52hk#pages-amp-dynamic-routing

UPDATE: Or migrate to Gatsby like https://github.com/iterative/blog. See https://github.com/iterative/dvc.org/issues/888#issuecomment-571165003

**Comment by iAdramelk** [comment]
@jorgeorpinel I tried dynamic routing then we were migrating to the current system, but wasn't able to make them work with the nested directories. E. g. `/docs/page` is ok, but `/docs/page/page` is not redirected to the `/docs/[item].js`. If you will be able to make it work, then yes, it will be better to migrate.

Same thing with the imports, I tried them, but they didn't work with for me with the `static` dir, so I decided to leave them out for now, but if you can make them work (and maybe they will work if we place `md` files not inside of `static`, but inside of some other folder) it will be better this way.

**Comment by jorgeorpinel** [comment]
Interesting, thanks. I'll research this issue.

**Comment by jorgeorpinel** [comment]
> Working on #738 I stumbled upon some more Next.js info. that brings me back to this issue...

> I tried dynamic routing but /docs/page/page is not redirected to the /docs/[item].js

@iAdramelk We have a custom route in our server.js for this. Can't we use the custom server to enforce dynamic routing of a single level `pages/doc/[item].js` file?

_Note that having this [custom server](https://nextjs.org/docs/advanced-features/custom-server) apparently prevents Next from enabling **Automatic Static Optimization**._

> Same thing with the imports, I tried them, but they didn't work with for me with the static dir...

We would probably need to import a node module that loads the static md files somehow. Maybe with `fs.open` instead of `fetch`, but I'm not sure `fs` is always available for pages/doc.js... Would need to try.

Another option is [dynamic importing](https://nextjs.org/docs/advanced-features/dynamic-import) instead of `await import` or `await fetch`.

**Comment by jorgeorpinel** [comment]
Another idea: per [this issue](https://github.com/zeit/next.js/issues/7607) and its release's [blog post](in the blog post) it seems there's no good way to implement deep/nested dynamic routing. BUT `react-router` [supports this](https://reacttraining.com/react-router/web/example/nesting) and there's a [version for Next](https://www.npmjs.com/package/react-router-next) so maybe that way we can implement our own "custom dynamic routes" (without a custom server).

Need to tray all this but the issue doesn't have high priority at least for now.

**Comment by iAdramelk** [comment]
> Note that having this custom server apparently prevents Next from enabling Automatic Static Optimization.

From that I understand, static optimization works for the static pages like index and features (see flash icon in the bottom right corner of the screen the running server in dev mode).

Right now we can't enable static optimization for docs pages because they use `getInitialProps` to download markdown, but in the near future we would be able to do this too: https://github.com/zeit/next.js/issues/9524

We can use `server.js` to replace `post.js` with `[post].js` aa the page target, but from the `next`'s point of view nothing will change in their work.

BTW. I think that it's is easier to migrate to Gatsby that can do anything we want out of the box then using non-stadard `next` builds. Migration itself without rewriting components can be done in a couple of days.

**Comment by jorgeorpinel** [comment]
> static optimization works for the static pages like index and features (see flash icon

Yep, seems you're right. I was thrown off by this note: "A custom server will remove important performance optimizations, like serverless functions and Automatic Static Optimization." (from https://nextjs.org/docs/advanced-features/custom-server) but I guess they mean disabled from the custom routes, so that means only the stuff inside `/doc...`

> now we can't enable static optimization for docs pages because they use getInitialProps to download markdown, but in the near future we would be able to do this too: zeit/next.js#9524

OK that's interesting but wait. I didn't know about Next.js [Static HTML Exports](Static HTML Export)... We could just do that now! Our md files will only change each time we deploy the page, and on each deploy we will run `next build && next export`. The whole thing would be fully SSG, while React will "hydrate" the client-side as well!

Another alternative I found [here](https://nextjs.org/docs/basic-features/data-fetching#static-generation) is https://github.com/zeit/swr (React Hooks library for remote data fetching). Let's you fetch stuff on the client-side only, without `getInitialProps`.

> BTW. I think that it's is easier to migrate to Gatsby that can do anything we want out of the box...

Sure, that sounds like an option too, of course. I would just need to learn that "next" 😋

**Comment by shcheklein** [comment]
Not relevant anymore after the migration.
