### ISSUE TITLE
nav: refactor util/sidebar.js?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#894]
I find it too complicated for the following reasons:

1. It's purpose is dual:
  a) transform sidebar.json into a different format (used at server load time), and
  b) provide helpers to find sidebar items in different situations (mainly for run-time).
  Each of these purposes could have its own separate module, and I have the impression they could be implemented in a more simple, obvious way.
2. It has several recursive functions, which could be rewritten as loops for performance

Furthermore, the very need for this module is questionable, per #888.

Related issues that could be resolved/eliminated by fully addressing this:
 - **nav: unnecessary gaps in sidebar** #724
- **docs: support items without nav sidebar entry** #731
- **docs: nav (left sidebar) isn't visible without js** #856
- **next: use dynamic routing?** #888 (mentioned above)
Among others?

**Comment by jorgeorpinel** [comment]
I'm not usually the one to suggest refactoring and I don't expect to have any priority assigned here soon, but I just wanted to leave my thoughts for the record and a possible future revisit.

**Comment by shcheklein** [comment]
Closing in favor of #1044 ... All mentioned items in the second section of this ticket are closed by the way, most of them are fixed. So this ticket is about complexity of the approach, I think #1044 is more or less the same. @jorgeorpinel feel free to reiterate your comments there.
