### ISSUE TITLE
changelog: remove or update

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#897]
https://dvc.org/doc/changelog has some very old (and few) release notes. The actual change log is in https://github.com/iterative/dvc/releases. Should we try to pull this info into the /doc/changelog dynamic page somehow (e.g as suggested in #515)? Or just remove the section and/or link to the GH repo link just mentioned?

**Comment by shcheklein** [comment]
related and probably can be merged - https://github.com/iterative/dvc.org/issues/515 . I agree that it probably does not make sense to support multiple places. I hope at some point someone will be publishing some weekly updates to out blog/forum and that with GH release notes should be enough. Current scheme is not sustainable clearly.

**Comment by kenahoo** [comment]
Came here to add a "me too" - in the short term, maybe add a link to https://github.com/iterative/dvc/releases on the docs page?  Whenever I'm updating I never seem to be able to find the release notes.

**Comment by jorgeorpinel** [comment]
Yup @iAdramelk @pavelgrinchenko can this perhaps be easily included in the blog merge #1091?

**Comment by jorgeorpinel** [comment]
It's just making a link of the nav entry, removing the changelog from sidebar.json, and its content (md docs).

Then again if should probably be a separate PR...

**Comment by shcheklein** [comment]
Definitely a separate PR, @jorgeorpinel

**Comment by shcheklein** [comment]
Fixed by https://github.com/iterative/dvc.org/pull/1273
