### ISSUE TITLE
user-guide: versioning semantics and compatibility policies

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#906]
In https://github.com/iterative/dvc.org/pull/896#pullrequestreview-339573664 I suggested introducing the following note to https://dvc.org/doc/install

```markdown
⚠️ Please try to use the same/latest DVC version on all the team member
machines. DVC is in active development and compatibility issues may arise
between significantly different versions.
```
> Per https://groups.google.com/a/iterative.ai/forum/#!msg/support/ZBNM2dydyxU

But we then thought it's a) to "scary" and that it probably belongs in a larger topic, that of semantic versioning and compatibility issues among levels of DVC releases (see https://github.com/iterative/dvc.org/pull/896#discussion_r364005745). So I'm creating this ticket to discuss and decide on what to write about this.

May even impact the dev process of the core repo going forward? Cc @iterative/engineering

**Comment by jorgeorpinel** [comment]
From Ivan:

>probably take Ruslan's exact language (from the Google group topic) about backward and forward compatibility
>and also let's not scary users with is in active development phrase:
> 1. First of all, only projects are of not any interest are not being actively developed and any mature project keeps in mind **compatibility policies**.
> 2. Second, our version number (0.80.0 currently) is already enough to scare users :)

**Comment by jorgeorpinel** [comment]
> only projects of not much interest are not being actively developed

@shcheklein I'm not sure about this. A mature project probably has very unfrequent updates (e.g. a security hot-fix every few months), but it doesn't mean that it's not being maintained. It depends what we mean by "active development". Maybe there's a better phrase like "beta stage" or something else.

**Comment by skshetry** [comment]
> Second, our version number (0.80.0 currently) is already enough to scare users :)

With 1.0, users will expect some kind of backward compatibility, especially when we break repo
compatibility (https://github.com/iterative/dvc/issues/3885).
I think, we should at least document this, so that we could redirect users to, politely.

And, regarding the documentation of compatibility policy, we can follow SemVer or a bit modified with:
1. Major version on repo incompatibility
2. Minor version on any features (including `cli`, `Repo` and `dvc.api` backward incompatibilities).
3. Patch version on bug-fixes.

**Comment by casperdcl** [comment]
also related: https://github.com/iterative/dvc/issues/3872

**Comment by jorgeorpinel** [comment]
> With 1.0, users will expect some kind of backward compatibility, especially when we break repo
compatibility (iterative/dvc#3885).
I think, we should at least document this, so that we could redirect users to, politely.

I'm sorry @skshetry I'm not sure what you're referring to. Document what?

Agree abour [SemVer](https://semver.org/)! It's an industry standard anyway 🙂

**Comment by skshetry** [comment]
> I'm sorry @skshetry I'm not sure what you're referring to. Document what?

umm, compatibility policies?

**Comment by jorgeorpinel** [comment]
So are you just saying you agree with this issue? Sorry, please be clear.

Also you were answering a comment by @shcheklein (which I quoted in https://github.com/iterative/dvc.org/issues/906#issuecomment-634606594) so I just mentioned him for awareness.

Thanks
