### ISSUE TITLE
Appending query params shows 404 page

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#909]
### Steps to reproduce
1. Open https://dvc.org/doc. It loads correctly.
2. Open https://dvc.org/doc?query=params. `404` page is returned.

This happens on all documentation links I tried, not just `/doc`.

Note: Some sites like `facebook` add a tracking code as a query param (via `?fbclid=<id>`), so, this makes the documentation links shared on such sites unusable.

**Comment by shcheklein** [comment]
Fixed, thanks @skshetry !
