### ISSUE TITLE
get: it can download from plain (non-DVC) Git repos.

### ISSUE THREAD

**Issue by fabiosantoscode** [iterative/dvc.org#911]
Matches this PR: https://github.com/iterative/dvc/pull/3097

**Comment by jorgeorpinel** [comment]
Thank you @fabiosantoscode! Please request my review here when https://github.com/iterative/dvc/pull/3097#pullrequestreview-341319527 is resolved.

**Comment by jorgeorpinel** [comment]
I meant on the PR 😋
