### ISSUE TITLE
cmd ref: get and import are getting confusing

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#920]
WARNING: **RANT**ish

#912 will soon merge the updates to the behavior of `dvc get` and `dvc import`, which now completely support dealing with regular Git repos (no DVC involved at all).

I forget what was the reason to implement that on the core repo but I'm sure there were good motives, however, it's made them confusing or at least difficult to explain.

We should probably revisit the command references again and explain again:

- Focus mostly on the DVC-related features and
- only note somewhere about regular Git repo support.

This way we'll avoid confusing phrases and paragraphs like `` `url` (location which can be a path) and `path` (also location) (both HTTPS or SSH supported) to DVC project (which can be a DVC repo, which is a Git repo) or Git repo (we mean a plain repo without DVC inside) ...`` – exagerated.

**Comment by shcheklein** [comment]
I don't know how it can be confusing, tbh. It's as simple as - `it can download any file or directory from any Git or DVC repo`. I think we are just overcomplicating and overthinking this. Just think about the essence of what it does first, would people who read this understand this, being precise and consistent - third.

Btw, ironically, it was initiated by the ticket you created (after the discussion in the `dvc list` ticket) :).

**Comment by jorgeorpinel** [comment]
> download any file or directory from any Git or DVC repo... Just think about the essence of what it does first

Exactly. Why are we talking so much about importing random stuff from Git repos? Why would we import small text files, or images, etc? Maybe I just forgot why we even started supporting this.

> ironically, it was initiated by the ticket you created

Darn karma... It made sense at the time! But when you have to explain something and think it through... Sometimes it's a different conclusion. Maybe we should try to write docs BEFORE questionable new features...

Anyway, yes: the current version in Fabian's PR basically just mentions "or Git repo" everywhere after several review rounds to ensure completeness and consistency (between get and import refs).

**Comment by jorgeorpinel** [comment]
OK fine let's close this. If it's confusing I'm sure we'll notice again in the future.
