### ISSUE TITLE
cmd ref: create doc for `metrics diff`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#921]
Per https://github.com/iterative/dvc/pull/3051

**Comment by jorgeorpinel** [comment]
> Per https://github.com/iterative/dvc.org/pull/933#pullrequestreview-357993125

#933  didn't solve this. Now we need to iterate on the metrics diff doc itself.

**Comment by jorgeorpinel** [comment]
Actually, we already have a follow up issue for this. See #959
