### ISSUE TITLE
md: enable custom anchor id/href for troubleshooting guide?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#922]
https://dvc.org/doc/user-guide/troubleshooting will have hardcoded H2 elements so we can choose the `id` to be short enough for error.dvc.org/{title} redirects (turned into URL hashes into this one page).

It would be ideal if we could use markdown instead (`react-markdown` renders them with a nice anchor link), but we don't control the `id` and `href` values  in there, which tend to a little long.

Implement a solution to this in our JS engine? Find a better workaround than hardcoded H2s?

**Comment by jorgeorpinel** [comment]
Would this imply using a special markdown syntax like
```md
## [Too many open files error](#many-files)
```
(and preventing the linking default)? If so, this seems probably too much to me. "Hardcoded" H2 elements is actually technically valid Markdown anyway. We just miss the nice anchor links – which could be hardcoded in as HTML/SVG as well, BTW.

**Comment by shcheklein** [comment]
`[Too many open files error](#many-files)` this one already has certain meaning, so not sure this is the best idea. In general yes, it should something simple and similar to this and implementation to our expandable sections I imagine.

**Comment by jorgeorpinel** [comment]
> `[Too many open files error](#many-files)` this one already has certain meaning

When you put it in a header `##` actually it throws a react render error so I guess it's available.

Another idea, just:

```md
## Probably long title #short-hash
```

**Comment by jorgeorpinel** [comment]
Found a bug on this. See https://github.com/iterative/dvc.org/pull/929#pullrequestreview-345551441

**Comment by shcheklein** [comment]
@jorgeorpinel What browser? I can't reproduce this for some reason on my Mac

**Comment by jorgeorpinel** [comment]
Chrome on Mac but O_o this just went away after a force reload. Cache issue I guess, never mind! 😬
