### ISSUE TITLE
tutorials: replace `dvc pull` example in deep tut

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#946]
The [Pulling data from the cloud](https://dvc.org/doc/tutorials/deep/sharing-data#pulling-data-from-the-cloud) deep tutorial code example doesn't work because https://github.com/dmpetrov/new_tag_classifier had been deleted. It's been restored now but the S3 remote is also gone so `dvc pull` fails.

![image](https://user-images.githubusercontent.com/1477535/73101024-6d7a7a00-3eb4-11ea-86ab-9f932cb2766b.png)

We should probably just use a completely different project as example here (and not directly in Dmitry's account) instead of restoring the bucket, as the example is not really tied to the larger tutorial anyway?

> `cd` command is also missing here, but being addressed in #931.

**Comment by shcheklein** [comment]
we might either delete that last section of the tutorial, or switch it indeed to the `example-get-started` like was suggested
