### ISSUE TITLE
remote-add: add a note about adding quotes around azure connection string

### ISSUE THREAD

**Issue by sijanmilan** [iterative/dvc.org#950]
DVC version 0.82.3, MacOS 10.14.6 installed via pip

In documentation example for Azure Remote Blob storage configuration: 
https://dvc.org/doc/command-reference/remote/add#supported-storage-types
```
dvc remote add myremote azure://my-container-name/path
dvc remote modify myremote connection_string my-connection-string --local
```
`--local` is specified at the end which will throw error `command not found: --local` 

update documentation so command is specified before the connection_string per command specification (https://dvc.org/doc/command-reference/remote/modify)

**Comment by shcheklein** [comment]
@sijanmilan sounds good! would be great if you can just edit the doc - there is a button on the right side screen "Edit on Github" and you can create a PR w/o in your browser :)
