### ISSUE TITLE
Custom header IDs mechanism breaks some pages

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#955]
Examples:

- https://dvc.org/doc/user-guide/running-dvc-on-windows
- https://dvc.org/doc/user-guide/external-dependencies

Error happens then header node have some children inside except the text.

In the case of `external-dependencies` error was caused by this header:

```
## Example: `import-url` command
```

Because `import-url` was rendered as a tag, incorrect id value was assigned for header in: https://github.com/iterative/dvc.org/blob/master/src/Documentation/Markdown/Markdown.js#L60-L65

**Comment by shcheklein** [comment]
@iAdramelk thanks for reporting this! will you take a look? if you don't have time, let's just disable the custom rendering, I'll fix the issue tomorrow. Should be something minor.

**Comment by iAdramelk** [comment]
@shcheklein fixing it ATM.
