### ISSUE TITLE
blog: DVC with Jupyter notebooks

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#96]

**Comment by efiop** [comment]
@jurasan

**Comment by efiop** [comment]
Hi @colllin ! 

 I see by the name of the notebook `train.ipynb`, that you are splitting your pipeline into separate steps, that you then plan to run using dvc. That is precisely what we usually recommend! You should be all set :tada:  Please don't hesitate to share your experience, we would really appreciate it. :slightly_smiling_face:

**Comment by mlisovyi** [comment]
Any progress on such example?

**Comment by colllin** [comment]
@mlisovyi I’ve been using Jupiter in a pipeline with a command like:
```
jupyter nbconvert Train.ipynb --clear-output --inplace --execute --ExecutePreprocessor.timeout=-1
```
This executes the notebook and overwrites it in-place, as if I had opened it in Jupyter and ran the entire notebook manually and saved it. I then commit the resulting notebook to git.  I also specify some outputs which are cached: a directory for model checkpoints and a directory for logs. For dependencies, I specify the notebook itself as well as a directory of supporting modules. 

I believe the initial command to set it up looked something like
```
dvc run -d Train.ipynb -d src/ -o checkpoints/ -o logs/ jupyter nbconvert Train.ipynb --clear-output --inplace --execute --ExecutePreprocessor.timeout=-1
```

You might also need to specify a name for the pipeline step somewhere in that command — I used `train.dvc`, which I can then execute using `dvc repro train.dvc`.

**Comment by jorgeorpinel** [comment]
Do we envision this as a regular part of our DVC user guide, or as a blog post? Cc WDYT @flippedcoder thanks

**Comment by jorgeorpinel** [comment]
> Cc WDYT @flippedcoder thanks

Cc @jendefig 

Also cc @dberenbaum — I think we discussed this topic at some point. Do you still have your DVC/Jupyter Notebook examples handy? Thanks

**Comment by jendefig** [comment]
I would think a best practices for migration would be good for the docs and blog post.  Showing different ways to do it in a series of blog posts?

**Comment by casperdcl** [comment]
Strongly would recommend taking a look at https://github.com/nteract/papermill :)

**Comment by jorgeorpinel** [comment]
Ping @jendefig 🙂

**Comment by jendefig** [comment]
@jorge Thanks! @flippedcoder is finishing up one on this now [here](https://github.com/iterative/dvc.org/pull/3624).  Not sure she is familiar with Papermill @casperdcl.  With what you know could you take a look and see if there are any significant advantages over the approach being used now?

**Comment by casperdcl** [comment]
[done](https://github.com/iterative/dvc.org/pull/3624#pullrequestreview-1068582996)

**Comment by jendefig** [comment]
> Does https://iterative.ai/blog/jupyter-notebook-dvc-pipeline close this? WDYT @dberenbaum @jendefig
> 
> Cc @RCdeWit is there an issue for the planned blog follow-up? (Getting to an actual pipeline)
> 
> Thanks

@jorgeorpinel I would think that until the follow-up one to the papermill one is done this isn't quite closed.  But plans for the next one are already in our backlog, so it won't be lost.

**Comment by shcheklein** [comment]
I think we can close this for now. No need to track it here as a separate issue.
