### ISSUE TITLE
cmd ref: double check example-get-started repo examples (tag names)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#961]
The example-get-started repo changed from 2 tags to 12 at some point, but we didn't update all the examples in cmd ref (or any doc) that use them. More context in https://github.com/iterative/dvc.org/pull/933#pullrequestreview-350597257

**Comment by shcheklein** [comment]
Looks like I was wrong, tags are still here https://github.com/iterative/example-get-started/releases?after=1-initialize . And example get started and all example should use them where appropriate.

**Comment by jorgeorpinel** [comment]
My bad. I thought they were gone because they don't come up in page 1 of https://github.com/iterative/example-get-started/tags
