### ISSUE TITLE
md: don't auto-link from headers

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#963]
For example currently an H2 title in the `dvc checkout` cmd ref has the following md code:

```markdown
## Automating `dvc checkout`
```

and looks like:

![image](https://user-images.githubusercontent.com/1477535/73575589-26edc800-443e-11ea-9acb-fe285ba10901.png)
https://dvc.org/doc/command-reference/checkout#automating-dvc-checkout

"dvc checkout" should not be linked in this case, as it's part of a header. It should just be rendered as `<code>` per normal md rules. Similar to:

![image](https://user-images.githubusercontent.com/1477535/73575794-8ea41300-443e-11ea-933b-e80321d7f5b4.png)
https://dvc.org/doc/user-guide/running-dvc-on-windows#enabling-paging-with-less

> Notice that in both cases the right side nav/ToC widget renders the plain text including the backquotes. Not the same issue but should those internal links remove special characters?

**Comment by jorgeorpinel** [comment]
> currently an H2 title in the dvc checkout cmd ref has the following md code

p.s. this will change soon, see https://github.com/iterative/dvc.org/pull/931/commits/ef4140104257e9a5f41968b9bf38e1adde5a6170.

**Comment by shcheklein** [comment]
@jorgeorpinel I think we want this to work for blog - check Heartbeats - we organize question with titles. Do you think this a big problem for docs? I think it's fine even if we have links in title? Please, feel free to reopen if it's critical.

**Comment by jorgeorpinel** [comment]
I´m only seeing actual md links in community gem posts

![image](https://user-images.githubusercontent.com/1477535/78943015-842a7900-7a80-11ea-85d9-8f6958a616d5.png)

Here I was referring to disabling auto linking `` `dvc command` `` strings.

**Comment by shcheklein** [comment]
Yup, you are right. Still, I think it's fine to auto-link if you use `inline code` even in titles. Why do you consider this as a problem?

**Comment by jorgeorpinel** [comment]
Nah, it was a very minor change request. We can just avoid useing backquotes in docs titles
