### ISSUE TITLE
cmd ref: review correctness of `dvc install` ref and notes in other docs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#968]
> Extracted from https://github.com/iterative/dvc.org/pull/931#pullrequestreview-351859026

> The installed Git hook automates reminding the user to run either dvc repro or dvc commit, as needed.
From https://dvc.org/doc/command-reference/install

Example note: "For convenience, a Git hook is available to remind you to `dvc repro`" (in repro cmd ref)
Comment: "It's not necessarily dvc repro though. It might be dvc commit or dvc checkout -f or manually remove files"

**Comment by jorgeorpinel** [comment]
More comments:

> sounds like I should try this and confirm that doc first

> that's should be easy enough to fix, it's two functions 5-10 lines of code each - https://github.com/iterative/dvc/blob/master/dvc/scm/git/__init__.py#L277 . The purpose of the initial doc was probably to clarify when it might be useful to see the status and fail (forgot to commit, repro, manually, may be even push (I would check this one), basically every situation status return non-zero exit code and what does it mean from a user perspective).

**Comment by shcheklein** [comment]
`that's should be easy enough to fix` -> that's should be easy enough to check`
