### ISSUE TITLE
fix broken links

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#974]
- [ ] fix dead links detected by #958
  + see `daily` workflow builds on https://circleci.com/gh/iterative/dvc.org (e.g. https://circleci.com/gh/iterative/dvc.org/2131) for an up-to-date list
- [ ] should warnings (status codes `0xx`, `3xx` etc) be counted as errors instead?

**Comment by jorgeorpinel** [comment]
The latest build (https://circleci.com/gh/iterative/dvc.org/2145) failed, but that's before #979. Will need to wait until the next daily run because I don't have permission to trigger it manually. Unless you happen to be around now or before the next run @shcheklein 🙂

**Comment by jorgeorpinel** [comment]
For now my local run of `yarn link-check | grep ERROR` on master found something like this:
```
 ERROR:404:http://ogp.me/ns
public/static/docs//user-guide/managing-external-data.md:public/static/docs//user-guide/troubleshooting.md:ERROR:1 failures
 ERROR:404:https://dvc.org/static/img/<filename>.gif
 ERROR:406:http://millionsongdataset.com/pages/getting-dataset/
 WARNING:000:https://dvc.org$
public/static/docs//use-cases/versioning-data-and-model-files.md:ERROR:1 failures
public/static/docs//command-reference/cache/dir.md:ERROR:1 failures
 ERROR:404:https://example.com/path/to/file
ERROR:1 failures
 ERROR:404:https://code.dvc.org/foo/bar
 ERROR:404:https://data.dvc.org/foo/bar
 ERROR:404:https://dvc.org/doc/command-reference/foo
 ERROR:404:https://dvc.org/foo
 ERROR:404:https://example.com/foo
 ERROR:404:https://example.com/foo/bar?baz
 ERROR:404:https://man.dvc.org/foo
 ERROR:404:https://remote.dvc.org/foo/bar
 ERROR:404:https://s3-us-east-2.amazonaws.com/dvc-public/code/foo/bar
 ERROR:404:https://s3-us-east-2.amazonaws.com/dvc-public/data/foo/bar
 ERROR:404:https://s3-us-east-2.amazonaws.com/dvc-public/remote/foo/bar
 ERROR:403:https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb/foo
 ERROR:403:https://s3-us-east-2.amazonaws.com/dvc-s3-repo/rpm/foo
 ERROR:404:https://www.dvc.org/foo
ERROR:1 failures
```
I'm not sure I understand the output as some of these are already in the exclude list, but I'm trying to solve all these in #978 (please review). Most of the new ones come from _server: refactor redirects so they're more declarative_ #943 and related PRs.

**Comment by jorgeorpinel** [comment]
After fixing those though, the command now crashes for me:
```
...
README.md:jest.config.js:OK
server.js:OK
OK
OK
OK
OK
OK
OK
OK
error Command failed with exit code 1.
```
🙁 

AND it's also happening on the PR 😕 https://circleci.com/gh/iterative/dvc.org/2152
