### ISSUE TITLE
broken links detection CI looks broken

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#977]
This run:

https://circleci.com/gh/iterative/dvc.org/2138

takes links from unrelated files?

**Comment by casperdcl** [comment]
It runs 8 processes concurrently (significant speedup) so output will be interleaved.

**Comment by casperdcl** [comment]
Not sure if you think it's worth spending time on fixing

**Comment by shcheklein** [comment]
The problem here is that it takes some links from the files that are not changed ... at least it looks like this. I'm totally fine with this multithreaded output :)

**Comment by casperdcl** [comment]
there's a daily cron job full check (all files) which takes a couple of min. For PRs though it'll only check the diff.

**Comment by shcheklein** [comment]
it looks like it is not daily in this link, this is PR one.

**Comment by jorgeorpinel** [comment]
I'm running into a similar problem. Please see https://github.com/iterative/dvc.org/pull/978#issuecomment-583208260 for a full report.

**Comment by jorgeorpinel** [comment]
- [ ] p.s. let's reevaluate #974 when this one is figured out.

**Comment by casperdcl** [comment]
ah you mean #976? Interesting. That's because master advanced after the PR branch was created.

So what was checked was [75e0482..b5e24c5](https://github.com/iterative/dvc.org/compare/75e0482..b5e24c5) rather than [ef74b9d..b5e24c5](https://github.com/iterative/dvc.org/compare/ef74b9d..b5e24c5).

Yes I can fix this...

**Comment by jorgeorpinel** [comment]
> ah you mean #976? 

Nope, I meant https://github.com/iterative/dvc.org/issues/974#issuecomment-583262421 🙂

**Comment by casperdcl** [comment]
> #976 is correct (referring to the OP link https://circleci.com/gh/iterative/dvc.org/2138)

**Comment by jorgeorpinel** [comment]
I think this issue is still unresolved, per https://github.com/iterative/dvc.org/issues/974#issuecomment-583273943

**Comment by casperdcl** [comment]
Can this be closed?

**Comment by shcheklein** [comment]
yep!
