### ISSUE TITLE
installation troubleshooting

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#983]
https://github.com/iterative/dvc/issues/2989 Might want to put it as a note in `installation` part of docs or maybe just put those into `troubleshooting` and then link it from `installation`.

Also https://github.com/iterative/dvc/issues/3281

**Comment by shcheklein** [comment]
@efiop we need way more info to make this actionable. any specific ideas what should we put, what environments are affected? Also, is it always an environment problem or DVC related sometimes?

**Comment by jorgeorpinel** [comment]
> On installation one gets the following message: ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. So there is an issue with the installed PyYAML version. dvc wants to install its own version, but can't.
Workaround: pip install --ignore-installed dvc.
> 
> Running dvc leads to the following message: AttributeError: module 'enum' has no attribute 'IntFlag'.
Workaround: pip uninstall enum34.

These workarounds could potentially break other packages though. We do already strongly recommend to install DVC as a requirement and with a package manager to avoid this kind of problem, I think.

**Comment by jorgeorpinel** [comment]
If it's more because of the latest https://github.com/iterative/dvc/issues/2989#issuecomment-583792544

> I ran into this issue as well while trying to install it in a docker container based off of jupyter/tensorflow-notebook. Since these are the official images and they are pretty ubiquitous to use as a base (and thus not know all the details of how it was set up) it would probably be worth either putting a note in the documentation...

Then maybe a Docker installation/troubleshooting section after all could be useful. Related: #811 (cc @mroutis), #850

**Comment by mroutis** [comment]
Not sure about the Docker section, @jorgeorpinel, this is more about the installation process in general, not specific to installing DVC inside a container.

> we need way more info to make this actionable

@shcheklein, I think @efiop was asking to introduce a section in Troubleshooting about Installation problems, where we put both, `enum34` and `PyYAML` problems with the respective work arounds.

**Comment by jorgeorpinel** [comment]
I'm not convinced :P the problems described in that issue are Python environment-related more than DVC installation-related. In the context of the TensorFlow Docker images it makes more sense to consider adding the notes but otherwise no. So if it's about Py/env not worth a docs section I think. If it's about TF/docker maybe.

**Comment by efiop** [comment]
@jorgeorpinel Even though those are not dvc-s fault, those are issues that people often encounter while installing dvc, so I think it is worth mentioning them there. Here is another one, btw: https://github.com/iterative/dvc/issues/3281 , @andronovhopf has run into it as well.

**Comment by jorgeorpinel** [comment]
This seems stale so we're closing but please feel free to reopen if there are specific common problems with installation still that we can add to https://dvc.org/doc/user-guide/troubleshooting or to a troubleshooting section in https://dvc.org/doc/install cc @dberenbaum thanks
