### ISSUE TITLE
community: pending issues

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#996]
> Continued from https://github.com/iterative/dvc.org/pull/874#issuecomment-585459258

Let's use this issue to list all pending issues @shcheklein @SvetaGr @andronovhopf

**Comment by jorgeorpinel** [comment]
My 2 pending Qs:
- Is removing the GitHub link from the top nav a good idea?
- The **Be an Ambassador** block may need more emphasis, maybe a special color and/or being on top of its section.

**Copy edits:**

https://github.com/iterative/dvc.org/blob/eb190befd7e7bd0ffe5d7e9c7c630c2a6df2d101/src/components/Community/data.json#L10
`DVC is 100% open source. We welcome contributions to our code and docs.`

https://github.com/iterative/dvc.org/blob/eb190befd7e7bd0ffe5d7e9c7c630c2a6df2d101/src/components/Community/data.json#L15
Learn more about DVC and meet us in person! We&apos;re appearing at conferences, meetups, and talks around the world.

https://github.com/iterative/dvc.org/blob/eb190befd7e7bd0ffe5d7e9c7c630c2a6df2d101/src/components/Community/data.json#L20
`Our community is a place for beginners and pros alike to learn best practices for data science and engineering. Check out our docs, news from the community, recommended reads, and more.`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/data.json#L33
`Reproducible walkthroughs on advanced topics`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/data.json#L38
`Step-by-step introduction into basic DVC features`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/data.json#L43
`See what&apos;s new in DVC.`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/Contribute/index.js#L49
`Let&apos;s build something great together. Become a DVC contributor!`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/Contribute/index.js#L67
`We&apos;re always interested in guest writers for our blog. If you have something to share, please reach out!`

https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/Contribute/index.js#L106
`Get perks and benefits for contributing to the code base, writing blog posts, or hosting meetups.`

**Comment by shcheklein** [comment]
@SvetaGr @andronovhopf could you please a list of copy edits please, that we missed during the merge/release?

**Comment by andronovhopf** [comment]
Agree with @jorgeorpinel on all of the above, think those are pretty comprehensive suggestions. Just a few more:

1. https://github.com/iterative/dvc.org/blob/c32e687986ad94e0998f5e6f0ae1f90e0070ba52/src/components/Community/data.json#L38
I like @jorgeorpinel's suggestion but want to change "into"  -> "to". for grammar So it will be 
`Step-by-step introduction to basic DVC features`

2. Under the "Learn" header, it says, "Every month we are sharing here our news, findings, interesting reads, community takeaways, and everything along the way.". Let's change this to
```There are many ways to learn about DVC: check out our documentation, our blogs and monthly Heartbeats, and articles and tutorials written by users.```

3. Under the "Community" header, it says, "Ask questions, find answers, share your ideas and connect with DVC community." Let's change this to:
```Ask questions, find answers, and connect with the DVC community.```

**Comment by shcheklein** [comment]
@SvetaGr did you have anything else in mind or it's good to go?

**Comment by jorgeorpinel** [comment]
Addressing everything in #1012.
