### ISSUE TITLE
api: document Repo object?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#998]
Extracted from https://github.com/iterative/dvc.org/pull/908#pullrequestreview-348450957

> we have already three different APIs - dvc.api + summon (should we move summon to another lib @dmpetrov @Suor ?), repo API (mirrors CLI). We probably should introduce sections right away.

This would probably also imply to review the docstrings in the corresponding module(s) (related: https://github.com/iterative/dvc/issues/3176).

**Comment by jorgeorpinel** [comment]
Hi @shcheklein, how do we feel about this one? I don't think there's been a huge need to doc the Repo "API" so far so should we close this? Thanks

**Comment by shcheklein** [comment]
Yes, Repo itself is not ready and not officially released.
